### ISSUE TITLE
Session metrics are decreasing

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#5088] opened 2021-01-11 11:05 UTC
# Description #
----------
Metrics with following definition are decreasing in one module.

```
<metadata>
      <tags>
        <tag>
          <name>module</name>
          <value>%s</value>
        </tag>
      </tags>
      <name>session.module.active.count</name>
      <mbean>amx:pp=/mon/server-mon[$SERVER_NAME],type=session-mon,name=cis-web-ui/%s/server/activesessionscurrent#current</mbean>
      <type>gauge</type>
      <unit>none</unit>
      <displayName>Count of active sessions</displayName>
      <description>The total of active sessions</description>
    </metadata>
```

## Expected Outcome

Gauge to be only positive.

## Current Outcome
![Snímek obrazovky pořízený 2021-01-11 11-24-33](https://user-images.githubusercontent.com/6689451/104172560-c5332d80-5404-11eb-9abf-1b631b366e00.png)

## Environment ##

- **Payara Version**: 5.2020.7
- **Edition**: Full 
- **JDK Version**: OpenJDK 11 
- **Operating System**: RedHat

**Comment by AlanRoth** [comment] 2021-01-11 16:54
Hi @sgflt, can you provide a more clear reproducer? Is this just in the default payara metrics application? Thank you.

**Comment by sgflt** [comment] 2021-01-12 08:25
Hi @AlanRoth , I need to collect more data. Yes, it is default Payara's implementation configured via metrics.xml.

**Comment by sgflt** [comment] 2021-01-12 12:17
Found hint in code:

```
// PAYARA-486 & PAYARA-1224 Correct the incorrect incrementation - needs further looking at
```

**Comment by sgflt** [comment] 2021-01-12 12:29
Method `sessionDestroyedEvent` is caled at least 20 times when hitting F5 on specific page.

**Comment by sgflt** [comment] 2021-01-12 15:22
FlashLightProbe#invokerList contains 36 identical listeners.

**Comment by sgflt** [comment] 2021-01-12 15:53
It seems that each war in ear registers own listener hook, but event does not care about war locality and executes all attached listeners from whole ear.

**Comment by sgflt** [comment] 2021-01-12 16:27
Fix seems to be easy... crafting a new code.

**Comment by AlanRoth** [comment] 2021-01-12 16:32
Hi @sgflt, thanks for keeping me updated, feel free to make a PR when you are ready. Thank you.

**Comment by sgflt** [comment] 2021-01-12 16:44
And fix is already present as isValidEvent method, but I am looking at a wrong place.

**Comment by sgflt** [comment] 2021-01-12 17:27
I have Examined positive values and they do not seem to be correct too. Some event happened and all numbers are going mad.

![Snímek obrazovky pořízený 2021-01-12 18-25-26](https://user-images.githubusercontent.com/6689451/104349898-d44cd500-5503-11eb-9a9c-b4021bf4ba75.png)

**Comment by AlanRoth** [comment] 2021-01-15 10:39
Hi @sgflt, could you provide a sample app so I can quickly verify this issue? Thank you.

**Comment by sgflt** [comment] 2021-01-17 09:47
Demo app located at https://github.com/sgflt/payara-test-case should be sufficient. I though I know ehere the problem is, but after few hours I got nothing. The cause is well hidden and I dont know what order of steps can cause this behavior. I plan to add metrics for pasivation and activation of sessions in hope it might be related.

**Comment by AlanRoth** [comment] 2021-03-08 10:51
Hi @sgflt, I'm not sure how to use your Demo app to reproduce your issue. Could you provide some steps?

**Comment by sgflt** [comment] 2021-03-11 10:38
Hi @AlanRoth steps for deplyoment and basic clicking are reusable from https://github.com/payara/Payara/issues/3907. I vill prepare configuration of metrics.xml to that repo.

**Comment by sgflt** [comment] 2021-03-11 14:41
metrics.xml pushed right now

**Comment by sgflt** [comment] 2021-03-26 08:41
New data afted added pasivated and activated metrics.

![Snímek obrazovky pořízený 2021-03-26 09-36-27](https://user-images.githubusercontent.com/6689451/112604946-0be6d000-8e17-11eb-9f07-c54ed6095be7.png)

![Snímek obrazovky pořízený 2021-03-26 09-34-39](https://user-images.githubusercontent.com/6689451/112604970-10ab8400-8e17-11eb-9734-6d361f151ac6.png)

![Snímek obrazovky pořízený 2021-03-26 09-35-25](https://user-images.githubusercontent.com/6689451/112604983-15703800-8e17-11eb-87db-fa60a091e9db.png)

**Comment by AlanRoth** [comment] 2023-06-06 15:30
Hi @sgflt,

I must apologise as this issue has fallen through the cracks and has not recieved any attention.

I will close this issue at the moment, however I encourage you - if the issue is still relevant - to raise a new issue and a member of our team will handle it.

Thank you,
Alan

**Closed by AlanRoth** 2023-06-06 15:30 UTC
Labels: Type: Bug, Status: Open
