### ISSUE TITLE
Bug Report:  Payara 5  fail in Centos 8 with Java 11

### ISSUE THREAD

**Issue by joedayz** [payara/Payara#5376] opened 2021-08-09 12:31 UTC
# Description #
----------

I installed Payara 5 + Java 11 in Centos 8.
It was working from installation until now (around 3 months). Everything was ok.

## Expected Outcome ##

I followed it guide: https://soportetecnicox24.com/como-instalar-payar-5-en-centos-8/

## Current Outcome ##

After restart I am getting it error

[legallmorpheusadmin@legall-morpheus config]$ systemctl status payara.service
● payara.service - Payara Server v5.2
   Loaded: loaded (/usr/lib/systemd/system/payara.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2021-08-09 12:04:13 UTC; 5min ago
  Process: 2001455 ExecStart=/usr/bin/java -jar /opt/payara5/glassfish/lib/client/appserver-cli.jar start-domain (code=exited, status=1/FAILURE)
 Main PID: 176200 (code=exited, status=10)

Aug 09 12:04:13 legall-morpheus java[2001455]: Waiting for domain1 to start .Error starting domain domain1.
Aug 09 12:04:13 legall-morpheus java[2001455]: The server exited prematurely with exit code 1.
Aug 09 12:04:13 legall-morpheus java[2001455]: Before it died, it produced the following output:
Aug 09 12:04:13 legall-morpheus java[2001455]: Unrecognized option: -servidor
Aug 09 12:04:13 legall-morpheus java[2001455]: Error: Could not create the Java Virtual Machine.
Aug 09 12:04:13 legall-morpheus java[2001455]: Error: A fatal exception has occurred. Program will exit.
Aug 09 12:04:13 legall-morpheus java[2001455]: Command start-domain failed.
Aug 09 12:04:13 legall-morpheus systemd[1]: payara.service: Control process exited, code=exited status=1
Aug 09 12:04:13 legall-morpheus systemd[1]: payara.service: Failed with result 'exit-code'.
Aug 09 12:04:13 legall-morpheus systemd[1]: Failed to start Payara Server v5.2.

## Steps to reproduce ## 

I have the same error if I execute from /opt/payara5/glassfish/bin:

[legallmorpheusadmin@legall-morpheus bin]$ ./asadmin start-domain
Waiting for domain1 to start .Error starting domain domain1.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

Unrecognized option: -servidor
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Command start-domain failed.

## Environment ##

- **Distribution**:
Thank you for downloading Payara Server 5.2020.7!

- **JDK Version**: 
[legallmorpheusadmin@legall-morpheus bin]$ java -version
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1-LTS, mixed mode, sharing)

- **Operating System**: 
[legallmorpheusadmin@legall-morpheus bin]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

**Comment by aubi** [comment] 2021-08-10 08:00
Hello joedayz,
Somehow, you probably changed JVM option from "-server" to "-servidor". Could you look into domain.xml and replace it back?
Petr

**Comment by AlanRoth** [comment] 2021-08-10 08:10
Hi @joedayz,

As @aubi has suggested, there seems to be a typo in your domain.xml causing it to not start correctly. 

I will also be closing this issue due to the fact it has been raised for a old version, 5.2020.7, and the issue not being caused by a bug.

Feel free to update us to let us know if @aubi's suggestion fixed your issue, or if you believe this is a genuine bug - feel free to reopen the issue after reproducing it on the latest Payara Community version, 5.2021.5.

Thank you for your understanding,
Alan

**Closed by AlanRoth** 2021-08-10 08:10 UTC
Labels: Type: Bug, Status: Open
