### ISSUE TITLE
Remote clients cannot discover payara 5 EJBs due to spurious java.io.NotSerializableException/FISH-6807

### ISSUE THREAD

**Issue by Blavo** [payara/Payara#5973] opened 2022-10-06 06:04 UTC
### Brief Summary

Remote clients cannot discover payara 5 EJBs using the list() method of InitialContext to list the remote server's 'java:global' naming context due to a java.io.NotSerializableException that names class org.glassfish.kernel.javaee.MEJBNamingObjectProxy.

### Expected Outcome

Running list() of 'java:global' locally on the server hosting the target EJBs returns a naming enumeration with just two entries, both sub-contexts: 'APILoaderServer' (sub context for the server's EJBs) and 'mejb' (presumably a sub-context for m-beans). This is the result that the remote call above should have obtained.

So the expected behaviour is the return of a naming enumeration of two NameClassPairs, each referencing (by class name) a sub-context.

### Current Outcome

The current outcome is instead a java.io.NotSerializableException naming class org.glassfish.kernel.javaee.MEJBNamingObjectProxy.

What fails is the naming context list() method. This is the method used to discover remotely-invocable services, such as EJBs, on a remote server. These services are listed under a well-known context ('java:global'). In my case I am looking for remotely-invocable EJBs on a remote payara server. The remote server binds the EJBs under a sub-context of java:global where the sub context is remote-server-dependent and generally unknown to the caller. So I have to list the java:global context to discover that sub-context. (The sub-context is usually the deployment name of the application containing the EJBs; multiple such applications would result in multiple sub-contexts of 'java:global'.)

My attempt to list the java:global context gives a java.io.NotSerializableException naming class org.glassfish.kernel.javaee.MEJBNamingObjectProxy.

The call signature for list() is 'NamingEnumeration list(String name) throws NamingException'. All elements of the signature, recursively, are serializable. So a correct response to the list() call is incapable of giving a serialisation exception. So there is definitely something wrong with the implementation of list() in payara (and glassfish 5 and glassfish 6).

Part of the original response to https://github.com/eclipse-ee4j/glassfish/issues/17220 is that the cause may be that the sub-context being listed contains JNDI entries that aren't serializable. Such entries are allowed (though pointless - see below). In fact it doesn't matter whether the elements of the sub-context are serializable or not because only their class names are being returned in a list() call. Serialisability doesn't come into play until the result of a list() call is used to make a lookup() call to obtain an instance of the bound class type.

The actual cause of the list() problem appears to be that the 'mejb' sub-context of 'java:global' contains a binding to a non-serializable class (org.glassfish.kernel.javaee.MEJBNamingObjectProxy) and that, for reasons best known to the implementor, the implementation of list() in payara/glassfish attempts to lookup() that entry, gets a CORBA exception because the bound class is not serializable, and returns the CORBA error to the caller as the list() result. Two problems here. There is no need to lookup() anything to provide the correct result to the list() call. So the CORBA error is spurious. Second the 'mejb' sub-context shouldn't contain any bound entries that aren't serialisable. My understanding is that 'java:global' is a well-known naming context under which JEE containers list their remotely-invocable services. There is no point listing a non-serialisable entry in the 'java:global' naming context because it can never be remotely invoked because the bound object won't reach the intending invoker because it is not serializable.

The output and stack trace from including the code in the Reproducer in the initialisation code of an application on the target server follows:

  Here 1a and listing with no properties|#]
    VirtualAirControlSystem bound to com.sun.enterprise.naming.impl.TransientContext|#]
    mejb bound to com.sun.enterprise.naming.impl.TransientContext|#]
  Here 1b and listing with host and port properties|#]
  Cannot find the resource bundle for the name com.sun.logging.enterprise.system for class org.glassfish.enterprise.iiop.api.ORBLazyServiceInitializer using fish.payara.server.internal.orb.connector [279]|#]
  javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={org.omg.CORBA.ORBInitialPort=3700, java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, org.omg.CORBA.ORBInitialHost=127.0.0.1, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is java.rmi.MarshalException: CORBA BAD_PARAM 1398079494 Maybe; nested exception is: 
	java.io.NotSerializableException: WARNING: 00100006: Class org.glassfish.kernel.javaee.MEJBNamingObjectProxy is not Serializable]
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:518)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
	at com.sun.enterprise.naming.impl.SerialContext.list(SerialContext.java:791)
	at javax.naming.InitialContext.list(InitialContext.java:461)
	at javax.naming.InitialContext.list(InitialContext.java:461)
	at q.demoApplications.VirtualAir.server.lifeCycle.Initialise.initialise(Initialise.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1022)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:978)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:978)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:418)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:381)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:2071)
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:529)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:81)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:687)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:421)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:159)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:171)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:292)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:361)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:623)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:597)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:604)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:256)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:166)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:201)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.rmi.MarshalException: CORBA BAD_PARAM 1398079494 Maybe; nested exception is: 
	java.io.NotSerializableException: WARNING: 00100006: Class org.glassfish.kernel.javaee.MEJBNamingObjectProxy is not Serializable
	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.mapSystemException(Util.java:301)
	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.wrapException(Util.java:696)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:246)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:140)
	at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
	at com.sun.enterprise.naming.impl._SerialContextProvider_DynamicStub.lookup(com/sun/enterprise/naming/impl/_SerialContextProvider_DynamicStub.java)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:483)
	... 81 more
Caused by: java.io.NotSerializableException: WARNING: 00100006: Class org.glassfish.kernel.javaee.MEJBNamingObjectProxy is not Serializable
	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.mapSystemException(Util.java:293)
	... 87 more
Caused by: org.omg.CORBA.BAD_PARAM: WARNING: 00100006: Class org.glassfish.kernel.javaee.MEJBNamingObjectProxy is not Serializable  vmcid: SUN  minor code: 6 completed: Maybe
	at com.sun.proxy.$Proxy328.notSerializable(Unknown Source)
	at com.sun.corba.ee.impl.misc.ORBUtility.throwNotSerializableForCorba(ORBUtility.java:773)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_abstract_interface(CDROutputStream_1_0.java:556)
	at com.sun.corba.ee.impl.encoding.CDROutputObject.write_abstract_interface(CDROutputObject.java:523)
	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.writeAbstractObject(Util.java:493)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.writeObjectOverride(IIOPOutputStream.java:167)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1793)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.invokeObjectWriter(IIOPOutputStream.java:640)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.outputObject(IIOPOutputStream.java:607)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.simpleWriteObject(IIOPOutputStream.java:187)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValueInternal(ValueHandlerImpl.java:238)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValueWithVersion(ValueHandlerImpl.java:219)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValue(ValueHandlerImpl.java:179)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.callWriteValue(CDROutputStream_1_0.java:711)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.writeRMIIIOPValueType(CDROutputStream_1_0.java:696)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:821)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:834)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:565)
	at com.sun.corba.ee.impl.encoding.CDROutputObject.write_value(CDROutputObject.java:506)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.writeObjectField(IIOPOutputStream.java:766)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.outputClassFields(IIOPOutputStream.java:837)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.defaultWriteObjectDelegate(IIOPOutputStream.java:236)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.outputObject(IIOPOutputStream.java:609)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.simpleWriteObject(IIOPOutputStream.java:187)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValueInternal(ValueHandlerImpl.java:238)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValueWithVersion(ValueHandlerImpl.java:219)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValue(ValueHandlerImpl.java:179)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.callWriteValue(CDROutputStream_1_0.java:711)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.writeRMIIIOPValueType(CDROutputStream_1_0.java:696)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:821)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:834)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_abstract_interface(CDROutputStream_1_0.java:551)
	at com.sun.corba.ee.impl.encoding.CDROutputObject.write_abstract_interface(CDROutputObject.java:523)
	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.writeAbstractObject(Util.java:493)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.writeObjectOverride(IIOPOutputStream.java:167)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1793)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.invokeObjectWriter(IIOPOutputStream.java:640)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.outputObject(IIOPOutputStream.java:607)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.simpleWriteObject(IIOPOutputStream.java:187)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValueInternal(ValueHandlerImpl.java:238)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValueWithVersion(ValueHandlerImpl.java:219)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValue(ValueHandlerImpl.java:179)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.callWriteValue(CDROutputStream_1_0.java:711)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.writeRMIIIOPValueType(CDROutputStream_1_0.java:696)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:821)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:834)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:565)
	at com.sun.corba.ee.impl.encoding.CDROutputObject.write_value(CDROutputObject.java:506)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.writeObjectField(IIOPOutputStream.java:766)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.outputClassFields(IIOPOutputStream.java:837)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.defaultWriteObjectDelegate(IIOPOutputStream.java:236)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.outputObject(IIOPOutputStream.java:609)
	at com.sun.corba.ee.impl.io.IIOPOutputStream.simpleWriteObject(IIOPOutputStream.java:187)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValueInternal(ValueHandlerImpl.java:238)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValueWithVersion(ValueHandlerImpl.java:219)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.writeValue(ValueHandlerImpl.java:179)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.callWriteValue(CDROutputStream_1_0.java:711)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.writeRMIIIOPValueType(CDROutputStream_1_0.java:696)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:821)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(CDROutputStream_1_0.java:834)
	at com.sun.corba.ee.impl.encoding.CDROutputObject.write_value(CDROutputObject.java:500)
	at com.sun.corba.ee.impl.copyobject.ORBStreamObjectCopierImpl.copy(ORBStreamObjectCopierImpl.java:73)
	at org.glassfish.pfl.dynamic.copyobject.impl.FallbackObjectCopierImpl.copy(FallbackObjectCopierImpl.java:34)
	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.copyObject(Util.java:771)
	at com.sun.corba.ee.impl.presentation.rmi.DynamicMethodMarshallerImpl.copyResult(DynamicMethodMarshallerImpl.java:472)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:231)
	... 85 more
|#]
  Failed to list entries because of javax.naming.CommunicationException with messsage Communication exception for SerialContext[myEnv={org.omg.CORBA.ORBInitialPort=3700, java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, org.omg.CORBA.ORBInitialHost=127.0.0.1, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}|#]

### Reproducer

The problem is easily reproducible (in fact unavoidable) when running the list() of 'java:global' against the target server from a remote client.

The problem is also reproducible when the list() is run locally on the target server but where values are provided in the initial context for properties org.omg.CORBA.ORBInitialHost (127.0.0.1) and org.omg.CORBA.ORBInitialPort (3700). (Specifying these appears to force the list() response to go through a Stream (requiring serialisation) rather than via a pipe (which doesn't)).

To reproduce run the following code on any payara server that has EJBs defined (though the error will probably occur without EJBs defined since it occurs in the 'mejb' sub context which is probably present with or without EJBs). Adding the code to the initialisation code of an application that has the EJBs will work - it doesn't need to be invoked via a transaction.

        System.out.println("Here 1a and listing with no properties; this should work");
        Properties contextProperties = new Properties();
        InitialContext namingContext1 = null;
        try {
            namingContext1 = new InitialContext(contextProperties);
        } catch (Throwable e) {
            e.printStackTrace();
            System.out.println("Failed to set up context because of " + e.getClass().getName()
                    + " with messsage " + e.getMessage());
            System.exit(1);
        }

        NamingEnumeration<NameClassPair> result1 = null;
        try {
            result1 = namingContext1.list("java:global");
            while (result1.hasMore()) {
                NameClassPair entry = result1.next();
                System.out.println("  " + entry.getName() + " bound to " + entry.getClassName());
            }
        } catch (Throwable e) {
            e.printStackTrace();
            System.out.println("Failed to list entries because of " + e.getClass().getName()
                    + " with messsage " + e.getMessage());
            System.exit(1);
        }

        System.out.println("Here 1b and listing with host and port properties; this should fail");
        Properties props2 = new Properties();
        props2.put("org.omg.CORBA.ORBInitialHost", "127.0.0.1");    // Enough to force serialisation of result
        props2.put("org.omg.CORBA.ORBInitialPort", "3700");         // Enough to force serialisation of result
        InitialContext namingContext2 = null;
        try {
            namingContext2 = new InitialContext(props2);
        } catch (Throwable e) {
            System.out.println("Failed to set up context because of " + e.getClass().getName()
                    + " with messsage " + e.getMessage());
            System.exit(1);
        }
        NamingEnumeration<NameClassPair> result2 = null;
        try {
            result2 = namingContext2.list("java:global");
            while (result2.hasMore()) {
                NameClassPair entry = result2.next();
                System.out.println("  " + entry.getName() + " bound to " + entry.getClassName());
            }
        } catch (Throwable e) {
            e.printStackTrace();
            System.out.println("Failed to list entries because of " + e.getClass().getName()
                    + " with messsage " + e.getMessage());;
            System.exit(1);
        }

### Operating System

Mac OS 12.4 (Monterey) also Mac OS 10.15.2 (Catalina)

### JDK Version

Oracle JDK 1.8.0_202 (and others)

### Payara Distribution

Payara Server Full Profile

**Comment by lprimak** [comment] 2022-10-06 06:25
OMG that's a can of worms. I would suggest trying to get a PR through, or becoming an Enterprise customer on this issue, it's pretty esoteric.
I spent weeks debugging that stuff and still don't completely understand how it works

**Comment by Blavo** [comment] 2022-10-06 06:44
G’day,

Another ‘fix’ would be to patch the code to test specifically for an an attempt to lookup MEJBNamingObjectProxy and not do it. (I believe MEJBNamingObjectProxy goes away shortly so the code wouldn’t be long).

Or the code could catch any NonSerializable exception thrown by any lookup() call and keep going. No point in returning MEJBNamingObjectProxy or anything else that isn’t serialisable to a remote list() call because the remote user won’t be able to do a lookup() on them to get them.



Ian Blavins
0408 848 548

**Comment by smillidge** [comment] 2022-10-06 18:01
See https://github.com/eclipse-ee4j/glassfish/issues/23309

**Comment by Blavo** [comment] 2022-10-06 22:36
G'day,

I don't need to see https://github.com/eclipse-ee4j/glassfish/issues/23309 - I wrote it. I've been asked, and expect to be asked again, whether it can be closed because it is old and nobody is working on it. Reading around a bit I get the impression that payara bugs are more likely to get fixed than glassfish bugs so I've moved the bug here. I have developed a work around but it is ugly and needs the user of what I am making to apply it to their server which is a bit of an ask. So I'd like to see it fixed.

**Comment by lprimak** [comment] 2022-10-06 22:48
If you have a PR it’ll greatly increase the chance chances of being fixed.

**Comment by smillidge** [comment] 2022-10-07 09:05
NP. I added just for reference on the issue for others in the team.

**Comment by Blavo** [comment] 2022-10-11 09:00
G’day,

Actually I doubt it is that difficult.

I’ve just added the stack trace. Line 6 of the stack trace is my code (q.demoApplications…) so there are only 5 calls to follow. The fourth is a lookup() call and that is likely the problem since the result of a lookup of MEJBNamingObjectProxy will not serialise. 

I think the fix is to stop the code doing a lookup() of anything that is below a sub context of java:global.


Ian Blavins
0408 848 548

**Comment by shub8968** [comment] 2022-11-25 10:08
Hi @Blavo,

I have escalated the issue to the Platform development team with `FISH-6807`. The priority of this issue is marked as trivial, If you are looking for an immediate fix for it, kindly consider using Payara Enterprise.

**Comment by Blavo** [comment] 2022-11-25 21:20
G’day,

Why trivial? A feature is completely broken by the addition of a later feature (which is soon itself to be withdrawn). The broken feature is the discovery of server services offered as remote EJBs. Discovery of server services is considered normal modern practice. This is the kind of feature used in the development of extensibility tools, which is how I am (attempting to) use it. Unless EJBs themselves are now out of favour I would have thought the ability to discover them was of more than trivial significance. 

Since it was the inclusion of org.glassfish.kernel.javaee.MEJBNamingObjectProxy in the java:global JNDI name space that caused the problem I would have thought it reasonable to ask the instigator of that change to fix the problem, if only by changing the name space in which their object proxy is listed. (There is no point in including the object proxy is a remotely-listable name space anyway, as being non-serialisable, it cannot be downloaded after discovery even if it didn’t break the discovery process).


Ian Blavins
0408 848 548

**Comment by kalinchan** [comment] 2023-07-12 10:03
Closed as duplicate of https://github.com/payara/Payara/issues/6330 (and Payara 5 is no longer supported)

**Closed by kalinchan** 2023-07-12 10:03 UTC
Labels: Status: Accepted, Type: Bug
