### ISSUE TITLE
Payara 5 beta2 does not start with Java 9

### ISSUE THREAD

**Issue by seldon3000** [payara/Payara#2296] opened 2018-01-19 10:10 UTC
# Description #
---------------

Payara 5 does not start with Java 9 on Ubuntu 17.10

## Expected Outcome

Payara 5 starts. 

## Current Outcome

The start ends immediately with the following error `-Xbootclasspath/p is no longer a supported option.`.

## Steps to reproduce (Only for bug reports) 

```
bin/asadmin start-domain --debug payaradomain
JVM failed to start: com.sun.enterprise.admin.launcher.GFLauncherException: The server exited prematurely with exit code 1.
Before it died, it produced the following output:

-Xbootclasspath/p is no longer a supported option.

Command start-domain failed.
```

The file `server.log` only contains the start command.

The server starts, if I replace `-Xbootclasspath/p` by `-Xbootclasspath/a` in the `domain.xml` of the payaradomain. Maybe this could fix this bug? Is it important to prepend to the bootstrap class path?

According to [Java 9 Release notes](http://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html) the options `-Xbootclasspath` and `-Xbootclasspath/p` have been removed from Java 9.

## Environment ##

- **Payara Version**: payara-5.Beta2-20180118.004922-27
- **Edition**: Full
- **JDK Version**: Oracle JDK 9.0.4
- **Operating System**: Ubuntu 17.10
- **Database**: none

**Comment by michaelranaldo** [comment] 2018-01-19 10:20
Hi @seldon3000 ,

Thanks for reporting this. The payaradomain was intended for JDK 8 but as you have seen there's issues with JDK 9 deprecating some classpath arguments.

I've created internal issue PAYARA-2416

**Comment by smillidge** [comment] 2018-01-19 16:03
We don't officially support JDK9 as it is not an LTS release. It is not possible to support both JDK versions in a single domain version.

**Comment by ratcashdev** [comment] 2018-03-27 19:33
So how can we get HTTP2 support working with Payara 5? With 5.181 (release) not even asadmin works on jdk9.

**Comment by lprimak** [comment] 2018-03-27 19:46
We are working on JDK-specific JVM options for the next release.
For now, you need to modify config/domain.xml manually to change ```<jvm-options>``` elements to the ones that are compatible with the JDK you are using

**Comment by ratcashdev** [comment] 2018-03-27 20:04
I see. But that won't help with asadmin, would it? the `asadmin.bat` seems not to use any of the config xmls.

**Comment by lprimak** [comment] 2018-03-27 20:20
Might have to modify the asadmin script with correct JVM options too, but I am not sure what the issue is with asadmin (I haven't seen any)

**Comment by lprimak** [comment] 2018-03-27 20:20
Also, HTTP/2 works on JDK 8 with Payara 5

**Comment by ratcashdev** [comment] 2018-03-28 10:46
did not know that, thanks for the quick help.

**Comment by ratcashdev** [comment] 2018-04-17 12:32
@lprimak  Hi Lenny,
> We are working on JDK-specific JVM options for the next release.
Has this already been done? If not, and you wound't mind providing some guidance how to do it (e.g. 1 domain for JDK8, another for JDK9, or doing some JVM Options filtering in the Config) I may have some time to start working on it a do a PR.

**Comment by pdurbin** [comment] 2019-03-31 11:41
I just upvoted https://stackoverflow.com/questions/53762114/payara-5-compatibility-with-java-9/55433340#55433340 where I learned from @arjantijms that https://github.com/payara/Payara/tree/JDK11 exists and that we are all welcome to try it out. Thanks!

**Comment by smillidge** [comment] 2019-04-25 20:49
Closing as Payara 5 on JDK 11 is a bigger piece of work and is scheduled

**Comment by pdurbin** [comment] 2019-04-26 12:14
@smillidge hi! I'm confused. I have been tracking this issue as the one for Java 11 support for Payara. Now that you've closed this issue, is there a different one I should be tracking? Thanks!

**Comment by smillidge** [comment] 2019-04-26 14:39
OK JDK 11 work is currently in the JDK 11 branch and tech preview is schedule for the 192 release.
I'll reopen this one and milestone it that way you can still track it.

**Comment by smillidge** [comment] 2019-05-29 16:54
JDK 11 Tech Preview support has been released.

**Closed by smillidge** 2019-05-29 16:54 UTC
Labels: 2:WithDev, c:Enhancement, v:JDK-9, v:Payara-5
