### ISSUE TITLE
The resource type of a JDBC connection pool can't be changed in the second step of creation

### ISSUE THREAD

**Issue by krichter722** [payara/Payara#2977] opened 2018-07-23 04:21 UTC
# Description #
----------

Creating a JDBC connection pool happens in two step after clicking the "New" button. In the first the name and resource type are specified and in the second driver and resource classes and connection attributes. In the first step the specification of resource type is not enforce and in the second it's not editable. The error message

```
Constraints for this JdbcConnectionPool configuration have been violated: on property [ resType ] violation reason [ {javax.validation.constraints.Pattern.message} ]
```

is not very comprehensive (it's possible to understand what's wrong, but there's no reason to keep the message in a less comprehensive form than possible). It should also contain a hint that it's necessary to go pack in the wizard to change the resource type.

## Expected Outcome

I'm assuming that the separation in two steps provides an advantage in developing and maintaining the application, otherwise the two steps should be removed. It's of course more comfortable for the user to have all information on one eventually dynamic page rather than being forced to go back in the wizard. In my opinion this is a UX anti-pattern.

The error message should explain that no values has been selected in the resource type combo box on the first page of the creation wizard.

## Current Outcome

The above error message is shown.

![screenshot-localhost 4848-2018-07-23-05-46-00](https://user-images.githubusercontent.com/4369372/43057166-cbff841a-8e40-11e8-80b9-3abe60ee10ec.png)

## Steps to reproduce (Only for bug reports) 

Start the domain `./asadmin start-domain domain1` and go to the admin web console.

I couldn't test the latest 5.183-SNAPSHOT because it doesn't start (I need to investigate and eventually file a different report).

### Samples

---

## Context (Optional)

---

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**: OpenJDK 8
- **Operating System**: Ubuntu 18.04
- **Database**: ---

This is an enhancement request for make the use of the software more intuitive, I'm not seeking for support.

**Comment by Ykus** [comment] 2018-09-23 13:35
Hi,

resource type value is not required in all cases. Resource type has this allowed values javax.sql.DataSource, javax.sql.XADataSource, javax.sql.ConnectionPoolDatasource, or java.sql.Driver.
In this case you describe above, is the problem in empty string coming from the form instead null value.
Because of an empty string, error "Constraints for this JdbcConnectionPool configuration have been violated: on property [ resType ] violation reason [ {javax.validation.constraints.Pattern.message} ]" raise.

I fixed this problem and created a pull request.

**Comment by fturizo** [comment] 2020-02-06 18:17
Due to how old this request is and that the requester fell unresponsive, we'll close this issue. Feel free to raise a new issue with a clear detailed reproducer if the problem is still present in the current release of Payara Server 5.x

**Closed by fturizo** 2020-02-06 18:17 UTC
