### ISSUE TITLE
BugReport: com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [102]], State = [NEW]Bug Report:  

### ISSUE THREAD

**Issue by manish-manghwani** [payara/Payara#5953] opened 2022-09-21 07:56 UTC
# Description #
Starting the server fails with error. It was working fine for couple of days.

## Expected Outcome ##
Server should start

## Current Outcome ##

Server Fails with error.

` Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@6fecacab in service registry.
Completed shutdown of GlassFish runtime
We are in non-embedded mode, so fish.payara.server.internal.core.glassfish [113] has nothing to do.
Sep 20, 2022 6:41:38 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:121)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
Caused by: A MultiException has 2 exceptions.  They are:
1. com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [102]], State = [NEW]
2. java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
        implementation=org.glassfish.batch.spi.impl.BatchRuntimeConfigurationInjector
        name=batch-runtime-configuration
        contracts={org.glassfish.batch.spi.impl.BatchRuntimeConfigurationInjector,org.jvnet.hk2.config.ConfigInjector}
        scope=javax.inject.Singleton
        qualifiers={org.jvnet.hk2.config.InjectionTarget}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=@table-suffix={optional,default\:,datatype\:java.lang.String,leaf},@data-source-lookup-name={optional,datatype\:java.lang.String,leaf},@table-prefix={optional,default\:,datatype\:java.lang.String,leaf},@schema-name={optional,default\:APP,datatype\:java.lang.String,leaf},@executor-service-lookup-name={optional,default\:concurrent/__defaultManagedExecutorService,datatype\:java.lang.String,leaf},target={org.glassfish.batch.spi.impl.BatchRuntimeConfiguration},Bundle-SymbolicName={fish.payara.server.internal.batch.glassfish-batch-connector},Bundle-Version={5.2022.3}
        rank=0
        loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [102]], State = [NEW],843803222)
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=188
        locatorId=0
        identityHashCode=1109218483
        reified=false)

        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2247)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:438)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:457)
        at org.jvnet.hk2.config.DomDocument$InjectionTargetFilter.matches(DomDocument.java:184)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:347)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:389)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getBestDescriptor(ServiceLocatorImpl.java:397)
        at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:135)
        at org.jvnet.hk2.config.ConfigModel.parseValue(ConfigModel.java:959)
        at org.jvnet.hk2.config.ConfigModel.<init>(ConfigModel.java:875)
        at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:114)
        at org.jvnet.hk2.config.DomDocument.getModelByElementName(DomDocument.java:162)
        at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:166)
        at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:102)
        at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:96)
        at org.glassfish.config.support.DomainXml.parseDomainXml(DomainXml.java:271)
        at org.glassfish.config.support.DomainXml.run(DomainXml.java:121)
        at org.jvnet.hk2.config.ConfigurationPopulator.populateConfig(ConfigurationPopulator.java:58)
        at org.glassfish.hk2.bootstrap.HK2Populator.populateConfig(HK2Populator.java:83)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.populateConfig(AbstractModulesRegistryImpl.java:190)
        at com.sun.enterprise.module.bootstrap.Main.createServiceLocator(Main.java:249)
        at org.jvnet.hk2.osgiadapter.HK2Main.createServiceLocator(HK2Main.java:95)
        at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime.newGlassFish(EmbeddedOSGiGlassFishRuntime.java:95)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishRuntimeDecorator.newGlassFish(GlassFishRuntimeDecorator.java:68)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntime.newGlassFish(OSGiGlassFishRuntime.java:91)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:137)
        ... 6 more
Caused by: com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [102]], State = [NEW]
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:193)
        at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:54)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2239)
        ... 31 more
Caused by: org.osgi.framework.BundleException: Unable to resolve fish.payara.server.internal.batch.glassfish-batch-connector [102](R 102.0): missing requirement [fish.payara.server.internal.batch.glassfish-batch-connector [102](R 102.0)] osgi.wiring.package; (osgi.wiring.package=com.ibm.jbatch.spi) [caused by: Unable to resolve fish.payara.server.internal.batch.payara-jbatch [316](R 316.0): missing requirement [fish.payara.server.internal.batch.payara-jbatch [316](R 316.0)] osgi.wiring.package; (osgi.wiring.package=org.glassfish.weld) [caused by: Unable to resolve fish.payara.server.internal.web.weld-integration [381](R 381.0): missing requirement [fish.payara.server.internal.web.weld-integration [381](R 381.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.web.deployment.descriptor)(version>=5.2022.0)(!(version>=6.0.0))) [caused by: Unable to resolve fish.payara.server.internal.web.glue [369](R 369.0): missing requirement [fish.payara.server.internal.web.glue [369](R 369.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.catalina)(version>=5.2022.0)(!(version>=6.0.0))) [caused by: Unable to resolve fish.payara.server.internal.web.core [367](R 367.0): missing requirement [fish.payara.server.internal.web.core [367](R 367.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.web.loader)(version>=5.2022.0)(!(version>=6.0.0)))]]]] Unresolved requirements: [[fish.payara.server.internal.batch.glassfish-batch-connector [102](R 102.0)] osgi.wiring.package; (osgi.wiring.package=com.ibm.jbatch.spi)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:1006)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.startBundle(OSGiModuleImpl.java:227)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:185)
        ... 33 more

Command start-domain failed. `

## Steps to reproduce ## 

1. Start the server 
asadmin start-domain --debug domain1

2. Observation
Waiting for domain1 to start ........................Error starting domain domain1.
The server exited prematurely with exit code 1.

## Environment ##

- **Distribution**: Server Full Profile
- **JDK Version**: "1.8.0_202" | Oracle
- **Operating System**: Windows 10

**Comment by JamesHillyard** [comment] 2022-09-22 13:15
HI @manish-manghwani,

I haven't been able to reproduce this error, but this is often caused due to missing modules in Payara Server. Could you please try with a new install of Payara and confirm if that starts as expected?

Thanks,
James

**Comment by manish-manghwani** [comment] 2022-09-23 12:09
Hi @JamesHillyard,

Thank you for looking into this. I tried with fresh server installation, and it is working as expected. Although, the root cause of missing modules is still unknow. Can you provide any pointers to find the root cause?

**Comment by JamesHillyard** [comment] 2022-09-23 12:51
Hi @manish-manghwani,

I'm glad to hear that a fresh install worked as expected, are you running Windows Defender? If so there is currently a known issue where it is marking a module as suspicious and removing it. We have reviewed and confirmed this is a false positive so there is nothing to worry about, but would explain a module going missing.

Thanks,
James

**Comment by manish-manghwani** [comment] 2022-09-28 07:05
Hi @JamesHillyard,

Yes, I have Windows Defender running and probably what you suspected is the root cause. I would like to keep this issue open, so that if server doesn't start again then we might have list of modules that were removed.

**Comment by roberto-cisternino** [comment] 2023-01-19 14:45
It looks this error comes up after moving or making a copy of payara5 on another folder in the same machine.

**Comment by fturizo** [comment] 2023-06-21 15:28
We're proceeding to close this issue as there's no additional work to do.

**Closed by fturizo** 2023-06-21 15:28 UTC
Labels: Type: Bug
