### ISSUE TITLE
Out of memory after number of redeployments

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4098] opened 2019-07-22 09:54 UTC
# Description #
----------

On our preprod env after a couple tenths of redeployments instances are lacking memory and have to be killed manually from OS. Problem is reproduced on two separate environments.

## Expected Outcome
No out of memory error.

## Current Outcome
```
2019-07-22 11:50:12 WARNING [org.apache.catalina.core.ApplicationDispatcher doInvoke] Servlet.service() for servlet Faces Servlet threw exception
java.lang.OutOfMemoryError: Java heap space

2019-07-22 11:50:12 WARNING [org.apache.catalina.core.ApplicationDispatcher doInvoke] Servlet.service() for servlet Faces Servlet threw exception
java.lang.OutOfMemoryError: Java heap space

2019-07-22 11:50:06 WARNING [com.sun.enterprise.web.logger.CatalinaLogger write] StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
java.lang.OutOfMemoryError: Java heap space

2019-07-22 11:50:12 WARNING [com.sun.enterprise.web.logger.CatalinaLogger write] org.apache.catalina.core.StandardHostValve@409d228: Exception Processing ErrorPage[errorCode=500, location=/WEB-INF/error_500.html]
javax.servlet.ServletException: Java heap space
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:725)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:824)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:688)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:527)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:496)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:378)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:507)
	at org.apache.catalina.core.StandardHostValve.dispatchToErrorPage(StandardHostValve.java:701)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:385)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:319)
	at org.apache.catalina.core.StandardHostValve.postInvoke(StandardHostValve.java:217)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:373)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$0(WorkerThreadIOStrategy.java:90)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
----- Root Cause -----
java.lang.OutOfMemoryError: Java heap space

```

## Steps to reproduce (Only for bug reports) 

Start the deployment group, perform multiple redeployments of your application and at some time the error will occur.
## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**:  zulu8.38.0.13-ca-jre8.0.212-linux_x64
- **Operating System**: RHEL
- Instances memory: -Xmx2g

**Comment by smillidge** [comment] 2019-07-27 15:30
How do you know this is caused by Payara and not your application. Have you looked at what objects are causing the OOME?

**Comment by rdebusscher** [comment] 2020-01-03 10:21
Closing as not responsive.

**Comment by sgflt** [comment] 2020-01-04 12:08
Could we reopen this issue? I have been curious and tried https://github.com/sgflt/payara-test-case on Payara 5.194.

Memory leak is clearly visible after many redeployments:
`for i in {1..100}; do /app/bin/payara5/bin/asadmin redeploy --name test-case-0 ~/git/payara-test-case/ear/target/test-case-0.ear; done`

Most of created instances came from Felix as java-util.HashMap$Node referenced by

> m_felix in org.apache.felix.framework.FrameworkWiringImpl#1 [GC root - Java frame]

![Snímek obrazovky pořízený 2020-01-04 12-45-11](https://user-images.githubusercontent.com/6689451/71765240-50284080-2ef2-11ea-94a2-b69d6dcef91f.png)

Also classes seems to be loaded permanently as count of loaded classes is constantly growing.

**Comment by smillidge** [comment] 2020-01-05 18:23
I did our usual classloader leak test. Deployed the application, heap dumped the server and looked for EarClassLoader instances and WebAppClassLoader instances for the application. Undeployed the application and forced GC a few times then heap dumped again and the relevant classloaders are gone. So I don't think we have a classloader leak. You need to ensure there is a full GC to unload classes so not sure whether in the image above that has happened.

**Comment by sgflt** [comment] 2020-12-23 16:33
Linking with https://github.com/payara/Payara/pull/5063 that may reveal the cause. (tested on 5.2020.7 and still getting OOM after some count of redeployments)

**Comment by sgflt** [comment] 2020-12-30 21:22
Leak is probably caused by ServiceLocatorImpl with name "__HK2_Generated_0".
Count of  ((IndexedListData)((ServiceLocatorImpl)this).allDescriptors).unsortedList is constantly increasing.

<details>

```
[MARKED] addConfigurationInternal:1893, ServiceLocatorImpl (org.jvnet.hk2.internal)
[MARKED] addConfiguration:2113, ServiceLocatorImpl (org.jvnet.hk2.internal)
commit:262, DynamicConfigurationImpl (org.jvnet.hk2.internal)
addOneDescriptor:344, ServiceLocatorUtilities (org.glassfish.hk2.utilities)
addOneDescriptor:303, ServiceLocatorUtilities (org.glassfish.hk2.utilities)
addWithAlias:562, Dom (org.jvnet.hk2.config)
insertAfter:602, Dom (org.jvnet.hk2.config)
add:462, ConfigModel$CollectionNode$1 (org.jvnet.hk2.config)
add:108, AbstractList (java.util)
commitListChanges:419, WriteableView (org.jvnet.hk2.config)
commit:400, WriteableView (org.jvnet.hk2.config)
commit:114, Transaction (org.jvnet.hk2.config)
registerAppInDomainXML:1467, ApplicationLifecycle (com.sun.enterprise.v3.server)
registerAppInDomainXML:1349, ApplicationLifecycle (com.sun.enterprise.v3.server)
execute:616, DeployCommand (org.glassfish.deployment.admin)
run:556, CommandRunnerImpl$2$1 (com.sun.enterprise.v3.admin)
run:552, CommandRunnerImpl$2$1 (com.sun.enterprise.v3.admin)
doPrivileged:-1, AccessController (java.security)
doAs:360, Subject (javax.security.auth)
execute:551, CommandRunnerImpl$2 (com.sun.enterprise.v3.admin)
run:582, CommandRunnerImpl$3 (com.sun.enterprise.v3.admin)
run:574, CommandRunnerImpl$3 (com.sun.enterprise.v3.admin)
doPrivileged:-1, AccessController (java.security)
doAs:360, Subject (javax.security.auth)
doCommand:573, CommandRunnerImpl (com.sun.enterprise.v3.admin)
doCommand:1497, CommandRunnerImpl (com.sun.enterprise.v3.admin)
access$1300:120, CommandRunnerImpl (com.sun.enterprise.v3.admin)
execute:1879, CommandRunnerImpl$ExecutionContext (com.sun.enterprise.v3.admin)
execute:1755, CommandRunnerImpl$ExecutionContext (com.sun.enterprise.v3.admin)
execute:129, ReDeployCommand (org.glassfish.deployment.admin)
run:556, CommandRunnerImpl$2$1 (com.sun.enterprise.v3.admin)
run:552, CommandRunnerImpl$2$1 (com.sun.enterprise.v3.admin)
doPrivileged:-1, AccessController (java.security)
doAs:360, Subject (javax.security.auth)
execute:551, CommandRunnerImpl$2 (com.sun.enterprise.v3.admin)
run:582, CommandRunnerImpl$3 (com.sun.enterprise.v3.admin)
run:574, CommandRunnerImpl$3 (com.sun.enterprise.v3.admin)
doPrivileged:-1, AccessController (java.security)
doAs:360, Subject (javax.security.auth)
doCommand:573, CommandRunnerImpl (com.sun.enterprise.v3.admin)
doCommand:1497, CommandRunnerImpl (com.sun.enterprise.v3.admin)
access$1300:120, CommandRunnerImpl (com.sun.enterprise.v3.admin)
execute:1879, CommandRunnerImpl$ExecutionContext (com.sun.enterprise.v3.admin)
execute:1755, CommandRunnerImpl$ExecutionContext (com.sun.enterprise.v3.admin)
executeCommand:409, CommandResource (org.glassfish.admin.rest.resources.admin)
execCommandSimpInMultOut:236, CommandResource (org.glassfish.admin.rest.resources.admin)
invoke:-1, GeneratedMethodAccessor441 (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
lambda$static$0:52, ResourceMethodInvocationHandlerFactory (org.glassfish.jersey.server.model.internal)
invoke:-1, 610366744 (org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$$Lambda$1483)
run:124, AbstractJavaResourceMethodDispatcher$1 (org.glassfish.jersey.server.model.internal)
invoke:167, AbstractJavaResourceMethodDispatcher (org.glassfish.jersey.server.model.internal)
doDispatch:176, JavaResourceMethodDispatcherProvider$ResponseOutInvoker (org.glassfish.jersey.server.model.internal)
dispatch:79, AbstractJavaResourceMethodDispatcher (org.glassfish.jersey.server.model.internal)
invoke:469, ResourceMethodInvoker (org.glassfish.jersey.server.model)
apply:391, ResourceMethodInvoker (org.glassfish.jersey.server.model)
apply:80, ResourceMethodInvoker (org.glassfish.jersey.server.model)
run:253, ServerRuntime$1 (org.glassfish.jersey.server)
call:248, Errors$1 (org.glassfish.jersey.internal)
call:244, Errors$1 (org.glassfish.jersey.internal)
process:292, Errors (org.glassfish.jersey.internal)
process:274, Errors (org.glassfish.jersey.internal)
process:244, Errors (org.glassfish.jersey.internal)
runInScope:265, RequestScope (org.glassfish.jersey.process.internal)
process:232, ServerRuntime (org.glassfish.jersey.server)
handle:680, ApplicationHandler (org.glassfish.jersey.server)
service:356, GrizzlyHttpContainer (org.glassfish.jersey.grizzly2.httpserver)
service:179, JerseyContainerCommandService$3 (org.glassfish.admin.rest.adapter)
service:189, RestAdapter (org.glassfish.admin.rest.adapter)
call:520, ContainerMapper$HttpHandlerCallable (com.sun.enterprise.v3.services.impl)
service:217, ContainerMapper (com.sun.enterprise.v3.services.impl)
runService:182, HttpHandler (org.glassfish.grizzly.http.server)
doHandle:156, HttpHandler (org.glassfish.grizzly.http.server)
handleRead:218, HttpServerFilter (org.glassfish.grizzly.http.server)
execute:95, ExecutorResolver$9 (org.glassfish.grizzly.filterchain)
executeFilter:260, DefaultFilterChain (org.glassfish.grizzly.filterchain)
executeChainPart:177, DefaultFilterChain (org.glassfish.grizzly.filterchain)
execute:109, DefaultFilterChain (org.glassfish.grizzly.filterchain)
process:88, DefaultFilterChain (org.glassfish.grizzly.filterchain)
execute:53, ProcessorExecutor (org.glassfish.grizzly)
fireIOEvent:524, TCPNIOTransport (org.glassfish.grizzly.nio.transport)
fireIOEvent:89, AbstractIOStrategy (org.glassfish.grizzly.strategies)
run0:94, WorkerThreadIOStrategy (org.glassfish.grizzly.strategies)
access$100:33, WorkerThreadIOStrategy (org.glassfish.grizzly.strategies)
run:114, WorkerThreadIOStrategy$WorkerThreadRunnable (org.glassfish.grizzly.strategies)
doWork:569, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool)
run:549, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool)
run:748, Thread (java.lang)
```
</details>

**Comment by lprimak** [comment] 2020-12-30 21:28
@sgflt since you are looking at it, any chance you can pinpoint the source of the leak in non-generated code?
I am seeing a leak with the new leak tester, but am not yet looking for a source of the leak (got holiday + more high-priority projects before I can look at this)

**Comment by sgflt** [comment] 2020-12-30 21:29
Yes, another candidate is org.glassfish.deployment.admin.DeployCommand. Retained size is about 230 MB.

**Comment by lprimak** [comment] 2020-12-30 21:33
Something is not deleting a reference to the class loader and this what's causing redeploy leak, and needs to be pinpointed / fixed. Anything else would be a small leak

**Comment by sgflt** [comment] 2020-12-30 21:49
Tracked GC root to archiveMetaData in com.sun.enterprise.deploy.shared.FileArchive#440 [GC root - Java frame]

**Comment by sgflt** [comment] 2020-12-30 23:07
There is some relation between FileArchive.archiveMetaData -> DeployCommand.report -> PropsFileActionReporter.resultTypes ->  DeployCommandSupplementalInfo.dc -> DeploymentContextImpl.source -> FileArchive.archiveMetadata again

**Comment by sgflt** [comment] 2020-12-31 00:40
I was able to cut out some fields. Now the leak is not so fast, but still present. All fixed places used nested classes.

**Comment by sgflt** [comment] 2020-12-31 00:47
And the way is turned into ServiceLocatorImpl back again. Now stored in static field in Globals with nice comment: "Very sensitive class, anything stored here cannot be garbage collected"

**Comment by sgflt** [comment] 2020-12-31 00:57
I think Globals are the main cause. All places I have fixed was Services instantiated by ServiceLocator.

**Comment by sgflt** [comment] 2020-12-31 01:36
Yes. Each redeploy puts some descriptors into default service locator, but undeploy does not call shutdown nor unregisters its own descriptors from default service locator, so count of initialized services is unstopably growing.

Insertion stacktrace:

<details>

```
addConfigurationInternal:1893, ServiceLocatorImpl (org.jvnet.hk2.internal)
addConfiguration:2113, ServiceLocatorImpl (org.jvnet.hk2.internal)
commit:262, DynamicConfigurationImpl (org.jvnet.hk2.internal)
addOneDescriptor:344, ServiceLocatorUtilities (org.glassfish.hk2.utilities)
addOneDescriptor:303, ServiceLocatorUtilities (org.glassfish.hk2.utilities)
addWithAlias:562, Dom (org.jvnet.hk2.config)
insertAfter:602, Dom (org.jvnet.hk2.config)
add:462, ConfigModel$CollectionNode$1 (org.jvnet.hk2.config)
add:108, AbstractList (java.util)
commitListChanges:419, WriteableView (org.jvnet.hk2.config)
commit:400, WriteableView (org.jvnet.hk2.config)
commit:114, Transaction (org.jvnet.hk2.config)
registerAppInDomainXML:1467, ApplicationLifecycle (com.sun.enterprise.v3.server)
registerAppInDomainXML:1349, ApplicationLifecycle (com.sun.enterprise.v3.server)
execute:615, DeployCommand (org.glassfish.deployment.admin)
run:556, CommandRunnerImpl$2$1 (com.sun.enterprise.v3.admin)
run:552, CommandRunnerImpl$2$1 (com.sun.enterprise.v3.admin)
doPrivileged:-1, AccessController (java.security)
doAs:360, Subject (javax.security.auth)
execute:551, CommandRunnerImpl$2 (com.sun.enterprise.v3.admin)
run:582, CommandRunnerImpl$3 (com.sun.enterprise.v3.admin)
run:574, CommandRunnerImpl$3 (com.sun.enterprise.v3.admin)
doPrivileged:-1, AccessController (java.security)
doAs:360, Subject (javax.security.auth)
doCommand:573, CommandRunnerImpl (com.sun.enterprise.v3.admin)
doCommand:1497, CommandRunnerImpl (com.sun.enterprise.v3.admin)
access$1300:120, CommandRunnerImpl (com.sun.enterprise.v3.admin)
execute:1879, CommandRunnerImpl$ExecutionContext (com.sun.enterprise.v3.admin)
execute:1755, CommandRunnerImpl$ExecutionContext (com.sun.enterprise.v3.admin)
execute:129, ReDeployCommand (org.glassfish.deployment.admin)
run:556, CommandRunnerImpl$2$1 (com.sun.enterprise.v3.admin)
run:552, CommandRunnerImpl$2$1 (com.sun.enterprise.v3.admin)
doPrivileged:-1, AccessController (java.security)
doAs:360, Subject (javax.security.auth)
execute:551, CommandRunnerImpl$2 (com.sun.enterprise.v3.admin)
run:582, CommandRunnerImpl$3 (com.sun.enterprise.v3.admin)
run:574, CommandRunnerImpl$3 (com.sun.enterprise.v3.admin)
doPrivileged:-1, AccessController (java.security)
doAs:360, Subject (javax.security.auth)
doCommand:573, CommandRunnerImpl (com.sun.enterprise.v3.admin)
doCommand:1497, CommandRunnerImpl (com.sun.enterprise.v3.admin)
access$1300:120, CommandRunnerImpl (com.sun.enterprise.v3.admin)
execute:1879, CommandRunnerImpl$ExecutionContext (com.sun.enterprise.v3.admin)
execute:1755, CommandRunnerImpl$ExecutionContext (com.sun.enterprise.v3.admin)
executeCommand:409, CommandResource (org.glassfish.admin.rest.resources.admin)
execCommandSimpInMultOut:236, CommandResource (org.glassfish.admin.rest.resources.admin)
invoke:-1, GeneratedMethodAccessor380 (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
lambda$static$0:52, ResourceMethodInvocationHandlerFactory (org.glassfish.jersey.server.model.internal)
invoke:-1, 1066657839 (org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$$Lambda$1415)
run:124, AbstractJavaResourceMethodDispatcher$1 (org.glassfish.jersey.server.model.internal)
invoke:167, AbstractJavaResourceMethodDispatcher (org.glassfish.jersey.server.model.internal)
doDispatch:176, JavaResourceMethodDispatcherProvider$ResponseOutInvoker (org.glassfish.jersey.server.model.internal)
dispatch:79, AbstractJavaResourceMethodDispatcher (org.glassfish.jersey.server.model.internal)
invoke:469, ResourceMethodInvoker (org.glassfish.jersey.server.model)
apply:391, ResourceMethodInvoker (org.glassfish.jersey.server.model)
apply:80, ResourceMethodInvoker (org.glassfish.jersey.server.model)
run:253, ServerRuntime$1 (org.glassfish.jersey.server)
call:248, Errors$1 (org.glassfish.jersey.internal)
call:244, Errors$1 (org.glassfish.jersey.internal)
process:292, Errors (org.glassfish.jersey.internal)
process:274, Errors (org.glassfish.jersey.internal)
process:244, Errors (org.glassfish.jersey.internal)
runInScope:265, RequestScope (org.glassfish.jersey.process.internal)
process:232, ServerRuntime (org.glassfish.jersey.server)
handle:680, ApplicationHandler (org.glassfish.jersey.server)
service:356, GrizzlyHttpContainer (org.glassfish.jersey.grizzly2.httpserver)
service:179, JerseyContainerCommandService$3 (org.glassfish.admin.rest.adapter)
service:189, RestAdapter (org.glassfish.admin.rest.adapter)
call:520, ContainerMapper$HttpHandlerCallable (com.sun.enterprise.v3.services.impl)
service:217, ContainerMapper (com.sun.enterprise.v3.services.impl)
runService:182, HttpHandler (org.glassfish.grizzly.http.server)
doHandle:156, HttpHandler (org.glassfish.grizzly.http.server)
handleRead:218, HttpServerFilter (org.glassfish.grizzly.http.server)
execute:95, ExecutorResolver$9 (org.glassfish.grizzly.filterchain)
executeFilter:260, DefaultFilterChain (org.glassfish.grizzly.filterchain)
executeChainPart:177, DefaultFilterChain (org.glassfish.grizzly.filterchain)
execute:109, DefaultFilterChain (org.glassfish.grizzly.filterchain)
process:88, DefaultFilterChain (org.glassfish.grizzly.filterchain)
execute:53, ProcessorExecutor (org.glassfish.grizzly)
fireIOEvent:524, TCPNIOTransport (org.glassfish.grizzly.nio.transport)
fireIOEvent:89, AbstractIOStrategy (org.glassfish.grizzly.strategies)
run0:94, WorkerThreadIOStrategy (org.glassfish.grizzly.strategies)
access$100:33, WorkerThreadIOStrategy (org.glassfish.grizzly.strategies)
run:114, WorkerThreadIOStrategy$WorkerThreadRunnable (org.glassfish.grizzly.strategies)
doWork:569, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool)
run:549, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool)
run:748, Thread (java.lang)
```

</details>

**Comment by lprimak** [comment] 2020-12-31 01:56
Unfortunately, I am not sure you are barking up the right tree here.
Most services are singletons and will not hold a copy of anything in them.
Some do hold some stuff, but if (and that's a big if) there is a leak, it's usually small.
The big leak is when something holds onto the Class loader instance (WebappClassLoader or ASURLClassLoader),
and that's where the big problems lie because those hold huge amounts of data

**Comment by sgflt** [comment] 2020-12-31 10:14
I wouldn't be suprised if there were multiple causes of different leaks. I am going to measure the change to confirm that the big leak is fixed and small is still present.

**Comment by sgflt** [comment] 2020-12-31 11:11
After fix: 30 minutes, heap growing slowly, 1000 redeployments passed, metaspace usege constant, clases being unloaded

![Snímek obrazovky pořízený 2020-12-31 11-39-23](https://user-images.githubusercontent.com/6689451/103406967-eff7c900-4b5c-11eb-8b92-45346e9ca136.png)

![Snímek obrazovky pořízený 2020-12-31 11-39-32](https://user-images.githubusercontent.com/6689451/103406971-f6864080-4b5c-11eb-8d65-413285e21a4d.png)

Heap stats: retained size is mostly caused by in ServiceLocator's defaultHabitat.
![Snímek obrazovky pořízený 2020-12-31 11-43-17](https://user-images.githubusercontent.com/6689451/103407095-8cba6680-4b5d-11eb-9456-680f7c89ab1e.png)

Before fix: 10 minutes, heap full, ~ 200 redeployments, metaspace growing, classes sitting in memory

![Snímek obrazovky pořízený 2020-12-31 11-59-03](https://user-images.githubusercontent.com/6689451/103407635-9e9d0900-4b5f-11eb-93a1-f8ac96753268.png)

![Snímek obrazovky pořízený 2020-12-31 11-59-07](https://user-images.githubusercontent.com/6689451/103407637-a2309000-4b5f-11eb-840b-06085df1fe8f.png)

Heap stats: 
![Snímek obrazovky pořízený 2020-12-31 12-10-44](https://user-images.githubusercontent.com/6689451/103408064-47983380-4b61-11eb-90de-4bb3f9491ee8.png)

**Closed** 2021-01-26 02:53 UTC
Labels: Type: Bug

**Comment by lprimak** [comment] 2021-01-27 02:32
> Yes. Each redeploy puts some descriptors into default service locator, but undeploy does not call shutdown nor unregisters its own descriptors from default service locator, so count of initialized services is unstopably growing.

FYI I tried to track this down today, and services **are** actually unregistered from `ServiceLocatorImpl`
However, as @dmatej knows there is a race condition with logging that was causing the wrong service locator to be cached. I removed the `@Inject` of `ServiceLocator` from logging and that leak went away.

This was all part of the fix to this issue.

**Comment by heatherita** [comment] 2021-06-16 16:36
Lately we are getting memory leak errors and heap space errors in our server log. The heap space problem prevents me from deploying. Will an upgrade to a newer version of Payara solve this? I'm currently on Payara Server 5.194 #badassfish (build 327). Thanks.

```
[2021-06-15T17:56:37.914-0400] [Payara 5.194] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=65727 _ThreadName=RunLevelControllerThread-1623794197218] [timeMillis: 1623794197914] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.OutOfMemoryError: Java heap space
]]

[2021-06-15T17:56:37.923-0400] [Payara 5.194] [SEVERE] [] [javax.enterprise.web.util] [tid: _ThreadID=65727 _ThreadName=RunLevelControllerThread-1623794197218] [timeMillis: 1623794197923] [levelValue: 1000] [[
  The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@26816562]) and a value of type [org.glassfish.admingui.theme.AdminguiThemeContext] (value [org.glassfish.admingui.theme.AdminguiThemeContext@e604929]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]


```

**Comment by lprimak** [comment] 2021-06-16 17:42
Yes. Latest Payara community will solve most of these issues. While there are still small leaks, the large ones are absent

**Comment by heatherita** [comment] 2021-06-16 19:27
Thanks. Is there any way to temporarily reset the server and the memory, until we get a chance to upgrade?
