### ISSUE TITLE
CDI fails in combination with JSF with a WAB (OSGi bundle) /CUSTCOM-58

### ISSUE THREAD

**Issue by tosuns** [payara/Payara#517] opened 2015-11-07 19:54 UTC
I tried to get more familiar with JavaEE and OSGi and build a simple WAB and run it. I noticed that CDI fails in combination with JSF, but works fine with JAX-RS.

I created a maven project http://www.filedropper.com/cdi-test-wab and copied it to ../domain1/autodeploy/bundles of Payara 4.154.
The deployment was successfull without any error messages.
1. First I browsed http://&lt;server&gt;:&lt;port&gt;/cdi-test but I didn't get the expected output "Hello User".
2. Afterwards I browsed http://&lt;server&gt;:&lt;port&gt;/cdi-test/webresources/resources and got the expected output.

At the end I replaced the CDI annotation with JSF @ManagedBean annotation and everything works fine.

**Comment by smillidge** [comment] 2015-11-09 14:52
Can you create a test case?

**Comment by tosuns** [comment] 2015-11-16 17:42
Hi,
and sorry for the late reply. What kind of test case do you need? I thought the provided link to a sample maven project, which actually displays the probleme and the described steps in my post should be enough for an test case or do you need something else  ?

**Comment by smillidge** [comment] 2015-11-16 22:36
I can’t download the file from the link

**Comment by tosuns** [comment] 2015-11-17 17:23
Hi, 

and sorry again :) seems like there was some kind of time limitation. I put the project on my github account. you should be able to download the project via this linke: https://github.com/tosuns/cdi-test-case/archive/master.zip

I hope this time you will be able to download the project.

**Comment by smillidge** [comment] 2015-11-19 18:17
We can take a look thanks for the test case.

**Comment by gimby** [comment] 2015-12-04 09:34
A note on that example program: its a little confusing to me. The IndexController class mixes JSF annotations and CDI annotations which are incompatible; it has the JSF ManagedBean annotation on it and the CDI SessionScoped annotation. That won't fail with an error, but it won't make the bean session scoped.

It either needs to use the CDI **Named** annotation and the **javax.enterprise.context.SessionScoped** annotation, or the JSF **ManagedBean** annotation and the **javax.faces.bean.SessionScoped** annotation.

**Comment by tosuns** [comment] 2015-12-05 10:27
It seems like I forgot to change it back. I tested it again with the correct combination to make sure it didn't cause the issue. But as far as I can tell, it still doen't work how I expect it should: CDI annotation does not work, but JSF annotation does.

Actually, in this case it doesn't matter, which scope the backing bean has. The scope is only of importance in the use case with the rest endpoint in the project, which is not part of the test case  (I should have removed that one, but I was to lazy).

**Comment by abani-github** [comment] 2016-01-28 07:44
Hi @tosuns, @smillidge I was not able to reproduce this issue with payara-4.1.1.154.

@tosuns i have followed the project structure which you have created. tested below use cases

1. Simple Servlet - worked
2. Servlet with Service injected - worked
3. JSF simple xhtml - worked
4. XHTML with JSF managed bean and sevice injected worked.

See the below code snippet which i have used

<script src="https://gist.github.com/abani-github/80f8dceae97025fe9912.js"></script> 

<script src="https://gist.github.com/abani-github/318b56526e0f341c779a.js"></script>

please let me know if i am doing anything wrong here

**Comment by tosuns** [comment] 2016-01-28 10:16
The way how you implemented your project works fine for me too. But my point was that if you use a CDI (javax.inject.Named) bean as backing bean - in your case GreetBean - for the jsf page, instead of and javax.faces.bean.ManagedBean, and depoly it as an OSGi web application, then the backing bean does not get called (at least in my tests).  
If you deploy the project with and CDI backing bean for a jsf page as a plain web application then in this case the project works fine as I would expect it, but it does not work in the OSGi environment.

**Comment by abani-github** [comment] 2016-01-28 10:28
@tosuns thanks for the clarification. I agree to this use case. I am able to reproduce the issue with @Named and @RequestScoped (enterprise) annotation. the bean is not getting invoked. Even if i don't see any errors in server log

**Comment by mikecroft** [comment] 2016-09-12 10:26
Internal issue `PAYARA-1064`

**Comment by rdebusscher** [comment] 2019-12-05 08:07
Now Internal issue `CUSTCOM-58`

**Comment by AlanRoth** [comment] 2020-11-11 10:20
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:20 UTC
Labels: bug, reproducible, status:accepted
