### ISSUE TITLE
SSO-Entries may expire ahead of time /CUSTCOM-93

### ISSUE THREAD

**Issue by HRE** [payara/Payara#2881] opened 2018-06-21 15:32 UTC
# Description #
----------
When doing SSO with multiple WARs, preexisting sessions of the WARs not used for login do not participate in extending the SSO-Entry. Also invalidating these sessions does not affect the SSO token.

This seems to be because the sessions will only be associated with the SSO-Entry when being created or during authentication.

## Expected Outcome

When logging in with /app1 and then continuously using /app2 the login should not expire, regardles of a preexisting session in /app2.

## Current Outcome
Despite continuously using /app2 after about 37 minutes (session timeout of app1.war + session reap interval + sso max inactive + sso reap interval) the login form of /app2 is shown.

## Steps to reproduce

1 -**  Enable SSO

2 -**  Deploy two WARs app1.war and app2.war with security constraints and form authentication

3 -**  Open /app2 in browser so that the login form is shown

4 -**  Open /app1 in browser so that the login form is shown

5 -**  Perform login so the content of /app1 is shown

6 -**  Open /app2 in browser so the content of /app2 is shown

7 -**  Regularly reload /app2

8 -**  After about 37 minutes the login form is shown instead of the content

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full

**Comment by smillidge** [comment] 2018-07-02 19:28
Can you provide a test case which demonstrates the issue?
Also is the issue present in Payara 5.x?

**Comment by HRE** [comment] 2018-07-25 10:16
I can confirm the bug for Payara 5.182.
It can be reproduced within a few minutes by a [Unit Test](https://github.com/HRE/PAYARA-2881-sso-test)  with reduced session timeouts.

**Comment by rdebusscher** [comment] 2019-12-17 11:11
I have created `CUSTCOM-93`

**Comment by AlanRoth** [comment] 2020-11-11 11:20
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:20 UTC
Labels: status:accepted

**Comment by sgflt** [comment] 2021-01-13 15:36
The problem is caused by the session created for app2 before login in app1. This session is not associated with SSO. Only login creates SSO cookie and following new sessions are associated with SSO id.

So in your case access to app2 does not trigger last access update in SSO, because for app2's session there is no SSO.
