### ISSUE TITLE
eclipselink.logging.logger=ServerLogger results in logs going to /dev/null equivilent

### ISSUE THREAD

**Issue by FireballDWF** [payara/Payara#725] opened 2016-03-25 22:14 UTC
When the following two lines are added to a JPA persistence.xml file, the actual results are logs, such as StackTraces from an Exception, are not written to server.log or anywhere else.
```
    <property name="eclipselink.logging.logger" value="ServerLogger"/> 
    <property name="eclipselink.target-server" value="Glassfish" /> 
```
replacing the above two lines with: 
```
    <property name="eclipselink.logging.logger" value="JavaLogger"/> 
```
does result in logs written to server.log as expected, per setting of com.sun.enterprise.server.logging.GFFileHandler.file

Request is to either document that the ServerLogger setting in unsupported, or change code/config to support it.

**Comment by mikecroft** [comment] 2016-03-26 11:01
Hi @FireballDWF - it looks like the relevant lines haven't been included in the issue. Could you paste them in again?

**Comment by FireballDWF** [comment] 2016-03-26 16:10
Edited my original writeup, had to add the markdown to make the tags visible

**Comment by mulderbaba** [comment] 2016-04-15 07:05
@FireballDWF I tried your configuration on CargoTracker-J12015 example that we have. I added persistence.xml configs and added a RuntimeException. You can find the changes on my forked branch with the url to the commit: https://github.com/mulderbaba/CargoTracker-J12015/commit/b6c0fdfe479c4ca7c92282cd1ea38fbb7c7b4a26. I couldn't reproduce the problem while deploying CargoTracker-J12015 against the current trunk of Payara Server. Exception got printed into server.log with no problem. can you give it a try to see if that was your case?

**Comment by mikecroft** [comment] 2016-06-10 14:46
Hi @FireballDWF did you try @mulderbaba's test?

**Comment by mikecroft** [comment] 2016-08-16 08:59
Is this still an issue for you @FireballDWF?

**Comment by mikecroft** [comment] 2016-09-13 13:22
Closing since we can't reproduce.

**Closed by mikecroft** 2016-09-13 13:22 UTC
Labels: 1:Wait, c:PossibleBug, cannot reproduce, requestor unresponsive (1), requestor unresponsive (2)
