### ISSUE TITLE
asadmin create-domain not honoring domainproperties jms.port

### ISSUE THREAD

**Issue by eicheled** [payara/Payara#1289] opened 2017-01-17 17:45 UTC
# Description #
When creating a domain from the command line using asadmin, using this command:

`asadmin create-domain --adminport 4850 --instanceport 80  --domainproperties jms.port=7678:domain.jmxPort=8688:orb.listener.port=3702:http.ssl.port=443:orb.ssl.port=3822:orb.mutualauth.port=3922:osgi.shell.telnet.port=6668:java.debugger.port=9011 my_domain`

The command returns the following output:
`Using port 4850 for Admin.
Using port 80 for HTTP Instance.
Using port 7678 for JMS.
Using port 3702 for IIOP.
Using port 443 for HTTP_SSL.
Using port 3822 for IIOP_SSL.
Using port 3922 for IIOP_MUTUALAUTH.
Using port 8688 for JMX_ADMIN.
Using port 6668 for OSGI_SHELL.
Using port 9011 for JAVA_DEBUGGER.
On Unix platforms, port numbers below 1024 may require special privileges.
<cert info excluded>
Domain my_domain created.
Domain my_domain admin port is 4850.
Domain my_domain allows admin login as user "admin" with no password.
Command create-domain executed successfully.
`
## Expected Outcome
I expect the domain to be created with the specified jmx.port value (note that the supplied value is echoed in the command output - _"Using port 7678 for JMS."_)

## Current Outcome
However, when inspecting the resulting domains/my_domain/config/domain.xml, this is system property entry that is found:

`<system-property name="JMS_PROVIDER_PORT" value="7677" description="Port Number that JMS Service will listen for remote clients connection." />`

Another big issue (to me) is that the behavior changes depending on what domains are running. The default domain1 uses jms.port=7676. If I create the new domain when domain1 is running, the new domain is assigned jms.port=7677. However, if domain1 is NOT running, the new domain is assigned jms.port=7676

This makes script-based creation of domains challenging, since the state of the server alters the results of the creation script.

## Steps to reproduce
1) Clean install of Payara
2) Start domain1
3) Create new domain with above command
4) Inspect JMS_PROVIDER_PORT in domain.xml
5) delete my_domain
6) Stop domain1
7) Create new domain with above command
8) Inspect JMS_PROVIDER_PORT in domain.xml

## Environment ##

- **Payara Version**: Payara Server 4.1.1.154 #badassfish (build 270)
- **Edition**: Full
- **JDK Version**: OpenJDK Runtime Environment (build 1.8.0_111-b15)
- **Operating System**: Linux

**Comment by OndrejM** [comment] 2017-01-17 19:56
@eicheled thank you for reporting, but this issue has been fixed already in version 4.1.1.164. See the issue `1090/PAYARA-892/GLASSFISH-20606` in the [changelog](https://payara.gitbooks.io/payara-server/content/release-notes/release-notes-164.html). 

You are using much older version 154, have tried if the problem is fixed with the latest version of Payara Server?

**Comment by eicheled** [comment] 2017-01-17 20:12
Thanks for the reply. I know the version is older, but that is currently what we are running (not able to upgrade at this time). I did not test against a newer version. I searched for reported bugs like this before I posted, but did not find any, sorry for the duplicate.

**Comment by OndrejM** [comment] 2017-01-17 20:19
No problem :) Some bugs are not reported as github issues, they only appear as pull requests, like this one. All fixed issues (including PRs) are listed in the release notes for a particular release. However, it's always appreciated to test any bug with the latest public version ;-)

**Closed by OndrejM** 2017-01-17 20:19 UTC
Labels: 1:Wait, c:AlreadyFixed

**Comment by smillidge** [comment] 2017-01-18 09:25
@eicheled if you have a support contract you can ask for a downport of the fix to your specific Payara version.
