### ISSUE TITLE
deploy application exception

### ISSUE THREAD

**Issue by zhangmeng0426** [payara/Payara#1583] opened 2017-05-09 09:15 UTC
# Description #
----------
  not all Environment report this exception, no regular

## Steps to reproduce (Only for bug reports) 

deploy project 
asadmin deploy --port 4848 com.xxxx.war

[2017-05-09T11:50:00.362+0800] [Payara 4.1] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=70 _ThreadName=deployment-jar-scanner] [timeMillis: 1494301800362] [levelValue: 1000] [[
  Exception while visiting java/lang/Object.class of size 1497
java.lang.NullPointerException
        at org.glassfish.hk2.classmodel.reflect.impl.TypesImpl.getType(TypesImpl.java:81)
        at org.glassfish.hk2.classmodel.reflect.impl.ModelClassVisitor.visit(ModelClassVisitor.java:131)
        at org.glassfish.hk2.external.org.objectweb.asm.ClassReader.accept(ClassReader.java:622)
        at org.glassfish.hk2.external.org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
        at org.glassfish.hk2.classmodel.reflect.Parser$5.on(Parser.java:360)
        at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleEntry(ReadableArchiveScannerAdapter.java:165)
        at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:127)
        at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:345)
        at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:68)
        at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:304)
        at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:293)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
]]

## Context (Optional)

    web project 

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**:  Web
- **JDK Version**: 8 u121 - Oracle
- **Operating System**:Linux 5.8 5.10 7.2

**Comment by mikecroft** [comment] 2017-05-10 20:41
Is this always with the same application? Can you upload it so we can reproduce the problem?

**Comment by zhangmeng0426** [comment] 2017-05-11 00:42
It so strange that this application deploy a  virtual machine  ,every time report this problem , but change a machine, identical envionment variables, no problem. test several machine, didn't found any rules.

cpoy a application from the problem application, deploy in ths same container , no problem

**Comment by fturizo** [comment] 2017-06-01 21:30
@zhangmeng0426, we need more details to help you on this issue. Can you upload a sample project on GitHub to help use identify the issue?

**Comment by mikecroft** [comment] 2017-06-13 10:39
Closing because this seems to be an environment specific issue and we can't reproduce it to fix it.

At a ***guess***, it looks like HK2 is trying to parse the object type of something and possibly can't find the requested type (since the method throwing the error is [TypesImpl.getType()](https://github.com/javaee/hk2/blob/14b92ddd06a69d71f80f354ed2c5bfba184cdd8d/class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/TypesImpl.java#L81).

If the application can be deployed successfully to other environments, I would recommend trying a fresh Payara Server installation (any existing domain or nodes directories can be either copied across to the new installation or referenced from their current location; a similar thing is described [in method 2 on this page in the docs](https://docs.payara.fish/documentation/user-guides/upgrade-payara.html))

**Closed by mikecroft** 2017-06-13 10:39 UTC
Labels: 1:Wait, Insufficient Detail, requestor unresponsive (1)
