### ISSUE TITLE
@Stateless @WebService does not inject CDI beans in SOAPHandler

### ISSUE THREAD

**Issue by baztian** [payara/Payara#1106] opened 2016-09-23 10:52 UTC
When I annotate a Soap webservice with @Stateless the SOAPHandlers won't inject CDI beans. Glassfish is also affected.

Minimal example:

```
@Stateless
@WebService
@HandlerChain (file = "/soap-handler-chain.xml")
public class HelloWorld {
    public String hallo(@WebParam (name = "who") String who) {
        return "Hello " + who;
    }
}

public class TestSOAPHandler implements SOAPHandler<SOAPMessageContext> {
    @Inject
    private Bean bean;
    @Override
    public void close(MessageContext ctx) {
    }
    @Override
    public Set<QName> getHeaders() {
        return Collections.emptySet();
    }
    @Override
    public boolean handleFault(SOAPMessageContext ctx) {
        return true;
    }
    @Override
    public boolean handleMessage(SOAPMessageContext ctx) {
        System.err.println("Bean=" + bean.foo());
        return true;
    }
}

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<javaee:handler-chains xmlns:javaee="http://java.sun.com/xml/ns/javaee">
    <javaee:handler-chain>
        <javaee:handler>
            <javaee:handler-class>me.ejb.mini.TestSOAPHandler</javaee:handler-class>
        </javaee:handler>
    </javaee:handler-chain>
</javaee:handler-chains>
```

**Comment by baztian** [comment] 2016-09-23 10:54
I'm not sure if this might be related to https://java.net/jira/browse/GLASSFISH-20658

**Comment by baztian** [comment] 2016-09-23 10:55
I'm not sure if this might be related to https://java.net/jira/browse/GLASSFISH-20658 and https://java.net/jira/browse/GLASSFISH-19493

**Comment by smillidge** [comment] 2016-09-25 20:03
Have you tried adding a Bean defining annotation on your SOAP handler e.g. @Dependent to see if it makes any difference?

**Comment by baztian** [comment] 2016-09-26 08:32
Thanks @smillidge @Dependent on the TestSOAPHandler doesn't make any difference. Using the same example as above but without @Stateless injection works.

**Comment by smillidge** [comment] 2016-09-26 08:53
OK thanks that narrows it down a bit

**Comment by fturizo** [comment] 2016-12-30 16:52
Hello @baztian, is this still a issue on your application with the newer version of Payara Server? If so, then let us know to reproduce the test case.

**Comment by baztian** [comment] 2017-02-13 15:26
Hello @fturizo, it is still a issue. You can reproduce it by creating the HelloWorld.class the TestSOAPHandler.class and the soap-handler-chain.xml with the javaee:handler-chains element as outlined in my issue. When the application is deployed you can call the Webservice (for example using SoapUI). With @Stateless there should be a NullPointer when accessing the CDI bean. Please note that the endpoint will be different if @Stateless is provided or not. See the related links I've posted previously for the details on why this happens.

Do you want me to provide a zip/jar or something?

**Comment by baztian** [comment] 2017-03-24 10:14
@smillidge what kind of "Test Case" do you need? Should it be an automated one. Or just some instructions on how to reproduce? Please also see my previous comment.

**Comment by smillidge** [comment] 2017-03-24 11:44
A simple maven project on GitHub that demonstrates the issue would be useful.

**Comment by fturizo** [comment] 2017-04-27 22:49
Greetings @baztian,

After doing some testing and research on the JAX-Ws specification, I found out that the **JAX-WS** specification indeed allows message handlers (both SOAP handlers and Logical handlers) to support resource injection. From section[ 9.3.1. Handler Lifecycle](http://download.oracle.com/otn-pub/jcp/jaxws-2_0-fr-eval-oth-JSpec/jaxws-2_0-fr-spec.pdf?AuthParam=1493152744_2600492f645ebceea0ddd0747add390d#subsection.9.3.1):

> The lifecycle of a handler instance begins when the JAX-WS runtime system creates a new instance of the
> handler class. **The runtime MUST then carry out any injections requested by the handler**, typically via the `javax.annotation.Resource` annotation. After all the injections have been carried out, including in the case where no injections were requested, the runtime MUST invoke the method carrying a
> `javax.annotation.PostConstruct` annotation, if present. Such a method MUST satisfy the requirements in **JSR-250** for lifecycle methods (i.e. it has a void return type and takes zero arguments). The handler instance is then ready for use.
> 
> ♦ Conformance (Handler initialization):
> After injection has been completed, an implementation MUST call the lifecycle method annotated with `PostConstruct`, if present, prior to invoking any other method on a handler instance

So in this case, handlers must support the injection of managed JEE resources (using either the `@Resource`, `@EJB`, `@Datasource` or other similar annotations). Keep in mind that the **JAX-WS 2.0** specification was devised around the year 2006 , way before **CDI** was conceived, which means that CDI injection and integration is not considered at all when using JAX-WS sepcial artifacts. Since JAX-WS is a very old API, I would recommend you to make the Bean component in your example a stateless EJB bean and use the @EJB annotation to inject it into the handler like this:

```java
public class TestSOAPHandler implements SOAPHandler<SOAPMessageContext> {
  @EJB
  private Bean bean;
  ...
}
```

I've tested this behavior on Payara Server and works without issues.

**Comment by fturizo** [comment] 2017-06-01 22:15
Greeting @baztian, I'm closing this issue since we haven't received a formal reply from you on the proposed workaround and the cause of the problem is clear enough and problems are present with Payara Server. If you have any other questions regarding this issue feel free to reopen the issue so we can resume discussion.

**Closed by fturizo** 2017-06-01 22:15 UTC
Labels: c:Misconfiguration
