### ISSUE TITLE
CMT transaction missing in sessionbeans/FISH-5896

### ISSUE THREAD

**Issue by rlfnb** [payara/Payara#5503] opened 2021-11-24 08:03 UTC
# Description #
----------

Calling EntityManagers commit() fails because No transaction ist available.

## Expected Outcome 

Calling em.commit() inside a SessionBean must always use the container managed transaction according top javaee specification.

## Current Outcome ##
If you persist an Entity From inside a Session Bean you get a TransactionException

## Steps to reproduce ## 

Create an Entity and a SessionBean and persist the Entity from inside a Session Bean 

## Environment ##

- **Distribution**: Server full and micro 2021.9 (2021.7 works)
- **JDK Version**: openjdk11/Zulu 11
- **Operating System**: tested on Linux

**Comment by rlfnb** [comment] 2021-11-26 10:13
I created a short PoC to speed up a possible solution.

[PoC.zip](https://github.com/payara/Payara/files/7607978/PoC.zip)

Unzip, mvn clean package payara-micro:bundle; java -jar target/PoC-1.0-SNAPSHOT-microbundle.jar and open a browser to http://localhost:8080/webresources/generic *peng*

with version 5.201 everything's working as expected. 5.2021.(7|8|9) fails. To make it more simple for you: If I remove the Named annotation it's working as well in 5.2021.9 but AFAIK its not forbidden to use Named within an EJB session bean, so it might look to me like a broken javaee contract?

**Comment by shub8968** [comment] 2021-12-03 18:55
Hi @rlfnb,

I am able to reproduce this issue. I have raised an internal issue with JIRA `FISH-5896`. Thanks. It may take a while to fix the issue. You are free to submit a PR to fix this issue if you feel confident to do so.

**Comment by shub8968** [comment] 2021-12-09 09:11
Hi @rlfnb,

This bug is a side-effect on how the  GenericResource class is implemented. Since the class is both annotated with @Named and @Stateless, then it's unclear for the container it should be treated as a CDI bean or as a pure EJB stateless bean, which is confusing and unnecessary since EJB beans are automatically and implicitly treated as CDI beans for injection purposes. What you need to do is to stick to one convention, i.e: define the class as an EJB:

@Stateless
@Path("generic")
public class GenericResource {
}

Or define it as a CDI bean and mark the corresponding method as transactional-enabled:

@Named
@Path("generic")
public class GenericResource {

    ...
    
    @GET
    @Produces(MediaType.TEXT_PLAIN)    
    @Transactional
    public String getText() {
        LogEntry entry = new LogEntry();
        em.persist(entry);
        return entry.toString();
    }
}
The specs don’t define what happens to applications when these scenarios are encountered, so they leave it to the provider to make a choice. It seems that in previous releases, the bean was automatically treated as an EJB, whereas now it is treated as a CDI bean and the method requires a transaction. For now, we are closing this issue.

**Closed by shub8968** 2021-12-09 09:11 UTC
Labels: Status: Accepted, Type: Bug

**Comment by rlfnb** [comment] 2021-12-10 14:07
Having a different view on it regarsing the spec is legit. Changing default behaviour should bei at least documented in the release notes?

**Comment by fturizo** [comment] 2021-12-15 20:43
@rlfnb, I'm afraid that what you state is not true. There are no comments on both the EJB and CDI specs about what happens when a bean class is annotated with both annotations. In fact, the CDI spec discourages doing this, since it already allows runtimes to treat existing EJBs as CDI beans in some contexts.
