### ISSUE TITLE
glassfish-web.xml scanning-exclude not working /CUSTCOM-64

### ISSUE THREAD

**Issue by IrminAuwerda** [payara/Payara#1536] opened 2017-04-18 10:53 UTC
# Description #
----------
I use Payara 171.1 full on a windows machine (like many developers in a large organization this is my designated development machine).

I have a dependency on a jar with classes with **Path** annotations because I use a client to connect to it. I want to exclude the jar with these classes from scanning so none of the classes are attempted to be instantiated; they are just interfaces, any attempt by CDI to create them will result in an exception. To do this I use the **scanning-exclude** tag in the **glassfish-web** xml.

This is my glassfish-web.xml in the war (located in WEB-INF folder):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app>

    <context-root>/</context-root>
    <parameter-encoding default-charset="UTF-8"/>
    <scanning-exclude>item-service-public-api*</scanning-exclude>

</glassfish-web-app>
```

The class I want to exclude is this one (it is part of the item-service-public-api-1.8.0.jar):

```java
package com.alphabet.service.itemcatalogue.api.item;

import com.alphabet.service.itemcatalogue.domain.PricedItem;
import java.util.List;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

@Path("/public/priced-items")
@Produces({"application/json"})
public interface PricedItemServiceRestSpecification {
    @GET
    List<PricedItem> list();
}
```

Now when I try to deploy the application:

```
asadmin deploy --contextroot quote-offer-service --name quote-offer-service `webapp/target/quote-offer-service-webapp.war
```

I get:

remote failure: Error occurred during deployment: Exception while loading the app:

```
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.apache.catalina.LifecycleException: org.jboss.weld.exceptions.DefinitionException: WELD-001508: Cannot create an InjectionTarget from [EnhancedAnnotatedTypeImpl] public abstract interface @Produces @Path class com.alphabet.service.itemcatalogue.api.item.PricedItemServiceRestSpecification as it is an interface. Please see server.log for more details.
Command deploy failed.
```

I have not tried this out on a Linux machine yet. So I'm not sure if it's a specific windows problem.

## Expected Outcome

The expected outcome is that the deployment succeeds and the `PricedItemServiceRestSpecification` is not scanned by the CDI system, as by the specification of the scanning-exclude documentation.

## Current Outcome

I get a `DefinitionException` that no `InjectionTarget` can be created for the `PricedItemServiceRestSpecification`.

Another thing that I noticed is that [the glassfish-xml DTD is updated at GitHub](https://github.com/payara/Payara/blob/master/appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-web-app_3_0-1.dtd), but [the specified location in the DTD](http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd) still holds the old DTD. Will this ever be updated?

When I tried this out with the old version 164 of Payara I got the same problem as in #1158:
```
Exception while deploying the app [quote-offer-service] : Illegal/unsupported escape sequence near index 13
^WEB-INF/lib\item-service-public-api*(-.*)?\.jar$
```

## Steps to reproduce (Only for bug reports) 

To reproduce, use Payara 171.1 on a Windows machine

1 -**  Start the domain

    asadmin start-domain

2 -**  Deploy the application to the domain

    asadmin deploy --contextroot quote-offer-service --name quote-offer-service webapp/target/quote-offer-service-webapp.war

- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 8 u65 - Oracle
- **Operating System**: Windows

**Comment by lprimak** [comment] 2017-04-18 19:29
Can you supply the server.log snippet with the exception and the full stack trace (including all causes) associated with the failure?
thanks

**Comment by fturizo** [comment] 2017-04-19 00:55
@IrminAuwerda, I could reproduce this error on Payara Server 4.1.171.1. This is an excerpt from the stack trace I got:

```
org.jboss.weld.exceptions.IllegalArgumentException: WELD-001508: Cannot create an InjectionTarget from [EnhancedAnnotatedTypeImpl] public abstract interface @Path @Produces @RequestScoped class fish.payara.support.gh1536.commoninterface.PricedItemServiceRestSpecification as it is an interface
	at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:81)
	at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:69)
	at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:53)
	at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanHk2Factory$2.<init>(AbstractCdiBeanHk2Factory.java:134)
	at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanHk2Factory.<init>(AbstractCdiBeanHk2Factory.java:116)
	at org.glassfish.jersey.ext.cdi1x.internal.GenericCdiBeanHk2Factory.<init>(GenericCdiBeanHk2Factory.java:58)
	at org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.bind(CdiComponentProvider.java:336)
	at org.glassfish.jersey.server.ApplicationHandler.bindWithComponentProvider(ApplicationHandler.java:1026)
	at org.glassfish.jersey.server.ApplicationHandler.bindProvidersAndResources(ApplicationHandler.java:955)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:522)
```

The stack trace actually reveals that it is Jersey(JAX-RS) the one that is trying to instantiate the bean using its CDI integration. The `scanning-exclude` definition in the _glassfish-web.xml_ is working fine since is preventing the interface from being scanned and processed as a CDI bean by **Weld**, but it doesn't prevent **Jersey** from recognizing it as a resource definition, and then trying to instantiate it as a CDI bean. 

This is actually the default behaviour according to the JAX-RS specification when not specifying the list of available resources so Jersey can scan them. By default, Jersey will scan all available `@Path` resources on both the WAR and bundled JARs. To solve this issue, simply override your `ApplicationConfig` class and specify only the resources your application will expose, like this:

```java
@ApplicationPath("/rest")
public class ApplicationConfig extends Application{

  @Override
  public Set<Class<?>> getClasses() {
  Set<Class<?>> classes = new HashSet<>();
  classes.add(PricedItemServiceImpl.class);
  return classes;
  }
}
```

**Comment by IrminAuwerda** [comment] 2017-04-19 06:58
@fturizo Thanks, although it is somewhat disappointing. It is exactly what I was trying to avoid; having to do an all-inclusion instead of excluding specifics from scanning. Extra manual work whenever you create something new sucks.

Back to using the `packages(String ...)` operation of the `ResourceConfig` :-(.

**Comment by fturizo** [comment] 2017-04-21 17:28
You are right @IrminAuwerda in that having to use Jersey definitions of packaging and scanning of resources can be cumbersome for some scenarios. I have proposed an enhancement request so that the `scanning-exclude` and `scanning-include` elements also take into account the scanning of JAX-RS resources as well to our developers, so be sure to check out new releases if this enhancement is implemented.

**Comment by fturizo** [comment] 2017-04-21 17:28
Raised internal JIRA issue `PAYARA-1608`

**Comment by IrminAuwerda** [comment] 2017-04-24 07:43
Thanks! I'll subscribe to that one.

**Comment by rdebusscher** [comment] 2019-12-05 14:15
Tracked by `CUSTCOM-64` now.

**Comment by AlanRoth** [comment] 2020-11-11 10:49
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:49 UTC
Labels: enhancement, status:accepted
