### ISSUE TITLE
Prevent caught Exceptions from being logged to server.log /CUSTCOM-62

### ISSUE THREAD

**Issue by baztian** [payara/Payara#1496] opened 2017-03-29 12:29 UTC
# Description #
----------

The *logger name* of *caught* system exceptions from EJBs should be configurable to allow logging to a different logger than for *uncaught* system exceptions. (Enhancement Request)

## Expected Outcome

I want to be able to log my EJBExceptions that have been caught in the application but have not being rethrown getting logged into a different logger than `javax.enterprise.system`. Therefore the enhancement proposal is to have a asadmin configuration that allows me to change the logger name for *uncaught* system exceptions.

This would enable me to set the log level for this logger to a lower value so that those exceptions don't appear in `server.log`. The default should be `javax.enterprise.system` to not interfere with existing configurations. *Caught* system exceptions should always be logged to `javax.enterprise.system`.

Having a separate logger allows for better customization, e.g. setting it to different log levels to be able to set up a monitoring/alerting.

## Current Outcome

An EJBException is is always logged to the `javax.enterprise.system`logger no matter if it's being caught by the application or not.

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: 8 u102 - Oracle
- **Operating System**: Linux

**Comment by fturizo** [comment] 2017-03-29 21:39
Hello @baztian,

Unfortunately, an `EJBException` and other **system exceptions** must be logged to the server's log by the EJB container. This is one of the Bean Deployer's responsibilities described in the EJB 3.2 specification: 

> 9.2 Bean Provider’s Responsibilities
> 
> ...
> 9.2.2 System Exceptions
> 
> ...
> Note that the `javax.ejb.EJBException` is a subclass of the `java.lang.RuntimeException`, and therefore it does not have to be listed in the throws clauses of the business methods. The container catches a  non-application  exception;  **logs it  (which can result in alerting the  System Administrator)**; and, unless the bean is a message-driven bean, throws the `javax.ejb.EJBException` or, if the web service client view is used, the `java.rmi.RemoteException.`

If you do want specific exceptions to be logged by the EJB container, these exceptions should be made into **application exceptions** or should be wrapped into one.

**Comment by mikecroft** [comment] 2017-03-30 18:53
Closing as wontfix since we need to meet the spec

**Comment by baztian** [comment] 2017-03-30 20:45
@mikecroft  and @fturizo understanding the EJB spec issue. Could you please evaluate my changed solution (edited description) and consider reopening the issue/feature request?

**Comment by mikecroft** [comment] 2017-03-30 21:31
Interesting idea! It reminds me of another enhancement request we had around logging:
https://github.com/payara/Payara/issues/143

Is this sort of behaviour something you've seen in other app servers/similar software?

**Comment by baztian** [comment] 2017-04-05 07:52
@mikecroft I don't have very detailed know-how in other app servers so I can't say how other app servers handle this.

**Comment by baztian** [comment] 2017-04-05 08:13
There is a new log attribute (for instance `com.sun.enterprise.server.logging.uncaughtEjbExceptionLogger` that defaults to `javax.enterprise.system`). I can change it to another logger and change the logging level as desired.

I think that's an even better solution. This way Payara's ensures to stay a drop in replacement for GF.

**Comment by fturizo** [comment] 2017-04-11 00:17
Hello @baztian,

I don't quite understand what you mean for a new log attribute. Would you be kind enough to give more details on this workaround? Do you think is enough to solve this situation or should we expand on the enhancement request?

**Comment by baztian** [comment] 2017-04-11 07:50
Sorry @fturizo for the confusion. I was going to write a longer comment and then changed my mind and only posted this fragment.

The comment about the new log attribute is a suggestion for an improvement to the enhancement request. Instead of logging to a different logger by default, payara logs to the same logger as before (`javax.enterprise.system`). The log attribute allows me to change it to another logger for which I can configure the level separately.

If this sounds good for you, I'll update my enhancement request once again.

**Comment by ggam** [comment] 2017-04-12 13:43
Just as an idea. WildFly offers an option to disable the default behavior of logging that exceptions.

Disabling it obviously is against the spec, but that's way it's enable by default.

**Comment by baztian** [comment] 2017-04-12 17:44
Thanks @ggam. If disabling the default behaviour means **uncaught** exceptions are still being logged that would be fine for me.
Still my proposal has the benefit of more fine grained control. I could still log caught exceptions but with a lower level.

**Comment by fturizo** [comment] 2017-04-19 01:26
Thanks for the clarification, @baztian. I've opened the internal JIRA issue PAYARA-1587 so the developers can work on implementing a new setting that can be used to change the default logger used by all system exceptions.

**Comment by baztian** [comment] 2017-04-19 08:54
Thank you @fturizo. Did I put enough emphasize on the distinction between *caught* and *uncaught* Exceptions? Both are system exceptions. So just changing the default logger used by *all* system exceptions wouldn't help me. I need a setting that allows me to change the logger for *uncaught* system exceptions alone.

**Comment by fturizo** [comment] 2017-04-26 01:33
@baztian, all uncaught exceptions that are thrown by an EJB business method are treated inherently as **system exceptions** by the EJB container unless they fulfil the requirement to be treated as application exceptions (checked exceptions declared using the `throws` clause or unchecked exceptions annotated with `@ApplicationException`). **Application exceptions** are ignored by the EJB container since they have to be explicitly be resolved by the client calling the EJB, as they are interpreted as business logic errors.

Taking this into account, there shouldn't be a problem by logging all _uncaught system exceptions_ to a specific logger with the enhancement request I documented.

**Comment by baztian** [comment] 2017-04-26 07:01
Thanks @fturizo. I know about the distinction between system and application exceptions. I should've put more emphasise that my enhancement request refers to the distinction of caught/uncaught system exceptions only. I was using the more specific term EJBExcpetion. System exceptions get wrapped in EJBExceptions automatically by the container.

That said I don't think that simply changing the logger for *all* system exceptions would help me in any way nor do I know in what use case that could help anyone.

I think I didn't really manage to make my requirement clear enough. Would it help to provide you with some example code?

**Comment by baztian** [comment] 2017-04-26 07:15
I've updated the description of the enhancement request to reflect the input from the conversation.

**Comment by rdebusscher** [comment] 2019-12-05 14:05
Tracked by issue `CUSTCOM-62`

**Comment by jamxval** [comment] 2020-05-29 21:46
Can I request to show compact stack trace frames, to me jboss is a black box, I don't want to know so many details, but 70% of printed stack trace frames are from JBoss, the frames are groups (JBoss and non-JBoss), in every JBoss sections, only few informative frames shown and others suppressed (or printed to another log as backup). In attached logs, JBoss's frames tell me my program crosses  2 boundaries, 1st is a BMT and 2nd is a CMT, other information is useless to me. As a comparison IBM WebSphere provides a FDC log for troubleshooting, I want raw logs are printed to FDC log and compact log printed to server.log when an optional indicator is enabled in current jboss configuration, this optional indicator can be applied to at least CMT exception and Tx-Timeout cases.

[raw.log](https://github.com/payara/Payara/files/4704473/raw.log)
[compact.log](https://github.com/payara/Payara/files/4704510/compact.log)

**Comment by AlanRoth** [comment] 2020-11-11 10:26
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:26 UTC
Labels: enhancement, status:accepted

**Comment by UlrichCech** [comment] 2023-02-07 14:52
I am currently facing the same problem, because any "lock-exception" is logged (and multiple times) in the Payara server.log and pollutes the log-file. The exception is catched, but it is logged in any case.

Is there some solution, I can mark the exception as catched or provide another configuration property, so the exception does not occur in the server.log?

https://forum.payara.fish/t/avoid-logging-of-caught-exception/426/4
