### ISSUE TITLE
SSL certificate has expired on Payara 5

### ISSUE THREAD

**Issue by yasass** [payara/Payara#4215] opened 2019-09-11 22:22 UTC
# Description #
----------

An SSL certificate has expired. From other issues i have seen to remove them - how do i know which one to remove and how?

## Expected Outcome

provide error before startup

## Current Outcome

[
  Version: V3
  Subject: CN=Class 3P Primary CA, O=Certplus, C=FR
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5
  Key:  Sun RSA public key, 2048 bits
  modulus: 21614364623234645301176979052165345431898293847960486915478489113641331309644631752003221165383118398140398886336016387390724896962665812867256887907245520366436021903224959533376678696719936735972067367920592968608491103081205372406043624400010083880772415904795029373948490802676779159314439078110930739868553466210514140689407010259951984397616006783494760981020892138542824737977628597898766038609349270744008280631843922769380819511751485857445066566834873801830547383948214472026533037321650013565965180311449002065019426293174492769711409600018705331909203823027179297493805317578775200581989013716669464825171
  public exponent: 65537
  Validity: [From: Wed Jul 07 20:10:00 IDT 1999,
               To: Sun Jul 07 02:59:59 IDT 2019]
  Issuer: CN=Class 3P Primary CA, O=Certplus, C=FR
  SerialNumber: [    bf5cdbb6 f21c6ec0 4deb7a02 3b36e879]
Certificate Extensions: 5
[1]: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:true
  PathLen:10
]
[2]: ObjectId: 2.5.29.31 Criticality=false
CRLDistributionPoints [
  [DistributionPoint:
     [URIName: http://www.certplus.com/CRL/class3P.crl]

## Environment ##

- **Payara Version**: 5
- **Edition**: 
- **JDK Version**: 8 
- **Operating System**: 
- **Database**:

**Comment by noscorpion** [comment] 2019-11-04 22:39
You could use a tool like KeyStore Explorer (https://keystore-explorer.org/) where you have a more visual representation of your certificates. Just open your cacerts.jks file with this tool remove the certificate and save the file. If there is a new certificate you can also import it with this tool.

**Comment by fturizo** [comment] 2020-02-06 19:32
Closing this issue as this is not a bug report. Please, address your question in the [official Payara Forum](https://groups.google.com/forum/#!forum/payara-forum) by raising a topic requesting assistance with the clearance of SSL certificates.

**Closed by fturizo** 2020-02-06 19:32 UTC
