### ISSUE TITLE
Fix GLASSFISH-19317

### ISSUE THREAD

**Issue by drupalspring** [payara/Payara#587] opened 2016-01-03 07:05 UTC
It seems that the problems of [GLASSFISH-19317](https://java.net/jira/browse/GLASSFISH-19317) still occurs. [This] (https://wiki.java.net/forum/topic/glassfish/glassfish/persistencecontext-ignored-library-jar-classes) describes the problem in detail.

Follow is the my summary :

```java
@ApplicationScoped
public class EntitiyManagerProvider {  

        @PersistenceContext(unitName="localTest")
  	private EntityManager entityManager;

        @Produces
  	@RequestScoped
  	public EntityManager getEntityManager() {
  		return entityManager;
  	}
}
```
Suppose `EntitiyManagerProvider` is packaged inside a JAR called `domain.jar`

`EntityManager` cannot be injected (i.e null) if the application is packaged as a EAR (i.e `EntitiyManagerProvider` is located in EAR 's `lib\domain.jar` )

 It works if the application is packaged as a WAR (i.e  `EntitiyManagerProvider` is located in `WEB-INF/lib/domain.jar`)

**Comment by mikecroft** [comment] 2016-01-04 09:12
Is your test case something that we can use to reproduce for ourselves? What version are you testing with?

**Comment by drupalspring** [comment] 2016-01-04 15:06
Hi Mike, I am using payara 4.1.1.154 .

 I am quite busy in these days . I hope I have time to provide a demo project to reproduce this problem in the weekend.

**Comment by mikecroft** [comment] 2016-01-04 15:08
Thanks, that would be very useful! Either a link to some source or an EAR/WAR would be good.

**Comment by abhirockzz** [comment] 2016-02-01 19:10
I failed to reproduce this on Payara 4.1.1.154. Here is the link to the [Maven project](https://drive.google.com/open?id=0BwKHHk1eqZaca3R3cU4xX3RDbUk)

Project setup
- WAR file with REST endpoint which injects an EJB (uses beans.xml)
- JAR file with CDI Producer to produce (default) JPA Entity Manager
- EJB JAR file which injects Entity Manager (using Producer)
- EAR file with EJB JAR and WAR and the CDI producer JAR in 'lib' directory

After downloading (if you choose not to import this in Netbeans directly)
- cd <your_download_dir>
- mvn clean install
- deploy EAR on Payara
- visit http://host:port/payara-587-web/payara/587

You should something like this - 'Inject EM --> com.sun.enterprise.container.common.impl.EntityManagerWrapper@4f3649f9' . This is nothing but a simple EntityManager.toString() being returned by the EJB

**Comment by mikecroft** [comment] 2016-03-24 16:24
Hi @drupalspring - using @abhirockzz's test project, I couldn't reproduce this on Payara 153 or 161, either on a standalone server or in a cluster.

Can you try Abhi's test case and confirm? It may be a similar but unrelated bug you're seeing, or some misconfiguration?

**Comment by mikecroft** [comment] 2016-09-07 15:32
Hi @drupalspring is this still a problem for you? Could you reproduce the problem with the test project that Abhi provided?

**Comment by mikecroft** [comment] 2016-09-12 11:01
Closing as cannot reproduce.

If this is still an issue @drupalspring, please reopen with a test case that shows the issue.

**Closed by mikecroft** 2016-09-12 11:01 UTC
Labels: c:PossibleBug, cannot reproduce, requestor unresponsive (1), Test Case Required
