### ISSUE TITLE
Deployment of EAR fails due to  java.lang.ClassCircularityError: org/eclipse/persistence/internal/weaving/WeaverLogger

### ISSUE THREAD

**Issue by krichter722** [payara/Payara#1500] opened 2017-03-30 11:42 UTC
# Description #
----------

Deployment of ear fails due to  `java.lang.ClassCircularityError: org/eclipse/persistence/internal/weaving/WeaverLogger.`. If the failure occurs due to a packaging/user error it'd be nice if the error message would be improved explaining the reason for the failure.

## Expected Outcome

Since the deployment works with Glassfish 4.1 it assume it should work with Payara.

## Current Outcome

`deploy` in `asadmin` fails due to

```
remote failure: Error occurred during deployment: Exception while preparing the app : org/eclipse/persistence/internal/weaving/WeaverLogger. Please see server.log for more details.
Command deploy failed.
```

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  deploy application

    ./asadmin deploy /home/richter/project1/project1-ear/target/project1-ear-1.0-SNAPSHOT.ear

### Samples

see https://richtercloud.de:451/index.php/s/Y9pyNrP8At0Su0Q for EAR

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 8 OpenJDK
- **Operating System**: Linux (Ubuntu 16.10 amd64)

**Comment by mikecroft** [comment] 2017-03-30 13:28
I reproduced this on 171.1 with the `payaradomain`, but not with `domain1`, interestingly, so I think this is probably down to a configuration issue with the payaradomain.

**Comment by mikecroft** [comment] 2017-03-30 14:27
OK, I think this is down to the classloader isolation and the fact that Eclipselink 2.6.4 is packaged with your app. Deleting the JAR from the EAR/lib folder allows it to deploy correctly.

While the classloader isolation is a pretty powerful feature, EclipseLink is something we've needed to patch, so the version we include by default is 2.6.4 + some of our own compatibility fixes. I would suggest you remove the dependency from your pom.xml entirely, or change the scope to `provided` if there's some proprietary EclipseLink feature you need to use.

**Comment by mikecroft** [comment] 2017-04-01 15:19
Hi @krichter722 have you verified this yourself yet? I'm closing this now in anticipation of a resolution since it was so clear-cut to reproduce and fix. Let me know if you still have problems.

**Closed by mikecroft** 2017-04-01 15:19 UTC
Labels: 1:Wait, c:Misconfiguration, reproducible

**Comment by krichter722** [comment] 2017-04-02 20:50
> OK, I think this is down to the classloader isolation and the fact that Eclipselink 2.6.4 is packaged with your app. Deleting the JAR from the EAR/lib folder allows it to deploy correctly.
>
> While the classloader isolation is a pretty powerful feature, EclipseLink is something we've needed to patch, so the version we include by default is 2.6.4 + some of our own compatibility fixes. I would suggest you remove the dependency from your pom.xml entirely, or change the scope to provided if there's some proprietary EclipseLink feature you need to use.

I can confirm that changing the EclipseLink Maven scope to `provided` works, thank you. However it's strange that the user needs to figure out that Payara is using the mentioned version of EclipseLink and change the scope. Even if the versions in the application and the server match (aside from patches on the Payara side), shouldn't the isolation work with runtime scope as well? Why is Payara using functionality which is provided by application - shouldn't it be one way only and the other way around? If any of that is true, the issue should remain open because _then_ changing is a workaround only.

**Comment by lprimak** [comment] 2017-04-02 22:24
The issue is that you are not providing _all_ EclipeseLink-required dependencies in your application, which actually defeats the purpose of app server.  If you have included all of EL's dependencies, it would have worked.  Otherwise you have different versions of different modules mixed in, which doesn't work

**Comment by krichter722** [comment] 2017-06-05 18:08
might be an EclipseLink issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=510204

**Comment by mikecroft** [comment] 2017-06-06 11:52
I don't think it is - WebLogic also uses EclipseLink so, as @lprimak says, the problem is that certain newer core parts of EclipseLink have been provided in that bugzilla, but not enough to override everything.

That user is trying to manually override the EclipseLink version in a very old WebLogic version. There is very likely some incompatibilities between the updated part of Eclipselink which he is trying to use and the parts in WebLogic which haven't been replaced. This version mismatch is probably causing the errors.
