### ISSUE TITLE
[INFO] message in server.log: Cannot find the resource bundle for the name

### ISSUE THREAD

**Issue by oxyuranus-scutellatus** [payara/Payara#4683] opened 2020-05-27 15:06 UTC
# Description #
----------

Using Payara 5.201 there are these messages in the server.log saying that:
* Cannot find the resource bundle for the name com.sun.logging.enterprise.resource.resourceadapter for class org.glassfish.resources.javamail.deployer.MailResourceDeployer using fish.payara.server.internal.resources.javamail-runtime
* Cannot find the resource bundle for the name com.sun.logging.enterprise.system.core.naming for class org.glassfish.resources.javamail.naming.MailNamingObjectFactory using fish.payara.server.internal.resources.javamail-runtime

Sending email seems not to be affected.

## Expected Outcome

No such log messages

## Current Outcome

```
[2020-04-30T12:52:33.234+0200] [Payara 5.201] [INFO] [] [] [tid: _ThreadID=79 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1588243953234] [levelValue: 800] [[
  Cannot find the resource bundle for the name com.sun.logging.enterprise.resource.resourceadapter for class org.glassfish.resources.javamail.deployer.MailResourceDeployer using fish.payara.server.internal.resources.javamail-runtime [214]]]
```
```
[2020-04-30T12:52:33.258+0200] [Payara 5.201] [INFO] [] [] [tid: _ThreadID=79 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1588243953258] [levelValue: 800] [[
  Cannot find the resource bundle for the name com.sun.logging.enterprise.system.core.naming for class org.glassfish.resources.javamail.naming.MailNamingObjectFactory using fish.payara.server.internal.resources.javamail-runtime [214]]]
```

## Steps to reproduce (Only for bug reports) 

May be: create-javamail-resource and create-resource-ref via asadmin

- create-javamail-resource --mailhost=${mail_host} --mailuser=${mail_user} --fromaddress=${mail_from_address} --property mail.smtp.port=${mail_port} --target=domain mail/xyz
- create-resource-ref --enabled=true --target=server mail/xyz

## Environment ##

* **Payara Version**: 5.201
* **JDK Version**: amazoncorretto:8u242
* **Operating System**: CentOS, Mac
* **Virtualization**: docker

**Comment by dmatej** [comment] 2020-05-27 17:46
Hi, thanks for reporting, but there are hundreds of such errors - they were generally caused by the refactoring between SGES2 and GF3 and also later since some 15 years ago, when developers moved code between modules, created new code, and also created tool for generating i18n messages, but they often forgot to move also messages in bundle properties and sometimes the resolution uses incorrect classloader or path.
Another problem causing this is asynchronous resolution of messages.

Currently we work on fixing several issues in logging system and fixing at least some of messages is a part of it. It is nearly impossible to fix all of them, but if you are able to report them this way, it is helpful too ;-)

**Comment by MatthiasScherrerFGCZ** [comment] 2020-10-07 14:18
I can confirm as I have exactly the same problem (also on Payjara 2020.4)
@oxyuranus-scutellatus Did you find any workaround?

**Comment by AlanRoth** [comment] 2020-11-16 17:32
Hi @oxyuranus-scutellatus, do you still have these errors in the latest version of Payara Community? I tried to reproduce it in `5.2020.6` but was not able too.

**Comment by oxyuranus-scutellatus** [comment] 2020-11-19 16:15
Seems better with Payara 5.2020.6. No more such INFO messages.

**Comment by AlanRoth** [comment] 2020-11-19 16:55
If you're happy with the latest release then I'll close this issue. If you still have any problems please raise a new issue. Thank you

**Closed by AlanRoth** 2020-11-19 16:55 UTC
Labels: Status: Pending, Type: Bug
