### ISSUE TITLE
Upgraded to 5.194, Arquillian Embeded Payara profile failed.

### ISSUE THREAD

**Issue by hantsy** [payara/Payara#4372] opened 2019-12-10 12:23 UTC
I created a Jakarata EE 8 starter project to initialise a Jakarta EE 8 project quickly. But when bump the Payara version to 5.194, the payara-embeded profile failed.

The logging details are here.
https://github.com/hantsy/jakartaee8-starter/runs/341510215

```bash
Dec 10, 2019 8:22:42 AM org.glassfish.hk2.classmodel.reflect.Parser$5 on
SEVERE: Exception while visiting org/jboss/arquillian/testenricher/resource/SecurityActions$GetTcclAction.class of size 1685
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.glassfish.hk2.classmodel.reflect.impl.ModelClassVisitor.<init>(ModelClassVisitor.java:57)
	at org.glassfish.hk2.classmodel.reflect.ParsingContext.getClassVisitor(ParsingContext.java:211)
	at org.glassfish.hk2.classmodel.reflect.Parser$5.on(Parser.java:336)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleEntry(ReadableArchiveScannerAdapter.java:165)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:127)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:321)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:44)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:280)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:269)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dmatej** [comment] 2019-12-11 10:41
Hi, have you tried newer arquillian plugin? 
https://mvnrepository.com/artifact/fish.payara.arquillian/arquillian-payara-server-embedded

**Comment by hantsy** [comment] 2019-12-11 12:16
Still failed after upgraded Payara arquillian plugin to 2.0(from 1.2). 
https://github.com/hantsy/jakartaee8-starter/runs/343726915

The former Payara 5.193.1 and Payara arquillian plugin 1.2 combination worked.

**Comment by jGauravGupta** [comment] 2019-12-12 17:46
Hi @hantsy,

Can you try to remove the `com.jayway.jsonpath:json-path` & `com.jayway.jsonpath:json-path-assert` dependencies from the classpath of Payara server embedded.

**Comment by hantsy** [comment] 2019-12-13 02:27
@jGauravGupta  **worked** when I commented out most of **test** dependencies and only included Arquillian and JUnit. 

But if I want to check the JSON result by JSON path assertions with Payara embedded, how can I do?

**Comment by jGauravGupta** [comment] 2019-12-13 08:07
Hi @hantsy,

Please use the `payara-bom` to resolve the dependency conflicts.

````
    <dependency>
        <groupId>fish.payara.api</groupId>
        <artifactId>payara-bom</artifactId>
        <version>${payara.version}</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
````

**Comment by hantsy** [comment] 2019-12-13 13:08
Great idea, @jGauravGupta .

**Comment by dmatej** [comment] 2019-12-14 17:35
If it would not help, actually we are fixing an issue with jersey-client used on the same classpath with payara-embedded* , which does not work with payara versions 5.193.1 and 5.194.

**Comment by hantsy** [comment] 2019-12-15 15:07
@dmatej It is released for test purpose?

**Comment by hantsy** [comment] 2019-12-16 03:41
@jGauravGupta I have checked the [Payara BOM documention](https://docs.payara.fish/documentation/ecosystem/maven-bom.html) with my project dependencies, and also tried to add the following codes:

```xml
<dependency>
            <groupId>fish.payara.api</groupId>
            <artifactId>payara-bom</artifactId>
            <version>5.194</version>
            <type>pom</type>
            <scope>import</scope>
 </dependency>
```
 I do not think there is a json-path-assert in the Payara BOM. 

But this conflict issue is caused by Payara 5.194, I am sure 5.193.1 worked.

**Comment by jGauravGupta** [comment] 2019-12-16 05:25
Hi @hantsy,

After adding `payara-bom`, you should not remove `json-path` or `json-path-assert` from pom.xml as its child dependencies (org.ow2.asm:asm) are causing classpath conflicts.

**Comment by rdebusscher** [comment] 2020-01-02 18:51
Hi,

We have also an internal issue related to JAX-RS and Payara Embedded, `CUSTCOM-70`.
If possible, can you create a small reproducer which shows the problem. That way, we can verify if the fix for that `CUSTCOM-70` issue also solves your problem.

Thanks
Regards
Rudy

**Comment by hantsy** [comment] 2020-01-03 04:51
@rdebusscher  Check out my [Jakarta EE 8 stater](https://github.com/hantsy/jakartaee8-starter), change the payara server version to 5.194, and run tests with `-Parq-payara-embedded`.

**Comment by rdebusscher** [comment] 2020-01-04 12:57
Hi @hantsy,

I did a download of the repo, the version is already 5.194 (https://github.com/hantsy/jakartaee8-starter/blob/6156c46f73564d46b588d237df2b1a41cbca8bed/pom.xml#L38)

>mvn clean integration-test -Parq-payara-embedded

```
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

```

What am I missing? There seems to be no problem.

**Comment by hantsy** [comment] 2020-01-05 03:19
Can you review the [Github Actions logs](https://github.com/hantsy/jakartaee8-starter/runs/341510215), and make sure you are using a JDK 8.

**Comment by rdebusscher** [comment] 2020-01-05 10:54
Hi @hantsy 

yes, the 2 JSON dependencies are active https://github.com/hantsy/jakartaee8-starter/blob/6156c46f73564d46b588d237df2b1a41cbca8bed/pom.xml#L102

The link you posted to the GitHub Action log is an old one using version 1.2 of Payara Arquillian dependency.

The logs from the latest run show a successful outcome (and is using version 2.0 of Payara Arquillian) see https://github.com/hantsy/jakartaee8-starter/commit/6156c46f73564d46b588d237df2b1a41cbca8bed/checks?check_suite_id=374254935

**Comment by hantsy** [comment] 2020-01-05 11:47
@rdebusscher In the latest commit, I have commented out JSON path dependencies.  If I removed the comments, it will fail.

**Comment by rdebusscher** [comment] 2020-01-05 15:39
Yes, sorry. I was looking at the managed dependency.

The issue is that `jayway.jsonpath` brings in another (old?) ASM dependency which results in the failures.

By excluding this ASM, the tests succeed again.

  ```
          <dependency>
                <groupId>com.jayway.jsonpath</groupId>
                <artifactId>json-path</artifactId>
                <version>2.4.0</version>
                <scope>test</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

```
But I'm not sure the JSON Path is still fully functional then since it depends on `net.minidev.json-smart` which uses ASM to generate dynamic code instead of using Reflection for accessing class fields for JSON (de)serialization.

**Comment by OndroMih** [comment] 2020-02-07 13:28
Hi @hantsy, I can confirm that when I uncomment the json-path dependency I see 1 test failure.

A solution for me is to include the Payara BOM in the pom.xml file as documented here: https://docs.payara.fish/documentation/ecosystem/maven-bom.html

```
    <dependencyManagement>
        <dependencies>
        <dependency>
            <groupId>fish.payara.api</groupId>
            <artifactId>payara-bom</artifactId>
            <version>5.194</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
```

Then all tests pass. It's probably because the BOM file brings in a newer version of the asm artifact.

As there's a simple solution I'm going to close this issue. We always recommend using Payara BOM, especially when having issues with artifact conflicts.

**Closed by OndroMih** 2020-02-07 13:28 UTC
Labels: c:ConfirmedBug
