### ISSUE TITLE
On restart: javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class

### ISSUE THREAD

**Issue by webelcomau** [payara/Payara#1162] opened 2016-11-03 02:34 UTC
_[EDIT: I think I've already found the cause. It seems to happen when restarting Payara when JVisualVM is already running, and was attached to a previous Payara server execution. It might not be a Payara problem at all]_

# Description #
----------

On restart (with or without osgi cache clear) get error:

`Severe:   javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder: java.lang.ClassNotFoundException: com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder ..
`
Payara and web apps still run, not sure whether error has any adverse effects.

## Expected Outcome

No error logging (expect some kind of info message about MBeanServerBuilder instead).

## Current Outcome

```
Launching GlassFish on Felix platform

javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder: java.lang.ClassNotFoundException: com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:503)
	at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:539)
	at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:316)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:231)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:469)
	at sun.management.jmxremote.ConnectorBootstrap.startLocalConnectorServer(ConnectorBootstrap.java:533)
	at sun.management.Agent.startLocalManagementAgent(Agent.java:138)
	at sun.management.Agent.startAgent(Agent.java:260)
	at sun.management.Agent.agentmain(Agent.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl._jrloadClassAndStartAgent(InstrumentationImpl.java:388)
	at com.zeroturnaround.jrebelbase.reorder.a.invoke(SourceFile:69)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.ClassNotFoundException: com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:446)
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:488)
	... 19 more
Exception thrown by the agent : javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder: java.lang.ClassNotFoundException: com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl._jrloadClassAndStartAgent(InstrumentationImpl.java:388)
	at com.zeroturnaround.jrebelbase.reorder.a.invoke(SourceFile:69)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.RuntimeException: javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder: java.lang.ClassNotFoundException: com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder
	at sun.management.Agent.error(Agent.java:516)
	at sun.management.Agent.startAgent(Agent.java:266)
	at sun.management.Agent.agentmain(Agent.java:128)
	... 10 more
Caused by: javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder: java.lang.ClassNotFoundException: com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:503)
	at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:539)
	at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:316)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:231)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:469)
	at sun.management.jmxremote.ConnectorBootstrap.startLocalConnectorServer(ConnectorBootstrap.java:533)
	at sun.management.Agent.startLocalManagementAgent(Agent.java:138)
	at sun.management.Agent.startAgent(Agent.java:260)
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:446)
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:488)
	... 19 more
Agent failed to start!
...
Info:   Created virtual server server
Info:   Created virtual server __asadmin
...
Info:   Loading application [__admingui] at [/]
Info:   Loading application __admingui done in 5,794 ms
```

## Steps to reproduce (Only for bug reports) 

Preface: I can't recall this happening on initial install of Payara, so something seems to have changed. Seems to have happened since I last used the __admingui app (but not sure). **Also happens on Glassfish4.1.1.**

1. Delete /generated and /osgi-cache folders (not sure whether this is relevant, but I know I did this because there as a lockup "Error in linked security policy' state, and this is known to clear it).
 
2. _[EDIT: Run JVisualVM **BEFORE** restarting Payara. It might need also to have been opened vs (attached to) a previous Payara execution]_

3. Restart Payara in NetBeans IDE. The error is seen in the Payara log window in NetBeans.

## Environment ##

- Payara41 (163 Full) and very similar on Glassfish4.1.1
- jdk1.8.0_102
- Mac OS X 10.10.5
- NetBeans8.1
- _[EDIT: JVisualVM 1.8.0_102]_

**Comment by chrjohn** [comment] 2016-11-03 06:43
We also have these kinds of errors when we try to connect via JMX to Payara while it is starting.

**Comment by fturizo** [comment] 2016-12-01 16:43
@webelcomau, were you able to found the cause for this issue? Was it related to restarting _JVisualVM_ while the server is running?

**Comment by chrjohn** [comment] 2017-01-19 09:08
In our environment it happens almost every day when starting Payara (it was stopped before, so we were not doing a quick restart). Our own monitoring tool uses JMX to connect to Payara. But apart from the Exception everything seems to work normally.

**Comment by fturizo** [comment] 2017-01-25 00:22
Hi, @chrjohn.

Is this error happening with just the freshly installed server or do you have some applications deployed on it? Let us know so we can work with a reproducible case.

**Comment by chrjohn** [comment] 2017-01-25 08:08
Hi @fturizo , I was only jumping in because we have the same "problem".
We have applications deployed to our server but nothing that does JMX stuff. We are only accessing some of the MBeans in Payara from an external application to get information about memory, message queues etc.
But I have no reproducible test case at hand, sorry

**Comment by fturizo** [comment] 2017-04-27 22:53
Greetings @chrjohn,

As I recall there were some JMX fixes and improvements included in the latest release of Payara Server (4.1.1.171.1). Can you test if this release fixes this particular issue? Since we don't have a reproducible test case, it would be good to know first if the issue is still present.

**Comment by chrjohn** [comment] 2017-04-28 08:33
Sorry, cannot test that at the moment since it is not reproducible for me and only occurs spradically in our non-dev environments (since they are monitored). Those environments are using Payara 4.1.1.171.0.1 and still face this issue.

**Comment by fturizo** [comment] 2017-09-19 23:06
Closing this issue since original poster was unresponsive and couldn't get a reproducible test case.

**Closed by fturizo** 2017-09-19 23:06 UTC
Labels: c:PossibleBug, Test Case Required
