### ISSUE TITLE
localhost (127.0.0.1) used for remote EJB references

### ISSUE THREAD

**Issue by teefal** [payara/Payara#1226] opened 2016-12-11 17:50 UTC
This long-standing bug has new relevance due to host/IP configuration issues with Amazon's EC2.

## Expected Outcome

I want to connect to a Payara 164 Full server on LINUX using a remote EJB connection from a standalone client.  Doing a standard lookup should return the stub for remote use, as in:

InitialContext aCtx = new InitialContext();
EjbStub aRetVal = aCtx.lookup( "java:global/appName/BeanName!com.example.BeanInt"  );

## Current Outcome

The lookup call never returns.  Using Wireshark, it's clear this is because the hostname/IP returned by Payara is 127.0.0.1, which won't work.  

The longstanding workaround for this bug was to put the EXTERNAL IP for the hostname in /etc/hosts.  This works fine everywhere except Amazon EC2, where doing so prevents Payara from starting at all, likely because of some DNS resolution problems. 

This *works* on systems with straightforward DNS, such as locally on Mac/Linux, providing you can change the /etc/hosts file to map the hostname to an external IP.

Yes, I opened up all ports, so it's not the firewall.  
Yes, I tried changing the addresses in domain.xml for both the main server and the IIOP listener.
Yes, I tried using java.rmi.server.hostname with a variety of IPs & hostnames.

## See also

Here's more context from other bug reports:

https://java.net/jira/browse/GLASSFISH-4051

http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4665037

https://issues.apache.org/jira/browse/JCS-40

Note the recommendations from the last comment of the first link:

"If the ORB code does a lookup, and gets back 127.0.0.1, it should know that is useless... and shouldn't return it. Perhaps you could just return the hostname instead, or look at the initial incoming connection, and return the IP address that was used there."

## Environment ##

- **Payara Version**: 416
- **Edition**: Full
- **JDK Version**: Oracle JDK 8u112
- **Operating System**: Amazon Linux (CentOS variant)

**Comment by lprimak** [comment] 2016-12-11 21:41
Have you tried to set ```org.omg.CORBA.ORBInitialHost``` to your desired hostname?

**Comment by teefal** [comment] 2016-12-12 14:09
lprimak, yes, that's how the EJB connection is made.  It's actually returned data from the initial connection, hence my results from Wireshark.

**Comment by fturizo** [comment] 2016-12-12 15:50
@teefal, regarding the Payara starting issue on Linux, for the server to start on an EC2 instance, you must set the _INTERNAL_ IP address of the instance instead of the _EXTERNAL_ one on the _/etc/hosts_ file. The hanging out of the remote **EJB**  is a known bug on the **CORBA** modules inherited from Glassfish 4.x. Our developers are aware of this bug and are working on it. 

Keep in mind that this bug is caused by some design flaws for multi-home environment network scenarios so fixing it will take some time.

**Comment by fturizo** [comment] 2016-12-12 15:51
The behavior of this bug is the same exhibited described on the JIRA issue **PAYARA-798**

**Comment by teefal** [comment] 2016-12-12 16:31
fturizo, are you saying that remote EJB on EC2 is impossible at this point?

IE, if I need an INTERNAL IP for payara to start, and remote EJB will then report that internal IP when connections are made ... I'm I out of luck?

**Comment by lprimak** [comment] 2016-12-12 16:56
@teefal as a workaround, please set ```org.omg.CORBA.ORBInitialHost``` on the _server_ to the internal AWS IP address.  This may help.

**Comment by teefal** [comment] 2016-12-12 17:31
lprimak, I tried org.omg.CORBA.ORBInitialHost on the server, with both the private AWS IP and the public one.  I even tried the official domain name, which resolves to different IPs privately and publicly.  

In each case, Wireshark told me that the initial lookup had a IIOP:Profile_host of the private server IP, so none of the changes had an effect.

Put simply, Payara tells my client to use `hostname -i` no matter what.  Since I cannot get `hostname -i` to resolve to a public-facing IP and still have Payara start, I'm not sure what to do.

**Comment by teefal** [comment] 2016-12-12 17:41
@fturizo by "you must set the INTERNAL IP address of the instance instead of the EXTERNAL one on the /etc/hosts file" do you mean that you could do something like this ...

<node name="localhost-storymill" install-dir="${com.sun.aas.productRoot}" type="CONFIG" node-host="1.2.3.4"></node>

where 1.2.3.4 is the AWS internal IP. And then do this in /etc/hosts...

4.3.2.1  myhostname

where 4.3.2.1 is the AWS external IP?

(tried this and it didn't work, but I'm sure I'm missing something)

**Comment by lprimak** [comment] 2016-12-12 17:48
Ok, I think I get it now, @fturizo is exactly right about the issue, it's something that we are aware of and working on

**Comment by fturizo** [comment] 2016-12-12 19:55
@teefal, yes for the moment communicating to a remote EJB deployed on EC2 instances is not possible due to their multi-homed network arrangement. As you noticed when sniffing the packets with _Wireshark_, the **IIOP:Profile_host** property in the _GIOP_ packets is set incorrectly. This is the CORBA bug I was referencing earlier. 

We'll let you know when we have a solution available for our quarterly release.

P.S: The JIRA ID is for reference only since our JIRA is internal only.

**Comment by teefal** [comment] 2016-12-14 13:16
@fturizo Is it possible to force the Payara to use an IP, in a manner similar to java.rmi.server.hostname or some other setting?

**Comment by lprimak** [comment] 2016-12-14 16:33
Try setting system property ORBServerHost
```-DORBServerHost```

**Comment by teefal** [comment] 2016-12-14 17:10
Tried both -DORBServerHost and -Dcom.sun.CORBA.ORBServerHost and both gave back the same private IP for IIOP:Profile_host

**Comment by fturizo** [comment] 2016-12-14 17:17
@teefal, have you tried to set the EXTERNAL IP address of the instance in the `orb-listener-1`? By default is  assigned to _0.0.0.0_, which forces the server to use an available address from the OS.

**Comment by teefal** [comment] 2016-12-15 10:39
@fturizo When I use the external IP (the 52.x one), I get:

[2016-12-15T05:18:29.286-0500] [Payara 4.1] [SEVERE] [] [javax.enterprise.resource.corba.org.glassfish.enterprise.iiop.impl] [tid: _ThreadID=22 _ThreadName=RunLevelControllerThread-1481797092636] [timeMillis: 1481797109286] [levelValue: 1000] [[

java.net.BindException: Cannot assign requested address (Bind failed)

**Comment by teefal** [comment] 2016-12-15 10:42
However, when I use the multi-homed domain (ec2-52-12-34-567compute-1.amazonaws.com) instead of 0.0.0.0, it works!

I have definitely tried all domains/IPs in all locations (all the 0.0.0.0's and addresses and hosts in domain.conf), though perhaps keeping everything local *except* the IIOP one did the trick.

Looks like we have a workaround ... use amazon's dual domain (internal on the inside, external on the outside).

**Comment by teefal** [comment] 2016-12-15 12:28
Wow, my app is completely working now.  Only took me only 39 hours to get there, though admittedly, half of this time was upgrading to JEE 7 and mostly implementing a web service interface as an alternative to EJB. :)

**Comment by fturizo** [comment] 2016-12-15 17:26
Glad to know it worked @teefal, I never tried to use the custom AWS domain name for the EC2! You probably have it considered already but I recommend setting a proper domain name for the instance if that is possible as well. I'm leaving this issue open in the meantime since the default configuration should allow remote **EJB**s to connect to the server nevertheless.

We'll notify you when a proper fix is available on our releases.

**Comment by teefal** [comment] 2016-12-15 20:34
@fturizo We originally had our own domain name, and I've just put it back. Really have no idea what changed from the dozens of earlier attempts to now ... could just be this is the first time using Payara with the right combination of hosts (just started using it this week).

For the record, I can use my own sub.example.com host specified in the node line as well as all the address/0.0.0.0 fields.  My internal /etc/hosts points to the internal IP and my external resolves to the public IP.  Not sure why this didn't work to begin with.

**Comment by lprimak** [comment] 2017-07-06 01:11
This should be fixed in .172 release

**Closed by lprimak** 2017-07-06 01:11 UTC
Labels: 2:WithDev, c:ConfirmedBug, upstream bug

**Comment by thabach** [comment] 2018-07-13 07:53
This approach also seems to work out for Payara hosted remote EJBs running in a Kubernetes Pod (with the app server having its ORB port  „bound“ via hostPort to the underlying host running the pod), allowing for cluster-external clients under the condition of such clients being able to address the host directly (i.e. without any additional NATing).
