### ISSUE TITLE
Resource adapter stopped + recreated after MDB /CUSTCOM-86

### ISSUE THREAD

**Issue by RedeemerSK** [payara/Payara#2386] opened 2018-02-10 15:32 UTC
# Description #

When deployed app contains JCA resource adapter, _glassfish-resources.xml_ that amongst other things defines `resource-adapter-config` and also message driven bean set up to use the configured resource adapter, during deployment, MDB is first successfully created and put to service (even consumes messages) but then gets stopped immediately.

Looks like a deployment order issue.

## Expected Outcome

MDB should not be stopped and continue to receive messages.

## Current Outcome

Because resource adapter that was created during MDB initialization is stoped during deploy right after MDB is created and put to service, MDB becomes effectively stopped / disabled.

Guy that stops the MDB (that was initialized properly and was consuming messages): 
`org.glassfish.resourcebase.resources.listener.ResourceManager.PropertyChangeHandler.changed(TYPE, Class<T>, T)` 
called with type ADD

Above results in this guys stoping the MDB's resource adapter (ServerSession):
 `com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.reCreateActiveResourceAdapter(String)`

## Steps to reproduce
1. have EAR app with following things inside:
* JCA resource adapter for target jms broker (ActiveMQ)
* _glassfish-resources.xml_ descriptor that defines `resource-adapter-config`, `connector-connection-pool`, `connector-resource` and `admin-object-resource` for communication with target jms broker
* message driven bean using (by means of cfg in _glassfish-ejb-jar.xml_) ~~connection factory~~ resource adapter defined in _glassfish-resources.xml_
(see example project below)

2. have target JMS broker running

3. deploy EAR to payara

4. notice that MDB does not consume messages

### Samples

https://drive.google.com/drive/folders/0B02xDEkJefcwVFptMTNUaUhJTUk?usp=sharing
Publishes simple JAX-RS resource with single operation that puts message to a queue (name: bundled-rar-test) for testing.
3 secs after deploy, app sends a message to this resource (expects default port 8080).

## Context (Optional)

I'm trying to build small prototype JEE app for usage of JMS that does not require previous setup of Payara. That's why I wanted to bundle both JCA resource adapter itself and all the custom payara config int the app.

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full
- **JDK Version**: Oracle jdk1.8.0_162 (x64)
- **Operating System**: Windows 10 x64
- **External JMS broker**: ActiveMQ 5.15.3

**Comment by smillidge** [comment] 2018-03-09 20:24
Thanks for the test case.

**Comment by smillidge** [comment] 2019-04-25 20:15
Please try Payara 5 and see if it is still a problem there.

**Comment by RedeemerSK** [comment] 2019-04-27 04:50
> Please try Payara 5 and see if it is still a problem there.

Problem still on  Payara Server 5.191 #badassfish (build 94)

**Comment by rdebusscher** [comment] 2019-12-16 15:35
Tracked by `CUSTCOM-86`.

**Comment by AlanRoth** [comment] 2020-11-11 11:04
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:04 UTC
Labels: status:accepted
