### ISSUE TITLE
JSF commandLink does not show value from bean /CUSTCOM-100

### ISSUE THREAD

**Issue by schaarsc** [payara/Payara#3518] opened 2018-12-11 16:19 UTC
if a h:commandLink together with f:ajax is used within a h:dataTable and two dataTables are shown on the same page, then the var from dataTable is empty for the commandLink. commandButton does not show this behavior.
see example test_v_ajax.xhtml, id="thislinkfails"

the example has two dataTables, if we modify the example by using a different var for the second table the commandLink is rendered with the correct value
see test_v2_ajax.xhtml

if we remove f:ajax the commandLink will also show the correct value
see test_v.xhtml

tested with: Payara Server 5.184 #badassfish (build 89)

[reproducer.commandLink.tar.gz](https://github.com/payara/Payara/files/2668365/reproducer.commandLink.tar.gz)

**Comment by rdebusscher** [comment] 2019-12-18 07:59
I have created `CUSTCOM-100`.

**Comment by AlanRoth** [comment] 2020-11-11 11:26
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:26 UTC
Labels: status:accepted
