### ISSUE TITLE
Gogo Shell regression PAYARA-4183

### ISSUE THREAD

**Issue by chrjohn** [payara/Payara#4244] opened 2019-10-01 12:10 UTC
# Description #
----------

According to #3472 and #3450 respectively, the Gogo shell should work again since 5.191. However, it somehow is still/again broken on 5.193.
Left a comment here but no reply so far: https://github.com/payara/Payara/pull/3472#issuecomment-532382477

## Expected Outcome

Commands submitted to `asadmin osgi-shell` should work.

## Current Outcome

Commands simply return with no output.

```
~/tmp/payara5/bin$ ./asadmin osgi-shell
Use "exit" to exit and "help" for online help.
gogo$ help
gogo$ lb
gogo$ 
Command osgi-shell executed successfully.
```

Using workaround of osgi telnet shell:

```
~/tmp/payara5/bin$ telnet localhost 2019
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
____________________________
Welcome to Apache Felix Gogo

g! help
cm:createFactoryConfiguration
cm:getConfiguration
cm:getFactoryConfiguration

... and so on ...

g! lb
START LEVEL 2
   ID|State      |Level|Name
    0|Active     |    0|System Bundle (6.0.2)|6.0.2
    1|Active     |    1|OSGi resource locator bundle - used by various API providers that rely on META-INF/services mechanism to locate providers. (1.0.1)|1.0.1
    2|Active     |    1|Common Utilities (5.193.0)|5.193.0
    3|Resolved   |    1|javax.resource API (1.7.3)|1.7.3
    4|Active     |    1|nucleus.resources (5.193.0)|5.193.0

... and so on ...
```

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain production

2 -**  Start gogo shell

    ./asadmin osgi-shell

3 -**  try to list bundles (for example) inside the shell

    lb

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Full
- **JDK Version**: JDK8, JDK10
- **Operating System**: Ubuntu 19.04
- **Database**: n/a

**Comment by khasunuma** [comment] 2019-10-02 00:43
I confirmed it's a bug because I reproduced this issue on Payara Server 5.192 and 5.193. I've reported it as an internal issue (PAYARA-4183).

**Comment by chrjohn** [comment] 2019-10-02 12:00
Maybe it makes sense to add a unit test to ensure that this regression does not occur again. E.g. listing bundles should always generate output longer than x lines or something like that.

**Comment by RedeemerSK** [comment] 2020-04-04 16:04
Still broken on Payara 5.201 (tried on Win 10)

`osgi-shell` does not even enter the gogo shell, just prints the error right away.
```
asadmin> osgi-shell
Use "exit" to exit and "help" for online help.
remote failure: Invalid property syntax, missing property value: help
Invalid property syntax, missing property value: help
Usage: osgi [--session=session] [--session-id=session-id] [--instance=instance] [command-line]
Command osgi-shell failed.
```

`osgi lb` also still produces no output.

(both commands work fine on glassfish 5.0.1)

Am I right that in order to have remote shell to telnet to, one needs to download org.apache.felix.shell.remote JAR and manually put it into modules/autostart directory ?
At least that's what worked for me. Looks like this bundle is not part of gf/payara installation for some time now (found it in gf 3.1.2.2 only)

**Comment by AlanRoth** [comment] 2020-11-11 11:48
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:48 UTC
Labels: bug, reproducible, status:accepted
