### ISSUE TITLE
NPE calling a EJB 2.x method / FISH-887

### ISSUE THREAD

**Issue by Thihup** [payara/Payara#5041] opened 2020-12-09 20:52 UTC
# Description #
----------

I was trying to simulate a bug on the Open Liberty server and I tried to deploy the same application on the Payara and it failed too. Open Liberty related issue: https://github.com/OpenLiberty/open-liberty/issues/15244

## Current Outcome

```
javax.ejb.EJBException: javax.ejb.EJBException: javax.ejb.CreateException: Could not create stateless EJB
	at com.sun.ejb.containers.StatelessSessionContainer._getContext(StatelessSessionContainer.java:399)
	at com.sun.ejb.containers.BaseContainer.getContext(BaseContainer.java:2598)
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2019)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:135)
	at com.sun.proxy.$Proxy249.supportsSecurity(Unknown Source)
	at io.openliberty.sample.ejb2.SecurityProxy.<clinit>(SecurityProxy.java:22)
	at io.openliberty.sample.SampleApplication.init(SampleApplication.java:19)
	at javax.servlet.GenericServlet.init(GenericServlet.java:203)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1529)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:1166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:178)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.ejb.EJBException: javax.ejb.CreateException: Could not create stateless EJB
	at com.sun.ejb.containers.StatelessSessionContainer$SessionContextFactory.create(StatelessSessionContainer.java:653)
	at com.sun.ejb.containers.util.pool.NonBlockingPool.getObject(NonBlockingPool.java:219)
	at com.sun.ejb.containers.StatelessSessionContainer._getContext(StatelessSessionContainer.java:395)
	... 37 more
Caused by: javax.ejb.CreateException: Could not create stateless EJB
	at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:473)
	at com.sun.ejb.containers.StatelessSessionContainer.access$000(StatelessSessionContainer.java:100)
	at com.sun.ejb.containers.StatelessSessionContainer$SessionContextFactory.create(StatelessSessionContainer.java:651)
	... 39 more
Caused by: java.lang.reflect.InvocationTargetException
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1725)
	at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:419)
	... 41 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.jboss.weld.manager.BeanManagerImpl.getBean(BeanManagerImpl.java:1169)
	at org.glassfish.weld.services.JCDIServiceImpl.createInterceptorInstance(JCDIServiceImpl.java:407)
	at com.sun.ejb.containers.BaseContainer.createEjbInterceptors(BaseContainer.java:1795)
	at com.sun.ejb.containers.BaseContainer.createEmptyContextAndInterceptors(BaseContainer.java:1689)
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1703)
	... 42 more
```

## Steps to reproduce (Only for bug reports) 

1. Download the example: 
[example-ejb-cdi.zip](https://github.com/payara/Payara/files/5668586/example-ejb-cdi.zip)
2. `cd example-ejb-cdi && mvn clean install && cd war`
3. `./asadmin start-domain`
4. `./asadmin deploy $(example)/war/target/war.war`
5. Go to `http://localhost:8080/war/hello`

## Environment ##

- **Payara Version**: 5.2020.7
- **Edition**: Full
- **JDK Version**: 11 Hotspot AdoptOpenJDK
- **Operating System**: Linux

**Comment by AlanRoth** [comment] 2020-12-10 14:54
Hi @Thihup, 

I'm having trouble compiling your reproducer following your steps, could you provide some pointers and/or update the reproducer?

```
[ERROR] ../example-ejb-cdi/ejb/src/main/java/io/openliberty/sample/ejb2/SecurityProxy.java:[4,17] package javax.rmi does not exist
[ERROR] ../example-ejb-cdi/ejb/src/main/java/io/openliberty/sample/ejb2/SecurityProxy.java:[14,71] cannot find symbol
[ERROR]   symbol:   variable PortableRemoteObject
[ERROR]   location: class io.openliberty.sample.ejb2.SecurityProxy
```

Thank you,
Alan

**Comment by Thihup** [comment] 2020-12-10 14:56
Hi @AlanRoth. You can either compile with JDK 8 or add the RMI spec to the pom.xml.

**Comment by AlanRoth** [comment] 2020-12-10 15:01
Hi @Thihup,

Compiles fine in JDK8! I assumed you were compiling in JDK 11 since you have listed that under your environment, apologies!

**Comment by AlanRoth** [comment] 2020-12-10 15:08
Hi @Thihup,

Thank you for providing a reproducer, I have been able to reproduce the issue easily.

I have created `FISH-887` internally. I will mention, if you are able to create a PR yourself, we will be more than happy to accept it! Your issue may not be picked up for an extended amount of time, just due to the sheer amount of issues we currently have.

Thank you for your understanding,
Alan

**Comment by smillidge** [comment] 2020-12-10 15:31
can you try disabling implicit CDI scanning?

**Comment by Thihup** [comment] 2020-12-10 15:39
Hi @smillidge.
The same exception happens with Implicit CDI disabled.

**Comment by OndroMih** [comment] 2021-06-15 09:55
Hi @Thihup, we recommend that you disable CDI altogether in the beans.xml with [bean-discovery-mode=none](https://stackoverflow.com/questions/30863889/disable-scanning-of-cdi-beans-in-war).

I'm sorry but we need to close this issue because we can't afford to investigate this issue in Payara Community. Feel free to investigate yourself and raise a pull request with a fix. You're also welcome to sign a contract for Payara Enterprise and raise this as a support ticket to get it fixed.

**Closed by OndroMih** 2021-06-15 09:55 UTC
Labels: Status: Accepted, Type: Bug
