### ISSUE TITLE
JavaMail Session cannot target deployment group /FISH-55

### ISSUE THREAD

**Issue by vanuatoo** [payara/Payara#3850] opened 2019-03-17 16:34 UTC
# Description #
----------
Payara 5.181 introduced the notion of deployment groups to replace clusters.
It's expected that all enterprise resources can target a deployment group.

## Current Outcome
Until 5.183 it was not possible to target JDBC resource to deployment group
https://github.com/payara/Payara/issues/2699
Until 5.191 it was not possible to target JNDI resource to deployment group
https://github.com/payara/Payara/issues/3253

In 5.191 it's not possible to target JavaMail Session to deployment group
## Steps to reproduce (Only for bug reports) 
1. Create deployment group
https://blog.payara.fish/creating-a-simple-deployment-group
2. Create JavaMail Session
3. Indicate deployment group as a target for the JavaMail Session.
It gives error.

## Environment ##
- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: Oracle JDK 1.8u181
- **Operating System**: Linux

**Comment by rdebusscher** [comment] 2019-03-22 14:11
Hi,

I can confirm that the error message `Resource <name> has Invalid target to create resource-ref on <dg-name>.` appears when you select a Deployment Group on the New JavaMail Session page on the Web Administration Console.

I have created internal issue `PAYARA-3705` in order to fix this.

Thanks for reporting this issue

Regards
Rudy

**Comment by rdebusscher** [comment] 2019-12-19 14:52
Tracked by `CUSTCOM-35`

**Comment by AlanRoth** [comment] 2020-11-11 11:34
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:34 UTC
Labels: bug, status:accepted
