### ISSUE TITLE
Resource adapters' thread pools ignore max-pool-size

### ISSUE THREAD

**Issue by pdudits** [payara/Payara#1869] opened 2017-08-16 10:33 UTC
# Description #
----------

We recently upgraded to 172 and seen major performance regressions. Our system heavily uses MDBs, and only 5 threads (from `orb-thread-pool-1`) are processing requests. 

## Expected Outcome

Resource adapter thread pools should grow up to specified Max Pool Size in presence of work items.

## Current Outcome

ORB thread pools remain at Min Pool Size.

I tracked that down to rewrite of `com.sun.corba.ee.impl.threadpool.ThreadPoolImpl`, that uses a 
ThreadPoolExecutor with unbounded queue size, and that, per its documentation

> Using an unbounded queue (for example a LinkedBlockingQueue without a predefined capacity) will cause new tasks to wait in the queue when all corePoolSize threads are busy. *Thus, no more than corePoolSize threads will ever be created. (And the value of the maximumPoolSize therefore doesn't have any effect.)*

I cannot find in which patch release this change was done, but I will need to downgrade the module to prior version. Are there any API incompatibilties in corba's `internal-api` I should be aware of?

## Steps to reproduce (Only for bug reports) 

Submit more than _Min Queue Size_ work items to a work manager of `thread-pool-1`. The thread pool will not grow.

## Environment ##

- **Payara Version**: 4.1.1.172
- **Edition**: Full
- **JDK Version**: 8u144
- **Operating System**: Windows
- **Database**: Oracle

**Comment by pdudits** [comment] 2017-08-16 11:06
Reverting `glassfish-corba-internal-api` to `4.0.1-p3` restores previous functionality.

**Comment by lprimak** [comment] 2017-08-16 15:18
Can you confirm this is still present in .173?
I believe I made fixes for a similar issue.

**Comment by pdudits** [comment] 2017-08-16 15:45
Cannot test it directly as that was production system :)

But `glassfish-corba-internal-api 4.0.1-p8` still creates ThreadPoolExecutor with unbounded queue. So unless JCA WorkManager uses different thread pool manager, the bug must be present.
And the thread manager is not different in .173:

https://github.com/payara/Payara/blob/master/appserver/connectors/work-management/src/main/java/com/sun/enterprise/connectors/work/CommonWorkManager.java#L118

https://github.com/payara/Payara/blob/32f9e683cf01ed0b96de79648dafefa0a6087aa2/appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/util/S1ASThreadPoolManager.java#L192

**Comment by lprimak** [comment] 2017-08-16 21:50
I believe I tested that scenario in .173 but I will double-check

**Comment by lprimak** [comment] 2017-08-16 21:52
Assigned internal ```PAYARA-1960``` issue to track this

**Comment by pdudits** [comment] 2017-08-19 22:01
I created a test case for embedded Payara that can verify this in [payara-testcases/issue-1869](https://github.com/pdudits/payara-testcases/tree/e0bd2f9b531ac24af3216e16db18ed93dc1881d6/issue-1869).

Unfortunately 171 was last working release of `payara-embedded-all` in Central, and I can verify against my builds on Monday. But I believe this will fail with 172 onwards

**Comment by lprimak** [comment] 2017-08-29 21:21
Looking at the code in .173 (corba-p8) module I did fix this to submit a LinkedBlockingQueue that is bounded:

ThreadPoolImpl.java line 117:
```
    threadPool = new ThreadPoolExecutor(minSize, maxSize, timeout, TimeUnit.MILLISECONDS,
                new LinkedBlockingQueue<Runnable>(Math.max(maxSize * 100, Integer.MAX_VALUE)),
                new ORBThreadFactory(name, tg, defaultClassLoader, false));
```
so on the surface this issue should be fixed in .173
Next, I will try to test your example against .173 and see what kind of results I get

**Comment by lprimak** [comment] 2017-08-29 21:22
Looking at this again, perhaps maybe the limit in the blocking queue is too high...

**Comment by pdudits** [comment] 2017-08-29 22:15
Math.max(maxSize * 100, Integer.MAX_VALUE)


I consider this an unbounded queue.

Even it were maxSize *100, given minimum pool size of 5 and maximum size of
100, I need to have 10000 work items in the queue to get more threads. As
soon as there would be 10095 items, the work items would get... rejected?

That's why I'm afraid, that ThreadPoolExecutor does not offer good
characteristics to serve as WorkManager thread pool. It becomes extremely
rigid and hard to tune.


On Aug 29, 2017 23:22, "lprimak" <notifications@github.com> wrote:

Looking at this again, perhaps maybe the limit in the blocking queue is too
high...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/payara/Payara/issues/1869#issuecomment-325808248>, or mute
the thread

**Comment by lprimak** [comment] 2017-08-29 22:25
> Math.max(maxSize * 100, Integer.MAX_VALUE)
Yeah, you are right...
The issue is that the old pool has a lot of bugs that are basically impossible to debug (~20 years old) hence the reason we replaced it in the first place.  It was randomly hanging under load for one of our customers.

ThreadPoolExecutor replacement fixed that.

I believe that I can modify (override a couple of methods) of the ThreadPoolExecutor to prefer to create threads upto maximum rather than to prefer the queue, which should fix the problem.
What do you think?

**Comment by lprimak** [comment] 2017-08-29 22:32
Basically, the issue is that ThreadPoolExecutor prefer to queue items rather than to create threads that are greater than core and less than the maximum.  We need it to prefer to create threads instead, and then use the queue

**Comment by pdudits** [comment] 2017-08-29 22:41
I agree that this would be the right behavior, but I only got phone with me at the moment, so I cannot fully evaluate if TPE can be bent that way. 

I remember that setting large core pool size and letting core threads time out is almost similar, but first rule will keep spawning new core threads even if current ones are idle. 

Also grizzly's thread pools are fine, but that would mess the dependencies.

**Comment by lprimak** [comment] 2017-08-29 23:12
I've tried setting a large core pool size, but it didn't work for some reason (don't remember what it was) definitely didn't yield the correct behavior

**Comment by chrjohn** [comment] 2017-08-30 11:52
This reminds me of the following article. Maybe it is helpful.
https://dzone.com/articles/scalable-java-thread-pool-executor

Cheers,

**Comment by lprimak** [comment] 2017-08-30 14:51
Goor article @chrjohn That behavior did take me by surprise.
I resolved this by overriding TPE's execute() method and using a bit of reflection and setAccessible() to get to the private bits of TPE to make it all work

**Comment by lprimak** [comment] 2017-08-30 17:50
This will be fixed with CORBA -p9 module

**Closed** 2017-09-16 09:35 UTC
Labels: 4:Ready, c:ConfirmedBug, payara bug, reproducible
