### ISSUE TITLE
REST endpoints not found (404) in Arquillian "micro managed" container with Payara micro 5.182

### ISSUE THREAD

**Issue by ospringauf** [payara/Payara#2903] opened 2018-06-27 10:32 UTC
# Description #
----------

When testing a shrink-wrapped WAR with Arquillian "micro-managed" connector (Payara micro 5.182), the deployed REST endpoints cannot be called by the Arquillian client (error 404 not found). The same tests run successfully with Payara micro 5.181.

## Expected Outcome

REST endpoints should be available in Arquillian container. The provided example works with Payara 5.181, but fails with 5.182.

## Current Outcome

Server reports successful start and deployment of the WAR under test, but calls to the service endpoints result in a 404 error.

```
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.ospringauf.api.test.ArquillianApiTest
Jun 27, 2018 11:24:13 AM fish.payara.arquillian.container.payara.managed.PayaraMicroDeployableContainer deploy
INFORMATION: Starting Payara Micro using cmd: [java, -jar, c:\develop\.m2\repository\fish\payara\extras\payara-micro\5.182\payara-micro-5.182.jar, --deploy, C:\Users\****\AppData\Local\Temp\arquillian-payara-micro6053583088559680758\deployments\my-microservice.war, --port, 8299, --autoBindHttp, --autoBindRange, 1000, --nocluster, --showServletMappings]
...
[2018-06-27T11:24:30.718+0200] [] [ [1;92mINFORMATION [0m] [] [ [1;94mPayaraMicro [0m] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1530091470718] [levelValue: 800] 
{
    "Instance Configuration": {
        "Host": "****",
        "Http Port(s)": "8299",
        "Https Port(s)": "",
        "Instance Name": "payara-micro",
        "Instance Group": "no-cluster",
        "Deployed": [
            {
                "Name": "my-microservice",
                "Type": "war",
                "Context Root": "/my-microservice",
                "Mappings": {
                    "*.jspx": "jsp",
                    "/*": "com.ospringauf.api.MyApp",
                    "/ArquillianServletRunner": "ArquillianServletRunner",
                    "*.jsp": "jsp",
                    "/": "default"
                }
            }
        ]
    }
}

[2018-06-27T11:24:30.728+0200] [] [ [1;92mINFORMATION [0m] [] [ [1;94mPayaraMicro [0m] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1530091470728] [levelValue: 800] 
Payara Micro URLs:
http://****:8299/my-microservice

'my-microservice' REST Endpoints:
GET	/my-microservice/api/text
GET	/my-microservice/application.wadl

...
CALL: http://****:8299/my-microservice/api/text
InboundJaxrsResponse{context=ClientResponse{method=GET, uri=http://****:8299/my-microservice/api/text, status=404, reason=Not Found}}
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.968 s <<< FAILURE! - in com.ospringauf.api.test.ArquillianApiTest
[ERROR] getText(com.ospringauf.api.test.ArquillianApiTest)  Time elapsed: 0.93 s  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<404>
	at com.ospringauf.api.test.ArquillianApiTest.getText(ArquillianApiTest.java:68)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ArquillianApiTest.getText:68 expected:<200> but was:<404>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

## Steps to reproduce

run "mvn test" with the provided example (see below)

### Samples

see demo project [PayaraMicroArquillianDemo](https://github.com/ospringauf/PayaraMicroArquillianDemo)

## Context

Testing REST endpoints in a shrink-wrapped WAR with Arquillian (client mode).

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Micro
- **JDK Version**: 1.8.0_172 - Oracle
- **Operating System**: Windows 
- **Database**: none

**Comment by MattGill98** [comment] 2018-07-02 15:34
Hi @ospringauf,

This is a known issue, which is being addressed in `PAYARA-2878`. It is caused by using both `--port` and `--autobind`.

Kind regards,

Matt

**Comment by ospringauf** [comment] 2018-07-03 11:41
Thanks for the hint. 
Workaround: If I add
```
<payara.autoBindHttp>false</payara.autoBindHttp>
``` 
to the Arquillian/Surefire configuration, the test runs fine.

**Comment by smillidge** [comment] 2018-09-07 12:44
Fixed by https://github.com/payara/Payara/pull/2928

**Closed by smillidge** 2018-09-07 12:44 UTC
Labels: 2:WithDev, c:ConfirmedBug
