### ISSUE TITLE
java.lang.NullPointerException Using openapi using  @Operation(hidden = true)

### ISSUE THREAD

**Issue by jcrochavera** [payara/Payara#3265] opened 2018-10-12 18:19 UTC
java.lang.NullPointerException
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitAPIResponse(ApplicationProcessor.java:597)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitAPIResponses(ApplicationProcessor.java:617)
        at fish.payara.microprofile.openapi.impl.visitor.OpenApiWalker.processAnnotation(OpenApiWalker.java:234)
        at fish.payara.microprofile.openapi.impl.visitor.OpenApiWalker.processAnnotations(OpenApiWalker.java:193)
        at fish.payara.microprofile.openapi.impl.visitor.OpenApiWalker.accept(OpenApiWalker.java:162)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.process(ApplicationProcessor.java:157)

Steps to reproduce it:
@GET
@Operation(hidden = true)
public Response someEndpoint(){
.....
}

Payara Micro: 5.183

**Comment by Ykus** [comment] 2018-10-30 16:58
Hi,

I have tried to simulate this error, but without success.
It's working fine on current master version.

Kind regards,

Zdeněk Soukup

**Comment by MattGill98** [comment] 2018-11-01 15:05
Hi @jcrochavera,

This error doesn't look to me like one caused by the hidden operation. Instead, it seems to me that you have an `@APIResponses` annotation on a method that isn't recognised as a correct location. Possibly a custom JAX-RS method annotation or a subresource method?

Kind regards,

Matt

**Comment by jcrochavera** [comment] 2018-11-08 13:39
Hi @MattGill98 
No custom JAX-RS method annotation or subresource used, just the annotation @Operation(hidden = true), in version 5.183

Regards,
Julio Cesar

**Comment by MattGill98** [comment] 2018-11-08 17:05
Hi @jcrochavera,

I'm still unable to reproduce this. Can you provide a reproducer?

Kind regards,

Matt

**Comment by jcrochavera** [comment] 2018-11-08 17:46
Hi @MattGill98 
I can reproduce it with any endpoint annotated with  @Operation(hidden = true), in version 5.183

**Comment by MattGill98** [comment] 2018-11-09 09:54
Hi @jcrochavera,

As I've said, this information alone is not enough to reproduce the problem. Can you provide a WAR packaged application or src to produce this bug?

Kind regards,

Matt

**Comment by jcrochavera** [comment] 2018-11-09 12:21
Hi @MattGill98 
The src:

import org.eclipse.microprofile.openapi.annotations.Operation;

import javax.json.Json;
import javax.json.JsonObject;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

/**
 * Created by julio.rocha on 09-11-18.
 *
 * @author julio.rocha
 */
@Path("/example")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class ExampleResource {

    @GET
    @Path("/{name}")
    @Operation(hidden = true)
    public Response hello(@PathParam("name") String name) {
        JsonObject message = Json.createObjectBuilder()
                .add("message", "hello" + name)
                .build();
        return Response.ok(message).build();
    }
}

Regards & Thanks
Julio Cesar

**Comment by MattGill98** [comment] 2018-11-12 15:33
Hi @jcrochavera,

Thank you for the source. I actually get a different exception, but I suspect they're caused by the same issue. I've raised internal issue `PAYARA-3259` to address this.

Kind regards,

Matt

**Comment by jcrochavera** [comment] 2018-11-15 14:01
Hi @MattGill9:
Thank you very much

Regards,

Julio Cesar

**Comment by jbee** [comment] 2019-04-08 12:11
Fixed in #3852. Please retest after 5.192 release.

**Comment by jcrochavera** [comment] 2019-05-21 20:25
Awesome!!

**Closed** 2019-05-29 16:55 UTC
Labels: 0:Triaged, c:ConfirmedBug
