### ISSUE TITLE
Getting absolute path is actually calling getCanonicalPath()

### ISSUE THREAD

**Issue by bradvido** [payara/Payara#3706] opened 2019-02-08 01:27 UTC
This seems wrong, is it intentional that the absolutePath is using the canonicalPath?
https://github.com/payara/Payara/blob/5400417c32378c72477ab10e8b89f159d5b06775/nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java#L196

Related to https://github.com/payara/Payara/issues/2591

**Comment by smillidge** [comment] 2019-03-16 21:16
Not sure does it fix #2591 if you change it?

**Comment by OndroMih** [comment] 2020-02-04 14:21
Hi, since this is not a bug report or request for an improvement, I’m going to close this issue. Feel free to raise your suggestions as a pull request and we’ll review them there.

**Closed by OndroMih** 2020-02-04 14:21 UTC
Labels: c:Question, requestor unresponsive (1)
