### ISSUE TITLE
Payara Micro 5.184: Precompile JSPs on deploy /CUSTCOM-101

### ISSUE THREAD

**Issue by ricmzn** [payara/Payara#3627] opened 2019-01-17 19:02 UTC
# Description #

We can already accomplish this on Payara Full by passing `--precompilejsp` as a command-line switch when deploying an application, but Payara Micro doesn't seem to understand it, throwing an "invalid command line switch" error instead.

Since we run a web application as an Uber JAR, it would be preferable to to compile all of the jsp servlets when the Docker image is built, instead of only when a specific page is first loaded. This would avoid noticeable slowdowns after updates, and not require the entire JDK to be installed on a production server.

## Expected Outcome

When deploying a web application using the Payara Micro Jar, it should accept `--precompilejsp` as a command-line switch to compile all jsp in the application to servlets using the available Java compiler.

## Current Outcome

Payara Micro doesn't allow `--precompilejsp` as a command-line switch, and only compiles jsp servlets at runtime, when the application is accessed via remote requests. As a side-effect, it also cannot serve any jsp-based pages if a full JDK is not available.

## Context

I know, I know. Payara Micro is meant primarily for micro-services, so why should it work with compiled server pages, right? Well, it turns out that Payara Micro is still based on the Java EE Web profile, and is not only more easily configurable than Payara Full, but it's also faster on start-up and uses less memory overall, allowing for quicker development and more seamless updates. I wouldn't be surprised if we had to revert to Payara Full to get full support for this type of hybrid application, though.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Micro
- **JDK Version**: 8 - OpenJDK
- **Operating System**: Linux
- **Database**: Any

**Comment by smillidge** [comment] 2019-01-26 19:47
Looks like an interesting feature. Perhaps it could be passed on the commandline and all deployments precompiled. It will be tricky to specify it on a per-deployment basis.

**Comment by rdebusscher** [comment] 2019-12-18 08:26
I created internal issue `CUSTCOM-101`.

**Comment by AlanRoth** [comment] 2020-11-11 11:27
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:27 UTC
Labels: enhancement, status:accepted
