### ISSUE TITLE
Payara Micro crashes due to local hostname not resolving

### ISSUE THREAD

**Issue by mbering** [payara/Payara#2267] opened 2018-01-15 15:34 UTC
# Description #
----------

This issue appears when trying to use AWS "awsvpc" network mode, specifically with their new Fargate service in which you are required to use "awsvpc". I experiecend the same issue when trying to use the Elastic Container Service with "awsvpc" network mode as well.

## Expected Outcome

I would like some way to disable Payara from trying to resolve the hostname.

## Current Outcome

I can start the container on AWS and while at first it cannot resolve the hostname, the Payara continues to load, however when the application loads on it, it will fail due to now being able to resolve the hostname.

## Steps to reproduce (Only for bug reports) 

Launch Payara micro docker instance with "awsvpc" network mode using Fargate or ECS.

Log file is attached.
[error_log.log](https://github.com/payara/Payara/files/1632151/error_log.log)

## Environment ##

- **Payara Version**: 5.0.0.174-20170911.005352-20
- **Edition**: Micro
- **JDK Version**: 8
- **Operating System**: Linux / AWS Fargate
- **Database**: Postgressd

**Comment by mikecroft** [comment] 2018-01-15 15:51
Interesting! I wasn't aware that Fargate was released yet (I thought it required EKS) but apparently it runs on ECS too, but only in us-east-1 at the moment.

* Is this the official Payara Micro dockerfile with the 5-SNAPSHOT version? Looking at the build number, it looks like our auto-build script needs updating.
* Does this happen with Payara Micro 4.x as well?

I've a feeling this will be a bug with both 4.x and the latest 5.x as well, but we'll take a look.

**Comment by mbering** [comment] 2018-01-15 16:04
Yes, my dockerfile uses the official [dockerfile](https://hub.docker.com/r/payara/micro/~/dockerfile/) as a base. In the logs I have attached, I believe I created an uber jar with the test app and a jar file it requires, but I had the same issue before doing so as well.

I have not tried Payara Micro 4, but can.

**Comment by mbering** [comment] 2018-01-15 16:36
I get a similar failure when using Payara Micro 4.1.2.174.
[error_log_pm4.log](https://github.com/payara/Payara/files/1632354/error_log_pm4.log)

**Comment by faelwar** [comment] 2018-01-17 19:10
I had a similar issue when I was trying to deploy an application using docker swarm, I found a workaround it by setting the hostname to localhost when I create the service on docker swarm. My issue was that the returned hostname was my container id which will not resolve to a hostname.

Hope this can help you in some way.

**Comment by smillidge** [comment] 2019-04-25 20:17
Please try Payara 5 and see if it is still a problem there.

**Comment by OndroMih** [comment] 2020-02-04 14:03
Hi, since we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us a reproducer for the latest version of Payara Server or Payara Micro. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.

**Closed by OndroMih** 2020-02-04 14:03 UTC
Labels: 0:Triaged, Try On Latest Release, c:PossibleBug, payara-micro, requestor unresponsive (1), requestor unresponsive (2), v:Payara-4, v:Payara-5

**Comment by www-aiqu-no** [comment] 2020-03-08 20:14
I am having this issue when running payara-server-full as well.

It happens when I try to use CNI-driver (bridge) for running the container. The scheduler I'm using is Nomad v0.10.4.

#### Example jobfile for working container:
```hcl
job "payara-std" {
  datacenters = ["dc1"]
  group "payara" {
    task "payara" {
      driver = "docker"
      resources {
        network {
          port "http"  {}
          port "admin" {}
        }
      }
      config {
        image = "payara/server-full:5.201"
        port_map {
          admin = 4848
          http  = 8080
        }
      }
    }
  }
}
```

#### Example jobfile for failing container (cni bridge)
Error message is:
```bash
# stdout
java.net.UnknownHostException: 
[ERROR.log](https://github.com/payara/Payara/files/4303812/ERROR.log)

# stderr
/opt/payara/scripts/startInForeground.sh: line 73: exec: java.net.UnknownHostException:: not found
```
```hcl
job "payara-cni" {
  datacenters = ["dc1"]
  group "payara" {
    network {
      mode = "bridge"
      port "http"  { to = 8080 }
      port "admin" { to = 4848 }
    }
    task "payara" {
      driver = "docker"
      config {
        image = "payara/server-full:5.201"
        mounts = [
          {
            type = "bind"
            target = "/opt/payara/scripts/init.d/script.sh"
            source = "local/script.sh"
          }
        ]
      }
    }
  }
}
```

#### Example jobfile with "workaround" (cni bridge)
Adding startupscript for appending the dynamic /etc/hostname to /etc/hosts
Running as root in example (since root is required)
```hcl
job "payara-cni" {
  datacenters = ["dc1"]
  group "payara" {
    network {
      mode = "bridge"
      port "http"  { to = 8080 }
      port "admin" { to = 4848 }
    }
    task "payara" {
      driver = "docker"
      template {
        destination = "local/script.sh"
        data = <<-EOH
        #!/usr/bin/env bash
        echo 127.0.0.1 `cat /etc/hostname` >> /etc/hosts
        EOH
      }
      user = "root"
      config {
        image = "payara/server-full:5.201"
        mounts = [
          {
            type = "bind"
            target = "/opt/payara/scripts/init.d/script.sh"
            source = "local/script.sh"
          }
        ]
      }
    }
  }
}
```

Payara log is attached
