### ISSUE TITLE
Asadmin recorder: username and timestamp would be needed

### ISSUE THREAD

**Issue by z-mathe** [payara/Payara#1698] opened 2017-06-21 12:55 UTC
Hi,

The "Asadmin recorder" is a useful thing (for audit purposes as well), but it would be even better if the text file would be include minimum a timestamp and a username fields (before the native command, separated by e.g. "|"). In our company there are more users with admin privileges to use the admin console with own username/password, but it matters who and when gave it out the commands.

Thank you.

## Environment ##

- **Payara Version**: 4.1.1.172
- **Edition**: Full
- **JDK Version**: 8 u131 - Oracle
- **Operating System**: Windows

**Comment by mikecroft** [comment] 2017-06-26 09:56
Implementing this feature would mean that the resulting file could no longer be used as an asadmin multimode file without additional manual processing. This would effectively be a regression due to the loss of functionality, so I don't think this is something we would do.

If you are looking at audit functionality, there is an upcoming 2-part blog from @fturizo which will cover security auditing in Payara Server which you could probably apply here.

The asadmin recorder was never intended to fill such a function, so relying on it to give audit information could result in certain actions being missed in more complex edge cases which we (deliberately) did not consider.

@Pandrex247 - could you confirm my statements above before I close this?

**Comment by mikecroft** [comment] 2017-06-26 09:57
**Note:** The first part of the auditing blog will be available next week

**Comment by Pandrex247** [comment] 2017-06-27 13:22
@mikecroft 
Yep, you're correct, it was never written with audit purposes in mind. 
IIRC, the recorder also only records stuff from the Admin Console; manual asadmin commands aren't recorded - bit of an auditing hole!

**Comment by mikecroft** [comment] 2017-06-27 13:26
Cheers @Pandrex247 - that's a good point. If you subscribe to the blog @z-mathe you'll get alerts for when the security auditing blogs are out.

**Closed by mikecroft** 2017-06-27 13:26 UTC
Labels: wontfix
