### ISSUE TITLE
Admin Console LogView cannot view logs if formatted by JSON

### ISSUE THREAD

**Issue by yumix** [payara/Payara#1225] opened 2016-12-11 16:43 UTC
# Description #
----------

I found that Admin Console Log Viewer show nothing logs formatted by JSON.
I checked other format, _e.g._ ULF, ODL is work well.

## Expected Outcome

I think that Log Viewer should accept all log format supported by Payara Server. e.g. ULF, ODL, JSON.

## Current Outcome

Log Viewer shows any logs that format are supported by Payara Server. Certainly, Log Viewer works well in case of ULF and ODL format. But JSON format not work.

![loggersettings-to-json](https://cloud.githubusercontent.com/assets/1458895/21081442/5a18213c-c00a-11e6-9bf5-b9704397b83a.png)
![logviewer-json-nothing](https://cloud.githubusercontent.com/assets/1458895/21081444/642df930-c00a-11e6-80c5-ab14185850b9.png)
(Log File: server.log_2016_111T23-04-03 is JSON format.)

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  Configure an HTTP network listener in the admin console:

    Set 'Log File Logging Format' ODL to 'JSON'

3--** Restart the domain

4--**After the restart domain

    Log file logging format is already changed to JSON.
    Select 'View Log Files' from 'General Information', show Log Viewer but no log entry is listed.

### Samples

    Please trace to step to reproduce (above) in your environment.

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Web
- **JDK Version**: Oracle JDK 8 (update 112)
- **Operating System**: Windows 10 Professional

**Comment by khasunuma** [comment] 2016-12-12 08:20
I can reproduce it. But I'm afraid that LogViewer cannot show JSON-formatted logs without more improvement. (I think it's not a bug.)

com.sun.enterprise.server.logging.GFFileHandler.formatter in logging.properties is accepted UniformLogFormatter, ODLLogFormatter or custom formatters. GFFileHandler assumes JSONLogFormatter as a custom formatter and LogViewer cannot show any custom formatters.

If you want to show JSON-formatted logs on Admin Console, I suggest using not LogViewer but RawLogViewer.

**Comment by mikecroft** [comment] 2016-12-12 08:44
Thanks, @khasunuma, you're right, this is an enhancement request. I've created internal issue `PAYARA-1270` for the enhancement.

**Comment by smillidge** [comment] 2018-02-22 21:24
Fixed by #1943

**Closed by smillidge** 2018-02-22 21:24 UTC
Labels: 2:WithDev, c:Enhancement, reproducible
