### ISSUE TITLE
SSL configuration and the issue #4578 still persist on payara 5.201 build(512)

### ISSUE THREAD

**Issue by Chalfouh** [payara/Payara#4690] opened 2020-06-01 02:29 UTC
Description
----------
The server doesn't read correctly the path the the keystore, and could not update JVM
options from admin UI, even if i update the keystore path from the console it still doesn't read it correctly,"it updates it" but it has no effect.
Tried to delete the JVM options from the UI it doesn't take effects it deletes some entries but not all the entries.
and this issue:
[https://github.com/payara/Payara/issues/4578]

## Expected Outcome
it should be this path
**payara5-201\glassfish\domains\domain1\config\keystore.jks** 

## Current Outcome
it reads this path:
**payara5-201\glassfish\domains\domain1\keystore.jks** 

## Context (Optional)

[2020-05-31T11:09:40.888+0100] [Payara 5.201] [WARNING] [] [javax.enterprise.network.config] [tid: _ThreadID=134 _ThreadName=http-thread-pool::http-listener-4(3)] [timeMillis: 1590919780888] [levelValue: 900] [[
  GRIZZLY0050: SSL support could not be configured!
java.io.FileNotFoundException: I:\payara5-201\glassfish\domains\domain1\keystore.jks (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.glassfish.grizzly.config.ssl.JSSESocketFactory.getStore(JSSESocketFactory.java:311)
	at org.glassfish.grizzly.config.ssl.JSSESocketFactory.getKeystore(JSSESocketFactory.java:259)
	at org.glassfish.grizzly.config.ssl.JSSE14SocketFactory.getKeyManagers(JSSE14SocketFactory.java:175)
	at org.glassfish.grizzly.config.ssl.JSSE14SocketFactory.init(JSSE14SocketFactory.java:144)
	at org.glassfish.grizzly.config.SSLConfigurator.initializeSSLContext(SSLConfigurator.java:283)
	at org.glassfish.grizzly.config.SSLConfigurator.configureSSL(SSLConfigurator.java:147)
	at org.glassfish.grizzly.config.SSLConfigurator$InternalSSLContextConfigurator.createSSLContext(SSLConfigurator.java:429)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:185)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
	at org.glassfish.grizzly.sni.SNIFilter.handleRead(SNIFilter.java:261)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]

## Environment ##

- **Payara Version**:  payara 5.201 build(512)
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**:

**Comment by Chalfouh** [comment] 2020-06-01 07:15
It seems that the relationship between certificate nick name and the server name is broken
 GRIZZLY0050: SSL support could not be configured!
java.io.IOException: 5330: Alias name www.domain.com does not identify a key entry
i tested my certificate and they work just fine

**Comment by Chalfouh** [comment] 2020-06-02 05:38
changing the jvm option from keystore.jks to config/keystore.jks  solved my ssl problem
so the miss-configuration is definitely on you side.

**Comment by andresku** [comment] 2020-07-03 12:28
I confirm the problem. 
Additionally: in Payara5 (5.2020.2) the JVM option "javax. net. ssl. keyStore" is obviously ignored if the attribute "key-store" of ssl is present:
\<ssl classname="com.sun.enterprise.security.ssl.GlassfishSSLImpl" cert-nickname="s1as" key-store="config/keystore.jks"\>\</ssl\>
Who likes the above-mentioned JVM option, has to remove the ssl-attribute 'key-store="config/keystore. jks"'. 
Who prefers the ssl Attribute, should pay attention to the relative path of the attribute value (relative to the current domain).

**Comment by smillidge** [comment] 2020-07-03 12:58
Apologies I have no real idea what the issue is you are trying to describe? Can you provide steps to reproduce?

**Comment by andresku** [comment] 2020-07-03 14:09
The problem appears when switching from Glassfish4 to Payara5. 
In the Gf4 default domain.xml there are 2 links to the keystore file:
1. \<jvm-options\>-Djavax.net.ssl.keyStore=${com.sun.aas.instanceRoot}/config/keystore.jks\</jvm-options\>
2. Http-Protocol-ssl-Tag: \<ssl classname="com.sun.enterprise.security.ssl.GlassfishSSLImpl" cert-nickname="s1as" key-store="keystore.jks"\>\</ss\>

Every "average" Sysadmin expects, this settings will work under payara5 too. But they do not: the existence of key-store-Attribute in ssl-Tag above "deactivates" the jvm-option "javax.net.ssl.keyStore", but the value of the key-store-Attribute is not right.
This is the whole problem. This ist not a bug, but this change ist not described in any known documentation.

**Comment by smillidge** [comment] 2020-07-03 15:47
But Payara doesn't have the keystore path in the ssl tag? So there's not a bug here?

I checked back in the GlassFish 4.1 source https://github.com/javaee/glassfish/blob/4.1.2/appserver/admin/template/src/main/resources/config/domain.xml#L427 and it doesn't seem to have the key-store element be default. 

Are you sure this isn't something you have added specifically in your set up?

**Comment by andresku** [comment] 2020-07-06 07:25
You're right. I do not longer know how this attribute of the SSL tag was added to domain.xml. The fact is that I propagated it in all my Glassfish-4.1.2 installations. Thank you.

**Comment by smillidge** [comment] 2020-07-06 09:07
Thanks for the update I will close this.

**Closed** 2020-07-06 09:06 UTC
Labels: status:details-needed
