### ISSUE TITLE
Grizzly chunking-enabled property is ignored when compression is turned on /PAYARA-1857

### ISSUE THREAD

**Issue by sameencse** [payara/Payara#1739] opened 2017-07-03 09:30 UTC
# Application throws net::ERR_INCOMPLETE_CHUNKED_ENCODING error while downloading js files #
----------

Migrated server from glassfish 3.1 to Payara Server  4.1.1.171 #badassfish (build 137) and deployed my application in payara server and its failed to load due to incomplete downloading of js files. The same was  working fine in glassfish 3.1 and in console its throws "net::ERR_INCOMPLETE_CHUNKED_ENCODING" error.

Also FYI our requirement needs chunking disabled

`<http request-timeout-seconds="2700" chunking-enabled="false" compressable-mime-type="text/html,text/xml,text/plain,image/gif,image/jpeg,image/png,text/css,text/javascript,application/json,application/xml" max-connections="250" compression="on" default-virtual-server="server">`

Seems the similar issue is reported here (https://github.com/payara/Payara/issues/1038)  and 

Even i tried with Payara Server  4.1.2.172 & payara server 4.1.2.173-SNAPSHOT but no luck the same issue
attached image below contains the response header

![resp](https://user-images.githubusercontent.com/9302653/27786367-76630f20-5ffe-11e7-97a9-08ec60d09aef.png)

**Comment by mikecroft** [comment] 2017-07-03 12:02
Hi @sameencse I tested this by disabling chunking on the admin listener for the admin console and found it worked with no problems, after restarting the server. The header `Transfer-Encoding: chunked` was present in every response header before I made the change and it was not present afterwards.

How did you make the change? Did you make sure to change the correct config and restart the server instance following the change?

**Comment by sameencse** [comment] 2017-07-03 12:33
Thanks @mikecroft You made my day :)

However need a clarification

We updated from glassfish3 to payara some time back
For glassfish3 we used to disable chunking on the http-listener and not admin-listener

Is there any specific reason for change in functionality ?

**Comment by mikecroft** [comment] 2017-07-03 13:07
There shouldn't be any change needed @sameencse - I used the admin-listener because I didn't have an app deployed to my most recent Payara Server instance, so I tested with the admin console itself, which uses the admin-listener (port 4848).

The key thing to check is that the correct listener has chunking disabled. E.g. http-listener-1 is the non-ssl listener on port 8080 (default) and http-listener-2 is the ssl listener on port 8181 (default).

Does that clear things up a bit? Have you managed to get it to work?

**Comment by sameencse** [comment] 2017-07-03 13:23
Mike

Just observed. 

If i add the compression="on" attribute, though i disable the chunking, the response header contains Transfer-Encoding:chunked and the JS loading fails

fyi 

`<http request-timeout-seconds="2700" chunking-enabled="false" compressable-mime-type="text/html,text/xml,text/plain,image/gif,image/jpeg,image/png,text/css,text/javascript,application/json,application/xml" max-connections="250" **compression="on"** default-virtual-server="server">`

Back to square one. 

Please remember we had the same configuration in glassfish3 which is on prod and working fine

**Comment by sameencse** [comment] 2017-07-04 12:24
@mikecroft

Do you have any update on the above issue? still we are observing the same issue , how to fix this?

**Comment by mikecroft** [comment] 2017-07-05 08:20
Hi @sameencse do you have a test case that we can use to reproduce the issue?
http://sscce.org/

**Comment by sameencse** [comment] 2017-07-05 16:57
Server : Payara Server 4.1.2.172

**Failed to load the js files**
Payara configuration with attribute compression="on" and chunking-enabled="false" , 
![compression-on](https://user-images.githubusercontent.com/9302653/27875326-62e82b3c-61d0-11e7-9a2f-6945390bd38a.PNG)

See the Request & Response Header 

![fail-req-res](https://user-images.githubusercontent.com/9302653/27875380-8794a06e-61d0-11e7-8672-4015b92fc76a.PNG)

![fail-status](https://user-images.githubusercontent.com/9302653/27875389-8fc6ba74-61d0-11e7-8ae1-eb83a97541ed.PNG)


After changing the attribute compression="off" and chunking-enabled="false" , its working 
![compression-off](https://user-images.githubusercontent.com/9302653/27875430-b658a4b8-61d0-11e7-8abe-ce5b57246fef.PNG)

![req-res](https://user-images.githubusercontent.com/9302653/27875445-c09f4e54-61d0-11e7-9971-d9dc95848f1c.PNG)



Note: But we have application deployed in production which is using glassfish 3.1 with compression="on" and chunking-enabled="false", working fine. The same is creating issue in payara 171,172

**Comment by sameencse** [comment] 2017-07-07 01:40
Is this a bug or any misconfiguration ? Can any one confirm ?

**Comment by mikecroft** [comment] 2017-07-07 08:24
Hi @sameencse this is on our queue and we will evaluate as soon as we can. There is currently more urgent work that needs to be prioritised, hence the delay.

**Comment by sameencse** [comment] 2017-07-13 10:57
any update on this?

**Comment by mikecroft** [comment] 2017-07-14 07:49
It looks like the value of `chunking-enabled` is simply ignored when compression is enabled. I've raised internal issue `PAYARA-1857` for this, though it's not yet clear if this is a bug in Payara or Grizzly (I suspect Grizzly).

I suggest the best next step would be to find out why your application can't handled chunking.

**Comment by sameencse** [comment] 2017-08-07 03:38
Hi @mikecroft 
 Any update on the above bug? When can i expect the fix for this bug..

**Comment by mikecroft** [comment] 2017-08-07 10:04
It's not yet scheduled @sameencse so we can't tell you when it will be fixed. If this is something that you need to be fixed for a deadline, please [consider buying support](https://www.payara.fish/choose_support) since we commit to prioritising work for our customers.

**Comment by sameencse** [comment] 2017-08-07 12:40
Thanks @mikecroft our clients are already have payara support..will log a ticket

**Comment by Nallamachu** [comment] 2018-06-05 09:21
Thanks @sameencse. I have the similar issue, it solved now.

**Comment by rdebusscher** [comment] 2019-12-05 14:39
Hi @sameencse 

Is this still an issue or can I close this?

Regards
Rudy

**Comment by AlanRoth** [comment] 2020-11-11 10:54
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:54 UTC
Labels: bug, status:accepted
