### ISSUE TITLE
JDBC Connection Pooling - monitoring values can become negative

### ISSUE THREAD

**Issue by invinity** [payara/Payara#1409] opened 2017-02-22 21:58 UTC
# Description #
----------

I believe Payara is experiencing an old Glassfish bug [GLASSFISH-19416](https://java.net/jira/browse/GLASSFISH-19416).

It looks like [JdbcConnPoolStatsProvider.java](https://github.com/payara/Payara/blob/32f9e683cf01ed0b96de79648dafefa0a6087aa2/appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/pool/monitor/JdbcConnPoolStatsProvider.java) needs some of the changes suggested in the Glassfish bug.

## Expected Outcome

'numconnused' JMX/REST monitoring values should always be zero or positive:

`http://127.0.0.1:4848/monitoring/domain/server/resources/my-jdbc-pool`
`
{
  "message" : "",
  "command" : "Monitoring Data",
  "exit_code" : "SUCCESS",
  "extraProperties" : {
    "entity" : {
      "numconnused" : {
        "unit" : "count",
        "current" : 4,
        "lastsampletime" : 1487799202149,
        "lowwatermark" : 0,
        "name" : "NumConnUsed",
        "description" : "Provides connection usage statistics. The total number of connections that are currently being used, as well as information about the maximum number of connections that were used (the high water mark).",
        "highwatermark" : 4,
        "starttime" : 1487731422098
      }
    },
    "childResources" : {}
  }
`

## Current Outcome

`
{
  "message" : "",
  "command" : "Monitoring Data",
  "exit_code" : "SUCCESS",
  "extraProperties" : {
    "entity" : {
      "numconnused" : {
        "unit" : "count",
        "current" : -435,
        "lastsampletime" : 1487799202149,
        "lowwatermark" : -435,
        "name" : "NumConnUsed",
        "description" : "Provides connection usage statistics. The total number of connections that are currently being used, as well as information about the maximum number of connections that were used (the high water mark).",
        "highwatermark" : 4,
        "starttime" : 1487731422098
      }
    },
    "childResources" : {}
  }
`

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  Configure an HTTP network listener in the admin console:

[Attach screenshots of Payara's Server console, to illustrate]

3 -**  Add a JDBC connection pool configuration.

4 -** Enable connection pool monitoring `enable-monitoring --modules jdbc-connection-pool=HIGH`

5 -** Exercise connection pools and watch monitoring values

## Context (Optional)

I am seeing this with MySQL XADataSources configured for validation.

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: 1.8.0_111
- **Operating System**: Linux

**Comment by michaelranaldo** [comment] 2017-03-02 11:59
Hi there @invinity,

Just to check, there were some changes made to monitoring to fix some similar issues - are you able to confirm if this issue is still present in 171?

**Comment by dmatej** [comment] 2017-03-08 15:57
I will check it, because we observed this in older Payara version too.

**Comment by mikecroft** [comment] 2017-06-13 10:29
did you confirm this was still the case in the most recent version of Payara @dmatej?

**Comment by sgflt** [comment] 2017-08-22 20:13
@mikecroft I can confirm that Payara 4.1.1.171.0.1 on our production environment have this bug. The NumConnFree counter in GUI monitoring showed a value about -2000 on each instance of a cluster.

**Comment by pdudits** [comment] 2017-08-23 09:19
I can confirm that for 4.1.2.172, after turning on "Associate with thread" on Oracle JDBC connection pool.

**Comment by dmatej** [comment] 2017-08-26 15:21
Sorry, I left the company, @sgflt replaced me as a leader :-)
(I will propagate Payara anyway ;-) )

**Comment by rdebusscher** [comment] 2019-12-05 09:05
Fixed in 4.1.2.174 by https://github.com/payara/Payara/pull/1966

**Closed by rdebusscher** 2019-12-05 09:05 UTC
Labels: 1:Wait, Test Case Required, try to reproduce
