### ISSUE TITLE
"asadmin list-logger-levels" does not list java.util.logging.ConsoleHandler

### ISSUE THREAD

**Issue by webelcomau** [payara/Payara#1092] opened 2016-09-13 10:55 UTC
Mac OS X: Yosemite 10.10.5
NetBeans8.1
Payara 4.1.1.163 (and same with Glassfish4.1 or Glassfish4.1.1)

Also reported as: https://java.net/jira/browse/GLASSFISH-21560

With out-of-the-box Payara.

The docs I refer to below are:

```
GlassFish Server Open Source Edition
Administration Guide
Release 4.0
```

The docs (and `help list-log-levels` both give java.util.logging.ConsoleHandler in the output example:

From Glassfish4 admin guide:

> Example 7–3 Listing Logger Levels for Modules
> 
> This example shows a partial list of the existing loggers and their log levels in the
> DAS.

```
asadmin> list-log-levels
javax.enterprise.system.container.cmp <INFO>
javax.enterprise.system.tools.admin <INFO>
java.util.logging.ConsoleHandler <FINEST>
javax.enterprise.system.container.web <INFO>
javax.enterprise.system.util <INFO>
javax.enterprise.resource.webcontainer.jsf.timing <INFO>
javax <INFO>
javax.enterprise.resource.corba <INFO>
...
Command list-log-levels executed successfully.
```

When I perform this with or without a server target the java.util.logging.ConsoleHandler does not appear:

```
asadmin> list-log-levels server
ShoalLogger <CONFIG>


javax.enterprise.resource.corba <INFO>
javax.enterprise.resource.javamail  <INFO>
javax.enterprise.resource.jdo   <INFO>
javax.enterprise.resource.jms   <INFO>
javax.enterprise.resource.jta   <INFO>
javax.enterprise.resource.resourceadapter   <INFO>
...
```

I can change it in the domain1/domain/config/logging.properties, but then I have to restart:

```
$ grep Console /Applications/NetBeans-8.1/payara41/glassfish/domains/domain1/config/logging.properties 

handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter=com.sun.enterprise.server.logging.UniformLogFormatter
com.sun.enterprise.server.logging.GFFileHandler.logtoConsole=false
java.util.logging.ConsoleHandler.level=FINEST
```

This executes without error but does not seem to do anything, and the Console logger still does not appear in the list:

> Example 7–5 Changing the Global Log Level for All Module Loggers
> 
> By setting the log level of the ConsoleHandler, you set the global log level for all
> loggers. This example sets the global log level in the DAS to INFO:

```
asadmin> set-log-levels java.util.logging.ConsoleHandler=INFO
java.util.logging.ConsoleHandler package set with log level INFO.
These logging levels are set for server.
Command set-log-levels executed successfully.
```

**Comment by mikecroft** [comment] 2016-10-20 09:39
Sorry for the delay in getting back to you. I've done a bit of digging here, it looks like this was a deliberate design decision on the part of GlassFish to ignore Handlers and only list log levels

[Line 173 of ListLoggerLevels.java explicitly ignores handlers](https://github.com/payara/Payara/blob/32f9e683cf01ed0b96de79648dafefa0a6087aa2/nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/ListLoggerLevels.java#L173):
```java
if (n.endsWith("Handler")) {
    continue;
}
```

This is the commit that brought the change in:
["No bug. Exclude the handler names from the logger list."](https://github.com/payara/Payara/commit/0278dbe237c06a5e67853953a2bad426cf875681)

**Comment by mikecroft** [comment] 2016-10-31 12:50
I've discussed this with development. It's not a bug, since the change was intentional, but my opinion was that the change brought no real benefit and made usability (arguably) slightly worse.

I've therefore raised this as an enhancement request `PAYARA-1116` to restore original (documented) functionality.

**Comment by webelcomau** [comment] 2016-11-01 06:50
@mikecroft Thanks for your analysis of this. You wrote:

> my opinion was that the change brought no real benefit and made usability (arguably) slightly worse.

> I've therefore raised this as an enhancement request PAYARA-1116 to restore original (documented) functionality.

I agree that either the documentation needs to be changed to match the logging behaviour change, or the original functionality should be restored (enhancement request PAYARA-1116), which I prefer, because the filtering out of the java.util.logging.ConsoleHandler is not very intuitive.

**Comment by mikecroft** [comment] 2017-06-26 08:30
Fixed via a pull from upstream

**Closed by mikecroft** 2017-06-26 08:30 UTC
Labels: 2:WithDev, c:Enhancement, upstream bug
