### ISSUE TITLE
Microprofile Config not working on EJB with JCache

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#4436] opened 2020-01-16 00:51 UTC
# Description #
----------

When I use a microprofile `config` instance in a EJB bean with JCache the application throws an exception.

Note: I already tried to inject the config directly using `@Inject` with `@ConfigProperty` and the occurs the same error.

## Expected Outcome

That can use microprofile config in the EJB bean.

## Current Outcome

```java
java.lang.IllegalThreadStateException: Thread[hz._hzInstance_2_development.partition-operation.thread-1,5,main] cannot make remote call: com.hazelcast.map.impl.operation.GetOperation{serviceName='hz:impl:mapService', identityHash=1052781357, partitionId=93, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 20:59:59.999), waitTimeout=-1, callTimeout=60000, name=payara.microprofile.config}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:590)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:433)
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:351)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:120)
	at fish.payara.nucleus.store.ClusteredStore.get(ClusteredStore.java:186)
	at fish.payara.nucleus.microprofile.config.source.ClusterConfigSource.getValue(ClusterConfigSource.java:80)
	at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getValue(PayaraConfig.java:166)
	at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getValue(PayaraConfig.java:78)
	at fish.payara.nucleus.microprofile.config.spi.InjectedPayaraConfig.getValue(InjectedPayaraConfig.java:63)
	at MyClass
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.producer.ProducerMethodProducer.produce(ProducerMethodProducer.java:103)
	at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:161)
	at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:180)
	at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:70)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:794)
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:336)
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:347)
	at org.jboss.weld.injection.producer.DefaultInjector$1.proceed(DefaultInjector.java:71)
	at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:191)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)
	at org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:73)
	at org.jboss.weld.module.ejb.DynamicInjectionPointInjector.inject(DynamicInjectionPointInjector.java:61)
	at org.jboss.weld.module.ejb.SessionBeanInjectionTarget.inject(SessionBeanInjectionTarget.java:138)
	at org.glassfish.weld.services.JCDIServiceImpl$JCDIInjectionContextImpl.inject(JCDIServiceImpl.java:576)
	at org.glassfish.weld.services.JCDIServiceImpl.injectEJBInstance(JCDIServiceImpl.java:323)
	at com.sun.ejb.containers.BaseContainer.injectEjbInstance(BaseContainer.java:1796)
	at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:437)
	at com.sun.ejb.containers.StatelessSessionContainer.access$000(StatelessSessionContainer.java:100)
	at com.sun.ejb.containers.StatelessSessionContainer$SessionContextFactory.create(StatelessSessionContainer.java:651)
	at com.sun.ejb.containers.util.pool.NonBlockingPool.getObject(NonBlockingPool.java:219)
	at com.sun.ejb.containers.StatelessSessionContainer._getContext(StatelessSessionContainer.java:395)
	at com.sun.ejb.containers.BaseContainer.getContext(BaseContainer.java:2581)
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2002)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy257.load(Unknown Source)
	at MyClass
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:410)
	at org.jboss.weld.module.ejb.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:134)
	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
	at org.jboss.weld.module.ejb.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:68)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at MyClass$Proxy$_$$_Weld$EnterpriseProxy$.load(Unknown Source)
	at fish.payara.nucleus.hazelcast.contextproxy.CompleteConfigurationProxy$1$CacheLoaderImpl.load(CompleteConfigurationProxy.java:95)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.readThroughCache(AbstractCacheRecordStore.java:995)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.get(AbstractCacheRecordStore.java:1158)
	at com.hazelcast.cache.impl.operation.CacheGetOperation.run(CacheGetOperation.java:50)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
```

## Steps to reproduce (Only for bug reports) 

1. Create a CacheStore class:
```java
@LocalBean
@Stateless
public class CacheStore implements CacheLoader<DefaultGeneratedCacheKey, V>, CacheWriter<DefaultGeneratedCacheKey, V>, Serializable {
    
    @Inject
    private Config config;

    private void test() {
         config.getValue("myValue", String.class);
    }

}
```

2. Configure the cache:
```java
@WebListener
public class CacheConfigurer implements ServletContextListener {

    @Inject
    private Instance<CacheStore> instance

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        Factory<ExpiryPolicy> expiryPolicyfactory = CreatedExpiryPolicy.factoryOf(new Duration(validadeCacheUnit, validadeCache));

        cacheManager.createCache(cacheName, new MutableConfiguration<DefaultGeneratedCacheKey, V>()
                .setExpiryPolicyFactory(expiryPolicyfactory)
                .setReadThrough(true)
                .setCacheLoaderFactory(instance::get)
                .setWriteThrough(true)
                .setCacheWriterFactory(instance::get));
    }
}
```

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Micro
- **JDK Version**: 8 - OpenJDK
- **Operating System**: Linux
- **Database**: N/A

**Comment by ThomasSousa96** [comment] 2020-01-26 01:04
I found the problem. The EJB bean can't access config properties from the **Custer Config Source**. This config source is managed by the Hazelcast.

To resolve this problem I used the bellow command, in pre boot, to reduce the priority of this source. 

**pre-boot-commands.txt**
```sh
set-config-ordinal --ordinal=0 --source=cluster
```

```sh
--prebootcommandfile pre-boot-commands.txt
```

*This solution works because the config properties are defined in other config sources, with highest priority.*

**Comment by fturizo** [comment] 2020-02-05 23:43
Greetings @ThomasSousa96, 

Although the solution you are proposing solves the issue, the real problem that I can see is that your cache store is conformed of an EJB that has additional dependencies (in this case an instance of the MicroProfile configuration object), which is not a recommended solution as EJB references are proxies to internal services and dependencies of the container runtime which are not designed to be cached in a distributable manner. Bottom line is that I would recommend refactoring that code, and making sure that the `CacheStore` class is neither an EJB or logically depends on any injected dependencies as well. 

Considering that the nature of this issue is not a bug, but rather a cofiguration/usage issue related to JCache, I'll proceed to close it.

**Closed by fturizo** 2020-02-05 23:43 UTC

**Comment by ThomasSousa96** [comment] 2020-02-06 00:34
Hi @fturizo,

Thanks for the feedback. I'm using EJB because the `CacheWriter` and `CacheLoader` need a `EntityManager` instance to write and load from a database and to manage the transactions I'm using `@Transactional`. How to do it without use EJB?

**Comment by lprimak** [comment] 2020-06-23 21:30
This is related to https://github.com/hazelcast/hazelcast/issues/10875
I am working on tightening up integration between Hazelcast and Payara in general and when done it should fix this and similar issues

**Comment by lprimak** [comment] 2020-06-23 21:33
Can you please create a complete, self-contained reproducer on github so I can test this issue without worrying if I created a proper reproducer. thank you.

**Comment by lprimak** [comment] 2020-06-23 23:16
Looking further at it, this issue is somewhat unrelated to the Hazelcast integration.
Looks like your EJB is getting called from within Hazelcast-thread-backed callback. Then, MP config
tries to run another callback synchronously, which is disallowed by Hazelcast. The trick is to dis-entangle the two calls.
Not sure how / if / how easily this can be achieved

**Comment by lprimak** [comment] 2020-06-24 01:24
Try making ```CacheStore``` ```@Asynchronous ``` EJB. That will de-couple the threads and will do what you need
Obviously without reproducer I can't test it, but it's a simple solution that may work
