### ISSUE TITLE
Broken connection after commit when using more than one JDBC connection in one transaction.

### ISSUE THREAD

**Issue by gignac1024** [payara/Payara#1490] opened 2017-03-28 10:33 UTC
# Description #
----------

When using more than one JDBC connection (call DataSource40(AbstractDataSource).getConnection()) in one trasaction the connection is broken after all commit and can't using it, instance object of class ManagedConnectionImpl has value parameter "connectionCount" equal -1 and other instance has 1 but should 0.

Next use of the conection by instance object of class ManagedConnectionImpl with parameter "connectionCount" equal -1 in single transaction throw exception on close conection, when using transaction containing autonomous transactions first transaction is rollback when second transaction throw error on close conection.

[2017-03-27T14:16:47.976+0200] [Payara 4.1] [SEVERE] [] [javax.enterprise.resource.resourceadapter.com.sun.gjc.spi.jdbc40] [tid: _ThreadID=54 _ThreadName=http-thread-pool(3)] [timeMillis: 1490617007976] [levelValue: 1000] [[
  RAR7115: Unable to set ClientInfo for connection
java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy314.setClientInfo(Unknown Source)
        at com.sun.gjc.spi.jdbc40.ConnectionHolder40.setClientInfo(ConnectionHolder40.java:344)
        at com.sun.gjc.spi.jdbc40.ConnectionHolder40.close(ConnectionHolder40.java:597)
        at net.sf.log4jdbc.sql.jdbcapi.ConnectionSpy.close(ConnectionSpy.java:1012)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.closeConnection(DatasourceConnectionProviderImpl.java:127)
        at org.hibernate.internal.NonContextualJdbcConnectionAccess.releaseConnection(NonContextualJdbcConnectionAccess.java:46)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.releaseConnection(LogicalConnectionManagedImpl.java:189)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.close(LogicalConnectionManagedImpl.java:232)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.close(JdbcCoordinatorImpl.java:183)
        at org.hibernate.internal.AbstractSharedSessionContract.close(AbstractSharedSessionContract.java:304)
        at org.hibernate.internal.SessionImpl.close(SessionImpl.java:411)
        at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:347)
        at com.sun.proxy.$Proxy357.close(Unknown Source)
        at org.jcas.persistence.service.jpa.AbstractTransactionalEntityManagerRegistry$1.afterCompletion(AbstractTransactionalEntityManagerRegistry.java:89)
        at com.sun.enterprise.transaction.JavaEETransactionImpl.commit(JavaEETransactionImpl.java:547)
        at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.commit(JavaEETransactionManagerSimplified.java:884)
        at com.sun.enterprise.transaction.UserTransactionImpl.commit(UserTransactionImpl.java:212)
        at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1023)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:504)
        at org.jcas.glue.spring.tx.CustomTransactionInterceptor.commitTransactionAfterReturning(CustomTransactionInterceptor.java:56)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy263.login(Unknown Source)
        at org.jcas.gui.gwt.servlet.StandardGwtLoginServlet.doLogin(StandardGwtLoginServlet.java:116)
        at org.jcas.gui.gwt.servlet.BaseGwtLoginServlet.logInAction(BaseGwtLoginServlet.java:277)
        at org.jcas.gui.gwt.servlet.BaseGwtLoginServlet.doPost(BaseGwtLoginServlet.java:250)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

## Steps to reproduce (Only for bug reports) 

<jdbc-connection-pool allow-non-component-callers="true" datasource-classname="org.postgresql.ds.PGConnectionPoolDataSource" name="xxxx_localhost" validation-classname="org.glassfish.api.jdbc.validation.PostgresConnectionValidation" wrap-jdbc-objects="false" is-connection-validation-required="true" connection-validation-method="custom-validation" res-type="javax.sql.ConnectionPoolDataSource">
  <property name="ApplicationName" value="${application_name}"></property>
  <property name="DatabaseName" value="xxxx"></property>
  <property name="PortNumber" value="5431"></property>
  <property name="User" value="xxxxxx"></property>
  <property name="Password" value="xxxxx"></property>
  <property name="ServerName" value="localhost"></property>
</jdbc-connection-pool>

Call scenario:
1. Start first transaction.
2. Get first connction by instance of class ManagedConnectionImpl (object id=262,  before connectionCount=0)  

this	ManagedConnectionImpl  (id=262)
Thread [reportJmsContainer-1] (Suspended (breakpoint at line 928 in ManagedConnectionImpl))	
	ManagedConnectionImpl.incrementCount() line: 928	
	ManagedConnectionImpl.getConnection(Subject, ConnectionRequestInfo) line: 532	
	LocalTxConnectorAllocator.fillInResourceObjects(ResourceHandle) line: 119	
	ConnectionPool.getResource(ResourceSpec, ResourceAllocator, Transaction) line: 488	
	PoolManagerImpl.getResourceFromPool(ResourceSpec, ResourceAllocator, ClientSecurityInfo, Transaction) line: 245	
	PoolManagerImpl.getResource(ResourceSpec, ResourceAllocator, ClientSecurityInfo) line: 170	
	ConnectionManagerImpl.getResource(int, PoolManager, ManagedConnectionFactory, ResourceSpec, Subject, ConnectionRequestInfo, ClientSecurityInfo, ConnectorDescriptor, boolean) line: 360	
	ConnectionManagerImpl.internalGetConnection(ManagedConnectionFactory, ResourcePrincipal, ConnectionRequestInfo, boolean, String, Object, boolean) line: 307	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo, String, Object) line: 196	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo, String) line: 171	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo) line: 166	
	DataSource40(AbstractDataSource).getConnection() line: 114	
	LoggingDataSource(DataSourceSpy).getConnection() line: 147	
	DatasourceConnectionProviderImpl.getConnection() line: 122	
	...
	

3. Get second connction by instance of class ManagedConnectionImpl (object id=284,  before connectionCount=0) (object id=262,  before connectionCount=1)  
Execution of three operations (incerement object id=284, incerement object id=262, decrement object id=284 )

this	ManagedConnectionImpl  (id=284)  
Thread [reportJmsContainer-1] (Suspended (breakpoint at line 928 in ManagedConnectionImpl))	
	ManagedConnectionImpl.incrementCount() line: 928	
	ManagedConnectionImpl.getConnection(Subject, ConnectionRequestInfo) line: 532	
	LocalTxConnectorAllocator.fillInResourceObjects(ResourceHandle) line: 119	
	ConnectionPool.getResource(ResourceSpec, ResourceAllocator, Transaction) line: 488	
	PoolManagerImpl.getResourceFromPool(ResourceSpec, ResourceAllocator, ClientSecurityInfo, Transaction) line: 245	
	PoolManagerImpl.getResource(ResourceSpec, ResourceAllocator, ClientSecurityInfo) line: 170	
	ConnectionManagerImpl.getResource(int, PoolManager, ManagedConnectionFactory, ResourceSpec, Subject, ConnectionRequestInfo, ClientSecurityInfo, ConnectorDescriptor, boolean) line: 360	
	ConnectionManagerImpl.internalGetConnection(ManagedConnectionFactory, ResourcePrincipal, ConnectionRequestInfo, boolean, String, Object, boolean) line: 307	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo, String, Object) line: 196	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo, String) line: 171	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo) line: 166	
	DataSource40(AbstractDataSource).getConnection() line: 114	
	...

this	ManagedConnectionImpl  (id=262)
Thread [reportJmsContainer-1] (Suspended (breakpoint at line 928 in ManagedConnectionImpl))	
	ManagedConnectionImpl.incrementCount() line: 928	
	ManagedConnectionImpl.associateConnection(Object) line: 331	
	ConnectorXAResource.start(Xid, int) line: 139	
	JavaEETransactionManagerSimplified.enlistResource(Transaction, TransactionalResource) line: 410	
	ResourceManagerImpl.registerResource(ResourceHandle) line: 152	
	ResourceManagerImpl.enlistResource(ResourceHandle) line: 112	
	PoolManagerImpl.getResource(ResourceSpec, ResourceAllocator, ClientSecurityInfo) line: 211	
	ConnectionManagerImpl.getResource(int, PoolManager, ManagedConnectionFactory, ResourceSpec, Subject, ConnectionRequestInfo, ClientSecurityInfo, ConnectorDescriptor, boolean) line: 360	
	ConnectionManagerImpl.internalGetConnection(ManagedConnectionFactory, ResourcePrincipal, ConnectionRequestInfo, boolean, String, Object, boolean) line: 307	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo, String, Object) line: 196	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo, String) line: 171	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo) line: 166	
	DataSource40(AbstractDataSource).getConnection() line: 114	
	
this	ManagedConnectionImpl  (id=284)	(4)
Thread [reportJmsContainer-1] (Suspended (breakpoint at line 932 in ManagedConnectionImpl))	
	ManagedConnectionImpl.decrementCount() line: 932	
	ManagedConnectionImpl.associateConnection(Object) line: 338	
	ConnectorXAResource.start(Xid, int) line: 139	
	JavaEETransactionManagerSimplified.enlistResource(Transaction, TransactionalResource) line: 410	
	ResourceManagerImpl.registerResource(ResourceHandle) line: 152	
	ResourceManagerImpl.enlistResource(ResourceHandle) line: 112	
	PoolManagerImpl.getResource(ResourceSpec, ResourceAllocator, ClientSecurityInfo) line: 211	
	ConnectionManagerImpl.getResource(int, PoolManager, ManagedConnectionFactory, ResourceSpec, Subject, ConnectionRequestInfo, ClientSecurityInfo, ConnectorDescriptor, boolean) line: 360	
	ConnectionManagerImpl.internalGetConnection(ManagedConnectionFactory, ResourcePrincipal, ConnectionRequestInfo, boolean, String, Object, boolean) line: 307	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo, String, Object) line: 196	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo, String) line: 171	
	ConnectionManagerImpl.allocateConnection(ManagedConnectionFactory, ConnectionRequestInfo) line: 166	
	DataSource40(AbstractDataSource).getConnection() line: 114	
	
4 Close second connction by instance of class ManagedConnectionImpl (object id=284,  before connectionCount=0) (object id=262,  before connectionCount=2)  
Execution of three operations (decrement object id=262, incerement object id=284, decrement object id=262 ) 
Sequence of this operations is changed !

this	ManagedConnectionImpl  (id=262)
Thread [reportJmsContainer-1] (Suspended (breakpoint at line 932 in ManagedConnectionImpl))	
	ManagedConnectionImpl.decrementCount() line: 932	
	ManagedConnectionImpl.connectionClosed(Exception, ConnectionHolder) line: 831	
	ConnectionWrapper40(ConnectionHolder).close() line: 214	
	ConnectionWrapper40(ConnectionHolder40).close() line: 604	
	
this	ManagedConnectionImpl  (id=284)
Thread [reportJmsContainer-1] (Suspended (breakpoint at line 928 in ManagedConnectionImpl))	
	ManagedConnectionImpl.incrementCount() line: 928	
	ManagedConnectionImpl.associateConnection(Object) line: 331	
	ConnectorXAResource.end(Xid, int) line: 166	
	JavaEETransactionManagerSimplified.delistResource(Transaction, TransactionalResource, int) line: 551
	ResourceManagerImpl.unregisterResource(ResourceHandle, int) line: 277	
	ResourceManagerImpl.delistResource(ResourceHandle, int) line: 235	
	PoolManagerImpl.resourceClosed(ResourceHandle) line: 379	
	
this	ManagedConnectionImpl  (id=262)	(1)  
Thread [reportJmsContainer-1] (Suspended (breakpoint at line 932 in ManagedConnectionImpl))	
	ManagedConnectionImpl.decrementCount() line: 932	
	ManagedConnectionImpl.associateConnection(Object) line: 338	
	ConnectorXAResource.end(Xid, int) line: 166	
	JavaEETransactionManagerSimplified.delistResource(Transaction, TransactionalResource, int) line: 551	
	ResourceManagerImpl.unregisterResource(ResourceHandle, int) line: 277	
	ResourceManagerImpl.delistResource(ResourceHandle, int) line: 235	
	PoolManagerImpl.resourceClosed(ResourceHandle) line: 379	
	
	
5. first connction by instance of class ManagedConnectionImpl (object id=262,  before connectionCount=0)  

this	ManagedConnectionImpl  (id=262)	(0)
Thread [reportJmsContainer-1] (Suspended (breakpoint at line 932 in ManagedConnectionImpl))	
	ManagedConnectionImpl.decrementCount() line: 932	
	ManagedConnectionImpl.connectionClosed(Exception, ConnectionHolder) line: 831	
	ConnectionWrapper40(ConnectionHolder).close() line: 214	
	ConnectionWrapper40(ConnectionHolder40).close() line: 604	
	
	
Finall value after all commit on instances of class ManagedConnectionImpl: 
* instance with object id 262 has value -1 
* instance with object id 284 has value 1

## Environment ##

- **Payara Version**: 4.1.1.171.0.1
- **Edition**: Full
- **JDK Version**:  8 u121 - Oracle
- **Operating System**: Linux

**Comment by fturizo** [comment] 2017-03-29 20:57
Greetings @gignac1024 

I'm afraid I don't understand too much how to reproduce the bug you are experiencing. Could you attach a reproducible test case to help us out diagnose the issue? A sample project hosted on GitHub would be preferred also.

**Comment by mikecroft** [comment] 2017-05-31 11:05
Closing since we can't progress this without any more details. Please feel free to reopen with a test case we can use to recreate the problem @gignac1024

**Closed by mikecroft** 2017-05-31 11:05 UTC
Labels: 0:Triaged, Insufficient Detail, Test Case Required
