### ISSUE TITLE
Batch XML Files kept open

### ISSUE THREAD

**Issue by sosRoland** [payara/Payara#768] opened 2016-04-24 13:43 UTC
I am not sure if this is the right place to report this, as it concerns the Batch Module, but here it goes anyway.

I have noticed (lsof on linux) Batches running on a regular basis that the XML Batch Job files are not getting closed.

There for the system runs eventually out of file descriptors.

Roland

**Comment by mikecroft** [comment] 2016-04-24 13:45
What are the conditions that makes this happen? Would any simple batch job cause it? Would I need to run the jobs very many times to be able to see the problem?

We've got some JBatch samples I could use to reproduce this, but if you've got an example, that would be great.

**Comment by sosRoland** [comment] 2016-04-24 13:47
It seems to happen on any batch that you run. A matter of fact, after some quick testing more with my batches, it seems the xml file gets opened several time with in one execution.

**Comment by sosRoland** [comment] 2016-04-24 13:55
As an addition, re-deploy of the application seems to clear the open files

**Comment by smillidge** [comment] 2016-05-16 10:30
We can't reproduce this with a very simple batch job i.e. https://github.com/payara/Payara-Examples/tree/master/Java-EE/jbatch-schedule there is no increase in file descriptors and the jbatch xml file is not shown as open using lsof.

**Comment by smillidge** [comment] 2016-05-16 10:30
Can you provide a simple test case?

**Comment by sosRoland** [comment] 2016-05-16 10:35
I will try to produce one that has not got my whole application attached to it

**Comment by smillidge** [comment] 2016-05-16 10:59
That would be great thanks.

**Comment by sosRoland** [comment] 2016-06-24 09:12
Good morning,

Sorry this took so long. I created this simple and rather ugly example:

https://github.com/sosRoland/batch

When running this. the following command:

lsof |grep batch-job

Will have an ever increasing number of open fds.

Roland

PS: this is a oracle jvm

**Comment by mikecroft** [comment] 2016-07-08 13:03
I spent quite some time today trying to reproduce this without any success. The number of open files varies slightly (always somewhere between ~730 and ~860) but is usually stable at a particular number for the majority of the time. For reference, I had `while true; do lsof 2>/dev/null | grep batch | wc -l; done` running for about 15 mins and didn't see any significant change.

I was using Ubuntu 14.04 for my test.

It may be significant that I couldn't load your project, so I created a new maven project and packaged your classes and `MyBatch.xml` as a WAR. How did you do things to reproduce the problem? Also, what version of Payara Server are you using and what database?

**Comment by sosRoland** [comment] 2016-07-08 13:16
Hi Mike,

When i run it spikes at the end at about 1900 open xml files (the same over and over again), and even after the job is done they do not close (which I would presume they really should).

My test environment is a linux mint 17.2 on a standard build kernel 3.19.0-22-generic. With Oracle 1.7.45 server JVM/JDK. I did on one point try a later java 8 jvm with the same effect. I also have the problem with Amazon Ubuntu instance, same jvm.

I have had the problem with the last 3 of the latest update, but on my test system it is currently 4.1.152.1/build 193. The database is a mysql server 5.5.47 on the test system and a 5.5.46 on the ec2 instance (the batch db)

What I do find interesting so is, that you could not deploy it and that you deployed it into a war. My modules are setup as an ejb jar inside an ear.

Roland

**Comment by sosRoland** [comment] 2016-07-08 14:17
Hi Mike,

I did some testing on my own on this. And this is the cause. If the Batch Jobs are in a EJB jar the XML Job files will not be closed but kept open. If they are in WAR it works spot on.

Not sure if that counts as a bug or not. But seems to me, that the batch jobs belong much more into a ejb jar than into a web war. But at least I can move the stuff about and rework it into a war.

Roland

**Comment by mikecroft** [comment] 2016-07-08 14:42
Thanks, Roland, I repackaged it and the problem was immediately obvious. Looks like you've just helped to confirm https://java.net/jira/browse/GLASSFISH-20997, which we were already tracking in #722 so I'll close this one and continue using the other issue to track the problem. Thanks for your help!

**Closed by mikecroft** 2016-07-08 14:42 UTC
Labels: 2:Defect, c:ConfirmedBug, reproducible, upstream bug
