### ISSUE TITLE
Improper synchronization of session map

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#4280] opened 2019-10-22 18:59 UTC
# Description #
----------
We are experiencing two kind of problems with SSO:

1. SSO expires prematurely (similar issue https://github.com/payara/Payara/issues/2881)
2. SSO never expires

I have done some debugging and found two possible minor issues with synchronization.

## Expected Outcome

No ConcurrentModificationExceptions during session expiration.

## Current Outcome
```
[2019-08-10T12:30:24.036+0200] [Payara 4.1] [WARNING] [AS-WEB-GLUE-00045] [javax.enterprise.web] [tid: _ThreadID=157 _ThreadName=SingleSignOnExpiration] [timeMillis: 1565433024036] [levelValue: 900] [[
  Caught exception during SingleSignOn expiration
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
at com.sun.enterprise.security.web.GlassFishSingleSignOn.processExpires(GlassFishSingleSignOn.java:602)
at com.sun.enterprise.security.web.GlassFishSingleSignOn.run(GlassFishSingleSignOn.java:697)
at java.lang.Thread.run(Thread.java:748) 
```

## Steps to reproduce (Only for bug reports) 

Problem is reproducible with breakpoints at HASingleSignOn:170 and GlassfishSingleSignOn:697 with pausing only threads.

## Context (Optional)
HASingleSignOn calls cache.put without synchronized block on line 170. This may cause ConcurrentModificationException if some session expired and cleaner threed is actively looping over cache of sessions.

## Environment ##

- **Payara Version**: 4.1.1.171+

**Comment by smillidge** [comment] 2019-10-26 19:06
That is a very old version of Payara. Have you tried on the latest version of Payara?

**Comment by fturizo** [comment] 2020-02-06 19:35
Considering that the requester fell unresponsive and that this issue was reported on a considerably older release of Payara Server, we'll close this issue. Please, verify if the problem is present in the current release and if this is the case raise a new issue with a detailed reproducer that can help us identify the problem.

**Closed by fturizo** 2020-02-06 19:35 UTC
Labels: Try On Latest Release
