### ISSUE TITLE
admin GUI interface refresh issue

### ISSUE THREAD

**Issue by tbugfinder** [payara/Payara#497] opened 2015-10-29 11:22 UTC
Hello,

different sections of the admin GUI do not refresh updated values.
E.g. on extract payara-4.1.1.154, start-domain, open the admin GUI http://localhost:4848/common/index.jsf .

Open "Monitoring Data" -> Configure Monitoring -> Select all items and set Level to HIGH
apply this change using "Change level" and save the configuration.

Without a restart of the admin GUI the modified values are not displayed but the previous setttings (OFF) are displayed.

If admin GUI is restarted the changed settings are displayed. This issue comes up on almost any section of the admin GUI.

Thanks,

**Comment by smillidge** [comment] 2015-11-03 17:53
I can't reproduce this when following the instructions above all settings say HIGH even if I navigate away and back HIGH is always shown. I was using firefox, which browser and operating system are you using?

**Comment by tbugfinder** [comment] 2015-11-03 20:34
OS: Windows Server 2012 R2
Browser executed on localhost.
Browser version: IE 11.0.9600.17031
access.log user agent: "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko" 

I just verified this "bug" description again.

Indeed using Google Chrome it's ok.

**Comment by tbugfinder** [comment] 2015-11-03 21:32
I played around with IE11 developer tools.
As soon as developer tools are opened the issue does not show up. Closing Developer Tools ends up in the issue.

**Comment by smillidge** [comment] 2015-11-04 10:34
Does holding <shift> key and then refreshing the page show the modified values?

**Comment by tbugfinder** [comment] 2015-11-06 19:30
No, refreshing the page using shift-key does not show updated values either.

**Comment by tbugfinder** [comment] 2015-11-06 19:43
even closing the tab and reopening the page does not show the updated values, browser restart does.

**Comment by tbugfinder** [comment] 2015-11-06 19:44
Would you also be able to used IE11 on Windows Server 2012 ?

**Comment by smillidge** [comment] 2015-11-09 15:07
I will get one of the team to test on Windows Server 2012

**Comment by danPowell52** [comment] 2015-11-24 09:53
I have reproduced the issue by following the given instructions.
Issue seems it appears only in windows server 2012 and only on IE.
Will continue looking into it.

**Comment by smillidge** [comment] 2015-12-05 20:18
Fixed by pull request #542

**Closed by smillidge** 2015-12-05 20:18 UTC
Labels: cannot reproduce
