### ISSUE TITLE
Unexpected behaviour of remote call of beans using @PermitAll and @RolesAllowed for different methods // FISH-206

### ISSUE THREAD

**Issue by rabbink** [payara/Payara#2223] opened 2017-12-21 15:06 UTC
# Description #
----------
Calling a `@PermitAll` annotated business method in a remote EJB throws a `java.rmi.AccessException: CORBA NO_PERMISSION` when **_another_** method in this bean is annotated  `@RolesAllowed`. 

## Expected Outcome
In an unauthenticated context using the example bean below my expectations would be the call to succeed and HelloServiceRemote#sayHello() returning `Hello ANONYMOUS!` 

## Current Outcome
A `java.rmi.AccessException: CORBA NO_PERMISSION` is thrown.

```
javax.naming.NamingException: Lookup failed for 'java:global/payara.ear-1.0-SNAPSHOT/payara.ejb-1.0-SNAPSHOT/HelloServiceBean!com.mycompany.poc.HelloServiceRemote' in SerialContext[myEnv={org.omg.CORBA.ORBInitialPort=3700, java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, org.omg.CORBA.ORBInitialHost=10.0.100.4, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}
 [Root exception is javax.naming.NamingException: ejb ref resolution error for remote business interfacecom.mycompany.poc.HelloServiceRemote [Root exception is java.rmi.AccessException: CORBA NO_PERMISSION 0 No; nested exception is: 
	org.omg.CORBA.NO_PERMISSION: ----------BEGIN server-side stack trace----------
org.omg.CORBA.NO_PERMISSION:   vmcid: 0x0  minor code: 0  completed: No
	at com.sun.enterprise.iiop.security.SecServerRequestInterceptor.handle_null_service_context(SecServerRequestInterceptor.java:421)
	at com.sun.enterprise.iiop.security.SecServerRequestInterceptor.receive_request(SecServerRequestInterceptor.java:443)
	at com.sun.corba.ee.impl.interceptors.InterceptorInvoker.invokeServerInterceptorIntermediatePoint(InterceptorInvoker.java:612)
	at com.sun.corba.ee.impl.interceptors.PIHandlerImpl.invokeServerPIIntermediatePoint(PIHandlerImpl.java:614)
	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.getServantWithPI(ServerRequestDispatcherImpl.java:333)
	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:196)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1564)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:1440)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleInput(MessageMediatorImpl.java:945)
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:213)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:709)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.dispatch(MessageMediatorImpl.java:508)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.doWork(MessageMediatorImpl.java:2237)
```

## Steps to reproduce (Only for bug reports) 
Create a session bean with some business methods and a remote interface. Declare at least one method  `@PermitAll` and at least one method `@RolesAllowed`. Perform a lookup using a remote client, and call the method annotated `@PermitAll`. This bean is packaged as an EJB module in an EAR.
```
@Stateless
@DeclareRoles("user")
public class HelloServiceBean implements HelloServiceRemote {

    @Resource
    private SessionContext sc;

    @PermitAll
    @Override
    public String sayHello() {
        return "Hello " + sc.getCallerPrincipal().getName() + "!";
    }

    @RolesAllowed("user")
    @Override
    public String secureSayHello() {
        return "Hello " + sc.getCallerPrincipal().getName() + "!";
    }

}
```

Instead of using annotations and declaring security in the deployment descriptor ejb-jar.xml results in the same **_unexpected_** behaviour.
```
...
    <enterprise-beans>
        <session>
            <ejb-name>HelloServiceBean</ejb-name>
        </session>
    </enterprise-beans>
    <assembly-descriptor>
        <security-role>
            <role-name>user</role-name>
        </security-role>
        <method-permission>
            <unchecked />
            <method>
                <ejb-name>HelloServiceBean</ejb-name>
                <method-intf>Remote</method-intf>
                <method-name>sayHello</method-name>
            </method>
        </method-permission>
        <method-permission>
            <role-name>user</role-name>
            <method>
                <ejb-name>HelloServiceBean</ejb-name>
                <method-intf>Remote</method-intf>
                <method-name>secureSayHello</method-name>
            </method>
        </method-permission>
    </assembly-descriptor>
...
```
For completeness removing `@RolesAllowed` from the bean above and calling sayHello() **_does_** return` Hello ANONYMOUS!` in other words, the call **_succeeds_** as expected.

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full
- **JDK Version**: 8 u152 - Oracle
- **Operating System**: Windows

**Comment by rabbink** [comment] 2018-01-04 21:47
I have created a 'simple' reproduction project at https://github.com/rabbink/payara-remote-ejb-declarative-security.

In the project root execute `mvn package` to let maven create all artifacts and run the tests in module `payara-test`.

**Comment by smillidge** [comment] 2018-01-05 18:00
Thanks for the test case we will take a look.

**Comment by fturizo** [comment] 2020-02-06 18:00
Due to this issue being present in an unsupported release of Payara Server and how old the issue is, we'll proceed to close it. Feel free to raise a new issue if the problem is still present in the current version of Payara Server 5.x

**Comment by escay** [comment] 2020-02-19 10:49
Retested on 5.184 and 5.194 releases using the same example project and it seems the problem still exists.

**Comment by OndroMih** [comment] 2020-09-14 09:03
We'll need to reproduce this. @escay, @rabbink, could you assemble all the instructions how to reproduce into a sample application that we can use to reproduce the problem? This would save us some time and allow us to give higher priority to fixing this issue.

**Comment by AlanRoth** [comment] 2020-11-02 16:21
Hi, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us an easy to follow reproducer for the latest version of Payara. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.

**Closed by AlanRoth** 2020-11-02 16:21 UTC

**Comment by escay** [comment] 2020-12-08 12:10
@AlanRoth @OndroMih 
The reproduction scenario still exists at https://github.com/rabbink/payara-remote-ejb-declarative-security
The project contains a description and unit test how to reproduce it. On request of Fabio it was already updated in Ferbruary for and it was also discussed in August / September during the service contract period. I also think I received a confirmation of the problem while we had the service contract.

**Comment by AlanRoth** [comment] 2020-12-08 12:28
Hi @escay, 

This issue has been fixed in PR https://github.com/payara/Payara/pull/4981 for Payara Server Community 5.2020.7 and Payara Server Enterprise 5.23.1, but it wasn't linked to this issue for some reason. 

Thank you for your understanding, sorry about the confusion,
Alan
