### ISSUE TITLE
Remote context lookup fails with ClassCastException after sufficient lookups despite previously working 

### ISSUE THREAD

**Issue by Blavo** [payara/Payara#6299] opened 2023-06-07 09:13 UTC
### Brief Summary

After a some number of successful remote context lookups the same lookups from the same client instance will fail thereafter with a ClassCastException in sun.reflect.GeneratedMethodAccessor<nn>.invoke (<nn> varies).

My understanding is that the first few lookups from a given client instance are done on the server side using a less efficient, but more debuggable, scheme. After some threshold number of lookups from the one client instance subsequent lookups are done via a method accessor created for the purpose (hence GeneratedMethodAccessor<nn> above). The accessor scheme is more efficient but less debuggable. (This is based on https://stackoverflow.com/questions/16042591/reflections-illegalargumentexception-causes).

It appears to me, from the behaviour, that the less efficient scheme works reliably if the lookup string is valid (ie maps to a resource in the context) but that the accessor scheme always fails. (It is difficult to be sure because, if the lookup succeeds, we have no way of telling what scheme it used. We can only tell, from the stack trace, the scheme used by failing lookups and it is always the accessor scheme).

The real root exception is a ClassCastException. But it appears this is caught in the invoking code and turned into an IllegalArgumentException whose message is 'ClassCastException@nnnn'. The message from the ClassCastException, which would identify the expected and actual classes in the cast, is lost as is the source code line number of the failing class cast.

In my test case I restart my client (to get a fresh instance), do a batch of 11 lookups (which all succeed) then do the same batch of eleven lookups, and they all fail as above. After that the lookups always fail until the client is restarted (creating a fresh instance). For me the threshold number of successful lookups is 11 but others have reported 16. 

### Expected Outcome

Lookup succeeds and returns a proxy.

### Current Outcome

Lookup fails with a ClassCast exception in sun.reflect.GeneratedMethodAccessor<nn>.invoke (<nn> varies)

### Reproducer

1. Start a Payara instance that has at least one remote EJB listed in java:global.
2. From the server log get the lookup string for the bean.
3. Create a stand alone standard Java application (not an application client).
4. In the client create a lookup context against the server.
5. Add code to lookup the bean in a loop of say 50 iterations using the context from 4. and lookup string from 2.
6. Run the client. It can run on the same machine as the server.
7. The first few lookups should succeed, returning a proxy.
8. Eventually a lookup will fail as above.
9. All subsequent lookups will fail as above.

### Operating System

Mac OS Monterey (12.4)

### JDK Version

Java(TM) SE Runtime Environment (build 1.8.0_202-b08) Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

### Payara Distribution

Payara Server Full Profile

**Comment by Blavo** [comment] 2023-06-08 01:53
The reproducer needs a bit more work. Having made a reproducer to the above spec I have been able to do 10 x 2 x 11 lookups with 5 or 10 second intervals between the 10 repeats without a failure. I can't say for sure whether a GeneratedMethodAccessor is being used but based on previous experience I would expect that it is. Leave this with me to discover why my real client fails reliably on the 2nd group of 11 lookups and the reproducer does up to 22 groups of the same 11 lookups against the same server without error.

**Comment by Blavo** [comment] 2023-06-08 08:35
I think I see what is going on. 

In my stand alone reproducer I have to include the JARs that contain the remote interface classes and dependent classes in the reproducer's class path. In my real client I load these classes dynamically (a necessary feature of my project). If I (temporarily, as a test) I include those JARs in the class path of my real client I can reliably do the lookups. So, it appears that the less efficient, but more debuggable scheme, correctly recognises the dynamically loaded classes but the more efficient, but less debuggable, scheme relies on the class path and fails to recognise the dynamically loaded classes. Now, you might wonder how putting those JARs in the class path of the client would impact the behaviour of the server. The reason it does is that the client runs the server embedded. So the class path of the server is the same as the class path of the client.

**Comment by Blavo** [comment] 2023-06-11 23:57
The reproduce described above fails to reproduce the problem. But that may give a clue as to how to resolve the issue. It appears to me now that the problem is caused by doing the lookups from an embedded payara instance. I attempted to prove this by putting the code from the (non) reproducer into my tool before it starts the embedded glassfish. (The tool runs as a non-enterprise client Java application, which may be important.) As expected the lookups worked. But they prevented the tool doing its own lookup of remote beans. (I didn't record what failed but it looked ugly.) So then I moved the code from the (non) reproducer into the embedded glassfish instance. Then the tool successfully looked up the remote beans it requires for its own use but the lookups from the reproducer code failed. But they failed because a sub context named in the lookup string wasn't found. So we never reached the code whose failure is the subject of the issue.

So, to make a reproducer this issue looks to involve the following:
- a payara application (call it Target) that has a dozen or so remotely-invokable beans
- another payara application (call it Looker) that looks up the beans in Target but doesn't lookup beans for itself
- a stand-alone non enterprise client that
-- runs payara embedded
-- deploys Looker to it
-- causes Looker to do the lookups against Target

This is quite a bit of work. I'm not minded to do this on spec and will wait until someone shows an interest in working this issue. (Given the complete lack of comments to date I'm suspecting there isn't much interest). When that person emerges we will work out how to create a reproducer with the least work. (I suspect that person will already have one or more of the components on their workbench which we can reuse.)

If I am right that the issue arises from doing lookups from embedded payara then that would imply that a lookup call made by (embedded payara) is somehow different from a call made by the stand alone (non) reproducer. It seems that has to be the case since the decision on which lookup scheme to use is made by the target (the remote holder of the beans being looked up) and you would expect that similar calls to the target would result in the same lookup strategy.

So, as above, I'll wait for someone who has an interest in working this issue to arise before working with them to create an invoker.

**Comment by Blavo** [comment] 2023-06-13 23:19
<Likely cause> In developing a bypass for this (I have to have a solution) I think I have stumbled over the root cause.  In my bypass I got an unexpected ClassCastException: com.sun.corba.se.impl.javax.rmi.CORBA.StubDelegateImpl cannot be cast to com.sun.corba.ee.impl.javax.rmi.CORBA.StubDelegateImpl. The difference is .se. against .ee. in the package name.  In other words there is a StubDelegateImpl class in both the SE and EE libraries but they are different by virtue of being in different packages. 

Now, if I understand things correctly, when the server switches from honouring lookups with the less efficient but more debuggable scheme to the more efficient but less debuggable scheme (see the problem summary) it creates a GeneratedMethodAccessor on the fly. To do this I presume it writes code specific to the lookups coming from the client and then compiles it. The code almost certainly uses the StubDelegateImpl class. The definition for that class will have to be supplied to the compile. I'm guessing that either the SE library containing the StubDelegateImpl class is supplied to the compile or both the SE and EE libraries containing the StubDelegateImpl class are supplied, but with the SE library ahead of the EE library. 

This hypothesis explains the observable behaviour: 1) lookups work some of the time (when the less efficient scheme is used) 2) compilation of the on-the-fly-made GeneratedMethodAccessor works 3) use of the GeneratedMethodAccessor fails with a class cast exception - an EE StubDelegateImpl is received from elsewhere in Payara and won't cast (explicitly or implicitly) to an SE StubDelegateImpl 4) Remote lookups passed Payara QA (because insufficient lookups were done to trigger the switch in schemes in the server.

This looks like exactly the sort of problem that could occur in the change of namespaces (and therefore packaging) that was part of the GlassFish to Payara migration. However my notes suggest that the issue was occurring in GlassFish.

**Comment by Blavo** [comment] 2023-06-14 22:55
**Workaround** The workaround I've developed is complex. I'll only outline it here because you would need to be pretty dedicated to develop one. (It would probably be less effort to fix the bug!) The essence of the workaround is to do the lookups against the remote server in a process separate from, but initiated by, the embedded payara application. The two biggest challenges are: providing the lookup code with JARs that contain the classes of the invokers being looked up, their output, parameter, exception, and generic types plus any dependent JARs; and getting the invokers (the results of the lookups) back from that separate process.

The necessary classes have to be available to the embedded payara application for it to be able to use the looked up invokers, so the main issue there is their packaging into one or more JARs. I do this on the fly but you could probably do it statically if you only have one target. These JARs then become the subject of the -classpath parameter of the 'java' command that is run as the separate process. I've added two servers to my embedded payara application. The looking up code in the separate process connects to one to receive lookup strings and connects to the other to send the looked up invokers to the embedded payara application, these being sent via Java object IO.

**Comment by kalinchan** [comment] 2023-06-23 08:20
Hi @Blavo,

It looks like you are running Payara Community 5 which is out of support.

Are able to test this issue on the current release of Community 6?

**Comment by Blavo** [comment] 2023-06-25 02:32
G’day,

In principle but it would be a lot of work. Payara 6 requires Java 11 and my development environment is at Java 8. (We wish to remain on as early a Java release as is tenable because we import other people’s Java code as part of what we do. So the least constraining our version of Java the better.) I am not in a position to go to Java 11 on the development environment at present and would prefer not to even install it there. So that means upgrading another environment to Java 11, installing a newer NetBeans, installing Payara 6, and porting two substantial NetBeans projects there to make the test. There would also, no doubt, be environment things to set up to make the two projects work on the new machine. So, a lot of work to do one test. I would need to be convinced someone is going to work the problem if, as is most likely, the problem is demonstrated to be still in Payara 6.

If you are minded to fix something #5973 would be a better issue to fix. #5973 is going to affect a lot more people (#6299 appears to be in embedded Payara) and, while the work around for #6299 is non-trivial, the work around for #5973 is horrible.

**Comment by kalinchan** [comment] 2023-06-26 09:06
Hi @Blavo, as you can not create a reproducer and test this issue on the latest version of Payara Community 6, I will proceed to close this issue.

If you are able to test this issue on the latest Payara Community version in the future and the issue is still present, please raise a new issue with a working reproducer.

I suggest that you consider a Payara Enterprise subscription.

**Closed as completed by kalinchan** 2023-06-26 09:06 UTC
Labels: Type: Bug
