### ISSUE TITLE
191 Micro : define context root for application deployed from maven repo /FISH-115

### ISSUE THREAD

**Issue by carlbradwell17** [payara/Payara#4145] opened 2019-08-12 11:07 UTC
# Description #
----------

Referring to the documentation here:
https://docs.payara.fish/documentation/payara-micro/deploying/deploy-cmd-line.html

In the **Deploying Applications from a Maven repository** section, it states "This option can be used multiple times, and in conjunction with the standard --deploy options."
 
It therefore should be expected that defining the context root as part of the filename, as we can with the --deploy option, should also work with the --deployfromGAV option.

## Expected Outcome

This command should deploy the sample-1.war from the defined additional maven repo to the context root "one":
`java -jar payara-micro.jar --deployFromGAV "mygroup,sample,1:one" --additionalRepository http://mymavenrepo.com`

## Current Outcome

The above command fails to deploy the war completely.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Micro
- **JDK Version**:  8
- **Operating System**: Ubuntu

**Comment by smillidge** [comment] 2019-10-26 19:45
The parsing of the GAV doesn't support this so this is an enhancement request.

**Comment by rdebusscher** [comment] 2019-12-20 15:23
Tracked now as `CUSTCOM-46`

**Comment by AlanRoth** [comment] 2020-11-11 11:43
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:43 UTC
Labels: enhancement, status:accepted
