### ISSUE TITLE
Console is slow with Nodes off

### ISSUE THREAD

**Issue by stePrime** [payara/Payara#1296] opened 2017-01-19 09:00 UTC
# Description #
----------

Hi Team,

I configured an Hazelcast cluster environment with 3 Nodes:

![nodes](https://cloud.githubusercontent.com/assets/12546042/22099888/73a87778-de2d-11e6-9413-14f2e2e957b0.PNG)

![si](https://cloud.githubusercontent.com/assets/12546042/22099890/755ba374-de2d-11e6-9a82-a991dad0f3bd.PNG)

When the node machines are off it is impossible to navigate the console because it is very slow.

![running](https://cloud.githubusercontent.com/assets/12546042/22100046/2383c274-de2e-11e6-8c65-74a9fc2a2b41.PNG)

Is it normal this behaviour? Is there a way to speed it up? 

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: 8 - Oracle
- **Operating System**: Windows

**Comment by stePrime** [comment] 2017-03-06 16:03
no news?

**Comment by michaelranaldo** [comment] 2017-03-06 16:33
Hi @stePrime, 

Could you clarify how long is "ages"? When setting up instances time of ~10 - 15s should be considered normal.

**Comment by mikecroft** [comment] 2017-07-25 10:42
Closing since there's no clear way to reproduce. "Slow" is too subjective to act on here. This may be a better fit for the [Payara Forum](https://groups.google.com/forum/#!forum/payara-forum)

**Closed by mikecroft** 2017-07-25 10:42 UTC
Labels: 1:Wait, c:Question, requestor unresponsive (1)
