### ISSUE TITLE
Convert method do not work on Payara (most of the times)

### ISSUE THREAD

**Issue by leacardenas** [payara/Payara#1288] opened 2017-01-16 21:08 UTC
Convert method do not work on Payara (most of the times)
----------

I just changed form glassfish to payara, and there are certain convert methods that will not work for me. The thing is that the work perfectly con glassfish, but when I run my application on payara, they do not work. this error appear: 

> Severe:   java.lang.NullPointerException
> 	at com.toursys.apps.converters.CurrencyConverter.getAsObject(CurrencyConverter.java:33)
> 

Method: 

```
@Override
    public Object getAsObject(FacesContext context, UIComponent component, String value) {
        
        if (value == null || "".equals(value)) {
            return null;
        }
        
        return currencyDAO.findCurrency(Integer.parseInt(value));
    }
```

Enviroment:

- **Payara Version**: 4.1.1.164
- **Operating System**: Windows 10
- **NetBeans**: 8.0.2
- **Glassfish version that works**: 4.1

**Comment by mikecroft** [comment] 2017-01-17 08:43
Can you add more detail, please? There isn't enough information here to give an answer since that class and method isn't from Payara.

* What is the *full* error message?
* If this works in some cases, what are the differences between the times it works and the times it fails?
* Can you reproduce this error easily?

**Comment by leacardenas** [comment] 2017-01-20 23:00
Hello, thank you for your answer I was able to find the problem and fix it.
The problem was with something related to JSF and a bug but the thing is
that glassfish never showed me the error so when i installed payara it
suddenly appeared.

So, thank you still.

Regards,

Lea

2017-01-17 2:43 GMT-06:00 Mike Croft <notifications@github.com>:

**Comment by lprimak** [comment] 2017-01-21 00:46
This is probably because of latest version of JSF included in Payara vs. GlasFIsh
Please close the issue if you are satisfied, thanks!

**Closed** 2017-01-21 14:46 UTC
Labels: 1:Wait, c:Misconfiguration, Insufficient Detail

**Comment by leacardenas** [comment] 2017-01-25 18:33
Yes, thank you

2017-01-21 8:46 GMT-06:00 Steve Millidge <notifications@github.com>:
