### ISSUE TITLE
Restart instance fails from Admin Console when its Node has custom Node Directory /CUSTCOM-143

### ISSUE THREAD

**Issue by nando2301** [payara/Payara#4401] opened 2019-12-20 19:13 UTC
# Description #
----------
When I use Deployment Groups with remote nodes and instances, trying to restart instances from Admin Console --)) Instances --)) Instance Name --)) Restart Button it fails.

## Expected Outcome

When I use custom `Node Directory:` outside `${com.sun.aas.productRoot}/glassfish/nodes`, I expected instance created on it can be restarted from Admin Console without problem.

## Current Outcome

Stop and Start Button work but Restart Button fails with this error:

```
An error has occurred
Could not sync instance myidtravel-instance1 on node local-myidtravel-domain (localhost). Command failed on node local-myidtravel-domain (localhost): Command _synchronize-instance failed. More than one node in directory /opt/aplicaciones/payara5/glassfish/nodes. Please specify --node. To complete this operation run the following command locally on host localhost from the Payara Server install location /opt/aplicaciones/payara5: lib/nadmin _synchronize-instance --sync normal myidtravel-instance1
```

## Steps to reproduce (Only for bug reports) 

1. Create domain with `Production Template` and `--savemasterpassword=true --usemasterpassword=true --savelogin=true` options to automate it after creation.

```
$ asadmin create-domain --template ${PAYARA_HOME}/glassfish/common/templates/gf/production-domain.jar --savemasterpassword=true --usemasterpassword=true --savelogin=true --portbase 8400 "myidtravel-domain"
```

2. Secure DAS
```
$ asadmin --host localhost --port 8448 enable-secure-admin
```

3. Create one node with this parametes
**Name:** `localhost-myidtravel-domain`
**Type:** `CONFIG`
**Node Host:** `localhost`
**Node Directory:** `/opt/myidtravel-nodes`
**Installation Directory:** `${com.sun.aas.productRoot}`

4. Create Instance
```
$ asadmin --port 8448 create-local-instance --portbase 28100 --savemasterpassword=true --usemasterpassword=true --node local-myidtravel-domain --nodedir /opt/myidtravel-nodes myidtravel-instance1
```
5. Start Instance from Admin Console
6. Try to restart Instance from Admin Console Instance Page, Fails but seens restart works fine!

<img width="1440" alt="instance" src="https://user-images.githubusercontent.com/32605309/71285714-8202aa00-232b-11ea-942d-01fea0f28b50.png">

```
An error has occurred
Could not sync instance myidtravel-instance1 on node local-myidtravel-domain (localhost). Command failed on node local-myidtravel-domain (localhost): Command _synchronize-instance failed. More than one node in directory /opt/aplicaciones/payara5/glassfish/nodes. Please specify --node. To complete this operation run the following command locally on host localhost from the Payara Server install location /opt/aplicaciones/payara5: lib/nadmin _synchronize-instance --sync normal myidtravel-instance1
```

## Environment ##

- **Payara Version**: 5 update 193
- **Edition**:  Full
- **JDK Version**: Zulu 8.0.222
- **Operating System**: RHEL 7
- **Database**: No

**Comment by rdebusscher** [comment] 2020-01-07 10:28
Hi,

I have created the internal issue `CUSTCOM-143` to fix the restart-instance command.

Regards
Rudy

**Comment by AlanRoth** [comment] 2020-11-11 11:52
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:52 UTC
Labels: status:accepted
