### ISSUE TITLE
server.log empty after updating from 4.1.2.174 to 4.1.2.181

### ISSUE THREAD

**Issue by md-mg** [payara/Payara#2526] opened 2018-03-14 11:31 UTC
# Description #
----------

after upgrading payarafish from 4.1.2.174 to 4.1.2.181 the server.log isn't written any more.
see also https://groups.google.com/forum/#!topic/payara-forum/48_RBEzbA4o

server.log contains only
`[2018-03-14T07:14:28.581+0100] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1521008068581] [levelValue: 800] [[
  JVM invocation command line:
/usr/local/java_1_8/bin/java
-cp
/usr/local/payara41/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:+ScavengeBeforeFullGC
-XX:MaxMetaspaceSize=1024m
-XX:-HeapDumpOnOutOfMemoryError
-XX:+PrintGCDetails
-XX:+UseG1GC
-XX:PermSize=512m
-XX:MaxPermSize=512m
-Xms4096M
-Xmx4096M
-Xloggc:/tmp/gc.log
-server
-javaagent:/usr/local/payara41/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/usr/local/payara41/glassfish/domains/domain1/config/cacerts.jks
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/usr/local/payara41/glassfish/modules/autostart/
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=/usr/local/payara41/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.security.policy=/usr/local/payara41/glassfish/domains/domain1/config/server.policy
-Djava.endorsed.dirs=/usr/local/payara41/glassfish/modules/endorsed:/usr/local/payara41/glassfish/lib/endorsed
-Dfelix.fileinstall.bundles.startTransient=true
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.log.level=2
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Djavax.net.ssl.keyStore=/usr/local/payara41/glassfish/domains/domain1/config/keystore.jks
-Djava.security.auth.login.config=/usr/local/payara41/glassfish/domains/domain1/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/usr/local/payara41/glassfish/domains/domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dosgi.shell.telnet.ip=127.0.0.1
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.awt.headless=true
-Djava.ext.dirs=/usr/local/java_1_8/lib/ext:/usr/local/java_1_8/jre/lib/ext:/usr/local/payara41/glassfish/domains/domain1/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djava.library.path=/usr/local/payara41/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/usr/local/payara41/glassfish/domains/domain1
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/usr/local/payara41/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/usr/local/payara41/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false]]
`

... and then doesn't get any more entries.

- **Payara Version**: 4.1.2.181
- **Edition**: Full
- **JDK Version**: java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

- **Operating System**: CentOS 6, CentOS 7

**Comment by chrjohn** [comment] 2018-03-14 11:53
Isn't this #2400 ?

**Comment by md-mg** [comment] 2018-03-14 11:59
Ah, ok - looks like. 

Sorry, didn't find the other issue before creating this one.

**Comment by smillidge** [comment] 2018-03-14 12:35
Yep this is a duplicate of #2400

**Closed by smillidge** 2018-03-14 12:35 UTC
