### ISSUE TITLE
cannot resolve MPCONFIG-Vars in post-boot-commands /PAYARA-4178

### ISSUE THREAD

**Issue by alexander-dammeier** [payara/Payara#4206] opened 2019-09-07 10:44 UTC
# Description #
----------

I am using payara-full-docker image and tried to bind some values in my post-boot-commands to docker secrets. Therefore in my pre-boot-commands I say microprofile to use my secrets folder but while executing the post-boot-commands I got an exception.

## Expected Outcome

Vars like ${MPCONFIG=postgres_password} in post-boot-commands should be replaced with the value in my docker secrets files.

Variables in post-boot-commands are possible, [see](https://docs.payara.fish/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.html)
and there is no comment that MPCONFIG-vars should not work in post-boot-commands.

For my usecase (securing payara with secrets and make it easy to change passwords) it would be easier if the vars are not translated to its value but directly written to the property so that payara resolves the variable everytime using it.  

## Current Outcome

I got an exception while executing the post-boot-commands:
```
my-payara | [#|2019-09-07T09:02:48.636+0000|INFO|Payara 5.193||_ThreadID=1;_ThreadName=main;_TimeMillis=1567846968636;_LevelValue=800;|
my-payara |   Reading in commandments from /opt/payara/config/post-boot-commands.asadmin|#]
my-payara |
my-payara | [#|2019-09-07T09:02:48.662+0000|SEVERE|Payara 5.193|com.sun.enterprise.glassfish.bootstrap.GlassFishMain|_ThreadID=1;_ThreadName=main;_TimeMillis=1567846968662;_LevelValue=1000;|
my-payara |   java.lang.ExceptionInInitializerError
my-payara |     at org.glassfish.config.support.TranslatedConfigView.getTranslatedValue(TranslatedConfigView.java:146)
my-payara |     at org.glassfish.config.support.TranslatedConfigView.expandValue(TranslatedConfigView.java:104)
my-payara |     at fish.payara.boot.runtime.BootCommands.parseCommandScript(BootCommands.java:111)
my-payara |     at fish.payara.boot.runtime.BootCommands.parseCommandScript(BootCommands.java:98)
my-payara |     at fish.payara.boot.runtime.BootCommands.parseCommandScript(BootCommands.java:92)
my-payara |     at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:293)
my-payara |     at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:133)
my-payara |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
my-payara |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
my-payara |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
my-payara |     at java.lang.reflect.Method.invoke(Method.java:498)
my-payara |     at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
my-payara |     at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
my-payara | Caused by: java.lang.IllegalStateException: No ConfigProviderResolver implementation found!
my-payara |     at org.eclipse.microprofile.config.spi.ConfigProviderResolver.instance(ConfigProviderResolver.java:122)
my-payara |     at org.eclipse.microprofile.config.ConfigProvider.<clinit>(ConfigProvider.java:74)
my-payara |     ... 13 more
```

Interesting is that the exception was thrown before any post-boot-commands were executed. So variables seems to be resolved in the whole file before any commands will be executed.

I can confirm that the secrets were read correctly by payara (see steps to reproduce, step 7)

## Steps to reproduce

1. setup all files for docker-compose (see samples)

1.1 create dockerfile and command files

/payara/Dockerfile
```
FROM payara/server-full:latest
COPY --chown=payara:payara pre-boot-commands.asadmin $PREBOOT_COMMANDS
COPY --chown=payara:payara post-boot-commands.asadmin $POSTBOOT_COMMANDS
```
/payara/pre-boot-commands.asadmin
```
set-config-dir --directory=/run/secrets/ --target=server-config
set-environment-warning-configuration --enabled=true --message=mytext --textcolour="#ffffff" --backgroundcolour="#ff0000"

```
/payara/post-boot-commands.asadmin
```
#create-jdbc-connection-pool --validateAtmostOncePeriodInSeconds=0 --sqlTraceListeners=fish.payara.jdbc.SilentSqlTraceListener --statementLeakReclaim=false --ping=false --maxWaitTimeInMillis=60000 --wrapJdbcObjects=true --connectionValidationMethod=table --steadyPoolSize=8 --idleTimeoutInSeconds=300 --maxConnectionUsageCount=0 --matchConnections=false --connectionCreationRetryIntervalInSeconds=10 --associateWithThread=false --isConnectionValidationRequired=false --connectionLeakReclaim=false --datasourceClassname=org.postgresql.ds.PGSimpleDataSource --connectionCreationRetryAttempts=0 --statementCacheSize=0 --resType=javax.sql.DataSource --statementLeakTimeoutInSeconds=0 --failAllConnections=false --statementTimeoutInSeconds=-1 --lazyConnectionEnlistment=false --pooling=true --poolResizeQuantity=2 --allowNonComponentCallers=false --connectionLeakTimeoutInSeconds=0 --isIsolationLevelGuaranteed=true --maxPoolSize=32 --nonTransactionalConnections=false --lazyConnectionAssociation=false project-pool
#set resources.jdbc-connection-pool.project-pool.property.user=${MPCONFIG=postgres_user} resources.jdbc-connection-pool.project-pool.property.password=${MPCONFIG=postgres_password} resources.jdbc-connection-pool.project-pool.property.databaseName=${MPCONFIG=postgres_db} resources.jdbc-connection-pool.project-pool.property.datasourceName=postgres resources.jdbc-connection-pool.project-pool.property.serverName=project-postgres resources.jdbc-connection-pool.project-pool.property.portNumber=5432

```

1.2 create docker secrets

/secrets/postgres_user.txt
```
user
```
/secrets/postgres_password.txt
```
admin
```
/secrets/postgres_db.txt
```
project_db
```

1.3 create docker-compose-file

/docker-compose.yml
```
version: '3.2'
services:
  
  payara:
    build:
      context: ./payara
    ports:
      - "4848:4848"
      - "9009:9009"
    container_name: my-payara
    networks:
      - my-net
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db

networks:
  my-net:

secrets:
    postgres_password:
        file: secrets/postgres_password.txt
    postgres_user:
        file: secrets/postgres_user.txt
    postgres_db:
        file: secrets/postgres_db.txt
```
2. start server
(open console in the folder of the compose-file)
`docker-compose up --build`
3. check if pre-boot-commands work correctly
```
my-payara | Sep 07, 2019 8:49:32 AM fish.payara.boot.runtime.BootCommand execute
my-payara | INFO: Boot Command set-config-dir returned with result SUCCESS : PlainTextActionReporterSUCCESSUsing readable directory at /run/secrets
my-payara |
my-payara | Sep 07, 2019 8:49:32 AM fish.payara.boot.runtime.BootCommand execute
my-payara | INFO: Boot Command set-environment-warning-configuration returned with result SUCCESS : PlainTextActionReporterSUCCESSNo monitoring data to report.
```
4. Error occured (see current outcome)
5. stop server
```
CTRL+C
docker-compose down
```
5. remove post-boot-commands
6. start server again
`docker-compose up --build`
7. check if docker secrets were loaded in payara
7.1 log in to admin console
[localhost:4848](https://localhost:4848)
user: `admin`
pw: `admin`
7.2 add var to Domain/environment warning/Warning Message
`${MPCONFIG=postgres_password}`
7.3 check if enironment warning shows 'admin' on top of the console

### Samples

[bug report1.zip](https://github.com/payara/Payara/files/3586505/bug.report1.zip)

## Environment ##

- **Payara Version**: Docker latest (5.193)
- **Edition**: Full
- **JDK Version**: 8 OpenJDK
- **Operating System**: Windows10 with Docker for Windows (Hyper-V)
- **Database**: PostGres

**Comment by rdebusscher** [comment] 2019-10-01 10:26
Hi @alexander-dammeier,

Thank you for the reproducer.  MicroProfile Config is designed for application configuration and therefor not available during the execution of the post boot command file.

However, such a feature request sound reasonable and I have created the internal issue PAYARA-4178 so that the engineering team can pick up this request. 

Thank you
Regards
Rudy

**Comment by AlanRoth** [comment] 2020-11-11 11:47
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed** 2020-11-11 11:47 UTC
Labels: enhancement, status:accepted
