### ISSUE TITLE
JAX-RS message body writer looking at wrong class

### ISSUE THREAD

**Issue by mohamnag** [payara/Payara#1258] opened 2016-12-30 09:25 UTC
# Description #
----------

Trying to get a polymorphic response out of a JAX-RS resource using some JAXB annotated class hierarchy but it seems that the message body writer is examining the wrong class for finding proper annotations. 

Having following classes:
```java
package com.mohamnag.others;

import java.io.Serializable;

public class SuperDto implements Serializable {
}
```

```java
package com.mohamnag.others;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class SomeDto extends SuperDto {

    private int instanceCount;
    private String oneThing;

    private SomeDto() {
    }

    public SomeDto(String oneThing, int instanceCount) {
        this.oneThing = oneThing;
        this.instanceCount = instanceCount;
    }

    @XmlElement
    public int getInstanceCount() {
        return instanceCount;
    }

    @XmlElement
    public String getOneThing() {
        return oneThing;
    }

}
```

and this resource:
```java
package com.mohamnag.test;

import com.mohamnag.others.SomeDto;
import com.mohamnag.others.SuperDto;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("test")
public class TestResource {
    
    @GET
    @Path("dto")
    @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
    public SomeDto getDto() {
        return new SomeDto("first thing", -1);
    }

    @GET
    @Path("dto2")
    @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
    public SuperDto getDto2() {
        return new SomeDto("first thing", -2);
    }

    @GET
    @Path("dto3")
    @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
    public Object getDto3() {
        return new SomeDto("first thing", -3);
    }

}
```

Trying to access `test/dto`, `test/dto2` and `test/dto3` produces different results or even exceptions.

## Expected Outcome

is that any of the resources return a response similar to following structure:
```json
{
  "instanceCount": -3,
  "oneThing": "first thing"
}
```

## Current Outcome

accessing `test/dto` returns (kind of) expected data:
```json
{
  "type": "someDto",
  "instanceCount": -1,
  "oneThing": "first thing"
}
```

accessing `test/dto2` returns empty:
```json
{}
```

and accessing `test/dto3` returns this error and nothing in the logs:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Payara Server  4.1.1.164 #badassfish - Error report</title>
        <style type="text/css">
            <!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}-->
        </style>
    </head>
    <body>
        <h1>HTTP Status 500 - Internal Server Error</h1>
        <hr/>
        <p>
            <b>type</b> Status report
        </p>
        <p>
            <b>message</b>Internal Server Error
        </p>
        <p>
            <b>description</b>The server encountered an internal error that prevented it from fulfilling this request.
        </p>
        <hr/>
        <h3>Payara Server  4.1.1.164 #badassfish</h3>
    </body>
</html>
```

it seems to me that body writer is kind of looking at static type of returned object and not the actual runtime type. (Just for comparison, WildFly returns expected result on all three resources)

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full & Micro
- **JDK Version**: 8 u112 - Oracle
- **Operating System**: Mac

**Comment by mohamnag** [comment] 2016-12-30 12:18
so interesting enough, this problem does not happen in the microprofile 164.1. When running with microprofile 164.1, all the resources return following (expected) response:

```json
{
  "instanceCount": 1,
  "oneThing": "one thing"
}
```

**Comment by mikecroft** [comment] 2016-12-30 12:59
I would imagine this is because you will be using JAXB provided by Java SE in microprofile, whereas other versions of Payara would use the reference implementation which, I believe, is covered  by Metro
https://jaxb.java.net/

**Comment by mohamnag** [comment] 2016-12-30 13:20
your point helped me find [this](http://stackoverflow.com/questions/9219355/why-jaxb-is-not-marshalling-my-own-subclass) and changing the super class helped at least to have proper response from `dto` and `dto2` paths:
```java
package com.mohamnag.others;

import javax.xml.bind.annotation.XmlSeeAlso;
import java.io.Serializable;

@XmlSeeAlso({SomeDto.class})
public class SuperDto implements Serializable {
}
```

however `dto3` throws as before an exception which is understandable. I wonder however whether this functionality is defined and intended in JAXB or is it just implementation level problem. Specially when I see how Oracle's JDK (which is probably reference of all references ;) ) acts differently.

PS: I'm also wondering what did people think when they agreed on this! Java EE is so heavily relying of reflection, even on unsafe actions in reflection (like accessing private ctors and co) but here they stop all of a sudden and rely only on an annotation!

**Comment by fturizo** [comment] 2016-12-30 23:12
As @mikecroft mentioned this is indeed caused by using the JAXB prepackaged MessageBodyWriter to handle XML and JSON (via EclipseLink MOXy) marshalling on Payara Server in accordance to Java EE. As you say the way the JAXB annotation API works is kind of convoluted, hence the idea of providing a far simpler API with JSONB (akin to what Jackson does on Spring) is being worked on Java EE 8.

I'm closing the issue since your problem has been solved, but feel free to reopen it if you have more questions about JAXB related use cases.

**Closed by fturizo** 2016-12-30 23:12 UTC
Labels: 1:Wait, c:Misconfiguration
