### ISSUE TITLE
Bug Report: __admingui web application should only works on Mojarra

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#6375] opened 2023-08-23 08:55 UTC
### Brief Summary

As PayaraDAS server's administration web application, __admingui should only dependents on the embedded JSF implementation (Mojarra). In any other case, for example, customer maybe load other JSF implementation for their own web application.

but unfortunately, in my case, my web applications heavily dependents on Primefaces (JSF implementation), in Payara 5 they work fine, but in Payara 6, when primefaces was loaded as domain lib, will cause __admingui failed to start.

### Expected Outcome

__admingui web application should works fine even other JSF implementation was loaded in domain lib.

### Current Outcome

When primefaces-13.0.0-jakarta.jar was loaded into domain lib, payara DAS's __admingui not start properly.

### Reproducer

Clean installed payara-6.2023.8 on Rocky Linux 9, and production domain created. resources (database resource, jms and mail resource) added, three payara instances created,

When primefaces-13.0.0-jakarta.jar was loaded into production domain's lib, restart domain from command line.

DAS server started, but __admingui web application failed to start.

Payara thows "java.lang.IllegalArgumentException: argument type mismatch" error, 

and "java.lang.ClassCastException: class org.primefaces.application.resource.DynamicResourcesPhaseListener cannot be cast to class jakarta.faces.event.PhaseListener (org.primefaces.application.resource.DynamicResourcesPhaseListener is in unnamed module of loader com.sun.enterprise.loader.CurrentBeforeParentClassLoader @2264ea32; jakarta.faces.event.PhaseListener is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @4732bdfa"

and "java.lang.NoSuchMethodException: org.primefaces.application.resource.PrimeResourceHandler.<init>()"

and even more.
[server.log](https://github.com/payara/Payara/files/12417254/server.log)

I had dumped the DAS server's server.log, please find it in attachment.

### Operating System

Rocky Linux 9

### JDK Version

Oracle idk 17.0.7

### Payara Distribution

Payara Server Full Profile

**Comment by felixif** [comment] 2023-08-29 15:30
Hello @cidylong,

Thank you for reporting this issue. Could you try adding the library as an extension library:
`./asadmin add-library --type=ext primefaces.jar`
And check if the `primefaces.jar` works correctly in your environment?

**Comment by cidylong** [comment] 2023-08-30 21:41
I found a work around. 

Add it as app lib

    $PAYARA_HOME/bin/asadmin --passwordfile /home/payara/config/payaraPW.txt add-library --type app /home/payara/software/lib/primefaces-13.0.0-jakarta.jar

Then restart-domain, __admingui started properly

When deploy application, need add application lib as:

    $PAYARA_HOME/bin/asadmin --passwordfile /home/payara/config/payaraPW.txt deploy --libraries primefaces-13.0.0-jakarta.jar --force=true --target APPDG --enabled=true --type ejb --name EjbJar /home/payara/software/ejb/EjbJar-1.0-SNAPSHOT.jar

EJB application works fine as well.

I will test web application later.

**Comment by cidylong** [comment] 2023-08-30 21:43
@felixif , I tested with app libs, it works fine. Thank you for your advice.

**Comment by felixif** [comment] 2023-08-31 08:12
Hello @cidylong,

I am glad you managed to resolve the issue. If there are no more problems related to this issue, is it okay for me to close this issue?

**Comment by felixif** [comment] 2023-08-31 12:21
Hello @cidylong,

I will close the issue now that you have confirmed that the issue is fixed on your end.

**Closed by felixif** 2023-08-31 12:21 UTC
Labels: Type: Bug, Status: Pending
