### ISSUE TITLE
Failed deployment to a cluster via deployment group /CUSTCOM-78

### ISSUE THREAD

**Issue by siruslan** [payara/Payara#2765] opened 2018-05-24 14:28 UTC
# Failed redeployment from one target to another #
----------
We are trying to figure out why some deployments fail while others work. 
I have an example of two completely identical applications deployed into the same group. One of them is running fine (newapp) and another one fails to start (test)

<img src="https://lh3.googleusercontent.com/-Uy42WtdwHbM/WwTvI3kZ0KI/AAAAAAAAHaI/QzUiixYH4Z0HdJwoSYuGSwoPXbmlUFw8gCLcBGAs/s1600/Screen%2BShot%2B2018-05-23%2Bat%2B6.32.20%2BAM.png">

The only difference that non working test application was previously deployed into another target (server) and it worked fine there. Then later it was undeployed and redeployed into the new target (group1)

Both applications have the same target at the end.

There is a little bit information about the issue in the logs of a worker instance.

```
[2018-05-23T03:24:20.235+0000] [Payara 5.181] [INFO] [NCLS-CORE-00022] [javax.enterprise.system.core] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045860235] [levelValue: 800] [[
  Loading application test done in 3,832 ms]]

[2018-05-23T03:24:24.412+0000] [Payara 5.181] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864412] [levelValue: 800] [[
  Hazelcast Instance Bound to JNDI at payara/Hazelcast]]

[2018-05-23T03:24:24.414+0000] [Payara 5.181] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864414] [levelValue: 800] [[
  JSR107 Caching Provider Bound to JNDI at payara/CachingProvider]]

[2018-05-23T03:24:24.415+0000] [Payara 5.181] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864415] [levelValue: 800] [[
  JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager]]

[2018-05-23T03:24:24.428+0000] [Payara 5.181] [INFO] [AS-WEB-GLUE-00206] [javax.enterprise.web] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864428] [levelValue: 800] [[
  Web module test not loaded to any virtual servers]]

[2018-05-23T03:24:24.429+0000] [Payara 5.181] [SEVERE] [] [javax.enterprise.web] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864429] [levelValue: 1000] [[
  webApplication.unknownError]]

[2018-05-23T03:24:24.430+0000] [Payara 5.181] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864430] [levelValue: 1000] [[
  Module not started com.sun.enterprise.web.WebApplication@357e1702]]

[2018-05-23T03:24:24.432+0000] [Payara 5.181] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864432] [levelValue: 1000] [[
  Exception while invoking class com.sun.enterprise.web.WebApplication start method
java.lang.Exception: Module not started com.sun.enterprise.web.WebApplication@357e1702
 at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:296)
 at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
 at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:538)
 at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:334)
 at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:327)
 at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
 at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
 at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
 at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:89)
 at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
 at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
 at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
 at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
 at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
]]

[2018-05-23T03:24:24.436+0000] [Payara 5.181] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864436] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.Exception: Module not started com.sun.enterprise.web.WebApplication@357e1702
 at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:296)
 at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
 at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:538)
 at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:334)
 at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:327)
 at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
 at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
 at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
 at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:89)
 at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
 at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
 at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
 at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
 at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
]]

[2018-05-23T03:24:24.438+0000] [Payara 5.181] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864438] [levelValue: 1000] [[
  Exception while loading the app]]

[2018-05-23T03:24:24.439+0000] [Payara 5.181] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=21 _ThreadName=RunLevelControllerThread-1527045852892] [timeMillis: 1527045864439] [levelValue: 1000] [[
  Undeployment failed for context /test]]
```

The issue appears only at Payara, the same deployment flow works fine with GlassFish. 

## Expected Outcome

Two applications should be deployed and available 

## Current Outcome

Only one 'newapp' is deployed.   

## Steps to reproduce (Only for bug reports) 

```
$asadmin undeploy --target server test
Command undeploy executed successfully.

$asadmin deploy --availabilityenabled=true --asyncreplication=false --force=true --target group1 --contextroot test test/test.war
Application deployed with name test.
Command deploy executed successfully.
```

## Context (Optional)

Redeploy project from standalone server to a cluster via deployment group

## Environment ##

- **Payara Version**: 5.181
- **Edition**: Full
- **JDK Version**: OpenJDK 1.8.0u171
- **Operating System**: Linux

**Comment by smillidge** [comment] 2018-05-30 16:23
I have tried this many times and I can't reproduce it. Do you have any hints?

**Comment by siruslan** [comment] 2018-06-19 02:46
@smillidge, thank you for reviewing the issue. Let me provide more details how the redeployment process works in our case. Initially we create only one standalone node. Then we deploy a war application. Afterward we add one more node and the platform automatically creates additional dedicated DAS node, configures cluster in the domain mode and performs set of actions: 

1. Copying /glassfish/domains/domain1/config/domain.xml from the initial Standalone to the new DAS node
2. Starting the DAS node
3. Redeploying apps from Standalone to the DAS by undeploying from target "server" to the new target "cluster1" 
```
Redeploying apps from standalone server to cluster1
/opt/payara/glassfish/domains/domain1/applications/__internal
Undeploying myapp from standalone server
/opt/payara/bin/asadmin --user admin --interactive=false --passwordfile /home/jelastic/.ssh/pwdfile --host 172.25.2.132 --port 4848 --secure undeploy --target server myapp
Command undeploy executed successfully.

Deploying myapp/myapp.war to myapp...
/opt/payara/bin/asadmin --user admin --interactive=false --passwordfile /home/jelastic/.ssh/pwdfile --host 172.25.2.132 --port 4848 --secure deploy --availabilityenabled=true --asyncreplication=false --force=true --target cluster1 --contextroot myapp myapp/myapp.war
Application deployed with name myapp.
Command deploy executed successfully.  
```
Please note that DAS node is located inside an isolated container - in a different one than the initial standalone node, so maybe we miss something during redeployment process.

I have a running cluster with this issue in our demo lab. I can provide an access, so it may help to speed up troubleshooting.

**Comment by rdebusscher** [comment] 2019-12-17 10:53
There is currently a similar internally issue related to un/re/deployment to a deployment group.  issue `CUSTCOM-78`.

**Comment by AlanRoth** [comment] 2020-11-11 11:16
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:16 UTC
Labels: status:accepted
