### ISSUE TITLE
create-auth-realm in prebootcomandfile doesn't handle spaces in dn property /CUSTCOM-91

### ISSUE THREAD

**Issue by berryma4** [payara/Payara#2698] opened 2018-05-01 19:23 UTC
# Description #
----------
The space in "Some Accounts" gives an exception when used in a prebootcommandfile in micro payara

```
create-auth-realm --classname com.sun.enterprise.security.auth.realm.ldap.LDAPRealm --property jaas-context=ldapRealm:directory=ldap\://mydomain\:389:base-dn=dc\=my,dc\=domain:group-base-dn=dc\=my,dc\=domain:group-search-filter=(&(objectClass\=group)(member\:1.2.840.113556.1.4.1941\:\=%d)):java.naming.referral=follow:search-filter=(&(objectClass\=user)(sAMAccountName\=%s)):search-bind-password=mypassword:search-bind-dn=cn\=Doug,ou\=Some Accounts,dc\=my,dc\=domain mine
```
## Expected Outcome

to create an auth realm
I've tried escaping the space in many ways ie. "\ " or various ways of using quotes to no avail.

## Current Outcome

```java
Exception while running a command
org.glassfish.common.util.admin.UnacceptableValueException: Invalid parameter: authrealmname.  This parameter may not have more than one value.
	at org.glassfish.common.util.admin.MapInjectionResolver.convertListToObject(MapInjectionResolver.java:413)
	at org.glassfish.common.util.admin.MapInjectionResolver.getValue(MapInjectionResolver.java:141)
	at org.jvnet.hk2.config.InjectionManager.syncDoInject(InjectionManager.java:170)
	at org.jvnet.hk2.config.InjectionManager.inject(InjectionManager.java:74)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.injectParameters(CommandRunnerImpl.java:378)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1234)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
	at fish.payara.micro.boot.runtime.BootCommand.execute(BootCommand.java:65)
	at fish.payara.micro.boot.runtime.BootCommands.executeCommands(BootCommands.java:106)
	at fish.payara.micro.boot.runtime.BootCommands.executeCommands(BootCommands.java:100)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1005)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:383)
]]

[2018-05-01T15:13:13.654-0400] [] [WARNING] [] [fish.payara.micro.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1525201993654] [levelValue: 900] [[
  Boot Command create-auth-realm failed PlainTextActionReporterFAILUREorg.glassfish.common.util.admin.UnacceptableValueException: Invalid parameter: authrealmname.  This parameter may not have more than one value.Description: create-auth-realm commandInvalid parameter: authrealmname.  This parameter may not have more than one value.
    Usage: create-auth-realm --classname=classname [--property=property] [--target=server] authrealmname 
]]

```

## Steps to reproduce (Only for bug reports) 

/usr/bin/java -Xmx2G -jar myjar.jar --sslport ${SERVICESSLPORT} --nocluster true --port ${SERVICEPORT} --prebootcommandfile /etc/myprogram/asadmin_commands --logProperties /etc/myprogram/logging.properties

## Environment ##

- **Payara Version**: 5.181
- **Edition**: Micro
- **JDK Version**: Oracle 1.8.0_161-b12
- **Operating System**: Linux
- **Database**: None

**Comment by mikecroft** [comment] 2018-05-02 07:26
AFAIK, `asadmin` commands will not work in a **pre** boot commandfile, since it's too early in the boot sequence and dependent services won't have started. Try using `--postbootcommandfile` instead.

**Comment by berryma4** [comment] 2018-05-02 10:45
But this is a parsing exception, because of not being able to escape the space.  It "works" if I remove the space.  Is the ```postbootcommandfile``` parsed differently?

**Comment by rdebusscher** [comment] 2019-12-17 10:49
I have created `CUSTCOM-91` for this.

**Comment by AlanRoth** [comment] 2020-11-11 11:16
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:16 UTC
Labels: status:accepted
