### ISSUE TITLE
Custom Resource injection failing using payara embedded /CUSTCOM-60

### ISSUE THREAD

**Issue by feldob** [payara/Payara#1019] opened 2016-08-12 12:33 UTC
Using Payara embedded 4.1.1.162, the injection of a custom JNDI String resource into an EJB fails. Deploying the same EJB to regular Payara 4.1.1.162 works just fine.

I've created a minimal variant of that problem here:

https://github.com/feldob/resource_injection_problem_payara_embedded_4.1.1.162

The error message can be found in startup.txt.

Regards,
Felix

**Comment by mulderbaba** [comment] 2016-08-12 21:43
@feldob, I sent a PR for your sample project fixing a couple of minor maven problems. I executed PayaraBootstrap but ended with no problem? see the output below.

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java -Dvisualvm.id=92095095243532 -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 2.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/tools.jar:/Users/mertcaliskan/Desktop/work/Payara/tasks/git-1019/resource_injection_problem_payara_embedded_4.1.1.162/payara-embedded/target/classes:/Users/mertcaliskan/.m2/repository/fish/payara/extras/payara-embedded-all/4.1.1.162/payara-embedded-all-4.1.1.162.jar:/Applications/IntelliJ IDEA 2.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.bug.PayaraBootstrap
Aug 13, 2016 12:40:09 AM org.glassfish.security.services.impl.authorization.AuthorizationServiceImpl initialize
INFO: Authorization Service has successfully initialized.
Aug 13, 2016 12:40:09 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.2.Final
Aug 13, 2016 12:40:10 AM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Grizzly Framework 2.3.24 started in: 28ms - bound to [/0.0.0.0:8085]
Aug 13, 2016 12:40:10 AM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Grizzly Framework 2.3.24 started in: 1ms - bound to [/0.0.0.0:8086]
Aug 13, 2016 12:40:10 AM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
Aug 13, 2016 12:40:10 AM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
Aug 13, 2016 12:40:10 AM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
Aug 13, 2016 12:40:10 AM com.sun.enterprise.v3.server.AppServerStartup postStartupJob
INFO: Undefined Product Name - define product and version info in config/branding  0.0.0.0.0  (0) startup time : Embedded (1,635ms), startup services(1,016ms), total(2,651ms)
Aug 13, 2016 12:40:10 AM fish.payara.nucleus.util.CleanupPostBoot event
INFO: Cleaning JarFileFactory Cache to prevent jar FD leaks
Aug 13, 2016 12:40:10 AM org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread run
INFO: JMXStartupService has disabled JMXConnector system
Aug 13, 2016 12:40:10 AM com.sun.enterprise.connectors.jms.util.JmsRaUtil getInstalledMqVersion
WARNING: jmsra.upgrade_check_failed
Aug 13, 2016 12:40:11 AM org.bug.PayaraBootstrap createCustomResource
INFO: exit status for the addition of custom resource: SUCCESS

```

**Comment by feldob** [comment] 2016-08-13 09:40
@mulderbaba , I investigated the changes and found that the version tag that was added in resource-bug/pom.xml caused that server output. However, the EJB deployment seems to not take place (server halt). Commenting the version tag out will make the startup fail again. The error happens at runtime when injecting.

I extended the case slightly to make it more obvious that the injection is causing the error; you find the changes in the new version of org.bug.InjectResource on

https://github.com/feldob/resource_injection_problem_payara_embedded_4.1.1.162

Regards,
Felix

**Comment by mulderbaba** [comment] 2016-08-13 22:03
@feldob can you add a readme or state here the exact steps for reproducing the error with your sample project please? Maven project demands GAV (groupid:artifactid:version) so having version commented out breaks on "maven install" build for me and will eventually break the project within my IDE,  intellij idea.

**Comment by feldob** [comment] 2016-08-14 09:21
@mulderbaba OK, I should have been more precise. The version tag in module resource-bug was wrongly set to 

0.0.1-snapshot

but when changing it to 

0.0.1-SNAPSHOT

Eclipse tells me that "Version is duplicate of parent version". That is why I removed the then redundant tag. The GAV is held by the parent project.

Everything should build after a git clone and "mvn install" from the root. Let me know if there is a problem.

Regards,
Felix

**Comment by mulderbaba** [comment] 2016-08-14 14:09
@feldob, ok got a successful build with maven 3.3.9 on your last commit (commit id: 315bcdedb18cd45e684189ff3a22db6337502eec). Version handling is a little bit different with 3.0.x branch of maven, which was accidentally defined in my run config with the previous build. 

After running PayaraBootstrap, I got the output below, I guess I still couldn't reproduce the problem?
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java -Dvisualvm.id=98931335005823 -Didea.launcher.port=7535 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 2.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/tools.jar:/Users/mertcaliskan/Desktop/work/Payara/tasks/git-1019/resource_injection_problem_payara_embedded_4.1.1.162/payara-embedded/target/classes:/Users/mertcaliskan/.m2/repository/fish/payara/extras/payara-embedded-all/4.1.1.162/payara-embedded-all-4.1.1.162.jar:/Applications/IntelliJ IDEA 2.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.bug.PayaraBootstrap
Aug 14, 2016 5:07:14 PM org.glassfish.security.services.impl.authorization.AuthorizationServiceImpl initialize
INFO: Authorization Service has successfully initialized.
Aug 14, 2016 5:07:14 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.2.Final
Aug 14, 2016 5:07:14 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Grizzly Framework 2.3.24 started in: 23ms - bound to [/0.0.0.0:8085]
Aug 14, 2016 5:07:14 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Grizzly Framework 2.3.24 started in: 1ms - bound to [/0.0.0.0:8086]
Aug 14, 2016 5:07:14 PM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
Aug 14, 2016 5:07:14 PM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
Aug 14, 2016 5:07:14 PM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
Aug 14, 2016 5:07:15 PM com.sun.enterprise.v3.server.AppServerStartup postStartupJob
INFO: Undefined Product Name - define product and version info in config/branding  0.0.0.0.0  (0) startup time : Embedded (1,593ms), startup services(815ms), total(2,408ms)
Aug 14, 2016 5:07:15 PM fish.payara.nucleus.util.CleanupPostBoot event
INFO: Cleaning JarFileFactory Cache to prevent jar FD leaks
Aug 14, 2016 5:07:15 PM org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread run
INFO: JMXStartupService has disabled JMXConnector system
Aug 14, 2016 5:07:15 PM com.sun.enterprise.connectors.jms.util.JmsRaUtil getInstalledMqVersion
WARNING: jmsra.upgrade_check_failed
Aug 14, 2016 5:07:15 PM org.bug.PayaraBootstrap createCustomResource
INFO: exit status for the addition of custom resource: SUCCESS

```

**Comment by feldob** [comment] 2016-08-15 06:31
@mulderbaba I've added a brief 'howto' in the readme.md. Please take a look inside.

Regards,
Felix

**Comment by mulderbaba** [comment] 2016-08-15 11:46
@feldob thanks, now I can reproduce the problem with your sample project.

**Comment by feldob** [comment] 2016-08-15 12:27
@mulderbaba great, we're making progress :)

**Comment by mikecroft** [comment] 2017-07-13 14:23
`PAYARA-1258`

**Comment by smillidge** [comment] 2019-04-25 20:30
Please try Payara 5 and see if it is still a problem there.

**Comment by rdebusscher** [comment] 2019-12-05 08:43
Still reproducible on 5.194, but works on Payara Server

**Comment by rdebusscher** [comment] 2019-12-05 08:45
Created internal issue `CUSTCOM-60`

**Comment by AlanRoth** [comment] 2020-11-11 10:22
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:22 UTC
Labels: status:accepted
