### ISSUE TITLE
payara/server-full:latest image crashes

### ISSUE THREAD

**Issue by skonx** [payara/Payara#3434] opened 2018-11-19 11:25 UTC
# Description #
----------

The latest image of payara/server-full on docker hub crashes at startup.

Furthermore, latest tag seems to be earlier than 5.183.

![screenshot 2018-11-19 at 12 15 22](https://user-images.githubusercontent.com/19473981/48703897-74916280-ebf5-11e8-904d-91f885a8a705.png)

## Expected Outcome

Start as expected without errors

## Current Outcome

Crach with a SSL / Security exception

## Steps to reproduce (Only for bug reports) 

jsie-macbook:payara-datagrid jsie$ docker run -it --rm -p 4848:4848 payara/server-full
Unable to find image 'payara/server-full:latest' locally
latest: Pulling from payara/server-full
bc9ab73e5b14: Pull complete 
193a6306c92a: Pull complete 
e5c3f8c317dc: Pull complete 
a587a86c9dcb: Pull complete 
a4c7ee7ef122: Pull complete 
a7c0dad691e9: Pull complete 
367a6a68b113: Pull complete 
60c0e52d1ec2: Pull complete 
c9d22bc43935: Pull complete 
33d5c45c6b61: Pull complete 
cf31ef02ea62: Pull complete 
0debc0462c30: Pull complete 
488b2f2a6275: Pull complete 
Digest: sha256:4f1d03a8b1988dd0b3c99ea7279c1eda51b651c4a77518eeee8f3f7b8f10ae51
Status: Downloaded newer image for payara/server-full:latest
Executing Payara Server with the following command line:
/docker-java-home/bin/java -cp /opt/payara5/glassfish/modules/glassfish.jar -XX:+UnlockDiagnosticVMOptions -XX:NewRatio=2 -Xbootclasspath/p:/opt/payara5/glassfish/lib/grizzly-npn-bootstrap.jar -Xmx512m -client -javaagent:/opt/payara5/glassfish/lib/monitor/flashlight-agent.jar -Djavax.xml.accessExternalSchema=all -Djavax.net.ssl.trustStore=/opt/payara5/glassfish/domains/domain1/config/cacerts.jks -Djdk.tls.rejectClientInitiatedRenegotiation=true -Djdk.corba.allowOutputStreamSubclass=true -Dfelix.fileinstall.dir=/opt/payara5/glassfish/modules/autostart/ -Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall -Dcom.sun.aas.installRoot=/opt/payara5/glassfish -Dfelix.fileinstall.poll=5000 -Djava.endorsed.dirs=/opt/payara5/glassfish/modules/endorsed:/opt/payara5/glassfish/lib/endorsed -Djava.security.policy=/opt/payara5/glassfish/domains/domain1/config/server.policy -Dosgi.shell.telnet.maxconn=1 -Dfelix.fileinstall.bundles.startTransient=true -Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory -Dfelix.fileinstall.log.level=2 -Djavax.net.ssl.keyStore=/opt/payara5/glassfish/domains/domain1/config/keystore.jks -Djava.security.auth.login.config=/opt/payara5/glassfish/domains/domain1/config/login.conf -Dfelix.fileinstall.disableConfigSave=false -Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager -Dfelix.fileinstall.bundles.new.start=true -Dcom.sun.aas.instanceRoot=/opt/payara5/glassfish/domains/domain1 -Dosgi.shell.telnet.port=6666 -Dgosh.args=--nointeractive -Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as -Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false -Dosgi.shell.telnet.ip=127.0.0.1 -DANTLR_USE_DIRECT_CLASS_LOADING=true -Djava.awt.headless=true -Dcom.ctc.wstx.returnNullForDefaultNamespace=true -Djava.ext.dirs=/docker-java-home/lib/ext:/docker-java-home/jre/lib/ext:/opt/payara5/glassfish/domains/domain1/lib/ext -Djdbc.drivers=org.apache.derby.jdbc.ClientDriver -Dorg.glassfish.grizzly.nio.DefaultSelectorHandler.force-selector-spin-detection=true -Djava.library.path=/opt/payara5/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib com.sun.enterprise.glassfish.bootstrap.ASMain -upgrade false -read-stdin true -postbootcommandfile /opt/payara5/post-boot-commands.asadmin -domainname domain1 -domaindir /opt/payara5/glassfish/domains/domain1 -asadmin-args --host,,,localhost,,,--port,,,4848,,,--passwordfile,,,/opt/pwdfile,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=false,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/opt/payara5/glassfish/domains,,,domain1 -instancename server -type DAS -verbose false -asadmin-classpath /opt/payara5/glassfish/lib/client/appserver-cli.jar -debug false -asadmin-classname com.sun.enterprise.admin.cli.AdminMain -watchdog false

Launching Payara Server on Felix platform
Nov 19, 2018 11:14:42 AM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@59325561 in service registry.

#!## LogManagerService.postConstruct : rootFolder=/opt/payara5/glassfish
#!## LogManagerService.postConstruct : templateDir=/opt/payara5/glassfish/lib/templates
#!## LogManagerService.postConstruct : src=/opt/payara5/glassfish/lib/templates/logging.properties
#!## LogManagerService.postConstruct : dest=/opt/payara5/glassfish/domains/domain1/config/logging.properties
[#|2018-11-19T11:14:48.544+0000|INFO|Payara 5.183|javax.enterprise.logging|_ThreadID=19;_ThreadName=RunLevelControllerThread-1542626088264;_TimeMillis=1542626088544;_LevelValue=800;_MessageID=NCLS-LOGGING-00009;|
  Running Payara Version: Payara Server  5.183 #badassfish (build 380)|#]

[#|2018-11-19T11:14:48.552+0000|INFO|Payara 5.183|javax.enterprise.logging|_ThreadID=19;_ThreadName=RunLevelControllerThread-1542626088264;_TimeMillis=1542626088552;_LevelValue=800;_MessageID=NCLS-LOGGING-00010;|
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter|#]

[#|2018-11-19T11:14:49.859+0000|INFO|Payara 5.183|org.glassfish.ha.store.spi.BackingStoreFactoryRegistry|_ThreadID=19;_ThreadName=RunLevelControllerThread-1542626088264;_TimeMillis=1542626089859;_LevelValue=800;|
  Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry|#]

[#|2018-11-19T11:14:50.026+0000|INFO|Payara 5.183|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1542626088250;_TimeMillis=1542626090026;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener http-listener-1 started in: 12ms - bound to [/0.0.0.0:8080]|#]

[#|2018-11-19T11:14:50.107+0000|INFO|Payara 5.183|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1542626088250;_TimeMillis=1542626090107;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener http-listener-2 started in: 9ms - bound to [/0.0.0.0:8181]|#]

[#|2018-11-19T11:14:50.172+0000|WARNING|Payara 5.183|org.glassfish.grizzly.config.GenericGrizzlyListener|_ThreadID=17;_ThreadName=RunLevelControllerThread-1542626088250;_TimeMillis=1542626090172;_LevelValue=900;|
  HTTP/2 (enabled by default) is unsupported with port unification and will be disabled for network listener admin-listener.|#]

[#|2018-11-19T11:14:50.220+0000|INFO|Payara 5.183|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1542626088250;_TimeMillis=1542626090220;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener admin-listener started in: 14ms - bound to [/0.0.0.0:4848]|#]

[#|2018-11-19T11:14:50.228+0000|INFO|Payara 5.183|javax.enterprise.system.core|_ThreadID=17;_ThreadName=RunLevelControllerThread-1542626088250;_TimeMillis=1542626090228;_LevelValue=800;_MessageID=NCLS-CORE-00087;|
  Grizzly 2.4.3 started in: 1,289ms - bound to [http-listener-1:8080, http-listener-2:8181, admin-listener:4848]|#]

[#|2018-11-19T11:14:50.355+0000|INFO|Payara 5.183|javax.enterprise.system.core|_ThreadID=19;_ThreadName=RunLevelControllerThread-1542626088264;_TimeMillis=1542626090355;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener iiop-service started in: 18ms - bound to [/0.0.0.0:3700]|#]

[#|2018-11-19T11:14:53.036+0000|INFO|Payara 5.183|fish.payara.nucleus.hazelcast.HazelcastCore|_ThreadID=20;_ThreadName=RunLevelControllerThread-1542626088273;_TimeMillis=1542626093036;_LevelValue=800;|
  Hazelcast Instance Bound to JNDI at payara/Hazelcast|#]

[#|2018-11-19T11:14:53.038+0000|INFO|Payara 5.183|fish.payara.nucleus.hazelcast.HazelcastCore|_ThreadID=20;_ThreadName=RunLevelControllerThread-1542626088273;_TimeMillis=1542626093038;_LevelValue=800;|
  JSR107 Caching Provider Bound to JNDI at payara/CachingProvider|#]

[#|2018-11-19T11:14:53.039+0000|INFO|Payara 5.183|fish.payara.nucleus.hazelcast.HazelcastCore|_ThreadID=20;_ThreadName=RunLevelControllerThread-1542626088273;_TimeMillis=1542626093039;_LevelValue=800;|
  JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager|#]

[#|2018-11-19T11:14:53.065+0000|INFO|Payara 5.183|fish.payara.nucleus.cluster.PayaraCluster|_ThreadID=89;_ThreadName=Executor-Service-9;_TimeMillis=1542626093065;_LevelValue=800;|
  Data Grid Status 
Payara Data Grid State: DG Version: 35 DG Size: 1
Instances: {
Address: /172.17.0.3:4900 UUID: 7a6236c7-a653-4a6d-a334-ab42180a30e8 Lite: false This: true Name: server Group: server-config
}|#]

[#|2018-11-19T11:14:53.084+0000|INFO|Payara 5.183|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1542626093084;_LevelValue=800;_MessageID=NCLS-CORE-00017;|
  Payara Server  5.183 #badassfish (380) startup time : Felix (5,606ms), startup services(4,856ms), total(10,462ms)|#]

[#|2018-11-19T11:14:53.102+0000|INFO|Payara 5.183|fish.payara.nucleus.notification.NotificationService|_ThreadID=1;_ThreadName=main;_TimeMillis=1542626093102;_LevelValue=800;|
  Payara Notification Service bootstrapped with configuration: NotificationExecutionOptions{enabled=true, notifierConfigurationExecutionOptionsList={LOG=LogNotifierConfigurationExecutionOptions{useSeparateLogFile=false} NotifierConfigurationExecutionOptions{notifierType=LOG, enabled=true, noisy=true}}}|#]

[#|2018-11-19T11:14:53.768+0000|INFO|Payara 5.183|javax.enterprise.system.core|_ThreadID=19;_ThreadName=RunLevelControllerThread-1542626088264;_TimeMillis=1542626093768;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener JMS_PROXY_default_JMS_host started in: 32ms - bound to [/0.0.0.0:7676]|#]

[#|2018-11-19T11:14:53.940+0000|INFO|Payara 5.183||_ThreadID=1;_ThreadName=main;_TimeMillis=1542626093940;_LevelValue=800;|
  Reading in commandments from /opt/payara5/post-boot-commands.asadmin|#]

[#|2018-11-19T11:14:53.953+0000|INFO|Payara 5.183||_ThreadID=1;_ThreadName=main;_TimeMillis=1542626093953;_LevelValue=800;|
  Running command: deploy --force --enabled=true  /opt/payara5/deployments/*|#]

[#|2018-11-19T11:14:54.203+0000|INFO|Payara 5.183|org.hibernate.validator.internal.util.Version|_ThreadID=1;_ThreadName=main;_TimeMillis=1542626094203;_LevelValue=800;|
  HV000001: Hibernate Validator 6.0.12.Final|#]

[#|2018-11-19T11:14:54.307+0000|INFO|Payara 5.183|javax.enterprise.system.jmx|_ThreadID=101;_ThreadName=Thread-15;_TimeMillis=1542626094307;_LevelValue=800;_MessageID=NCLS-JMX-00024;|
  Creating a SecureRMIServerSocketFactory @ 0.0.0.0 with ssl config = GlassFishConfigBean.org.glassfish.grizzly.config.dom.Ssl|#]

[#|2018-11-19T11:14:54.348+0000|WARNING|Payara 5.183|javax.enterprise.system.jmx|_ThreadID=101;_ThreadName=Thread-15;_TimeMillis=1542626094348;_LevelValue=900;_MessageID=NCLS-JMX-00020;|
  All SSL cipher suites disabled for network-listener(s).  Using SSL implementation specific defaults|#]

[#|2018-11-19T11:14:54.348+0000|INFO|Payara 5.183||_ThreadID=101;_ThreadName=Thread-15;_TimeMillis=1542626094348;_LevelValue=800;|
  SSLParams =org.glassfish.admin.mbeanserver.ssl.SSLParams@5ac394de|#]

[#|2018-11-19T11:14:54.496+0000|WARNING|Payara 5.183|javax.enterprise.system.jmx|_ThreadID=101;_ThreadName=Thread-15;_TimeMillis=1542626094496;_LevelValue=900;_MessageID=NCLS-JMX-00020;|
  All SSL cipher suites disabled for network-listener(s).  Using SSL implementation specific defaults|#]

[#|2018-11-19T11:14:54.496+0000|INFO|Payara 5.183||_ThreadID=101;_ThreadName=Thread-15;_TimeMillis=1542626094496;_LevelValue=800;|
  SSLParams =org.glassfish.admin.mbeanserver.ssl.SSLParams@5ac394de|#]

[#|2018-11-19T11:14:54.641+0000|INFO|Payara 5.183|javax.enterprise.system.jmx|_ThreadID=101;_ThreadName=Thread-15;_TimeMillis=1542626094641;_LevelValue=800;_MessageID=NCLS-JMX-00025;|
  SSLServerSocket /0.0.0.0:8686 and [SSL: ServerSocket[addr=/0.0.0.0,localport=8686]] created|#]

[#|2018-11-19T11:14:54.984+0000|WARNING|Payara 5.183|javax.enterprise.system.jmx|_ThreadID=101;_ThreadName=Thread-15;_TimeMillis=1542626094984;_LevelValue=900;_MessageID=NCLS-JMX-00007;|
  Cannot start JMX connector JmxConnector config: { name = system, Protocol = rmi_jrmp, Address = 0.0.0.0, Port = 8686, AcceptAll = false, AuthRealmName = admin-realm, SecurityEnabled = true} due to exception java.io.IOException: Cannot bind to URL [rmi://0.0.0.0:8686/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake]|#]

[#|2018-11-19T11:14:54.992+0000|**SEVERE**|Payara 5.183||_ThreadID=113;_ThreadName=RMI TCP Connection(idle);_TimeMillis=1542626094992;_LevelValue=1000;|
  Exception in thread "RMI TCP Connection(idle)" |#]

[#|2018-11-19T11:14:54.995+0000|**SEVERE**|Payara 5.183||_ThreadID=113;_ThreadName=RMI TCP Connection(idle);_TimeMillis=1542626094995;_LevelValue=1000;|
  java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V
	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:862)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:245)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1077)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1012)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:938)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:727)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
|#]

[#|2018-11-19T11:14:55.011+0000|INFO|Payara 5.183||_ThreadID=1;_ThreadName=main;_TimeMillis=1542626095011;_LevelValue=800;|
  PlainTextActionReporterFAILUREFile not found : /opt/payara5/deployments/*|#]

[#|2018-11-19T11:15:07.555+0000|WARNING|Payara 5.183|org.glassfish.grizzly.filterchain.DefaultFilterChain|_ThreadID=43;_ThreadName=admin-thread-pool::admin-listener(1);_TimeMillis=1542626107555;_LevelValue=900;|
  GRIZZLY0013: Exception during FilterChain execution
java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V
	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:862)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:245)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1077)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1017)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1014)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1497)
	at org.glassfish.grizzly.ssl.SSLUtils.executeDelegatedTask(SSLUtils.java:250)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:683)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:598)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:310)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
|#]

**Comment by skonx** [comment] 2018-11-19 11:32
payara/server-full:5-SNAPSHOT produces another error 😲 

[#|2018-11-19T11:30:37.802+0000|WARNING|Payara 5.183-SNAPSHOT|org.glassfish.grizzly.filterchain.DefaultFilterChain|_ThreadID=77;_ThreadName=admin-thread-pool::admin-listener(2);_TimeMillis=1542627037802;_LevelValue=900;|
  GRIZZLY0013: Exception during FilterChain execution
java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V
	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:862)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:245)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1077)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1017)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1014)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1497)
	at org.glassfish.grizzly.ssl.SSLUtils.executeDelegatedTask(SSLUtils.java:250)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:683)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:598)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:310)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
|#]

**Comment by Cousjava** [comment] 2018-11-19 11:43
Closed as a duplicate of payara/docker-payaraserver-full#56

**Closed by Cousjava** 2018-11-19 11:43 UTC
