### ISSUE TITLE
Inconsistent Module State after multiple redeployments of ear types

### ISSUE THREAD

**Issue by davewinters** [payara/Payara#198] opened 2015-02-06 16:52 UTC
After multiple undeployments and deployments of a .ear application using EJB's, deployment can fail intermittently with this exception:

This issue was supposed to be addressed on Glassfish 4.1 but it is reproducible in Glassfish 4.1 GA and the latest Payara

Here is the stack trace:
2015-02-05 17:15:48.912 - :: ERROR [RunLevelControllerThread-1423174519295] javax.enterprise.system.core:503 - Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: Error in linking security policy for Profit-ear-8.13.0.10 -- Inconsistent Module State
        at com.sun.enterprise.security.ee.SecurityUtil.linkPolicyFile(SecurityUtil.java:336) ~[security-ee.jar:na]
        at com.sun.enterprise.security.ee.SecurityDeployer.linkPolicies(SecurityDeployer.java:318) ~[security-ee.jar:na]
        at com.sun.enterprise.security.ee.SecurityDeployer.access$100(SecurityDeployer.java:87) ~[security-ee.jar:na]
        at com.sun.enterprise.security.ee.SecurityDeployer$AppDeployEventListener.event(SecurityDeployer.java:145) ~[security-ee.jar:na]
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131) ~[kernel.jar:na]
        at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:328) ~[internal-api.jar:na]
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496) ~[kernel.jar:na]
        at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406) [kernel.jar:na]
        at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243) [kernel.jar:na]
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:329) [hk2-locator.jar:na]
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:377) [hk2-locator.jar:na]
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:461) [hk2-locator.jar:na]
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:227) [hk2-runlevel.jar:na]
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:84) [hk2-runlevel.jar:na]
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2258) [hk2-locator.jar:na]
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:105) [hk2-locator.jar:na]
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:87) [hk2-locator.jar:na]
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1162) [hk2-runlevel.jar:na]
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1147) [hk2-runlevel.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

And here is the bug report.
https://java.net/jira/browse/GLASSFISH-11348

**Comment by dmatej** [comment] 2015-02-06 17:05
Glassfish4.1 cannot even redeploy any our application - that problem is fixed in Payara and was caused by using symlinks in filesystem, which GF could not recognize correctly.

But even then this sometimes occurs. Yeah, I have seen it too - it comes when some of redeployments was interrupted or in some phase crashed. GF/Payara then unloads it and sometimes deletes all files and sometimes not. Then it cannot redeploy, deploy not even undeploy the application. Files must be deleted manually.

**Comment by davewinters** [comment] 2015-02-17 17:44
Interesting thread on this issue regarding the solution proposed to fix this issue on GF 4.1 https://java.net/projects/glassfish/lists/dev/archive/2014-01/message/11

**Comment by davewinters** [comment] 2015-02-18 11:46
Provider is a file based JACC provider which comes out of the box in glassfish configured in domain.xml. Added extra debug logging into the relevant security and deployment classes to capture state when I reproduce the issue.

https://docs.oracle.com/javaee/6/api/javax/security/jacc/PolicyConfiguration.html.

**Comment by smillidge** [comment] 2015-10-04 18:13
Suspect this will be fixed by #467 as no crud remains in the generated/policy directory anymore

**Closed** 2015-11-19 18:14 UTC
Labels: Test Case Required, upstream bug

**Comment by wainaina** [comment] 2015-12-18 08:55
I had a similar problem, At first it couldn't undeploy, so i used the command line to remove the application. Then restarted it, then I couldn't deploy it. I stopped the server, restarted it and it was okay. 

GF definitely has some problems I hope the fixes are coming soon.

I was using GlassFish 4.1 at the time this error was occurring.
