### ISSUE TITLE
Payara should clean up temp files

### ISSUE THREAD

**Issue by Pandrex247** [payara/Payara#443] opened 2015-09-15 10:08 UTC

**Comment by dgomesbr** [comment] 2016-03-20 00:57
I'd like to contribute to it, any hints on which files needed to be modified or handle the cleanUp step?

**Comment by mikecroft** [comment] 2016-09-12 10:12
This was investigated a while ago. The cause is stopping a server with a `kill -9` instead of gracefully. The temporary files are created in the location set in `-Djava.io.tmpdir` and some examples are:

fileinstall-502716310109529317
gendContent9090768065971402812.zip
tmpdir-gf-gf4pilot-multi-26990

To make sure these are cleaned up, we would need to eagerly destroy them. Even then, there is no guarantee that these will always be cleaned up, so this is a low-priority enhancement for us.

@dgomesbr - this probably isn't the nicest issue to contribute to, but if you'd still like to take a look then we would certainly be grateful of the contribution!

**Comment by mikecroft** [comment] 2016-12-05 10:30
`PAYARA-455`

**Comment by smillidge** [comment] 2018-12-07 20:45
Fixed by #3479

**Closed by smillidge** 2018-12-07 20:45 UTC
Labels: 2:WithDev, Help Wanted, c:Enhancement
