### ISSUE TITLE
Overriding inherited fields of @MappedSuperclass

### ISSUE THREAD

**Issue by Hellmy** [payara/Payara#2904] opened 2018-06-27 13:48 UTC
# Description #
----------
Derived entities `ConcreteOverwritten`, `ConcreteDefault` which extend an abstract base class `Base` annotated with `@MappedSuperclass` get normally all fields of the base class filled with the values. If a subclass `ConcreteOverwritten` overwrites a property of the base class, the other derived class `ConcreteDefault` doesn't get the field filled up any more.

Something similar found https://github.com/payara/Payara/issues/1589 but it wasn't solved.

## Expected Outcome

Load all fields in the derived class `ConcreteDefault` correctly.

ConcreteDefault JSON-Output:
```
[{id: 1}, {id: 2}]
```

ConcreteOverwritten JSON-Output:
````
[{id: 1}, {id: 2}]
````

## Current Outcome

The overwritten field is not filled on any derived class `ConcreteDefault` and `ConcreteOverwritten`

ConcreteDefault JSON-Output:
```
[{id: 0}, {id: 0}]
```

ConcreteOverwritten JSON-Output:
````
[{id: 0}, {id: 0}]
````

## Steps to reproduce (Only for bug reports) 
1. Configure a domain with a Postges data-source.
2. Add Tables for `ConcreteDefault` and `ConcreteOverwritten` with some dummy-values
3. Adapt an Payara-Example to use domain and the data-source
persistence.xml
```
<?xml version="1.0" encoding="UTF-8"?>
    <persistence-unit name="app"
                      transaction-type="JTA">
        <jta-data-source>jdbc/postgres.app</jta-data-source>
        <shared-cache-mode>NONE</shared-cache-mode>
        <properties>
            <property name="openjpa.Log"
                      value="File=/tmp/org.apache.openjpa.log, DefaultLevel=DEBUG, Runtime=DEBUG, Tool=DEBUG"/>
            <property name="eclipselink.ddl-generation" value="none"/>
            <property name="eclipselink.target-database" value="PostgreSQL"/>
            <property name="eclipselink.logging.level" value="FINE"/>
            <property name="eclipselink.logging.level.sql" value="FINE"/>
            <property name="eclipselink.logging.parameters" value="true"/>
        </properties>
    </persistence-unit>
</persistence>
```
4. Have two Rest Services accessing the entities looking like
```
@MappedSuperclass
public abstract class Base{

  @Id
  @GeneratedValue(generator = "seq")
  @SequenceGenerator(name = "seq", sequenceName = "SEQ", allocationSize = 1)
  private long id;

  public Base() {
  }

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }
}

@Entity
@Table(name = "ConcreteDefault")
@NamedQueries({
    @NamedQuery(name = "ConcreteDefault .findOne", query = "select p from ConcreteDefault p where p.id = :id"),
    @NamedQuery(name = "ConcreteDefault .getAll", query = "select p from ConcreteDefault p")
}
)
public class ConcreteDefault extends Base{
}

@Entity
@Table(name = "ConcreteOverwritten ")
@NamedQueries({
    @NamedQuery(name = "ConcreteOverwritten .findOne", query = "select p from ConcreteOverwritten p where p.id = :id"),
    @NamedQuery(name = "ConcreteOverwritten .getAll", query = "select p from ConcreteOverwritten p")
}
)
public class ConcreteOverwritten extends Base {
  @Id
  @GeneratedValue(generator = "seq")
  @SequenceGenerator(name = "seq", sequenceName = "SEQ", allocationSize = 1)
  private long id;
}
```

## Context (Optional)

The overwriting in `ConcreteOverwritten` was done in missconception and the error was difficult to find as we just added another entity which had overwritten such base class field. All old entities got the id null and we haven't found this error during development of the new entities as we had already planned to suppress the id - also our testing framework hasn't found this issue...

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**:  Full
- **JDK Version**: 8 
- **Database**: PostGres

**Comment by smillidge** [comment] 2018-07-02 19:11
Please create a simple test case project on GitHub that we can build and test. It makes it easier for us to look at the issue

**Comment by Hellmy** [comment] 2018-07-03 07:42
Some setup still needed as I have a postgres running connected through the payara data source:
https://github.com/Hellmy/id-example

What could be improved to get it faster running on your side?

**Comment by krichter722** [comment] 2018-08-06 16:53
@Hellmy I like to create my SSCCE for Payara and others using GitLab CI because it runs on Docker images wich provides large flexibility. Check out some examples on my project page: https://gitlab.com/?utf8=%E2%9C%93&name=payara-&sort=latest_activity_desc. You can find the commands of the reproducers in `.gitlab-ci.yml` of each project and the results in the Pipelines section, e.g. https://gitlab.com/krichter/netbeans-java-ee-double-deployment/blob/master/.gitlab-ci.yml for a PostgreSQL-based example.

**Comment by Hellmy** [comment] 2018-08-07 11:59
@krichter722 don't understand if this is requested for the investigation for the ticket but thank you for the hint. I will hav e look next time.

**Comment by OndroMih** [comment] 2020-02-04 14:18
Hi, since the provided reproducer scenario is not easy to follow, we weren't able to reproduce this issue. I'm going to close it. 
We'll reopen this issue if you provide us an easy to follow reproducer for the latest version of Payara Server or Payara Micro. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.

**Closed by OndroMih** 2020-02-04 14:18 UTC
Labels: requestor unresponsive (1), requestor unresponsive (2), try to reproduce
