### ISSUE TITLE
"java.lang.IllegalStateException: Use getGMSAdapterByName method when there are multiple clusters" when an EJB is deployed and GMS is enabled

### ISSUE THREAD

**Issue by angtes** [payara/Payara#1586] opened 2017-05-10 08:26 UTC
# Description #
I have a domain with several clusters and GMS enabled.
Whenever I try to deploy an EJB I get the following error:
java.lang.IllegalStateException: Use getGMSAdapterByName method when there are multiple clusters

If GMS is disabled all runs OK.

Is this a bug? Can I use EJB and GMS simultaneously? Do I need to configure something? 

## Environment ##
- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 8 u121 - Oracle
- **Operating System**: Linux (CentOS 6.8)

**Comment by MattGill98** [comment] 2017-05-11 16:12
Hi Angtes,
Unfortunately I'm having a bit of trouble reproducing your bug. I tried by setting up a clean Payara 171.1 and deploying the [SimpleRemoteEJB Payara Example](https://github.com/payara/Payara-Examples/tree/master/Java-EE/SimpleRemoteEJB). GMS was enabled for both clusters, and each cluster had two instances running in it. Is there maybe anything else specific about your configuration that might be causing this?

**Comment by angtes** [comment] 2017-05-15 09:02
Thanks MattGill98 for your answer.
I've deployed the SimpleRemoteEjb on my system without any problem.
The differences I've seen regarding my ejb are that mine is stateful and is EJBv2 instead EJBv3
I'm going to do some tests and I'll comment the conclusions.
Thank you very much

**Comment by angtes** [comment] 2017-05-15 14:59
I've tried to deploy a simple Stateful EJBv3 and I've got the same error:
java.lang.IllegalStateException: Use getGMSAdapterByName method when there are multiple clusters

I've compiled the sources from [https://www.go4expert.com/articles/ejb-30-stateful-session-bean-example-t4212/](url).
When I deploy the jar I got the error.

I've attached the jar file with the example.

[ejb_stateful.zip](https://github.com/payara/Payara/files/1001449/ejb_stateful.zip)

**Comment by MattGill98** [comment] 2017-05-15 16:40
Hi @angtes,
Thank you for attaching the jar file. I've managed to reproduce the bug consistently now. I found the bug only happens when you try to deploy to the DAS as well as the clusters. If you just deploy the application to the clusters then you should find it deploys successfully. Is there any reason that you would need to deploy to the DAS?

Let me know if it works for you.
Kind regards,
Matt

**Comment by angtes** [comment] 2017-05-15 17:01
I've tried it and it works ok.

In our production environment, we have an automated script to deploy wars and jars. It deploy first to the DAS and then does create-application-ref to the required clusters. We can change this script to deploy directly to the clusters.

In our development enviroment, we have a DAS and several clusters. We use mainly the DAS to try the applications with dynamic reloading, so we need to deploy the EJB to the DAS. In this case we can disable GMS because we will not use it.

Although we can solve our problem it would be fine to deploy the EJB to the DAS.

Thank you for your help

**Comment by MattGill98** [comment] 2017-05-16 09:40
No worries, I'm glad it's working now! I agree that this seems to be a problem. I've raised this as internal issue PAYARA-1679.

Let me know if you get any more issues

**Comment by MattGill98** [comment] 2017-08-25 13:27
Hi @angtes,

This problem has been fixed now in 173, so I'll close the issue.

Let me know if you get any more problems.

Matt

**Closed** 2017-08-25 13:28 UTC
