### ISSUE TITLE
Bug Report: "Network Listener named http-listener-1 to which this ssl element is being added already has an ssl element."

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5598] opened 2022-02-02 14:21 UTC
# Description #
----------

The error message "Network Listener named http-listener-1 to which this ssl element is being added already has an ssl element." occurs as soon as pressing "OK" after typing "s1as" in the certificate nickname field.

CSS apparently is missing, the page is shown as pure HTML (black on white).

## Expected Outcome ##

The alias "s1as" is stored.

CSS still is getting applied (Payara CI colors)

## Current Outcome ##

"Network Listener named http-listener-1 to which this ssl element is being added already has an ssl element." is shown.

CSS is ignored (black on white)

## Steps to reproduce ## 

Install Payara Community Edition 5.2021.8.
Navigate to localhost:4848.
Navigate to server-config - network config - http-listener-1 - ssl
Type "s1as" in the "Certificate NickName" field.
Klick "OK".

## Environment ##

- **Distribution**: Server Full Profile
- **JDK Version**: 11.0.13 - Azul Zulu
- **Operating System**: Windows 10

**Comment by AlanRoth** [comment] 2022-05-09 12:58
Hi @mkarg,

Can you try in the latest version 5.2022.2? 

I have been able to reproduce it in 5.2021.8, however it seems to be functioning in 5.2022.2, although the CSS does break momentarily however it does not seem to impact the function of Payara Server.

Let me know your findings,
Thank you,
Alan

**Comment by mkarg** [comment] 2022-05-17 08:01
I will try to reproduce in June. Living with the workaround until then.

**Comment by eveoc** [comment] 2023-03-30 07:29
Hello!
Are there any updates to this report? I have the same problem with version 5.2020.5 #badassfish (build 942).
Thanks!

**Comment by AlanRoth** [comment] 2023-06-06 15:30
Hi,

Due to the lack of updates, we will be closing this issue.

Thank you,
Alan

**Closed by AlanRoth** 2023-06-06 15:30 UTC
Labels: Type: Bug, Status: Pending
