### ISSUE TITLE
Payara Micro support for persistent EJB timers in MySQL / Hazelcast EJB Timer Timeouts

### ISSUE THREAD

**Issue by krystianity** [payara/Payara#4794] opened 2020-07-16 17:28 UTC
# Description #
----------

Currently Payara Full Server supports either JDBC or Hazelcast backed persistent EJB timers, however Payara Micro does not allow for this selection.

But on the contrary with Payara Full Server one cannot set a fixed instance name using containers (random UID taken from FS), which Payara Micro on the other hand does support.

Therefore when trying to run Payara in a clustered Kubernetes environment the only way to go is to pick micro, set a fixed instance name and choose Hazelcast as data grid to back EJB timers.

## Expected Outcome

Running persistent EJB timers backed by JDBC instead of Hazelcast.

## Context (Optional)

We have migrated our application (600 Beans+) from VMs to Kubernetes lately.
And had to move to Hazelcast backed timers (as Payara Full Server is not an option for k8s, as state above). We are using EJB timers extensively for our business logic and have several thousands of timers running at the same time, which has not been an issue until migrating to Hazelcast. Since our migration we notice delays e.g. timers getting fired up to 10 minutes late, causing timeouts in the application and UI. It also feels extremely difficult to debug issues related to Hazelcast.
We have been trying out endless configuration scenarios to see if they are any kind of help - with the extend that we are thinking about migrating back to Payara Full Server on VMs.

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Micro
- **JDK Version**: 11
- **Operating System**: Linux (Kubernetes)
- **Database**: MySQL

**Comment by OndroMih** [comment] 2020-08-10 13:19
Hi, we currently have no plans to support JDBC-based timers in Payara Micro. However, it should be possible to add this from Payara Server and rely on an external DB. 

However, Payara Server also supports giving fixed names to instances, besides also giving them an automatically-generated name. Can you explain how you tried to use Payara Server in Kubernetes and why you failed? Although the official Docker image only starts a DAS, you should be able to create and run a Payara instance that runs in a Docker container and connects to DAS and give the instance either a fixed name, or a name passed to the docker container via an environment variable or a completely generated name using the `--autoname` option (https://docs.payara.fish/community/docs/5.2020.3/documentation/payara-server/asadmin-commands/auto-naming.html).

**Comment by krystianity** [comment] 2020-08-10 14:19
Hi @OndroMih thank you for your reply.

We are aware of the `--instancename` argument, however that does not really help the Full Server in a Kubernetes environment. The main issue occurs when deploying or scaling instances in the Kubernetes cluster. Spinning up a new Docker container instance will cause the internal values for APPLICATIONID and CONTAINERID (Timer Table) to be different (this stuff is taken care of by `--keepstate=true` when deploying by hand on VMs). With different ids the container will not recover the timers of the last instance, even if the names are identical.

Since any crash or re-deployment on Kubernetes would cause us to loose hundreds of persisted timers, we are currently not able to use Kubernetes. As stated above running Micro with Hazelcast in Kubernetes is also not an option for us, as the timer performance is decreased and we have random freezes across the whole application.

**Comment by MeroRai** [comment] 2020-11-12 17:28
Hi @krystianity, 

Due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by MeroRai** 2020-11-12 17:28 UTC
Labels: Status: Pending, Type: Bug
