### ISSUE TITLE
Slow deploy from NetBeans to Payara

### ISSUE THREAD

**Issue by omniprof** [payara/Payara#4477] opened 2020-02-08 19:09 UTC
# Description #
----------

Initially I thought that JSF apps deploy unreasonably slowly from NetBeans to Payara. Subsequently I determined that any app that included a glassfish-resources.xml file deployed slowly even if it did not have any JPA code. Once deployed everything worked as expected.

## Expected Outcome

Once I discovered that there was an alternate name for glassfish-resources.xml that is payara-resources.xml the issue was gone. Deployment using the Run command in NetBeans went from 50 seconds to almost instantaneous. Please either correct this or make the need to name the file payara-resources.xml more prominent like as a big banner on your home page. More reasonably consider having a log message recommending changing the name when either the server starts up or when deploying an app.

## Environment ##

- **Payara Version**:5.194
- **Edition**: Full
- **JDK Version**: AdoptOpenJDK 11
- **Operating System**: Windows 10
- **Database**: MySQL 8

**Comment by smillidge** [comment] 2020-02-08 21:32
OK thanks would be interesting to understand why it is running slow.

**Comment by OndroMih** [comment] 2020-02-10 11:26
The problem is that the file glassfish-resources.xml references the schema at http://glassfish.org/dtds/glassfish-resources_1_5.dtd, which is inaccessible and takes ages to load even in a browser. 

It has nothing to do with Netbeans. Even nothing to do with renaming the file to payara-resources.xml. To get around this it was enough to replace the DTD reference in glassfish-resources.xml with a references to the payara DTD in `glassfish-resources.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources PUBLIC "-//Payara.fish//DTD Payara Server 5 Resource Definitions//EN" "https://raw.githubusercontent.com/payara/Payara-Server-Documentation/master/schemas/payara-resources_1_6.dtd">
<resources>
</resources>
```

I'm not sure we can do anything about this, possibly at least add a timeout when accessing a remote DTD, but I guess this part is hidden very deeply in the XML parser.

**Comment by OndroMih** [comment] 2020-02-10 12:29
Here's a simple reproducer: [gh4477reproducer.zip](https://github.com/payara/Payara/files/4180756/gh4477reproducer.zip).

**Comment by omniprof** [comment] 2020-02-10 13:31
Thank you for the info. What is strange is that if I manually deployed, dropped the war into autodeploy, or used Cargo there was no issue. It also doesn’t explain why renaming the file works. I will try the new doctype later this morning.

What you are telling me is that every time a project is deployed the server must make a request for a URL. As you point out, that URL does not exist. What is Payara doing in that case? Does it through up it’s hands after 50 seconds and decides to process the resources anyway?

Why do we need the reference to the dtd at all especially if when it can’t be retrieved Payara still configures the resource? The file is processed on the server so it should know which dtd to use based on the file name and should already be part of the server. I was under the impression that these urls did not reference a real web address but were pointers into a table already on the server or, in the case  regular html already in the browser.

My guess is that in a war Payara doesn’t care what the dtd is or fails fast. NetBeans does not deploy a war but points Payara at a folder. This is when Payara gets hung up on the dtd.

There is still more to this. I’ll try your dtd when I get into school this morning.

Thanks,

Ken



________________________________

**Comment by omniprof** [comment] 2020-02-10 19:38
I have just used your doctype in glassfish-resources.xml and it did load quickly.

I also left the old glassfish 1.5 dtd doctype and just renamed the file to payara-resources.xml and it loaded just as fast.

So I leave it to you and your team to figure why changing the name but still using an invalid DTD url works.

 

Ken

**Comment by omniprof** [comment] 2020-02-11 15:31
Sorry to keep this up but I believe there is an error in one of your statements. The site glassfish.org does not exist. From what I have learned the url http://glassfish.org/dtds/glassfish-resources_1_5.dtd is meant to point at <YOUR_GLASSFISH_FOLDER>/glassfish/lib/dtds/  (https://stackoverflow.com/questions/44239395/glassfish-doctype-description-files-missing). When I look into this folder in Payara all the dtds are there.

 

I agree that something in NetBeans might be looking for this site as the time it takes my browser to tell me it has timed out trying to contact the site is about the same length of time that NetBeans delays until it deploys. I will now pursue this further with NetBeans. 

 

The point I want to make is that all these URLs in doctypes or in xmlns attributes do not exist. They are just pointers to a file stored on the server or contained within a framework. Solving the problem by providing a real URL that exists is not the right solution.

 

Thanks again for all your help.

 

Ken

**Comment by OndroMih** [comment] 2020-03-03 10:14
Reading back the comment history, I'm confused if this has been properly clarified or not. Based on the conversation in the forum (https://groups.google.com/forum/#!searchin/payara-forum/netbeans%7Csort:date/payara-forum/QL-4xi4PuDw/yOXDSADuEQAJ) I assume that it's accepted that this is an issue in Netbeans. 

Although Payara team maintains the Netbeans plugin for Payara, it's now core Netbeans functionality and this issue should be raised with the Netbeans project. There's nothing we can do in Payara Server to fix this issue so I'm closing this.

**Closed by OndroMih** 2020-03-03 10:14 UTC
