### ISSUE TITLE
Payara 5.184: Intermittent app deployment failures

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#3493] opened 2018-12-06 05:12 UTC
# Description #
----------

After updating to v5.184, a web application which has been working fine on previous versions of payara5 now often fails when attempting to deploy, but not always.  Also, after a successful deployment, sometimes restarting the domain results in failure to start the application.

## Expected Outcome

Application should always deploy successful, and app server should always startup the app which has been successfully deployed.

## Current Outcome

Sometimes the war deploys fine, and the application works fine just as it does on v5.183 and earlier.  Many times, though, the deployment fails.  Also, many times the application is deployed, but restarting the domain results in the application not starting.

## Steps to reproduce (Only for bug reports) 

It's difficult to reproduce on demand, but at this point it's happening about 60% of the time.  If I just continuously attempt to deploy, it eventually will deploy.  Unfortunately, sometimes when the domain is restarted, the errors occur and the app is not started.  Deploying the application with `asadmin deploy --force=true --upload=true --contextroot=/ <path to warfile>`

When the deployment fails, the following shows up in server.log:
```
[2018-12-06T04:52:54.998+0000] [Payara 5.184] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=141 _ThreadName=payara-executor-service-task] [timeMillis: 1544071974998] [levelValue: 1000] [[
  Exception while parsing file file:/home/payara5/payara-5.184/payara5/glassfish/domains/domain1/applications/ica-web1/
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@69acecd rejected from java.util.concurrent.ThreadPoolExecutor@798ac9f5[Running, pool size = 20, active threads = 20, queued tasks = 30, completed tasks = 9]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.glassfish.hk2.classmodel.reflect.Parser.parse(Parser.java:293)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleJar(ReadableArchiveScannerAdapter.java:197)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:131)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:345)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:68)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:304)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]
```

and then further down, various CDI exceptions are listed such as
```
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type X with qualifiers Y at injection point Z
```
but the types/injection points shown are not always the same.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 8u192 - Azul Zulu OpenJDK
- **Operating System**: Centos7 Linux
- **Database**: postgres

**Comment by chrjohn** [comment] 2018-12-06 09:34
Seems to be the same issue as reported in #3360 . 
https://github.com/payara/Payara/issues/3360#issuecomment-444692778

**Comment by smillidge** [comment] 2018-12-06 09:47
Closing as duplicate of #3495

**Closed by smillidge** 2018-12-06 09:47 UTC

**Comment by phillipross** [comment] 2018-12-06 16:15
This was indeed the issue and increasing the queue size for the payara executor service (per https://github.com/payara/Payara/issues/3495#issuecomment-444812043) does fix the problem
thanks!
