### ISSUE TITLE
Payara console keeps redirecting to index.jsf

### ISSUE THREAD

**Issue by SirTates** [payara/Payara#3998] opened 2019-06-03 11:50 UTC
# Description #
----------
Payara console shows a white screen that keeps redirecting to the same screen.
Logging into the web console is impossible.

## Expected Outcome

The console should only redirect once and allow me to log in.

## Current Outcome

Logging into the web console is impossible.
The Payara log only repeatedly notes: Info:  redirecting to /index.jsf

## Steps to reproduce (Only for bug reports) 
- download latest Payara5
- run Payara with asadmin start
- open http://localhost:4848/ in any browser

### Screenshots of log
Setup for the console:
![Payara Log1](https://i.imgur.com/Wxr49Wd.png)
Everything after: 
![Payara Log2](https://i.imgur.com/NqdMyr4.png)
## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 8/OpenJDK 1.8
- **Operating System**: Linux/Ubuntu 19.04
- **Database**: MySQL

**Comment by khasunuma** [comment] 2019-06-03 23:32
I can't reproduce this issue on Windows 10. (5.184, 5.191 and 5.192)

We'd try to reproduce another environments.

**Comment by Cousjava** [comment] 2019-06-04 08:17
This occurs due to browser caching. To fix this clear the cache for the domain Payara is on.

In Firefox this can be done by Shift+F9 when on the page to open the storage viewer and then right click to delete.

**Comment by OndroMih** [comment] 2019-06-04 09:21
Also pressing Ctrl+R or the reload button should clear the cache in most browsers.

**Comment by OndroMih** [comment] 2019-06-04 09:24
We've raised an internal issue PAYARA-3879 to disable caching in the Admin console, which will hopefully fix this issue in the future.

**Comment by OndroMih** [comment] 2019-06-04 09:24
Since there's a workaround and it mostly happens only in development, I'm closing this github issue.

**Closed by OndroMih** 2019-06-04 09:24 UTC
Labels: Help Wanted, try to reproduce
