### ISSUE TITLE
Payara Eclipse Plugin hangs on server start

### ISSUE THREAD

**Issue by juerg-b69** [payara/Payara#4539] opened 2020-02-28 08:52 UTC
On starting the server from the IDE I get: Unable to start server on time. Timeout while waiting for Payara to start

    1. Payara starts, but the status within the IDE remains stopped.
    2. Doubling the timeout just takes the double time until the error message pops up.
    The log hangs at 52% without more messages. Of course there ist the "severe" error of certificate validity overrun, but I don't see this as the origin of the problem.
    On trying to deploy the application I get:
    The Eclipse plugin cannot communicate with the Payara server....
    The Eclipse plugin cannot communicate with the Payara server. A Payara Server may be running on the same admin or HTTP port, but with a different root installation.Please also check for antivirus software, firewall configuration, or VPN setup which might block some ports.

None of this hints applies.

## Expected Outcome

Message: Server started! Note this works with jdk8 normally, but not with jdk 11.

## Current Outcome

as mentioned above. Note, the server ist started anyway and admin console in the browser works as expected

## Steps to reproduce (Only for bug reports) 
After installation of payara eclipse plugin and complete configuration as usual. Just start the server from within the ide without any project to deploy. 

Note the latter doesen't work neither with jdk 8, but this is due to differing naming between maven and eclipse within the application.xml on ear generation! (The maven build of the application can be deployed from within the adminstration console within the browser and the application works as expected.

## Environment ##
    Eclipse IDE 2019-12
    Payara Tools Version:1.0.1.201912202010
- **Payara Version**:  5 (5.194)
- **Edition**: Full
- **JDK Version**: jdk-11.0.6_windows-x64 - Oracle
- **Operating System**: Windows 10 prof
- **Database**: N/A

**Comment by jGauravGupta** [comment] 2020-02-28 09:03
Hi @juerg-b69,

Can you please create the Eclipse tools related issue here: https://github.com/payara/ecosystem-eclipse-plugin

Also, may you confirm, if this issue is duplicate of https://github.com/payara/ecosystem-eclipse-plugin/issues/22

**Closed** 2020-02-28 09:03 UTC

**Comment by juerg-b69** [comment] 2020-02-28 09:15
Can you please create the Eclipse tools related issue here:
https://github.com/payara/ecosystem-eclipse-plugin Yes I'll do it.

lso, may you confirm, if this issue is duplicate of
payara/ecosystem-eclipse-plugin#22
<https://github.com/payara/ecosystem-eclipse-plugin/issues/22>: Not
exactly, as the issue is related to jdk 11 (I guess 9 and above) and the
plugin works normally when JAVA_HOME and PATH ponits to JDK8 (actual
jdk1.8.0_241)

Am Fr., 28. Feb. 2020 um 10:03 Uhr schrieb Gaurav Gupta <
notifications@github.com>:

**Comment by juerg-b69** [comment] 2020-02-28 09:32
Issue created as you suggested!

Am Fr., 28. Feb. 2020 um 10:15 Uhr schrieb Hans Dampf <nsnospam3@gmail.com>:
