### ISSUE TITLE
from 172 deploy ear fail when ear with web and ws war and ws declare WebServiceContext

### ISSUE THREAD

**Issue by omarbr** [payara/Payara#2081] opened 2017-10-19 07:33 UTC
# Description #
----------
Deploy ear fail when ear contain two war and one is webservice and use WebServiceContext.
Added test project to reproduce this error. 
Ws war, class WebServices declare WebServiceContext.
If comment this, deploy was fine, otherwise fail.
if remove one war (indifferent), ear succesfuly deploy.
log.txt contain log when deploy fail.

Version before 172 not affected of this problem

## Steps to reproduce
create project with two war (web and webservice).
on ws war create simple ws and add `	@Resource
	private WebServiceContext wsctx;`
deploy ear

## Current Outcome
[log.txt](https://github.com/payara/Payara/files/1397456/log.txt)

### Samples
[testProject.zip](https://github.com/payara/Payara/files/1397454/testProject.zip)

## Environment ##

- **Payara Version**: 4.1.2.172 and 4.1.2.173
- **Edition**: Full
- **JDK Version**: Oracle 8
- **Operating System**: Windows 10

**Comment by Cousjava** [comment] 2017-10-23 10:05
Reproduced the issue and raised internal issue PAYARA-2229. As a workaround if you change bean discovery mode to ANNOTATED instead of ALL it works fine.

**Comment by albanf** [comment] 2017-12-18 12:51
Any progress on this issue? I tried the workaround you suggest, but I get the same error message.
Same result with 4.1.2.174 and 4.1.2.181-SNAPSHOT (build 169)

**Comment by OndrejM** [comment] 2018-01-19 22:22
Hi @albanf,
The fix is in progress, unfortunately it won't make it into the next release 181 because we're too busy with adding Java EE 8 support. I hope you can understand.

**Closed** 2018-03-22 09:59 UTC
Labels: 4:Ready, c:ConfirmedBug, payara bug, reproducible, upstream bug
