### ISSUE TITLE
Command create-node-dcom failed

### ISSUE THREAD

**Issue by mirozitnansky** [payara/Payara#2016] opened 2017-09-20 20:31 UTC
* 4.1.2.173 #badassfish (build 24)
* DAS using payaradomain config, cluster enviroment
* Windows 2016 DC as DAS host, windows 10 enterprise as instance host

* I found this BUG was reported and never fixed on glassfish 3.1 http://markmail.org/message/bkngpqazx7neawtb#query:+page:1+mid:tauxcf7okqte6in3+state:results

* running with asadmin
```
PS C:\payara41\bin> .\asadmin -W passfile create-node-dcom --windowsuser admin1 --install false --nodehost kiosk21 --installdir c:\payara41 --windowsdomain postest kiosk21-node
remote failure: Warning: some parameters appear to be invalid.
DCOM node not created. To force creation of the node with these parameters rerun the command using the --force option.
com.sun.enterprise.util.cluster.windows.process.WindowsException: Logon failure: unknown user name or bad password.
Command create-node-dcom failed.
```

password is provided within _passfile_

Traced with Wireshark, error seems to be ignoring _--windowsdomain_ parameter
[CreateNodeFailed.zip](https://github.com/payara/Payara/files/1319162/CreateNodeFailed.zip)

```
9	0.739616	192.168.1.130	192.168.1.151	SMB	310	1	Session Setup AndX Request, User: 192.168.1.151\admin1; Tree Connect AndX, Path: \\KIOSK21\IPC$
17	0.750160	192.168.1.151	192.168.1.130	SMB	93	1	Session Setup AndX Response, Error: STATUS_LOGON_FAILURE
```
asadmin tries to log in as local user 192.168.1.151\admin1, but this is domain user a login should postest\admin1
direct login onto host using this credentials is worfing find

on the other hand validate-node-dcom is working as expected, includind _--windowsdomain_ into login request
```
PS C:\payara41\bin> .\asadmin -W passfile validate-dcom --windowsuser admin1 --windowsdomain postest kiosk21
Command validate-dcom executed successfully.
```
[ValidateNodeDcom.zip](https://github.com/payara/Payara/files/1319173/ValidateNodeDcom.zip)
`25	6.865994	192.168.1.130	192.168.1.151	SMB	291	3	Session Setup AndX Request, User: POSTEST\admin1; Tree Connect AndX, Path: \\KIOSK21\C$`

On the other hand, running create-node-dcom using node local user is working (somehow, only when _--force_ parameter is used, and with nodes registry modifications)
nto host using this credentials is worfing find

on the other hand validate-node-dcom is working as expected, includind _--windowsdomain_ into login request
```
PS C:\payara41\bin> .\asadmin -W passfile validate-dcom --windowsuser admin1 --windowsdomain postest kiosk21
Command validate-dcom executed successfully.
```
[ValidateNodeDcom.zip](https://github.com/payara/Payara/files/1319173/ValidateNodeDcom.zip)
`25	6.865994	192.168.1.130	192.168.1.151	SMB	291	3	Session Setup AndX Request, User: POSTEST\admin1; Tree Connect AndX, Path: \\KIOSK21\C$`

On the other hand, running create-node-dcom using node local user is working (somehow, only when _--force_ parameter is used, and with nodes registry modifications)
```
PS C:\payara41\bin> .\asadmin -W passfile create-node-dcom --windowsuser kiosk --install false --nodehost kiosk21 --installdir c:\payara41 --force kiosk21-node
Warning: some parameters appear to be invalid.
Couldn't connect via DCOM to remote host: kiosk21
Continuing with node creation due to use of --force.
Command create-node-dcom executed successfully.
```
Which are those "some invalid pamerters" I wasn't able to find out. Still, attaching tcp dump.
[CreateNodeSuccessedLocalUser.zip](https://github.com/payara/Payara/files/1319212/CreateNodeSuccessedLocalUser.zip)
This is definitelly not prefered method in enterprise, domain controlled enviroment. Using locally created users and registry modifications which are necessary to make it work. 
Even these registry modifications has to be done manually, because _asadmin setup-local-dcom_ is not working on windows 7 and newer correctly (tried more than once).

Also, after creation of node using node local user, and successfully installing instance from DAS on it, ping command is not working either
```
PS C:\payara41\bin> .\asadmin -W passfile ping-node-dcom kiosk21-node
remote failure: Failed to validate DCOM connection to node kiosk21-node (kiosk21)
Couldn't connect via DCOM to remote host: kiosk21
Command ping-node-dcom failed.
```
[PingNodeDcomFailed.zip](https://github.com/payara/Payara/files/1319247/PingNodeDcomFailed.zip)

Again, I am not sure what is asadmin evaluating as failed in that communication. 
I understand these are old glassfish issues, but for payara to be fully usable on windows environment, it should be fixed.

**Comment by Acidcrawl** [comment] 2018-04-25 20:13
I am having the exact same problem, although I am not using a password file.  I have setup everything according to a blog post from Payara, but it seems to be ignoring the windows domain, the same problem exists in Glassfish.

This is my log entry:
[2018-04-25T13:53:42.135-0600] [Payara 5.181] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=45 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1524686022135] [levelValue: 1000] [[
  RestResponse.getResponse() gives FAILURE.  endpoint = 'https://localhost:4848/management/domain/nodes/create-node-dcom'; attrs = '{windowspassword=*******, nodehost=usid01ws451.ad.mydomain.com, windowsuser=uspt3_cim_service, windowsdomain=mydomain, install=true, installdir=${com.sun.aas.productRoot}, force=false, id=usid01ws451}']]

I really want to switch to Payara from Glassfish, I was hoping this had been fixed.

**Comment by rdebusscher** [comment] 2019-12-06 13:01
Hi @mirozitnansky, @Acidcrawl 

Do you experience this issue in the latest Payara 5 release (5.194). Is this still an issue for you?

Regards
Rudy

**Comment by Acidcrawl** [comment] 2019-12-07 05:41
I will try it and let you know.

**Comment by fturizo** [comment] 2020-02-06 18:02
Due to the nature of this issue, and that the issue has not been reported in the latest release of Payara Server 5.x, we'll proceed to close this issue. Feel free to raise a new issue with a detailed reproducer if the problem is present in the current release of Payara Server 5.x

**Closed by fturizo** 2020-02-06 18:02 UTC
Labels: Try On Latest Release, status:reproducer-needed, try to reproduce
