### ISSUE TITLE
Bug Report: Customer implemented MapStore with JTA DataSource Persistence Unit, not write to backend Database

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#6470] opened 2023-10-28 10:07 UTC
### Brief Summary

Operating System: Rocky Linux 9.2
Oracle JDK 17.0.6
Payara 6.2023.10
Backend Database: PostgreSQL 15

I developed a simple project that tried to write simple events to Hazelcast then to backend database.

jdbc connection pool configured with XADatasource, jdbc resources Jndi name as: jdbc/PG15_ozssc_150

JTA transaction type was used in persistence.xml

customer hazelcast-config.xml used to configure map and serialisable in payara domain.

Customer MapStore implemented

EJB schedule was used to create entity and put it into Hazelcast map

Entity and EJB logic were put into separated module and deploy differently

Details please refer to: https://github.com/cidylong/JTAMapStoreEJB

### Expected Outcome

When EJB write entity to hazelcast map, system should automatically write back database as configured in hazelcast-config.xml.

### Current Outcome

EJB scheduler write entity to Hazelcast map successfully, (checked by using ViduslVM over jmx service that payara provided).

customer MapStore function store() was called (checked on console log)

Backend Database NOT record any information about the entity at all. (customer MapStore implementation don't throw any exception at all)

### Reproducer

Details please refer to: https://github.com/cidylong/JTAMapStoreEJB

I had created a gitHub project to have all source code here. And there is a README.MD to have the development and  test guide

### Operating System

Rocky Linux 9.1

### JDK Version

Oracle JDK 17.0.7

### Payara Distribution

Payara Server Full Profile

**Comment by cidylong** [comment] 2023-10-28 10:08
<img width="987" alt="Screenshot 2023-10-28 at 8 51 05 pm" src="https://github.com/payara/Payara/assets/11171226/23c93b8f-c642-4d23-aed7-cdaf33b780ce">
<img width="736" alt="Screenshot 2023-10-28 at 8 52 18 pm" src="https://github.com/payara/Payara/assets/11171226/188229ed-05d9-40f7-a88e-64063662357a">

There are some payara server configure screen shots

**Comment by cidylong** [comment] 2023-11-01 02:58
This issue maybe caused by same reason with issue #6450. 

If it is, please advise a work around to create a system (Payara Domain) available datasource that can be used as JTA datasource in persistence.xml

**Comment by cidylong** [comment] 2023-11-01 02:59
@felixif , please advise.

**Comment by felixif** [comment] 2023-11-01 09:54
Hello @cidylong,

This issue is a duplicate of [issue 6467](https://github.com/payara/Payara/issues/6467). Elif will continue the communication about the issue there. Thank you for your contribuiton.

Regards,
Felix

**Closed by felixif** 2023-11-01 09:54 UTC
Labels: Type: Bug, Status: Open
