### ISSUE TITLE
Payara Micro logToFile history /CUSTCOM-125

### ISSUE THREAD

**Issue by carlbradwell17** [payara/Payara#4014] opened 2019-06-05 14:06 UTC
# Description #
----------

I currently use Payara Micro with the logtofile option and specify a custom path. This works fine, log files are generated as desired and file rotation occurs, with a maximum of 10 files.

I am using the default domain template provided in Micro 5.192.

However, I wish to increase this limit of 10 files in the rotation, or increase the max size of the log files, so I can capture greater history of logs.

I have attempted to use the logproperties switch instead of logtofile, so I can customise the logging. I tried this using the default logging.properties from the domain, and while the logs/server.log file was created, it is always blank.

I also tried copying a logging.properties file from a Payara Full 5.192 installation, which I use on a Windows 10 PC, which logs as expected. This did not make any difference on Payara Micro.

Can you advise how I can get the logging.properties working with Payara Micro, or alternatively any way I can simply continue using logtofile and increase the limit?

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Micro
- **JDK Version**: OpenJDK 11
- **Operating System**: Ubuntu 18

**Comment by smillidge** [comment] 2019-06-07 22:03
Questions are better raised on the Payara forums https://groups.google.com/forum/#!forum/payara-forum

**Comment by OndroMih** [comment] 2019-06-12 06:56
You can try to specify the number of files with a command in a [postboot command script](https://docs.payara.fish/documentation/payara-micro/asadmin/pre-and-post-boot-scripts.html), instead of passing a modified log properties file. With this command in the script:

```
set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles='20'
```

**Comment by carlbradwell17** [comment] 2019-06-12 12:57
@OndroMih when trying your suggestion, I get the following exception:

```
 NCLS-CORE-00002
MultiException stack 1 of 3
org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=LogManagerService,parent=SetLogAttributes,qualifiers={},position=-1,optional=false,self=false,unqualified=null,2118482375)
        at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:75)
        at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:727)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:197)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:181)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:104)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:166)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:110)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:104)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1039)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:210)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:112)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:71)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
MultiException stack 2 of 3
java.lang.IllegalArgumentException: While attempting to resolve the dependencies of com.sun.enterprise.server.logging.commands.SetLogAttributes errors were found
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:248)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:727)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:197)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:181)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:104)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:166)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:110)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:104)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1039)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:210)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:112)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:71)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
MultiException stack 3 of 3
java.lang.IllegalStateException: Unable to perform operation: resolve on com.sun.enterprise.server.logging.commands.SetLogAttributes
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:387)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:727)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:197)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:181)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:104)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:166)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:110)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:104)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1039)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:210)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:112)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:71)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]
```

**Comment by rdebusscher** [comment] 2019-12-20 10:20
I have created `CUSTCOM-125`

**Comment by AlanRoth** [comment] 2020-11-11 11:40
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:40 UTC
Labels: status:accepted
