### ISSUE TITLE
Problem with compressed JAX-RS requests (Payara 4.1.1.164)

### ISSUE THREAD

**Issue by tfal** [payara/Payara#1186] opened 2016-11-18 08:50 UTC
# Description #
----------

Jersey EncodingFilter does not work in Payara 4.1.1.164 (the same requests works fine under Payara 4.1.1.163).

## Current Outcome

The following exception occures when sending compressed POST request (http header ContentEncoding: gzip) to our REST service:

ExceptionMessage: Not in GZIP format
at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
at org.glassfish.jersey.message.GZipEncoder.decode(GZipEncoder.java:73)
at org.glassfish.jersey.spi.ContentEncoder.aroundReadFrom(ContentEncoder.java:125)

## Steps to reproduce (Only for bug reports) 

web.xml fragment of REST servlet configuration with EncodingFilter and GZipEncoder:
&lt;servlet&gt;
  &lt;servlet-name&gt;ServletAdaptor&lt;/servlet-name&gt;
  &lt;servlet-class&gt;org.glassfish.jersey.servlet.ServletContainer&lt;/servlet-class&gt;
...
  &lt;init-param&gt;
    &lt;param-name>jersey.config.server.provider.classnames&lt;/param-name&gt;
    &lt;param-value&gt;org.glassfish.jersey.server.filter.EncodingFilter,org.glassfish.jersey.message.GZipEncoder&lt;/param-value&gt;
  &lt;/init-param&gt;
...
&lt;/servlet&gt;

jmeter request example:

- **HTTP Request (Method: POST)**
message content in body

  - **HTTP Header Manager (add Content-Encoding http header)**
  Content-Encoding: gzip

  - **BeanShell PreProcessor (compress request body):**
  import org.apache.commons.io.IOUtils;
  import java.util.zip.GZIPOutputStream;
  String bodyString = sampler.getArguments().getArgument(0).getValue();
  byte [] requestBody = bodyString.getBytes();
  ByteArrayOutputStream out = new ByteArrayOutputStream(requestBody.length);
  GZIPOutputStream gzip = new GZIPOutputStream(out);
  gzip.write(requestBody);
  gzip.close();
  sampler.getArguments().getArgument(0).setValue(out.toString(0));

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: 8  u112 Oracle
- **Operating System**: Windows 7

**Comment by mikecroft** [comment] 2016-11-18 08:53
Can you give some more details on the actual problem? What is the code that is failing? How can we reproduce the issue? Do you have an example you can show us?

**Comment by tfal** [comment] 2016-11-18 09:52
Simple JAX-RS project:
[compressionTest.zip](https://github.com/payara/Payara/files/599566/compressionTest.zip)

JMeter config file to reproduce error:
[compressionTestJMeter.zip](https://github.com/payara/Payara/files/599570/compressionTestJMeter.zip)

**Comment by matthiasblaesing** [comment] 2016-11-19 17:15
A lead might be, that compression content-encoding headers were disabled until grizzly 2.3.28. I asume this is what happens:

- the grizzly input CompressionEncodingFilter now decodes the incoming stream (so far, so correct)
- the Filter leaves the headers untouched and this causes the jersey filter to kick in and tries to decode the stream again

I try to get familiar with the grizzly code base, but I'm not yet sure where the correct location would be to to this. My gut feeling tells me that `org.glassfish.grizzly.http.HttpCodecFilter#setContentEncodingsOnParsing` might be the right place. From my reading this analyses the Content-Encoding header and adds the encoding to the decoder chain. As at that time the content can be assumed "decoded" the header could be removed.

This patch: https://java.net/jira/browse/GRIZZLY-1669 might be responsible to expose this, though it does not introduce the problem, the problem was just masked before.

**Comment by matthiasblaesing** [comment] 2016-11-20 21:38
I raised https://java.net/jira/browse/GRIZZLY-1875 and added a proposed patch. Tests/comments would be appreciated. I ran a grizzly build and replaced the class in the `nucleus-grizzly-all.jar` and the supplied test works with that.

**Comment by mikecroft** [comment] 2016-11-29 13:01
Internal issue ID `PAYARA-1219`

**Comment by rlubke** [comment] 2016-12-02 06:07
Just to be clear, as of Grizzly 2.3.28, gzip decompression is being applied regardless if disabled in the network listener configuration in the domain.xml?

**Comment by tfal** [comment] 2016-12-02 08:05
Domain directory (from Payara 4.1.1.164 downloaded zip):
[domain1.zip](https://github.com/payara/Payara/files/626605/domain1.zip)
JAX-RS project (corrected):
[compressionTest.zip](https://github.com/payara/Payara/files/626606/compressionTest.zip)
JMeter config file to reproduce error:
[compressionTestJM.zip](https://github.com/payara/Payara/files/626607/compressionTestJM.zip)

**Comment by matthiasblaesing** [comment] 2016-12-09 19:47
@rlubke the GUI does not offer a seperate decompression setting and the compression settings are not applied. If I'm not mistaken:

- GenericGrizzlyListener is the attachement point between glassfish and grizzly
- GenericGrizzlyListener passes the configure CompressionLevel  to CompressionEncodingFilter
- CompressionEncodingFilter evaluates CompressionLevel in combination with the send Accepts header and decides to compress or not

Before the patch in https://java.net/jira/browse/GRIZZLY-1669 the input was never considered for decompression. So we see two issues here:

1. grizzly does not strip the content-encoding header if it applies decompression (that would be https://java.net/jira/browse/GRIZZLY-1875)
2. decompression is always applied even if compression deactivated

For 1. a patch is suggested. For 2. this would be my suggestion:

```diff
--- a/modules/http-server/src/main/java/org/glassfish/grizzly/http/server/CompressionEncodingFilter.java
+++ b/modules/http-server/src/main/java/org/glassfish/grizzly/http/server/CompressionEncodingFilter.java
@@ -114,6 +114,7 @@
         
         assert httpPacket instanceof HttpRequestPacket;
         return canDecompressHttpRequest((HttpRequestPacket) httpPacket, 
+                compressionConfig,
                 aliases);
     }
     
@@ -177,8 +178,13 @@
      */
     protected static boolean canDecompressHttpRequest(
             final HttpRequestPacket request,
+            final CompressionConfig config,
             final String[] aliases) {
         
+        if(config.getCompressionMode() == CompressionMode.OFF) {
+            return false;
+        }
+        
         String contentEncoding = request.getHeader(Header.ContentEncoding);
         
         // If no header is present, assume request is not encoded, so don't decode
```

If compression is disabled decompression is skipped, the other two cases (ON and FORCE) both imply that the server is willing to do compression/decompression. If agreed feel free to use this patch (I have an OCA filed), if needed I can raise a seperate issue for this.

**Comment by rlubke** [comment] 2016-12-12 17:52
I'm somewhat uncomfortable modifying the request.  I think we should correct the regression.

**Comment by matthiasblaesing** [comment] 2016-12-12 17:55
@rlubke what do you suggest? My understanding of your words is: The server won't decompress a request. Why is it ok to modify the header on send, but not on receive?

**Comment by rlubke** [comment] 2016-12-12 18:00
No.  I think Using CompressionConfig to control the behavior is probably the way to go.  It will be disabled by default which would return existing apps that relied on Jersey to handle this to work as they did before.  

Regarding the header modification.  I think it's a different case with the response.  We're adding headers to support compression.  What makes me nervous is modifying an inbound request.  I don't want to make assumptions about what other applications may or may not rely on.  Given that, I think the request should available to the application as is.

**Comment by matthiasblaesing** [comment] 2016-12-12 18:22
Sorry to say it so open: For me your suggestion is useless and even makes the situation worse for me.

Worse in this sense: If you couple decompression to "CompressionConfig" I will have to deactivate compression altogether, as we have decompression ServletFilters deployed. So either the ServletFilter based applications are broken or performance suffers because decompression is removed from all other applications.

I still don't see the problem - yes my approach keeps the information about the content-encoding of the request away from the application, but I don't see the need to get that information at the application level.

If you take both suggested patches above:

- https://github.com/payara/Payara/issues/1186#issuecomment-266105446 and 
- https://java.net/jira/browse/GRIZZLY-1875

then:

If compression is enabled in the server, it will be transparent to the application and from the applications perspective it does not matter if the request has a content-encoding or not, it will only see the decompressed stream. This comes at the cost, that the header is removed.

If compression is disabled, neither compression, nor decompression will happen. Headers won't be touched.

Currently from my perspective this happens:

- Server receives compressed stream, which is indicated in the header
- Server decompresses stream, but leaves indicator in place
- Application now has to magically now, that the stream was decompressed (there is no indicator I'm aware of)

**Comment by lprimak** [comment] 2016-12-17 22:01
@matthiasblaesing I have reviewed your patch, and it looks great.  I do agree with @rlubke about the risks of this, so I am going to try a 3rd option, which is to disable compression processing on Jersey side.

What do you think?

**Comment by matthiasblaesing** [comment] 2016-12-18 16:37
@lprimak thank you for taking the time to review!

With regard to the alternative solution, please keep in mind, that other libraries/servlet filters are affected to. One other example is ziplet, which acts as a serverlet filter to add compression/decompression to a webapplication. I'm interested in the approach you'd take.

**Comment by lprimak** [comment] 2016-12-18 22:32
@matthiasblaesing after extensive testing with many combinations, I have come to the conclusion, just as you have, that the best and the least error-prone (and the least risky) way is to modify the content-encoding header inside Grizzly.  All other methods are Jersey specific and do not work correctly with anything but specific filter combinations, and are brittle and sure-to break

**Comment by lprimak** [comment] 2016-12-18 22:36
@tfal I have come up with a workaround for your specific case until Grizzly gets fixed:

```
@Provider @Priority(Priorities.HEADER_DECORATOR)
public class GzipStripperInterceptor implements ReaderInterceptor {
    @Override
    public Object aroundReadFrom(ReaderInterceptorContext context) throws IOException, WebApplicationException {
        context.getHeaders().get(HttpHeaders.CONTENT_ENCODING).remove("gzip");
        return context.proceed();
    }
}
```

**Comment by lprimak** [comment] 2016-12-18 22:38
Awaiting https://java.net/jira/browse/GRIZZLY-1875

**Comment by lprimak** [comment] 2016-12-18 22:39
The ultimate fix is dependent on https://java.net/jira/browse/GRIZZLY-1875
Please vote for it

**Comment by matthiasblaesing** [comment] 2016-12-20 20:30
@lprimak: You should consider reverting the grizzly version to the version before 2.3.28 (this is the first version doing decompression). As you can see in the grizzly patch discussion I offer a more complete fix, but considering that the end of 2016 is near it might not make it in time for 4.1.1.171 and at work we are currently blocked by this issue and can't update.

**Comment by lprimak** [comment] 2016-12-21 05:03
@matthiasblaesing I cannot make the grizzly decision.
@smillidge or @mulderbaba may be able to help though

**Comment by matthiasblaesing** [comment] 2016-12-22 21:03
I hope the temporary solution is considered.

@lprimak Could you please have a look at the grizzly issue - do you agree with the fix proposed there? As there is a glassfish/payara changed involved I'd like your opinion too.

**Comment by lprimak** [comment] 2016-12-22 23:09
I don't see any changes needed to be made outside Grizzly.  All looks good as far as I can tell

**Comment by lprimak** [comment] 2016-12-22 23:13
I commented on the Grizzly issue.  When compression is enabled, the header removal should be turned on by default, as it's more compliant with "works out-of-the-box" principal

**Comment by lprimak** [comment] 2016-12-30 01:25
@tfal has the workaround work for you?
Let us know, or close this issue.  The ultimate fix is going to be done by Grizzly team

**Closed** 2016-12-30 07:13 UTC
Labels: 1:Wait, c:ConfirmedBug, c:Task, upstream bug
