### ISSUE TITLE
JAX-WS Service not fully working with Moxy /CUSTCOM-63

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#1521] opened 2017-04-10 18:01 UTC
# Description #
----------

My company is trying to migrate its main software from Glassfish 3.1.2.2 towards Payara. This includes several JAX-WS services which have a problem whenever a SOAP fault is to be serialized using eclipselink Moxy JAXBContext.

## Expected Outcome

The SOAP fault should be serialized and returned to the caller.

## Current Outcome

Currently all requests and responses seem to work fine but all SOAP faults trigger an exception:
`
[2017-04-10T19:27:51.457+0200] [Payara 4.1] [SEVERE] [] [com.sun.xml.ws.servlet.http] [tid: _ThreadID=31 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1491845271457] [levelValue: 1000] [[
  caught throwable
com.sun.xml.ws.spi.db.DatabindingException: Unknown JAXBContext implementation: class org.eclipse.persistence.jaxb.JAXBContext
	at com.sun.xml.ws.spi.db.BindingContextFactory.getJAXBFactory(BindingContextFactory.java:207)
	at com.sun.xml.ws.spi.db.BindingContextFactory.create(BindingContextFactory.java:149)
	at com.sun.xml.ws.message.jaxb.JAXBMessage.create(JAXBMessage.java:167)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createSOAP11Fault(SOAPFaultBuilder.java:437)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createSOAPFaultMessage(SOAPFaultBuilder.java:213)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createSOAPFaultMessage(SOAPFaultBuilder.java:201)
	at com.sun.xml.ws.server.WSEndpointImpl.createServiceResponseForException(WSEndpointImpl.java:387)
	at com.sun.xml.ws.server.WSEndpointImpl$1.onCompletion(WSEndpointImpl.java:350)
	at com.sun.xml.ws.api.pipe.Fiber.completionCheck(Fiber.java:923)
	at com.sun.xml.ws.api.pipe.Fiber.run(Fiber.java:823)
	at com.sun.xml.ws.api.pipe.Fiber.start(Fiber.java:420)
	at com.sun.xml.ws.server.WSEndpointImpl.processAsync(WSEndpointImpl.java:368)
	at com.sun.xml.ws.server.WSEndpointImpl.process(WSEndpointImpl.java:398)
	at com.sun.xml.ws.metro.api.config.management.ManagedEndpoint.process(ManagedEndpoint.java:235)
	at com.sun.xml.ws.transport.http.HttpAdapter.invokeAsync(HttpAdapter.java:734)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.invokeAsync(ServletAdapter.java:212)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:161)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:197)
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1696)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
]]
`
There is an open bug report which states some problems with Moxy and JAX-WS but doesn't quite fit: https://java.net/jira/browse/JAX_WS-1130

## Environment ##

- **Payara Version**: 4.1.1.171.0.1
- **Edition**: Full
- **JDK Version**: Oracle 1.8.0_121
- **Operating System**: Mac & Linux

**Comment by lprimak** [comment] 2017-04-10 19:03
Can you please upload a simple test case as described here: http://sscce.org
thanks!

**Comment by svendiedrichsen** [comment] 2017-04-10 20:22
I have created a simple test that you can find at https://github.com/svendiedrichsen/ws-bug-example which triggers the error.

After deployment you will find the service under http://localhost:8080/service/fault?wsdl

I have used SoapUI to trigger the service.

**Comment by svendiedrichsen** [comment] 2017-04-11 15:05
With our attempt activating Moxy by using the system property approach `-Djavax.xml.bind.context.factory=org.eclipse.persistence.jaxb.JAXBContextFactor` we were working around the problem that showed when we tried to use the service file under `META-INF/services`. This file will not be used because a JAXBContext from OSGI is found first.

**Comment by fturizo** [comment] 2017-04-28 20:00
Greetings @svendiedrichsen,

Many thanks for including the sample reproducer for the problem. I need to clarify something first, EclipseLink Moxy is used as the default serialisation provider for **JAX-RS** web services, not **JAX-WS** web services. Payara and Glassfish use the default serializer implementation included with Project Metro, which can be overridden in the same manner you described. I encountered the same issues when the server tries to serialise a SOAP fault, so I reported this issue to the developers so they can get a deeper look into it.

**Comment by fturizo** [comment] 2017-04-28 20:01
Raised internal JIRA issue `PAYARA-1623`

**Comment by svendiedrichsen** [comment] 2017-05-03 21:36
Thanks @fturizo for your clarification. We are running JAX-WS and JAX-RS services in the same server. When activating Moxy for the JAX-RS using the system property this becomes an issue for the JAX-WS services in the same server.

**Comment by rdebusscher** [comment] 2019-12-05 14:11
Tracked by issue CUSTCOM-63

**Comment by AlanRoth** [comment] 2020-11-11 10:26
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:26 UTC
Labels: bug, status:accepted
