### ISSUE TITLE
Payara 5 responds with 404 on endpoints with complex parameter

### ISSUE THREAD

**Issue by schoeffm** [payara/Payara#3077] opened 2018-08-22 10:21 UTC
# Description #
----------

On Payara-Micro 5.182 JAX-RS endpoints which use complex parameter types (no matter if in the header, the path or as query-params) _sporadically_ respond with a 404.
The bug is hard to track since it _sometimes_ works - that's the reason why I've recorded a screencast demoing the behavior. With Payara-Micro v. 4.1.2.181 (and other v4 versions) it works perfectly - but when switching to version 5.182 (and former v5 versions) it breaks.

## Expected Outcome

When calling these endpoints they should be resolved like with Payara v4.1.2.181 - on translation-errors (i.e. if the parameter cannot be parsed) you should get a corresponding error (at least in the server-logs there should be a hint that the parameter was not parsable).

## Current Outcome

Currently, Payara responds with a 404 return code - there are no errors or hints in the server log that give you an idea what was wrong actually with the respective request. 
What is even more irritating is the fact that sometimes the endpoints are called correctly - but after a simple restart of the server (without even a recompilation involved!!) resolution of the very same endpoints fails.
To make sure that this is not just an issue with a local setup glitch I've also added a docker image in the attached demo-project which can be used to fire up the server. Same story here - so even without rebuilding the image it _sometimes_ fails after just restarting the container.

## Steps to reproduce (Only for bug reports) 

Now, this is the tricky part - I did everything I could to make it simple to reproduce. Use the attached project, build the project and restart the server (several times - if necessary). 

1. build the project

        mvn clean package

2. start the server

        mvn payara-micro:start

3. curl the endpoints

        curl -X GET http://localhost:8080/test/resources/pong/bar

    a. if you got a 200 response code - stop the server and go back to step 2.
    b. if you got a 404 response code - that's it

### Samples

I've recorded a demo of the described behavior - plz find it here: 
[![asciicast](https://asciinema.org/a/197520.png)](https://asciinema.org/a/197520)

Also, plz have a look at the attached maven-project (which was also used in the screencast): [test.zip](https://github.com/payara/Payara/files/2309853/test.zip)

The crucial part are these kind of rest-endpoints: 

```
@Path("pong")
@Consumes(MediaType.APPLICATION_JSON)
public class PongResource {
    @GET
    @Path("/{heisenbug}")
    public String pongByPath(@PathParam("heisenbug") ComplexType test) {
        System.out.println(test);
        return "That was successful!";
    }
   ...
}
```
they make use of custom types which are defined like that:
```
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class ComplexType {

    @XmlElement
    public String name;

    public ComplexType() {}

    public ComplexType(String value) {
        this.name = value;
    }

    public static ComplexType fromString(final String value) {
        return new ComplexType(value);
    }

    @Override
    public String toString() {
        return "ComplexType{" +
                "name='" + name + '\'' +
                '}';
    }
}
```
They define a `fromString(String)` method which - according to the javadoc of i.e. `@PathParam` - should be sufficient to parse a given input value.

## Environment ##

- **Payara Version**:  5.182
- **Edition**: Micro
- **JDK Version**: 8 u152 - OpenJDK
- **Operating System**:  Linux / Mac 
- **Database**: no DB involved

**Comment by MattGill98** [comment] 2018-08-22 11:37
Hi @schoeffm,

Firstly I'd like to say thank you for the detailed reproducer and the asciicinema video, they were really useful! I've reproduced this, and it appears to be a bug with Jersey and JAXB unmarshalling. Under the covers, the following error is being swallowed:

~~~
Error un-marshalling JAXB object of type: class com.bender.ping.boundary.ComplexType.
~~~

I've raised internal issue `PAYARA-3038` to address this bug.

In the meantime, since it's a JAXB bug, you should be able to prevent this bug by removing the `@XML` related annotations on the `ComplexType` class. Obviously this only works if you don't require XML deserialisation! In other words, if you only require JSON deserialisation you can remove them.

Kind regards,

Matt

**Comment by schoeffm** [comment] 2018-08-22 12:55
Hi,

yes - removing the `@XML*`-annotations seem to work. We can relinquish XML-marshalling so this would work for us (at least for now).
Should I close this one as you've created an internal issue already?

**Comment by MattGill98** [comment] 2018-09-19 11:07
Fixed by https://github.com/payara/Payara/pull/3094

**Closed by MattGill98** 2018-09-19 11:07 UTC
Labels: 2:WithDev, c:ConfirmedBug, v:Payara-5
