### ISSUE TITLE
[microprofile] The config value does not refresh when the system property changing.

### ISSUE THREAD

**Issue by charleech** [payara/Payara#4817] opened 2020-08-06 05:41 UTC
# Description #
----------

Regarding to the [MP-Config Specification version 1.4: Simple Dependency Injection Example](https://download.eclipse.org/microprofile/microprofile-config-1.4/microprofile-config-spec.html#_simple_dependency_injection_example) metions as

```java
    //Injects a Provider for the value of myprj.some.dynamic.timeout property to
    //resolve the property dynamically. Each invocation to Provider#get() will
    //resolve the latest value from underlying Config.
    //The existence of configured values will get checked during startup.
    //Instances of Provider<T> are guaranteed to be Serializable.
    @Inject
    @ConfigProperty(name="myprj.some.dynamic.timeout", defaultValue="100")
    private javax.inject.Provider<Long> timeout;
```
I've tried to test this feature against the `Payara-Micro 5.2020.3` as the following sample: -

```java
@Path("/config")
@ApplicationScoped
public class MyConfigResource {

    private static final String CONF_KEY = "my.name";

    /**
     * This is a constant which represents the default value as {@value}.
     *
     * @since 1.0.0
     */
    private static final String DEFAULT_VALUE = "unknown";

    @Inject
    @ConfigProperty(
        name         = MyConfigResource.CONF_KEY,
        defaultValue = MyConfigResource.DEFAULT_VALUE
    )
    private Provider<String> myValue;

    @GET
    public Response getConfig() {
        String value1 = null;
        String value2 = null;
        String value3 = null;
        String entity = null;
        try {
            value1 = this.myValue.get();
            System.setProperty(MyConfigResource.CONF_KEY, "system-value1");
            value2 = this.myValue.get(); //<-- expect new value applying here.
            System.setProperty(MyConfigResource.CONF_KEY, "system-value2");
            value3 = this.myValue.get(); //<-- expect new value applying here.

            entity = new StringBuilder().
                         append("value1=").append(value1).append(",").
                         append("value2=").append(value2).append(",").
                         append("value3=").append(value3).
                         toString();

            return Response.ok().entity(entity).build();

        } finally {
            value1 = null;
            value2 = null;
            value3 = null;
            entity = null;
        }
    }
```

The default config is defined as the following:-
```properties
#
# src/main/resource/META-INF/microprofile-config.properties
#
my.name=from-config-file
```

## Expected Outcome

Since the system property has been changed via `System.setProperty`, the configuration with `javax.inject.Provider` should be refresh with the new value automatically.

```bash
curl -v \
-H "Accept: application/json" \
-X GET \
http://localhost:8080/api/config
value1=from-config-file,value2=system-value1,value3=system-value2
```

## Current Outcome

But it is not refresh.

```bash
curl -v \
-H "Accept: application/json" \
-X GET \
http://localhost:8080/api/config
value1=from-config-file,value2=from-config-file,value3=from-config-file
```

### Samples

The full maven project which reproduces this issue is at [charleech/payara-evaluation](https://github.com/charleech/payara-evaluation/tree/master/payara-evaluation-config)

## Context (Optional)

N/A

## Environment ##

- **Payara Version**: 5.2020.3
- **Edition**: Micro
- **JDK Version**: 
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
- **Operating System**: 

```
CentOS Linux release 7.7.1908 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

- **Database**: N/A

**Comment by charleech** [comment] 2020-08-06 08:38
It is my fault, since the [Payara Document: Eclipse MicroProfile Config API: Config Cache Duration](https://docs.payara.fish/community/docs/5.2020.3/documentation/microprofile/config.html#config-cache-duration-configuration)

> Since 5.2020.2 
> Config cache duration can be configured by using Asadmin commands. 
> By default properties have a TTL (time to live) of 60 seconds. 

Then the issue should be a question as how to override the `Payara Micro` TTL to `0` (zero) without using `asadmin`?

Do we have any workaround the passing the TTL via the Environment variable, System property or via the configuration file or other?

**Comment by smillidge** [comment] 2020-08-06 09:30
You can use a pre or post-boot command file see https://docs.payara.fish/community/docs/5.2020.3/documentation/payara-micro/asadmin/pre-and-post-boot-scripts.html 

Looks like it could be something to configure on the command line but that would need an enhancement request.

**Comment by smillidge** [comment] 2020-08-06 09:44
Closing as not a bug

**Closed by smillidge** 2020-08-06 09:44 UTC
