### ISSUE TITLE
Not stable deployment of spring-boot app on payara 5.184

### ISSUE THREAD

**Issue by DNWEIJ** [payara/Payara#4233] opened 2019-09-20 08:55 UTC
# Description #

Depoying a spring boot war file on payara using cargo:redeploy sometimes fails. Although the spring boot log shows 'succesfull started' payara return a 404 on the url. 
Once reload has been hit, the spring boot application is available.  
This happens about 1 out of every 5 deploys.  (Using same war file)

## Expected Outcome
The application should be available everytime after redepoy.

## Current Outcome
On average 1 out of 5 times it is not avaiable and payara return 404.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 8 openJDK
- **Operating System**: linux

Information Question:
- I would like to know how i can further debug or see more logging about the actual deploy process of payara,
- Also how does payara ' known' that a application is succesfully deployed / not succesfully deployed and returning  404
- Is there anything else i can try in settings of payara to influence the logging during deploy?
- Is there anything else i can try to influence the deploy process?

**Comment by smillidge** [comment] 2019-10-01 21:34
Have you tried on the latest Payara version?

**Comment by OndroMih** [comment] 2019-10-08 10:46
Hi, can you provide a reproducer application that gives you the same error on the latest Payara Server version (currently it's 5.193)? If not, we're very likely to close this issue.

It would also help if you shared your log file with us. It may contain some information that describes what's going on during an unsuccessful redeployment.

To briefly answer your questions:

* you can simply debug Payara Server by attaching a debugger to it from your IDE and download the sources of Payara Server from Github to step through the source code
* you can enable FINE logging in Payara Server for the `javax.enterprise` logger to see more details about what's going on. You'll need to filter out some loggers that are not interesting, for example set `javax.enterprise.admin` and `javax.enterprise.config` to INFO
* you can review whether these can improve your deployment: [Scanning exclude and include XML directives](https://docs.payara.fish/documentation/payara-server/app-deployment/descriptor-elements.html#scanning-exclude-and-scanning-include), [Enhanced classloading config](https://docs.payara.fish/documentation/payara-server/classloading.html)

**Comment by OndroMih** [comment] 2020-02-04 13:53
Hi, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us a reproducer for the latest version of Payara Server or Payara Micro. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.

**Closed by OndroMih** 2020-02-04 13:53 UTC
Labels: Insufficient Detail, Try On Latest Release, c:Question, requestor unresponsive (1)
