### ISSUE TITLE
Cannot lookup a global JNDI resource defined in another application /CUSTCOM-105

### ISSUE THREAD

**Issue by orthoxerox** [payara/Payara#3830] opened 2019-03-12 21:42 UTC
# Description #
----------

I tried implementing code from https://blog.payara.fish/deploying-data-source-configuration with one little change: instead of annotating the DataSource field with just `@Resource` I annotated it with `@Resource(lookup = "java:global/datasource")`

## Expected Outcome

The data source is initialized, just like the blog post shows and as Java EE7 spec (EE.5.18)  says the global resource should behave.

## Current Outcome

The data source consumer war fails to deploy with a NamingException:

```
[2019-03-12T23:49:50.425+0300] [] [[1;91mSEVERE[0m] [NCLS-CORE-00026] [[1;94mjavax.enterprise.system.core[0m] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1552423790425] [levelValue: 1000] [[
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: JNDI lookup failed for the resource: Name: [java:module/env/com.example.StartupService/dataSource], Lookup: [java:global/jdbcds], Type: [javax.sql.DataSource]
        at com.sun.enterprise.deployment.util.ResourceValidator.validateJNDIRefs(ResourceValidator.java:896)
        at com.sun.enterprise.deployment.util.ResourceValidator.validateResources(ResourceValidator.java:742)
        at com.sun.enterprise.deployment.util.ResourceValidator.event(ResourceValidator.java:146)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:416)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:540)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:557)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:553)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:552)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:583)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:574)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1483)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:119)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1865)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1741)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:136)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1552)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1036)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:208)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
Caused by: javax.naming.NamingException: Lookup failed for 'java:global/jdbcds' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: java:global]
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
        at javax.naming.InitialContext.lookup(Unknown Source)
        at javax.naming.InitialContext.lookup(Unknown Source)
        at com.sun.enterprise.deployment.util.ResourceValidator.validateJNDIRefs(ResourceValidator.java:891)
        ... 32 more
Caused by: javax.naming.NameNotFoundException: java:global
        at com.sun.enterprise.naming.impl.TransientContext.resolveContext(TransientContext.java:299)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:207)
        at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:70)
        at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:483)
        ... 36 more
]]
```
## Steps to reproduce (Only for bug reports) 

1. Checkout https://github.com/orthoxerox/repro
2. Run `mvn package` in both ds-producer and ds-consumer
3. Drop payara-micro.jar into the root folder of the repo
4. Run `java -jar payara-micro.jar --addlibs include  --nocluster --deploy ds-provider\target\ds-provider-1.0-SNAPSHOT.war --deploy ds-consumer\target\ds-consumer-1.0-SNAPSHOT.war`
5. To prove that the code is otherwise fine, change line 26 in StartupService.java to `@Resource(lookup = "java:global/jdbcds2")`, repackage and rerun step 4. This data source is defined in the same war as the bean itself.

### Samples

See above.

## Context (Optional)

Context: I am trying to structure my EJB application to work both in a traditional Java EE server and in a containerized deployment with a Payara Micro or Thorntail hollow jar. The hollow jar cannot contain data source and JMS connection factory definitions, as the same image must run on both staging and live environments. Neither can this information be encoded in the EJB jar. In addition, I would like to avoid non-cross-platform data source definitions.

## Environment ##

- **Payara Version**:  5.191. Build Number 94
- **Edition**: Micro
- **JDK Version**: Oracle 1.8.0_191
- **Operating System**: Windows
- **Database**: H2

**Comment by smillidge** [comment] 2019-03-16 19:16
Thanks for the test case it helped to find a subtle bug in Payara with multiple deployments that depend on each other. 

First you must use the System property `-Ddeployment.resource.validation=false` to turn off deploy time validation. 
Second there is a bug on the order of initialization of deployments in micro. It is ignoring order on the command line and using a HashMap natural order of key iteration to start the applications therefore the consumer app is being started before the provider app. I fixed this as an example by renaming ds-consumer.war to z.war which forced it to be started after provider.war.

To understand what is going on you need to understand that Payara first deploys each application and then starts each application. The datasource is not registered until the application is started therefore when the consumer war is deployed the datasource does not exist and the resource validation fails the deployment. This can be resolved by setting the system property. The bug arises because the order of starting the applications is not the same order as they were deployed and in your test case the consumer application is started before the provider application.

**Comment by smillidge** [comment] 2019-03-16 19:21
Created PAYARA-3685 to track this

**Comment by rdebusscher** [comment] 2019-12-18 10:46
Tracked now as `CUSTCOM-105`

**Comment by AlanRoth** [comment] 2020-11-11 11:33
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:33 UTC
Labels: bug, status:accepted

**Comment by ojuschugh1** [comment] 2023-06-02 14:47
hi, I am facing this issue recently with the eclipse cargo tracker while running on Payara server 6 in VS Code.
