### ISSUE TITLE
Payara 4.1.1.162 a bug when using the resource javax.sql.DataSource

### ISSUE THREAD

**Issue by balan83** [payara/Payara#843] opened 2016-06-02 05:24 UTC
I want to redeploy our old java web applications from Glassfish 3 to Payara.
I have created a simple web application and jdbc pool for Payara for test.
My application connects to a Oracle 10 database and make a selection from the table. 

I have written this web.xml file for this app:
`<?xml version="1.0" encoding="UTF-8"?>`
`<web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee " title="http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">" class="link">http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"> (http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd)>`
`    <resource-ref>`
`        <res-ref-name>jdbc/pool4UTATOOL</res-ref-name>`
`        <res-type>javax.sql.DataSource</res-type>`
`        <res-auth>Container</res-auth>`
`        <res-sharing-scope>Shareable</res-sharing-scope>`
`    </resource-ref>`
`    <welcome-file-list>`
`        <welcome-file>welcom.jsp</welcome-file>`
`    </welcome-file-list>`
`</web-app>`

And my welcom.jsp file is:
`<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>`
`<%@taglib prefix="sql" uri="http://java.sun.com/jsp/jstl/sql"%>`
`<%@page contentType="text/html" pageEncoding="UTF-8"%>`
`<!DOCTYPE html>`
`<html>`
`    <head>`
`        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">`
`        <title>JSP Page</title>`
`    </head>`
`    <body>`
`        <h1>Hello World!</h1>`
`<sql:query var="subjects" dataSource="jdbc/pool4UTATOOL">`
`    SELECT count(*) cnt FROM msr3.addr_ato`
`</sql:query>`
`<c:forEach var="row" items="${subjects.rowsByIndex}">`
`    <tr>`
`    <c:forEach var="column" items="${row}">`
`        <td><c:out value="${column}"/></td>`
`    </c:forEach>`
`    </tr>`
`</c:forEach>`
`    </body>`
`</html>`

My application works fine on Glassfish 3 with  <res-type>javax.sql.DataSource</res-type> but it does not works on Payara server

When I use this strings:
   <res-type>javax.sql.DataSource</res-type>
in my web.xml file then I get error on Payara server:

Warning:   RAR5117 : Failed to obtain/create connection from connection pool [ DerbyPool ]. Reason : com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: java.net.ConnectException :Error connecting to server localhost port 1527 with message Connection refused: connect.
Warning:   RAR5114 : Error allocating connection : [Error in allocating a connection. Cause: Connection could not be allocated because: java.net.ConnectException : Error connecting to server localhost port 1527 with message Connection refused: connect.]
Warning:   StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception

but when I use the `<res-type> javax.sql.XADataSource </res-type>` or  `<res-type> javax.sql.ConnectionPoolDataSource </res-type>` in my web.xml file, my app works fine.

**Comment by mikecroft** [comment] 2016-06-02 15:02
Have you made sure you've started the database? Either with `asadmin start-database` or `payara41/javadb/bin/startNetworkServer`?

**Comment by balan83** [comment] 2016-06-03 09:27
Apache Derby database really is off, because I do not use Apache Derby database in my applications, but I use Oracle 10.
When I pointing directly resource jdbc/pool4UTATOOL:

`<resource-ref>`
`<res-ref-name>jdbc/pool4UTATOOL</res-ref-name>`
`<res-type>javax.sql.DataSource</res-type>`
`<res-auth>Container</res-auth>`
`<res-sharing-scope>Shareable</res-sharing-scope>`
`</resource-ref> `

Glassfish 3 use the jdbc/pool4UTATOOL resource, but Payara use the  jdbc/__default  resource in this case.

**Comment by lprimak** [comment] 2016-06-03 15:24
GlassFish 4 (and Payara 4) use use jdbc/__default as per the Java EE 7 spec.  GlassFish 3 was more liberal when picking up non-compliant object references.
What you need is resource references in glassfish-web.xml to make this work because the <sql> package that you use probably doesn't comply with the Java EE 7 spec correctly.

The root cause of your problem is that <sql> package is probably using old incompatible JNDI names that only GlassFish 3 understands.
@Resource(name = "jdbc/pool") as opposed to JavaEE 7 compliant @Resource(lookup = "jdbc/pool")

Hope this helps

**Comment by kikokairos** [comment] 2016-06-04 13:49
I have the same issue when setting up my datasource with connection to a Postgres database 9.5 it does not even ping.

**Comment by lprimak** [comment] 2016-06-05 00:23
It's probably worth printing out a warning when silently defaulting to the default data source instead of a lookup failure, so it can be traced much more easily than it is now

**Comment by lprimak** [comment] 2016-06-05 01:26
Payara has assigned this internal engineering issue https://jira.payara.fish/browse/PAYARA-823

**Comment by balan83** [comment] 2016-06-05 09:42
I have no access https://jira.payara.fish/browse/PAYARA-823

**Comment by kikokairos** [comment] 2016-06-05 14:34
I do not know if it's the same case, but found that my problem was the version that the postgresql 9.5 indicated on the site. Not the postgresql-9.4.1208.jre7, but the previous "1207".

**Comment by lprimak** [comment] 2016-06-05 16:51
@balan83 what is the JSP library that supplies <sql> tags are you using?
Is it possible to modify it to use JavaEE 7 compliant JNDI lookups for the data source?
I believe this will solve your immediate issue.

**Comment by mikecroft** [comment] 2016-06-06 08:00
@balan83 that JIRA is our internal one, so it's not publicly accessible. The important part is the `PAYARA-823` issue ID which you'll be able to search for in future release notes.

**Comment by lprimak** [comment] 2016-06-16 20:57
Fixed - Pull request #862

**Closed by lprimak** 2016-06-16 20:57 UTC
Labels: 2:Enhancement, c:Enhancement, reproducible, upstream bug

**Comment by lprimak** [comment] 2016-06-16 21:04
@balan83 As a workaround, meanwhile, you can change JDBC->JDBC Resources->jdbc/__default data source reference to point to your Oracle connection pool (in the Admin GUI)
