### ISSUE TITLE
Escaping in asadmin command create-jvm-options changed /CUSTCOM-137

### ISSUE THREAD

**Issue by bbulk** [payara/Payara#4404] opened 2019-12-31 16:27 UTC
# Description #
----------

Creating a new JVM option with escaped characters works fine in version 5.192, but no longer since version 5.193.

## Expected Outcome

A new JVM option is created and the console shows:
```
asadmin> create-jvm-options "-XX\:MaxPermSize=512m"
Created 1 option(s)
```

## Current Outcome

There is an error and the following output:
```
asadmin> create-jvm-options "-XX\:MaxPermSize=512m"
remote failure: JVM option MaxPermSize=512m is invalid because it does not start with a '-'
```

## Steps to reproduce (Only for bug reports) 

1 -**  Start the asadmin tool

    sh asadmin

2 -**  Start the domain

    asadmin> start-domain

3 -**  Create a new JVM option which requires escaping:

    asadmin> create-jvm-options "-XX\:MaxPermSize=512m"

### Workarounds

1 -**  Using the asadmin tool like this still works:

    ./asadmin create-jvm-options "-XX\:MaxPermSize=512m"

2 -**  Using a second escaping backslash also works:

    asadmin> create-jvm-options "-XX\\:MaxPermSize=512m"

## Environment ##

- **Payara Version**: 5.193, 5.193.1, 5.194
- **Edition**: Full
- **JDK Version**: 11.0.4 OpenJDK (WSL) / 8u201 Oracle (Mac)
- **Operating System**: Windows (WSL with Ubuntu) / Mac

**Comment by rdebusscher** [comment] 2020-01-02 14:11
Hi,

The behaviour of the escaping is changed in Payara version 5.193 and higher due to the upgrade of the JLIne dependency we use for the multimode.

I have created internal issue `CUSTCOM-137` to investigate if we can remove the double escaping requirements in the current version.

Regards
Rudy

**Comment by AlanRoth** [comment] 2020-11-11 11:52
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:52 UTC
Labels: enhancement, status:accepted
