### ISSUE TITLE
Payara can close JarFile instances used by current URLClassLoaders

### ISSUE THREAD

**Issue by bjetal** [payara/Payara#4414] opened 2020-01-07 17:25 UTC
# Description #
----------

Several places in the Payara code call JarFileUtils.closeCachedJarFiles (Weld deployment, undeployment, etc) in order to clean up no longer needed open files.  The problem is that the code cannot determine why the JarFile is open.  Unfortunately in certain circumstances URLClassLoader can open JarFile objects that are stored in that cache and forcing the closure breaks the class loader for all further class loading attempts.

## Expected Outcome

Classloaders should continue working until the classloader itself is closed.

## Current Outcome

Under certain circumstances (URLClassLoaders with a URL NOT in the "file:" schema), the JarFile cleanup causes the class loader to break.

## Steps to reproduce (Only for bug reports) 

The circumstances we saw this was in using JRuby based servlet applications (Ruby on Rails) where it was using internal JRuby SSL code (in the form of the jopenssl.jar file embedded in the jruby-stdlibs jar).

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: Open JDK 8
- **Operating System**: RedHat Linux

**Comment by bjetal** [comment] 2020-01-07 17:30
The best fixes I have been able to come up with for this is to either disable JarFile caching or to change the closeCachedJarFiles to just remove the JarFile from the JarFileFactory cache without actually closing them.  The latter solution will allow the JarFile instances to be garbage collected where they will be closed during finalization.   The below patch will do the latter:

```
diff --git a/nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/JarFileUtils.java b/nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/JarFileUtils.java
index b075c04347..589de8ca29 100644
--- a/nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/JarFileUtils.java
+++ b/nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/JarFileUtils.java
@@ -41,6 +41,8 @@ package com.sun.enterprise.admin.util;
 
 import java.io.IOException;
 import java.lang.reflect.Field;
+import java.lang.reflect.InvocationTargetException;
+import java.lang.reflect.Method;
 import java.net.URL;
 import java.util.ConcurrentModificationException;
 import java.util.HashSet;
@@ -88,13 +90,17 @@ public class JarFileUtils {
                 } else {
                     jarFiles.addAll(files.values());
                 }
+                // Remove the cached files from the cache so they can be closed via finalization
+                // Leave them open in case someone is still using them
+                Method closeMethod = clazz.getMethod("close", JarFile.class);
+                closeMethod.setAccessible(true);
                 for (JarFile file : jarFiles) {
                     if (file != null) {
-                        file.close();
+                        closeMethod.invoke(jarFileFactoryInstance, file);
                     }
                 }
             }
-        } catch (ClassNotFoundException | IllegalAccessException | SecurityException | IllegalArgumentException | IOException | ConcurrentModificationException ex) {
+        } catch (ClassNotFoundException | IllegalAccessException | SecurityException | IllegalArgumentException | ConcurrentModificationException | InvocationTargetException | NoSuchMethodException ex) {
             LOG.log(Level.SEVERE, null, ex);
         }
     }
```

**Comment by rdebusscher** [comment] 2020-01-14 07:33
Hi,

Can you try to disable the CDI scanning of the webapplication? That is probably the system which causes the closing of the jarFiles and gives you problems.
See [here](https://blog.payara.fish/cdi-scanning-in-payara-server)

The closing of the files is required to deal with file locks, mainly on Windows.

Regards
Rudy

**Comment by bjetal** [comment] 2020-01-14 13:38
1. I don't believe that solution will work for us.  We have a number of modules installed into the same server, some of which depend on CDI.  This actually happens after the web application in question is active and other modules are starting up.  Also there are other processes (including undeploy) that also call the code in question.
2. The solution I proposed still allows the files opened by those processes to close because they will be garbage collected.  It might delay it slightly, but at least it won't close files opened by another process.

**Comment by smillidge** [comment] 2020-01-14 13:59
garbage collection doesn't cut it for redeployment on the windows platform. Those files need closing to prevent file locks otherwise the jars can't be deleted when a redeployment occurs leading to a terrible development experience on Windows.

**Comment by bjetal** [comment] 2020-01-14 19:14
While I understand the problem, closing files used by other applications is not acceptable either.  Not sure what the solution is - maybe coming up with a way to track which files need closed when the process completes, possibly combined with turning off caching of open JarFile instances.

**Comment by smillidge** [comment] 2020-01-14 22:30
The files are closed after deployment. What exception are you seeing? My understanding, if I remember correctly, is the classloader will reopen the file if it needs to.

**Comment by bjetal** [comment] 2020-01-15 15:22
We are seeing a file closed exception when attempting to load a class.  Here is the top of the stack trace:
```
[2019-12-20T13:31:07.725-0500] [Payara 5.194] [INFO] [] [javax.enterprise.web] [tid: _ThreadID=231 _ThreadName=pool-32-thread-1] [timeMillis: 1576866667725] [levelValue: 800] [[
  WebModule[/ei] ServletContext.log():java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
java.util.zip.ZipFile.getEntry(ZipFile.java:315)
java.util.jar.JarFile.getEntry(JarFile.java:240)
sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:128)
java.util.jar.JarFile.getJarEntry(JarFile.java:223)
sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1054)
sun.misc.URLClassPath.getResource(URLClassPath.java:249)
java.net.URLClassLoader$1.run(URLClassLoader.java:366)
java.net.URLClassLoader$1.run(URLClassLoader.java:363)
java.security.AccessController.doPrivileged(Native Method)
java.net.URLClassLoader.findClass(URLClassLoader.java:362)
org.jruby.util.JRubyClassLoader.findClass(JRubyClassLoader.java:221)
java.lang.ClassLoader.loadClass(ClassLoader.java:424)
java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

To give a little more detail to what is happening, we have a fairly large application with a number of modules.  One of the modules is Ruby on Rails application running on JRuby.  The version of JRuby we run packs a set of JAR files in one of its libraries and some of our code (indirectly) requires one of those to be loaded into a JRuby controlled ClassLoader which is a subclass of URLClassloader.

Because the URL for the internal JAR is not a 'file:' URL, the URLClassLoader code uses JarURLConnection code to open the JAR, which cause the JarFile to be in the JarFileFactory cache.  When another module in the overall application is deployed, the cleanup process for the Weld deployment then closes all of the JarFiles in the cache, including this one.

I suspect part of the reason we are seeing this is some bad timing, but we were seeing it rather consistently during Glassfish startup until I applied the changes above.

**Comment by bjetal** [comment] 2020-01-15 15:49
The discussion got me thinking more about how this fit together and I was wondering if a reasonable compromise would be to have JarFileUtils.closeCachedJarFiles only close files with a "file:" URL?  It might still cause some problems in unusual circumstances, but would prevent closing JARs opened by URLClassLoader, since it optimizes opening "file:" URLs.

**Comment by smillidge** [comment] 2020-01-17 11:14
If  you can create a PR we can review. We need to check that it doesn't lead to classloader leaks or poor redeploy performance on the Windows platform.

**Comment by OndroMih** [comment] 2020-02-07 12:59
Hi @bjetal, could you please provide a pull request with your suggested improvement? The comments here are very ambiguous and it's not clear what the problem is and how to improve the current behavior.

**Comment by bjetal** [comment] 2020-02-07 15:10
Pull request is https://github.com/payara/Payara/pull/4441.

**Comment by vootelerotov** [comment] 2020-10-12 08:28
I would like to renew this discussion.

I have created a sample set of applications that reproduce the issue caused by cached `JarFile` closures.

[payara-repro-app.zip](https://github.com/payara/Payara/files/5363783/payara-repro-app.zip)

To reproduce the issue, build the project with Maven, deploy `crashing-app`, make a request against it and then deploy `app-that-causes-crashing`. 

One should get the following exception:
```
[#|2020-10-12T10:36:02.815+0300|WARNING|Payara 5.2020|javax.enterprise.web|_ThreadID=102;_ThreadName=http-thread-pool::http-listener-1(4);_TimeMillis=1602488162815;_LevelValue=900;|
  StandardWrapperValve[com.test.CrashingServlet]: Servlet.service() for servlet com.test.CrashingServlet threw exception
java.lang.RuntimeException: java.lang.IllegalStateException: zip file closed
	at com.test.CrashingServlet.doGet(CrashingServlet.java:30)
...
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.access$200(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:519)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at java.util.jar.JarFile$JarEntryIterator.next(JarFile.java:257)
	at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:266)
	at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:247)
	at com.test.CrashingServlet.doGet(CrashingServlet.java:24)
	... 30 more
```

The repro application is artificial, but hopefully it proves the point that the deployment of an application `B` can be destructive for an unrelated application `A`.

I stumbled upon this as part of my work on JRebel. We run our test suites on Payara. This involves deploying a quite large quantity of webapps on a server and this issue causes instability in our tests. 

I do understand the issues around re-deployment on Windows. And I would be much less surprised if this issue happened when I tried to redeploy `app-that-causes-crashing`.

However:
1) Is the forceful closure of `JarFiles` really needed during deployment of the application? Perhaps this could be delayed until undeployment?
2) As I understand this, closing the cached `Jarfiles`  fixes an issue that only affects Windows. Considering the side-effects, this seems like a net negative on Unix. If my understanding is correct, then perhaps this could be limited to only Windows?

Please let me know if you would like me to create another issue instead of continuing the discussion here.

**Comment by fturizo** [comment] 2020-11-11 20:57
@vootelerotov, I'll proceed to close the issue since the original PR was already merged. Please, raise a new issue and test your current reproducer with the latest release of Payara Community Edition.

**Closed by fturizo** 2020-11-11 20:57 UTC
Labels: Type: Community Contribution
