### ISSUE TITLE
Spring Boot - Session Scope is not working

### ISSUE THREAD

**Issue by miltonbo** [payara/Payara#4097] opened 2019-07-20 20:10 UTC
# Description #
----------
I have a project running in Weblogic, but now we want to migrate to Payara Server. The problem happens with the **Session Scope** of the components we have implemented using Spring Boot. 

Basically Session Scope is not working, when I load the login page, there is a redirection too much times until the browser stop and show **ERR_TOO_MANY_REDIRECTS**. This happens because the session is not storing anything and every time the component check for the information about the user, there is nothing and every time send the user to the login page.

My Login component that store the session information is:

```
@Component("loginMB")
@Scope(value = WebApplicationContext.SCOPE_SESSION, proxyMode = ScopedProxyMode.TARGET_CLASS)
public class LoginMB implements Serializable {
    
    private Users user;
    ....
}
```

glassfish-web.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-web-app  PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app error-url="">
    <class-loader delegate="true"/>
    <jsp-config>
        <property name="keepgenerated" value="true">
          <description>Keep a copy of the generated servlet class' java code.</description>
        </property>
      </jsp-config>
    <context-root>micuenta-web</context-root>
    <parameter-encoding default-charset="UTF-8"/>
</glassfish-web-app>
```

## Expected Outcome

@Scope should work and store the information about the session.

## Current Outcome

Any session is stored.

## Steps to reproduce (Only for bug reports) 

1. Create a simple project with JSF and Spring Boot.
2. Implement a Session component with Spring Boot in your project.
3. Use this component in a index.xhtml file.
4. Run the project and the session component must store information about every http session connected to the server.

### Samples

The component:

```
@Component("loginMB")
@Scope(value = WebApplicationContext.SCOPE_SESSION, proxyMode = ScopedProxyMode.TARGET_CLASS)
public class LoginMB implements Serializable {
    
    private Users user;
    ....
}
```

index.xhtml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:adm="http://github.com/adminfaces"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Mi Cuenta | Administrador</title>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
        <link rel="shortcut icon" type="image/x-icon" href="#{resource['img:favicon.ico']}"/>
        <meta name="theme-color" content="#444"/>
        <meta name="mobile-web-app-capable" content="yes"/>

        <h:outputStylesheet library="css" name="login.css"/>
    </h:head>

    <h:body styleClass="hold-transition login-page">
          #{loginMB.user.name}
    </h:body>
</html>

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full
- **JDK Version**: 1.8.0_201    64 Bits
- **Operating System**: Ubuntu 18.04
- **Database**: No needed

**Comment by smillidge** [comment] 2019-07-27 15:32
We need an executable test case to investigate this issue. Can you create one on GitHub.

**Comment by OndroMih** [comment] 2020-02-04 14:01
Hi, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us a reproducer for the latest version of Payara Server or Payara Micro. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.

**Closed by OndroMih** 2020-02-04 14:01 UTC
Labels: Test Case Required, requestor unresponsive (1), requestor unresponsive (2)
