### ISSUE TITLE
Exception When Pinging newly created JDBC Connection Pool 

### ISSUE THREAD

**Issue by CLaz** [payara/Payara#4590] opened 2020-03-26 13:20 UTC
# Description #
An Exception was raised when Pinging a newly created JDBC Connection Pool  from the Domain Admin Console, with the message copied below.

## Expected Outcome
Expected the Ping to succeed.

## Current Outcome
The following message from the Domain Admin Console:
RAR8054: Exception while creating an unpooled [test] connection for pool [ formulationsPool ], Class name is wrong or classpath is not set for : com.mysql.cj.jdbc.MysqlDataSource]]
[2020-03-26T14:04:29.892+0200] [Payara 5.201] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=351 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1585224269892] [levelValue: 1000] [[
  RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/resources/ping-connection-pool.json'; attrs = '{id=formulationsPool}']]
These are snapshots from the Domain Admin Console:
![image](https://user-images.githubusercontent.com/4404560/77650645-77802e00-6f74-11ea-911c-0f1ff8a41977.png)

![image](https://user-images.githubusercontent.com/4404560/77650674-81a22c80-6f74-11ea-8fb6-51b4abbfda6a.png)

![image](https://user-images.githubusercontent.com/4404560/77650933-ba420600-6f74-11ea-9ac2-e7593bdee950.png)

## Steps to reproduce (Only for bug reports) 
Since I don't know if this is a bug or my mistake, I add the steps to reproduce for clarity:
1.	Started Payara 5.201 (build 512) navigarted to Domain Admin Console through NetBeans 11.3.
2.	Navigated to Domain Admin Console->JDBC->JDBC Resources added a new jdbc resource as jdbc/formulatons.
3.	Navigated using the link, to JDBC Connection Pools.
4.	Selected New to create new pool.
5.	Entered name as formulationsPool
6.	Selected java.sqlDataSource as Resource Type.
7.	Selected MySql8 as Driver Vendor since I’m using MySQL 8.0.19.
8.	Selected ‘Next’.
9.	Checked the values; they seem correct as per instructions for MySql 8 (system returned “com.mysql.cj.jdbc.MysqlDataSource” as DataSource Classname, as expeted)
10.	Saved entries and received success message.
11.	Then tried to Ping the Pool created and got the exception message RAR8054 stated above.

 

## Context (Optional)
Attempting to create a JDBC Resource and Connection Pool .

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **JDK Version**: jdk1.8.0_241  - Oracle
- **Operating System**: Windows10
- **Database**: MySQL 8.0.19

**Comment by fturizo** [comment] 2020-03-26 19:22
@CLaz, the issue that you are encountering is due to the Mysql8 JDBC driver missing from the server's classpath, hence why the connection cannot be established. Before starting the server's domain, you need to add the driver's JAR file as a domain library. More instructions on how to do this can be found in this official blog post: https://blog.payara.fish/using-mysql-with-payara. 

Considering this is not a bug/defect in the server, I'll proceed to close this issue.

**Closed by fturizo** 2020-03-26 19:22 UTC

**Comment by CLaz** [comment] 2020-03-26 22:46
Thank you for getting back to me so fast Fabio! Well appreciated!

I followed the steps in the article as exactly as I could. The result is I
get a different massage now:

"Ping Connection Pool failed for mySQLPool. Connection could not be
allocated because: Communications link failure The last packet sent
successfully to the server was 0 milliseconds ago. The driver has not
received any packets from the server. Please check the server.log for more
details".

which by the way has been mentioned already by Richard Grin on
3/6/2020, 2:04:35 PM, as a comment under said article.

 Following the link found in the server Raw Log I get this message:

"{"message":"Cannot find poolName in ping-connection-pool command model, *file
a bug*\ninjection failed on
org.glassfish.connectors.admin.cli.PingConnectionPool.poolName with class
java.lang.String","command":"ping-connection-pool
command","exit_code":"FAILURE","extraProperties":{"methods":[{"name":"GET"},{"messageParameters":{"appname":{"acceptableValues":"","defaultValue":"","optional":"true","type":"string"},"id":{"acceptableValues":"","defaultValue":"","optional":"false","type":"string"},"modulename":{"acceptableValues":"","defaultValue":"","optional":"true","type":"string"},"targetName":{"acceptableValues":"","defaultValue":"","optional":"true","type":"string"}}}],"commandLog":["ping-connection-pool"]},"children":[{"message":"Usage:
ping-connection-pool [--appname=appname] [--modulename=modulename]
pool_name ","properties":{}}]} ".

As you may note, there is mention about filing a bug (?) if I interpret the
message correctly.
Is this a bug ?
Any further assistance greatly appreciated!
Thank you,
Constantine

**Comment by fturizo** [comment] 2020-03-26 23:11
@CLaz, I'm afraid that is not a bug. It seems that your connection pool is not properly configurated to reach your database server. The error you are getting is raised by the JDBC driver when the MySQL server is unreacheable. 

I recommend that you post the configuration of your MySQL connection pool at our official Payara Forum (https://groups.google.com/forum/#!forum/payara-forum) for further assistance.

**Comment by CLaz** [comment] 2020-03-27 10:20
Thank you for giving me a new direction of search. Will post accordingly.

**Comment by Katopy** [comment] 2023-09-13 21:25
> for anyone encountering this on local development, next to your database properties, use `UseSSL: false`

That worked for me, thanks!
