### ISSUE TITLE
The class does not have a descriptor, or a descriptor that does not use inheritance or uses a ClassExtractor for inheritance

### ISSUE THREAD

**Issue by Quix0r** [payara/Payara#966] opened 2016-07-29 13:21 UTC
Severity: **Blocker** (see reason below)
Reproduceable: **Always**

This message comes with following JPQL:
`SELECT c FROM AbstractFoo AS c WHERE TYPE(c) IN :types`
The class is annotated with:

```
@Entity
@Inheritance (strategy = InheritanceType.TABLE_PER_CLASS)
@NamedQueries (
{
// Some named queries
}
)
public abstract AbstractFoo implements Fooable {
// Some properties + equals()/hashCode() methods
}
```

Sadly I cannot simply switch to any other inheritance type as the table design is given (I write a JavaEE application for an existing database).
Then many other concrete classes expands it:

```
@Entity (name = "Some_000123_Foo")
@Table (name = "Some_000123_Foo")
@SuppressWarnings ("PersistenceUnitPresent")
public class SomeFooier extends AbstractFoo {

    /**
     * Serial number
     */
    @Transient
    private static final long serialVersionUID = 15_868_174_390L;

}
```

And tons more of these. As you can see, I try to minimize my code base, else I would have been required to duplicate all the entity properties to all concrete classes.

I already use Payara 162.

An excerpt from the backtrace:

```
Exception Description: Invalid Type Expression on [com.example.project.model.foo.AbstractFoo].  The class does not have a descriptor, or a descriptor that does not use inheritance or uses a ClassExtractor for inheritance
    at org.eclipse.persistence.exceptions.QueryException.invalidTypeExpression(QueryException.java:763)
    at org.eclipse.persistence.internal.expressions.ClassTypeExpression.validateNode(ClassTypeExpression.java:100)
    at org.eclipse.persistence.expressions.Expression.normalize(Expression.java:3291)
    at org.eclipse.persistence.internal.expressions.DataExpression.normalize(DataExpression.java:369)
    at org.eclipse.persistence.internal.expressions.CompoundExpression.normalize(CompoundExpression.java:224)
    at org.eclipse.persistence.internal.expressions.RelationExpression.normalize(RelationExpression.java:574)
    at org.eclipse.persistence.internal.expressions.SQLSelectStatement.normalize(SQLSelectStatement.java:1474)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.buildNormalSelectStatement(ExpressionQueryMechanism.java:550)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.prepareSelectAllRows(ExpressionQueryMechanism.java:1722)
    at org.eclipse.persistence.queries.ReadAllQuery.prepareSelectAllRows(ReadAllQuery.java:885)
    at org.eclipse.persistence.queries.ReadAllQuery.prepare(ReadAllQuery.java:816)
    at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:666)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.checkPrepare(ObjectLevelReadQuery.java:911)
    at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:615)
    at org.eclipse.persistence.internal.jpa.QueryImpl.getDatabaseQueryInternal(QueryImpl.java:342)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createNamedQuery(EntityManagerImpl.java:1135)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createNamedQuery(EntityManagerImpl.java:1155)
    at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createNamedQuery(EntityManagerWrapper.java:537)
    at com.example.project.model.foo.ReportsCustomerSessionBean.fetchSelectedCustomerStatistics(ReportsCustomerSessionBean.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
    at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
    at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4789)
    at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
    at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
    at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
    at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
    at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
    at sun.reflect.GeneratedMethodAccessor276.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
    at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
    at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
    at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
    at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
    at sun.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
    at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
    at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
    at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4761)
    at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4749)
    at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
    at com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
    at com.sun.proxy.$Proxy354.fetchSelectedCustomerStatistics(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:143)
    at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:173)
    at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:528)
    at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:199)
    at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1549)
    at com.sun.corba.ee.impl.protocol.SharedCDRClientRequestDispatcherImpl.marshalingComplete(SharedCDRClientRequestDispatcherImpl.java:119)
    at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.invoke(ClientDelegateImpl.java:258)
    at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:198)
    at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:150)
    at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
```

**Comment by Quix0r** [comment] 2016-08-10 14:05
Bump, because it is always reproduceable and is a blocker (I cannot change datbase layout).

**Comment by mikecroft** [comment] 2016-08-12 11:44
Hi, sorry for the delay! We haven't forgotten about this issue, we're just in a particularly busy time of the year at the moment. Do you have a simple reproducer we could use to help speed things up?

**Comment by Quix0r** [comment] 2016-08-15 07:48
OKay, maybe I can rwrite some, my posting may contain a basic one. Just add a few properties (class fields) to the abstract POJO and let it persist. Then implement an EJB with a named query with TYPE(someAliasOrBean) = :somePlaceholder and you should get the same message.

Oh, I have one more (other) bug in the pipeline.

**Comment by mikecroft** [comment] 2016-08-15 08:23
Thanks, that would be a huge help!

**Comment by Quix0r** [comment] 2016-08-16 14:28
Sorry, running out of hands here.

**Comment by Quix0r** [comment] 2016-08-23 07:35
As I said above, it is some easy  to reproduce:
1) Take my example above and make to a real entity/class (compileable and with at least 1-2 properties/class fields with public getter/setter)
2) Try to let the JPA create them in a database.
3) Run the named query on it with that said TYPE statement

Sorry, I have so much to do here, I cannot write a test case for you here.

**Comment by mikecroft** [comment] 2016-08-23 15:30
OK, no problem, we'll do our best to move it forward as quick as we can

**Comment by Quix0r** [comment] 2016-08-26 14:39
Thank you, very much.

**Comment by Quix0r** [comment] 2016-09-03 15:10
Sorry to say but this is getting urgent. :-(

**Comment by lprimak** [comment] 2016-09-03 18:20
@Quix0r Did you by any chance raise this issue with EclipseLink team?
At first glance, this seems to be an issue with EclipseLink

**Comment by mikecroft** [comment] 2016-09-05 11:44
Sorry it's taken a while @Quix0r. We are, unfortunately, unable to give any guarantees or SLAs on issues raised via GitHub, since we always have to prioritise work for paying customers (we couldn't fund any work if we didn't!). If you [get in touch with us](http://www.payara.fish/contact), we can give you some details on pricing for a support contract where you would get SLAs on tickets and access to our customer-only patch releases so, once an issue has been fixed and merged into the codebase, you wouldn't have to wait more than a month to get a supported build (as opposed to only getting releases once a quarter normally).

**Comment by Quix0r** [comment] 2016-09-05 12:42
@lprimak Okay, I can report it there and link to here. :-)
@mikecroft I understand this.

**Comment by mikecroft** [comment] 2016-09-05 13:20
The next public release will be the 2016 Q4 (164) release, which is currently targeted to early November. The version of Eclipselink in Payara is [a patched 2.6.2](https://github.com/payara/Payara/blob/master/appserver/pom.xml#L125) if the bug is in Eclipselink like @lprimak says, then let us know on this ticket and we will get it into the next public release as soon as it's made available by Eclipselink.

**Comment by smillidge** [comment] 2016-09-07 09:25
Have you thought about dropping down into Native SQL to execute the query you wanted?

**Comment by Quix0r** [comment] 2016-09-07 11:13
No, the query runs over more than one table and cannot be joined.

**Comment by smillidge** [comment] 2016-09-07 12:10
You would need to use a Union.

**Comment by OndrejM** [comment] 2016-12-23 14:31
@Quix0r, can you try if Payara 164 fixes the behavior? 
We haven't had the time to create the testing app to reproduce.

If it is not fixed, I recommend to try with Hibernate - you can bundle it in your application as suggested here: [How To configure Hibernate as a JPA provider](http://stackoverflow.com/questions/34258555/how-to-configure-hibernate-as-a-jpa-provider-for-payara-glassfish-4-1)

**Comment by mikecroft** [comment] 2017-03-24 12:51
@Quix0r [Payara 171](http://www.payara.fish/downloads) is now available, can you try to reproduce with the latest version?

**Comment by Quix0r** [comment] 2017-03-24 22:00
Okay, had not been developing JavaEE recently. Will try to reproduce with it.

**Comment by mikecroft** [comment] 2017-07-04 07:30
Is this still an issue @Quix0r?

**Closed** 2018-03-18 19:19 UTC
Labels: 0:Triaged, Test Case Required, c:PossibleBug, requestor unresponsive (2)

**Comment by Quix0r** [comment] 2018-03-29 18:32
Sorry, no longer employed with them. Still a strange database layout (even the main administrator said that!). So never mind.
