### ISSUE TITLE
Provide a Payara Micro Java EE API artifact /PAYARA-1465

### ISSUE THREAD

**Issue by ggam** [payara/Payara#2082] opened 2017-10-22 07:35 UTC
Excuse me if this is already covered in some way, but I couldn't find it.

Payara Micro supports only a subset of the Java EE 7/8 API, which is at the same time more than the Web Profile.

When creating a new project I don't want to put a dependency on Java EE 7 "full" as it contains more things than supported. The "correct" way would be to depend on Web Profile + the additionally supported specs. But that's error prone and also, I haven't found a complete list of supported specs (I know it adds Concurrency Utilities and JCA at least).

What I'd like to have is a "`payara-micro-javaee-api`" artifact that just depends on Web Profile + other supported specs, so I still have just one dependency. This can be particularly useful for e.g. Payara 5 alphas where possibly not all specs are already Java EE 8. This could also be useful with MicroProfile.

**Comment by Cousjava** [comment] 2017-10-23 07:58
That's a good idea, raised internal issue PAYARA-2227 for the enhancement.

A list of all currently supported APIs is listed at https://www.payara.fish/payara_micro

**Comment by ggam** [comment] 2017-10-23 08:05
Thanks @Cousjava, I didn't see that list of APIs. However a more prominent advertise would be useful. It could also be categorized as Web Profile, Additional features/Java EE specs (JCache, JCA, JBatch and Concurrency Utilities), and MicroProfile.

**Comment by OndroMih** [comment] 2020-02-04 14:50
This is now internally tracked as CLOUD-4.

**Comment by AlanRoth** [comment] 2020-11-11 10:56
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:56 UTC
Labels: enhancement, status:accepted
