### ISSUE TITLE
Method with annotation @RollesAllowed() allways response HTTP Status 401 - Unauthorized

### ISSUE THREAD

**Issue by sgomanf** [payara/Payara#2326] opened 2018-01-25 23:34 UTC
When I went from Payara 5 Beta1 to Beta2 the methods with @RolleAllowed() annotation respond with "HTTP 401 - unauthorized - This request requires HTTP authentication". If I remove the annotation, it responds normally. With beta1, it did not happen.

The Response header is:

content-language →
content-length →1074
content-type →text/html
server →Payara Server 5.Beta2 #badassfish
www-authenticate →Basic realm=""
x-frame-options →SAMEORIGIN
x-powered-by →Servlet/4.0 JSP/2.3 (Payara Server 5.Beta2 #badassfish Java/Oracle Corporation/1.8)

- **Payara Version**: 5 Beta2
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**:

**Comment by sgomanf** [comment] 2018-01-25 23:39
When I invoke the resource's method the log throws the following:

WARNING: WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for

Again, if I remove the annotation it does not report in the log

**Comment by arjantijms** [comment] 2018-02-22 12:40
@sgomanf I assume that with "the methods" you mean methods in JAX-RS resources, right?

The meaning of the `@RolesAllowed` annotation is that only a caller that has at least one of those roles is granted access. If the caller isn't authenticated, the roles aren't known, so that's why the system asks for authentication.

In the previous versions that annotation was by default deactivated for JAX-RS resources, but starting from beta2 it's activated by default.

I wonder, if you don't want access restriction (and hence, authentication), why did you put the `@RolesAllowed` annotation on your methods in the first place?

**Comment by OndrejM** [comment] 2018-02-22 13:32
@sgomanf The behavior you described is correct and intentionally implemented in Payara 5 as @arjantijms explained. Payara 5 will automatically secure JAX-RS methods if there are security annotations.

A client accessing secured resource should authenticate, e.g. by the [basic authentication method](https://en.wikipedia.org/wiki/Basic_access_authentication). In short, the HTTP request should contain `Authorization` HTTP header with the value starting with `Basic`, followed by username and password encoded as described on the wiki page. You may use Graphical REST clients such as [Postman](https://www.getpostman.com/) to generate the header from username and password and try if you can access the secured JAX-RS methods when the HTTP request contains authorization information.

Only if you can't access JAX-RS methods even if your request contains authorization info then it would be a bug. But the behavior you described earlier is expected and thus not a bug at all.

**Comment by sgomanf** [comment] 2018-02-22 18:28
@OndrejM, @arjantijms  thanks for the reply. Yes, I'm actually implementing Bearer authentication scheme (JWT) so I had to create an annotation to provide the authorization mechanisms similar to RollesAllowed through the authentication filters provided by the container. In beta1 I could use RollesAllowed, DenyAll, etc, which prevents me from having to implement my own.

**Comment by arjantijms** [comment] 2018-02-22 23:12
>In beta1 I could use RollesAllowed, DenyAll, etc, which prevents me from having to implement my own.

I see your point, and you would indeed be right if it would prevent you to do that. 

But it doesn't. What the @RolesAllowed baking code does, is effectively calling `HttpServletRequest.authenticate` when it finds that the end point is secured and the caller is not authenticated.

`HttpServletRequest.authenticate` which is a well known method from the Servlet spec will call your standard authentication module/filter if you have installed one in your application. If none is installed it will fallback to the container provided one, which in the case of Payara defaults to the BASIC Authentication mechanism, which is backed by the FILE identity store.

Java EE 8 Security authentication mechanisms will also be called, but that basically happens automatically since they are layered on standard authentication module/filters.

See the code here where it invokes the `authenticate` method:

https://github.com/payara/Payara/blob/master/appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jaxrs/RolesAllowedRequestFilter.java#L93

My guess is that you're not using the right artefact to put your authentication logic, and that thus the `authenticate` call does not reach that point in your code.

There's basically 3 valid places where to put that code, two being EE standard:

1. The ServerAuthModule, see here for a very basic example: https://github.com/javaee-samples/javaee7-samples/blob/master/jaspic/basic-authentication/src/main/java/org/javaee7/jaspic/basicauthentication/sam/TestServerAuthModule.java#L31

2. The HttpAuthenticationMechanism, see here for a basic example: https://github.com/javaee/security-soteria/blob/master/test/app-custom/src/main/java/org/glassfish/soteria/test/TestAuthenticationMechanism.java#L59

3. A Payara specific AuthenticationMechanism/Realm/LoginModule combo, but that's one I would not recommend.

Two more points:

1. Payara already provides JWT based authentication. See https://github.com/javaee-samples/microprofile1.2-samples/tree/master/jwt-auth

2. Despite all the above, I'll implement a switch in `glassfish-web.xml` to switch the default activation of @RolesAllowed off, although for the use case you explained I think that should not be needed.

Hope this helps

**Comment by smillidge** [comment] 2018-02-24 22:50
Fixed by #2446

**Closed by smillidge** 2018-02-24 22:50 UTC
Labels: v:Payara-5
