### ISSUE TITLE
JMS Coordinated Cache

### ISSUE THREAD

**Issue by stePrime** [payara/Payara#1293] opened 2017-01-18 16:26 UTC
Hi Team,

i tried the JMS Cache Coordination in a hazelcast cluster environment .
With ActiveMQ as JMS provider and everything works fine, instead with OpenMQ ( the embedded JMS broker shipped with Payara Server ) it doesn' t work ,the error occurs whereas update operation .

this message is printed in the log file

`Exception Description: Received JMS message is null. Treating it as a JMSException`

- Payara Version: 4.1.1.163
- Edition: Full
- JDK Version: 8 - Oracle
- Operating System: Linux
- Java persistence solution: Eclipselink 2.6.4

Have you any ideas?

**Comment by fturizo** [comment] 2017-01-18 23:21
Hello @stePrime, can you help us reproduce the issue with the detailed steps to configure the server/ application code and deployment? If possible try to link to a sample project hosted on Github for example.

**Comment by lprimak** [comment] 2017-01-19 00:07
BTW I have had cache coordination success in the past via JMS w/EclipseLink, so it is possible with minimum fuss.

**Comment by fturizo** [comment] 2017-04-08 00:38
Greetings @stePrime. Is this issue still persisting? If yes, try to attach a sample reproducer to get more information about the specified error

**Comment by fturizo** [comment] 2017-06-01 21:28
Greetings @stePrime, any news on this issue? Is it still a problem to you? Can you create a sample reproducer to help us identify and solve the problem?

**Comment by mikecroft** [comment] 2017-07-13 08:01
Closing since we cannot reproduce. Please feel free to reopen this issue with a test case that shows the issue.

**Closed by mikecroft** 2017-07-13 08:01 UTC
Labels: 1:Wait, c:PossibleBug, requestor unresponsive (2), Test Case Required
