### ISSUE TITLE
Environment variable substitution for orm.xml /FISH-110

### ISSUE THREAD

**Issue by vanuatoo** [payara/Payara#4055] opened 2019-06-17 10:21 UTC
# Description #
----------
Payara supports environment variable substitution for persistence.xml but in some cases you need to provide orm.xml which defines additional parameters. For instance database schema name

Would be nice to have environment variable substitution for orm.xml

**Comment by rdebusscher** [comment] 2019-12-20 14:17
I have created internal issue `CUSTCOM-127` for this.

**Comment by AlanRoth** [comment] 2020-11-11 11:41
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:41 UTC
Labels: enhancement, status:accepted
