### ISSUE TITLE
asadmin command line does not allow to type only one character being captured

### ISSUE THREAD

**Issue by alexvinok** [payara/Payara#3828] opened 2019-03-12 16:11 UTC
# Description #
----------

When trying to set admin password initially on 5.191 the command line was accepting only one character.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: 
- **JDK Version**: java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

- **Operating System**: Linux svr1 4.1.12-112.14.10.el7uek.x86_64 #2 SMP Mon Jan 8 18:26:37 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Database**:

**Comment by smillidge** [comment] 2019-03-19 17:44
Closing as duplicate of #3833

**Closed by smillidge** 2019-03-19 17:44 UTC
Labels: c:Duplicate
