### ISSUE TITLE
Using --domainConfig together with --rootDir results in the value of --domainConfig being ignored

### ISSUE THREAD

**Issue by bseiller** [payara/Payara#396] opened 2015-08-14 17:45 UTC
Looking in the code of PayaraMicro.bootStrap a possible value of alternateDomainXML is processed prior to the value of rootDir, which then always replaces an existing configFile.
There might be a similar problem if any options that can also be configured via domain.xml (ports, hzConfigFile) and an alternateDomainXML are specified together.

If this is by design, a warning in the log would be nice, otherwise switching the order of processing might solve this.

**Comment by Pandrex247** [comment] 2016-03-03 16:56
Hi bseiller,

I'm currently looking into the order of precedence for configuration files vs. specific options and wasn't able to reproduce what you listed above.

I ran the following command, and it seemed to work as expected (it used the domain.xml I specified in the rootDir I specified): `java -jar ./payara-micro.jar --domainConfig /home/andrew/test-domain.xml --rootDir /home/andrew/Testing`

Are you still able to reproduce this with the latest version of Payara Micro (161)?

Thanks

**Comment by bseiller** [comment] 2016-03-07 10:12
Hi there Andrew,

I'll try and check this, but it will probably have to wait till the beginning of the next week.

Thanks for looking into this!

**Comment by bseiller** [comment] 2016-03-07 10:58
Ok I couldn't resist :)

> I ran the following command, and it seemed to work as expected (it used the domain.xml I specified in the rootDir I specified): java -jar ./payara-micro.jar --domainConfig /home/andrew/test-domain.xml --rootDir /home/andrew/Testing

Ah, that's exactly what I meant: When you specify both the --domainConfig and the --rootDir and there is a domain.xml in the passed rootDir the former domain config is replaced by the latter. Which I find confusing.
If this is intentionally there should be a warning in the log if the replacement actually happens.
Or the via --domainConfig specified file should take precedence over a domain.xml in the rootDir, thus no more replacing happens, in which case the rootDir is used for everything else but not as location for the domain.xml. 

Have a look in \nucleus\payara-modules\payara-micro\src\main\java\fish\payara\micro\PayaraMicro.java starting a line 665:
First the option --domainConfig gets handled, and 
`gfproperties.setConfigFileURI();`
gets called. Then --rootDir gets handled and if there is a domain.xml in the config subfolder
`gfproperties.setConfigFileURI();`
gets called again replacing the previous value and confusing me :)

**Comment by Pandrex247** [comment] 2016-03-07 13:21
Ah OK I understand what you're saying now - I didn't realise you already had a _domain.xml_ in the _rootDir_.

In this case, yes the _domain.xml_ in the _rootDir_ currently holds precedence over what you specify with the `--domainConfig` option due to the order that they are processed in the code.

To me, that doesn't seem right, as in my mind it makes more sense for a more specific thing to have precedence over a more general thing. 
The way it is now, it also means that if you wanted to use a specific directory that you had used previously with a newer _domain.xml_ file, you would need to either clean out that directory, or manually overwrite the _domain.xml_ file yourself.

I'll bring this up with the team for getting a consensus on the precedence order here.
I'll also look at adding some warning messages in for when conflicting/overriding options are specified.

Thanks!

**Comment by bseiller** [comment] 2016-03-07 18:29
Exactly and it might be pretty much the same with other quite specific options like 
`--sslPort`, `--hzConfigFile` or `--deploymentDir` which also can be specified in the domain.xml and thus also via `--domainConfig`
They probably should be processed after `--rootDir` and `--domainConfig`.

Thanks for taking the time to look into this again!

**Comment by smillidge** [comment] 2016-05-04 09:02
Fixed by #740

**Closed by smillidge** 2016-05-04 09:02 UTC
Labels: reproducible
