### ISSUE TITLE
Bug Report: Memory leak in Payara 5.2022.5 related to Grizzly Http2Session

### ISSUE THREAD

**Issue by rdelaplante** [payara/Payara#6258] opened 2023-04-13 14:33 UTC
### Brief Summary

We've been encountering "java.lang.OutOfMemoryError: Java heap space" in Payara logs and managed to capture some heap dumps.  We ran them through Eclipse Memory Analyzer Tool's leak suspects report and looked at the dominator tree.  The leak looks to be related to Grizzly's Http2Session.  It happens on http-listener-2 which has SSL enabled (the only listener exposed to the Internet).    We are going to try disabling HTTP/2 on http-listener-2 to see if that resolves the issue for us.

This issue came up years ago, but it was supposed to be fixed already:

https://github.com/payara/Payara/pull/3897

However I see an open ticket in Grizzly's github seemingly related to the issue I'm describing:

https://github.com/eclipse-ee4j/grizzly/issues/2125

Below is the Eclipse MAT leak suspects report from my heap dump taken on 2023-04-04

![Eclipse MAT 2023-04-04](https://user-images.githubusercontent.com/13222352/231788461-f999f1d5-a365-46bf-8267-5d0767c7acf3.png)

### Expected Outcome

There should be no memory leak related to Grizzly HTTP/2 sessions.

### Current Outcome

OOME, website becomes unusable and we need to restart Payara Server.  We usually see a bunch of these in the server.log

```
[2023-04-04T05:13:36.191-0700] [Payara 5.2022.5] [WARNING] [] [org.glassfish.grizzly.http2.Http2Session] [tid: _ThreadID=263 _ThreadName=http-thread-pool::http-listener-2(12)] [timeMillis: 1680610416191] [levelValue: 900] [[
  Unable to write GOAWAY.  Terminating session.
java.io.EOFException
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.read(TCPNIOTransport.java:615)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleRead(TCPNIOTransportFilter.java:51)
	at org.glassfish.grizzly.filterchain.TransportFilter.handleRead(TransportFilter.java:149)
	at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1131)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]
```

### Reproducer

Unable to provide steps to reproduce. This is happening to two separate installations that experience high traffic on weekends.   The OOME usually happens on weekends.

### Operating System

Windows Server, not sure which version, probably 2019 or 2022

### JDK Version

OpenJDK 17.0.5_8

### Payara Distribution

Payara Server Full Profile

**Comment by rdelaplante** [comment] 2023-04-13 14:57
I forgot to mention that the other server having this issue is running on OpenJDK 11.0.17_8, Payara 5.2022.4 and Windows Server.  So the issue is happening on JDK 11 and 17, Payara 5.2022.4 and 5.2022.5

**Comment by shub8968** [comment] 2023-04-14 10:33
Hi @rdelaplante,

Payara 5 Community is no longer updated. If you can verify the same on the latest release of Payara 6. Thanks.

**Comment by rdelaplante** [comment] 2023-04-14 12:28
Not possible to test on Payara 6. It would require a major migration of the code base. I tried migration in the past but Spring 6 won’t run on Payara 6. It complains about needing asm 9.x despite Payara 6 already using a 9.x version. Also I cannot replicate the high traffic in my dev environment.  

This memory leak is a grizzly bug likely still present in Payara 6 and is worth looking into.

For some reason I cannot comment on this ticket without also closing it?!

**Comment by shub8968** [comment] 2023-06-04 19:33
Hi @rdelaplante,

Is your application also using Primefaces?

**Comment by Bensbush** [comment] 2023-06-07 11:52
Hi,

I experience the same issue on payara 6.2023.2.

Stacktrace:

[2023-06-07T13:23:38.987+0200] [Payara 6.2023.2] [WARNING] [] [org.glassfish.grizzly.http2.Http2Session] [tid: _ThreadID=74 _ThreadName=http-thread-pool::http-listener-2(2)] [timeMillis: 1686137018987] [levelValue: 900] [[
  Unable to write GOAWAY.  Terminating session.
java.io.EOFException
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.read(TCPNIOTransport.java:594)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleRead(TCPNIOTransportFilter.java:59)
	at org.glassfish.grizzly.filterchain.TransportFilter.handleRead(TransportFilter.java:133)
	at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:927)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]

**Comment by rdelaplante** [comment] 2023-06-07 11:56
> Hi @rdelaplante,
> 
> Is your application also using Primefaces?

Yes it uses PrimeFaces 11

**Comment by fturizo** [comment] 2023-06-21 15:52
@rdelaplante, as you are not able to test this reproducer on Payara Server 6, we'll proceed to close this issue. Please re-test this scenario on Payara Server 6 to confirm if the problem is present in its current release.

**Closed by fturizo** 2023-06-21 15:52 UTC
Labels: Type: Bug, Status: Pending
