### ISSUE TITLE
Config password file for CLI commands doesn't work

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#892] opened 2016-07-04 15:46 UTC
Hi,
I use GF 3.1.2.2 and configure a password file just with the password.
Then, any CLI command runs without typing the password, like this:
asadmin --user admin --passwordfile pass.txt ping-connection-pool MyPool
and it works fine.
I tried the same in Payara 4.1.1 and it didn't work.
Then, I saw this link http://docs.oracle.com/cd/E19776-01/820-4495/ghytn/index.html
to configure three lines. I tried and it didn't work too.
Always it appears this line, and I need to retype the pass all the time:
Enter admin password for user "admin"> 
I use the same password pro GF and Payara.
Is there some incompatibility if I have both in the same machine?
Obviously I run one server per time.

**Comment by edilmar** [comment] 2016-07-04 15:59
The link from Oracle is incomplete.
The correct is:
AS_ADMIN_PASSWORD=XXXX
AS_ADMIN_ADMINPASSWORD=XXXX
AS_ADMIN_MASTERPASSWORD=XXXX
AS_ADMIN_USERPASSWORD=XXXX
AS_ADMIN_ALIASPASSWORD=XXXX
I don't know why so many password lines, because no manual explain this.

**Comment by mikecroft** [comment] 2016-07-06 13:23
Are you using the same password for GlassFish and for Payara Server? I believe the issue is likely due to caching in the `~/.gfclient` folder. I've seen this behaviour before on a machine with multiple servers where passwords were different. On my own test machine I've got every version of Payara Server installed and set up and I don't have this issue (I always use the same password).

**Comment by mikecroft** [comment] 2016-07-26 10:33
Hi @edilmar can you try renaming the `~/.gfclient` directory to `~/.gfclient_old` or something? You should see the directory is recreated and the old cached `~/.gfclient/pass` file will not be used

**Comment by mikecroft** [comment] 2016-07-26 10:40
The password values are as follows:

| Value | Meaning |
|--------|------------|
| AS_ADMIN_PASSWORD | The password which is interpreted as belonging to the current user.  |
| AS_ADMIN_ADMINPASSWORD | The password for the current user, but specifically noted as being an admin user. There can be more than one admin user, so this password must match the admin used supplied in the command. |
| AS_ADMIN_MASTERPASSWORD | This is the master password which corresponds to the keystore and trust store. Changing this password will change the keystore and truststore passwords. If you supply new keystore and truststore files, they will need to be locked with this password. |
| AS_ADMIN_USERPASSWORD | A password specifically for a limited access user |
| AS_ADMIN_ALIASPASSWORD | The password to use when creating a password alias, for example a database password. Once the alias is created, this should not be needed again. |

**Comment by mikecroft** [comment] 2016-07-28 14:35
Having tested this myself, renaming/deleting the `~/.gfclient` cache achieves the expected result, so I'll close this issue.

**Closed by mikecroft** 2016-07-28 14:35 UTC
Labels: 1:Wait, c:Question, requestor unresponsive (1)
