### ISSUE TITLE
Properties substitustion issue

### ISSUE THREAD

**Issue by Mephysto666** [payara/Payara#703] opened 2016-03-14 16:06 UTC
Hi there,
I have some problem in properties substitution in DBPool defined in an EJB scope.

This is content of glassfish-resources.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Resource Definitions//EN" "http://glassfish.org/dtds/glassfish-resources_1_5.dtd">
<resources>
  <jdbc-resource enabled="true" jndi-name="jdbc/redevodb" object-type="user" pool-name="RedevoDBPool">
    <description/>
  </jdbc-resource>
  <jdbc-connection-pool allow-non-component-callers="false" associate-with-thread="false" connection-creation-retry-attempts="0" connection-creation-retry-interval-in-seconds="10" connection-leak-reclaim="false" connection-leak-timeout-in-seconds="0" connection-validation-method="table" datasource-classname="org.postgresql.ds.PGConnectionPoolDataSource" fail-all-connections="false" idle-timeout-in-seconds="300" is-connection-validation-required="true" is-isolation-level-guaranteed="true" lazy-connection-association="false" lazy-connection-enlistment="false" match-connections="false" max-connection-usage-count="0" max-pool-size="32" max-wait-time-in-millis="60000" name="RedevoDBPool" non-transactional-connections="false" ping="false" pool-resize-quantity="2" pooling="true" res-type="javax.sql.ConnectionPoolDataSource" statement-cache-size="0" statement-leak-reclaim="false" statement-leak-timeout-in-seconds="0" statement-timeout-in-seconds="-1" steady-pool-size="8" transaction-isolation-level="read-uncommitted" validate-atmost-once-period-in-seconds="0" validation-table-name="pg_catalog.pg_roles" wrap-jdbc-objects="true">
    <property name="User" value="${postgres_user}"/>
    <property name="Password" value="${ALIAS=aptredevo_pwd}"/>
    <property name="databaseName" value="redevolution"/>
    <property name="serverName" value="${postgres_host}"/>
    <property name="PortNumber" value="${postgres_port}"/>
  </jdbc-connection-pool>
</resources>
`

I'm using payara 4.1.1 and Netbeand 8.1 and after a deploy i get this error:

java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: FATAL: password authentication failed for user "${postgres_user}"
  at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:121)

The same error I get when i try a ping by ping button of DBPool in Payara.

If I execute a reload of EJB error disappear both in ping and in application running.

It seems that postgres_user properties are not be substituted.

Can you check this issue please?

Regards.

Meph

**Comment by OndrejM** [comment] 2016-03-25 18:15
Thank you @Mephysto666. I was also able to reproduce the behavior. 
It has nothing to do with PostgreSQL, I was able to reproduce it with a very simple EJB package, using DerbyDB packaged with Payara. It seems that there is a difference in how deployment mechanism works when package is deployed through asadmin and when redeployed from the disk.
I will try to describe the steps:
- use attached EJB module
- start clean Payara server (4.1.1.161.1)  
- run following command to setup system settings
 - asadmin create-jvm-options -Dpostgres_user=app:-Dpostgres_pwd=app:-Dpostgres_host=localhost:-Dpostgres_port=1527
 - restart server to apply settings

Then I was using Netbeans with maven project attached:
 - I executed 'Debug' in Netbeans and selected Payara server -- connection fails on authentication (error in logs, ping does not work in Applications -> EJBapp -> Resources -> Connection pool)
 - directly in Netbeans, I edited source code of StartupBean.java (added a new line), EJBapp was automatically redeployed in background. At this point connection worked (in logs: no errors, info message 'Database connection successful'), but ping button still didn't not work
 - in Netbeans I edited glassfish-resources.xml (added a space somewhere), then EJBapp was redeployed automatically and connection worked, also the ping button worked 
 - when I edited StartupBean.java is updated again, connection works according to log, but ping stopped working again
[EJBapp.zip](https://github.com/payara/Payara/files/189871/EJBapp.zip)

**Comment by OndrejM** [comment] 2016-03-25 18:37
The ping button also does not work in Glassfish 4.1.1, but giving a different error message: Ping Connection Pool failed for { PoolInfo : (name=java:app/RedevoDBPool), (applicationName=EJBapp) }. Connection could not be allocated because: Connection authentication failure occurred. Reason: Userid or password invalid. Please check the server.log for more details.

**Comment by lprimak** [comment] 2016-05-11 22:59
That should fix it

**Comment by smillidge** [comment] 2016-06-12 10:11
Fixed by #810

**Closed by smillidge** 2016-06-12 10:11 UTC
Labels: 2:Defect, c:PossibleBug, reproducible, upstream bug
