### ISSUE TITLE
Inline XSD into generated WSDL /CUSTCOM-59

### ISSUE THREAD

**Issue by Hoobie** [payara/Payara#994] opened 2016-08-04 09:27 UTC
According to the untouched JIRA issue from Glassfish: https://java.net/jira/browse/GLASSFISH-20168
I would suggest adding the -inlineSchema option to the web console. Thank you.

**Comment by mikecroft** [comment] 2016-08-04 10:04
I've created internal issue `PAYARA-966` for this enhancement

**Comment by rdebusscher** [comment] 2019-12-05 08:15
Now internal issue `CUSTCOM-59`

**Comment by AlanRoth** [comment] 2020-11-11 10:20
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:20 UTC
Labels: enhancement, status:accepted, upstream bug
