### ISSUE TITLE
Bug Report: Payara 6 not support @PersistenceUnit annotation?

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#6317] opened 2023-06-26 00:58 UTC
### Brief Summary

Clean installed Payara 6.2023.5, configured JDBC connection pool and datasource.

    ./asadmin --passwordfile /home/payara/config/payaraPW.txt create-jdbc-connection-pool --datasourceclassname org.postgresql.ds.PGSimpleDataSource --restype javax.sql.DataSource --property url="jdbc\:postgresql\://10.0.1.150\:9999/ozssc":user="tomcat":password="tacmot":host="10.0.1.150":port=9999:database="ozssc" --steadypoolsize 64 --maxpoolsize 128 PG15pool-ozssc-150
    ./asadmin --passwordfile /home/payara/config/payaraPW.txt create-jdbc-resource --connectionpoolid PG15pool-ozssc-150 --enabled true jdbc/PG15_ozssc_150

create Entity Audit from Postgresql database as: 

<img width="1163" alt="Screenshot 2023-06-26 at 10 38 39 am" src="https://github.com/payara/Payara/assets/11171226/086a6129-9fab-4609-b4d8-0691753fdac8">

create persistence.xml under META-INF/ as:

<img width="1163" alt="Screenshot 2023-06-26 at 10 42 37 am" src="https://github.com/payara/Payara/assets/11171226/9e25f33c-b3bb-4940-979d-af67efbcd807">

as above, persistenceUnit named as: PG15_OZSSC_NONJTAPU

Then develop AuditMapStore and AuditDataSerializableFactory as:

<img width="857" alt="Screenshot 2023-06-26 at 10 46 25 am" src="https://github.com/payara/Payara/assets/11171226/6ac9bfa9-3918-45b2-9453-b1956ac8d83d">

implemented all methods in MapStore

Then call AuditMapStore from other class, say AuditBean to load data from Database into Hazelcast Map.

<img width="577" alt="Screenshot 2023-06-26 at 10 50 47 am" src="https://github.com/payara/Payara/assets/11171226/401fa6f7-0f13-478f-91fe-a2f288965fce">

Tried to deploy and start service by using @Start annotation in EJB service jar.

Server report error as: entityManager not found. As below:

<img width="2101" alt="Screenshot 2023-06-26 at 10 55 42 am" src="https://github.com/payara/Payara/assets/11171226/dfb1bde8-caa1-4b2c-a51d-3091dca5a403">

### Expected Outcome

Those part of code works well in Payara 5.2021.X version.

All data in Database were loaded into Hazelcast Map properly.

### Current Outcome

JPA EntityManger not found

### Reproducer

Follow the brief summary to reproduce it.

### Operating System

Rocky Linux 9.1

### JDK Version

Oracle JDK 17.0.7

### Payara Distribution

Payara Server Full Profile

**Comment by lprimak** [comment] 2023-06-26 01:33
Looks like you are trying to use OSGi in your application?
It's not a common use case, very hard to get help for I think
Are you sure you are using correct import / export statements in OSGi to import jakarta.* namespace vs. javax.* namespace?

**Comment by cidylong** [comment] 2023-06-26 02:50
@lprimak . 

Yeah. I do used OSGi and bnd-maven-plug in to manage my module import/export in MANIFEST.MF

I checked all my Import-Package: JPA related as: "jakarta.persistence;version="[3.1,4)"". The javax related Import-Packages only Java.naming.* and javax.xml.*.

**Comment by cidylong** [comment] 2023-06-26 02:54
And this is my build section in my pom.xml

<img width="1096" alt="Screenshot 2023-06-26 at 12 53 20 pm" src="https://github.com/payara/Payara/assets/11171226/dc49d611-a246-4d67-a43c-ec9390233ef6">

**Comment by lprimak** [comment] 2023-06-26 04:00
I would remove OSGi, at least for testing purposes

**Comment by cidylong** [comment] 2023-06-26 05:55
@lprimak , for testing purpose, I removed all OSGi related features (dependency and OSGi bundle Activator), re-compile and redeploy it to server.

There is nothing change, Payara 6 server instance report same error: EntityManagerFactory is null.

**Comment by shub8968** [comment] 2023-07-01 00:14
Hi @cidylong,

Can you share the complete reproducer app? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will significantly help us to find the cause and fix the issue. Thanks.

**Comment by cidylong** [comment] 2023-07-03 23:08
@shub8968 , I just come back from Sydney on my business trip. I will try to build s simple package to send to you soon.

**Comment by cidylong** [comment] 2023-07-03 23:11
@shub8968 , The pilot development package will include a database schema with table, entity bean, and simple EJB to start the service. Actually, it is very easy to re-produce it.

**Comment by cidylong** [comment] 2023-07-09 23:27
@PersistenceUnit definitely not work. But when I use

     Persistence.createEntityManagerFactory(ThssUtils.PU_NAME);

as:

<img width="1244" alt="Screenshot 2023-07-10 at 9 23 54 am" src="https://github.com/payara/Payara/assets/11171226/bfe0835e-1296-4157-9f95-3c2d0701e893">

ie. if Inject by using annotation not success (check it by constructor), create it in class constructor.

I got it works now.

**Comment by cidylong** [comment] 2023-07-09 23:38
Please note: JPA module (callee, include Entity, Mapstore and DataSerializableFactory, persistence.xml etc.) was put in jar file and add it to payara as lib. Custom hazelcalt-config.xml (include map and data-serializable-factory configure) was added to production domain's config directory. EJB module (Caller, load database into hazelcast IMap, ebb-jar.xml etc.) was put in an other jar file and deployed into Payara server instance.

**Comment by lprimak** [comment] 2023-07-09 23:44
> JPA module (callee, include Entity, Mapstore and DataSerializableFactory, persistence.xml etc.) was put in jar file and add it to payara as lib

Why? I am 99% sure that's not supported

**Comment by cidylong** [comment] 2023-07-09 23:53
This is what I did in Payara-5.2021.5 (multi-tiers application development idea). It works fine even just simply use @PersistenceUnit in MapStore class. Recently, I'm trying to migrate it to Payara-6.2023.5 (for Jakarta EE 10 compatible), I found @PersistenceUnit not work, but entityManager can be created in MapStore constructor (in Payara lib layer).

**Comment by fturizo** [comment] 2023-07-11 20:43
@cidylong, I'm afraid that @lprimak  is correct. This is an unsupported use case, Payara Server requires persistence units to be defined as specified by the Jakarta EE specification, `MapStore` implementation and other Hazelcast components are not supported for injecting a persistence context. 

I'm not sure why this particular use case worked previously, but unfortunately, it is not a supported use case as it doesn't follow the guidelines of any other Jakarta EE applications.

My advice would be to reconvert this module as a traditional Jakarta EE application and deploy it properly in the server but not as a shared library as you intended. We'll close this issue as there's no proper support to do here.

**Closed by fturizo** 2023-07-11 20:43 UTC
Labels: Type: Bug, Status: Pending

**Comment by cidylong** [comment] 2023-07-12 00:36
@fturizo , Thank you for your explanation, please close this issue.
