### ISSUE TITLE
Ajax components not working in 5.191

### ISSUE THREAD

**Issue by tkernstock** [payara/Payara#3820] opened 2019-03-07 19:32 UTC
# Description #
----------
When updating from 5.184 to 5.191 all ajax based primefaces components stop working. 

I run a JEE8 application with primefaces 6.2 components on a payara 5.184 server without any problems. 
The domain folders are outside the payara program folders so I can easily update and the payara folder is a hardlink to the installation folder.
![grafik](https://user-images.githubusercontent.com/2870206/53981391-bbf31e80-4112-11e9-9952-466dae3334a5.png)

When I leave the domain unchanged and just switch to version 5.191 and restart the domain/nodes all ajax components don't work anymore. 

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: 8 202 OpenJDK
- **Operating System**:  Linux
- **Database**:  MySQL

**Comment by smillidge** [comment] 2019-03-16 19:35
Hi Can you provide a test case for this we could use?

**Comment by tkernstock** [comment] 2019-03-19 12:10
Unfortunatley not, the project is huge and I didn't find the time yet to isolate a testcase from it. Sorry.

**Comment by mulderbaba** [comment] 2019-04-04 12:42
@tkernstock does this apply to [PrimeFaces Showcase](http://repository.primefaces.org/org/primefaces/showcase/6.2/showcase-6.2.war) as well? If yes, we can use that as the reproducer. If not, then something related to your env. may be the cause of the problem.

**Comment by tkernstock** [comment] 2019-04-04 13:46
Hi, very good idea, thanx. I will try that as soon as possible and reply the results!

**Comment by sgflt** [comment] 2019-04-04 18:38
I am experiencing similar problem. I found that the response produces unparseable XML for partial update. I think the problem in my case is with panelGroup that produces a </span> end tag without opening tag.

I will try to create a test case for that too.

**Comment by erickdeoliveiraleal** [comment] 2019-04-05 21:51
try to update to primefaces 7.0. @abelet provided a commit to work around this bug in mojarra. or you can install myfaces into payara. myfaces doesn't have this bugs. https://github.com/primefaces/primefaces/issues/4122

**Comment by sgflt** [comment] 2019-04-06 08:06
I have created a test case https://github.com/sgflt/payara-test-case/commit/ac66d1c2af360849af49783c756879161481d611 

The problem is already described in javaserverfaces/mojarra#4370

**Comment by abelet** [comment] 2019-04-08 19:26
It is quite similar to eclipse-ee4j/mojarra#4488. Unfortunately mojarra not just buggy, but after examining the implementation, the code quality seems to be very poor also.

**Comment by tkernstock** [comment] 2019-07-05 13:59
Hi again,
I installed Payara 5.192 but the ajax problem still exists. So I tried to create a Testcase and found out, that the problem is neither payara nor primefaces. If you get the following error check if you are using omnifaces and make sure to update to version 3.3. My problem was caused by version 3.2 and I suppose its the org.omnifaces.exceptionhandler.FullAjaxExceptionHandlerFactory:

`2019-07-05T15:11:19.662+0200|SCHWERWIEGEND: Error Rendering View[/testpage.xhtml]
java.lang.IllegalArgumentException: Unerkannter Inhaltstyp
	at com.sun.faces.renderkit.RenderKitImpl.createResponseWriter(RenderKitImpl.java:259)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.createResponseWriter(FaceletViewHandlingStrategy.java:1125)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:415)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:115)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at org.apache.deltaspike.jsf.impl.listener.request.DeltaSpikeLifecycleWrapper.render(DeltaSpikeLifecycleWrapper.java:111)
	at javax.faces.lifecycle.LifecycleWrapper.render(LifecycleWrapper.java:88)
	at org.apache.deltaspike.jsf.impl.listener.request.JsfClientWindowAwareLifecycleWrapper.render(JsfClientWindowAwareLifecycleWrapper.java:160)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:339)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:133)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:118)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:81)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by OndroMih** [comment] 2020-04-03 10:58
Hi @sgflt , can you provide instructions how to use your reproducer? I was able to build it and deploy but when I access http://localhost:8080/bug/ajax.xhtml, I get "HTTP Status 403 - Access to the requested resource has been denied". It doesn't help if I create a user in the file realm that has the AJAX_VIEW role and then try to log in using http://localhost:8080/login. If I remove teh security constraint in web.xml and access http://localhost:8080/bug/ajax.xhtml, it always redirects to http://localhost:8080/login even if I already logged in.

**Comment by OndroMih** [comment] 2020-04-03 10:59
Besides, I think it's already fixed with the new Mojarra version 2.3.13 in Payara Server 5.201: https://github.com/payara/Payara/issues/4424. Can you check?

**Comment by tkernstock** [comment] 2020-04-03 11:04
Hi,
In Payara 5.201 this problem is gone. There is another one with Mojarra in this new version too, but I was able to find a workaround -> https://github.com/payara/Payara/issues/4588
br
Thomas

**Comment by sgflt** [comment] 2020-04-03 16:45
> Hi @sgflt , can you provide instructions how to use your reproducer? I was able to build it and deploy but when I access http://localhost:8080/bug/ajax.xhtml, I get "HTTP Status 403 - Access to the requested resource has been denied". It doesn't help if I create a user in the file realm that has the AJAX_VIEW role and then try to log in using http://localhost:8080/login. If I remove teh security constraint in web.xml and access http://localhost:8080/bug/ajax.xhtml, it always redirects to http://localhost:8080/login even if I already logged in.

Hi @OndroMih. Ajax seems to be fixed in 5.201. The testcase was clearly reproducible without 403 on Payra 5.194, so maybe there is another bug. I will try to identify authorization problem and probably raise another issue. :) (It may be related to session management and cookies mentioned in already created issues)

**Comment by OndroMih** [comment] 2020-04-20 22:43
Thanks for confirmation that the issue is solved in 5.201. I'm closing this.

**Closed by OndroMih** 2020-04-20 22:43 UTC
Labels: cannot reproduce, status:reproducer-needed, upstream bug
