### ISSUE TITLE
Payara 5.182 https extremely slow

### ISSUE THREAD

**Issue by linfaimom** [payara/Payara#3022] opened 2018-08-07 15:37 UTC
# Description #
----------

Before migrating to Payara 5.182, I use Payara 4.1.181, and the http/https requests are all very fast. Things go strange when I migrate to Payara 5.182, the configurations are all the same as Payara 4.1.181, http requests are working just fine, but the https requests become extremely slow.

Then I found that one difference between Paraya 5.182 and Payara 4.1.181 is that Payara 5.182 makes the HTTP/2 default enabled, so I disabled the HTTP/2 and then tried again, things go normal as before! 

So, as far as I've tried, maybe it's HTTP/2 that makes the https requests become so slow, but I'm not sure what really happened behind, hoping you guys find out why and finally fix it.

## Expected Outcome

Expecting the https request should as fast as or even faster than Payara 4.1.181

## Current Outcome

Accessing the page using https will spend minutes or even couldn't access.

## Steps to reproduce (Only for bug reports) 

* Here's how I write my CA Cert to keystore.jks & cacerts.jks, just the same operations like I did in Payara 4.1.181
   * `keytool -importkeystore -destkeystore keystore.jks -srckeystore 3MEdu.p12 -srcstoretype PKCS12 -alias 3medu_cert`
    * `keytool -importkeystore -destkeystore cacerts.jks -srckeystore 3MEdu.p12 -srcstoretype PKCS12 -alias 3medu_cert`

* Here's how I configure the http-listener, also the same way like Payara 4.1.181
   * create 80-port for http request
      * ![image](https://user-images.githubusercontent.com/12679396/43786018-38775194-9a9a-11e8-9b8d-b154f56d5701.png)

   * create 443-port for https request, and enable ssl, set the Certificate NickName
      * ![image](https://user-images.githubusercontent.com/12679396/43786075-5f499520-9a9a-11e8-9699-0ef526a75485.png)
      * ![image](https://user-images.githubusercontent.com/12679396/43786104-72269a08-9a9a-11e8-8acb-3f66c877f7dd.png)

### Samples

* Because I'm in production environment, so I roll back to Payara 4.1.181 and forget to capture the request & response image, sorry about that
* Here's the log show what happened at that time
   * ![image](https://user-images.githubusercontent.com/12679396/43786190-a8528ee8-9a9a-11e8-9f22-5270d7800cb2.png)

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**: Oracle JDK 8u161
- **Operating System**: Ubuntu 16.04.4 LTS
- **Database**: MySQL

**Comment by smillidge** [comment] 2018-08-07 16:51
Are you using Primefaces?

**Comment by smillidge** [comment] 2018-08-08 09:25
OK thanks can you provide a test case that demonstrates the issue as this is the first time we are aware of the issue without using Primefaces.

**Comment by smillidge** [comment] 2018-08-08 09:26
Also can you let us know which browser you are using and whether you are accessing Payara Server directly or via another webserver like Apache, Nginx etc?

**Comment by linfaimom** [comment] 2018-08-08 10:15
* Almost every modern browsers we've tried, like chrome, firefox and safari, but got the same result. And we're accessing Payara Server directly. In addition, we also use our phone with mobile data and toggle the VPN on/off to test the page, still the same result, so it should not be client network's issue
* The test case I will provide to you tomorrow, sorry about that

**Comment by OndrejM** [comment] 2018-08-08 14:27
This issue was reported here first: https://stackoverflow.com/questions/51639240/payara-5-https-extremely-slow/51676915

**Comment by lprimak** [comment] 2018-08-15 23:08
Never mind, I can once again reproduce the issue

**Comment by lprimak** [comment] 2018-08-16 06:40
Possible duplicate of #2625

**Comment by linfaimom** [comment] 2018-08-16 10:13
Here's the screen capture, it took 1.2 minutes to finally finished.

"分" means "minute"
"秒" means "second"
"毫秒" means "ms"

![2018-08-16 6 07 19](https://user-images.githubusercontent.com/12679396/44202838-aa9af280-a17f-11e8-9fad-c483945f7d55.png)
![2018-08-16 6 07 48](https://user-images.githubusercontent.com/12679396/44202839-abcc1f80-a17f-11e8-9eb0-2fd354505e3f.png)

**Comment by lprimak** [comment] 2018-08-16 15:52
Can you confirm if the issue still exists with HTTP/2 server push disabled in the "advanced" tab for HTTPS listener?

**Comment by linfaimom** [comment] 2018-08-17 02:59
Did you mean keep the HTTP/2 enabled but disabled the server push?

**Comment by linfaimom** [comment] 2018-08-17 03:00
I'll have a try

**Comment by linfaimom** [comment] 2018-08-17 10:01
I've tried, but got the same result unless I disable the whole HTTP/2

**Comment by smillidge** [comment] 2018-09-02 20:16
I'm going to close this as a duplicate of #2625 as there is more discussion in the history of #2625

**Closed by smillidge** 2018-09-02 20:16 UTC
Labels: c:Duplicate

**Comment by linfaimom** [comment] 2018-09-25 13:07
@davidandradeb You can find how to disable the HTTP/2 in this [doc](https://docs.payara.fish/documentation/payara-server/server-configuration/http/protocols.html)

**Comment by davidandradeb** [comment] 2018-09-25 13:10
Thanks the complete menu are: 

Network Config -> Network Listeners -> http-listener-2 - HTTP TAG an search the HTTP/2 Option to disable
