### ISSUE TITLE
NullPointerException in Payara Micro when access logging to console is enabled

### ISSUE THREAD

**Issue by lreimer** [payara/Payara#4652] opened 2020-05-05 09:37 UTC
# Description #
----------

For a current project, we want to configure Payara Micro access logging to output to console. We use a preboot command file to issue the required `asadmin` commands. But instead of the access logs we see a NullPointerException on the console for `com.sun.enterprise.web.PEAccessLogValve`

## Expected Outcome

No NullPointerException is thrown, the access logs are logged to console.

## Current Outcome

Currently, a NullPointerException is thrown.
```
Exception in thread "AccessLogWriter" java.lang.NullPointerException
	at com.sun.enterprise.web.PEAccessLogValve.log(PEAccessLogValve.java:629)
	at com.sun.enterprise.web.PEAccessLogValve.run(PEAccessLogValve.java:1275)
	at java.lang.Thread.run(Thread.java:748)
```

## Steps to reproduce (Only for bug reports) 

Start Payara Micro (5.201) with the `--prebootcommandfile` option and a file with the following content:

```
set configs.config.server-config.http-service.access-logging-enabled=true
set configs.config.server-config.http-service.virtual-server.server.access-logging-enabled=true
set configs.config.server-config.http-service.access-log.log-to-console-enabled=true
set configs.config.server-config.http-service.access-log.write-interval-seconds=5
set configs.config.server-config.http-service.access-log.format="%client.name% %auth-user-name% %datetime% %request% %status% %response.length% %header.referer% %header.user-agent% %time-taken% %header.X-ISPI-REQ-ID% %cookie.JSESSIONID% %header.X-Forwarded-For% %header.X-Forwarded-Host% %header.X-Forwarded-Server% %header.X-ICS-Version% %header.X-APP-Version% %header.X-APP-Name% %attribute.v4%"
```

### Samples

A sample with access logging to console enabled is here: 
https://github.com/lreimer/payara-micro-appcds.git
```
$ ./gradlew assemble microStart
$ curl http://localhost:8080/api/appcds
```

## Context (Optional)

We want the access logs on console for easier log processing using FluentBit on Openshift. Access logging to file works, but requires extra configuration effort. So console access logging is the desired solution.

## Environment ##

- **Payara Version**: 5.201 (prior version probably also affected)
- **Edition**: Micro
- **JDK Version**: Zulu JDK 8u242
- **Operating System**: Linux, Mac
- **Database**: no relevant

**Comment by DhyanB** [comment] 2020-07-01 15:30
Any updates on this?

**Comment by khasunuma** [comment] 2020-09-10 02:47
Unfortunately, we’re not able to fit this feature request into our current roadmap. I’m closing this issue. I hope you understand.

**Comment by khasunuma** [comment] 2020-09-10 04:43
Hi @lreimer 

I think this issue has two means, so I'd like you to let us know which is your intention:

* a bug report that `NullPointerException` in the situation you told
* an enhancement request to output access log to console

If you aim later, unfortunately, we’re not able to fit this feature request into our current roadmap.

**Comment by lreimer** [comment] 2020-09-10 07:00
Hey @khasunuma , thanks for the reply. 
The `NullPointerException` is definitely unexpected behaviour in the described situation.
Can you please clarify why you consider the output of access log to console as a feature request? If I issue the above asadmin commands to enable access logging to console in Payara Server this is working OK. If I issue the above commands in Payara Micro, this results in the described NPE.

I can try to investigate and fix the issue myself and provide a PR for the described issue. Would that solve your problem with the current roadmap?

**Comment by dmatej** [comment] 2020-09-10 07:58
It is this block, could it be a configuration issue, like something called the System.setStdOut with null?
```
                if (accessLogToConsole && !bufString.isEmpty()) {
                    logManager.getOutStream().print(bufString.replaceAll("(?m)^", "AccessLog: ")); // line 629
                }
```
I refactored the LogManagerService to be more stable in these cases, but it really is not in the current road map despite most of the work is done. Can you build [this branch](https://github.com/dmatej/Payara/tree/PAYARA-4176-TestContainers-prototype) and give me feedback if it is reproducible there too?

**Comment by lreimer** [comment] 2020-09-10 08:04
OK. I will try and give you feedback until tomorrow.

**Comment by MeroRai** [comment] 2020-11-12 17:08
Hi @lreimer, 

Due to the lack of activity form you I am closing this issue immediately. If the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by MeroRai** 2020-11-12 17:08 UTC
Labels: Status: Pending, Type: Bug

**Comment by lreimer** [comment] 2020-11-12 17:10
Thanks @MeroRai 
I will soon retry with latest 5.2020.6 release.
