### ISSUE TITLE
JSON log formatter not used consistently if non-default log file /CUSTCOM-95

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#2976] opened 2018-07-22 20:26 UTC
# Description #
----------

If you configure the payara server to use the JSONLogFormatter and a non-default log file the `com.sun.enterprise.web.VirtualServer` will not use the JSONLogFormatter.

## Expected Outcome

JSONLogFormatter will be used consistently.

## Current Outcome

Default formatter will be used although the JSONLogFormatter is configured when i.e. Exceptions from REST resource methods are to be logged.

## Steps to reproduce (Only for bug reports) 

1 -**  Configure the domain to use JSONLogFormatter

2 -**  Configure a non-default log file

3 -**  Throw exception from REST resource method and observer the log

## Context (Optional)

```
   class VirtualServer
   ...
    synchronized void setLogFile(String logFile, String logLevel, String logServiceFile) {

        /*
         * Configure separate logger for this virtual server only if
         * 'log-file' attribute of this <virtual-server> and 'file'
         * attribute of <log-service> are different (See 6189219).
         */
        boolean customLog = (logFile != null && logServiceFile != null
                && !new File(logFile).equals(new File(logServiceFile)));
...
            // add handlers from root that is not GFFileHandler
            Logger rootLogger = Logger.global.getParent();
            if (rootLogger != null) {
                Handler[] rootHandlers = rootLogger.getHandlers();
                if (rootHandlers != null) {
                    for (Handler h : rootHandlers) {
                        if (!(h instanceof GFFileHandler)) {
                            newLogger.addHandler(h);
                        }
                    }
                }
            }

            // create and add new handler
            fileLoggerHandler = fileLoggerHandlerFactory.getHandler(logFile);
            newLogger.addHandler(fileLoggerHandler);
            newLogger.setUseParentHandlers(false);
...
```
The above code will result in a new logger being created and the call `fileLoggerHandlerFactory.getHandler(logFile);` will create a new handler which does _not_ use the JSONLogFormatter but the default one.

## Environment ##

- **Payara Version**: 4.1.2.174 / 4.1.2.181 and most probably 5.x also
- **Edition**: Full / Micro
- **JDK Version**: doesn't matter
- **Operating System**: doesn't matter
- **Database**: doesn't matter

**Comment by svendiedrichsen** [comment] 2018-07-23 18:51
As a workaround you can set the `log-file` attribute of the `<virtual-server>` configuration to the same value as the `GFFileHandler.file` property. Thus you avoid the creation of a new logger and the usage of the default formatter.

**Comment by smillidge** [comment] 2018-08-19 21:00
What do you mean by non-default log file?

**Comment by svendiedrichsen** [comment] 2018-08-19 21:37
@smillidge The default would i.e. be the logs/server.log file configured in the logging.properties by the GFFileHandler.file property. If you change this to a different location/file it will in the above mentioned formatting problem.

**Comment by MeroRai** [comment] 2018-09-10 09:52
Hi @svendiedrichsen, 

I can confirm this bug is present on the latest build of the master branch. I have created an internal issue `PAYARA-3092` to address it. 

Regards,
Su-san

**Comment by rdebusscher** [comment] 2019-12-17 13:40
Tracked now as `CUSTCOM-95`

**Comment by CarlosMOGoncalves** [comment] 2020-08-20 16:12
Hello there!
Can you provide any update on this issue?
We've jump bumped into the same problem lately and I see it has already been reported here.
Thanks!

**Comment by rdebusscher** [comment] 2020-08-24 09:08
Hi Carlos,

The ticket is not yet scheduled for development as we give priority to requests from Enterprise Customers.

Best Regards
Rudy

**Comment by AlanRoth** [comment] 2020-11-11 11:22
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:22 UTC
Labels: bug, status:accepted
