### ISSUE TITLE
RejectedExecutionException after upgrading to 5.184

### ISSUE THREAD

**Issue by rickuf** [payara/Payara#3532] opened 2018-12-18 22:22 UTC
# Description #
----------

After upgrading from Payara Micro 5.183 to 5.184 the server does not start properly and the application is not deployed.
## Expected Outcome
The application starts as expected. 

## Current Outcome
The following error occurs:
`[2018-12-18T21:40:25.679+0000] [] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=38 _ThreadName=payara-executor-service-task] [timeMillis: 1545169225679] [levelValue: 1000] [[
  Exception while parsing file file:/tmp/payaramicro-rt723860021734334896tmp/applications/woa-app-application-1.0/
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7ce9cbc3 rejected from java.util.concurrent.ThreadPoolExecutor@4dfdc8f9[Running, pool size = 20, active threads = 20, queued tasks = 30, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.glassfish.hk2.classmodel.reflect.Parser.parse(Parser.java:293)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleJar(ReadableArchiveScannerAdapter.java:197)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:131)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:345)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:68)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:304)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]
[2018-12-18T21:40:25.681+0000] [] [WARNING] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1545169225681] [levelValue: 900] result fault org.glassfish.hk2.classmodel.reflect.Parser$Result@60bbacfc Result for /tmp/payaramicro-rt723860021734334896tmp/applications/woa-app-application-1.0/
`

## Context (Optional)
Version 5.183 is still working as expected.

Sorry for barely giving any information, I am totally lost where this error comes from.

## Environment ##

- **Payara Version**: 5.184
- **Edition**:  Micro
- **JDK Version**:  10 - OpenJDK
- **Operating System**:  Docker on Ubuntu 18.04

**Comment by lprimak** [comment] 2018-12-18 23:23
This is a duplicate of #3495

**Closed** 2018-12-18 23:23 UTC
Labels: c:Duplicate
