### ISSUE TITLE
Response wrapped in WebApplicationException looses headers

### ISSUE THREAD

**Issue by roslaw-md** [payara/Payara#3349] opened 2018-10-31 16:38 UTC
# Description #
----------

The JAX-RS application throws a WebApplicationException with a Response 301 Moved Permanently and a location, which is handled by the container:
`    final URI uri = new URI("https://www.google.com/");`
`    final Response response = Response.status(Status.MOVED_PERMANENTLY).location(uri).build();`
`    throw new WebApplicationException(response);`

With 5.183, the location-header is missing in the server response. The header was present with Payara 4.x.

## Expected Outcome

If a location was added to the Response object wrapped by a WebApplicationException, then the location-header should be present in the server response:
Location: https://www.google.com/

## Current Outcome

With Payara 5.183, the location-header is missing. This isn't restricted to the location-header, it seems all headers added to the Response object are ignored, if wrapped by a WebApplicationException.

## Steps to reproduce

1 -** Deploy the sample application

    ./asadmin deploy --name example --contextroot example example.war

2 -** Open the sample page

    http://localhost:8080/example/

3 -** Follow the link to the resource that throws a WebApplicationException with a Response with status 301 and the location google.com

    http://localhost:8080/example/rest/moved

4 -** You didn't get redirected to google.com, because the location-header is missing

### Notice

If the Response is returned directly, then the location-header is present. This is only about throwing a WebApplicationException with a Response.

### Samples

Zip with example.war and the ExampleResource.class (also included in the war):
[example.zip](https://github.com/payara/Payara/files/2535395/example.zip)

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: Oracle 1.8.0_192
- **Operating System**: Windows 10, Linux / CentOS 6

**Comment by MattGill98** [comment] 2018-11-01 10:48
Hi @roslaw-md,

Thank you for raising this issue, I can confirm this is present since 5.182. I've raised internal issue `PAYARA-3225` to address this.

Kind regards,

Matt

**Comment by mulderbaba** [comment] 2018-11-09 11:44
fixed by #3397

**Closed by mulderbaba** 2018-11-09 11:44 UTC
Labels: c:ConfirmedBug, v:Payara-5
