### ISSUE TITLE
Build failing with InvalidAlgorithmParameterException

### ISSUE THREAD

**Issue by craigday** [payara/Payara#671] opened 2016-02-19 23:26 UTC
Trying to build master, have tried multiple version of jdk 1.7 on OSX and Centos Linux.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.6:unpack (unpack) on project web-gui-plugin-common: 
Unable to resolve artifact. Could not transfer artifact org.glassfish.docs.man:web-gui-plugin-common-manpage:zip:4.1 from/to jvnet-nexus-releases (https://maven.java.net/content/repositories/releases/): 
Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: 
the trustAnchors parameter must be non-empty from https://maven.java.net/content/repositories/releases/org/glassfish/docs/man/web-gui-plugin-common-manpage/4.1/web-gui-plugin-common-manpage-4.1.zip
[ERROR] org.glassfish.docs.man:web-gui-plugin-common-manpage:zip:4.1
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] jvnet-nexus-releases (https://maven.java.net/content/repositories/releases/, releases=true, snapshots=false),
[ERROR] jvnet-nexus-staging (https://maven.java.net/content/repositories/staging, releases=true, snapshots=false),
[ERROR] jvnet-nexus-promoted (https://maven.java.net/content/repositories/promoted/, releases=true, snapshots=false),
[ERROR] payara-patched-externals (https://raw.github.com/payara/Payara_PatchedProjects/master, releases=true, snapshots=false),

```

**Comment by Pandrex247** [comment] 2016-02-22 10:13
I've seen this error a few times before; it seems to be caused by the java.net repository, where some of the artefacts required for the build reside.

It normally gets fixed by including this in your MAVEN_OPTS environment variable (or specify it on the cmd line): `-Djavax.net.ssl.trustStore=/path/to/jdk/jre/lib/security/cacerts`

**Comment by mikecroft** [comment] 2016-08-16 08:57
I'm going to assume this is no longer an issue and close this. If the error still exists after adding the option specified above, then feel free to reopen.

**Closed by mikecroft** 2016-08-16 08:57 UTC
Labels: 1:Wait, c:Question, help wanted, requestor unresponsive (1)
