### ISSUE TITLE
Async requests stop receiving timeouts after a while

### ISSUE THREAD

**Issue by meliora** [payara/Payara#3167] opened 2018-09-14 15:22 UTC
# Description #
----------

We have been debugging a problem for a while where Payara stops delivering timeouts to our AsyncContexts. We have a AsyncContext based polling protocol which delivers messages to our clients with 60 second timeout. This protocol has been working flawlessly for a very long time but a while ago, after we set up another server environment with latest Payara 4 server (4.1.181) we have encountered problems. We first noticed that our front servers started acting up with sockets getting stuck in CLOSE_WAIT status between our load balancer and Payara backends. With some research, we noticed that suddenly (with no real explanation), the onTimeout was not called anymore and the requests were not completed. This had the effect of our load balancer (nginx) of giving up on the requests. By some time, the whole front becomes non-responsive as all Payara's threads get locked up. 

The problem seems completely random and is not related to high load or such and the problem might take several days to pop up. We haven't been able to reproduce the problem with any test case, I'm afraid.

As said, the environment with Payara 4.1.2.173 has no problems. The servers with 4.1.2.181 fail. We haven't tested the .174 version in between and our application has some compatibility problems with version 5 so we still haven't upgraded to the latest version.

We are reporting this problem as we happen to know the Payara version which seems to work and a later one which doesn't. It might help developers working on the Async protocol code to get hang of this especially as there has been some AsyncContext related changes (bug fixes) in these versions.

## Expected Outcome

Payara should deliver timeouts to AsyncContexts with timeout set to > 0.

## Current Outcome

Timeouts with AsyncContexts stop happening after a while (days of server uptime in our case) and totally randomly.

## Steps to reproduce (Only for bug reports) 

Cannot reproduce the problem with any sensible test case, sorry.

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full
- **JDK Version**: Oracle 1.8.0_172
- **Operating System**: Linux

**Comment by MattGill98** [comment] 2018-09-20 10:47
Hi @meliora,

Is this reproducible with Payara 5.x? Payara 4.x is no longer maintained in the community stream. I'd also have to press you for a reproducer of some form, is that at all possible?

Kind regards,

Matt

**Comment by meliora** [comment] 2018-10-18 05:38
Sorry, as said, we haven't yet tested and cannot be sure. As said, we have some servers running .173 from 4.x branch and they work as expected. The .181 exhibit issues. We have scheduled the upgrade of our servers by the end of the year.

As a workaround for .181 servers, we currently have our own Thread instantiated at the servlet which tracks the timeouts for AsyncContext's. When the timeout value gets exceeded the Thread manually calls .compete() on the context to clean it up. This workaround logs extensively and by the look of it, the .173 servers do not have this issue.

**Comment by MattGill98** [comment] 2018-10-19 10:00
Hi @meliora,

Since Payara 4.x is no longer in the community stream and we have no reproducer, I'm afraid we can't progress this issue any further. I'll close this issue for now. Feel free to reopen if you manage to reproduce on Payara 5.x.

Kind regards,

Matt

**Closed by MattGill98** 2018-10-19 10:00 UTC
Labels: Test Case Required, Try On Latest Release, requestor unresponsive (1)
