### ISSUE TITLE
Payara 5.191 wrong redirect

### ISSUE THREAD

**Issue by przemek207** [payara/Payara#3949] opened 2019-05-15 07:55 UTC
# Description #
Hello, 

I'm migrating to payara 5.191 from payara 4.181. 
When I enter to the site by the adress https://myaddress.pl:8181/, payara redirect me to the address https://myaddress.pl:8181/PERNSO-web/https:/index.xhtml
On payara4 everything works fine (redirect me to https://myaddress.pl:8181/index.xhtml)
I've set default app in server config, and i've set welcome file in web.xml

There is my config:
web.xml
 
![image](https://user-images.githubusercontent.com/15331955/57757898-c32c3f00-76f6-11e9-9c02-f76e44459ea2.png)

Default web module:
![image](https://user-images.githubusercontent.com/15331955/57757918-ce7f6a80-76f6-11e9-81dc-b18a30dacc40.png)

## Expected Outcome

https://myaddress.pl:8181/index.xhtml

## Current Outcome

https://myaddress.pl:8181/PERNSO-web/https:/index.xhtml

## Steps to reproduce (Only for bug reports) 

1 -**  Deploy the application

2 -**  Set default web module

## Environment ##

- **Payara Version**: 5.191
- **JDK Version**: Oracle 1.8.192 -->
- **Operating System**: Linux / CentOS 7

**Comment by khasunuma** [comment] 2019-06-04 02:24
I can't reproduce. Please provide reproducer sample.

**Comment by OndroMih** [comment] 2020-02-04 14:21
Hi, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us an easy to follow reproducer for the latest version of Payara. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.

**Closed by OndroMih** 2020-02-04 14:21 UTC
Labels: 1:Wait, Test Case Required, c:Misconfiguration, cannot reproduce, requestor unresponsive (1), requestor unresponsive (2)
