### ISSUE TITLE
Editing any existing realm in the webUI "An error has occurred" on save and changes do not save.

### ISSUE THREAD

**Issue by kjjaeger** [payara/Payara#2663] opened 2018-04-23 21:47 UTC
# Description #
----------

If you editing any existing realm in the webUI you will get "An error has occurred" on save
The changes to the realm will not be saved.

## Expected Outcome

Editing a realm and clicking "Save" should save changes to realms in Payara's web console.

## Current Outcome

The message "An error has occured" is displayed in a reddish orange box and changes will not save.

## Steps to reproduce

1 - Start the domain

    ./asadmin start-domain production

2 -Navigate on the left Configurations->server-config->Security->Realms

3 - Select any realm (or create a new realm and select it).

4 - Edit any property (or add a new property) to the realm and hit save.

## Environment ##

- **Payara Version**:  5.181
- **Edition**: Full
- **JDK Version**: Oracle JDK 1.8.0 update 162
- **Operating System**: Mac

**Comment by MeroRai** [comment] 2018-04-24 08:51
Hi @kjjaeger,

We had a very similar issue https://github.com/payara/Payara/pull/2333, which was fixed in 5.181. Can you confrim you are using the latest full release?

**Comment by kjjaeger** [comment] 2018-04-24 15:45
Pretty sure I am current: Payara Server 5.181 #badassfish (build 213)

**Comment by kjjaeger** [comment] 2018-04-24 15:49
The zip file was 145,295,967 bytes

**Comment by kjjaeger** [comment] 2018-04-24 22:32
Here is an example of what the log looks like
[2018-04-24T18:31:11.057-0400] [Payara 5.181] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1524609071057] [levelValue: 1000] [[
  RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/configs/config/server-config/security-service/auth-realm/file2/property'; attrs = '[{"name":"testname","description":"","value":"testvalue"},{"name":"file","value":"${com.sun.aas.instanceRoot}/config/keyfile"},{"name":"jaas-context","value":"fileRealm"}]']]

**Comment by smillidge** [comment] 2018-04-26 11:39
I can't reproduce on latest master on Linux

**Comment by MeroRai** [comment] 2018-04-26 14:56
I can reproduce the issue on Payara 5.181, but as @smillidge said issues doesn't seem to be present on latest master. I am using Ubuntu.

**Comment by smillidge** [comment] 2018-04-26 21:15
Can you try the latest nightly build? https://www.payara.fish/upstream_builds

**Comment by MeroRai** [comment] 2018-04-27 15:53
Works on the nightly build

**Closed** 2018-04-30 16:09 UTC
Labels: cannot reproduce
