### ISSUE TITLE
Request for update javax.el

### ISSUE THREAD

**Issue by okemaster** [payara/Payara#1119] opened 2016-10-03 04:00 UTC
**Cause :** AstValue#setValue Caused NullPointerException
**Reference :** https://java.net/projects/uel/sources/svn/revision/421
Before in GF3.1.2 with javax.el-2.23 still working

Stack Trace

> Caused by: java.lang.NullPointerException
>   at com.sun.el.parser.AstValue.setValue(AstValue.java:247)
>   at com.sun.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:294)
>   at org.jboss.weld.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
>   at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:131)
>   at javax.faces.validator.ValueExpressionAnalyzer.getReference(ValueExpressionAnalyzer.java:68)
>   at javax.faces.validator.BeanValidator.validate(BeanValidator.java:307)
>   at javax.faces.component.UIInput.validateValue(UIInput.java:1164)
>   at javax.faces.component.UIInput.validate(UIInput.java:982)
>   at javax.faces.component.UIInput.executeValidate(UIInput.java:1248)
>   at javax.faces.component.UIInput.processValidators(UIInput.java:712)
>   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
>   at org.primefaces.component.api.UIData.process(UIData.java:334)
>   at org.primefaces.component.api.UIData.processChildren(UIData.java:318)
>   at org.primefaces.component.api.UIData.processPhase(UIData.java:280)
>   at org.primefaces.component.api.UIData.processValidators(UIData.java:254)
>   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
>   at org.primefaces.component.panel.Panel.processValidators(Panel.java:281)
>   at javax.faces.component.UIForm.processValidators(UIForm.java:253)
>   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
>   at org.primefaces.component.panel.Panel.processValidators(Panel.java:281)
>   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
>   at org.primefaces.component.panel.Panel.processValidators(Panel.java:281)
>   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
>   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
>   at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1195)
>   at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76)
>   ... 40 more

**Comment by mulderbaba** [comment] 2016-10-03 10:17
@okemaster can you share your full stacktrace with the nested exceptions if any exists. we're almost at the very latest of the javax.el (3.0.1-b03), so my suspicion is there might be a hidden exception underneath yours.

**Comment by okemaster** [comment] 2016-10-04 09:40
latest version of javax.el in central repo is 3.0.1-b08
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.glassfish%22%20AND%20a%3A%22javax.el%22
** cannot find release note. 
i'm try update to 3.0.1-b08. the result of update can fix problem but i'm don't know root cause.

If i'm free after work, i will provide POC code later.

addition stack trace
> javax.faces.FacesException
> 	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:84)
> 	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
> 	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
> 	at org.apache.myfaces.extensions.cdi.jsf2.impl.listener.phase.CodiLifecycleWrapper.execute(CodiLifecycleWrapper.java:97)
> 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
> 	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1681)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
> 	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:105)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
> 	at xxx.xxx.common.NoCacheFilter.doFilter(NoCacheFilter.java:54)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
> 	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
> 	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
> 	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
> 	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
> 	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
> 	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
> 	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
> 	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
> 	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
> 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
> 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
> 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
> 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
> 	at com.sun.el.parser.AstValue.setValue(AstValue.java:247)
> 	at com.sun.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:294)
> 	at org.jboss.weld.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
> 	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:131)
> 	at javax.faces.validator.ValueExpressionAnalyzer.getReference(ValueExpressionAnalyzer.java:68)
> 	at javax.faces.validator.BeanValidator.validate(BeanValidator.java:307)
> 	at javax.faces.component.UIInput.validateValue(UIInput.java:1164)
> 	at javax.faces.component.UIInput.validate(UIInput.java:982)
> 	at javax.faces.component.UIInput.executeValidate(UIInput.java:1248)
> 	at javax.faces.component.UIInput.processValidators(UIInput.java:712)
> 	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
> 	at org.primefaces.component.api.UIData.process(UIData.java:334)
> 	at org.primefaces.component.api.UIData.processChildren(UIData.java:318)
> 	at org.primefaces.component.api.UIData.processPhase(UIData.java:280)
> 	at org.primefaces.component.api.UIData.processValidators(UIData.java:254)
> 	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
> 	at org.primefaces.component.panel.Panel.processValidators(Panel.java:281)
> 	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
> 	at org.primefaces.component.panel.Panel.processValidators(Panel.java:281)
> 	at javax.faces.component.UIForm.processValidators(UIForm.java:253)
> 	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
> 	at org.primefaces.component.panel.Panel.processValidators(Panel.java:281)
> 	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
> 	at org.primefaces.component.panel.Panel.processValidators(Panel.java:281)
> 	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
> 	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
> 	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1195)
> 	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76)
> 	... 40 more]]
>

**Comment by mulderbaba** [comment] 2016-10-05 11:57
@okemaster, I want to align the versions of API and IMPL for the unified EL so the max. version that we can get up to is: 3.0.1-b04. I can try 3.0.1-b08 with your reproducer by deploying it to custom-built Payara. From what I understood by looking to your the stacktrace is: you're doing a collection binding to PrimeFaces table and one most probably using an input field inside that table. The value bind to the input field gives an error on the bean-validation, most probably defined on your domain model.

**Comment by mulderbaba** [comment] 2016-10-21 08:18
@okemaster if you can provide a reproducer, that'd be great.

**Comment by mikecroft** [comment] 2016-12-02 09:32
Hi @okemaster have you got a reproducer for this?

**Comment by fturizo** [comment] 2017-01-25 00:26
Hello, @okemaster. Since we haven't received word from you since 3 months ago, I'm closing this issue. 

If this issue is still persisting in your environment, feel free to reopen it and provide a reproducible test case to detect and identify this possible bug.

**Closed by fturizo** 2017-01-25 00:26 UTC
Labels: 1:Wait, c:Question, requestor unresponsive (1), requestor unresponsive (2)

**Comment by karthik10001** [comment] 2020-09-13 08:37
We are hitting the exact same issue with build 3.0.1-b11.

We are getting NPE when we pass 'null' as the value. On debugging further we found that it is breaking at line 247 => if (value != null || targetType.isPrimitive()) 

Is there a case when targetType can be null?
