### ISSUE TITLE
Bug Report: Error if number of characters of DAS user admin is 18,19,20,22,... 

### ISSUE THREAD

**Issue by mitchpub** [payara/Payara#6146] opened 2023-01-11 14:52 UTC
### Brief Summary

When you create a DAS with command "asadmin create-domain --savemasterpassword=true DAS-xxxxxxxxxxxx", if the admin user name has 17 or 21 characters, all is ok. 
If you choose a name with 18,19,20 or 22 characters and if you save the login/password with "asadmin login", command like "asadmin stop-domain DAS-xxxxxxxxxxxx" can't connect to DAS.
It crashes with error "Input byte array has wrong 4-byte ending unit" 

### Expected Outcome

create DAS with payara-6.2022.2.zip 

$ asadmin create-domain --savemasterpassword=true DAS-xxxxxxxxxxxx   
Enter admin user name [Enter to accept default "admin" / no password]>das-xxxxxxxxxxxx-admi   <---- 21 characters (or 17)
Enter the admin password [Enter to accept default of no password]> aze
Enter the admin password again>aze
Enter the master password [Enter to accept default password "changeit"]>aze
Enter the master password again>aze
Using default port 4848 for Admin.
Using default port 8080 for HTTP Instance.
Using default port 7676 for JMS.
Using default port 3700 for IIOP.
Using default port 8181 for HTTP_SSL.
Using default port 3820 for IIOP_SSL.
Using default port 3920 for IIOP_MUTUALAUTH.
Using default port 8686 for JMX_ADMIN.
Using default port 6666 for OSGI_SHELL.
Using default port 9009 for JAVA_DEBUGGER.
Using default port 4900 for Hazelcast DAS.
Using default port 5900 for Hazelcast Start.
Distinguished Name of the self-signed X.509 Server Certificate is:
[CN=xxxxxxxxxxxx.yyyyy.fr,OU=Payara,O=Payara Foundation,L=Great Malvern,ST=Worcestershire,C=UK]
Distinguished Name of the self-signed X.509 Server Certificate is:
[CN=xxxxxxxxxxxx.yyyyy.fr-instance,OU=Payara,O=Payara Foundation,L=Great Malvern,ST=Worcestershire,C=UK]
Domain DAS-xxxxxxxxxxxx created.
Domain DAS-xxxxxxxxxxxx admin port is 4848.
Domain DAS-xxxxxxxxxxxx admin user is "das-xxxxxxxxxxxx-admi".
Command create-domain executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin start-domain DAS-xxxxxxxxxxxx
Waiting for DAS-xxxxxxxxxxxx to start .......
Successfully started the domain : DAS-xxxxxxxxxxxx
domain  Location: /home/glassfish/payara6/glassfish/domains/DAS-xxxxxxxxxxxx
Log File: /home/glassfish/payara6/glassfish/domains/DAS-xxxxxxxxxxxx/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin login
Enter admin user name [Enter to accept default]> das-xxxxxxxxxxxx-admi
Enter admin password>
Login information relevant to admin user name [das-xxxxxxxxxxxx-admi] for host [localhost] and admin port [4848] stored at [/home/glassfish/.gfclient/pass] successfully.
Make sure that this file remains protected. Information stored in this file will be used by administration commands to manage associated domain.
Command login executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin stop-domain DAS-xxxxxxxxxxxx
Waiting for the domain to stop .
Command stop-domain executed successfully.

All is OK.

### Current Outcome

create DAS with payara-6.2022.2.zip 

$ asadmin create-domain --savemasterpassword=true DAS-xxxxxxxxxxxx   
Enter admin user name [Enter to accept default "admin" / no password]>das-xxxxxxxxxxxx-adm   <---- 20 characters (or 18,19,22)
Enter the admin password [Enter to accept default of no password]> aze
Enter the admin password again>aze
Enter the master password [Enter to accept default password "changeit"]>aze
Enter the master password again>aze
Using default port 4848 for Admin.
Using default port 8080 for HTTP Instance.
Using default port 7676 for JMS.
Using default port 3700 for IIOP.
Using default port 8181 for HTTP_SSL.
Using default port 3820 for IIOP_SSL.
Using default port 3920 for IIOP_MUTUALAUTH.
Using default port 8686 for JMX_ADMIN.
Using default port 6666 for OSGI_SHELL.
Using default port 9009 for JAVA_DEBUGGER.
Using default port 4900 for Hazelcast DAS.
Using default port 5900 for Hazelcast Start.
Distinguished Name of the self-signed X.509 Server Certificate is:
[CN=xxxxxxxxxxxx.yyyyy.fr,OU=Payara,O=Payara Foundation,L=Great Malvern,ST=Worcestershire,C=UK]
Distinguished Name of the self-signed X.509 Server Certificate is:
[CN=xxxxxxxxxxxx.yyyyy.fr-instance,OU=Payara,O=Payara Foundation,L=Great Malvern,ST=Worcestershire,C=UK]
Domain DAS-xxxxxxxxxxxx created.
Domain DAS-xxxxxxxxxxxx admin port is 4848.
Domain DAS-xxxxxxxxxxxx admin user is "das-xxxxxxxxxxxx-adm".
Command create-domain executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin start-domain DAS-xxxxxxxxxxxx
Waiting for DAS-xxxxxxxxxxxx to start .......
Successfully started the domain : DAS-xxxxxxxxxxxx
domain  Location: /home/glassfish/payara6/glassfish/domains/DAS-xxxxxxxxxxxx
Log File: /home/glassfish/payara6/glassfish/domains/DAS-xxxxxxxxxxxx/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin login
Enter admin user name [Enter to accept default]> das-xxxxxxxxxxxx-adm
Enter admin password>
Login information relevant to admin user name [das-xxxxxxxxxxxx-adm] for host [localhost] and admin port [4848] stored at [/home/glassfish/.gfclient/pass] successfully.
Make sure that this file remains protected. Information stored in this file will be used by administration commands to manage associated domain.
Command login executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin stop-domain DAS-xxxxxxxxxxxx
CLI306: Warning - The server located at /home/glassfish/payara6/glassfish/domains/DAS-Photostomias is not running.
No domains are currently running.
Command stop-domain failed.

server.log  
[2023-01-11T14:42:08.046+0100] [Payara 6.2022.2] [INFO] [NCLS-REST-00003] [jakarta.enterprise.admin.rest] [tid: _ThreadID=95 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1673444528046] [levelValue: 800] [[
  An error occurred while processing the request. Please see the server logs for details.
java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:837)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
        at com.sun.enterprise.admin.util.AdminCallbackHandler.basicAuth(AdminCallbackHandler.java:163)
        at com.sun.enterprise.admin.util.AdminCallbackHandler.<init>(AdminCallbackHandler.java:122)
        at com.sun.enterprise.admin.util.GenericAdminAuthenticator.authenticate(GenericAdminAuthenticator.java:251)
        at com.sun.enterprise.admin.util.GenericAdminAuthenticator.loginAsAdmin(GenericAdminAuthenticator.java:213)
        at com.sun.enterprise.admin.util.GenericAdminAuthenticator.loginAsAdmin(GenericAdminAuthenticator.java:196)
        at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:168)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)
]]

### Reproducer

create DAS with payara-6.2022.2.zip 

$ asadmin create-domain --savemasterpassword=true DAS-xxxxxxxxxxxx   
Enter admin user name [Enter to accept default "admin" / no password]>das-xxxxxxxxxxxx-adm   <---- 20 characters (or 18,19,22)
Enter the admin password [Enter to accept default of no password]> aze
Enter the admin password again>aze
Enter the master password [Enter to accept default password "changeit"]>aze
Enter the master password again>aze
Using default port 4848 for Admin.
Using default port 8080 for HTTP Instance.
Using default port 7676 for JMS.
Using default port 3700 for IIOP.
Using default port 8181 for HTTP_SSL.
Using default port 3820 for IIOP_SSL.
Using default port 3920 for IIOP_MUTUALAUTH.
Using default port 8686 for JMX_ADMIN.
Using default port 6666 for OSGI_SHELL.
Using default port 9009 for JAVA_DEBUGGER.
Using default port 4900 for Hazelcast DAS.
Using default port 5900 for Hazelcast Start.
Distinguished Name of the self-signed X.509 Server Certificate is:
[CN=xxxxxxxxxxxx.yyyyy.fr,OU=Payara,O=Payara Foundation,L=Great Malvern,ST=Worcestershire,C=UK]
Distinguished Name of the self-signed X.509 Server Certificate is:
[CN=xxxxxxxxxxxx.yyyyy.fr-instance,OU=Payara,O=Payara Foundation,L=Great Malvern,ST=Worcestershire,C=UK]
Domain DAS-xxxxxxxxxxxx created.
Domain DAS-xxxxxxxxxxxx admin port is 4848.
Domain DAS-xxxxxxxxxxxx admin user is "das-xxxxxxxxxxxx-adm".
Command create-domain executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin start-domain DAS-xxxxxxxxxxxx
Waiting for DAS-xxxxxxxxxxxx to start .......
Successfully started the domain : DAS-xxxxxxxxxxxx
domain  Location: /home/glassfish/payara6/glassfish/domains/DAS-xxxxxxxxxxxx
Log File: /home/glassfish/payara6/glassfish/domains/DAS-xxxxxxxxxxxx/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin login
Enter admin user name [Enter to accept default]> das-xxxxxxxxxxxx-adm
Enter admin password>
Login information relevant to admin user name [das-xxxxxxxxxxxx-adm] for host [localhost] and admin port [4848] stored at [/home/glassfish/.gfclient/pass] successfully.
Make sure that this file remains protected. Information stored in this file will be used by administration commands to manage associated domain.
Command login executed successfully.
glassfish@xxxxxxxxxxxx:~$ asadmin stop-domain DAS-xxxxxxxxxxxx
CLI306: Warning - The server located at /home/glassfish/payara6/glassfish/domains/DAS-Photostomias is not running.
No domains are currently running.
Command stop-domain failed.

### Operating System

ubuntu 22.04 LTS

### JDK Version

OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment] 2023-01-25 07:40
Hi @mitchpub, 

I have not been able to reproduce this error. I have tried with 18,19,20, and 22 characters and received no errors. This might be related to regional settings, are you using this in a different language or in a different encoding?

Thank you,
Elif

**Comment by mitchpub** [comment] 2023-02-01 10:32
Hi,
I try DAS-xxxxxxxxxxxx / das-xxxxxxxxxxxx-adm with 3 char passwd
I try with an ubuntu 22.04 en_US.UTF-8 and french Keyboard
$ env
SHELL=/bin/bash
PWD=/home/glassfish
LOGNAME=glassfish
HOME=/home/glassfish
LANG=en_US.UTF-8
TERM=xterm
USER=glassfish
SHLVL=1
PATH=/home/glassfish/payara/glassfish/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
MAIL=/var/mail/glassfish
_=/usr/bin/env

I try with an ubuntu 20.04 and it's the same
$ env
SHELL=/bin/bash
LANGUAGE=fr_FR:fr:fr_FR:fr
PWD=/home/glassfish
LOGNAME=glassfish
HOME=/home/glassfish
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm
LESSOPEN=| /usr/bin/lesspipe %s
USER=glassfish
SHLVL=1
PATH=/home/glassfish/payara/glassfish/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
MAIL=/var/mail/glassfish
_=/usr/bin/env

**Comment by fturizo** [comment] 2023-06-21 15:43
@mitchpub, we were not able to reproduce this issue under our local development environments following your instructions, so we'll proceed to close this issue. 

As the problem is more involved with the settings of your local machine we recommend you consider getting a Payara Enterprise subscription so you can get dedicated help if this issue persists on your end.

**Closed by fturizo** 2023-06-21 15:43 UTC
Labels: Type: Bug
