### ISSUE TITLE
Chef integration with Peter Donald's excelent Glassfish cookbook.

### ISSUE THREAD

**Issue by sgreenslade** [payara/Payara#151] opened 2015-01-16 10:37 UTC
https://github.com/realityforge/chef-glassfish

We already use Peter's excelent cookbook for Glassfish. Working with him to include Payara, including automaticaly downloading the latest release would be fantastic.

**Comment by smillidge** [comment] 2015-01-16 21:42
#51 is reference for Chef. 

I'm keen to get involved just need to know what you need us to help with.

**Comment by realityforge** [comment] 2015-01-21 10:23
We have rolled out payara using a version of the chef-glassfish cookbook. The first release of payara is supported with very minor updates to the cookbook. The latest version of Payara actually required a few more changes wrt to how we set up the init/service. 

This is not yet pushed to the public repo but I will try to do that when I get back from my break.

**Comment by realityforge** [comment] 2015-01-21 10:24
In terms of one thing I would like to see changed in the chef-glassfish cookbook is to setup GlassFish clustering through it. Currently we manage our own session state and cluster manually between independent DAS+instances. We have not yet assessed what it would take to get decent clustering support into the chef-glassfish cookbook

**Comment by realityforge** [comment] 2015-04-20 21:29
Can we merge this issue into #51 or vice versa and close the other issue so we can have one place to track where this is at.

**Comment by smillidge** [comment] 2015-04-21 07:40
Duplicate of #51

**Closed by smillidge** 2015-04-21 07:40 UTC
Labels: duplicate, enhancement
