### ISSUE TITLE
Failure deploying large war

### ISSUE THREAD

**Issue by crazed-developer** [payara/Payara#3540] opened 2018-12-29 09:02 UTC
# Description #
----------

I created an application needing to detect text encoding. I opted to use Apache Tika for this.

This worked fine on my development machine, where I deployed exploded wars.

However Tika is huge, and when deploying (the war) on the production server it did not work. And little to none debug information available. I spent many many hours on this. And finally figured that maybe the size had something to do with it. (war being just below 100mb)

Only clue was this: 
[2018-12-29T08:19:18.782+0100] [Payara 5.184] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=71 _ThreadName=payara-executor-service-task] [timeMillis: 1546067958782] [levelValue: 1000] [[
  Exception while parsing file file:/opt/payara5-184/glassfish/domains/production/applications/xxxx-broker-0.3/
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@5c935382 rejected from java.util.concurrent.ThreadPoolExecutor@3cf20d1[Running, pool size = 20, active threads = 20, queued tasks = 30, completed tasks = 217]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.glassfish.hk2.classmodel.reflect.Parser.parse(Parser.java:293)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleJar(ReadableArchiveScannerAdapter.java:197)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:131)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:345)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:68)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:304)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]

## Expected Outcome

I expected the war to deploy properly

## Current Outcome

I got it to deploy by using this maven dependency instead of using Tika:
<dependency>
    <groupId>com.ibm.icu</groupId>
    <artifactId>icu4j</artifactId>
    <version>57.1</version>
</dependency>

Which made the war about 16mb in size, instead of 98mb

## Steps to reproduce (Only for bug reports) 

<!-- 

I reproduced the error simply by choosing to deploy as a war and not as exploded on the development machine. This created the exact same problem as on the server.

## Context (Optional)

I tried to include Apache Tika in my project. It proved to be a very big dependency. I ended up using icu4j instead. Which worked without any code changes. As all I need is encoding detection.

war is now very much smaller, and deploys correctly.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 8 u191 OpenJDK
- **Operating System**: Linux + Mac
- **Database**: MySQL

**Comment by svendiedrichsen** [comment] 2018-12-30 13:15
This is duplicate of  #3495

**Comment by lprimak** [comment] 2018-12-30 22:30
fixed in trunk

**Closed by lprimak** 2018-12-30 22:30 UTC
