### ISSUE TITLE
PROPOSAL: Add payara.xml as suppliment to application.xml /CUSTCOM-85

### ISSUE THREAD

**Issue by johnmanko** [payara/Payara#2337] opened 2018-01-29 17:36 UTC
# Add payara.xml as suppliment to application.xml #
----------

The Servlet 3.0 specification (JSR 315) has a slight oversight when it comes to web fragments (web-fragment.xml).  According to the spec (pp 65-66):

> If a framework is packaged as a jar file and has metadata information in the form of deployment descriptor then the `web-fragment.xml` descriptor must be in the `META-INF/` directory of the jar file.
> 
> If a framework wants its `META-INF/web-fragment.xml` honored in such a way that it augments a web application's `web.xml`, the framework must be bundled within the web application's `WEB-INF/lib`  directory. In order for any other types of resources (e.g., class files) of the framework to be made available to a web application, it is sufficient for the framework to be present anywhere in the classloader delegation chain of the web application. In other words, only JAR files bundled in a web application's `WEB-INF/lib` directory, but not those higher up in the class loading delegation chain, need to be scanned for `web-fragment.xml`.

This is a problem when a framework (that could augment `web.xml`) is packaged with an EAR in `<EAR>/lib` - it's `web-fragment.xml` will be ignored.  One example is a security framework that needs to exist at the application level but have realm information defined in `web-fragment.xml`.

## Expected Outcome

The following could be a proposed Payara-specific solution (which will hopefully could get adopted in a future Servlet spec).

```
<?xml version="1.0" encoding="UTF-8"?>
<payara xmlns="http://payara.fish/xml/ns/javaee" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://payara.fish/xml/ns/javaee http://payara.fish/xml/ns/javaee/application_7.xsd" version="7">

  <application>
    <module>
      <web>
        <web-uri>web.war</web-uri>
        <fragment>lib/security-framework.jar</fragment>
      </web>
    </module>
  </application>

</payara>
```

`fragment` would be either a `jar` (meeting fragment packaging rules) or stand-alone `web-fragment.xml` file.

Payara would then parse and apply `<EAR>/lib/security-framework.jar/META-INF/web-fragment.xml` as if `security-framework.jar` existed in `<EAR>/web.war/WEB-INF/lib`.

## Current Outcome

There is no spec approved way for adding a `web-fragment.xml` library at an Enterprise Application level.

**Comment by rdebusscher** [comment] 2019-12-16 14:58
Tracked by `CUSTCOM-85`.

**Comment by AlanRoth** [comment] 2020-11-11 11:03
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:03 UTC
Labels: enhancement, status:accepted
