### ISSUE TITLE
Admin console: missing asadmin commands at virtual server assignment

### ISSUE THREAD

**Issue by z-mathe** [payara/Payara#1697] opened 2017-06-20 20:00 UTC
Description #
----------

After deploying an app (web or ear) to the frontend cluster (with 2 nodes, 1 instance per node, many custom virtual servers) with admin web console, the application assigned to the all virtual server in the background (in clustered environment, on the "Deploy Applications or Modules" form there is no virtual server dropdown, only the server target selectable, I have no idea why, because after deploy I can manage the virtual servers too, but in the deploy time no).
By admin guide: "If you deploy a web application and don't specify any assigned virtual servers, the web application is assigned to all currently defined virtual servers". Ok, no problem, I will assing to the expected virtual server(s) after deploy.

```
domain.xml (after deploy):

<domain application-root="${com.sun.aas.instanceRoot}/applications" version="235" log-root="${com.sun.aas.instanceRoot}/logs">
  ...
  <servers>
    <server config-ref="server-config" name="server">
    ...
    </server>
    <server config-ref="frontend-config" node-ref="node1" name="instance1">
    ...
      <application-ref ref="app-name" virtual-servers="server,virt1,virt2,virt3"></application-ref>
    ...
    </server>
    <server config-ref="frontend-config" node-ref="node2" name="instance2">
    ...
      <application-ref ref="app-name" virtual-servers="server,virt1,virt2,virt3"></application-ref>
    ...
    </server>
    ...
  </servers>
  ...
  <clusters>
    <cluster gms-multicast-port="8041" config-ref="frontend-config" name="frontend-cluster" gms-bind-interface-address="${GMS-BIND-INTERFACE-ADDRESS-frontend}" gms-multicast-address="228.9.99.37">
      ...
      <application-ref ref="app-name" virtual-servers="server,virt1,virt2,virt3"></application-ref>
      ...
      <server-ref ref="instance1"></server-ref>
      <server-ref ref="instance2"></server-ref>
    </cluster>
  </clusters>
</domain>
```
After deploy, I open the application and goto to the "Target" tab, and click to "Manage Virtual Servers" link and assign only the virtual server "virt1" and click on the "Save" button.

## Expected Outcome

In the domain.xml all levels (the one cluster level, and the two server intance level) of assignments modified at same time (in all 3 places in the "virtual-servers" xml attribute remains only one server, named "virt1").

## Current Outcome

Only the cluster level modified. I need to modify the two server instance assigment in the xml by hand, and restart nodes. I will point out that this behavior already exists in Glassfish v3 too, but so far we do not deal with the virtual server assignments (we used it with the whole assignments). But in Payara versions (I tested in 171 and 172 too), if I left the all currently assigned virtual servers, then I'll get it #1133 at all JSF client-server communications (too many log rows).
I have no problem with #1133 warning (if I manually assign all applications to the exact one virtual server), the more so with the above wrong behaviour (that exists for many years, verisons to version). Can you fix it?

```
domain.xml (after assignment modify on the console):

<domain application-root="${com.sun.aas.instanceRoot}/applications" version="235" log-root="${com.sun.aas.instanceRoot}/logs">
  ...
  <servers>
    <server config-ref="server-config" name="server">
    ...
    </server>
    <server config-ref="frontend-config" node-ref="node1" name="instance1">
    ...
      <application-ref ref="app-name" virtual-servers="server,virt1,virt2,virt3"></application-ref>
    ...
    </server>
    <server config-ref="frontend-config" node-ref="node2" name="instance2">
    ...
      <application-ref ref="app-name" virtual-servers="server,virt1,virt2,virt3"></application-ref>
    ...
    </server>
    ...
  </servers>
  ...
  <clusters>
    <cluster gms-multicast-port="8041" config-ref="frontend-config" name="frontend-cluster" gms-bind-interface-address="${GMS-BIND-INTERFACE-ADDRESS-frontend}" gms-multicast-address="228.9.99.37">
      ...
      <application-ref ref="app-name" virtual-servers="virt1"></application-ref>
      ...
      <server-ref ref="instance1"></server-ref>
      <server-ref ref="instance2"></server-ref>
    </cluster>
  </clusters>
</domain>
```

## Environment ##

- **Payara Version**: All (originated from Glassfish versions)
- **Edition**: Full
- **JDK Version**: 8 u131 - Oracle
- **Operating System**: Windows

**Comment by z-mathe** [comment] 2017-06-20 20:06
A little workaround: after correct manually the domain xml, we try to use redeploy method instead of undeploy+deploy, because redeploy preserves the virtual server assingments. But sometimes it is necessary to undeploy the application (e.g. after an unsuccessfully redeploy, duplicate key, etc. problems), and then it comes the above case.

**Comment by z-mathe** [comment] 2017-06-21 12:01
The Asadmin Recorder writes only this:
set clusters.cluster.backend.application-ref.app-name.virtual-servers=virt1

But not necessary manually modify the domain.xml and restart server, enough to execute the following.

The missing commands, what the console does not do:
```
asadmin> set servers.server.instance1.application-ref.app-name.virtual-servers=virt1
perseus-instance:
servers.server.instance1.application-ref.app-name.virtual-servers=virt1

servers.server.instance1.application-ref.app-name.virtual-servers=virt1
Command set executed successfully.
asadmin> set servers.server.instance2.application-ref.app-name.virtual-servers=virt1
theseus-instance:
servers.server.instance2.application-ref.app-name.virtual-servers=virt1

servers.server.instance2.application-ref.app-name.virtual-servers=intranet
Command set executed successfully.
asadmin>
```
Can you modify the virtual server assignment process, to include the missing command per cluster instances too?

**Comment by mikecroft** [comment] 2017-06-26 10:15
Based on the steps you outlined, this behaviour seems correct. If you use the "Manage Virtual Servers" link under Application Targets, you are modifying the virtual servers _**for that target.**_ In your example above, you have deployed your application to multiple targets, so you will need to modify which virtual server you want to use for each target individually.

Even though you have virtual servers named "virt1", "virt2" etc for both targets, these are completely separate entities and not related in any way.

What the console is doing here is correct.

**Comment by z-mathe** [comment] 2017-06-26 12:29
Hi Mike,

How to configure a good cluster with 2 nodes, if it is a "misconfiguration"?
On the server target (on which the admin console runs) there is no application deployed (except for __admingui), this is called DAS (including the task of distributing the configuration between the nodes).
That's not exactly true, that I deploy my application to multiple target (the only one target, to which I am deploying is the **cluster** target, the default **server** target was left out from the dropdown list in the deploy process).
When deploying the application to the cluster target, I have no way to select virtual servers, but in the background, the cluster assign all virtual servers to my application and brodcasts (copy) the application and the configuration changes to the 2 nodes. By contrast if I change my virtual server assignment on the same cluster target, the changes will not be brodcasted to 2 nodes (I have to change assignments with asadmin command).

If that's the way it is, not even worth using the admin console to change the deployed application virtual server assignments, it's simpler to issue 3 asadmin commands by command line:
```
set clusters.cluster.backend.application-ref.app-name.virtual-servers=virt1
set servers.server.instance1.application-ref.app-name.virtual-servers=virt1
set servers.server.instance2.application-ref.app-name.virtual-servers=virt1
```
Do you have any suggestions on how to do this better from the admin console?

Thank you.

**Comment by mikecroft** [comment] 2017-06-26 12:35
Sorry, yes, I misread your initial overview! I'll take another look

**Comment by mikecroft** [comment] 2017-06-27 08:36
Yep, confirmed @z-mathe, your summary is correct. I created `PAYARA-1797` to track the issue.

**Comment by smillidge** [comment] 2017-11-05 20:51
Closed by #2086

**Comment by z-mathe** [comment] 2018-04-02 20:26
Hi @mikecroft,
Unfortunately, nothing has changed in the 4.174, according to the original scenario, everything works in the same way.
We have now switched from v172 to v174 (the v173 was still used for a short time with the v171 Corba jars because a weird thread-pooling error came in again).

I need to run manually this little batch file (VirtualServerRepair.bat) after the deploy with the default localhost:4848 (for the backend cluster and the two instances):
```
@echo off

if [%1]==[] goto usage
if [%2]==[] goto usage

call asadmin set clusters.cluster.backend.application-ref.%1.virtual-servers=%2
call asadmin set servers.server.instance1.application-ref.%1.virtual-servers=%2
call asadmin set servers.server.instance2.application-ref.%1.virtual-servers=%2

goto end

:usage
@echo Usage: %0 ^<AppName^> %1 ^<VirtualServerName^>
exit /B 1

:end
```

**Comment by z-mathe** [comment] 2018-04-02 21:02
What should I do now, should I open a new ticket that I refer to this closed?

**Comment by MattGill98** [comment] 2018-04-10 14:10
Hi @z-mathe,

I see what you mean with the propogation. This seems to have been an oversight on my behalf in the implementation. My understanding of the problem is that it works for the `domain.xml` used by the DAS, but not by other nodes. Is this correct? If to, I believe all that would be needed to make the change dynamic would be to make the command replicate on the selected instances. I've created issue `PAYARA-2674` which should address this problem.

Hope this helps,

Matt

**Comment by z-mathe** [comment] 2018-04-10 14:29
Hi @MattGill98,

It would be exactly this (with dynamic propagation without restarting the nodes, like my previous manual asadmin commands on live environments). Sorry for the late feedback (the testing of new versions takes a long time). Thanks also to @mikecroft for speedy involvement...

Thanks,
Zoltan

**Closed** 2018-04-28 15:27 UTC
Labels: 2:WithDev, c:ConfirmedBug
