### ISSUE TITLE
Connection closes with error 'err_connection_closed' in payara-5.2021.1 with using HTTPS protocal and unable to get the response from server / FISH-1515

### ISSUE THREAD

**Issue by sameencse** [payara/Payara#5268] opened 2021-05-25 11:06 UTC
# Description #
----------

Recently we upgraded the payara server from 5.194 to 5.2021.1 without modifying anything in domain.xml, and observed few of API calls which will take some time to process before returning response are abruptly closed with 'ERR_CONNECTION_CLOSED'  and we are using the HTTPS protocol.
Interestingly this issue is not happening with HTTP protocol, seems to be working

## Expected Outcome ##

Https request should complete without any error message or it should process the request and server should return the response

## Current Outcome ##

After the payara upgrade from  5.194 to 5.2021.1 , we notice in our application most of the API calls with HTTPS (the request which takes more than 45 seconds to send back the response to client are breaking with 'ERR_CONNECTION_CLOSED' in dev console) and causing the application to stop abruptly.
And after disabling the HTTP/2, the application seems to be working fine without any error.

## Environment ##

- **Distribution**: Full payara/ payara-5.2021.1
- **JDK Version**: zulu11.45.27-ca-jdk11.0.10-win_x64 
- **Operating System**:  Windows 10

**Comment by shub8968** [comment] 2021-06-06 10:01
Hi @sameencse,

Would you be able to provide the reproducer?

**Comment by sameencse** [comment] 2021-06-10 03:45
Hi @shub8968 

- With payara-5.2021.1 default setting has HTTP/2 Enabled on both HTTP & HTTPS listener
- Deploy the Application 
- Access the application with HTTPS port
- Let say if any action in application takes some time to perform( for example in my case, there is a process which takes time to generate xml files) will be result in CONNECTION error out in dev console 'ERR_CONNECTION_CLOSED'
- The same is process will work fine if its get access with  HTTP port.

PS:: the similar bug is already logged here [https://github.com/payara/Payara/issues/2625] which mentioned the issue is fixed in 5.2020.2 and 5.20 but it doesn't seems to be

**Comment by lprimak** [comment] 2021-06-11 20:09
There is a little confusion here.
HTTP/2 **push** (still) has issues in Grizzly and is disabled by default in Payara.

HTTP/2 should work without issues with **push** disabled. Please make sure that push is disabled with the latest version of Payara. There have been some Grizzly fixes in since 2021.1

If that doesn't work, and is confirmed as such, then this issue is indeed valid

**Comment by sameencse** [comment] 2021-06-12 18:51
@lprimak  see below image
![http2](https://user-images.githubusercontent.com/9302653/121786351-fe064700-cbdc-11eb-9ef2-ac1591fa2237.PNG)
 I can confirm that HTTP/2 push is disabled and HTTP/2 without push is enabled with that setting, it is failing
could you please confirm is that be a bug?

**Comment by shub8968** [comment] 2021-06-15 10:35
Hi @sameencse 

Would you be able to provide the sample application you are using in order to test the issue?

**Comment by sameencse** [comment] 2021-06-15 16:11
@shub8968  Nope, i can't
but its easily reproducible 

-With payara-5.2021.1 default setting has HTTP/2 Enabled on both HTTP & HTTPS listener
- Deploy the Application
- Access the application with HTTPS port
- Let say if any action in application takes some time to perform( for example in my case, there is a process which takes time to generate/download xml files and huge in size) will be result in CONNECTION error out in dev console 'ERR_CONNECTION_CLOSED'
- The same process works fine if its get access with HTTP port.

PS:: the similar bug is already logged here [https://github.com//issues/2625] which mentioned the issue is fixed in 5.2020.2 and 5.20 but it doesn't seems to be
i have provided sufficient data and steps to reproduce, and also pointing out that the similar issue is already reported in this ticket [https://github.com//issues/2625]

**Comment by shub8968** [comment] 2021-06-18 11:19
Hi @sameencse, I am able to reproduce this issue. I have raised an internal issue with JIRA `FISH-1515`. Thanks

**Comment by sameencse** [comment] 2021-06-19 17:46
Thanks @shub8968  for confirming this as bug,

- Not sure disabling HTTP/2 will cause any performance/slowness ? 
- And also do you have any deadline/release date for FISH-1515 fix.

**Comment by hberton** [comment] 2021-09-24 14:27
is there any prediction or way to get around the problem?

**Comment by ricovanrensburg** [comment] 2021-09-28 06:22
We also encountered this issue, service went down often. We un-ticked https/2 and running stable now. Payara 5 version 2021.1. Also interested in a fix and by when? Thanks

**Comment by JamesHillyard** [comment] 2022-10-04 10:00
Hi all,

This issue has been resolved in the latest version of Payara Community, 5.2022.3. Please upgrade your environments to resolve this issue.

Thanks,
James

**Closed by JamesHillyard** 2022-10-04 10:00 UTC
Labels: Status: Accepted, Type: Bug

**Comment by JamesHillyard** [comment] 2025-02-19 10:21
Hi @marcreichman-pfi, I no longer work within the support team at Payara but I would recommend raising a new issue, provide as many details as you can about the problem, your environment and link it to this issue. The support team will then pick up that new issue and give you a more thorough investigation.

Thanks,
James
