### ISSUE TITLE
Cannot open admin console in case of Payara path includes symbolic link /CUSTCOM-89

### ISSUE THREAD

**Issue by blono** [payara/Payara#2591] opened 2018-04-02 08:10 UTC
# Description #
----------

Cannot start server and cannot open admin console in case of Payara installation path includes symbolic link.

## Current Outcome

The following exceptions will occure:
<pre>
java.lang.ClassNotFoundException: org.glassfish.admin.rest.resources.generatedASM.DomainResource not found by org.glassfish.main.admin.rest-service [317]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.glassfish.admin.rest.adapter.RestManagementResourceProvider.getResourceClasses(RestManagementResourceProvider.java:110)
	at org.glassfish.admin.rest.adapter.RestAdapter.exposeContext(RestAdapter.java:300)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:178)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]

[2018-03-30T19:12:56.120+0900] [Payara 5.182-SNAPSHOT] [情報] [NCLS-REST-00003] [javax.enterprise.admin.rest] [tid: _ThreadID=152 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1522404776120] [levelValue: 800] [[
  An error occurred while processing the request. Please see the server logs for details.
java.lang.IllegalArgumentException: Registered component class cannot be null.
	at org.glassfish.jersey.model.internal.CommonConfig.checkComponentClassNotNull(CommonConfig.java:569)
	at org.glassfish.jersey.model.internal.CommonConfig.register(CommonConfig.java:407)
	at org.glassfish.jersey.server.ResourceConfig.register(ResourceConfig.java:422)
	at org.glassfish.jersey.server.ResourceConfig.registerClasses(ResourceConfig.java:498)
	at org.glassfish.jersey.server.ResourceConfig.<init>(ResourceConfig.java:364)
	at org.glassfish.admin.rest.adapter.AbstractRestResourceProvider.getResourceConfig(AbstractRestResourceProvider.java:106)
	at org.glassfish.admin.rest.adapter.RestManagementResourceProvider.getResourceConfig(RestManagementResourceProvider.java:96)
	at org.glassfish.admin.rest.adapter.RestAdapter.exposeContext(RestAdapter.java:310)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:178)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]

[2018-04-02T16:54:18.135+0900] [Payara 5.182-SNAPSHOT] [警告] [] [javax.enterprise.web.core] [tid: _ThreadID=77 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1522655658135] [levelValue: 900] [[
  Servlet.service() for servlet FacesServlet threw exception
java.lang.NullPointerException
	at com.sun.jsftemplating.layout.xml.XMLLayoutDefinitionManager.getBaseURI(XMLLayoutDefinitionManager.java:247)
	at com.sun.jsftemplating.layout.xml.XMLLayoutDefinitionManager.getLayoutDefinition(XMLLayoutDefinitionManager.java:183)
	at com.sun.jsftemplating.layout.LayoutDefinitionManager.getLayoutDefinition(LayoutDefinitionManager.java:152)
	at com.sun.jsftemplating.component.TemplateComponentHelper.getLayoutDefinition(TemplateComponentHelper.java:177)
	at com.sun.jsftemplating.component.TemplateComponentBase.getLayoutDefinition(TemplateComponentBase.java:93)
	at com.sun.jsftemplating.layout.descriptors.LayoutComponent.getFacetName(LayoutComponent.java:435)
	at com.sun.jsftemplating.component.factory.ComponentFactoryBase.addChild(ComponentFactoryBase.java:208)
	at com.sun.jsftemplating.component.factory.ComponentFactoryBase.createComponent(ComponentFactoryBase.java:259)
	at com.sun.jsftemplating.component.factory.basic.StaticTextFactory.create(StaticTextFactory.java:58)
	at com.sun.jsftemplating.component.ComponentUtil.createChildComponent(ComponentUtil.java:416)
	at com.sun.jsftemplating.layout.descriptors.LayoutComponent.getChild(LayoutComponent.java:291)
	at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:557)
	at org.glassfish.admingui.common.handlers.PluginHandlers.includeIntegrationPoint(PluginHandlers.java:449)
	at org.glassfish.admingui.common.handlers.PluginHandlers.includeFirstIntegrationPoint(PluginHandlers.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jsftemplating.layout.descriptors.handler.Handler.invoke(Handler.java:442)
	at com.sun.jsftemplating.layout.descriptors.LayoutElementBase.dispatchHandlers(LayoutElementBase.java:420)
	at com.sun.jsftemplating.layout.descriptors.LayoutElementBase.dispatchHandlers(LayoutElementBase.java:394)
	at com.sun.jsftemplating.layout.descriptors.LayoutComponent.afterCreate(LayoutComponent.java:363)
	at com.sun.jsftemplating.layout.descriptors.LayoutComponent.getChild(LayoutComponent.java:294)
	at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:557)
	at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:590)
	at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:590)
	at com.sun.jsftemplating.layout.LayoutViewHandler.createView(LayoutViewHandler.java:255)
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:261)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:133)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1622)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:824)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:688)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:525)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:496)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:378)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:325)
	at org.glassfish.admingui.common.security.AdminConsoleAuthModule.saveRequestAndForwardToLogin(AdminConsoleAuthModule.java:334)
	at org.glassfish.admingui.common.security.AdminConsoleAuthModule.validateRequest(AdminConsoleAuthModule.java:197)
	at com.sun.enterprise.security.jmac.config.GFServerConfigProvider$GFServerAuthContext.validateRequest(GFServerConfigProvider.java:999)
	at com.sun.web.security.RealmAdapter.validate(RealmAdapter.java:1725)
	at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:666)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:579)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:622)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:598)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]

[2018-04-02T16:54:18.137+0900] [Payara 5.182-SNAPSHOT] [警告] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=77 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1522655658137] [levelValue: 900] [[
  JMAC: http msg authentication fail
javax.security.auth.message.AuthException
	at org.glassfish.admingui.common.security.AdminConsoleAuthModule.saveRequestAndForwardToLogin(AdminConsoleAuthModule.java:338)
	at org.glassfish.admingui.common.security.AdminConsoleAuthModule.validateRequest(AdminConsoleAuthModule.java:197)
	at com.sun.enterprise.security.jmac.config.GFServerConfigProvider$GFServerAuthContext.validateRequest(GFServerConfigProvider.java:999)
	at com.sun.web.security.RealmAdapter.validate(RealmAdapter.java:1725)
	at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:666)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:579)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:622)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:598)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: java.lang.reflect.InvocationTargetException while attempting to process a 'afterCreate' event for 'event7'.
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:749)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1622)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:824)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:688)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:525)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:496)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:378)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:325)
	at org.glassfish.admingui.common.security.AdminConsoleAuthModule.saveRequestAndForwardToLogin(AdminConsoleAuthModule.java:334)
	... 30 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException while attempting to process a 'afterCreate' event for 'event7'.
	at com.sun.jsftemplating.layout.descriptors.LayoutElementBase.dispatchHandlers(LayoutElementBase.java:425)
	at com.sun.jsftemplating.layout.descriptors.LayoutElementBase.dispatchHandlers(LayoutElementBase.java:394)
	at com.sun.jsftemplating.layout.descriptors.LayoutComponent.afterCreate(LayoutComponent.java:363)
	at com.sun.jsftemplating.layout.descriptors.LayoutComponent.getChild(LayoutComponent.java:294)
	at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:557)
	at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:590)
	at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:590)
	at com.sun.jsftemplating.layout.LayoutViewHandler.createView(LayoutViewHandler.java:255)
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:261)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:133)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731)
	... 39 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jsftemplating.layout.descriptors.handler.Handler.invoke(Handler.java:442)
	at com.sun.jsftemplating.layout.descriptors.LayoutElementBase.dispatchHandlers(LayoutElementBase.java:420)
	... 51 more
Caused by: java.lang.NullPointerException
	at com.sun.jsftemplating.layout.xml.XMLLayoutDefinitionManager.getBaseURI(XMLLayoutDefinitionManager.java:247)
	at com.sun.jsftemplating.layout.xml.XMLLayoutDefinitionManager.getLayoutDefinition(XMLLayoutDefinitionManager.java:183)
	at com.sun.jsftemplating.layout.LayoutDefinitionManager.getLayoutDefinition(LayoutDefinitionManager.java:152)
	at com.sun.jsftemplating.component.TemplateComponentHelper.getLayoutDefinition(TemplateComponentHelper.java:177)
	at com.sun.jsftemplating.component.TemplateComponentBase.getLayoutDefinition(TemplateComponentBase.java:93)
	at com.sun.jsftemplating.layout.descriptors.LayoutComponent.getFacetName(LayoutComponent.java:435)
	at com.sun.jsftemplating.component.factory.ComponentFactoryBase.addChild(ComponentFactoryBase.java:208)
	at com.sun.jsftemplating.component.factory.ComponentFactoryBase.createComponent(ComponentFactoryBase.java:259)
	at com.sun.jsftemplating.component.factory.basic.StaticTextFactory.create(StaticTextFactory.java:58)
	at com.sun.jsftemplating.component.ComponentUtil.createChildComponent(ComponentUtil.java:416)
	at com.sun.jsftemplating.layout.descriptors.LayoutComponent.getChild(LayoutComponent.java:291)
	at com.sun.jsftemplating.layout.LayoutViewHandler.buildUIComponentTree(LayoutViewHandler.java:557)
	at org.glassfish.admingui.common.handlers.PluginHandlers.includeIntegrationPoint(PluginHandlers.java:449)
	at org.glassfish.admingui.common.handlers.PluginHandlers.includeFirstIntegrationPoint(PluginHandlers.java:247)
	... 57 more
]]
</pre>

## Steps to reproduce (Only for bug reports) 

1. Create directory C:\payara
2. Download Payara Server 5.181 Full.
3. Unzip payara-5.181.zip to C:\payara\payara5
4. Create symbolic link as follows:
mklink /D C:\payara\payara C:\payara\payara5
A symbolic link from C:\payara\payara to C:\payara\payara5 will be created.
5. Start Payara Server as follows:
C:\payara\payara\glassfish\bin\startserv.bat
(not C:\payara\payara5\glassfish\bin\startserv.bat)
6. Go to http://localhost:4848

## Context (Optional)

This problem is NOT occure in case of using payara-5.Beta2.

## Environment ##

- **Payara Version**: 5.181 or later(5.182-SNAPSHOT)
- **Edition**: Full
- **JDK Version**: Oracle JDK 1.8.162
- **Operating System**: Windows 7 64-bit Professional
- **Database**:

**Comment by bradvido** [comment] 2018-07-14 17:12
I have the same exact issue using Payara 5.182 on Windows 10.  I have a symbolic directory link pointing to the actual Payara installation, and the admin console fails to load with the same error.

This did not occur in Payara41 (I recently upgraded) using symbolic links

**Comment by bradvido** [comment] 2019-02-08 01:10
@smillidge Any thoughts on this? 
I've successfully reproduced this same exact issue multiple times on different combinations of Payara 5.181 to 5.184  The problem doesn't exist in Payara 4, and according to the OP, doesn't exist in payara-5.Beta2.

**Comment by khasunuma** [comment] 2019-02-26 05:29
As I confirmed, the problem doesn't exist in Payara 4.181 or earlier, but exist in Payara 5.181 or later. (and Payara 4.1.2.182 or later, that is customers only version.)

**Comment by khasunuma** [comment] 2019-02-26 05:47
I reproduced this problem using Payara 5.184 (latest) on Windows 10 build 17763. (It also exists in Payara 4.182 or later that is costomers only build.)

**Comment by khasunuma** [comment] 2019-02-26 06:08
I raised internal JIRA issue PAYARA-3523.

**Comment by rdebusscher** [comment] 2019-12-17 08:59
Tracked by `CUSTCOM-89`

**Comment by andresku** [comment] 2020-06-22 15:07
The problem still exists in the newest version payara-5.2020.2.

**Comment by bradvido** [comment] 2020-06-22 15:09
Confirmed, yes it does. It's a huge PITA for us becausae we use symbolic links everywhere to ease administration and updates

**Comment by AlanRoth** [comment] 2020-11-11 11:06
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:06 UTC
Labels: reproducible, status:accepted
