### ISSUE TITLE
Have a problem add new JVM Option

### ISSUE THREAD

**Issue by fcmattar** [payara/Payara#4660] opened 2020-05-08 18:48 UTC
I am trying to set two new jvm options on server-config by the domain admin console gui.
When I set it, this error is throw:

> An error has occurredJVM option -Xbootclasspath/a:${com.sun.aas.installRoot}/lib/grizzly-npn-api.jar already exists in the configuration. |  
> -- | --
## Environment ##

Payara Server  5.201 #badassfish (build 512)|#]
- **Edition**: Full
- **JDK Version**: Oracle JDK 11
- **Operating System**: Windows
- **Database**:  PostgreSQL but it seems irrelevant

**Comment by smillidge** [comment] 2020-05-09 11:55
Duplicate of #4578

**Closed by smillidge** 2020-05-09 11:55 UTC
