### ISSUE TITLE
HTTP DELETE containing payload or form data results in response 400 'Bad request'

### ISSUE THREAD

**Issue by riskovec** [payara/Payara#4961] opened 2020-10-21 11:09 UTC
I tried to set in payara asadmin
set configs.config.server-config.network-config.protocols.protocol.http-listener-1.http.allow-payload-for-undefined-http-methods=true
but it didn't helped.

When I set this in Payara 5.2020.5 it works fine, but I need older version of payara...

## Environment ##
Payara Server 4.1.2.174 #badassfish (build 192)

**Comment by AlanRoth** [comment] 2020-11-02 15:24
Hi @riskovec, if you require support with older versions of Payara you will have to contact our sales team. If you cannot reproduce this issue with our latest version I will have to close this issue. We'll reopen the issue if you are able to provide us with an easy to follow reproducer for the latest version of Payara.

**Closed** 2020-11-02 15:24 UTC
Labels: status:reproducer-needed
