### ISSUE TITLE
Bug Report:  Web session clustering not working in Data Grid

### ISSUE THREAD

**Issue by mirozitnansky** [payara/Payara#5332] opened 2021-07-06 09:23 UTC
# Description #

Web session clustering (via Hazelcast) does not work when there are third-party libraries in WEB-INF/lib directory.
Same issue as https://github.com/payara/Payara/issues/1689 still present in current Payara server version.
We've used examples provided before in this bug report related to this issue https://github.com/payara/Payara/issues/1676#issuecomment-309268286
attaching wars based on these [CrudView.zip](https://github.com/payara/Payara/files/6768896/CrudView.zip)

once we added external lib in to WAR, WEB-INF\lib\primefaces-10.0.0.jar , server generates new JSESSIONID for each request over balancer
once lib was removed, server holds JSESSIONID between requests and starts to generate new cookie JSESSIONIDVERSION

to test, deploy example wars, with availability
CrudView3.war doesn't include primefaces-10.0.0.jar - availability works
CrudView4.war does include primefaces-10.0.0.jar - availability is not working

I tested it on "real" balanced environment, but can be tested just as easily on localhost-domain1 > 2 instances (1 deployment group); deployed without balancer
and switching TCP ports between requests - on CrudView3 JSESSIONID is kept between calls
C:\curl\curl.exe http://localhost:28080/CrudView/index2.xhtml -I -c cookie -b cookie -v
C:\curl\curl.exe http://localhost:28081/CrudView/index2.xhtml -I -c cookie -b cookie -v

## Environment ##

- **Distribution**: Server Full Profile 5.2021.4
- **JDK Version**:  v11 u10 - ZuluJDK
- **Operating System**: Windows / Linux

**Comment by fturizo** [comment] 2021-11-19 19:07
Greetings @mirozitnansky, apologies for not coming back to you on this issue for quite a while, it kinda fell under the cracks since it was reported. Indeed the issue that you have encountered has been previously reported in #4844, so we'll proceed to close this one as a duplicate. Since that issue was reported quite a while ago, we are going to prioritize in the upcoming releases so that our Platform Development engineers work on providing a proper solution.

**Comment by fturizo** [comment] 2021-11-19 19:13
Greetings @mirozitnansky, apologies for not coming back to this issue sooner, as it kind of fell under the cracks in the past few months. Is this issue still present in the recent release of Payara Server Community (5.2021.9)? If so, can you please share the codebase of the CrudView3/CrudView4 applications to review them in detail and find out what is the cause of the problem?

**Comment by negiboudu** [comment] 2021-11-24 18:15
Hi, I had the same problem. I think that this is not payara issue.
The primefaces-10.0.0.jar contains web-fragment.xml, but not included \<distributable />.
Therefore, when I run the app, I get the following messages.

```
[2021-11-24T16:09:21.636+0000] [] [INFO] [AS-WEB-GLUE-00130] [javax.enterprise.web] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1637770161636] [levelValue: 800] Invalid Session Management Configuration for non-distributable app [hello1] - defaulting to memory: persistence-type = [hazelcast] / persistenceFrequency = [web-method] / persistenceScope = [modified-session]
```
- environment: Payara Micro 5.2021.9, JDK11, JakartaEE8.
- `hello1` is my sample app name. 

I tried using primefaces-11.0.0-RC2.jar and it worked fine.

## Related issue
https://github.com/primefaces/primefaces/issues/7976

**Comment by mirozitnansky** [comment] 2021-11-24 18:38
@negiboudu thanks for info. We will try to use updated version,  I'll post result.
@fturizo if it won't help, I will attach source codes.

**Comment by fturizo** [comment] 2021-11-25 00:53
@negiboudu, thanks for your input on this issue. in this case, the problem is clear: The Primefaces JAR file is missing a proper distributable web-fragment configuration,  then proper session replication won't work as per the Servlet specification all web application libraries inside the WAR module must be marked as distributable for the application to be so.  

Since this is not a Payara Server issue and is strictly caused by Primefaces we'll close this issue.

**Closed by fturizo** 2021-11-25 00:53 UTC
Labels: Type: Bug, Status: Pending

**Comment by mirozitnansky** [comment] 2021-11-26 12:33
I can confirm issues was caused by missing distributable property.
