### ISSUE TITLE
NPE loadFromBackingStore for Hazelcast cluster

### ISSUE THREAD

**Issue by jmutawa** [payara/Payara#1317] opened 2017-01-25 15:11 UTC
# Description #
----------

Hello,

I have configured 2 servers as per this [blog post](http://blog.payara.fish/creating-a-simple-cluster-with-payara-server) and this [YouTube video](https://www.youtube.com/watch?v=idifKBUhOsI), except that I have a DAS and a standalone instance in each server. 

I have enabled Hazelcast on DAS and instance servers on both servers, each can see 4 cluster members.

First node always works (whether server1 or server2), I get this error when the load balancer switches to second node:

```
[2017-01-25T13:19:43.250+0300] [Payara 4.1] [SEVERE] [AS-WEB-CORE-00037] [javax.enterprise.web.core] [tid: _ThreadID=29 _ThreadName=http-thread-pool(1)] [timeMillis: 1485339583250] [levelValue: 1000] [[
  An exception or error occurred in the container during the request processing
java.lang.NullPointerException
	at org.glassfish.web.ha.session.management.ReplicationStore.loadFromBackingStore(ReplicationStore.java:427)
	at org.glassfish.web.ha.session.management.ReplicationStore.load(ReplicationStore.java:416)
	at org.apache.catalina.session.PersistentManagerBase.doSwapIn(PersistentManagerBase.java:1215)
	at org.apache.catalina.session.PersistentManagerBase.swapIn(PersistentManagerBase.java:1175)
	at org.glassfish.web.ha.session.management.ReplicationManagerBase.findSession(ReplicationManagerBase.java:161)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3224)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:3089)
	at org.apache.catalina.connector.Request.lockSession(Request.java:4612)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:396)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
]]

[2017-01-25T13:19:43.250+0300] [Payara 4.1] [WARNING] [] [org.glassfish.grizzly.http.server.Response] [tid: _ThreadID=29 _ThreadName=http-thread-pool(1)] [timeMillis: 1485339583250] [levelValue: 900] [[
  GRIZZLY0207: Error during the Response finish phase
java.lang.NullPointerException
	at org.glassfish.web.ha.session.management.ReplicationStore.loadFromBackingStore(ReplicationStore.java:427)
	at org.glassfish.web.ha.session.management.ReplicationStore.load(ReplicationStore.java:416)
	at org.apache.catalina.session.PersistentManagerBase.doSwapIn(PersistentManagerBase.java:1215)
	at org.apache.catalina.session.PersistentManagerBase.swapIn(PersistentManagerBase.java:1175)
	at org.glassfish.web.ha.session.management.ReplicationManagerBase.findSession(ReplicationManagerBase.java:161)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3224)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:3089)
	at org.apache.catalina.connector.OutputBuffer.addSessionCookies(OutputBuffer.java:571)
	at org.apache.catalina.connector.OutputBuffer.access$300(OutputBuffer.java:94)
	at org.apache.catalina.connector.OutputBuffer$SessionCookieChecker.onCommit(OutputBuffer.java:748)
	at org.glassfish.grizzly.http.io.OutputBuffer.notifyCommit(OutputBuffer.java:1224)
	at org.glassfish.grizzly.http.io.OutputBuffer.doCommit(OutputBuffer.java:1126)
	at org.glassfish.grizzly.http.io.OutputBuffer.close(OutputBuffer.java:742)
	at org.glassfish.grizzly.http.io.OutputBuffer.endRequest(OutputBuffer.java:391)
	at org.glassfish.grizzly.http.server.Response.finish(Response.java:516)
	at org.glassfish.grizzly.http.server.HttpServerFilter.afterService(HttpServerFilter.java:384)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:260)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
]]

[2017-01-25T13:19:43.250+0300] [Payara 4.1] [WARNING] [] [org.glassfish.grizzly.http.server.Request] [tid: _ThreadID=29 _ThreadName=http-thread-pool(1)] [timeMillis: 1485339583250] [levelValue: 900] [[
  GRIZZLY0204: Unexpected error during afterService notification
java.lang.NullPointerException
	at org.glassfish.web.ha.session.management.ReplicationStore.loadFromBackingStore(ReplicationStore.java:427)
	at org.glassfish.web.ha.session.management.ReplicationStore.load(ReplicationStore.java:416)
	at org.apache.catalina.session.PersistentManagerBase.doSwapIn(PersistentManagerBase.java:1215)
	at org.apache.catalina.session.PersistentManagerBase.swapIn(PersistentManagerBase.java:1175)
	at org.glassfish.web.ha.session.management.ReplicationManagerBase.findSession(ReplicationManagerBase.java:161)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3224)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:3089)
	at org.apache.catalina.connector.Request.unlockSession(Request.java:4659)
	at org.apache.catalina.connector.CoyoteAdapter$CatalinaAfterServiceListener.onAfterService(CoyoteAdapter.java:1066)
	at org.glassfish.grizzly.http.server.Request.onAfterService(Request.java:617)
	at org.glassfish.grizzly.http.server.HttpServerFilter.afterService(HttpServerFilter.java:385)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:260)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
]]
```

I have an HA Proxy setup as follows:  
```
defaults
  mode http
  timeout client 5000ms
  timeout server 5000ms
  timeout connect 500ms

listen http-in
  bind *:80
  server server1 10.1.1.1:28080
  server server2 10.1.1.2:28080
```

I have deployed [this](https://github.com/jmutawa/session-test2) test application, I have used both a ManagedBean and a CDI Named bean, both give the same error.

Appreciate your guidance on how can I troubleshoot what is going wrong.

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**: Oracle jdk 8u111 64bit
- **Operating System**: Windows Server 2012 R2 64bit on Hyper-V

**Comment by lprimak** [comment] 2017-01-25 18:23
@jmutawa This has most likely already fixed in yet-unreleased .171 version, which should be released shortly

**Comment by lprimak** [comment] 2017-01-25 18:32
PR #1290 and #1171

**Comment by mikecroft** [comment] 2017-01-26 09:01
@jmutawa - you could test this before 171 is released with the latest pre-release build:
http://www.payara.fish/upstream_builds

Bear in mind it hasn't gone through our release testing yet, and there are a few things yet to be merged, so you may want to wait a couple of weeks for the actual release.

**Comment by jmutawa** [comment] 2017-01-26 09:20
@mikecroft I was just going to ask for that :)

Thank you, will try it out and see how it goes. When is the release planned?

**Comment by mikecroft** [comment] 2017-01-26 09:23
It's currently targeted for early February, providing testing doesn't throw up something unexpected!

**Comment by jmutawa** [comment] 2017-01-31 04:50
My apologies, it took me a while as I had to format my machine.

I have done the testing with the prerelease, this time using Virtualbox on Windows 7, running Windows 2012 R2 as guests. 

Unfortunately, I am getting the same errors. Any help would be appreciated.

**Comment by lprimak** [comment] 2017-01-31 06:39
Payara internal issue https://payara.atlassian.net/browse/PAYARA-1380

**Comment by lprimak** [comment] 2017-02-03 01:15
@fturizo can you reproduce this bug?  I wasn't able to reproduce it.
@jmutawa can you provide a complete log file from start to finish on the node that's failing?
espscially look for warnings.  I tracked through this code and this could only happen if Hazelcast wasn't properly initializing for some reason or another in your environment

**Comment by lprimak** [comment] 2017-02-03 01:44
#1336 is just so the NPE doesn't happen, you still have the underlying problem of hazelcast not initializing for some reason

**Comment by jmutawa** [comment] 2017-02-03 04:46
@lprimak Good morning, I have cleaned everything and started the testing again, and I see it is working fine now.

What I think happened is that some availability settings still had "replicated" as the availability method. So I changed everything, including default-config, even EJB although not used in this test, to Hazelcast. The logs where complaining about some Shoal GMS not being properly setup.

Thanks you for your support, you may close this issue as resolve. I look forward for the 171 release on Monday.

Just a last question, do I need to setup Hazelcast on both DAS and instance servers or only the instance would do? Also, is there a way to do only with a DAS and no instance servers? I cannot see Availability Setting for the DAS server.

**Comment by fturizo** [comment] 2017-02-03 18:41
@lprimak, no I couldn't replicate this bug either. I marked the bug as **payara-bug** prematurely.
@jmutawa, glad to know you could fix this issue and was a misconfiguration in this case. Considering the question you asked, the DAS server doesn't allow direct configuration of the Availability Service on the admin console, but you can configure it using `asadmin` commands:

`asadmin set server-config.availability-service.availability-enabled=true`

However, is not recommended to configure it on the DAS since the DAS must not be a part of a cluster configuration. In this regard, it's OK to only configure it on the instances instead.

**Closed** 2017-02-03 20:01 UTC
Labels: 1:Wait, c:Misconfiguration
