### ISSUE TITLE
Bug Report: Deploying applications to Virtual Servers payara 6 (and 5) is extremely difficult and has to be done manually when instances are defined.

### ISSUE THREAD

**Issue by naris** [payara/Payara#6512] opened 2023-12-21 01:15 UTC
### Brief Summary

Every time an application is deployed to a virtual server, it is **always** deployed to **every** virtual server on the server. This produces a "Virtual server <> already has a web module <> loaded at / therefore web module <> cannot be loaded at this context path on this virtual server" error.

This happens even if using ASADMIN and specifying --virtualservers. The admin "Deploy Applications or Modules" page doesn't even have anywhere to specify a virtual server to deploy to, it only has a target - even though the  [(blog post about Virtual Servers from 2018)](https://blog.payara.fish/virtual-servers-in-payara-server#:~:text=Deploying%20to%20Virtual%20Servers&text=Start%20Payara%20Server%2C%20and%20go,Create%20two%20new%20virtual%20servers.) has a screenshot that include a Virtual Server list to pick from (which does not exist in the current deployment page).

The only method I have found to be able to deploy to virtual servers is to manually:
    1. Clear the default-web-module of every virtual server.
    2. Disable or undeploy ALL the applications of every virtual server.
    3. Deploy an application.
    4. Manually remove all the virtual servers and add the 1 virtual server for that app in the "Manage Virtual Server" link of the Target tab for the application.
    5. Manually disable the application.
    6. Repeat steps 3-5 for each application to be deployed.
    7. Manually enable all the applications for all the virtual servers.
    8. Set the default-web-module of every virtual server to the appropriate application.

Since application are **always** deployed to **all** virtual servers when using ASADMIN, even when passing --virtualservers, it is not possible to script or automated deployment in any way forcing all deployments of any virtual servers to be a manual process :(

### Expected Outcome

There should be a way to deploy an application to only 1 virtual server and not all of them in the administration GUI.

When specifying ASADMIN --virtualservers to specify which virtual server to deploy an application to, it should deploy the application to **only** that server and not **all** of them.

It should be possible to deploy an application to 1 virtual server without having to disable or undeploy **every other** virtual server first.

### Current Outcome

There is no way to specify a virtual server when deploying an application using the administration "Deploy Applications or Modules" page, which only has a list of "targets" that only includes "server" and any instances you might have defined (we have 1 other instance defined so the target list is always server & instance2 and does not include any of the 3 virtual servers we have defined).

When using ASADMIN and specifying --virtualservers to specify which virtual server, it deploys the application to **all** of the virtual servers anyway and not just the one(s) specified.

### Reproducer

Configure multiple virtual servers and deploy applications that have / as the context root to each virtual server.

### Operating System

Linux RHEL 7 & 8

### JDK Version

openjdk version "11.0.20" 2023-07-18 LTS

### Payara Distribution

Payara Server Full Profile

**Comment by shub8968** [comment] 2024-01-08 14:39
Hi @naris,

Would you be kind enough to provide the steps in order to reproduce the issue and verify.

Thanks.

**Comment by naris** [comment] 2024-01-09 14:43
@shub8968 ,All you need to do is create 2 or more virtual servers with apps that use the same root context, such as /, and try to deploy a war to them.

**Comment by naris** [comment] 2024-01-09 14:53
In the administration UI, it only allows a selection of "targets", which only includes server instances, not virtual servers such as this screen shot shows:
![target_list](https://github.com/payara/Payara/assets/2623160/c484655c-6340-44ae-88d1-cd2f58963d7d)

**Comment by naris** [comment] 2024-01-09 14:57
Then, after the application has been deployed you have to go to the target tab
![application_targets](https://github.com/payara/Payara/assets/2623160/1a339e78-ad03-4a47-9378-9b4bda6e37ce)
and pick which server to deploy it to, **all** the virtual servers on the server was selected will **always* be selected after deploying the war file:
![virtual_server_list](https://github.com/payara/Payara/assets/2623160/ffbb6e43-b493-4cbd-a97b-53068739950c)

**Comment by naris** [comment] 2024-01-09 15:06
There *really* needs to be a way to deploy an application to a single virtual server, and not **all** of them. Especially when using asadmin, which does have a --virtualservers parameter that it, apparently, ignores :(

**Comment by naris** [comment] 2024-01-09 15:12
You have to disable **all** of the applications on a server in order to deploy **any** of them or you get this error
![virtual_error](https://github.com/payara/Payara/assets/2623160/b8419e2e-4082-4421-afe6-d7424dfceba2)

**Comment by fturizo** [comment] 2024-01-25 21:10
Greetings @naris,

We have been reviewing this issue and we are confused about your statements. Attempting to deploy an application in Payara Server 6.2023.12's Admin Console will show this screen:

![Application Deployment](https://github.com/payara/Payara/assets/2921814/0ae681a7-7187-4605-8a7f-1319087bfc47)

In this example, I can select the default `server` virtual server and 2 additional virtual servers I created to test this use case. Even after the application has been deployed, it is possible to modify the application's selected virtual server in its edit view:

![Application Edit](https://github.com/payara/Payara/assets/2921814/67420df6-832e-4a51-bc6a-d0012fc620ed)

So we're honestly confused about your claims that you cannot deploy an application to a specific virtual server. Deploying the application to all available virtual servers when none are selected is the default behaviour of the server and has always been, but this is not an issue since you can select the virtual server upon deployment.

Can you please share a detailed, self-contained reproducer with clear instructions that illustrate the issues you are encountering? We're afraid that without one we cannot assist you in this report as there is no clear indication of what the problem is.

**Comment by naris** [comment] 2024-01-27 22:37
@fturizo, No I have never seen the screen you show with a list of virtual servers. How do you get that as I have never seen it?
I only see a list of targets as shown in the screenshot I posted earlier, which are instances (server and instance2 since we have a 2nd instance defined) with no way to specify a virtual server.

Also, when I deploy applications using asadmin, it will ALWAYS deploy to all the virtual servers, even when --virtualservers is specified on the command line to specify only 1.

**Comment by naris** [comment] 2024-01-27 22:46
This is all I see when I deploy an application using Payara 6.2023.11 and is all I have seen with Payara 5 also, it has always been like this:
![image](https://github.com/payara/Payara/assets/2623160/093989a9-9afb-4eec-b273-fd6427f3e7b6)
![image](https://github.com/payara/Payara/assets/2623160/dbfaae6e-8bd7-4f8f-8dac-752a8b56646c)

**Comment by naris** [comment] 2024-01-27 22:49
The General Application page also does not look like your screenshot and does not have a section for virtual servers -- it looks like this:
![image](https://github.com/payara/Payara/assets/2623160/5c4c1068-10eb-4d21-83d4-eb13ce2ac7f8)

**Comment by naris** [comment] 2024-01-27 22:51
The only way to even see the Virtual Servers, and set them, are from the target tab:
![image](https://github.com/payara/Payara/assets/2623160/f7e48be6-8daa-492a-a4f1-463895fb6dd5)
and then clicking the Manage Virtual Servers link:
![image](https://github.com/payara/Payara/assets/2623160/8a7672ce-2928-45ba-af42-5bcf7ebe0a0d)

**Comment by naris** [comment] 2024-01-27 23:10
Using this ASADMIN command (from our Jenkinsfile) will deploy the application to ALL of the virtual servers, even though --virtualserver specifies which server to deploy it to:
asadmin deploy --force=true --upload=true --name "${APP_NAME}" --contextroot "/" --virtualservers "${VIRTUAL_SERVER}" "${WAR_FILE}"

Then if an attempt is made to deploy to a different virtual server it will fail because the 1st war file was already deployed to ALL the virtual servers :(

**Comment by naris** [comment] 2024-01-27 23:26
BTW, we are using the Community Edition of Payara Server 6.2023.11

**Comment by naris** [comment] 2024-01-27 23:31
I don't know if this makes a different, but as I stated above, we do have a 2nd instance defined:
![image](https://github.com/payara/Payara/assets/2623160/d1a528c2-a904-4723-8b63-5b4ce2b93399)

**Comment by naris** [comment] 2024-02-16 20:25
I have confirmed that this only happens when an instance has been defined. Then the virtual server dropdown no longer appears anywhere and you are left with only a list of available targets which are server + any instances that have been defined as seen above.

**Comment by fturizo** [comment] 2024-02-16 21:57
Greetings @naris,

We have been reviewing this issue using the information that you supplied, and indeed when there are multiple instances or targets available for deployments, virtual server selection gets trickier. If there are multiple instances the user interface in the Admin console page indeed won't allow the user to select which virtual servers will be used to host the web application in question.  This is a limitation of the page since the virtual server list selection will vary depending on the targets selected for the deployment. 

However, it is indeed possible to specify the virtual servers using the `deploy` subcommand. Here's an example:

     asadmin deploy --virtualservers=vs-2,vs-1 --target=local-instance-1 clusterjsp.war

Once this is done, you'll be able to verify the selected virtual servers using the Admin's Console *Target* tab in the Application's view:

![image](https://github.com/payara/Payara/assets/2921814/6d22c2dd-d7bc-44de-889c-4a9a961c6522)

Then you can view and modify the application's selected virtual servers for the specified target:

![image](https://github.com/payara/Payara/assets/2921814/51c8c696-3aab-4f17-bdb5-b062864fb4f1)

In the command samples you provided, I don't see any specific instances being set using the `--target` argument. To get your command working correctly and set the virtual servers as intended, you'll have to specify valid targets as per my example above.

Alternatively, you can also deploy the application from the Admin Console under the specific targets and then update the corresponding virtual servers using the UI views I showcased above. 

As the functionality of the server works as intended and virtual servers can be correctly set up for environments where there are multiple targets, we'll proceed to close this issue.

**Closed by fturizo** 2024-02-16 21:57 UTC
Labels: Type: Bug, Status: Open
