### ISSUE TITLE
High CPU usage after hibernate/suspend and wake up Window /CUSTCOM-42

### ISSUE THREAD

**Issue by dantonepinto** [payara/Payara#3817] opened 2019-03-06 19:52 UTC
# Description #
----------

After hibernate/suspend and wake up Windows with Payara running on it, Payara starts a high CPU usage. (No deployed applications on Payara.)
After Windows wake up, by analysing Thread tab of the Payara process on Process Explorer, I see seven threads remaining in infinite loop:
<table>
<thead>
<tr><th>tid</th><th>nid</th><th>name</th></tr>
</thead>
<tbody>
<tr><td>5568</td><td>0x15c0</td><td>hz._hzInstance_1_development.IO.thread-Acceptor</td></tr>
<tr><td>10616</td><td>0x2978</td><td>hz._hzInstance_1_development.IO.thread-out-2</td></tr>
<tr><td>10600</td><td>0x2968</td><td>hz._hzInstance_1_development.IO.thread-out-1</td></tr>
<tr><td>2196</td><td>0x894  </td><td>hz._hzInstance_1_development.IO.thread-out-0</td></tr>
<tr><td>7072</td><td>0x1ba0</td><td>hz._hzInstance_1_development.IO.thread-in-2</td></tr>
<tr><td>10584</td><td>0x2958</td><td>hz._hzInstance_1_development.IO.thread-in-1</td></tr>
<tr><td>10580</td><td>0x2954</td><td>hz._hzInstance_1_development.IO.thread-in-0</td></tr>
</tbody>
</table>

The attached file contains the result of the command "jstack -l PID".

I'm running Payara 5.184 on Window 7, but it was already happening on previous Payara's versions and Window 10.

[jstack_-l_PID.log](https://github.com/payara/Payara/files/2937920/jstack_-l_PID.log)

## Expected Outcome

The same CPU consumption as before hibernation.

## Current Outcome

Seven cores with 100% consumption.

## Steps to reproduce

1 - Start Payara Server preferably without deployies.
2 - Hibernate/Suspend Windows.
3 - Wake up Windows.

## Context

Every time I wake up Windows, I have to kill Payara in order to continue the development process or to do anything else activity on Windows.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 8 u181 - Oracle
- **Operating System**: Windows 7

**Comment by svendiedrichsen** [comment] 2019-03-06 20:56
It looks like a Hazelcast/Java NIO Bug on Windows: https://github.com/hazelcast/hazelcast/issues/7943

The fix provided by Hazelcast is a workaround which can be activated by setting a JVM property: https://github.com/hazelcast/hazelcast/pull/7998

**Comment by dantonepinto** [comment] 2019-03-06 22:09
The system property "-Dhazelcast.io.selectorMode=selectwithfix" solved such problem.

**Comment by svendiedrichsen** [comment] 2019-03-06 23:12
The Payara project might want to consider this Hazelcast workaround in the production configuration on windows machines.

**Comment by lprimak** [comment] 2019-03-06 23:36
@svendiedrichsen I doubt that production Payara server machines go to sleep and wake up...
So it's doubtful that this is required

**Comment by svendiedrichsen** [comment] 2019-03-06 23:51
@lprimak You are right. I hope that the bug is only tied to windows hibernation then.

**Comment by smillidge** [comment] 2019-03-16 19:38
So do we close this one or add the system property to the standard properties?

**Comment by lprimak** [comment] 2019-03-17 00:04
I would say to mention it in the documentation somewhere. Not to add this as a default

**Comment by svendiedrichsen** [comment] 2019-03-18 19:34
Agreed. But the documentation should also mention that this may happen if the server sits idle for about 2 hours as the original Hazelcast error states.

**Comment by OndroMih** [comment] 2019-03-20 14:49
So maybe it's better to add the sys property by default in Payara Server. This is caused by a known bug in OpenJDK, Grizzly has a similar workaround enabled by default. The workaround doesn't introduce any side effects in case the issue doesn't happen.

**Comment by lprimak** [comment] 2019-03-20 15:51
Ok, I take it back then. We should introduce the system property in production by default

**Comment by smillidge** [comment] 2019-03-20 19:27
OK create the JIRA

**Comment by rdebusscher** [comment] 2019-12-18 10:01
Tracked now as `CUSTCOM-42`

**Comment by AlanRoth** [comment] 2020-11-11 11:32
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:32 UTC
Labels: enhancement, status:accepted
