### ISSUE TITLE
MicroProfile Rest Client paths are reported as application paths /CUSTCOM-131

### ISSUE THREAD

**Issue by edthorne** [payara/Payara#4180] opened 2019-08-26 19:21 UTC
# MicroProfile Rest Client paths are reported as application paths

When deploying an application that contains MicroProfile Rest Client interfaces, several warnings are logged and the paths appear in the list of REST endpoints on startup. The endpoint is also documented in the `application.wadl`.

## Expected Outcome

MicroProfile Rest Client interfaces should not appear in the application's endpoints. Prior to version 5.192, these endpoints did not appear.

## Current Outcome

Using [this example](https://github.com/edthorne/ftrestclient), you can see the following in the client output:

```
[2019-08-26T13:56:45.366-0500] [] [WARNING] [] [org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1566845805366] [levelValue: 900] Component of class interface com.example.client.HelloService cannot be instantiated and will be ignored.

[2019-08-26T13:56:45.367-0500] [] [WARNING] [] [org.glassfish.jersey.server.ResourceModelConfigurator] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1566845805367] [levelValue: 900] Component of class interface com.example.client.HelloService cannot be instantiated and will be ignored.

...

[2019-08-26T13:01:25.079-0500] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1566842485079] [levelValue: 800] [[

Payara Micro URLs:
http://<host>:8086/client

'client' REST Endpoints:
GET	/client/api/api/hello/{name}
GET	/client/api/application.wadl
GET	/client/api/client
GET	/client/api/client/programmatic
GET	/client/api/client/retry
GET	/client/api/client/service

]]

```

The path `GET /client/api/api/hello/{name}` is not part of the deployed JAX-RS resources.

## Steps to reproduce

Deploy an application that contains a MicroProfile Rest Client on version 5.192 or higher.

### Samples

https://github.com/edthorne/ftrestclient

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Micro
- **JDK Version**: OpenJDK 1.8.0_201
- **Operating System**: Linux

**Comment by rdebusscher** [comment] 2019-08-30 11:42
Hi Ed,

I have created the internal issue PAYARA-4106 to fix this.

Thanks for the report and the link to the reproducer.

**Comment by rdebusscher** [comment] 2019-12-20 16:15
Tracked as `CUSTCOM-131`

**Comment by AlanRoth** [comment] 2020-11-11 11:45
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:45 UTC
Labels: bug, status:accepted
