### ISSUE TITLE
Asadmin console not responding when instance not working properly /CUSTCOM-112

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#3941] opened 2019-05-13 09:28 UTC
# Description #
----------

DAS asadmin web console is stuck when instance is not responding. There should be some shorter timeouts when waiting for instances to respond, because now the only solution is manually restart instance not using web console. I think the most important information is that the instance causing the problem is running, process in the OS is showed, so possibly DAS IS able to connect to it on TCP level, but this instance does not respond with any data. So timeout on just connection establishment might not be the answer, there has to be checked timeout of concurrent data flow.

## Expected Outcome

Better behaviour od web gui (short timeout, example 10 sec and show that instance is not responding).

## Current Outcome

Web gui stuck.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  Configure some instances

3 -**  Start instances

4 -**  Wait for some instance to get stuck (it happens, mostly on preprod env when there are a lot of redeployments).

5 -**  Try logging into asadmin GUI, navigate to the deployment group and try displaying status of instances.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: zulu8.38.0.13-ca-jre8.0.212-linux_x64
- **Operating System**: Linux
- **Database**: MySQL (but this has nothing to do with that)
- **Config**: Single DAS having 2 instances in deployment group (app is deployed to that deployment group)

**Comment by rdebusscher** [comment] 2019-05-15 14:55
Hi @peterpz1,

I have created an enhancement request in our system to have some kind of timeout for that operation in the Web Administration Console.

Thank you for your suggestion.

**Comment by smillidge** [comment] 2019-10-26 20:33
@rdebusscher what's the JIRA number?

**Comment by rdebusscher** [comment] 2019-10-28 06:15
@smillidge PAYARA-3818

**Comment by rdebusscher** [comment] 2019-12-20 08:22
Tracked now as `CUSTCOM-112`

**Comment by AlanRoth** [comment] 2020-11-11 11:36
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:36 UTC
Labels: enhancement, status:accepted
