### ISSUE TITLE
Does Payara 5 supports Web App 2.3...?

### ISSUE THREAD

**Issue by Mariselvam14** [payara/Payara#4226] opened 2019-09-18 20:51 UTC
Does Payara 5 supports Web App 2.3...?

We are trying to move from Glassfish 4 to Payara 5 and constantly redirected to login page of the app after 4-10 requests.
Could see Payara 5 lost the session in the middle and redirects to the login screen.
is this because we are running old web app on Payara 5..?

- **Payara Version**: 5 Build 192
- **JDK Version**:  Open JDK 8 -->
- **Operating System**: Linux
- **Database**: Oracle

**Comment by khasunuma** [comment] 2019-09-19 01:08
Payara 5 also supports Web App 2.3 because it has `web-app_2_3.dtd`. Perhaps, this issue is caused by another things. Would you create a simple reproducer for the issue?

**Comment by Mariselvam14** [comment] 2019-09-19 01:16
Yes, We were able to reproduce on PRODUCTION. Issue occurs during peak time(Happens only during heavy utilization). Still trying to reproduce locally.

During peak time, Payara will run slow and after some second it will loose the session.

**Note:** Same version of application works perfectly on Glassfish 4.

**Comment by khasunuma** [comment] 2019-09-19 05:21
It's seemed that there's a bug or performance degrade in Payara 5. I'd like someone in Dev team to reproduce and further investigate. @Mariselvam14 if you have additional information (e.g. configuration) that is useful for investigating, please let us know. Thanks.

**Comment by smillidge** [comment] 2019-10-26 19:23
This needs a reproducer as the issue is not reproducible using `ab`

**Comment by OndroMih** [comment] 2020-02-04 14:06
Hi, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us a reproducer for the latest version of Payara Server or Payara Micro. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.

**Closed by OndroMih** 2020-02-04 14:06 UTC
Labels: 1:Investigating, Help Wanted, Test Case Required, requestor unresponsive (1), v:Payara-5
