### ISSUE TITLE
MicroProfile Fault Tolerance not applied to MicroProfile Rest Client /FISH-746

### ISSUE THREAD

**Issue by edthorne** [payara/Payara#4179] opened 2019-08-26 18:42 UTC
# MicroProfile Fault Tolerance not applied to MicroProfile Rest Client

According to the [MicroProfile Rest Client 1.2 Documentation](https://github.com/eclipse/microprofile-rest-client/blob/1.2/spec/src/main/asciidoc/integration.asciidoc#microprofile-fault-tolerance) you should be able to apply Fault Tolerance annotations to a Rest Client interface. The annotations appear to not be applied to the constructed Rest Client implementation.

## Expected Outcome

Applying a Fault Tolerance annotation like `@Retry` to a Rest Client interface method should cause that method to be retried consistent with the annotation configuration according to the
specification linked above. Based on the [official documentation](https://docs.payara.fish/documentation/microprofile/) Payara Micro 5.192 supports MicroProfile 2.2.

## Current Outcome

If you annotate a Rest Client interface method with a Fault Tolerance annotation, it will not be applied to the Rest Client that is built and injected.

## Steps to reproduce

Apply a MicroProfile Fault Tolerance annotation to a MicroProfile Rest Client interface.

### Samples

I've fabricated an example loosely based on the existing [Payara-Examples](https://github.com/payara/Payara-Examples) for MicroProfile Fault Tolerance and Rest Client. The example can be found [here](https://github.com/edthorne/ftrestclient).

I've separated the Rest Client into it's client & server components to better demonstrate a micro-service environment where a Rest Client could be used to contact a remote service.

#### HelloRemoteResource.java

This class provides the server side of the example. It's wired to log each call and it's failure or success along with the passed argument to identify the caller.

#### HelloService.java

This interface defines the MicroProfile Rest Client interface. It's single method is annotated with `@Retry` to trigger a retry on any exception. **This annotation is not having the desired effect.**

#### ClientService.java

This managed bean only exists to demonstrate that the `@Retry` annotation is properly working on a managed bean that is not a JAX-RS resource class.

#### ClientResource.java

This JAX-RS resource provides multiple methods to test various retry scenarios. The outcomes are as follows:

* `helloWorld()` **no retry occurs**
* `helloWorldRetry()` retry occurs
* `helloWorldService()` retry occurs
* `helloWorldProgrammatic()` **no retry occurs**

## Context

The example provides a demonstration of leveraging the fault tolerance features of MicroProfile with a MicroProfile Rest Client. Since these are remote operations between services, it's convenient to specify some retry and fall back behaviors for when services are not available.

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Micro
- **JDK Version**: OpenJDK 1.8.0_201
- **Operating System**: Linux

**Comment by svendiedrichsen** [comment] 2019-08-26 21:42
To me it looks like this FT client feature has not been implemented yet. I can only find a _jaxrs-client-tracing_ module but nothing like a _jaxrs-client-fault-tolerance_ module.

**Comment by jbee** [comment] 2019-08-28 18:45
Pretty sure @svendiedrichsen is right.

**Comment by smillidge** [comment] 2019-11-03 20:09
I assume this is an upstream issue in Jersey then is that right?

**Comment by jbee** [comment] 2019-11-06 11:49
Talked about it with @pdudits - he pointed out this https://github.com/eclipse-ee4j/jersey/blob/master/ext/microprofile/mp-rest-client/src/main/java/org/glassfish/jersey/microprofile/restclient/RestClientProducer.java#L149 line. To have FT interceptors work the client creation needs CDI based enhancement or go via CDI as far as I understand the issue. He also pointed out that the behaviour isn't clearly defined in the specs.

**Comment by dimovelev** [comment] 2020-03-23 19:59
I am working around that issue by annotating the rest client interfaces with @fish.payara.microprofile.faulttolerance.cdi.FaultTolerance
I remember debugging it and figuring out that a something in CDI was annotating it with it upon startup but it does not work for clients built using as the builder (even if they are actual CDI beans e.g. created via a producer method)

**Comment by jbee** [comment] 2020-03-31 15:33
> I am working around that issue by annotating the rest client interfaces with @fish.payara.microprofile.faulttolerance.cdi.FaultTolerance

Interesting. If that works it should not require big changes. We just have to understand how rest client has CDI but is somehow not processed for FT.

**Comment by AlanRoth** [comment] 2020-11-11 11:45
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed** 2020-11-13 15:02 UTC
Labels: Status: Accepted
