### ISSUE TITLE
Nightly build 2015-04-28 does not allow creating jdbc connection pool resources through web interface

### ISSUE THREAD

**Issue by matthiasblaesing** [payara/Payara#269] opened 2015-04-28 18:24 UTC
Steps to reproduce:
- get fresh copy of "Payara 4.1.152 (Full Java EE)"
- Open web console
- Go to: Resources->JDBC->JDBC Connection Pools and select "New"
- Pool Name: XY, Resource Type: "javax.sql.DataSource", Database Driver Vendor: "Derby"
- Press next

=> results in HTTP Status 500 - Internal Server Error

The error reporting in the server.log gives not too much information:

```
[2015-04-28T20:20:37.510+0200] [Payara 4.1] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=107 _ThreadName=admin-listener(6)] [timeMillis: 1430245237510] [levelValue: 800] [[
  Exception Occurred :null]]

[2015-04-28T20:21:20.856+0200] [Payara 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=44 _ThreadName=admin-listener(1)] [timeMillis: 1430245280856] [levelValue: 900] [[
  StandardWrapperValve[FacesServlet]: Servlet.service() for servlet FacesServlet threw exception
java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:777)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:224)
	at com.sun.faces.context.ExternalContextImpl.getResponseOutputWriter(ExternalContextImpl.java:851)
	at com.sun.faces.context.PartialViewContextImpl.createPartialResponseWriter(PartialViewContextImpl.java:504)
	at com.sun.faces.context.PartialViewContextImpl.access$300(PartialViewContextImpl.java:79)
	at com.sun.faces.context.PartialViewContextImpl$DelayedInitPartialResponseWriter.getWrapped(PartialViewContextImpl.java:642)
	at javax.faces.context.PartialResponseWriter.startDocument(PartialResponseWriter.java:120)
	at com.sun.faces.context.AjaxExceptionHandlerImpl.handlePartialResponseError(AjaxExceptionHandlerImpl.java:201)
	at com.sun.faces.context.AjaxExceptionHandlerImpl.handle(AjaxExceptionHandlerImpl.java:126)
	at javax.faces.context.ExceptionHandlerWrapper.handle(ExceptionHandlerWrapper.java:100)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:119)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at com.sun.webui.jsf.util.UploadFilter.doFilter(UploadFilter.java:233)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:678)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
]]
```

**Comment by smillidge** [comment] 2015-04-29 08:26
Thanks Mathiass we've identified a bunch of console issues since we merged from upstream. I suspect this is just another one. We are currently tracking down what's the problem.

**Comment by Pandrex247** [comment] 2015-04-29 15:40
@smillidge I've made my own branch a pull request. It's similar to yours but a bit more focused. I think the error is being caused by having a weight value applied to an @Produces annotation with only one media type.

From my own tests, reverting all weighting causes the error to be thrown when starting the domain instead of when creating something. The error doesn't seem to be fatal to the server start-up, but I don't know if it killed something else that isn't readily apparent.

Your fix doesn't run into this, but I think it's safer to change less.

**Comment by smillidge** [comment] 2015-04-29 15:54
Do you mean your fix causes a server startup error or mine causes a server startup error?

**Comment by Pandrex247** [comment] 2015-04-29 16:03
Neither.

When I reverted all of the qs changes like you did, I ran into start-up errors. 
Your branch doesn't seem to throw these errors, so I either made a mistake when doing it like you did, or the errors are intermittent.

Either way, it's still probably safer to change less.

**Comment by smillidge** [comment] 2015-04-29 16:07
Agree. Merge in your pull.

**Comment by smillidge** [comment] 2015-04-29 16:08
Also raise a GF JIRA pointing back to this issue. 
BTW my Glassfish JIRA account is now payara_steve ;-)

**Closed** 2015-04-29 16:15 UTC
Labels: upstream bug

**Comment by mkarg** [comment] 2015-11-11 14:43
It seems upstream team is unresponsive: https://java.net/jira/browse/JERSEY-2861

Apparently they are not addressing this issue. Do you know the reason?

Is this bug really gone in latest download of Payara?

**Comment by smillidge** [comment] 2015-11-11 15:19
Should be fixed in the latest Payara release.
