### ISSUE TITLE
In simple Servlet not possible to make big (>2MB) Post request

### ISSUE THREAD

**Issue by omarbr** [payara/Payara#666] opened 2016-02-17 16:21 UTC
Report this bug opened on glassfish: 
https://java.net/jira/browse/GLASSFISH-21240

**Comment by mulderbaba** [comment] 2016-03-08 12:31
[Attached](https://github.com/payara/Payara/files/163129/jsf-inputfile.zip) is a sample app based on JSF 2.2 for uploading files with standard JSF2.2 inputFile component. After deploying it on Payara, just request for: localhost:8080/jsf-inputfile-1.0-SNAPSHOT/upload.jsf. 

I couldn't reproduce this with the sample app. There is only one configuration for http-listener-1 in the admin console of payaradomain and it's named Max Post Size. it has the default value -1, which doesn't limit uploaded file size. Configuration of http-listener-1 in admin console can be founded at Configurations > server-config > Network Config > http-listener-1 > HTTP Tab.

**Comment by figolino** [comment] 2016-04-19 11:09
Hi omarbr to allow simpel post request >2MB you have to  set this propertie there is no field in the admin UI.... 
asadmin  set configs.config.server-config.network-config.protocols.protocol.http-listener-1.http.max-form-post-size-bytes=-1
asadmin  set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.max-form-post-size-bytes=-1

**Comment by mikecroft** [comment] 2016-06-10 14:42
Hi @omarbr did @figolino's suggestion work for you?

**Comment by omarbr** [comment] 2016-06-10 14:46
yes, it works. 
Its possible add to admin UI?

**Comment by lprimak** [comment] 2016-06-10 16:08
I believe it's already in the admin UI

**Comment by mikecroft** [comment] 2016-06-10 17:22
Yes, it is, where @mulderbaba said it would be (I just checked on 162). I'll close this now since it all works.

**Closed by mikecroft** 2016-06-10 17:22 UTC
Labels: 1:Wait, c:PossibleBug, cannot reproduce, requestor unresponsive (1)

**Comment by phillip-kruger** [comment] 2016-11-21 16:07
Anyway to do this in Payara Micro ? (Without having to externalize the server.xml)
Thanks

**Comment by mikecroft** [comment] 2016-11-21 16:11
Probably the best way would be to use the `--rootDir` option to output the domain.xml, make the change there, then run Payara Micro again with `--outputUberJar` to bake in your modified domain.xml.

We're currently looking at the way all this works at a fundamental level so that we can make all this kind of stuff easier, but we don't have any kind of timescale on that at the moment because it's a pretty big job.

(incidentally, if you have problems with the above method, please feel free to raise it in a separate issue)

**Comment by smillidge** [comment] 2016-11-21 16:20
If you are using the programmatic api to boot Payara Micro you can also run the asadmin command listed above as part of your bootstrap of Payara Micro. As @mikecroft says we are redoing a lot of this packaging and in the future will allow the user to pass a pre-boot and post-boot set of asadmin commands to run.

**Comment by phillip-kruger** [comment] 2016-11-21 16:28
Again - thanks for the quick response !
I am not starting payara micro with the programmatic api, so will do as @mikecroft suggest. I am creating an uber jar in maven, so should be simple enough to pass the domain.xml in. (This might be something I need anyways as system gets feature rich)
Thanks !

**Comment by OndrejM** [comment] 2017-02-06 13:40
I found out that there are in fact 2 properties that limit the size of the POST data. 

- `max-post-size-bytes`, can be configured also in admin console, setting it to -1 will remove size limits and accept any request
- `max-form-post-size-bytes` (as @figolino suggested) 
   - this cannot be configured in Admin console, only via asadmin command
   - this is not being applied to requests of type `application/x-www-form-urlencoded`, therefore it is ignored for form file upload requests via a browser (here is the code in [Grizzly](http://grepcode.com/file/repo1.maven.org/maven2/org.glassfish.grizzly/grizzly-http-server/2.3.21/org/glassfish/grizzly/http/server/Request.java#2031))

**Comment by bradvido** [comment] 2023-08-02 17:04
For anyone stumbling upon this for payara micro 5, the command is slightly different:

`set configs.config.server-config.network-config.protocols.protocol.http-listener.http.max-post-size-bytes=-1`

`http-listener` instead of `http-listener-1`
