### ISSUE TITLE
REST Resources secured with Jersey filter not accessible after upgrade from 174 to 181 /FISH-71

### ISSUE THREAD

**Issue by clive-jevons** [payara/Payara#2490] opened 2018-03-01 20:12 UTC
# Description #
----------

We have created a Jersey ContainerRequestFilter which handles the authentication for our applications and use it in conjunction with the RolesAllowedDynamicFeature in order to handle authorisation.

After updating to Payara Micro 4.1.2.181 we always get an HTTP 401 when accessing resource secured in this manner and see the following output in the server log:

[2018-03-01T21:01:45.654+0100] [] [WARNING] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=25 _ThreadName=http-thread-pool::http-listener(4)] [timeMillis: 1519934505654] [levelValue: 900] WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for <our user here>.

Downgrading to 174 without any other changes fixes the problem again.

Could the classes

./appserver/payara-appserver-modules/jaspic-servlet-utils/src/main/java/fish/payara/security/jaspic/SimpleSAMAuthContext.java
./appserver/payara-appserver-modules/jaspic-servlet-utils/src/main/java/fish/payara/security/jaspic/SimpleSAMConfig.java

be the cause of this? It looks like these were added in 4.1.2.181?

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Micro
- **JDK Version**: Oracle JDK 8
- **Operating System**: Tested with Mac and Linux
- **Database**: n/a

**Comment by smillidge** [comment] 2018-03-01 21:12
Unlikely to be those classes as they are just a simplified api a developer can use to hook into JASPIC.
Could be Soteria but I'm speculating now.

Do you have a test case we could take a look at?

Could it be related to #2326?

**Comment by arjantijms** [comment] 2018-03-01 22:29
It's indeed related to #2326.

The Jersey `RolesAllowedDynamicFeature` interprets the `@RolesAllowed` annotation, but doesn't call the authentication system if it needs authentication but finds the user is not authenticated. Instead, it throws a ForbiddenException, which I guess is what the `ContainerRequestFilter` mentioned  is catching and responding to:

```java
        @Override
        public void filter(final ContainerRequestContext requestContext) throws IOException {
            if (!denyAll) {
                if (rolesAllowed.length > 0 && !isAuthenticated(requestContext)) {
                    throw new ForbiddenException(LocalizationMessages.USER_NOT_AUTHORIZED());
                }

                for (final String role : rolesAllowed) {
                    if (requestContext.getSecurityContext().isUserInRole(role)) {
                        return;
                    }
                }
            }

            throw new ForbiddenException(LocalizationMessages.USER_NOT_AUTHORIZED());
        }
```

Because of the JWT support that was added to 181, and it's requirement of interpreting the `@RolesAllowed` annotation as well, the following now happens instead:

```java
    @Override
    public void filter(final ContainerRequestContext requestContext) throws IOException {
        if (rolesAllowed.length > 0 && !isAuthenticated()) {
                
            AuthenticationStatus status =  securityContext.authenticate(request, response, withParams());
            
            // Authentication was not done at all (i.e. no credentials present) or
            // authentication failed (i.e. wrong credentials, credentials expired, etc)
            if (status == NOT_DONE || status == SEND_FAILURE) {
                throw new NotAuthorizedException("Authentication resulted in " + status);
            }
            
            if (status == SUCCESS && !isAuthenticated()) { // compensate for possible Soteria bug, need to investigate
                throw new NotAuthorizedException("Authentication not done (i.e. no JWT credential found)");
            }

        }

        boolean hasRole = stream(rolesAllowed).anyMatch(r -> requestContext.getSecurityContext().isUserInRole(r));

        if (!hasRole) {
            throw new ForbiddenException("Caller not in requested role");
        }

    }
```

Instead of the exception, `securityContext.authenticate` is called. This will call the default authentication mechanism, which will call the default identity store (the Payara specific File LoginModule), which causes the exception and response being seen.

Without having seen the reproducer and without having tested it, adding a class like the following to the application may be a quick workaround if that application is only using `@RolesAllowed` on JAX-RS endpoints, and not also Servlet authentication within the same application:

```java
import javax.enterprise.context.ApplicationScoped;
import javax.security.enterprise.AuthenticationException;
import javax.security.enterprise.AuthenticationStatus;
import javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism;
import javax.security.enterprise.authentication.mechanism.http.HttpMessageContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.ForbiddenException;


@ApplicationScoped
public class TestAuthenticationMechanism implements HttpAuthenticationMechanism {

    @Override
    public AuthenticationStatus validateRequest(HttpServletRequest request, HttpServletResponse response, HttpMessageContext httpMessageContext) throws AuthenticationException {

        if (httpMessageContext.isAuthenticationRequest()) {
            throw new ForbiddenException("User not authorized.");
        }

        return httpMessageContext.doNothing();
    }

}
```

@clive-jevons could you add that class to your application and let us know if that fixes things for now?

To fix this in a better way we'd either need the switch as was added in Payara 5, or make sure Payara's own `@RolesAllowed` doesn't get used if Jersey's one is already used (or both).

**Comment by clive-jevons** [comment] 2018-03-01 22:40
@smillidge Here's a simple application which demonstrates the problem:

[payara-security-test.tar.gz](https://github.com/payara/Payara/files/1773025/payara-security-test.tar.gz)

@arjantijms I'll have a go at integrating the solution you suggest to see if it work. Thanks.

**Comment by arjantijms** [comment] 2018-03-01 22:48
@clive-jevons before I forget, in order to have the above class compiled you'd also need the API dependency (provided scope, only for compiling against):

```xml
<dependency>
    <groupId>javax.security.enterprise</groupId>
    <artifactId>javax.security.enterprise-api</artifactId>
    <version>1.0</version>
    <scope>provided</scope>
</dependency>
```

**Comment by clive-jevons** [comment] 2018-03-01 22:53
@arjantijms already found the dep ;) Thnx :)
Unfortunately it results in the endpoint returning an HTTP 500, but I'm not seeing any errors in the log :(
Here's the altered project:

[payara-security-test-2.tar.gz](https://github.com/payara/Payara/files/1773062/payara-security-test-2.tar.gz)

**Comment by arjantijms** [comment] 2018-03-01 23:03
I just looked at your example code and you're not catching the exception from the Jersey filter as I blindly guessed you may had done. 

As you're doing basic authentication in your own filter, you could alternatively also activate BasicAuthentication from Java EE and implement an identity store where you can fetch the roles in the same way you're doing in the real filter now.

That's basically following the example from here:

https://github.com/javaee/security-soteria/tree/master/test/app-mem-basic/src/main/java/test

With basic authentication activated as done here:

https://github.com/javaee/security-soteria/blob/master/test/app-mem-basic/src/main/java/test/Servlet.java#L59

And the logic to fetch your roles as done here:

https://github.com/javaee/security-soteria/blob/master/test/app-mem-basic/src/main/java/test/TestIdentityStore.java#L56

It's late here now, but I'll look a bit closer at it tomorrow. Thanks for your report.

**Comment by clive-jevons** [comment] 2018-11-22 10:58
Hi all - just wondering if there's any news regarding this issue? If at all possible, a simple switch to deactivate all the JACC stuff would be just grand ;)

//cc @arjantijms @smillidge

**Comment by OndrejM** [comment] 2018-11-22 15:11
Some more information provided on the forum: https://groups.google.com/d/msg/payara-forum/9qkcUMW-5bw/DWGk6vUBCQAJ

@clive-jevons also reproduced with 5.183. He's getting 401 HTTP error. Setting `jaxrs-roles-allowed-enabled=false` in `payara-web.xml` descriptor didn't help either.

**Comment by Admiral-Joshua** [comment] 2019-04-11 12:44
Hi there Payara Team,
I'm actually encountering this exact problem myself with a project of mine, and it's really problematic as it means we can't upgrade our Payara server version for our application.

I've noticed this issue is marked as "WithDev." Are there any plans to update/fix this soon? Any plans on the next build maybe? Would be really useful to get ASAP.

**Comment by smillidge** [comment] 2019-04-11 18:14
No plans at the moment. If you need this fast I would suggest support or we welcome PRs.

**Comment by Admiral-Joshua** [comment] 2019-04-11 18:47
I see, that's a shame. So we'd probably have to look at rewriting some of our authentication / back-end.

We'll probably have to see about adopting the newer authentication method(s). I don't suppose you know of/have any links to tutorials or documentation that we could use to try and get our application back up and running with newer versions of Payara Server? 
Do you think removing the @RolesAllowed might help at all? We'd obviously rather keep them in, if possible. The application can be logged into fine but as soon as we try to make a JSON request we hit a 401 unauthorized on just about everything!

**Comment by Admiral-Joshua** [comment] 2019-09-17 12:52
Fixed it! For those who are still struggling with this issue. Could you try adding @DeclareRoles to your application config java bean. We had two roles in our application, which were previously outlined in our XML file, but were no longer being correctly picked up on @RolesAllowed decorated functions. After adding a single @DeclareRoles in the application and listing each of the two roles within it, the app immediately sprung back to life on Payara 5.191+ 
Hope this helps, if you're still having issues let me know and I'll take a look to see whether any changes are necessary in the config.

**Comment by rdebusscher** [comment] 2019-12-16 16:02
Tracked by `CUSTCOM-87`

**Comment by AlanRoth** [comment] 2020-11-11 11:05
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:05 UTC
Labels: bug, status:accepted
