### ISSUE TITLE
Bug Report: ` TemplateCommandGetResource`'s method uses @GET annotation but @Path is missing

### ISSUE THREAD

**Issue by oneturkmen** [payara/Payara#5316] opened 2021-06-22 21:38 UTC
# Description #
----------

`TemplateCommandGetResource` class uses JAX RS annotations, but misses `@Path` which is necessary for the resource to be picked up. Might be a potential issue.

Link:
https://github.com/payara/Payara/blob/5017a460aae0bf382f0a0255c84594f14fcb46bc/nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandGetResource.java#L69

`LeafResource` class uses JAX RS annotations, but misses `@Path` which is necessary for the resource to be picked up. Otherwise, 404 is returned.

Link:
https://github.com/payara/Payara/blob/5017a460aae0bf382f0a0255c84594f14fcb46bc/nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/LeafResource.java#L107

`CollectionLeafResource` class uses JAX RS annotations, but misses `@Path` which is necessary for the resource to be picked up. Otherwise, 404 is returned.

Link:
https://github.com/payara/Payara/blob/5017a460aae0bf382f0a0255c84594f14fcb46bc/nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java#L146

`NotificationLogViewer` class uses JAX RS annotations, but misses `@Path` which is necessary for the resource to be picked up. Otherwise, 404 is returned.

Link:
https://github.com/payara/Payara/blob/5017a460aae0bf382f0a0255c84594f14fcb46bc/nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/NotificationLogViewer.java#L102

## Expected Outcome ##

Use `@Path` either on the class or the methods of the class.

## Current Outcome ##

Might return 404 (not tested).

## Steps to reproduce ## 

Since the code snippets are part of the codebase, I am not sure how to properly reproduce that. Is there any way to check admin REST service in `/nucleus` ?

## Environment ##

- **Distribution**: all
- **JDK Version**: all
- **Operating System**: all

**Comment by shub8968** [comment] 2021-06-23 16:42
Merging the related issues raised by @oneturkmen into one.

**Comment by shub8968** [comment] 2021-06-23 16:42
Duplicate of #5314

**Comment by shub8968** [comment] 2021-06-23 16:44
Duplicate of #5313 

Duplicate of  #5312

**Comment by shub8968** [comment] 2021-06-23 16:44
Duplicate of  #5312

**Comment by shub8968** [comment] 2021-06-23 16:49
Hi @oneturkmen,

Would you be able to provide the proper reproducer for the issue? It is highly recommended to use the issue template while raising the issue.

**Comment by oneturkmen** [comment] 2021-06-24 16:44
@shub8968 updated the description. Albeit, I am not sure how to test the admin REST service to see if the code is reachable at all. I have a suspicion that it is not a bug and these classes are expected to be extended as follows:

```java
@Path("/foo") // we now attach @Path
public class Foo extends LeafResource {
    ...
}
```

**Comment by shub8968** [comment] 2021-06-30 15:11
Hi @oneturkmen,

Unfortunately, I need to close this as this issue is not reproducible.

**Closed by shub8968** 2021-06-30 15:11 UTC
Labels: Status: Open
