### ISSUE TITLE
CDI 2.0 Asynchronous event observer method is not working in @SessionScoped bean

### ISSUE THREAD

**Issue by pidekjunior** [payara/Payara#4110] opened 2019-07-26 14:14 UTC
# Description #
----------

Asynchronous event observer method is not working in @SessionScoped bean.

## Expected Outcome

An asynchronous observer should be asynchronously notified in @SessionScoped bean when Event#fireAsync method is called.

Documentations:
[https://docs.jboss.org/cdi/api/2.0/javax/enterprise/event/Event.html#fireAsync-U-](https://docs.jboss.org/cdi/api/2.0/javax/enterprise/event/Event.html#fireAsync-U-)

[https://docs.jboss.org/cdi/api/2.0.EDR2/javax/enterprise/event/ObservesAsync.html](https://docs.jboss.org/cdi/api/2.0.EDR2/javax/enterprise/event/ObservesAsync.html)

## Current Outcome

Observer method is not called when it is placed in @SessionScoped bean. The only working configuration is when the observer method is placed in @ApplicationScoped bean.

## Steps to reproduce (Only for bug reports) 

1) Create two @SessionScoped beans.
2) Place event producer method into one of them (use fireAsync method).
3) Place event asynchronous observer method into the second one.

Note: This approach works when the second bean is @ApplicationScoped.

Or run the example of the problem:
https://github.com/pidekjunior/asynceventexample

### Samples

```
@Named
@SessionScoped
public class TestBean implements Serializable {

    @Inject
    private Event<String> stringEvent;

    public String test(){
        stringEvent.fireAsync("aaaa");
        return "test";
    }

}
```

```
@Named
@SessionScoped
public class Test2Bean implements Serializable {

    public void listen(@ObservesAsync String s){
        System.out.println(s);
    }

}
```

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: 8 u222 - OpenJDK -->
- **Operating System**: Windows
- **Database**: -

**Comment by smillidge** [comment] 2019-07-27 15:25
We need a test case to investigate. Can you create one on GitHub. Are you sure you have SessionScope active when the event is fired?

**Comment by pidekjunior** [comment] 2019-07-29 10:47
I created a very simple showcase of the problem here: https://github.com/pidekjunior/asynceventexample

Both SessionScoped beans are activated before firing the event.

**Comment by rdebusscher** [comment] 2019-12-20 15:22
It works with synchronous event. So probably the fireAsync has lost the CDI context.

Not sure this can be solved easy.

**Comment by smillidge** [comment] 2019-12-20 23:14
Probably needs a spec check to see if it is supposed to work.

**Comment by rdebusscher** [comment] 2020-01-03 10:48
According to the spec section `Observer resolution` ( https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#observer_resolution) the above scenario might be supported. (as there is no mentioning of the scope)

>The event is fired asynchronously and the observer is an asynchronous observer 

However, various points are left undefined: 
- When an async event is fired, is only the CDI Session bean within the same session contacted, or all?
- What happens when HTTP session is already closed by the time the Event is processed?

**Comment by AlanRoth** [comment] 2020-11-11 11:43
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:43 UTC
Labels: status:reproducer-needed, try to reproduce

**Comment by pidekjunior** [comment] 2020-12-02 18:08
> Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

Hello,

first of all, I appreciate your long answer.

I try to reproduce the test case on the newest Payara (5.2020.6), and I found that the bug is still there OR the CDI specification is not 100% precise and correct.

1) `@ObservesAsync` works if it is an annotation of the parameter of static method
2) According to [official Jakarta javadoc](https://jakarta.ee/specifications/cdi/2.0/apidocs/) the observing method must be the method of Jakarta Enterprise Bean.
2a) `@ObservesAsync` works if a bean is annotated as `@Stateless`
2b) but it does not work in `@Stateful @SessionScoped` bean
3) According to [official Jakarta specification](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#observes_ee) the observing method must be in local session Jakarta Enterprise Bean, but even this does not work... But usually, there is no scope specified in the official specifications.

So if you consider reopening this issue in the future, you can use these new observations. Anyway, thank you for your work and time.

**Comment by AlanRoth** [comment] 2020-12-04 12:01
Hi @pidekjunior, 

If the bug still persists, we encourage you to create a new issue with an updated reproducer application and we will have a look at it ASAP!

The original initiative was to close issues the authors had abandoned, glad to see you're not one of them!

Thank you for your understanding,
Alan
