### ISSUE TITLE
JVM classloader issue 

### ISSUE THREAD

**Issue by maheshmarri** [payara/Payara#1229] opened 2016-12-12 22:38 UTC
# Description #
----------

JVM classloader not displaying the classpath of the libraries

## Expected Outcome

I have enabled the JVM options to generate the classloader to pring the classpath libraries to log file. What it should have happened it to print he entire class libraries in jvm.log

## Current Outcome

Currently the jvm.log is displaying the below issue for printing the classpath of the libraries.

<writer thread='140485025365760'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap keySet ()Ljava/util/Set;' witness='com/sun/enterprise/universal/g
lassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap keySet ()Ljava/util/Set;' witness='com/sun/enterprise/universal/g
lassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap entrySet ()Ljava/util/Set;' witness='com/sun/enterprise/universal
/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap containsKey (Ljava/lang/Object;)Z' witness='com/sun/enterprise/un
iversal/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap containsKey (Ljava/lang/Object;)Z' witness='com/sun/enterprise/un
iversal/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap containsKey (Ljava/lang/Object;)Z' witness='com/sun/enterprise/un
iversal/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap containsKey (Ljava/lang/Object;)Z' witness='com/sun/enterprise/universal/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap containsKey (Ljava/lang/Object;)Z' witness='com/sun/enterprise/universal/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap containsKey (Ljava/lang/Object;)Z' witness='com/sun/enterprise/universal/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap entrySet ()Ljava/util/Set;' witness='com/sun/enterprise/universal/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='java/util/HashMap' x='java/util/HashMap entrySet ()Ljava/util/Set;' witness='com/sun/enterprise/universal/glassfish/ASenvPropertyReader$ASenvMap' stamp='2.341'/>
<dependency_failed type='unique_concrete_method' ctxk='org/apache/felix/framework/wiring/BundleCapabilityImpl' x='java/lang/Object equals (Ljava/lang/Object;)Z' witness='org/apache/felix/framework/resolver/WrappedCapability' stamp='2.635'/>
<dependency_failed type='unique_concrete_method' ctxk='org/apache/felix/framework/wiring/BundleCapabilityImpl' x='java/lang/Object equals (Ljava/lang/Object;)Z' witness='org/apache/felix/framework/resolver/WrappedCapability' stamp='2.635'/>
<writer thread='140484004206336'/>
<dependency_failed type='leaf_type' ctxk='java/io/ByteArrayOutputStream' witness='com/sun/common/util/logging/LoggingOutputStream' stamp='3.885'/>
<writer thread='140484004566784'/>
<dependency_failed type='abstract_with_unique_concrete_subtype' ctxk='java/nio/charset/CharsetDecoder' x='sun/nio/cs/UT

## Steps to reproduce (Only for bug reports) 

<!-- 

Describe the test to reproduce the bug in a series of steps. Make each step simple to follow by describing configuration changes, commands to run or simple instructions; for example:

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  Configure JVM Options on Clusterconfig to generate the classpath information.
Configure the below 2 values to generate the classpath into logfile
-XX:LogFile=${com.sun.aas.instanceRoot}/logs/jvm.log
-XX:+LogVMOutput

## Context (Optional)

We are trying to upgrade our web application environment from glassfish 3.1.1.2 to Payara 4.1.1.163

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Web
- **JDK Version**: JDK 7
- **Operating System**: Linux

**Comment by maheshmarri** [comment] 2016-12-12 22:39
Hello Team,

Can anyone help on the above issue. 

Thanks
Mahesh

**Comment by fturizo** [comment] 2016-12-13 00:25
Hi @maheshmarri, could you post what are the JVM options you set in the domain's configuration so we can reproduce this behavior? Also, for the current outcome it seems that you missed the current output for the log file.

**Comment by maheshmarri** [comment] 2016-12-13 03:00
The beloa are the JVM Options.:
-XX:LogFile=${com.sun.aas.instanceRoot}/logs/jvm.log
-XX:+LogVMOutput

**Comment by maheshmarri** [comment] 2016-12-14 22:30
Hi ,Can you provide your inputs...

**Comment by fturizo** [comment] 2016-12-15 17:20
@maheshmarri, I've been looking at this issue but the official documentation on the XX:+LogVMOutput is really scarce and not useful at identifying issues with the JVM output. Can you tell us what is the diagnostic you want to do on the server? Maybe another approach that is better documented can help you.

**Comment by maheshmarri** [comment] 2016-12-21 00:00
But at aleast should it print the all the jar files list that it is loading in the classpath ,when the server is startingup... This is what we did it in glassfish 3.1.1.2 to print classpath details.

**Comment by fturizo** [comment] 2016-12-23 22:28
Hello @maheshmarri, I tested the same options with **Oracle Glassfish 3.1.2.2**, and got the following JVM output:

```
..
<properties>
java.vm.specification.name=Java Virtual Machine Specification
java.vm.version=24.79-b02
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.info=mixed mode, sharing
java.ext.dirs=C:\Program Files\Java\jdk1.7.0_79/lib/ext;C:\Program Files\Java\jdk1.7.0_79/jre/lib/ext;C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish\domains\domain1/lib/ext
java.endorsed.dirs=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish/modules/endorsed;C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish/lib/endorsed
sun.boot.library.path=C:\Program Files\Java\jdk1.7.0_79\jre\bin
java.library.path=C:/Users/fabio/Documents/GF_Payara-Servers/glassfish-3.1.2.2/glassfish/lib;C:/Program Files/Java/jdk1.7.0_79/bin;C:/Windows/Sun/Java/bin;C:/Windows/System32;C:/Windows;C:/Program Files (x86)/RSA SecurID Token Common;C:/ProgramData/Oracle/Java/javapath;C:/Program Files (x86)/Intel/iCLS Client;C:/Program Files/Intel/iCLS Client;C:/Windows/System32/wbem;C:/Windows/System32/WindowsPowerShell/v1.0;C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL;C:/Program Files/Intel/Intel(R) Management Engine Components/DAL;C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT;C:/Program Files/Intel/Intel(R) Management Engine Components/IPT;C:/Program Files/Intel/WiFi/bin;C:/Program Files/Common Files/Intel/WirelessCommon;C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C:/Program Files/NodeJS;C:/Program Files/Git/cmd;C:/Program Files/Git/usr/bin;C:/Program Files (x86)/Skype/Phone;C:/Program Files/Apache Software Foundation/apache-maven-3.3.3/bin;C:/Program Files/Apache Software Foundation/apache-ant-1.9.1/bin;C:/Program Files (x86)/Hashicorp/Vagrant/bin;C:/Users/fabio/AppData/Roaming/npm;C:/Program Files/Docker Toolbox;C:/Users/fabio/AppData/Local/atom/bin;C:/Users/fabio/AppData/Local/Microsoft/WindowsApps;C:/Program Files (x86)/Nmap;C:/Users/fabio/Documents/GF_Payara-Servers/glassfish-3.1.2.2/bin
java.home=C:\Program Files\Java\jdk1.7.0_79\jre
java.class.path=C:/Users/fabio/Documents/GF_Payara-Servers/glassfish-3.1.2.2/glassfish/modules/glassfish.jar
sun.boot.class.path=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish/modules/endorsed\javax.annotation.jar;C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish/modules/endorsed\jaxb-api-osgi.jar;C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish/modules/endorsed\webservices-api-osgi.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\resources.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\rt.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\sunrsasign.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\jce.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.7.0_79\jre\classes
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.7
java.vm.vendor=Oracle Corporation
osgi.shell.telnet.maxconn=1
jdbc.drivers=org.apache.derby.jdbc.ClientDriver
felix.fileinstall.disableConfigSave=false
felix.fileinstall.dir=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish/modules/autostart/
javax.net.ssl.keyStore=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish\domains\domain1/config/keystore.jks
osgi.shell.telnet.port=6666
java.security.policy=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish\domains\domain1/config/server.policy
java.awt.headless=true
felix.fileinstall.log.level=2
felix.fileinstall.poll=5000
com.sun.aas.instanceRoot=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish\domains\domain1
osgi.shell.telnet.ip=127.0.0.1
com.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
com.sun.aas.installRoot=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish
felix.fileinstall.bundles.startTransient=true
felix.fileinstall.bundles.new.start=true
javax.net.ssl.trustStore=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish\domains\domain1/config/cacerts.jks
com.sun.enterprise.security.httpsOutboundKeyAlias=s1as
ANTLR_USE_DIRECT_CLASS_LOADING=true
java.security.auth.login.config=C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish\domains\domain1/config/login.conf
gosh.args=--nointeractive
sun.java.command=com.sun.enterprise.glassfish.bootstrap.ASMain -domainname domain1 -asadmin-args --host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--debug=false,,,--domaindir,,,C:\Users\fabio\Documents\GF_Payara-Servers\glassfish-3.1.2.2\glassfish\domains,,,domain1 -instancename server -verbose false -debug false -asadmin-classpath C:/Users/fabio/Documents/GF_Payara-Servers/glassfish-3.1.2.2/glassfish/modules/admin-cli.jar -asadmin-classname com.sun.enterprise.admin.cli.AsadminMain -upgrade false -type DAS -domaindir C:/Users/fabio/Documents/GF_Payara-Servers/glassfish-3.1.2.2/glassfish/domains/domain1 -read-stdin true
sun.java.launcher=SUN_STANDARD
</properties>
..
```

The output is similar to the one I got with **Payara Server 4.1.1.164**. What is the expected output for the server's classpath?

**Comment by fturizo** [comment] 2017-01-24 15:27
Hello, @maheshmarri. Could you take a look at my last reply? Let us know what is the difference in the classpath printing to detect whether this is a bug.

**Comment by mikecroft** [comment] 2017-03-30 20:17
Hi @maheshmarri it looks like we're struggling to reproduce this one. Is the jvm.log snippet you posted the entire output, or is there a `<properties>` element like in @fturizo's post?

**Comment by fturizo** [comment] 2017-05-02 23:38
Closing this issue since the reported error couldn't be reproduced and the user was unresponsive on providing more details.

**Closed by fturizo** 2017-05-02 23:38 UTC
Labels: c:PossibleBug, cannot reproduce
