### ISSUE TITLE
MQTT Cloud Connector JNDI Lookup Fails on Payara Micro 4.1.2.174 or Later 

### ISSUE THREAD

**Issue by oxley-calabrio** [payara/Payara#2437] opened 2018-02-21 17:27 UTC
# Description #
----------
Pretty much follow your example outlined here:
http://blog.payara.fish/payara-micro-jca-adapters-mqtt

I isolated the issue when the Context Lookup is hitting the `@Resource` tag.  I believe Payara JNDI is not fully initialized at that point.  `@Resource` I believe is a little bit too eager.  

If I throw this a REST GET endpoint method to see if I can lazily find it and not experience an issue (not correct behavior obviously):
`   Context ctx = new InitialContext();
    MQTTConnectionFactory provider = (MQTTConnectionFactory) 
    ctx.lookup("java:comp/env/MQTTConnectionFactory");
`

When you try to use Payara Micro Cloud Connector you will receive a JNDI Lookup Error:

> [2018-02-21T11:11:41.287-0600] [] [1;91m[SEVERE][0m [NCLS-CORE-00026] [[1;94mjavax.enterprise.system.core[0m] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519233101287] [levelValue: 1000] [[
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: JNDI lookup failed for the resource: Name: [java:module/env/com.calabrio.research.microservices.payara.MQTTSendMessage/factory], Lookup: [java:comp/env/MQTTConnectionFactory], Type: [fish.payara.cloud.connectors.mqtt.api.MQTTConnectionFactory]
        at com.sun.enterprise.deployment.util.ResourceValidator.validateJNDIRefs(ResourceValidator.java:874)
        at com.sun.enterprise.deployment.util.ResourceValidator.validateResources(ResourceValidator.java:736)
        at com.sun.enterprise.deployment.util.ResourceValidator.event(ResourceValidator.java:141)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:424)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:508)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1426)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1001)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:361)
Caused by: javax.naming.NamingException: Lookup failed for 'java:comp/env/MQTTConnectionFactory' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NamingException: Invocation exception: Got null ComponentInvocation ]
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at com.sun.enterprise.deployment.util.ResourceValidator.validateJNDIRefs(ResourceValidator.java:869)
        ... 33 more
Caused by: javax.naming.NamingException: Invocation exception: Got null ComponentInvocation
        at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.getComponentId(GlassfishNamingManagerImpl.java:862)
        at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:734)
        at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:159)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:476)
        ... 37 more
]]

**I do not experience this issue on: Payara Micro 4.1.2.172**

## Expected Outcome

No error injecting the MQTT Factory using the @Resource(lookup="...")

## Current Outcome

Payara Micro is inaccessible

## Steps to reproduce (Only for bug reports) 
http://blog.payara.fish/payara-micro-jca-adapters-mqtt

## Environment ##

- **Payara Version**: 4.1.2.174, 4.1.2.181
- **Edition**: Micro
- **JDK Version**: 8
- **Operating System**:Windows

**Comment by smillidge** [comment] 2018-02-21 17:41
could be related to #2430 and #2387?

**Comment by oxley-calabrio** [comment] 2018-02-21 17:48
Yeah, I think it is related to #2430 but I am sure if it is related to #2387 because I can find it correctly.  When I read #2387, it appears the JDNI locations changed.  I will double check this.

**Comment by smillidge** [comment] 2018-02-22 16:59
Actually this is suspicious
```
Caused by: javax.naming.NamingException: Invocation exception: Got null ComponentInvocation
at 
```

**Comment by smillidge** [comment] 2018-02-22 19:54
Likely duplicate of #2430 
Please try setting the system property ```-Ddeployment.resource.validation=false``` to see if the error goes away?

**Comment by oxley-calabrio** [comment] 2018-02-22 20:18
@smillidge That worked! Is there a chance #2438 for a workaround while I wait for the latest version?  I still have this exact issue when I package the UberJar despite passing in the flag.

**Comment by smillidge** [comment] 2018-02-22 20:25
I don't think #2438 is related. I couldn't reproduce #2438

**Comment by smillidge** [comment] 2018-02-22 20:25
Closing as duplicate of #2430

**Closed by smillidge** 2018-02-22 20:25 UTC

**Comment by oxley-calabrio** [comment] 2018-02-22 22:11
@smillidge I think you are right.  I still get this error though when I created uber jar.  Is there a way to pass -Ddeployment.resource.validation=false ?

**Comment by smillidge** [comment] 2018-02-23 10:25
You can create a properties file and use ```--systemproperties``` on the command line. 
If I recall correctly they will also be incorporated into the Uber Jar correctly.
