### ISSUE TITLE
Remote CDI does not work Using CDI Qualifiers /CUSTCOM-98

### ISSUE THREAD

**Issue by skonx** [payara/Payara#3416] opened 2018-11-12 20:46 UTC
# Description #
----------

I've forked the [Payara-Examples](https://github.com/payara/Payara-Examples.git) and updated the dependencies of the project cdi-clustered-events for Payara 5.183 : [cdi-clustered-events](https://github.com/trendev/Payara-Examples/tree/master/payara-micro/cdi-clustered-events) 

CDI Events can only be sent/received adding the `eventdata.jar` on the classpath creating the two first Payara micro instances or typing the Event with String.

Unfortunately, it's not possible to qualify the Event (I've created a `NewCustomMessage` qualifier in the eventdata project).

It seems mandatory to add  the `CustomMessage` POJO and/or `NewCustomMessage` qualifier in the classpath in order to send/receive the CDI Events. 

Can be related to #3198 

## Expected Outcome

Fire and Observe POJO and not only String or primitive types.

## Current Outcome

Message is fired but never received

> INFO: Payara Micro  5.183 #badassmicrofish (build 380) ready in 15,071 (ms)
> Nov 12, 2018 9:17:47 PM fish.payara.examples.payaramicro.event.sender.SendEventServlet processRequest
> INFO: message fired

### 1. Start the first payara micro instance and deploy the 2 wars

> java -jar $MICROPATH/payara-micro-5.183.jar --autoBindHttp --logproperties logging.properties --deploy event-sender/target/event-sender-1.0-SNAPSHOT.war event-receiver/target/event-receiver-1.0-SNAPSHOT.war

### 2. Start the second payara micro instance and deploy the 2 wars

> java -jar $MICROPATH/payara-micro-5.183.jar --autoBindHttp --logproperties logging.properties --deploy event-sender/target/event-sender-1.0-SNAPSHOT.war event-receiver/target/event-receiver-1.0-SNAPSHOT.war

### 3. Post a message on the first instance
> curl http://127.0.0.1:8080/event-sender-1.0-SNAPSHOT/SendEventServlet?message=curl-message

## Context (Optional)

It works if I use the `eventName`  attribute in `@Outbound` and `@Inbound` instead of a qualifier.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full / Micro
- **JDK Version**: Oracle 1.8.0_181 / Oracle 1.8.0_191
- **Operating System**: Mac

**Comment by smillidge** [comment] 2018-11-17 19:41
This is fixed in the current master

**Comment by skonx** [comment] 2018-11-19 14:52
Hi @smillidge.

I've finally build the latest release and I'm using the latest payara-micro.

It works... but I'm facing troubles using Qualifiers 😞 

Randomly, the receiver application receives the Event or logs this exception (and in this case, the Event in not received) :

> [2018-11-19T15:41:42.652+0100] [] [INFO] [] [fish.payara.appserver.micro.services.PayaraClusteredCDIEventImpl] [tid: _ThreadID=110 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1542638502652] [levelValue: 800] [[
>   Problem determining the qualifier type of an Event ignoring
> java.lang.IllegalArgumentException: interface fish.payara.examples.payaramicro.eventdata.NewCustomMessage is not visible from class loader
> 	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
> 	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
> 	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
> 	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
> 	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
> 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
> 	at fish.payara.appserver.micro.services.PayaraClusteredCDIEventImpl.getQualifiers(PayaraClusteredCDIEventImpl.java:173)
> 	at fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl$1.run(ClusteredCDIEventBusImpl.java:176)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:143)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
> ]]

Adding `--addlibs ../eventdata/target/eventdata-1.0-SNAPSHOT.jar` forces the classloader to use this definition but the WAR files also include this dependencies (thanks to the scope "compile").

**Comment by smillidge** [comment] 2019-01-29 21:52
Is the error demonstrated by the same test application otherwise please create a new reproducer.

**Comment by skonx** [comment] 2019-01-29 22:10
Hi Steve. I guess it is.

**Comment by rdebusscher** [comment] 2019-12-17 16:10
Created issue `CUSTCOM-98`

**Comment by AlanRoth** [comment] 2020-11-11 11:25
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:25 UTC
Labels: status:accepted
