### ISSUE TITLE
restart-domain is slow, whereas stop-domain and start-domain work fine

### ISSUE THREAD

**Issue by dazed19** [payara/Payara#402] opened 2015-08-17 15:06 UTC
With a clean install of /payara-4.1.153 (also with /payara-4.1.151),  Within asadmin - "start-domain" and "stop-domain" work fine (and quick) but "restart-domain" is very slow and take ~2mins to complete

Looking at server.log I see the following - which show a) 3 min+ pause between starting JMX and b) an exception in JMSConfigListener

[2015-08-17T15:54:00.177+0100] [Payara 4.1] [INFO] [NCLS-JMX-00005] [javax.enterprise.system.jmx] [tid: _ThreadID=73 _ThreadName=Thread-21] [timeMillis: 1439823240177] [levelValue: 800] [[
  JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://myhost.mydomain,com:8686/jndi/rmi://myhost.mydomain,com:8686/jmxrmi]]

[2015-08-17T15:57:19.010+0100] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=66 _ThreadName=pool-14-thread-1] [timeMillis: 1439823439010] [levelValue: 1000] [[
  Config Listener class com.sun.enterprise.connectors.jms.system.JMSConfigListener notification took too long
java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.jvnet.hk2.config.Transactions$ConfigListenerNotifier$1.call(Transactions.java:289)
        at org.jvnet.hk2.config.Transactions$ConfigListenerNotifier$1.call(Transactions.java:268)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.jvnet.hk2.config.Transactions$Notifier$1$1.run(Transactions.java:167)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
]]

This is not a major issue (to me) as the work-around is clearly to "stop-domain" and "start-domain" which I have embedded into my init.d/services script.

**Comment by smillidge** [comment] 2015-08-17 20:07
Thanks I can reproduce this on a new domain.

**Comment by smillidge** [comment] 2015-08-17 20:11
Looks like it is only the very first restart-domain call after a clean installation

**Comment by dazed19** [comment] 2015-08-18 08:26
Hi - I get this behaviour every time I run "restart-domain" when the domain is running - the bulk of the restart appears to work (from the activity in the log) but it always seems to have a problem on the JMSConfigListener.   If I run "restart-domain" when the domain is not running it works fine

**Comment by khasunuma** [comment] 2016-04-27 05:43
Certainly, there may be wait a long time in a part of JMSConfigListener because it has two synchronized blocks. But they are process to create/remove network proxy for a particular http listener. So I think that it may be network problem, for example, a http listener is still listening for some reason.

**Comment by mikecroft** [comment] 2016-05-24 13:15
I just tried to reproduce this on a newly downloaded Payara and found that the restart happened very quickly:

```
[2016-05-24T14:08:50.891+0100] [Payara 4.1] [INFO] [NCLS-REST-00001] [javax.enterprise.admin.rest] [tid: _ThreadID=43 _ThreadName=admin-listener(1)] [timeMillis: 1464095330891] [levelValue: 800] [[
  Listening to REST requests at context: /command/domain.]]

[2016-05-24T14:08:51.068+0100] [Payara 4.1] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=89 _ThreadName=Thread-20] [timeMillis: 1464095331068] [levelValue: 800] [[
  Server restart initiated]]

[...snip...]

[2016-05-24T14:08:54.179+0100] [Payara 4.1] [INFO] [NCLS-REST-00001] [javax.enterprise.admin.rest] [tid: _ThreadID=43 _ThreadName=admin-listener(2)] [timeMillis: 1464095334179] [levelValue: 800] [[
  Listening to REST requests at context: /command/domain.]]
```

From there it looks like it took about 3 seconds. This was using `Payara Server 161.1` and domain1.

If the wait time is in JMSConfigListener, then it is likely that @khasunuma is correct and this is a network issue.

**Comment by mikecroft** [comment] 2016-07-06 13:43
Is this still a problem? Anecdotally, I use `restart-domain` frequently in my own testing and I've never (to my knowledge) seen this. Grepping my directory with all my test servers in, there is no occurrence of the JMSConfigListener exception, so that could be why.

Are you sure that that exception is the cause of the delay? AFAIK a FutureTask is async, so shouldn't block anything.

If you can still reproduce the problem, what would be really useful would be a couple of thread dumps from `jstack`, otherwise I'm not sure there's anything more we can do here.

**Comment by mikecroft** [comment] 2016-07-14 15:21
Is this still an issue for you @dazed19 ?

**Comment by dazed19** [comment] 2016-07-15 08:04
Hi @mikecroft 
No not an issue for me - as per original post, I wrapped the glassfish start/stop/restart in a linux service (init.d) script and used "stop" and "start" for restart - which never showed the problem.

**Comment by mikecroft** [comment] 2016-07-16 13:01
Thanks for the confirmation! I'll close this off now. There may have been an issue, but I think any issue is likely environmental rather than directly an issue with Payara Server.

**Closed by mikecroft** 2016-07-16 13:01 UTC
Labels: 1:Wait, c:PossibleBug, cannot reproduce, requestor unresponsive (1), requestor unresponsive (2)
