### ISSUE TITLE
Use a separate setting for Connection timeout /CUSTCOM-128

### ISSUE THREAD

**Issue by candrews** [payara/Payara#4061] opened 2019-06-26 00:41 UTC
# Description #
----------
https://github.com/payara/Payara/issues/1013 improved the connection validators to use the statement timeout. However, it would be much better to use a different setting than the statement timeout. For example, in my case, I have some queries which take 15 minutes to run, but I'd really like to timeout connections in 1 second.

## Expected Outcome

There should be a new connection pool setting:
`connect-timeout-in-seconds` of type `Number` by default set to `-1`. The description text would be: `Timeout property of a connection to enable limiting how long to wait for a connection. -1 will use the value of statement-timeout-in-seconds. 0 implies no timeout (wait forever).`
https://github.com/payara/Payara/blob/payara-server-5.192/appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java would have `isValidByCustomValidation` and `isValidByTableQuery` changed from using:
```
        int statementTimeout = Integer.valueOf(getStatementTimeout());
        
        // The timeout defaults to -1, which isn't actually a valid setting for the timeout
        if (statementTimeout == -1) {
            statementTimeout = 0;
        }
```
to
```
        int connectionTimeout = Integer.valueOf(getConnectionTimeout());
        
        // The timeout defaults to -1, which means use the statement timeout (for backwards compatibility)
        if (connectionTimeout == -1) {
            connectionTimeout = Integer.valueOf(getStatementTimeout());
        }
        
        // The timeout defaults to -1, which isn't actually a valid setting for the timeout
        if (connectionTimeout == -1) {
            connectionTimeout = 0;
        }
```
and use `connectionTimeout` instead of `statementTimeout`.

## Current Outcome
Statement timeout is used as the connection timeout, which is not ideal as it doesn't allow for long running statement to be normal but connection acquisition expected to be quick.

**Comment by rdebusscher** [comment] 2019-12-20 14:24
I have created `CUSTCOM-128`

**Comment by AlanRoth** [comment] 2020-11-11 11:42
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:42 UTC
Labels: enhancement, status:accepted
