### ISSUE TITLE
Ignored @WebFault targetNamespace on WSDL generation

### ISSUE THREAD

**Issue by Hoobie** [payara/Payara#1153] opened 2016-10-27 15:13 UTC
# Description

This issue is accurately described on Stackoverflow: http://stackoverflow.com/questions/27964771/why-webservices-wsdl-is-not-using-the-webfault-namespace
## Expected Outcome

Namespace from the WebFault annotation's targetNamespace property.
## Current Outcome

Namespace from one of the services.
## Steps to reproduce (Only for bug reports)

Prepare an application with 2 WebServices with different targetNamespaces and a common exception with targetNamespace from one of them.
## Environment
- **Payara Version**: 4.x
- **Edition**: Any
- **JDK Version**: 1.7+
- **Operating System**: Linux

**Comment by mulderbaba** [comment] 2016-10-27 21:24
@Hoobie I went through the code snippets but there were some missing bits. I gathered a working example available as attachment to this issue but couldn't reproduce the problem. [git-1153-src.zip](https://github.com/payara/Payara/files/557072/git-1153-src.zip). Can you go through it and verify?

**Comment by Hoobie** [comment] 2016-10-31 08:04
@mulderbaba, thank you for the quick reply.

I have verified your example and slightly modified it to get one namespace for the first WS and a separate namespace for the second WS and the web fault:
[git-1153-1.0.war.tar.gz](https://github.com/payara/Payara/files/561297/git-1153-1.0.war.tar.gz)
[git-1153.tar.gz](https://github.com/payara/Payara/files/561296/git-1153.tar.gz)

Then after the 3rd deploy (it doesn't seem to be deterministic) I have got the MyWebService1's XSDs like that:
```xml
<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is Metro/2.3.2-b608 (trunk-7979; 2015-01-21T12:50:19+0000) JAXWS-RI/2.2.11-b150120.1832 JAXWS-API/2.2.12 JAXB-RI/2.2.12-b141219.1637 JAXB-API/2.2.13-b141020.1521 svn-revision#unknown. --><xs:schema xmlns:ns1="http://some.custom.namespace1/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://some.custom.namespace2/">

<xs:import namespace="http://some.custom.namespace1/" schemaLocation="http://localhost:8080/git-1153-1.0/MyWebservice1?xsd=2"/>

<xs:element name="ApplicationFault" type="ns1:ApplicationFault"/>

</xs:schema>
```

```xml
<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is Metro/2.3.2-b608 (trunk-7979; 2015-01-21T12:50:19+0000) JAXWS-RI/2.2.11-b150120.1832 JAXWS-API/2.2.12 JAXB-RI/2.2.12-b141219.1637 JAXB-API/2.2.13-b141020.1521 svn-revision#unknown. --><xs:schema xmlns:tns="http://some.custom.namespace1/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://some.custom.namespace1/">

<xs:element name="myMethod" type="tns:myMethod"/>

<xs:element name="myMethodResponse" type="tns:myMethodResponse"/>

<xs:complexType name="myMethod">
<xs:sequence/>
</xs:complexType>

<xs:complexType name="myMethodResponse">
<xs:sequence/>
</xs:complexType>

<xs:complexType name="ApplicationFault">
<xs:sequence>
<xs:element name="message" type="xs:string" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
</xs:schema>
```
Which are wrong because the web fault should be from: `http://some.custom.namespace2/` but is from: `http://some.custom.namespace1/` due to `@WebFault(name = "ApplicationFault", targetNamespace = "http://some.custom.namespace2/")`.

**Comment by smillidge** [comment] 2019-02-02 22:54
Closed as too old

**Comment by smillidge** [comment] 2019-02-02 22:54
Please reopen if still an issue

**Closed by smillidge** 2019-02-02 22:54 UTC
Labels: 1:Investigating, c:PossibleBug
