### ISSUE TITLE
CDI in ServerAuthModule (JSR196) resulting in No valid EE environment for injection

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#299] opened 2015-05-27 09:45 UTC
Calling:
`Instance<MyAuthenticator> authenticator = CDI.current().select(MyAuthenticator.class, new AnnotationLiteral<Any>() {});`
inside a ServerAuthModule#validateRequest(...) method results in 
`No valid EE environment for injection of com.sample.MyAuthenticator`
although it seems that the bean is working properly. Similar finding here:
http://arjan-tijms.omnifaces.org/2012/11/implementing-container-authentication.html

**Comment by ratcashdev** [comment] 2015-05-27 12:35
Related SPEC ticket: https://java.net/jira/browse/JASPIC_SPEC-14
According to the link, some implementations (Wildfly) have already support for this. If it's not a huge undertaking, support in Payara would be welcome as well.

**Comment by smillidge** [comment] 2015-06-25 20:57
Tracking the code this is a random System.err.println which I believe should be a log message No valid EE environment for injection of com.sample.MyAuthenticator

https://github.com/payara/Payara/blob/7b449f9da0d851874b51ec63f497b9d8d3007016/appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java

**Comment by arjantijms** [comment] 2015-07-07 09:40
Strongly related to this is that while CDI lookup works in GlassFish/Payara in a SAM, EJB lookup (via JNDI) does not work. Lookup of a CDI bean that's injected by an EJB bean does not work either.

After a very quick glance at the GF code it looks like that CDI is initialised at that point, but the JNDI component namespaces (java:global, etc) are not.

Possible related is that EJB injection into a ServletRequestListener *may* not work either (but this is just an assumption, have to check this).

**Comment by ratcashdev** [comment] 2015-07-07 10:22
Arjan, just to understand your text, let's have a sample case:
* Bean1 is `@SessionScoped`
* Bean2 is `@Stateless`
* ServletMonitor is `@WebListener`
* MySAM is the SAM, `@ApplicationScoped`.

Essentially you're saying that:
* CDI lookup works in GlassFish/Payara in a SAM - i.e, doing `@Inject Bean1` works in MySAM. 
* EJB lookup (via JNDI) does not work - i.e. doing `@EJB Bean2` in MySAM will throw a NPE when referenced
* CDI bean that's injected by an EJB bean - i.e. doing `@Inject Bean2` in MySAM will throw a NPE when referenced? 

My finding is that the above actually works (at least 1 and 3), as long as MySAM was instantiated (via `@Inject MySAM`) in ServletMonitor and registered via ServletMonitor.
What also works (maybe only by miracle is the following):
* `@Inject Bean2` into Bean1
* `@Inject Bean1` into MySAM
* `@Inject MySAM` into ServletMonitor
* Finally, have ServletMonitor register the injected MySAM with JASPIC. In this scenario, Bean2 when actually used in the code (validate the user against a DB through an EntityManager) behaves as expected for both read and write.

**Comment by arjantijms** [comment] 2015-07-07 13:43
>My finding is that the above actually works (at least 1 and 3), as long as MySAM was instantiated (via @Inject MySAM) in ServletMonitor and registered via ServletMonitor.

That's really interesting! A SAM is *normally* instantiated via the ServerAuthContext and/or ServerAuthConfig. I often just use new() in a WebListener (we have to be aware that the SAM is a singleton then, and the Handler that it gets from the container every time HAS to be thread safe, but this is normally indeed the case).

If you inject an instance of the SAM in the web listener, then register that with JASPIC, you're using that single proxy as the instance for all invocations.

Now after this there are at least the following two situations;

1. The SAM is called BEFORE the resource invocation (before the first Filter or Servlet is called)
2. The SAM is called DURING the resource invocation (almost always after calling HttpServletRequest#authenticate from a Filter or Servlet)

In case 1, lookup of CDI beans works in GlassFish (but not in for instance WebLogic). And calling a method on them (even if normal scoped) works. This  means CDI is available AND relevant contexts (such as request scope) have been set up.

However, if you lookup an EJB bean at this point from the SAM it will not work. Likewise, if you did a lookup for a CDI bean that is injected with an EJB bean (either via @Inject or @EJB) it will not work either. There's an exception that says something along the lines of no component namespace or environment available. It's somewhere on my TODO to make a test for this.

It's really quite interesting that your method of re-using a proxy throughout the application with @Stateless proxies already created works. This is one case I haven't directly tested (Adam Bien had an example of this where he used this technique to switch between SAMs using alternatives, but he didn't used EJB).

**Comment by smillidge** [comment] 2015-07-07 13:52
Some questions.
What does the spec say should happen in the situations above, wrt to initialisation of container services?
Also ideally what would people like GlassFish to do?
Also how would it be different, if at all, between a JASPIC provider registered dynamically and packaged in a war/ear and a JASPIC provider registered via the administration console and loaded from the modules directory?

**Comment by arjantijms** [comment] 2015-07-07 18:00
>What does the spec say should happen in the situations above, wrt to initialisation of container services?

Unfortunately, nothing for JASPIC. I'm trying to get this clarified/added for Java EE 8. Perhaps as part of the security EG (of which I am a member), or via the JASPIC EG (but there's no EG started yet, so alternatively via a MR).

Part of the problem is that containers often initialise CDI using a ServletRequestListener, and it's not defined if a ServletRequestListener should fire before or after a SAM sees the request. This too has to be clarified, but at the moment it's a cross-spec concern which makes it harder to address.

>Also ideally what would people like GlassFish to do?

Ideally what JBoss does; all contexts (CDI, CDI scopes, EE component namespaces) are available in a SAM.

>Also how would it be different, if at all, between a JASPIC provider registered dynamically and packaged in a war/ear and a JASPIC provider registered via the administration console and loaded from the modules directory?

It should not be different, but it's a concern to think about indeed. Ideally the spec should say something about this, but in practice if I'm not mistaken the SAM always sees the classes and contexts of the application, even when registered via the "administration console" (where "administration console can also be an xml file like domain.xml or a CLI, etc).

**Comment by ratcashdev** [comment] 2015-07-08 08:01
I guess all my findings are relevant to case 2 in your description (The SAM is called DURING the resource invocation), as CDI has to be fully set up and working(thanks to `@WebListener`) for the SAM to actually get registered. By the time the EJB will really be needed (a resource is accessed) everything will be fully set up... (or  this is just my wishful thinking).

Could this (quietly) suggest that we can simply ignore case 1?

As for the container registered (via the admin console) or war/ear regitered SAM: today's trend is to use one application server for one war/ear. Which pretty much eliminates a possible reuse of the SAM accross applications. I am in favor of the war/ear registering (and thanks for Arjan's Factory-Factory-Factory example).

**Comment by arjantijms** [comment] 2015-07-08 19:04
>I guess all my findings are relevant to case 2 in your description (The SAM is called DURING the resource invocation), as CDI has to be fully set up and working(thanks to @WebListener) 

Well, it's not due to the WebListener that registered the SAM (I assume that this WebListener is a ServletContextListener). That one could potentially just receive an EJB proxy, but it's a complicating factor.

What causes CDI and EJB to be available for calls to a SAM during the resource invocation is simply that CDI and EJB are at least available during the point in time that the first Filter is called up until that first Filter returns again. If a SAM is called during the resource invocation it's in response to a HttpServletRequest#authenticate call, which is normally called from a Filter or Servlet. The contexts and namespaces simply remain active then.

In ASCII art:

Application start -> ServletContextListener [registers SAM with container]

Request start -> CDIServletRequestListener ... other ServletRequestListeners (requestInitialized) -> SAM (validateRequest [1]) -> Filter1, Filter2, ... Filter-that-calls-authenticate() -> SAM (validateRequest [2]) -> FilterN -> Servlet -> SAM (secureResponse) -> other ServletRequestListeners (requestDestroyed) -> CDIServletRequestListener (requestDestroyed)

The problem is with validateRequest [1], which means the first call to validateRequest and the one that happens before the resource invocation. It's here that in GlassFish CDI is available, but the Java EE component namespaces are not

>Could this (quietly) suggest that we can simply ignore case 1?

Unfortunately this is a very important case as well, the fact that a SAM can be called before the resource invocation is one of its prime virtues. 

>today's trend is to use one application server for one war/ear. Which pretty much eliminates a possible reuse of the SAM accross applications.

I agree that the trend is one war/ear per server, and SAM reuse across multiple apps on one server is indeed not the prime reason (AFAIK) for the "admin console" registration.

However, it remains an important aspect that the SAM be configured externally. This is specifically true for applications that are externally obtained and need to be incorporated into a (corporate) intranet. Prying a war open and putting a SAM there together with a ServletContextListener is frowned upon. The power of Java EE is that a range or resources can be configured/provided from both the app itself as externally.

Historically some people have tried to take away the option to configure such resources from within the app, claiming it's not a good practice for an enterprise to do so. I don't agree with that so you usually see me advocating the need for the configure from application case, but in reality I think both cases should be supported.

P.s.

JASPIC has a third option, where you can deploy a single war with only the SAM and the ServletContextListener, then use a NULL as app context ID when registering the SAM. After this is done, deploy any other application. This other application will use the SAM from the first deployment.

**Comment by ratcashdev** [comment] 2015-08-13 11:45
> I assume that this WebListener is a ServletContextListener
Correct. See the actual code here: https://github.com/ratcashdev/JSR196OAuthLogin/blob/master/src/main/java/com/ratcash/multilogin/sample/auth/ctrl/AuthenticatorRegistrar.java

I am under the assumption, that before this class is actually called (after the Servlet 3.0 implementation identifies the class, as a ServletContextListener interface implementation thanks to the annotation `@WebListener`), CDI *has* to be initialized as well. Not sure if such an order of the initialization is:
1. defined and mandated by the specs
2. ensured by Glassfish's implementation and it thus won't call the ServletContextListener until CDI beans (and ideally EJBs) are available
3. not ensured by Glassfish, and the risk of hitting the server with a request in the particular point in time when the ServletContextListener is already instantiated and could be called but CDI is not yet initialized is simply accepted with the consequence that there will be a potential NPE for a couple of requests, and that this state is only temporary until CDI gets fully initialized (in a kind of asynchronous way).

Which of the above is correct? If 2. is our case, then Initializing SAM with a `@WebListener` should be perfectly OK (at least for CDI) and we would not have to be concerned the SAM being called before other filters.

PS: The project linked above is my own attempt at creating a reusable and customizable SAM from inside a WAR. I'd love to get your input on it, @arjantijms. Provided you're interested, you're welcome to visit my own github space or please direct me to a place where it's more suitable for you. I'd definitely prefer not to clutter payara's space.

**Comment by arjantijms** [comment] 2015-08-13 12:06
@ratcashdev 
>Which of the above is correct? If 2. is our case, then Initializing SAM with a @WebListener should be perfectly OK (at least for CDI) and we would not have to be concerned the SAM being called before other filters.

There might be some small confusion here. The problem is there are 2 types of initialization:

1. A global per application initialization
2. A per request initialization

The ServletContextListener is concerned with ***global application wide initialization***. In this case the global part of CDI is initialized before the ServletContextListener is called. The ServletContextListener can do a global registration of a SAM here using the JASPIC provided factory.

There is no problem that I know of with global initialization. No requests will be serviced before this initialization is done. In your list above it's point 1 - "defined and mandated by the specs", but again, this is not where the problem is.

*The* problem is with ***per request initialization***.

Next to the global initialization, CDI *also* needs to be initialized for each and every request. Here it sets up the request (thread) specific things such as the request scope and session scope. This often, but not necessarily happens via a ServletRequestListener. 

See for instance http://grepcode.com/file/repo1.maven.org/maven2/org.jboss.weld/weld-core-impl/2.2.12.Final/org/jboss/weld/servlet/WeldInitialListener.java#WeldInitialListener

The big problem is now that it's not defined if a SAM should be called before or after a ServletRequestListener. And because it's not defined, different servers do this differently.

1. In case a ServletRequestListener is called BEFORE a SAM is called AND a ServletRequestListener is used to do the *per request initialization*, THEN the CDI services are available to a SAM.

2. In case a ServletRequestListener is called AFTER a SAM is called AND a ServletRequestListener is used to do the *per request initialization*, THEN the CDI services are NOT available to a SAM.

3. In case the server uses another mechanism than a ServletRequestListener to do *per request initialization*, then too it's not clear if this other mechanism should be called before or after a SAM is called.

The effect is that it's not guaranteed that CDI is available inside a SAM that's called before the resource invocation. For a portable mechanism this is not acceptable.

As mentioned above, the key insight is to distinguish between the *global initialization* that only happens once for each application, and the *per-request initialization* that happens for each and every request again and again.

**Comment by ratcashdev** [comment] 2015-08-13 12:50
Up until now I did not spot and realize the different between a `Servlet*Context*Listener` and the `Servlet*Request*Listener` in your detailed example (ascii art). Now it's perfectly clear. Thank you.

Right now my project appears to work correctly with `@SessionScoped` CDI beans and no state and session corruption is apparent, thus I assume GF uses a good order for RequestInitialization, but for the sake of peace of mind, it would be fine if the order for the request initialization inside GF could be checked and posted here. @smillidge could you please check?

**Comment by arjantijms** [comment] 2015-08-13 13:12
>Now it's perfectly clear. Thank you.

You're welcome, happy it's clear now ;)

>thus I assume GF uses a good order for RequestInitialization,

It does, in GlassFish a ServletRequestListener executes before a SAM. I researched a few servers before and found this when doing a request with a SAM and a ServletRequestListener installed:

WLS 12.1.3
SAM called
RequestListener called

JBoss Wildfly 8.2
RequestListener called
SAM called

GlassFish 4.1
RequestListener called
SAM called

So GlassFish and JBoss invoke the ServletRequestListener BEFORE a ServerAuthenticationModule (SAM) while WebLogic does so AFTER.

I've yet to test what Liberty does.

Unfortunately, it's not only CDI that needs to be initialized per request, but Java EE components (JNDI namespaces) need to be initialized as well for every request.

Here GlassFish does not seem to work. I have to dive deeper into this particular issue, but if I'm not mistaken a SAM that's called before the resource is invoked can't do a JNDI lookup in GlassFish for the java:app and java:module namespaces.

The same SAM in JBoss called at the same moment *can* do this kind of lookup.

**Comment by smillidge** [comment] 2015-08-13 15:45
@arjantijms Is there an existing GlassFish JIRA issue for the JNDI namespaces not being available?

If not I can put together a test case and raise here and on GlassFish if you consider it a bug.

**Comment by arjantijms** [comment] 2015-08-13 15:56
@smillidge 

I don't think so, but I'm not sure. I encountered this issue a while back and then created a quick local reminder for it. It's as we speak at position 68 of things I still need to do ;)

I'll give it some higher priority though and take a look at it soon, in the meantime feel free to create a test case too.

**Comment by smillidge** [comment] 2015-08-13 16:31
Do you consider it a bug, given your contributions to the Spec?

**Comment by arjantijms** [comment] 2015-08-13 16:35
@smillidge 

If it appears that it also doesn't work in the ServletRequestListener (which I suspect), then yes. It's likely a bug then.

If it somehow only doesn't work in a SAM, then it's just very unfortunate, but not a violation of the spec. I'm trying to get this clarified for Java EE 8, but it's not entirely trivial since it concerns JASPIC, Servlet, CDI and the Security EGs.

**Comment by ratcashdev** [comment] 2015-08-13 19:40
> It's really quite interesting that your method of re-using a proxy throughout the application with @Stateless proxies already created works.

At this point I share your surprise that my approach with the EJB proxies actually works, especially when you presume that EJBs won't be available in the `ServletRequestListener`.

One thing to note though: i've only used `@Stateless` EJBs in my code. Using Statefull EJBs may have had manifested certain problems. or not. I am yet to test it (or rather find a use case where I need a stateful EJB in a SAM).

**Comment by arjantijms** [comment] 2015-08-13 23:22
>you presume that EJBs won't be available in the ServletRequestListener.

Indeed, so I did a test, and they seem to work in a ServletRequestListener. This means the component namespaces are initialised, but then when a SAM is called they temporarily disappear, only to appear again right after the SAM (when the first Filter or Servlet is entered).

I have to test further, but I've a simple @Stateless EJB. No interfaces, just single method returning a String.

The following code works in a ServletRequestListener

TestEJBBean testEJBBean = (TestEJBBean) new InitialContext().lookup("java:app/comp/TestEJBBean");

Injecting the same bean via @EJB also works.

Then within the same request the SAM is called, and executing the exact same line of code now throws a naming exception.

I think (but have to check as well) that asking the CDI BeanManager for a CDI bean that is injected with an EJB (@Inject or @EJB should not matter), and then calling a method on that CDI bean may cause a "No valid EE environment" to be thrown.

I'll test this later.

**Comment by arjantijms** [comment] 2015-10-23 08:51
@ratcashdev @smillidge 
>I'll test this later.

Sorry to have taken so long to get back to this. I had the test app in my workspace but never followed-up.

I've committed the basic reproducer app here: https://github.com/arjantijms/glassfish-sam-ee-namespaces

I filed an upstream issue for it as well here: https://java.net/jira/browse/GLASSFISH-21447

**Comment by arjantijms** [comment] 2015-11-02 23:51
After some debugging on GF I posted an initial patch that seems to do the trick. It has to be polished a little still, but I've added it here: https://java.net/jira/browse/GLASSFISH-21447

**Comment by arjantijms** [comment] 2015-12-15 15:18
@smillidge @ratcashdev 
>Tracking the code this is a random System.err.println which I believe should be a log message No valid EE environment for injection of com.sample.MyAuthenticator

>https://github.com/payara/Payara/blob/7b449f9da0d851874b51ec63f497b9d8d3007016/appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java

Looking at this again, I indeed think that the EJB lookup via JNDI is strongly related to this.

The exact fragment from the above link that writes the error is:

    if (componentEnv == null ) {
        //throw new IllegalStateException("No valid EE environment for injection of " + targetClassName);
        System.err.println("No valid EE environment for injection of " + targetClassName);
        injectionContext.proceed();
        return;
    }

The fact that `componentEnv` is null is the problem I fixed in the patch mentioned in my previous comment. I have to test, but very likely that indeed fixes the initial problem of this issue as well.

**Comment by ratcashdev** [comment] 2015-12-15 21:37
I've read through your comments in https://java.net/jira/browse/GLASSFISH-21447 multiple times and trying to assemble a complete picture in my head. You proved, that for "per request initialization" the order is correct. I can only assume that this order is strictly deterministic.

What is now unclear to me, why is it, that we need to set and unset the context around the RequestListener invocation, and then again for the RealmAdapter? I mean, there must be a central  starting point that invokes both the RequestListener as well as the RealAdapter, in a pre-defined sequence. Wouldn't moving the `preInvoke` and `postInvoke` into that place make it easier and more transparent? Are there scenarios where this approach would break something?

**Comment by arjantijms** [comment] 2015-12-15 22:13
>Wouldn't moving the preInvoke and postInvoke into that place make it easier and more transparent? Are there scenarios where this approach would break something?

Frankly, I have no idea. During a single request GlassFish sets and unsets this context many times over. Every time just before an (application provided) web artefact is called.

Without having very intricate knowledge of the GlassFish internals, setting and unsetting the context just before the SAM is called seems the least intrusive method to me and most similar to what GlassFish already does for the other artefacts and so hopefully the least likely to break something.

But -why- this is needed and why it's not just set at the very beginning of the request and unset after I don't know. Perhaps GlassFish uses this to track when "container code" is running and when "application code" is running, kinda like kernel mode vs user mode in an operating system.

**Comment by smillidge** [comment] 2015-12-19 09:49
I'll take a look at the patch suggested on https://java.net/jira/browse/GLASSFISH-21447 and see if I can get the setting up of the web invocation context moved to before the SAM is called. Otherwise I will look to incorporate your fix into the Payara code base before the January release

**Comment by smillidge** [comment] 2015-12-22 18:00
I've opened a pull request. Taking @arjantijms ideas as described in GLASSFISH-21447. I've added new container events which are fired before and after the RealmAdapter is invoked. Result for the test case is now;
```shell
[#|2015-12-22T17:46:09.372+0000|INFO|Payara 4.1||_ThreadID=27;_ThreadName=http-listener-1(1);_TimeMillis=1450806369372;_LevelValue=800;|
  RequestListener initialized: Hello from EJB|#]

[#|2015-12-22T17:46:09.435+0000|INFO|Payara 4.1||_ThreadID=27;_ThreadName=http-listener-1(1);_TimeMillis=1450806369435;_LevelValue=800;|
  SAM: Hello from EJB|#]

[#|2015-12-22T17:46:09.479+0000|INFO|Payara 4.1||_ThreadID=27;_ThreadName=http-listener-1(1);_TimeMillis=1450806369479;_LevelValue=800;|
  Servlet: Hello from EJB|#]

[#|2015-12-22T17:46:09.481+0000|INFO|Payara 4.1||_ThreadID=27;_ThreadName=http-listener-1(1);_TimeMillis=1450806369481;_LevelValue=800;|
  SAM SR: Hello from EJB|#]

[#|2015-12-22T17:46:09.484+0000|INFO|Payara 4.1||_ThreadID=27;_ThreadName=http-listener-1(1);_TimeMillis=1450806369484;_LevelValue=800;|
  RequestListener destroyed: Hello from EJB|#]

```

**Comment by arjantijms** [comment] 2015-12-22 19:52
That looks absolutely great Steve! I looked at the code and it looks very well done. Approximately when do you think this can be available in a release of Payara?

**Comment by smillidge** [comment] 2015-12-22 21:32
The official release  will be the end of January. However once the pull request is merged it will be available in the prerelease  downloads on the website, if you want to test.

**Comment by ratcashdev** [comment] 2015-12-22 21:49
fantastic news, Steve.

**Closed** 2015-12-23 22:29 UTC
Labels: enhancement
