### ISSUE TITLE
Enhance documentation regarding JDBCRealm and Digest auth /CUSTCOM-68

### ISSUE THREAD

**Issue by peraxel** [payara/Payara#2260] opened 2018-01-15 08:48 UTC
# Description #
----------

Most implementations of HTTP Digest auth support storing passwords as MD5(username:realm:password) a.k.a. HA1, but Payara documentation does not give any hints as how to configure the realm to support this format. I found out that there is an undocumented setting to get support this. Set encoding->HASHED.
[Stackoverflow](https://stackoverflow.com/questions/48247919/how-to-configure-payara-jdbcrealm-jdbcdigestrealm-to-store-passwords-in-httpd-st)

Please include this in documentation and/or admin console hints.

**Comment by michaelranaldo** [comment] 2018-01-15 09:47
Hi @peraxel ,

Quite right, this could be better documented within the documentation, the admin console and the asadmin command help, where it doesn't seem to be mentioned at all.

Thanks for raising this, created internal JIRA PAYARA-2397

**Comment by rdebusscher** [comment] 2019-12-06 14:25
This is now tracked as `CUSTCOM-68`

**Comment by AlanRoth** [comment] 2020-11-11 10:57
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:57 UTC
Labels: documentation, status:accepted
