### ISSUE TITLE
Payara Micro 5.192 won't start with JDK 11 when a custom JAX-RS Feature which adds a binding to the context 

### ISSUE THREAD

**Issue by clive-jevons** [payara/Payara#4046] opened 2019-06-14 13:03 UTC
# Description #
----------

I realise JDK11 support is only a tech preview in 5.192, but wanted to provide what I experienced as feedback in the hope that it will help complete this feature for the 193 release.

Currently trying to test our app with Payara Micro 5.192 and JDK 11 - but receive an Exception on startup that ASM 7 is required.

## Expected Outcome

Server starts without exception.

## Current Outcome

Fails with:

java.lang.UnsupportedOperationException: This feature requires ASM7
        at jersey.repackaged.org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
        at jersey.repackaged.org.objectweb.asm.ClassReader.accept(ClassReader.java:550)
        at jersey.repackaged.org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener.process(AnnotationAcceptingListener.java:146)
        at org.glassfish.jersey.server.ResourceConfig.scanClasses(ResourceConfig.java:885)
        at org.glassfish.jersey.server.ResourceConfig._getClasses(ResourceConfig.java:839)
        at org.glassfish.jersey.server.ResourceConfig.getClasses(ResourceConfig.java:748)
        at org.glassfish.jersey.server.ResourceConfig$WrappingResourceConfig._getClasses(ResourceConfig.java:1117)
        at org.glassfish.jersey.server.ResourceConfig.getClasses(ResourceConfig.java:748)
        at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1175)
        at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1148)
        at org.glassfish.jersey.server.ResourceConfig.createRuntimeConfig(ResourceConfig.java:1144)
        at org.glassfish.jersey.server.ApplicationHandler$RuntimeConfigConfigurator.init(ApplicationHandler.java:182)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$0(ApplicationHandler.java:290)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)

## Steps to reproduce (Only for bug reports) 

I created a minimal web app using gradle with the war and fish.payara.micro-gradle-plugin and started it using gradle microStart.

This results in the exception listed above being thrown and the app not being deployed.

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Micro
- **JDK Version**: 11.0.2 OpenJDK
- **Operating System**: Mac OS 10.14.5

**Comment by smillidge** [comment] 2019-06-14 21:39
We will need a reproducer as Payara Micro 5.192 includes asm 7. Do you have anything packaged in your jar that shouldn't be there like asm?

**Comment by clive-jevons** [comment] 2019-06-15 13:45
Hi @smillidge 

Tried to put a minimal example together which reproduces the problem, but haven't succeeded yet 🤦🏻‍♂️

I've checked all the JARs in the app where it's not working, and the only one I can find which includes a version of asm is groovy. However, when I include the same dependency in the example everything starts up fine.

One other difference between the broken app and the working example attempt is that the former uses a custom domain.xml. I'll have a go at including that in the example app next week and see if the error pops up then.

As always, your help and thoughts are very much appreciated 😊

Will get back to you when I know more.

Cheers,
C

**Comment by clive-jevons** [comment] 2019-06-17 14:58
Hi @smillidge 

I was able to narrow down what was causing the problem - its a custom JAX-RS Feature which adds a binding to the context. I've created a minimal example which recreates this problem (see attachment).

HTH and as ever thanks for your support in this matter :)

Cheers,
C

[payara-issue-4046.zip](https://github.com/payara/Payara/files/3297557/payara-issue-4046.zip)

**Comment by MeroRai** [comment] 2019-06-21 11:57
Hi @clive-jevons 

Thank you for raising this issue. I've confirmed this is a bug. I've raised internal issue PAYARA-3959 to address it. Will keep you update.

Kind regards,
Mero

**Comment by clive-jevons** [comment] 2019-06-21 14:37
Thanks @MeroRai 😊👍

**Comment by clive-jevons** [comment] 2019-07-24 09:03
Hi @smillidge  @MeroRai ,
Any updates on this issue?
Cheers,
C

**Comment by MeroRai** [comment] 2019-08-01 08:51
Hi @clive-jevons,

I have created an internal issue for our engineering team and they have not scheduled, so we can't tell you when it will be fixed. If this issue is urgent and needs to be fixed for a deadline, please consider buying [Payara Support](https://www.payara.fish/support/) since we commit to prioritising work for our customers.

Kind Regards,
Mero

**Comment by kukiric** [comment] 2019-09-05 16:24
Hello @MeroRai, I have nailed down this issue and submitted a patch at https://github.com/payara/patched-src-jersey/pull/33. Would you mind reviewing it, assuming it isn't resolved internally?

**Comment by smillidge** [comment] 2019-10-26 20:22
Likely fixed by https://github.com/payara/patched-src-jersey/pull/41

**Comment by rdebusscher** [comment] 2019-12-20 14:14
Tested with Payara Micro 5.194 on JDK11 and issue is fixed.

**Closed by rdebusscher** 2019-12-20 14:14 UTC
Labels: JDK-11+, c:ConfirmedBug
