### ISSUE TITLE
Payara 5.184: Web GUI 'REST Endpoints' mixes endpoints of several same-name JAX-RS applications /CUSTCOM-103

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#3726] opened 2019-02-13 15:04 UTC
# Description #
----------

The web GUI's 'REST Endpoints' panel mixes endpoints of *several* applications having the same name. This is in contrast to what it pretends, as it says "belonging to a *selected* component" (not *all* components).

## Expected Outcome

Lists only the endpoints of the *selected* component.

## Current Outcome

Lists also the endpoints of *non-selected* components having the same name as the *selected* component.

## Steps to reproduce (Only for bug reports) 

* Deploy EAR containing two WARs, where each WAR contains the JAX-RS class 'App' and some JAX-RS resources.

* In the web GUI click on "Common Tasks > Applications > (your ear) > View Endpoints

### Samples

https://github.com/mkarg/payara-bug-ear/tree/payara-bug-componentnames

## Context (Optional)

This could happen, and is very nasty, in case several third-party WARs have to be shipped together in one EAR. While it is considered harmless, it is confusing.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: Azul Zulu 1.8.0_181-b02
- **Operating System**: Windows, Linux
- **Database**: N/A

**Comment by rdebusscher** [comment] 2019-02-21 09:47
Hi Markus,

Thanks for this report and the example which demonstrates the problem.

The mixture of JAX-RS resources only happens in the case the JAX-RS application class has the same name AND is defined in the same package.

I have created an internal development ticket to correct this issue under the id `PAYARA-3506`.

Thx
Rudy

**Comment by rdebusscher** [comment] 2019-12-18 09:17
Tracked now as `CUSTCOM-103`

**Comment by AlanRoth** [comment] 2020-11-11 11:31
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:31 UTC
Labels: enhancement, status:accepted
