### ISSUE TITLE
websocket action on idle timeout event stay alive after closing connection

### ISSUE THREAD

**Issue by dasvex** [payara/Payara#2564] opened 2018-03-24 21:26 UTC
Description 
----------
We use simple load test for websocket "open connection" service.
In the method for "open connection" we set timeout for session : session.setMaxIdleTimeout(TIMEOUT_VALUE);
After that we close the connection, but the task of closing the timeout is still waiting.
This can be seen in heapdump.
Upon the occurrence of the timeout, the event will try to execute - and only then free memory.

## Expected Outcome

Closing the websocket session remove the timeout task

## Current Outcome

Closing the websocket session did not remove the timeout task

## Steps to reproduce (Only for bug reports) 

using default configuration
for reproduce can be used simple class : 
   
    @ServerEndpoint("/endpoint")
    public class CloseTimeoutIssueService {
        private static final Logger loger = Logger.getLogger(CloseTimeoutIssueService.class.getName());

        @OnOpen
        public void onOpen(Session session) {
            try {
                loger.info("Session " + session.getId() + " opened");
                session.setMaxIdleTimeout(1000L*60*10);
                session.close();
            } catch (IOException e) {
                System.err.println("EXCEPTION:"+e.getMessage());
            }
        }

        @OnClose
        public void onClose(Session session) {
            loger.info("Session " + session.getId() + " has ended");
        }
    }

Pack this class into war file and deploy. 
Then execute load test for open websocket connetion to /endpoint service.
Despite the fact that we close the session, the tasks remain and take up space in the memory.
As a consequence, this can lead to OutOfMemory even in the case of a small ddos attack.

see https://github.com/dasvex/gf5-ws-close-timeout-bug/blob/master/heap-dump-problem.jpg

### Samples

https://github.com/dasvex/gf5-ws-close-timeout-bug

## Context (Optional)

A simple ddos attack can cause outOfMemory

## Environment ##

- **Payara Version**: 5.181
- **Edition**: full
- **JDK Version**: Oracle 1.8_u92 jdk
- **Operating System**: windows 7 x64
- **Database**: not used 

## Reference issue
#https://github.com/javaee/glassfish/issues/22476

**Comment by dasvex** [comment] 2018-03-24 21:31
## Reference issue
#https://github.com/javaee/glassfish/issues/22476

**Comment by khasunuma** [comment] 2018-07-12 04:38
@dasvex I try to reproduce this issue. I'd like to know how much load you test when OOME. FYI, I can't reproduce under 1500 threads access on JMeter. (I think it was probably more heavy load.)

**Comment by fturizo** [comment] 2020-02-06 18:11
As the requester of this issue fell unresponsive after our initial contact, we'll close this issue. Feel free to raise a new issue if the problem is present in the current release of Payara Server 5.x

**Closed by fturizo** 2020-02-06 18:11 UTC
Labels: status:reproducer-needed
