### ISSUE TITLE
ManagedExecutorService does not work on hybrid OSGi EJBs - module is disabled

### ISSUE THREAD

**Issue by chrjohn** [payara/Payara#690] opened 2016-03-03 16:11 UTC
This probably has some overlaps with https://java.net/jira/browse/GLASSFISH-21087 or https://java.net/jira/browse/GLASSFISH-21216. However, on those issues it is said that it might have to do with order of deployment or a race condition. But in my case the EJB is fully deployed.

There are also similar problems with regard to hybrid bundles here #673 and here #681 . So there might be several positions in the code where the hybrid module case is not honoured.

My test case is an MDB. But maybe this also does not work with hybrid session beans.

It works when deployed as normal JAR, but deployed as OSGi bundle and then sending a message to the test queue there is an exception thrown:

```
[2016-03-03 16:58:29,879] [INFO ] [unknown.jul.logger] [Thread-8] [#1] XXX onMessage()
[2016-03-03 16:58:29,880] [INFO ] [unknown.jul.logger] [Thread-8] [#1] Submitting task...
[2016-03-03 16:58:29,886] [ERROR] [unknown.jul.logger] [Thread-9] [#1] java.util.concurrent.ExecutionException: javax.enterprise.concurrent.AbortedException: Module com.macd.payarabug_0.0.1.SNAPSHOT is disabled
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at payarabug.PayaraBugMDB.onMessage(PayaraBugMDB.java:35)
...
```

Deployment with:
`asadmin deploy --type osgi payarabug-0.0.1-SNAPSHOT.jar`

Prerequisites: you need to have a test queue:
`asadmin create-jms-resource --restype=javax.jms.Queue --enabled=true queue/test`

The bean is just this:

```
package payarabug;

import javax.annotation.Resource;
import javax.ejb.MessageDriven;
import javax.enterprise.concurrent.ManagedExecutorService;
import javax.jms.Message;
import javax.jms.MessageListener;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

@MessageDriven( mappedName = "queue/test" )
public class PayaraBugMDB
    implements MessageListener {

    @Resource
    private ManagedExecutorService managedExecutorService;

    public void onMessage( final Message msg ) {
        System.out.println( "PayaraBugMDB.onMessage()" );

        final Runnable task = new Runnable() {

            @Override
            public void run() {
                System.out.println( "task run()" );
            }

        };
        Future<?> future = null;
        try {
            future = managedExecutorService.submit( task );
            try {
                System.out.println( "Submitting task..." );
                future.get();
                System.out.println( "... task finished" );
            } catch ( InterruptedException | ExecutionException e ) {
                e.printStackTrace();
            }
        } finally {
            if ( future != null ) {
                future.cancel( true );
            }
        }
    }

}

```

Attached is the JAR file (renamed as ZIP).

**Comment by chrjohn** [comment] 2016-03-03 16:15
[payarabug-0.0.1-SNAPSHOT.ZIP](https://github.com/payara/Payara/files/157152/payarabug-0.0.1-SNAPSHOT.ZIP)

Attached test case. Rename to JAR and deploy with "--type osgi" option.

**Comment by chrjohn** [comment] 2016-03-04 09:30
Just tested with a session bean which gets triggered by the MDB: does not work either:

`[2016-03-04 10:27:31,188] [ERROR] [unknown.jul.logger] [Thread-9] [#1] java.util.concurrent.ExecutionException: javax.enterprise.concurrent.AbortedException: Module com.macd.payarabug_0.0.1.SNAPSHOT is disabled
`

Attached modified test case.
[payarabug-0.0.1-SNAPSHOT.zip](https://github.com/payara/Payara/files/158438/payarabug-0.0.1-SNAPSHOT.zip)

**Comment by zmarcos** [comment] 2016-03-16 21:54
If you change the method **isApplicationEnabled** to return **true** by default, should work. https://github.com/zmarcos/Payara/compare/patch-1

**Comment by chrjohn** [comment] 2016-05-23 13:55
This seems to be fixed by #366 or #204 respectively.

**Comment by chrjohn** [comment] 2016-05-23 13:55
Somehow the issue got closed automatically now? Wow. ;)

**Comment by chrjohn** [comment] 2016-05-23 14:00
But: now there are strange entries (also from #366 ) in the log file:


`[2016-05-23 15:58:21,580] [INFO ] [javax.enterprise.concurrent] [concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-2] [#1] Job submitted for com.macd.payarabug_0.0.1.SNAPSHOT likely during deployment. Continuing...
`
I also saw this for other of our applications and it repeated every minute.

**Comment by chrjohn** [comment] 2016-05-24 07:34
So it seems that if `isApplicationEnabled` is called for a hybrid app, every time the log line as stated above is logged. I don't think that this was intended.

**Comment by smillidge** [comment] 2016-05-24 07:57
Reopen this one. It looks like the enabled property of the deployment is not being set to true on a successful deployment. Which is incorrect hence the log message.

**Comment by chrjohn** [comment] 2016-05-24 11:20
Just noticed that these messages even appear every minute after the named application has been undeployed. Strange indeed.

**Comment by fturizo** [comment] 2016-12-30 22:50
Hi @chrjohn, sorry it took us a while to get back to you with this issue. Is the issue still happening with the current release of Payara Server? If so let us know to have a reproducible test case.

**Comment by chrjohn** [comment] 2017-01-02 13:24
Hi @fturizo , I will update to the newest Payara version sometime during the next weeks. I will let you know if it still happens.
Thanks,
Chris.

**Comment by chrjohn** [comment] 2017-01-03 10:46
Hi @fturizo ,

I did some tests with the test case I attached earlier.

payara-4.1.1.162 and 164 show the same behaviour: The "module is disabled" message is no longer showing but as said in https://github.com/payara/Payara/issues/690#issuecomment-221239540 the following message is printed to the log file each minute:
`Job submitted for com.macd.payarabug_0.0.1.SNAPSHOT likely during deployment. Continuing...`

These messages are even continuing after the application has been undeployed! So something very strange seems to be going on there. Maybe this has also something to do with #909 ? Since the logging messages are printed by `glassfish-internal-managedThreadFactory-Thread-1`.

Let me know if you need any further information.
Cheers,
Chris.

**Comment by fturizo** [comment] 2017-01-04 22:39
Hi @chrjohn,

I tried to reproduce this behavior using the sample **MDB** you posted a while ago and created a sample Hybrid **OSGI** - **EJB** application and deployed it to Payara Server 4.1.1.164. Unfortunately I only got the following message:

`Job submitted for fish.payara.support.GH690-OSGIEJBModuleTest_1.0.0.SNAPSHOT likely during deployment. Continuing...`

Only once per message processed on the `onMessage `method instead of once per minute as you reported it. Can you recall some configuration details that are missing that could cause this error? Otherwise I think the message itself is harmless and doesn't require paying attention at the moment, but we could look into it if needed.

Cheers.

**Comment by chrjohn** [comment] 2017-01-05 09:47
Hi @fturizo ,
I just set up a new domain from scratch and retested and indeed the log line is only shown once. I am totally out of ideas what caused the repeated occurrence on the other domain.
However, I think the only thing left to do is to maybe make the log line more fitting to the actual procedure. Or even remove it because it does not really fit the procedure since I was not submitting a job during deployment.

Many thanks for your help.
Cheers,
Chris.

**Comment by fturizo** [comment] 2017-01-25 00:17
Hi, @chrjohn. Sorry for replying this late.

Considering that this single line is printed out only when deploying hybrid **OSGi - EJB** applications (normal MDBs deployed don't generate this line from the tests I made) I consider that is quite harmless and not urgent to fix. I'm closing this issue in this case.

If you encounter a similar issue with these circumstances feel free to reopen this issue and we'll take a look at it again.

**Closed by fturizo** 2017-01-25 00:17 UTC
Labels: 1:Wait, c:PossibleBug, try to reproduce

**Comment by chrjohn** [comment] 2017-01-25 07:24
Hi @fturizo , after some more tests it showed that the line is printed every time I submit a job to the ManagedExecutorService. Since I am doing it for every JMS message there are many unnecessary lines in the log.
For the time being I have worked around this by changing the logging level for logger `javax.enterprise.concurrent` to `WARN` level.
