### ISSUE TITLE
Injection on startup is not correctly working - marking servlet as unavailable

### ISSUE THREAD

**Issue by chrjohn** [payara/Payara#765] opened 2016-04-22 13:31 UTC
This is on version 4.1.152.1 but I couldn't find any resolved issue in a newer version that deals with this.

We deployed one hybrid OSGi application (I don't know if this is important) with a simple EJB and another application with one servlet. The servlet gets an instance of the EJB from the first application injected. In the normal case everything works as expected. But we faced problems when the servlet is accessed during startup of the server. It may happen that the EJB to be injected is not deployed but yet the servlet is instantiated. This results in an exception and the message that the servlet will now be unavailable. The only workaround is to reload (via `asadmin disable/enable` or `.reload` file in the application dir) the servlet once the whole deployment is finished.

Exception:

```
[2016-04-22 15:17:14,355] [INFO ] [javax.enterprise.web._vs.server] [http-listener-1(3)] [#1] WebModule[null] ServletContext.log():Marking servlet payarabugservlet.PayaraBugServlet as unavailable
[2016-04-22 15:17:14,360] [WARN ] [javax.enterprise.web._vs.server] [http-listener-1(3)] [#1] StandardWrapperValve[payarabugservlet.PayaraBugServlet]: Allocate exception for servlet payarabugservlet.PayaraBugServlet
javax.naming.NameNotFoundException: com.macd.payarabug_0.0.1.SNAPSHOT
        at com.sun.enterprise.naming.impl.TransientContext.resolveContext(TransientContext.java:299)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:207)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
        at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:66)
        at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:478)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
...

```

Will attach the sample applications.

**Comment by chrjohn** [comment] 2016-04-22 13:33
[payarabug-0.0.1-SNAPSHOT.zip](https://github.com/payara/Payara/files/231870/payarabug-0.0.1-SNAPSHOT.zip)
[payaraservletbug-0.0.1-SNAPSHOT.zip](https://github.com/payara/Payara/files/231871/payaraservletbug-0.0.1-SNAPSHOT.zip)

**Comment by mikecroft** [comment] 2016-04-26 08:58
Thanks for the test case, I've confirmed the bug myself quite easily.

**Comment by mikecroft** [comment] 2016-04-26 09:00
Note: I recreated this on `Payara Server  4.1.1.161.1 #badassfish (63)`

**Comment by mikecroft** [comment] 2016-12-05 10:15
Internal issue ID `PAYARA-735`

**Comment by lprimak** [comment] 2017-03-24 00:03
Hi, @chrjohn 

I have looked at the issue, and it's very much non-trivial.
We have decided not to work on this issue at this time.
Of course, if the community at large wishes to help, we would appreciate that.

The usual workarounds if to disable the load balancer from accessing the instance that's loading the application, until it's loaded / deployed.  After that, the load balancer can be re-enabled (the reloading/deploying node can be added) back into the load balanced cluster

**Comment by chrjohn** [comment] 2017-03-27 14:07
Hi @lprimak ,
we cannot disable the load balancer since we have none. ;) There is just some job that accesses the servlet and `wget` was the simplest way to reproduce it.

P.S.: I am asking myself if this has some overlaps with #1279 .

**Comment by lprimak** [comment] 2017-03-27 18:33
it may overlap.  Or maybe there are other issues.
The problem is that this issue is very deep and unlikely to get fixed anytime soon, if at all.
The easiest thing for you to do is to get a load balancer.  It could be Apache (AJP), HAProxy, AWS load balancer, etc.

**Comment by smillidge** [comment] 2019-02-02 22:59
This was closed in our jira please reopen if still a problem on the latest JIRA

**Closed by smillidge** 2019-02-02 22:59 UTC
Labels: 1:Wait, Help Wanted, c:ConfirmedBug, reproducible, upstream bug
