### ISSUE TITLE
SseEventSink is NOT closed even client closed the connection /CUSTCOM-220

### ISSUE THREAD

**Issue by hei1233212000** [payara/Payara#2897] opened 2018-06-25 14:47 UTC
# Description #
----------

I found that the SseEventSink is NOT closed even client closed the connection.
I created a POC for it: https://github.com/hei1233212000/payara-sse

## Expected Outcome

1. The corresponding SseEventSink should be closed when client close the connection
2. The SseBroadcaster.onClose() should be triggered when client close the connection

## Current Outcome

1. The corresponding SseEventSink keep opening when client close the connection
2. The SseBroadcaster.onClose() is NOT triggered when client close the connection

## Steps to reproduce (check out https://github.com/hei1233212000/payara-sse first) 

1. run the application `gradlew clean build runApp`
2. go to http://localhost:8080/payara-sse/
3. click the "Subscribe" button, then you can see the server log will show subscription is done
4. open the other browser and repeat the steps 2 and 3
5. click the "Increase Counter" button, you will see the counter in the BOTH web page will be increased and there is a log message in server console too
6. now click the "Unsubscribe" button in either one web page, **there is NO log printed in the server side which is NOT expected**
7. Go to the web page which is still subscribing the stream and click the "Increase Counter" button
8. So, the counter in the page is still subscribing the stream will be updated; the counter in the page is NOT subscribing the stream will remain. It show that the "unsubscribe" is working and the stream connection should be closed by client side
9. For double check, you could ge to http://localhost:8080/payara-sse/api/counter/event-status to check if there is any event stream is closed (true means closed)

### Samples

https://github.com/hei1233212000/payara-sse

## Context (Optional)

This issue make you NOT able to determine if the SSE connection is closed or not in server side

## Environment ##

- **Payara Version**: 5.181+
- **Edition**: Micro
- **JDK Version**: 8 u172 - Oracle
- **Operating System**: Mac/Window
- **Database**: N/A

**Comment by fturizo** [comment] 2020-02-07 15:08
@hei1233212000, is this issue still present in the latest release of Payara Server 5.x? Can you verify this?

**Comment by hei1233212000** [comment] 2020-02-08 11:42
Hi @fturizo, I just updated the Payara version to 5.194 and re-test it. The issue is still exist

**Comment by hei1233212000** [comment] 2020-02-08 11:42
Please check my sample again.

**Comment by hei1233212000** [comment] 2020-02-08 16:18
I added a test to show the issue: https://github.com/hei1233212000/payara-sse/blob/master/src/test/kotlin/poc/feature/counter/SseTest.kt

**Comment by fturizo** [comment] 2020-02-27 22:27
Thanks for confirming that the issue is still present, @hei1233212000. However, can you submit your reproducer to use Java instead of Kotlin? Even though we understand that any JVM language can be used with the Jakarta EE APIs, we only provide community support for Java applications at the moment. Once you submit your reproducer in Java we'll proceed to verify it.

**Comment by hei1233212000** [comment] 2020-02-28 01:31
I changed the project to be a Java project now. (https://github.com/hei1233212000/payara-sse/blob/master/src/test/java/poc/feature/counter/SseTest.java)
Cheers.

**Comment by fturizo** [comment] 2020-03-03 00:00
@hei1233212000, many thanks for submitting the reproducer as requested. However, after examining the reproducer's code and the details you submitted in the request, it seems that there's a bit of confusion on your part on how the JAX-RS SSE API is supposed to work. You claim that there's an error since the `SSEBroadcaster.onClose` observer is not called when the event source is closed on the client, correct? If so, I'm afraid to tell you that **this method will only be called when the respective broadcaster object is closed**, not when any of the event sources sent by it are closed. 

Based on your code, it seems that the intent is to detect when the SSE sources sent by the client are closed on the server-side, correct? If this is the case, I'm afraid that you can't observe the closure of any SSE event sources with the current capabilities of the API. My recommendation is that you bring your full use case to the [Payara Forum](https://groups.google.com/forum/#!forum/payara-forum) and request assistance on how to correctly implement it.

Since this request does not relate to any defects in the Payara Platform, I'll proceed to close this issue then.

**Comment by hei1233212000** [comment] 2020-03-03 00:21
However, in the Javadoc of [SseBroadcaster.onClose()](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/sse/SseBroadcaster.html#onClose-java.util.function.Consumer-)

> Register a listener, which will be called when the SSE event output has been closed (either by client closing the connection or by calling SseEventSink.close() on the server side.

So, my expectation should be valid, right?

**Comment by fturizo** [comment] 2020-03-05 20:05
@hei1233212000, you are absolutely correct, so allow me to offer apologies for the confusion. The official spec docs on how the JAX-RS SSE API should treat the event stream being closed from the client is not that clear, bu the API for the `SSEBroadcaster` class is perfectly clear in that it should observe the close event for the strem no matter what. 

To fix this bug I have raised the internal JIRA Issue `CUSTCOM-220` so that is it fixed in a future release.

**Comment by hei1233212000** [comment] 2020-03-06 00:16
@fturizo thank you for the clarification :)

**Comment by AlanRoth** [comment] 2020-11-11 11:21
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:21 UTC
Labels: status:accepted
