### ISSUE TITLE
EJB JNDI broken?? ASURLClassLoader exception (NCLS-COMUTIL-00014)

### ISSUE THREAD

**Issue by mlb1141** [payara/Payara#522] opened 2015-11-13 16:22 UTC
I believe I have somehow broken my EJB JNDI connection.  I am repeatedly getting the following exception in ASURLClassLoader.  It indicates the parameter is incorrect, but I have no idea what parameter it is talking about.  Any suggestions appreciated.

[2015-11-13T03:42:55.845-0600] [Payara 4.1] [INFO] [NCLS-COMUTIL-00014] [javax.enterprise.system.util] [tid: _ThreadID=19 _ThreadName=RunLevelControllerThread-1447407772075] [timeMillis: 1447407775845] [levelValue: 800] [[
  Exception in ASURLClassLoader
java.io.IOException: The parameter is incorrect
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
	at java.io.File.getCanonicalPath(File.java:618)
	at com.sun.enterprise.loader.ASURLClassLoader$2.run(ASURLClassLoader.java:489)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.enterprise.loader.ASURLClassLoader.findResource0(ASURLClassLoader.java:458)
	at com.sun.enterprise.loader.ASURLClassLoader.findResource(ASURLClassLoader.java:545)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:232)
	at com.sun.enterprise.loader.ASURLClassLoader.getResourceAsStream(ASURLClassLoader.java:930)
	at java.util.ResourceBundle$Control$1.run(ResourceBundle.java:2674)
	at java.util.ResourceBundle$Control$1.run(ResourceBundle.java:2659)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2658)
	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1501)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1465)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1361)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1082)
	at java.util.logging.Logger.findResourceBundle(Logger.java:1862)
	at java.util.logging.Logger.setupResourceInfo(Logger.java:1920)
	at java.util.logging.Logger.<init>(Logger.java:378)
	at java.util.logging.LogManager.demandLogger(LogManager.java:554)
	at java.util.logging.Logger.demandLogger(Logger.java:452)
	at java.util.logging.Logger.getLogger(Logger.java:550)
	at org.glassfish.pfl.basic.logex.WrapperGenerator.makeWrapper(WrapperGenerator.java:605)
	at com.sun.corba.ee.spi.logging.OMGSystemException.<clinit>(OMGSystemException.java:80)
	at com.sun.corba.ee.spi.orb.ORB.<clinit>(ORB.java:362)
	at com.sun.corba.ee.spi.osgi.ORBFactory.create(ORBFactory.java:74)
	at org.glassfish.enterprise.iiop.impl.GlassFishORBManager.initORB(GlassFishORBManager.java:585)
	at org.glassfish.enterprise.iiop.impl.GlassFishORBManager.getORB(GlassFishORBManager.java:265)
	at org.glassfish.enterprise.iiop.impl.GlassFishORBFactoryImpl.createORB(GlassFishORBFactoryImpl.java:93)
	at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:162)
	at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getProtocolManager(GlassFishORBHelper.java:230)
	at com.sun.ejb.containers.BaseContainer.initializeProtocolManager(BaseContainer.java:898)
	at com.sun.ejb.containers.BaseContainer.<init>(BaseContainer.java:657)
	at com.sun.ejb.containers.StatelessSessionContainer.<init>(StatelessSessionContainer.java:143)
	at com.sun.ejb.containers.StatelessSessionContainer.<init>(StatelessSessionContainer.java:137)
	at com.sun.ejb.containers.StatelessContainerFactory.createContainer(StatelessContainerFactory.java:61)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:225)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:291)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:99)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:206)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:314)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
]]

**Comment by smillidge** [comment] 2015-11-13 16:55
Is the directory structure too deep for Windows NT?

**Comment by smillidge** [comment] 2015-11-13 16:57
Alternatively something has a ':' in the filename

**Comment by mlb1141** [comment] 2015-11-13 17:10
Are you suggesting I enter "asadmin list-jndi-entries and check if there is a colon in any of the the jndi names?

**Comment by mlb1141** [comment] 2015-11-13 17:15
Is there a way to clear my existing ejb entries?  If it is malformed, I assume I will not be able to do an "unbind"

**Comment by smillidge** [comment] 2015-11-14 07:32
I don't think it is a JNDI entry as the stack trace looks like the Logging subsystem is trying to load a resource bundle. Is the path too deep on Windows ie the payara installation is generating pathnames longer that the Windows limit. Perhaps because of where it is installed.

Is this a new installation?

**Comment by mlb1141** [comment] 2015-11-16 05:37
Yes. in attempt to solve this issue I have reinstalled Payara 4.1.1.154 several times. 

 I have tried to run my client in debug mode.  I believe I got the default initial context with the following entries:
java.naming.factory.url.pkgs= com.sun.enterprise.naming and
java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory.

I finally got this message: (I did not have the source code for this module loaded)
// Compiled from SerialContext.java (version 1.7 : 51.0, super bit)
public class com.sun.enterprise.naming.impl.SerialContext implements javax.naming.Context {
  
  // Field descriptor #212 Ljava/lang/String;
  @org.glassfish.logging.annotation.LogMessageInfo(message="Exception during name lookup : {0}",
    cause="App Server may not be running at port intended, or possible Network Error.",
    action="Check to see if the AppServer is up and running on the port intended. The problem could be because of incorrect port. Check to see if you can access the host on which the AppServer running.")
  public static final java.lang.String EXCEPTION_DURING_LOOKUP = "AS-NAMING-00002";
  
I have the admin console running on port 4848 successfully.  In the literature I have seen mention of port 3700 but I do not believe I have used anything that was not a default.  I hope this sheds some light on the issue.  Thanks for all your help!

**Comment by mlb1141** [comment] 2015-11-16 05:38
Oops accidentally closed so I re-opened it.

**Comment by smillidge** [comment] 2015-11-19 18:19
Is that last error from the client? What JNDI properties are you passing into the Initial Context creation?

**Comment by OndrejM** [comment] 2016-03-10 11:16
@mlb1141, do still encounter the error? Do you think you can describe your setup so that we may reproduce it?

**Comment by mikecroft** [comment] 2016-06-10 12:38
Is this related to #519 or does it supersede that one?

**Comment by mikecroft** [comment] 2016-07-26 10:17
Is this still an issue @mlb1141?

**Comment by mikecroft** [comment] 2016-08-16 08:54
I'm going to close this now since we can't move forward without more input.

It looks like the problem was most likely due to the installation location in Windows.

**Closed by mikecroft** 2016-08-16 08:54 UTC
Labels: 1:Wait, c:Question, requestor unresponsive (1), requestor unresponsive (2)
