### ISSUE TITLE
flush JDBC Connection Pool  fails /CUSTCOM-66

### ISSUE THREAD

**Issue by bakkc** [payara/Payara#1873] opened 2017-08-17 07:43 UTC
# Description #
----------

When using the Flush button to reset jdbc connections error raises in the UI

## Expected Outcome

jdbc connections should re-initialize on the targets

## Current Outcome

An error has occurred
Flush Connection Pool failed for xxxx_jdbc_pool. Flush Connection Pool did not happen as pool - xxxx_jdbc_pool is not initialized. Please check the server.log for more details.

## Steps to reproduce (Only for bug reports) 

Press Flush button.

Login UI payara--> JDBC -->JDBC Connection Pools --> xxxx_jdbc_pool--> Flush button

## Environment ##

- **Payara Version**: Payara Server 4.1.2.172 #badassfish (build 235)
- **Edition**: Full
- **JDK Version**: java-1.8.0-openjdk-1.8.0.111-1.b15.el7_2.x86_64
- **Operating System**: RHEL 7.2
- **Database**: Oracle 12c

**Comment by smillidge** [comment] 2017-08-20 20:07
This is expected behaviour. The connection pool isn't initialised until it is first used. If an application has requested a connection from the pool then Flush Pool works as expected.

**Comment by lprimak** [comment] 2017-08-20 23:33
From the users perspective it shouldn't give an error but rather be a no-op. I found this very confusing

**Comment by bakkc** [comment] 2017-08-21 07:45
i'd expect that de connections to the oracle database would be dropped and that re-initialized.
Or is this only for active sessions that are using the pool?

**Comment by ggam** [comment] 2017-08-21 08:03
+1 with an info message saying that it was no-op.

As a side note, I've faced some case where the database was unavailable at
deployment time (e.g. stopped database), but then after starting the
database process, the application keeps seeing the uninitialized pool.
There's no way to fix it but redeploying/restarting the server.

@bakkc is this also your situation? In that case the solution might be to
make the flush initialize the pool in case it was already requested but
failed?

Btw, WildFly initializes the pool even if the database can't be reached.
That way it automatically works when the database problems are solved. I
see that as a more relisient solution. Just in case the idea adds some
value.

**Comment by bakkc** [comment] 2017-08-23 09:52
In our case the database is still up.  We are implementing oracle editions (versioning) in our database , and have de possibility to set new connections from one version to the other. But this is only for new connections, and the database keeps old sessions open. We can manage this by reducing the idle timeout of the oracle session, so they will be dropped after $timeout. I was hoping that the flush button would do the same.

**Comment by rdebusscher** [comment] 2019-12-05 15:54
This issue is tracked internally as `CUSTCOM-66`.

**Comment by AlanRoth** [comment] 2020-11-11 10:55
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:55 UTC
Labels: status:accepted
