### ISSUE TITLE
Java 8 fetuares not working with embedded payara while using scannotation plugin

### ISSUE THREAD

**Issue by meghajain27** [payara/Payara#689] opened 2016-03-03 10:40 UTC
Hi

I am using embedded payara for running the ejb test cases, but if i Use java8 features like Lambda or streams i ma getting the below exception while executing the test cases, the same error i am getting with embedded Glassfish 4.1 also

similar issue was also raised in 
similar issue was also raised in the below Jira link 
https://java.net/jira/browse/HK2-136

but i am able to use the same features in jax-rs layer while using payara 4.1

A java.io.IOException was encountered during plugin execution
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: A java.io.IOException was encountered during plugin execution
	at com.jenzabar.maven.scannotation.ListEntitiesMojo.execute(ListEntitiesMojo.java:130)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.io.IOException: invalid constant type: 18
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1023)
	at javassist.bytecode.ConstPool.read(ConstPool.java:966)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
	at javassist.bytecode.ClassFile.read(ClassFile.java:693)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
	at org.scannotation.AnnotationDB.scanClass(AnnotationDB.java:311)
	at org.scannotation.AnnotationDB.scanArchives(AnnotationDB.java:294)
	at com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:152)
	at com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:133)
	at com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:109)
	at com.jenzabar.maven.scannotation.ListEntitiesMojo.execute(ListEntitiesMojo.java:128)
	... 21 more

**Comment by smillidge** [comment] 2016-03-03 15:26
Hi 
I can't seen any Payara code in the stack trace you have sent. The error seems to be coming from 
```
  Caused by: java.io.IOException: invalid constant type: 18
  at javassist.bytecode.ConstPool.readOne(ConstPool.java:1023)
  at javassist.bytecode.ConstPool.read(ConstPool.java:966)
  at javassist.bytecode.ConstPool.(ConstPool.java:127)
  at javassist.bytecode.ClassFile.read(ClassFile.java:693)
  at javassist.bytecode.ClassFile.(ClassFile.java:85)
  at org.scannotation.AnnotationDB.scanClass(AnnotationDB.java:311)
  at org.scannotation.AnnotationDB.scanArchives(AnnotationDB.java:294)
  at   com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:152)
  at  com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:133)
  at com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:109)
  at com.jenzabar.maven.scannotation.ListEntitiesMojo.execute(ListEntitiesMojo.java:128)

```

There are no org.scannotation or com.jenzabar classes packaged in Payara Server.

**Comment by meghajain27** [comment] 2016-03-03 16:35
Hi 
Actually we are using scannotaion plugin (which we have overridden) for our web application while executing the  ejb test case and for that we are using payara-embedded-all.

if we don't use java8 feature like stream it works fine but if we add then we get this error while listing the entities during scanning.
the same issue is coming with embedded glassfish  as well. below is the jira raised for the same. 
https://java.net/jira/browse/HK2-136
   
I think it is because of the asm-all-repackaged jars used by hk2.external in Payara server, which are not compatible with java8 features.

**Comment by smillidge** [comment] 2016-03-03 17:34
javassist shipped with Payara Server is 3.18.1.GA which is pretty new.

**Comment by meghajain27** [comment] 2016-03-04 10:55
Hi 
I have created a simple ejb project with the jUnit test (Integration test).
i am using embedded payara to execute the test cases
if i use java8 Lambda expression in any of my ejb business logic my test case fails  (**lookup failed exception appears)**
i have used the following dependency

<dependency>
	<groupId>fish.payara.extras</groupId>
	<artifactId>payara-embedded-all</artifactId>
	<version>4.1.152.1</version>
        <scope>test</scope>
    </dependency>



below is the stack trace and the test file
Lookup failed for 'java:global/classes/NewSessionBean' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}
javax.naming.NamingException
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:491)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.megha.testejbproject.NewSessionBeanTest.testAddNumbers(NewSessionBeanTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: javax.naming.NameNotFoundException: classes
	at com.sun.enterprise.naming.impl.TransientContext.resolveContext(TransientContext.java:299)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:207)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
	at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:66)
	at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:478)
	... 37 more



attached are the files for![image]
ejb 
(https://cloud.githubusercontent.com/assets/17614148/13525111/165fc1d4-e225-11e5-9bb2-acd981de5fd6.png)

Test class


package com.megha.testejbproject;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.ejb.embeddable.EJBContainer;
import junit.framework.Assert;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author megha.jain
 */
public class NewSessionBeanTest {
    private static EJBContainer container;
    
    public NewSessionBeanTest() {
    }
    @BeforeClass
    public static void setUpClass() {
        Map<String, Object> properties = new HashMap<String, Object>();
    properties.put(EJBContainer.MODULES, new File("build/jar"));
    container = EJBContainer.createEJBContainer(properties);
    System.out.println("Opening the container");
    }
    
    @AfterClass
    public static void tearDownClass() {
        container.close();
    System.out.println("Closing the container");
    }
    /**
     * Test of businessMethod method, of class NewSessionBean.
     */
    @Test
    public void testBusinessMethod() throws Exception {
        System.out.println("businessMethod");
        NewSessionBean instance = (NewSessionBean)container.getContext().lookup("java:global/classes/NewSessionBean");
        instance.businessMethod();
            
    }

    /**
     * Test of addNumbers method, of class NewSessionBean.
     */
    @Test
    public void testAddNumbers() throws Exception {
        System.out.println("addNumbers");
        int numberA = 1;
        int numberB = 2;
        //EJBContainer container = javax.ejb.embeddable.EJBContainer.createEJBContainer();
        NewSessionBean instance = (NewSessionBean)container.getContext().lookup("java:global/classes/NewSessionBean");
        int expResult = 3;
        int result = instance.addNumbers(numberA, numberB);
        assertEquals(expResult, result);
        
    }
 @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }
  
}

**Comment by meghajain27** [comment] 2016-03-04 10:58
same error is also coming with embedded glassfish 4.1
http://stackoverflow.com/questions/35230667/glassfish-embedded-v4-1-1-and-lambda

**Comment by smillidge** [comment] 2016-03-05 23:08
Hi thanks this is reproducible. The jar is failing to deploy on embedded with the Lambda expression. The hidden error is;
`java.lang.ArrayIndexOutOfBoundsException: 52264
	at org.objectweb.asm.ClassReader.readClass(ClassReader.java:2015)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:469)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
	at   org.glassfish.deployment.common.GenericAnnotationDetector.scanArchive(GenericAnnotationDetector.java:145)
	at org.glassfish.deployment.common.GenericAnnotationDetector.hasAnnotationInArchive(GenericAnnotationDetector.java:96)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.getRequestedEJBModuleOrLibrary(EJBContainerProviderImpl.java:336)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModule(EJBContainerProviderImpl.java:381)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModules(EJBContainerProviderImpl.java:284)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.createEJBContainer(EJBContainerProviderImpl.java:130)
	at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:127)
	at com.megha.testejbproject.NewSessionBeanTest.setUpClass(NewSessionBeanTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
`

**Comment by smillidge** [comment] 2016-03-05 23:44
Duplicate of #647

**Closed by smillidge** 2016-03-05 23:44 UTC
Labels: duplicate, reproducible, upstream bug

**Comment by Vittalb** [comment] 2017-02-15 07:23
The Issue still existing with Payara Embedded 4.1.1.164 version. When I run test cases which has Lamda Expression code , getting below error

```
[ERROR] Failed to execute goal com.jenzabar.testing:jenzabar-maven-scannotation-plugin:13:list-entities (Generate JPA entity properties file) on project ngp-con
stituent-alert-ejb: A java.io.IOException was encountered during plugin execution: invalid constant type: 18 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.jenzabar.testing:jenzabar-maven-scannotation-plugin:13:list-entities (Generat
e JPA entity properties file) on project ngp-constituent-alert-ejb: A java.io.IOException was encountered during plugin execution
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: A java.io.IOException was encountered during plugin execution
        at com.jenzabar.maven.scannotation.ListEntitiesMojo.execute(ListEntitiesMojo.java:130)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: java.io.IOException: invalid constant type: 18
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1023)
        at javassist.bytecode.ConstPool.read(ConstPool.java:966)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
        at javassist.bytecode.ClassFile.read(ClassFile.java:693)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
        at org.scannotation.AnnotationDB.scanClass(AnnotationDB.java:311)
        at org.scannotation.AnnotationDB.scanArchives(AnnotationDB.java:294)
        at com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:152)
        at com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:133)
        at com.jenzabar.maven.scannotation.AbstractScannotationMojo.scan(AbstractScannotationMojo.java:109)
        at com.jenzabar.maven.scannotation.ListEntitiesMojo.execute(ListEntitiesMojo.java:128)
```

**Comment by mulderbaba** [comment] 2017-02-15 11:58
@Vittalb do you have a test case for this one?
