### ISSUE TITLE
JMS 2.0 bug (Container managed JMSContext)

### ISSUE THREAD

**Issue by vkalayda** [payara/Payara#1278] opened 2017-01-10 05:47 UTC
Hello everyone,

Looks like something wrong with connections in JMS 2.0

Using JMS 2.0 API  we are faced with following exception:

> Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4542)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2021)
	... 99 more
Caused by: com.sun.messaging.jms.MQRuntimeException: MQRA:CFA:allocation failure:createConnection:Error in allocating a connection. Cause: java.lang.IllegalStateException: Wrong XAState: 0
	at com.sun.messaging.jmq.jmsclient.JMSContextImpl.<init>(JMSContextImpl.java:230)
	at com.sun.messaging.jms.ra.ConnectionFactoryAdapter.createContext(ConnectionFactoryAdapter.java:182)
	at org.glassfish.jms.injection.AbstractJMSContextManager.createContext(AbstractJMSContextManager.java:80)

You can reproduce with this project: https://github.com/vkalayda/ee-jms-20-bug

**How to reproduce**

* Create JMS Destination Resource - jms/TestMessageQueue
* Build and Deploy project "ee-jms-20-bug"
* Execute following command "ab -n 100 -c 10 http://localhost:8080/ee-jms-20-bug/resources/test/jms20"
 
But with JMS 1.1 we haven't errors

* Execute following command "ab -n 100 -c 10 http://localhost:8080/ee-jms-20-bug/resources/test/jms11"

Another one interesting thing - Removing `@Stateless` annotation from "MessageSender20" (put it under the CDI container) will eliminate exceptions.

Also if each time create and close the JMSContext (Application Managed JMSContext) all works fine.

```
@Resource(mappedName = "jms/TestMessageQueue")
    private Queue testMessageQueue;

    @Resource(lookup = "java:comp/DefaultJMSConnectionFactory")
    private ConnectionFactory connectionFactory;

    public void send() {
        try (JMSContext context = connectionFactory.createContext()) {
            context.createProducer().send(testMessageQueue, "Hello world");
        }
    }
```

From JMSContext documentation:

https://docs.oracle.com/javaee/7/api/javax/jms/JMSContext.html

> A JMSContext may be created by calling one of several createContext methods on a ConnectionFactory. A JMSContext that is created in this way is described as being application-managed. An application-managed JMSContext must be closed when no longer needed by calling its close method.

This works.

> Applications running in the Java EE web and EJB containers may alternatively inject a JMSContext into their application using the `@Inject` annotation. A JMSContext that is created in this way is described as being container-managed. A container-managed JMSContext will be closed automatically by the container.

Doesn't work.

Was reproduced on Full **Payara 4.1.1.164**

**Comment by michaelranaldo** [comment] 2017-01-24 13:31
Hi @vkalayda,
We've reproduced the issue and confirmed that it is a bug. We have an internal issue `PAYARA-1354` set up.
Thanks for sending on your example.

**Comment by vkalayda** [comment] 2017-01-25 11:54
Hello @michaelranaldo,

Thank you for your feedback.

**Comment by smillidge** [comment] 2017-01-29 20:35
I've investigated this and there is a very subtle bug either in your application or in Payara related to the transaction boundaries.

The cause is you have 2 layers of session bean

TestResource -> starts a TX calls Message Sender20
Message Sender 20 send is invoked and the JMS Context joins the transaction and is a transaction scoped bean
Message Sender 2 method completes and the session bean is released back into the bean pool.
Test Resource Method completes, the transaction is committed and the JMS Context is now closed.

The bug occurs in the time window between the MessageSender2 session bean being released back to the pool and the transaction commit which releases the JMS context. As a second thread can invoke the MessageSender2 bean again (as it is free in the pool) before the first thread's transaction is complete and thereby use the same JMS context causing a race condition.

Setting ```java@TransactionAttribute(REQUIRES_NEW)``` onto your send() method on MessageSender20 also fixes the problem as it aligns the transaction boundary with the session bean method call.

**Comment by michaelranaldo** [comment] 2017-02-07 10:27
Hi @vkalayda,
Did @smillidge 's suggestions of setting @TransactionAttribute(REQUIRES_NEW) on your send() method in MessageSender20 help you or changing the JAX-RS class to @ApplicationScoped without changing any transaction properties on the MessageSender20 help you?

**Comment by vkalayda** [comment] 2017-02-07 12:22
Hello @michaelranaldo 

True, Setting @TransactionAttribute(REQUIRES_NEW) onto send() method on MessageSender20 fixes the problem.

But this is inappropriate in the real project - in the case when JMS message should be sent if transaction finished successfully.

I just close JMSContext each time

> try (JMSContext context = connectionFactory.createContext()) {
            context.createProducer().send(testMessageQueue, "Hello world");
        }

**Comment by michaelranaldo** [comment] 2017-02-21 13:57
Hi @vkalayda,

Just to check, did you have a look at changing the JAX-RS class to @ApplicationScoped? This wouldn't mean making any changes to your transaction boundaries.

**Comment by michaelranaldo** [comment] 2017-04-03 13:47
Hi @vkalayda  did you have any luck with the alternative solutions or are you still having trouble?

**Comment by vkalayda** [comment] 2017-05-08 04:42
Hello @michaelranaldo I am just close JMSContext each time and this works perfect.

**Comment by vkalayda** [comment] 2017-05-08 04:44
Of course, I can play with annotations, but closing JMSContext is the easiest way.

**Comment by vkalayda** [comment] 2017-05-08 04:48
By the way, in the real application i have no REST endpoint annotated with "@Stateless". In the real application I have the boundary class - Service and of course it is Stateless.

**Comment by michaelranaldo** [comment] 2017-05-08 09:13
@vkalayda I'm glad you've found a solution to the scopes; that makes more sense with the real implementation.

**Comment by michaelranaldo** [comment] 2017-05-17 08:12
Hi @vkalayda ,

Just to clarify, what did you mean by 

> But this is inappropriate in the real project - in the case when JMS message should be sent if transaction finished successfully.

**Comment by vkalayda** [comment] 2017-05-17 11:37
Hello @michaelranaldo 

I mean that I can't send JMS message in the different transaction.
A message should be sent if whole flow (several actions) successfully completed.
In this flow, database participates too.

**Comment by vkalayda** [comment] 2017-05-17 11:41
So if during execution of flow some exception occurs - the transaction will be rolled back and a message will not be sent.

**Comment by michaelranaldo** [comment] 2017-05-17 13:01
Hello @vkalayda ,

That makes sense. We've created an internal issue (PAYARA-1354) for the identified bug.

Thanks for your help!

**Comment by vkalayda** [comment] 2017-05-17 13:14
Thank you very much, guys!

**Comment by lprimak** [comment] 2018-01-29 05:45
Right now, this issue can be resolved by setting system property ```org.glassfish.jms.skip-resource-registration-in-transaction=true```

This causes no negative sideffects and makes the system work as desired.
I will take a look if we can track down this specific bug and fix it the "proper" way nonetheless, if we can.
Meanwhile, the above system property can be used in production

**Comment by lprimak** [comment] 2018-01-30 01:22
With PR #2338 the test passes, even without ```org.glassfish.jms.skip-resource-registration-in-transaction=true```
However, the new default will be ```org.glassfish.jms.skip-resource-registration-in-transaction=true``` and that will not even try to do duplicate work with the system property.

**Closed** 2018-01-31 18:54 UTC
Labels: 4:Ready, c:ConfirmedBug, reproducible, upstream bug
