### ISSUE TITLE
CPU usage high and looks like infinity loop

### ISSUE THREAD

**Issue by matsuk55** [payara/Payara#1555] opened 2017-04-25 11:04 UTC
# Description #
----------

Restart domain, The server CPU usage is always 90%.

And I get Full Tread Dump. 

Some thread looks like infinity loop.

~~~
Thread Execution Information:
-----------------------
Thread "http-listener-2-expirer(1)" thread-id: 58 thread-state: RUNNABLE
	 at: java.lang.Thread.interrupt0(Native Method)
	 at: java.lang.Thread.interrupt(Thread.java:923)
	 at: org.glassfish.grizzly.threadpool.AbstractThreadPool$4.doWork(AbstractThreadPool.java:163)
	 at: org.glassfish.grizzly.threadpool.AbstractThreadPool$4.doWork(AbstractThreadPool.java:159)
	 at: org.glassfish.grizzly.utils.DelayedExecutor$DelayedRunnable.run(DelayedExecutor.java:158)
	 at: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	 at: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	 at: java.lang.Thread.run(Thread.java:745)
Thread Synchronization Statistics:
-----------------------
Number of times this thread was blocked (to enter/reenter a Monitor): 1
Number of times this thread waited for a notification (i.e. it was in WAITING or TIMED_WAITING state): 0
Total CPU time for this thread: 98,305 seconds 906,250,000 nanoseconds.
User-level CPU time for this thread: 98,305 seconds 906,250,000 nanoseconds.
Object Monitors currently held or requested by this thread: []
Ownable Synchronizers (e.g. ReentrantLock and ReentrantReadWriteLock) held by this thread: []

Thread Execution Information:
-----------------------
Thread "http-thread-pool(4)" thread-id: 45 thread-state: WAITING Waiting on lock: java.lang.Object@5658d336
	 at: java.lang.Object.wait(Native Method)
	 at: java.lang.Object.wait(Object.java:502)
	 at: org.glassfish.grizzly.threadpool.SyncThreadPool$SyncThreadWorker.getTask(SyncThreadPool.java:200)
	 at: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:583)
	 at: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	 at: java.lang.Thread.run(Thread.java:745)
Thread Synchronization Statistics:
-----------------------
Number of times this thread was blocked (to enter/reenter a Monitor): 773,092,781
Number of times this thread waited for a notification (i.e. it was in WAITING or TIMED_WAITING state): 5,869,008,579
Total CPU time for this thread: 97,172 seconds 953,125,000 nanoseconds.
User-level CPU time for this thread: 97,172 seconds 953,125,000 nanoseconds.
Object Monitors currently held or requested by this thread: []
Ownable Synchronizers (e.g. ReentrantLock and ReentrantReadWriteLock) held by this thread: []
~~~

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: 8 u102 - Oracle
- **Operating System**: Windows

**Comment by smillidge** [comment] 2017-04-25 15:14
Both threads are idle in those thread dumps.

**Comment by mikecroft** [comment] 2017-04-26 09:25
If this is happening on start up, have you checked your heap size and GC behaviour? If your heap size is too small then the JVM will have to do a lot of work to free up more memory which will cause very high CPU usage.

**Comment by matsuk55** [comment] 2017-04-26 11:47
Restarting domain reduced CPU load.
I checked the heap memory usage, but GC does not occur much.
I think that the thread is spinning for some reason at startup.

**Comment by matsuk55** [comment] 2017-04-26 11:51
[threaddump.txt](https://github.com/payara/Payara/files/958242/threaddump.txt)

Attach file is is full thread dump.

**Comment by mikecroft** [comment] 2017-04-26 12:52
There are 5 thread dumps in that file.

The problem is that you haven't captured any activity in your thread dumps. The threads you've highlighted are both idle **at the time that you took the thread dump**. This tells us nothing about what was taking up the CPU time before that point. You would need to take a thread dump ***while the CPU is high*** so we can see what the threads are doing and what is taking the time.

**Comment by matsuk55** [comment] 2017-04-26 13:02
The attached thread dump was acquired when the CPU usage rate was high.
If processing was not done in the thread, what raised the CPU usage of the Java process?

**Comment by mikecroft** [comment] 2017-05-10 18:28
Hi @matsuk55 here is an overview of why reported CPU utilization alone may be misleading here:
http://www.brendangregg.com/blog/2017-05-09/cpu-utilization-is-wrong.html

Unless there are other symptoms beside observed CPU usage being high, then there may not be a problem here. The cause of the CPU spike could be anything like excessive disk I/O on a highly fragmented mechanical disk.

The threads you highlighted above may have been busy while the server was starting, but at the time that each thread dump was taken they were idle. There's no information here to be able to tell what was happening.

Without any more data, there's nothing else we can do on this.

**Comment by matsuk55** [comment] 2017-05-11 10:18
Thank you. @mikecroft 
Then, when the same problem happens next time, what kind of information should I collect for the investigation?

**Comment by matsuk55** [comment] 2017-06-26 05:11
The same problem occured.

I check the thread dump. follow thread looks like infinify loop.

Please tel me what is "http-listener-2-expirer(1)" thread.

`
"http-listener-2-expirer(1)" #58 daemon prio=5 os_prio=0 tid=0x0000000020a1d000 nid=0x12b8 runnable [0x00000000250ee000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Thread.interrupt0(Native Method)
	at java.lang.Thread.interrupt(Thread.java:923)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$4.doWork(AbstractThreadPool.java:163)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$4.doWork(AbstractThreadPool.java:159)
	at org.glassfish.grizzly.utils.DelayedExecutor$DelayedRunnable.run(DelayedExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x0000000680fdda28> (a java.util.concurrent.ThreadPoolExecutor$Worker)

`

**Comment by matsuk55** [comment] 2017-06-26 05:25
"http-listener-2-expirer(1)" therad does not found in thread dump of  other payara pocess.

**Comment by matsuk55** [comment] 2017-06-26 06:09
In the thread dump, I found three thread that use cpu long time.
And, I get a stack infomation by windows process explorer. (attached exel file).

[LongTimeExecutionThreads.txt](https://github.com/payara/Payara/files/1101138/LongTimeExecutionThreads.txt)
[ProcessExplorerHardCopy.xlsx](https://github.com/payara/Payara/files/1101139/ProcessExplorerHardCopy.xlsx)

**Comment by mikecroft** [comment] 2017-06-26 09:22
Hi @matsuk55, again, the thread you have pointed out is a **pooled** thread, meaning that it is just available as a worker to be used to perform some work in the server. At the time you took the thread dump there, each of those threads were sitting idle and waiting to be given work. This is entirely normal behaviour and to be expected.

There is zero evidence of any bug here, certainly not a JDK bug. If the CPU usage is high, then there are a very large number of perfectly valid reasons why it might be high.

The problem is that there is not sufficient information here to draw *any* conclusion. There is nothing to suggest there is a problem or any data to suggest where to start looking. I'm going to close this now since there is nothing we can do here.

**Closed by mikecroft** 2017-06-26 09:22 UTC
Labels: 1:Investigating, c:Question
