### ISSUE TITLE
Connection closes abruptly over HTTP/2 protocol

### ISSUE THREAD

**Issue by shivinm** [payara/Payara#4271] opened 2019-10-10 23:21 UTC
# Description #
----------

I am seeing an issue when calling one of our APIs over HTTP/2 protocol using a secure TLS. The problem only reproduces when the request takes close to a minute to complete. For shorter requests, I do not notice the symptoms:
 
- net::ERR_CONNECTION_RESET when API is called through the browser (Chrome/Firefox/Safari, etc)
- Unexpected EOF when API is called through cURL 

Any idea if this is a known bug? Any knobs I can turn to fix? Any logging I can turn on to debug further? 

For now, I have disabled HTTP/2 in Payara as a workaround. 
```
asadmin set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.http2-enabled=false
```

--

Below is an example showing behaviour on HTTP/2 vs. HTTP/1.1 using `cURL`. Note that the domain/ip addresses have been obfuscated for privacy.

**BAD (HTTP/2)**
```
curl -v -X POST https://some-domain.com/v1/requests -H "Content-Type: application/json" -d "@file.json"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 11.222.33.444...
* TCP_NODELAY set
* Connected to some-domain.com.com (11.222.33.444) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.some-domain.com
*  start date: Feb 27 00:00:00 2019 GMT
*  expire date: Feb 25 23:59:59 2020 GMT
*  subjectAltName: host "some-domain.com" matched cert's "*.some-domain.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7faead802200)
> POST /v1/requests HTTP/2
> Host: some-domain.com
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 417
> 
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* Unexpected EOF
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (56) Unexpected EOF
```

**GOOD (HTTP 1.1)**
```
curl -v -X POST https://some-domain.com/v1/requests -H "Content-Type: application/json" -d "@file.json" --http1.1
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 11.222.33.444...
* TCP_NODELAY set
* Connected to some-domain.com (11.222.33.444) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.some-domain.com
*  start date: Feb 27 00:00:00 2019 GMT
*  expire date: Feb 25 23:59:59 2020 GMT
*  subjectAltName: host "some-domain" matched cert's "*.some-domain"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> POST /v1/requests HTTP/1.1
> Host: some-domain.com
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 417
> 
* upload completely sent off: 417 out of 417 bytes
< HTTP/1.1 200 OK
< Server: Payara Server  5.184 #badassfish
< X-Powered-By: Servlet/4.0 JSP/2.3 (Payara Server  5.184 #badassfish Java/Oracle Corporation/1.8)
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: POST, GET, PUT, DELETE, HEAD, OPTIONS
< Access-Control-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Cookie
< Set-Cookie: JSESSIONID=7acfe9844f24ccae044e1ae24b40; Path=/v1/requests; Secure; HttpOnly
< Content-Type: application/json;charset=ISO-8859-1
< Transfer-Encoding: chunked
< X-Frame-Options: SAMEORIGIN
< 
* Connection #0 to host some-domain.com left intact
{"request_id":"20e839c7-5987-4948-b136-52c469840451"}
```

## Expected Outcome

See provided example. 

## Current Outcome

See provided example. 

## Steps to reproduce (Only for bug reports) 

See provided example. 

### Samples

See provided example. 

## Context (Optional)

See provided example. 

## Environment ##

- **Payara Version**:  5.184 (build 89)
- **Edition**:   Full
- **JDK Version**: 1.8
- **Operating System**: Amazon Linux
- **Database**: MariaDB

**Comment by shivinm** [comment] 2019-10-13 01:27
Been googling similar occurences online, this one looks similar - https://github.com/cloudflare/tableflip/issues/12

**Comment by shivinm** [comment] 2019-10-31 21:52
Any thoughts / pointers to diagnose further?

**Comment by smillidge** [comment] 2019-11-03 19:59
tbh this sounds a complicated thing to reproduce and is a bit out of the scope of GitHub issues. We need a easily reproducible test case to demonstrate the issue.

**Comment by eduarddrenth** [comment] 2019-12-09 09:27
perhaps related to #2625 ?

**Comment by OndroMih** [comment] 2020-02-07 13:38
Hi @shivinm, can you please provide a simple to follow scenario how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. Otherwise we’ll have to close this issue.

**Comment by lprimak** [comment] 2020-02-07 23:14
Sure looks like its a duplicate of #2625

**Comment by eduarddrenth** [comment] 2020-02-20 16:03
if I am not mistaken there is a reproducer, look back in the issue. for
sure this is still a problem

Op vr 7 feb. 2020 14:38 schreef Ondro Mihályi <notifications@github.com>:

**Comment by OndroMih** [comment] 2020-03-03 11:53
Hi @eduarddrenth , can you have a look at #2625 where it seems like it's the same issue as yours?

If it looks like it's the same issue, let's close this issue. We were able to reproduce #2625 and it's high on our list of issues to fix. However, we also have some customer issues we need to fix first.

If it's not the same problem, then please provide a simple to use reproducer. I looked back in this issue, and I only found information about what the problematic behavior and expected behavior. It only describes what happens in your environment but not how to reliably reproduce it in any environment with some example application. Without a reproducer that we can easily use to reproduce the problem in our environment we can't do anything to fix the issue and we'd need to close this anyway.

**Comment by eduarddrenth** [comment] 2020-03-04 20:06
Not sure which issue you want to close #2625 is mine.

reproducer mentioned here: https://github.com/payara/Payara/issues/2625#issuecomment-410357971 and here: https://github.com/payara/Payara/issues/2625#issuecomment-472379796

It looks like #2625 is the same as this issue, but cannot tell for sure. #2625 can be closed as far as I am concerned, for I have no direct need for http2.

**Comment by lprimak** [comment] 2020-03-05 01:56
Please close this issue as it's a dupliate

**Comment by OndroMih** [comment] 2020-03-24 16:20
Closing as a duplicate of #2625

**Closed by OndroMih** 2020-03-24 16:20 UTC
Labels: status:reproducer-needed

**Comment by shivinm** [comment] 2020-04-07 04:54
Hi all, just found about the recent updates. Thanks for marking this as a duplicate. I'll follow it's progress in the other ticket.

**Comment by eduarddrenth** [comment] 2022-02-15 17:34
For me everything is working fine since the fix in 5.2020.2, working with 5.2021.10 now

**Comment by lprimak** [comment] 2022-02-15 17:38
@mkarg this issue is a duplicate

**Comment by OndroMih** [comment] 2022-05-03 07:19
Hi @mkarg , please create a new issue for your case. This is closed as a duplicate and several people confirmed it works for them. Please create a new issue with exact details when you observe the problem, and please test with the latest Payara Server CE.

**Comment by StevenHachel** [comment] 2024-04-24 08:33
This problem is definitely not fixed. We've been switching to HTTPS for a few days now and have had constant connection failures since then (connection is closed). This does not occur under http (with HTTP/2), but only under https (with HTTP/2).
Now the question is what it could mean for our enterprise application if we switch off HTTP/2 under https. Then the problem no longer occurs, but are there any disadvantages?
