### ISSUE TITLE
Admin Console Fails to Load /CUSTCOM-139

### ISSUE THREAD

**Issue by mzaum** [payara/Payara#4397] opened 2019-12-18 21:22 UTC
# Description #
----------
Accessing the admin console intermittently fails.  The "loading console" screen appears, and then it redirects to a blank white page.  Subsequent accesses only show the blank white page, and a server restart is needed to restore access to the console.  Typically, if the first access after startup succeeds (no blank screen), then subsequent accesses succeed.  If the first access fails, subsequent accesses fail.

The following error shows up in the logs:

 `[2019-12-18T15:14:43.372-0500] [Payara 5.193] [SEVERE] [AS-WEB-CORE-00037] [javax.enterprise.web.core] [tid: _ThreadID=69 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1576700083372] [levelValue: 1000] [[
  An exception or error occurred in the container during the request processing
java.lang.NullPointerException
        at com.sun.jaspic.services.JaspicServices.hasExactMatchAuthProvider(JaspicServices.java:215)
        at com.sun.enterprise.security.jaspic.config.PayaraJaspicServletServices.<init>(PayaraJaspicServletServices.java:104)
        at com.sun.web.security.realmadapter.JaspicRealm.getConfigHelper(JaspicRealm.java:299)
        at com.sun.web.security.realmadapter.JaspicRealm.initJaspicServices(JaspicRealm.java:153)
        at com.sun.web.security.realmadapter.JaspicRealm.isJaspicEnabled(JaspicRealm.java:163)
        at com.sun.web.security.RealmAdapter.isSecurityExtensionEnabled(RealmAdapter.java:261)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:96)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:368)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
]]
`

## Expected Outcome

Admin console login screen appears.

## Current Outcome

Blank screen appears.

## Steps to reproduce (Only for bug reports) 

Start Payara.  Attempt to access admin console.  Only intermittently fails.

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Web
- **JDK Version**: OpenJDK Runtime Environment Corretto-8.232.09.1 (build 1.8.0_232-b09)
- **Operating System**: Linux
- **Database**: MySQL

**Comment by toanlc0912** [comment] 2019-12-24 07:25
I'm also having this issue on multiple payara servers after upgrading to 5.194 w/ JDK 11

-     **Payara Version**: 5.194
-     **Edition**: Web
-     **JDK Version**: JDK 11 (jdk-11.0.5)
-     **Operating System**: Linux
-     **Database**: Oracle 12c

**Comment by toanlc0912** [comment] 2019-12-24 09:25
After comparing the configuration of domain.xml, I see that the problem comes from the missing of security configuration for httpServlet layer.
```xml
<message-security-config auth-layer="HttpServlet">
          <provider-config provider-type="server" provider-id="GFConsoleAuthModule" class-name="org.glassfish.admingui.common.security.AdminConsoleAuthModule">
            <property name="loginPage" value="/login.jsf"></property>
            <property name="loginErrorPage" value="/loginError.jsf"></property>
            <response-policy></response-policy>
            <request-policy auth-source="sender"></request-policy>
          </provider-config>
        </message-security-config>
```

**Comment by rdebusscher** [comment] 2020-01-02 18:41
Hi,

This seems to be a race condition when server starts up. We have internal issue `CUSTCOM-139` to research this.

regards
Rudy.

**Comment by toanlc0912** [comment] 2020-01-03 04:39
Hi @rdebusscher
I found two cases as below:
- One server with this issue was solved by a domain restart.
- The other one behind a Load Balancer and all the domains admin console pages return blank. The load balancer is A10. I've tried multiple restart and comparing domain.xml between two servers, nothing stands out that could affect the console page.

Hope the information will help.

**Comment by rdebusscher** [comment] 2020-01-03 09:22
Hi @toanlc0912 

For the issue with the Load Balancer
- Can you check the Admin Console pages without the use of the Load Balancer?
- Can you verify if HTTP/2 and HTTP Push functionality are disabled (as LoadBalancer might not handle it properly or is not configured properly) See also https://blog.payara.fish/http2-in-payara-5.

Other than that, the LoadBalancer issue might difficult to research.

Regards
Rudy

**Comment by toanlc0912** [comment] 2020-01-06 06:24
Hi @rdebusscher
Sorry for the long response time, I tried out both options and it didn't work. 

Cheers,
Toan

**Comment by toanlc0912** [comment] 2020-01-22 23:54
Hi @rdebusscher 

After a quite trying to overcome this issue, I found out that we can reproduce this problem by starting the domain and try to access the admin console as soon as possible when the GFAuthConfig is not yet loaded and because the java.security file has no definition to the other AuthConfig Factory provider, so it cannot instantiate the factory.

I found a way to fix this issue on my payara domains by simply adding a java.security file into my domain config folder and add the jvm-option pointing to this java.security.

`<jvm-options>-Djava.security.properties=${com.sun.aas.instanceRoot}/config/java.security</jvm-options>`

The java.security file will define the default AuthConfigFactory, which is loaded by Payara when starting

`authconfigprovider.factory=com.sun.enterprise.security.jaspic.config.GFAuthConfigFactory`

By doing this, Payara can instantiate this factory when a non-null system wide factory can be found

Hope it helps.

Cheers,

Toan

**Comment by fabide** [comment] 2020-02-12 15:08
I also ran into this issue with Debian 10 - OpenJDK 11 JRE - Payara 5.194.
I can confirm that @toanlc0912 workaround works

**Comment by ettaramesh** [comment] 2020-10-06 10:30
Hi @toanlc0912 

We have faced this issue in our Production environments and as it was mentioned it occurs randomly. We are facing this issue with ZULU Open JDK 11.0.6+10, Payara 5.194, Operating System - Linux
But we were not able to reproduce this issue on our dev environments.  If we need to apply the workaround you have suggested, we should also need to understand if there are any other side effects. Please let us know if you think of any such issues.

Also if you could explain in detail how we can reproduce this issue that would be of great help.

Thanks

**Comment by ettaramesh** [comment] 2020-10-06 10:35
@rdebusscher 
Could you please let us know if the fix to this issue (CUSTCOM-139) is available in any of the new releases.
Thanks

**Comment by toanlc0912** [comment] 2020-10-06 10:52
Hi @ettaramesh 
Please check my comment here https://github.com/payara/Payara/issues/4397#issuecomment-577441374
That's my way to reproduce the issue on our environment. Not sure if it will work for you.
You can try out the fix I provided to see if it helps.

**Comment by ettaramesh** [comment] 2020-10-06 11:08
Hi @toanlc0912 
Thanks for your quick reply. I was not able to reproduce the issue. Also to apply the fix directly in our production env, we should know if there are any other issues raising due to this.  Please let me know if you think of any.

**Comment by toanlc0912** [comment] 2020-10-07 00:32
Hi @ettaramesh 
We applied this fix on our production server and encountered no side effects so far.

**Comment by AlanRoth** [comment] 2020-11-11 11:51
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:51 UTC
Labels: status:accepted
