### ISSUE TITLE
eclipselink bundled with payara cannot correctly read postgres timestamp values.

### ISSUE THREAD

**Issue by jimmymain** [payara/Payara#3040] opened 2018-08-14 14:00 UTC
# Description #
----------

[2018-08-14T15:40:00.357+0200] [Payara 5.182] [SEVERE] [] [fish.payara.microprofile.opentracing.jaxrs.JaxrsContainerRequestTracingFilter] [tid: _ThreadID=41 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1534254000357] [levelValue: 1000] [[
  javax.persistence.PersistenceException: Exception [EclipseLink-3005] (Eclipse Persistence Services - 2.7.1.qualifier): org.eclipse.persistence.exceptions.ConversionException
Exception Description: Incorrect timestamp format: [2018-04-16 10:56:15.353+02] (expected [YYYY-MM-DD HH:MM:SS.NNNNNNNNN])]]

The problem here is that the value also contains the time zone **+02**

This seems to be a known issue, so we need a maintenance release of payara to address the issue or a workaround on how to replace the version of eclipselink with a newer version.

https://github.com/eclipse-ee4j/eclipselink/pull/117

## Expected Outcome

The date value should be read correctly.

## Current Outcome

An exception is thrown.

## Steps to reproduce (Only for bug reports) 

Read a postgres date value with a timestamp including time zone.

## Environment ##

- **Payara Version**: 5.182
- **Edition**: FULL
- **JDK Version**: 8 ORACLE
- **Operating System**:  Windows
- **Database**: PostGres

**Comment by smillidge** [comment] 2018-08-14 16:26
Thanks this is a duplicate of #2746

**Closed by smillidge** 2018-08-14 16:26 UTC
Labels: c:Duplicate, upstream bug

**Comment by smillidge** [comment] 2018-08-14 16:43
If you need a fast maintenance release outside of the usual quarterly release cycle please go to https://www.payara.fish/choose_support

**Comment by jimmymain** [comment] 2018-08-15 10:55
Hi Steve, thanks very much for the support options, I am with BMW. I am not sure how to access support services through that channel though.
When is the next quarterly release due to be out?
End September?
