### ISSUE TITLE
SSL mutual auth not cooperating with HTTP2

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4052] opened 2019-06-16 13:21 UTC
# Description #
----------

When we have some URLs secured by CLIENT-CERT method and some specific config accepting everybody with valid cert (against cacerts.jks) if there is a request using HTTP/2 method whole server is blocked and starts to returning HTTP400 (bad request) code.

## Expected Outcome

I suppose that there is no support for CLIENT-CERT in http/2 but surely there should be some fallback or just single request might be broken but not to broke whole server!

## Current Outcome

Server starts to return HTTP400 for all requests.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

`[glassfish@papms10 ~]$ /opt/glassfish/payara5/glassfish/bin/asadmin --user admin --passwordfile /opt/glassfish/pms/asadmin_password.txt restart-domain production`

2 -**  Configure an certificate realm to add group to every request which passes it (group name is allusers in this example):

[Attach screenshots of Payara's Server console, to illustrate]
![obraz](https://user-images.githubusercontent.com/41665450/59564568-9dbd8880-9048-11e9-9590-239541ec2a9a.png)

3 -**  Restart domain to be 100% sure that settings are applied:

`[glassfish@papms10 ~]$ /opt/glassfish/payara5/glassfish/bin/asadmin --user admin --passwordfile /opt/glassfish/pms/asadmin_password.txt restart-domain production`

And check that allusers setting is still there

4 -**  Clone my example project and deploy it on payara domain:
https://github.com/peterpz1/PayaraSslMutualAuthExample

5 -** Try hitting the url from CLI, confirming that everything is working properly:

`[glassfish@papms10 ~]$ curl --insecure --cert /opt/glassfish/pms/crt/papms10.corpnet.pl/papms10.corpnet.pl.crt --key /opt/glassfish/pms/crt/papms10.corpnet.pl/priv.key https://10.79.162.39:8181/PayaraSslMutualAuthExample/webservice/soap/TestService?wsdl
<?xml version='1.0' encoding='UTF-8'?></style> </head><body><h1>HTTP Status 400 - Bad Request</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Bad Request</p><p><b>description</b>The request sent by the client was syntactically incorrect.</p><hr/><h3>Payara Server  5.191 #badassfish</h3></body></html>`

And now every hit to this service is resulting with HTTP400! The only solution now is to restart domain, which will work properly until hit from browser again!

It seems that probably Grizzly is getting broken when hit using HTTP/2. I'm almost sure about that, because when we will disable HTTP/2 protocol in network listener properties the problem is resolved. But the problems with HTTP/2 are always visible we have them from Glassfish5 and Payara has the same thing. Why the HTTP/2 was introduced if it is not working properly and we have always to disable it? Just disable it in the default config, because it is not the first problem with support of HTTP/2 from Payara/Glassfish servers (we can provide more examples from our deployments).

Don't ask me if I was testing it using 5.192 - we are not using this version, because there are too many changes (we cannot even use logback, because the logback-payara project was not updated).

And another thing - this issue is ocurring only when we don't use principal-name in glassfish-web.xml. Normally when we are using principal names that config is woking properly against HTTP/2; abut this config is important to us to have more possibilities to accept different principals (we can use filter, and not have static list on glassfish-web.xml).

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: zulu jdk 8 u 212
- **Operating System**: CentOS Linux release 7.5.1804 (Core)
- **Database**: not relevant

**Comment by peterpz1** [comment] 2019-06-16 13:22
Code insert seems to not be working properly...

**Comment by peterpz1** [comment] 2019-06-16 22:46
And last thing. When server starts to being stuck in HTTP 400 mode there are no logs in server.log pointing out to what is happening. I can increase the log levels if needed but I need package info what of them to increase.

**Comment by peterpz1** [comment] 2019-07-16 10:29
Any possibilities for feedback on that? I've lost almost 1 working day to get the cause :(

**Comment by Cousjava** [comment] 2019-07-16 11:17
HTTP/2 does not work with client certs. This is not a Payara-specific issue, but due to the specification of HTTP/2. When the IETF decides how client certs should work with HTTP/2, then we will implement it.

**Comment by peterpz1** [comment] 2019-07-16 12:12
@Cousjava I don't argue with that. But this shouldn't break whole Payara server, should it?

**Comment by fturizo** [comment] 2020-02-06 19:04
As previously stated, this is not an issue with Payara Server, but with the way the HTTP/2 spec is not compatible with client certificate authentication. Considering this, we'll proceed to close this issue. Feel free to explore the causes of this and a ny possible workaround by raising a topic in the [official Payara Forum](https://groups.google.com/forum/#!forum/payara-forum).

**Closed by fturizo** 2020-02-06 19:04 UTC
