### ISSUE TITLE
Bug Report:  Unable to start Payara5.192+ in ppc64le

### ISSUE THREAD

**Issue by rodrigobernart** [payara/Payara#5357] opened 2021-07-22 20:40 UTC
# Description #

Hello everybody!
According to documentation the Payara 5 is compatible with any architeture 
with a JDK installed [https://docs.payara.fish/community/docs/5.192/general-info/supported-platforms.html](url) and has a note saying it's not more required a Payara Blue to run with IBM SDK.

I'm trying to execute the Payara 5.192 or any other version above, but in my servers with architeture PowerPC64 or Power8 it's not possible, because an error looks likes this:

`Exception in thread "main" com.sun.jna.LastErrorException: [25] Inappropriate ioctl for device at com.sun.jna.Native.invokeVoid(Native Method)
at com.sun.jna.Function.invoke(Function.java:414)
at com.sun.jna.Function.invoke(Function.java:360)
at com.sun.jna.Library$Handler.invoke(Library.java:244)
at com.sun.proxy.$Proxy18.ioctl(Unknown Source)
at org.jline.terminal.impl.jna.linux.LinuxNativePty.getSize(LinuxNativePty.java:95)
at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:60)
at org.jline.terminal.Terminal.getBufferSize(Terminal.java:216)
at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:741)
at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:298)
at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:115)
at com.sun.enterprise.admin.cli.CLICommand.buildLineReader(CLICommand.java:1445)
at com.sun.enterprise.admin.cli.CLICommand.prevalidate(CLICommand.java:941)
at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:325)
at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:360)
at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:294)
at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)
`

![Captura de tela de 2021-07-22 17-39-29](https://user-images.githubusercontent.com/23552456/126706575-5aa29fe1-5a23-4ec2-b866-d2b27e2e596f.png)

## Steps to reproduce ## 

I'm just trying to start asadmin`(bin/asadmin start-domain domain1)`.

With a Payara 5.191 or versions previous i don't have problem to execute in my servers with this architeture.

## Environment ##

- **Distribution**: Server Full Profile 5.192 or above
- **JDK Version**: openjdk "1.8.0_292" or openjdk "11.0.11" or IBM SDK 1.8.0_sr6fp31
- **Operating System**: Ubuntu / Debian / CentOS

**Comment by AlanRoth** [comment] 2021-07-28 13:22
Hi, @rodrigobernart, 

We have not tested on ppc64le before as we have no customers (nor the hardware currently) that use this architecture. We have confirmed support for x64 and arm64 architectures.

This issue is far too complex for a Github ticket and if you wish for us to investigate in-depth this would require a Enterprise license.

Let me know how you would like to proceed.

Thank you for raising such a interesting ticket!
Alan

**Comment by rodrigobernart** [comment] 2021-07-28 13:57
Hi, @AlanRoth 

We tried to assign an Enterprise license, but the cost is very high to us and we aren't sure about the compatibility with Enterprise license either. We are in contact with the sales team of Payara, but we aren't so sure either about the sucess of this license. So my expectate was in resolve with community this problem.

**Comment by AlanRoth** [comment] 2021-07-28 16:22
Hi @rodrigobernart,

We have dropped official support for IBM JDK in later Payara server versions, I believe 5.2020.3 was the latest to include it. We only offer official support for x64 and arm64 architecture, before this we only offered official support for x64. 

My hands are sadly tied as we cannot reproduce your issue.

With a Enterprise license you can request support for ppc64le in which we will test and make sure Payara works with ppc64le.

Can you try disabling JLine and trying again?

The only other option is to raise a post on the Payara forum, which I see you have already done.

Thank you,
Alan

**Comment by rodrigobernart** [comment] 2021-07-28 19:49
Hi @AlanRoth 

I tryied to do your recommendations and I've followed this step: [https://docs.payara.fish/community/docs/5.2020.3/documentation/payara-server/asadmin-commands/disabling-jline.html](url) and the same error apears.

Remembering, i'm using OpenJDK 1.8.0_292 and Ubuntu 20.04 ppc64le and Payara 5.2020.3 because maybe works.

At the forum I don't have a answer :(

**Comment by AlanRoth** [comment] 2021-07-30 08:47
Hi @rodrigobernart,

Sadly, this seems to be a incompatibility between Payara and ppc64le. We don't claim to be able to run on _any_ architecture.

You can try raising a enhancement request for ppc64le support and if your request gets enough community votes we will look into it.

As it stands now, we have no plans to introduce support for ppc64le due to low demand.

I will close this issue now but feel free to leave any more comments with information that may be useful!

Thank you for your understanding,
Alan

**Closed by AlanRoth** 2021-07-30 08:47 UTC
Labels: Status: Pending, Type: Bug
