### ISSUE TITLE
Domain.xml JVM options supporting new-style JDK9+ parameters /FISH-131

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [payara/Payara#4187] opened 2019-08-29 18:34 UTC
# Description #
----------

Hello there and congratulations on the new version release!

There is a behaviour that has been going since the **5.192** version (also present in the **5.193**, I have just checked the code), which regards the interpretation of the new-style JVM options. The JVM supports a kind of options they describe as "long options" [like this](https://docs.oracle.com/javase/9/tools/java.htm#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE__BABDJJFI). 

One example is 
`--add-opens java.base/jdk.internal.loader=ALL-UNNAMED`, 
which is specific for JDK9+.

Now, since 5.192, domain.xml has a set of these options like the one above, as they are required to work with JDK11 (in compatibility mode I think, because of the module system).

`<jvm-options>[9|]--add-opens=java.base/jdk.internal.loader=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.base/java.lang=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.base/java.nio=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.base/sun.nio.ch=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.management/sun.management=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.base/sun.net.www.protocol.jrt=ALL-UNNAMED</jvm-options>`

Notice here that there is a "=" between each of them. Now, if you take the "=" off in the domain.xml the server will not start (under JDK11, naturally) because it doesn't recognize the options, for example:
`Unrecognized option: --add-opens java.base/java.nio=ALL-UNNAMED`

Now, this happens because the **MiniXml.java** reads the options inside each <jvmoptions> in domain.xml, creates a String[] and sends them to the **ProcessImpl.java** (this is a standard lib Java class). This class will first prepare the parameters before actually sending them to the java program. In **ProcessImpl.java**, Windows version (other OS have slightly different implementations), this bit of code will decide whether to quote the parameters or not (lines 244-265):

    private static boolean needsEscaping(int verificationType, String arg) {
        // Switch off MS heuristic for internal ["].
        // Please, use the explicit [cmd.exe] call
        // if you need the internal ["].
        //    Example: "cmd.exe", "/C", "Extended_MS_Syntax"

        // For [.exe] or [.com] file the unpaired/internal ["]
        // in the argument is not a problem.
        boolean argIsQuoted = isQuoted(
            (verificationType == VERIFICATION_CMD_BAT),
            arg, "Argument has embedded quote, use the explicit CMD.EXE call.");

        if (!argIsQuoted) {
            char testEscape[] = ESCAPE_VERIFICATION[verificationType];
            for (int i = 0; i < testEscape.length; ++i) {
                if (arg.indexOf(testEscape[i]) >= 0) {
                    return true;
                }
            }
        }
        return false;
    }

Since a long option without the "=" has a space between them, that function will always identify that option as "needsQuoting", and so the option will be quoted and sent to the java program. It is important to note that after this step, all the options will be concatenated into a single String and only then sent to the java program. With the option quoted it will result in a blow up of the startup of the java process because it cannot recognize the quoted option as a valid one.

As this is a Java standard lib class there is nothing that can be done, should the option reach the **ProcessImpl** normally without the "=". It will always quote an option with a space in the middle.

I suggest an approach like the **Payara Tools Eclipse Plugin** has done. In Payara Tools, the JVM options are parsed and split into an array, but for some reason they split at the "space" (they do all sorts of parameter replacement first, this is just the condensed story), which also creates a String[] but separates the "--add-opens" part from the "java.base/jdk.internal.loader=ALL-UNNAMED" (each in their own array position). This has a curious (I am guessing intentional) effect of, when it finally reaches the ProcessImpl class, it will "not need quotes", but in the end, the options array is concatenated so the java program will receive the correct String (because it joins the "--add-opens" part with the rest, no quotes, you see what I mean).

Now, I know this solution is "a trick". I also know that since the JVM accepts both with the equals and without it you could probably just ignore this suggestion and leave it at that. But I think this kind of problem will rise sometime in the future because someone will remove the equal sign from the options and it will blow. Further, options without the equals are valid JVM Options anyway.

Of course Payara will eventually stop needing these parameters to work with JDK9+, but still...

How about it?

PS: or maybe just add the "=" after you've read the JVM options from domain.xml to please the ProcessImpl...

## Expected Outcome

Starting normally with the options without the "=" sign

## Current Outcome

Won't start, because it doesn't consider the options as valid ones.

## Steps to reproduce (Only for bug reports) 

1 -**  Remove the "=" between long options (like JDK modular sepcific) in domain.xml
2 -**  Start-domain

## Context

I actually just found this behaviour because when I installed Payara Tools it also had a bug with these kind of options, but a slightly different one. I posted an issue there [number 15](https://github.com/payara/ecosystem-eclipse-plugin/issues/15), so there is some more information there.

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Full
- **JDK Version**: AdoptOpenJDK 11.0.3
- **Operating System**: Windows 10
- **IDE**: Eclipse 2019-06

**Comment by smillidge** [comment] 2019-11-03 20:09
@CarlosMOGoncalves is this fixed by https://github.com/payara/ecosystem-eclipse-plugin/pull/16

**Comment by CarlosMOGoncalves** [comment] 2019-11-04 12:45
Hello there.

Indeed, in the Plugin it is not an issue because it parses the JVM options in a different way from the Payara Server. An yes, that particular PR even solved the problem of an overwrite of multiple options.

I suggested to use a similar approach in the Server to the parsing of the JVM Options because whenever the parsed options reaches that **ProcessImpl.java** class it will be too late.

**Comment by fturizo** [comment] 2020-02-27 22:12
Greetings @CarlosMOGoncalves. Many thanks for brining this issue to our attention. We have raised the internal issue `CUSTCOM-210` to escalate this request to our engineering team for a possible implementation of this enhancement. We'll let you know once we got more details about a future release candidate.

**Comment by AlanRoth** [comment] 2020-11-11 11:46
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:46 UTC
Labels: status:accepted
