### ISSUE TITLE
MPCONFIG properties can not be used inside @DataSourceDefinition /CUSTCOM-196

### ISSUE THREAD

**Issue by haraldatbmw** [payara/Payara#4487] opened 2020-02-13 10:47 UTC
# Description #
----------

Payara Micro is not able to use MicroProfile Config properties inside ``@DataSourceDefinition`` annotation.

```java
// hardcoded version works
@DataSourceDefinition(
    name            = "java:global/jdbc/reproducer",
    className       = "org.postgresql.ds.PGSimpleDataSource", 
    serverName      = "localhost",
    portNumber      = 5432,
    databaseName    = "postgres",
    user            = "postgres",
    password        = "mysecretpassword"
)

// fully microprofile config does not work
@DataSourceDefinition(
    name            = "java:global/jdbc/reproducer",
    className       = "${MPCONFIG=dataSource.className}", 
    serverName      = "${MPCONFIG=dataSource.serverName}",
    portNumber      = 5432,
    databaseName    = "${MPCONFIG=dataSource.databaseName}",
    user            = "${MPCONFIG=dataSource.user}",
    password        = "${MPCONFIG=dataSource.password}"
)

// partial microprofile config does not work
@DataSourceDefinition(
    name            = "java:global/jdbc/reproducer",
    className       = "org.postgresql.ds.PGSimpleDataSource", 
    serverName      = "${MPCONFIG=dataSource.serverName}",
    portNumber      = 5432,
    databaseName    = "${MPCONFIG=dataSource.databaseName}",
    user            = "${MPCONFIG=dataSource.user}",
    password        = "${MPCONFIG=dataSource.password}"
)
```

## Expected Outcome

Ability to configure my DataSource using MicroProfile config.

## Current Outcome

Exception is thrown, due to the MPCONFIG properties does not get replaced.

```bash
[2020-02-13T11:35:45.809+0100] [] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1581590145809] [levelValue: 1000] [[
Exception while preparing the app : Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Class name is wrong or classpath is not set for : ${MPCONFIG=dataSource.className}
Error Code: 0
```

or

```bash
Caused by: java.net.UnknownHostException: ${MPCONFIG=dataSource.serverName}
```

## Steps to reproduce (Only for bug reports) 

See reproducer at https://github.com/haraldatbmw/payara-micro-mpconfig

## Context (Optional)

I want to use payara micro and have the ability to fully configure my application using MicroProfile Config. I want to use H2 in-memory db at dev time and Postgres as Integration and Production environment.

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Micro
- **JDK Version**: 8 OpenJDK 
- **Operating System**: Windows
- **Database**: PostGres

**Comment by fturizo** [comment] 2020-02-13 16:19
Greetings @haraldatbmw. Many thanks for reporting this issue. With your reproducer, I was able to verify that variable substitution for the `@DatasourceDefinition` annotation is not working properly with MicroProfile Configuration variables, and I've escalated this bug with the internal issue `CUSTCOM-196` so that it is fixed in a future release of Payara Micro.

In the meantime, as a workaround you can use the `web.xml` element equivalent of the annotation to make your application work as intended, like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
            version="4.0">
        <data-source>
            <name>java:global/jdbc/reproducer</name>
            <class-name>${MPCONFIG=dataSource.className}</class-name>
            <server-name>${MPCONFIG=dataSource.serverName}</server-name>
            <port-number>5432</port-number>
            <database-name>${MPCONFIG=dataSource.databaseName}</database-name>
            <user>${MPCONFIG=dataSource.user}</user>
            <password>${MPCONFIG=dataSource.password}</password>
        </data-source>
    </web-app>

I've tested this solution with your reproducer and works without problems.

**Comment by haraldatbmw** [comment] 2020-02-14 08:09
@fturizo I just tested your recommended workaround in my reproducer without success.
I updated my reproducer code at https://github.com/haraldatbmw/payara-micro-mpconfig
I still get this error message when starting the application.

```bash
[2020-02-14T09:00:49.527+0100] [] [SEVERE] [] [javax.enterprise.resource.resourceadapter.com.sun.gjc.util] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1581667249527] [levelValue: 1000] [[
  RAR5099 : Wrong class name or classpath for Datasource Object
java.lang.ClassNotFoundException: ${MPCONFIG=dataSource.className}
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.sun.gjc.common.DataSourceObjectBuilder.getDataSourceObject(DataSourceObjectBuilder.java:264)
        at com.sun.gjc.common.DataSourceObjectBuilder.constructDataSourceObject(DataSourceObjectBuilder.java:110)
        at com.sun.gjc.spi.ManagedConnectionFactoryImpl.getDataSource(ManagedConnectionFactoryImpl.java:1388)
        at com.sun.gjc.spi.DSManagedConnectionFactory.getDataSource(DSManagedConnectionFactory.java:166)
        at com.sun.gjc.spi.DSManagedConnectionFactory.createManagedConnection(DSManagedConnectionFactory.java:104)
        at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.createResource(LocalTxConnectorAllocator.java:87)
        at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:920)
        at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1209)
        at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
        at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:287)
        at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1532)
        at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:957)
        at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:235)
        at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:528)
        at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:386)
        at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:244)
        at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:171)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
        at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:113)
        at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:138)
        at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:172)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:233)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:815)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:256)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:769)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:219)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:197)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.getDatabaseSession(EntityManagerFactoryImpl.java:542)
        at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:388)
        at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:316)
        at org.glassfish.persistence.jpa.PersistenceUnitLoader.loadPU(PersistenceUnitLoader.java:207)
        at org.glassfish.persistence.jpa.PersistenceUnitLoader.<init>(PersistenceUnitLoader.java:114)
        at org.glassfish.persistence.jpa.JPADeployer$1.visitPUD(JPADeployer.java:225)
        at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:525)
        at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:240)
        at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:170)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:1045)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:475)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:538)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:137)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1592)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1055)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:211)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:71)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]

[2020-02-14T09:00:49.531+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.resource.allocator] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1581667249531] [levelValue: 900] RAR5038:Unexpected exception while creating resource for pool __SYSTEM/pools/__datasource_definition/java:global/jdbc/reproducer. Exception : javax.resource.ResourceException: Class name is wrong or classpath is not set for : ${MPCONFIG=dataSource.className}

[2020-02-14T09:00:49.532+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1581667249532] [levelValue: 900] RAR5117 : Failed to obtain/create connection from connection pool [ __SYSTEM/pools/__datasource_definition/java:global/jdbc/reproducer ]. Reason : com.sun.appserv.connectors.internal.api.PoolingException: Class name is wrong or classpath is not set for : ${MPCONFIG=dataSource.className}

[2020-02-14T09:00:49.547+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.gjc.spi] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1581667249547] [levelValue: 900] RAR5114 : Error allocating connection : [Error in allocating a connection. Cause: Class name is wrong or classpath is not set for : ${MPCONFIG=dataSource.className}]
```

**Comment by haraldatbmw** [comment] 2020-02-14 08:13
@fturizo The ${MPCONFIG=xxx} only works if the environment variable is additionally set. But it does not read the value from the microprofile-config.properties

**Comment by smillidge** [comment] 2020-02-14 11:35
This is difficult to fix with locally deployed properties due to the nature of deployment. Datasources are created and verified before reading of locally set microprofile-config.properties as these are an application local resource. The datasource needs to be created early in the deployment due to the need to enable deployment of JPA classes. Globally defined MP properties like environment variables, system properties, secrets dir etc. should work.

**Comment by haraldatbmw** [comment] 2020-02-14 11:40
@smillidge Yes, environment variables and system properties are working. 
But this is only half of the MicroProfile Config API. You can't implement it half-way only.
For a new project I don't want to start with such a workaround! The config-file provides my with default values behavior.

Wouldn't it be possible to move the loading of the microprofile-config.properties before the JPA initialization?

**Comment by smillidge** [comment] 2020-02-14 11:41
Possibly. Not sure without doing it. There has been an issue raised. Part of my comment is to the team likely to look at creating the fix.

**Comment by haraldatbmw** [comment] 2020-02-14 11:42
@smillidge Thanks

**Comment by fturizo** [comment] 2020-02-14 16:21
@haraldatbmw, you are correct, I focused on testing your reproducer using system properties and environment variables and didn't test it using the default MPConfig properties file. With that in mind, there's no current workaround for this scenario and, understandably, you need a fix. I have updated the escalated issue with this information so that the fix is sufficient. Keep in mind that as @smillidge has said, there's an inherent complexity like deployment, so a proper fix may take some time. I have submitted his comments to this effect.

**Comment by rxcorreia** [comment] 2020-04-14 16:40
Any updates on this issue? 
I'm facing a similar challenge, since we need to read the DB credentials from a legacy file and were thus planning to use a custom ConfigSource to provide those values and use them in an web.xml datasource definition, via mp-config mechanism.

**Comment by fturizo** [comment] 2020-04-14 22:22
@rxcorreia, this issue is still  in our project backlog with a low priority and at the moment we do not have an estimate when it will be implemented. Please monitor its status on future releases.

**Comment by OndroMih** [comment] 2020-05-06 11:20
I know this isn't a proper fix but a simple workaround is to unpack the `microprofile-config.properties` file from the application and pass it to Payara Micro on command line with `--systemproperties` option:

```
java -jar payara-micro.jar --systemproperties microprofile-config.properties application.war
```

**Comment by phillipross** [comment] 2020-06-01 03:06
I believe I may have run into this issue in payara-server-full, but it seems to be a regression.  In my case it was working in the past (as of payara v5.192) but it broke in 5.193 and has been broken since then.

In my case, when using MPCONFIG= replacement populated via environment or system properties, the replacement works... but populating via secrets doesn't work.  I didn't test other mechanisms but now I'm curious.  And since the values populated via secrets ARE available after the app is running, I was guessing that it was some kind of init/deploy timing problem where the secrets config provider was no longer available early enough in the deployment process to to the replacement.

My workaround was to hook into the payara docker image init scripts and script out a process whereby the /run/secrets are read and create password aliases, then the apps use ALIAS= replacement.

I'm not sure if it's the same exact issue, but if it helps, I have a reproducer that uses docker-compose and the official payara-server-full docker images

**Comment by smillidge** [comment] 2020-06-01 08:56
How are the secrets being set up? I would say this is a different issue as the secrets config source is built in to Payara. Whereas the issue described here is only for properties set in the application via a mp-config.properties file or a custom config source in the application.

**Comment by phillipross** [comment] 2020-06-01 12:30
Actually, after reading back through the message, I now better understand the problem @haraldatbmw is having.

In my case, the secrets are set up externally as files in /run/secrets directory before payara is even started.  It's not part of the app which is being deployed.  I'll file a separate issue with all the details.

**Closed** 2020-08-07 14:04 UTC
Labels: status:accepted
