### ISSUE TITLE
MP OpenApi: empty document on maven-war-plugin

### ISSUE THREAD

**Issue by thomas-mc-work** [payara/Payara#4039] opened 2019-06-12 09:27 UTC
# Description #
----------

Adding a certain build plugin to the `pom.xml` leads to empty `paths` and `components` items in the generated `yaml` document at `http://payara-domain/openapi`.

## Expected Outcome

All paths should be listet as [described in the documentation](https://docs.payara.fish/documentation/microprofile/openapi.html):

```yaml
openapi: 3.0.0
info:
  title: Deployed Resources
  version: 1.0.0
servers:
- url: http://tdk:8080/openapi-example
  description: Default Server.
- url: https://tdk:8181/openapi-example
  description: Default Server.
paths:
  /api/hello:
    get:
      operationId: hello world
      responses:
        default:
          description: Default Response.
          content:
            text/plain:
              schema:
                type: string
components: {}
```

## Current Outcome

```yaml
openapi: 3.0.0
info:
  title: Deployed Resources
  version: 1.0.0
servers:
- url: http://tdk:8080/openapi-example
  description: Default Server.
- url: https://tdk:8181/openapi-example
  description: Default Server.
paths: {}
components: {}
```

Log output form Payara looks normal:

    INFO:   Loading application [openapi-example-1.0-SNAPSHOT] at [/openapi-example]
    INFO:   openapi-example-1.0-SNAPSHOT was successfully deployed in 165 milliseconds.
    INFO:   OpenAPI document created.

## Steps to reproduce (Only for bug reports) 

Add this build-plugin into the `pom.xml`:

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <archive>
                        <manifest>
                           <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                        </manifest>
                        <manifestEntries>
                            <Build-Time>${maven.build.timestamp}</Build-Time>
                        </manifestEntries>
                    </archive>
                    <archiveClasses>true</archiveClasses>
                </configuration>
            </plugin>
        </plugins>
    </build>

Background: I need this snippet to be able to read the application version at runtime.

### Samples

Based on [the Payara-Examples project "microprofile/openapi"](https://github.com/payara/Payara-Examples/tree/master/microprofile/openapi-example).

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full
- **JDK Version**: OpenJDK 1.8.0_212
- **Operating System**: Xubuntu 18.04.2

**Comment by smillidge** [comment] 2019-06-16 20:30
This is reporducible. However I can fix it with
`<archiveClasses>false</archiveClasses>`

this seems to be because without that the web app classes are packed into library jar in the `WEB-INF/lib`

Not sure whether this is a big or not @jbee any idea?

**Comment by jbee** [comment] 2019-06-17 07:18
My guess is that this is the same issue reported in #3769 with the common problem that we only process class files in `WEB-INF/classes/` but do not process archives within the top-most application archive. 

@smillidge Does that make sense with the behaviour you see for `<archiveClasses>`?

**Comment by smillidge** [comment] 2019-06-17 08:24
Makes sense.

**Comment by smillidge** [comment] 2019-06-29 06:46
Duplicate of #3769

**Closed by smillidge** 2019-06-29 06:46 UTC
Labels: reproducible
