### ISSUE TITLE
Do not close the EntityManagerFactory when --skipdsfailure flag is used during deployment /CUSTCOM-202

### ISSUE THREAD

**Issue by JohnValJohn** [payara/Payara#3677] opened 2019-01-31 18:50 UTC
# Description #
----------
At the moment, we can use the option --skipdsfailure to deploy an application without having a live connection to the database. This is great for docker containers.
However, when deploying with no database connection Payara closes the EntityManagerFactory, with or without the --skipdsfailure option. This means that requests that make use of the EntityManagerFactory will fail, even if they are sent after the database container was started.

## Expected Outcome

Ideally, when we use the option --skipdsfailure, the EntityManagerFactory should not be closed, so that subsequent requests that make use of it do not fail.

## Current Outcome

The drawback would be that the application would be responsible to clean up in case the database never become available.

## Steps to reproduce (Only for bug reports) 

In a CDI/Weld application, we obtain a container-managed entity manager instance like this:

@PersistenceContext
EntityManager em;

And then use it to make some queries, for example:
em.createQuery( query ).getResultList();

It works well when we deploy with the datasource up. 

However, if we: 
-deploy without a connection to the database, using --skipdsfailure
-start our database container
-send a request

we get the following error: "Attempting to execute an operation on a closed EntityManagerFactory."

The error disappears when commenting out line 464 of the following payara file:
https://github.com/payara/Payara/blob/66a9b2a84d2144a7169a7ecd009276d92026edc2/appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/JPADeployer.java

## Environment ##

- **Payara Version**: 5.184
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**:

**Comment by smillidge** [comment] 2019-02-02 19:46
Can you provide steps to reproduce the issue?

**Comment by JohnValJohn** [comment] 2019-02-11 12:20
I added some details on how I uncountered this issue

**Comment by rdebusscher** [comment] 2020-02-20 14:46
Hi,

I have created the internal ticket `CUSTCOM-202`  to fix this issue.

Regards
Rudy

**Comment by AlanRoth** [comment] 2020-11-11 11:30
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:30 UTC
Labels: status:accepted
