### ISSUE TITLE
Empty array items attribute in OpenApi document

### ISSUE THREAD

**Issue by LarsBrenker** [payara/Payara#4331] opened 2019-11-19 10:59 UTC
# Description #
----------

When using a custom data type with the @Schema annotation in the response, which in turn contains a list, the items attribute is sometimes empty and sometimes filled. The data type of the list is also a custom data type (simple pojo). The behavior can not be specially reconstructed. Sometimes the items attribute is empty, sometimes it is filled. Sometimes it is already empty at the start of the Payara and sometimes it is filled. Then again it is empty after a restart.

## Expected Outcome
```
 Error Response:
      properties:
        details:
          type: array
          description: List with detailed error information
          items:
            properties:
              key:
                type: string
                description: e.g. the field name
                example: id
              value:
                type: string
                description: why is this key invalid
                example: value required
            description: POJO that represents a detailed error info.
      description: POJO that represents an error response.
```

## Current Outcome

```
Error Response:
      properties:
        details:
          type: array
          description: List with detailed error information
          items: {}
      description: POJO that represents an error response.
```

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

2 -**  Call openapi endpoint
http://localhost:8080/openapi

3 -**  Check **components** -> **schemas** section
items Attribute of Error Response is sometimes filled and sometimes empty. 
Sometimes direclty at startup, sometimes after restart.

### Samples

```
@Schema(name = "Error Detail", description = "POJO that represents a detailed error info.")
public class ErrorDetailResponseDto {
    @Schema(name = "key", description = "e.g. the field name", example = "id")
    private String key;
    @Schema(name = "value", description = "why is this key invalid", example = "value required")
    private String value;

... (and getter and setter)
}
```

```
@Schema(name = "Error Response", description = "POJO that represents an error response.")
public class ErrorResponseDto {
    @Schema(name = "details", description = "List with detailed error information.", implementation = ErrorDetailResponseDto.class, type = SchemaType.ARRAY)
    private List<ErrorDetailResponseDto> details = new ArrayList();

... (and getter and setter)
}
```

## Environment ##

- **Payara Version**: 5.193
- **Edition**:  Micro
- **JDK Version**: Amazon Corretto 8u222
- **Operating System**:  Docker / Linux

**Comment by rdebusscher** [comment] 2019-11-21 10:38
Hi Lars,

This is a known issue and covered by the internal issue PAYARA-4172.

The problem is that the order in which the classes are treated is not fixed and that 'dependencies' aren't verified. This leads to incomplete information when classes are processed 'in the wrong order'.

The fix for this issue should be part of the upcoming 5.194 release.

regards
Rudy

**Comment by LarsBrenker** [comment] 2019-11-21 12:40
> 
> 
> Hi Lars,
> 
> This is a known issue and covered by the internal issue PAYARA-4172.
> 
> The problem is that the order in which the classes are treated is not fixed and that 'dependencies' aren't verified. This leads to incomplete information when classes are processed 'in the wrong order'.
> 
> The fix for this issue should be part of the upcoming 5.194 release.
> 
> regards
> Rudy

Thank you for your reply. Then we wait for the 5.194

**Comment by LarsBrenker** [comment] 2019-12-03 16:07
Hi Rudy,

the problem unfortunately still occurs in version 5.194. Now it looks like that in the components-> schemas section the responses are always complete. So the items array is always filled.
 
However, it is not always the case above in the paths descriptions. Sometimes the items attribute is filled, then again after a Payara restart. (see HTTP 500 Response e.g.)

After a few restarts, it is filled. Then again not.

```
openapi: 3.0.0
info:
  title: Payara Micro WS Prototype with Eclipse MicroProfile
  description: Payara Micro WS with Eclipse MicroProfile.
    Here you see usage and API Design.
  version: 1.0-SNAPSHOT
servers:
- url: http://localhost:8080
paths:
  /microWsPrototype/user/v2/find:
    get:
      tags:
      - user
      summary: Find user by id.
      description: Find a specific User by Datenbase PK ID
      operationId: findById
      parameters:
      - name: id
        in: query
        description: The database unique key.
        required: true
        style: simple
        schema:
          type: integer
        example: "1"
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  name:
                    type: string
                    description: the username
                    example: mustermann
                description: POJO that represents a user.
          description: Successful, returning the Username.
        "400":
          content:
            application/json:
              schema:
                properties:
                  exceptionKey:
                    type: string
                    description: Detailed information which error occured.
                    example: validation.constraintViolation
                    enum:
                    - validation.constraintViolation
                  details:
                    minItems: 1
                    type: array
                    description: List with detailed information about the errors (e.g.
                      which fields are empty or invalid).
                    items:
                      properties:
                        value:
                          type: string
                          description: why is this key invalid
                          example: empty value
                          enum:
                          - empty value
                          - invalid value
                        key:
                          type: string
                          description: e.g. the field name
                          example: id
                      description: POJO that represents a detailed error info.
                description: POJO that represents an HTTP 400 error.
          description: Bad Request.
        "500":
          content:
            application/json:
              schema:
                properties:
                  exceptionKey:
                    type: string
                    description: Detailed information which error occured.
                    example: processFailed
                    enum:
                    - processFailed
                  details:
                    maxItems: 1
                    type: array
                    description: List with detailed information about the errors.
                      In case of HTTP 500, this list is empty.
                    items: {}
                description: POJO that represents an HTTP 500 internal server error.
          description: Internal Server Error occured.
components:
  schemas:
    Error Detail:
      properties:
        value:
          type: string
          description: why is this key invalid
          example: empty value
          enum:
          - empty value
          - invalid value
        key:
          type: string
          description: e.g. the field name
          example: id
      description: POJO that represents a detailed error info.
    HTTP 400 (Bad Request):
      properties:
        exceptionKey:
          type: string
          description: Detailed information which error occured.
          example: validation.constraintViolation
          enum:
          - validation.constraintViolation
        details:
          minItems: 1
          type: array
          description: List with detailed information about the errors (e.g. which
            fields are empty or invalid).
          items:
            properties:
              value:
                type: string
                description: why is this key invalid
                example: empty value
                enum:
                - empty value
                - invalid value
              key:
                type: string
                description: e.g. the field name
                example: id
            description: POJO that represents a detailed error info.
      description: POJO that represents an HTTP 400 error.
    HTTP 500 (Internal Server Error):
      properties:
        exceptionKey:
          type: string
          description: Detailed information which error occured.
          example: processFailed
          enum:
          - processFailed
        details:
          maxItems: 1
          type: array
          description: List with detailed information about the errors.
          items:
            properties:
              value:
                type: string
                description: why is this key invalid
                example: empty value
                enum:
                - empty value
                - invalid value
              key:
                type: string
                description: e.g. the field name
                example: id
            description: POJO that represents a detailed error info.
      description: POJO that represents an HTTP 500 internal server error.
```

**Comment by rdebusscher** [comment] 2020-04-29 07:24
Reworking part of the OpenAPI implementation within Payara. Needs to be retested later.

**Comment by smillidge** [comment] 2020-08-12 21:39
Reworked api implementation was released in 5.2020.3

**Comment by AlanRoth** [comment] 2020-11-11 11:49
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:49 UTC
Labels: status:accepted

**Comment by LarsBrenker** [comment] 2021-04-08 13:22
I looked at it again in 5.2020.7 and noticed that it now works. Since when I can't say, but to close the subject properly I just wanted to say that the problem doesn't seem to exist anymore
