### ISSUE TITLE
Using client auth, timeout receiving httprequest in WS

### ISSUE THREAD

**Issue by itservices-trust** [payara/Payara#1457] opened 2017-03-14 15:34 UTC
# Description #
----------

We have Rest web services on a glassfish4 (payara) server Our rest client is based on httpClient Lib As Authentication we use certificate and basic auth. The client work well getting and posting infos to WS But when we send a multipart post with file bigger than few bytes, parsing the request hang until a timeout

If we disable the certification auth, all is working

## Expected Outcome

Having the post data correctly received

## Current Outcome

Receiving data wait until a timeout thrown 

## Steps to reproduce (Only for bug reports) 

prepare a RESTFUL WS to receive multipart request with files in attachment, configure CERT AUTH, prepare a client using HttpClient (apache client) and try send some file

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**:8 u0_1010 - Oracle
- **Operating System**: Linux

**Comment by fturizo** [comment] 2017-03-28 23:00
Hello @itservices-trust, can you attach some code samples to help us reproduce the issue? Try to post the following code samples:

* REST Service declaration
* Client code to call the service using Apache HTTP client

Also, how are you configuring CERT authorization on the server? Are you using a valid SSL certificate imported correctly on the server's key stores and had its alias configured for the HTTPS network listener?

**Comment by itservices-trust** [comment] 2017-03-31 13:27
I would like to confirm that it's a self signed cert, but I've configured to ignore it in http client, and the requests to the REST method are managed correctly if the packet received is not large (a few kb)
The same REST method works perfectly if I did not attach also the file
About Declaration, I'm not sure what exactly you are asking. Following the annotation I used and a cleaned up version of the method, until the row it hangs
````java
@Path("/messages")
@RolesAllowed({"WS_Lista_Messaggi"})
@Stateless
public class MessagesWebService extends AbstractWebService
{
    @POST
    @Path("/send")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    @RolesAllowed({"WS_Message"})
   public ReturnMessage sendMessage1(@Context HttpServletRequest httpRequest) throws IOException, JAXBException
    {
        ReturnMessage ret = new ReturnMessage();
        String info = null;
        List<UploadedFile> uploadedFiles = new ArrayList<>();
// Create a factory for disk-based file items
        FileItemFactory factory = new DiskFileItemFactory();
        // Create a new file upload handler - apache poi class
        ServletFileUpload upload = new ServletFileUpload(factory);
        // Parse the request
        Iterator items;
        try {
            items = upload.parseRequest(httpRequest).iterator();
            while (items.hasNext()) {
                FileItem thisItem = (FileItem) items.next();
                if (thisItem.getFieldName().equals("info")) {
                    info = thisItem.getString();
                }
                else if (thisItem.getFieldName().equals("file")) {
                    uploadedFiles.add(new ByteArrayUploadedFile(thisItem.get(), thisItem.getName(), thisItem.
                                                                getContentType()));
                }

            }
        }
        catch (FileUploadException ex) {
            LOG.log(Level.INFO, "Errore uploading messages", ex);
            ret.setStatus(ReturnStatusEnum.ERROR);
            ret.setErrorCode(ReturnErrorCodeEnum.FILE_NOT_UPLOADED);
            return ret;
        }

    }
}
````
at line with `thisItem.get()`, after a few byte, stop receiving

**Comment by itservices-trust** [comment] 2017-03-31 13:50
The HttpClient part 
````java
    public static void main(String[] args) throws FileNotFoundException, IOException, URISyntaxException,
                                                  KeyStoreException, NoSuchAlgorithmException, CertificateException,
                                                  KeyManagementException, UnrecoverableKeyException
    {
        CloseableHttpClient httpClient = null;
        String protocol = null;
        Integer port = null;
        ConnectionConfig connConfig = ConnectionConfig.custom()
                .setBufferSize(DESIRED_BUFFER_SIZE)
                .build();
        protocol = "https";
        port = 8181;
        KeyStore keystore = KeyStore.getInstance("PKCS12");
        keystore.load(new FileInputStream(new File(CERT)), CERT_PWD.toCharArray());
        SSLContext sslcontext = SSLContexts.custom().loadKeyMaterial(keystore, CERT_PWD.toCharArray()).
                loadTrustMaterial(new TrustSelfSignedStrategy()).build();
        SSLConnectionSocketFactory sslsf = new SSLConnectionSocketFactory(
                sslcontext,
                new String[]{"TLSv1",
                             "TLSv1.1",
                             "TLSv1.2"},
                null,
                new NoopHostnameVerifier());
        Registry<ConnectionSocketFactory> registry = RegistryBuilder.<ConnectionSocketFactory>create()
                .register("https", sslsf)
                .register("http", new PlainConnectionSocketFactory())
                .build();

        HttpClientBuilder builder = HttpClientBuilder.create();
        builder.setSSLSocketFactory(sslsf);
        builder.setConnectionManager(new PoolingHttpClientConnectionManager(registry));
        httpClient = builder.build();
        CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
        credentialsProvider.setCredentials(
                new AuthScope(AuthScope.ANY_HOST, AuthScope.ANY_PORT),
                new UsernamePasswordCredentials("user", "Password"));
        HttpHost targetHost = new HttpHost(host, port, protocol);
        AuthCache authCache = new BasicAuthCache();
        authCache.put(targetHost, new BasicScheme());

        HttpClientContext localContext = HttpClientContext.create();
        localContext.setCredentialsProvider(credentialsProvider);
        localContext.setAuthCache(authCache);
        String baseUrl = protocol + "://" + host + ":" + port + "/" + wsPath;

        HashMap<String, File> fileMap = new HashMap<>();
        fileMap.put("test.txt", new File("./uploadTestFiles/test.txt"));
        fileMap.put("test1.txt", new File("./uploadTestFiles/test1.txt"));
        fileMap.put("test2.txt", new File("./uploadTestFiles/test2.txt"));
        fileMap.put("test3.txt", new File("./uploadTestFiles/test3.txt"));

        JSONObject session = new JSONObject();

        session.put("mbxId", mbxId);

        session.put("subject", subject);
        session.put("body", body);

        session.append("toContacts", toId1);
        session.append("toContacts", toId2);

        CloseableHttpResponse response;
        HttpEntity responseEntity;
        HttpPost request;
        request = new HttpPost(baseUrl + module + "/" + wsName);

        MultipartEntityBuilder entBuilder = MultipartEntityBuilder.create();
        entBuilder.addTextBody("info", session.toString(), ContentType.APPLICATION_JSON);

        for (File file : fileMap.values()) {
            entBuilder.addBinaryBody("file", file, ContentType.APPLICATION_OCTET_STREAM, file.getName());
        }
        HttpEntity multipart = entBuilder.build();
        request.setEntity(multipart);
        response = httpClient.execute(request, localContext);
        responseEntity = response.getEntity();
    }    

````

**Comment by itservices-trust** [comment] 2017-03-31 13:57
The certificate auth by payara seems work correctly (the realm check the certificate, authenticate it and assign relevant roles)
The first part of the request (the "info" text body part) is read with no problem
If the first two o three file are little (a few bytes) they are read too. 
The process get stuck when a file is more the some Kb

**Comment by fturizo** [comment] 2017-04-10 23:36
Greetings @itservices-trust,

I could successfully reproduce the error on _Payara Server 4.1.1.171_.  As you mentioned it, the server will timeout at some point after trying to get the part data of files greater than 2MB approximately when using `CLIENT-CERT` authentication. This timeout is caused due to the way the web container saves the parts that make the POST during authentication: When using the `CLIENT-CERT` authentication, the request POST size will be increased due to the contents of the SSL certificate (self-signed or not doesn't matter) to authenticate the request with the container, so when the total size of the POST request exceeds the default value (**4096** Bytes), it will block the server and timeout.  

To solve this, increase the **Max Save POST** Size value of the HTTP listener used to call the REST service (since you are using HTTPS, then it should be http-listener-2 by default):

```shell
set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.max-save-post-size-bytes=104857600
```

Change the size to a proper value that works for the average size of the requests for your application. 

Also, I wouldn't recommend using the Apache Commons FileUpload to parse the request and get the file parts on a REST service. It's best to simply use the Native API introduced on Servlet 3.0:

```java
@POST
@Path("/send")
@Consumes(MediaType.MULTIPART_FORM_DATA)
public ReturnMessage sendMessage(@Context HttpServletRequest httpRequest) throws IOException, ServletException{
      ...
      for(Part part : httpRequest.getParts()) {
            if(part.getName().equals("info")){
                try(InputStreamReader reader = new InputStreamReader(part.getInputStream(), Charsets.UTF_8)){
                    LOG.log(Level.INFO, "Info entity: {0}", CharStreams.toString(reader));
                }
            }else if(part.getName().equals("file")){
                InputStream stream  = part.getInputStream();
                UploadedFile uFile = new UploadedFile(ByteStreams.toByteArray(stream), part.getSubmittedFileName(), part.getContentType());
            }
      }
      ...
}
```

Keep in mind that to access the parts using the Native API, the REST servlet needs to be enabled with `MultipartConfig` support. Simply configure your REST application config class like this (notice that there is no `@Application` annotation in place):

```java
public class ApplicationConfig extends Application{

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> classes = new HashSet<>();
        classes.add(MessagesWebService.class);
        return classes;
    }
}
```

And map this class to a Servlet declaration on the web.xml configuration file:

```xml
<servlet>
   <servlet-name>fish.payara.support.clientcertrestupload.ApplicationConfig</servlet-name>
   <multipart-config>
      <file-size-threshold>0</file-size-threshold>
   </multipart-config>
</servlet>
<servlet-mapping>
  <servlet-name>fish.payara.support.clientcertrestupload.ApplicationConfig</servlet-name>
  <url-pattern>/rest/*</url-pattern>
</servlet-mapping>
```

**Comment by fturizo** [comment] 2017-05-16 02:54
Greetings @itservices-trust, since we haven't received a reply from your part that the issue could be solved with our suggestions then I'm going to close the issue since there are no problems on Payara Server. If you experience another issue related to this one or if you have any other questions regarding the solutions provided, feel free to reopen this issue.

**Closed by fturizo** 2017-05-16 02:54 UTC
Labels: 1:Wait, c:Misconfiguration

**Comment by itservices-trust** [comment] 2017-05-16 08:09
Sorry to haven't commented your post, I was sure it had done: your comment was really useful for us, thanks for the support
