### ISSUE TITLE
Unable to access a local EJB from a JAX-RS resource

### ISSUE THREAD

**Issue by trajano** [payara/Payara#394] opened 2015-08-11 17:47 UTC
I created a simple example at https://github.com/trajano/test/tree/local-beans

Here's the crux of the sample
* A simple `@Stateless` SLSB
* A JAX-RS resource annotated with `@Stateless`
* The resource has an `@EJB` reference
* The `@PostConstruct` method simply does a System.out

In my example it fails the moment the resource SLSB is postconstructed when http://localhost:8080/test-war/V1/resource is accessed

(upstream bug) https://java.net/jira/browse/GLASSFISH-21412

**Comment by trajano** [comment] 2015-08-11 19:26
Seems to be the same as #377

**Comment by smillidge** [comment] 2015-08-12 18:22
Hi I can't seem to reproduce your problem with your example;

If I access http://localhost:8080/test-war/hello I get output
Hello=net.trajano.test.api.Hello_1370887394
Hello2=net.trajano.test.api.Hello2_347377840

Which shows both EJBs injected.

If I access

http://localhost8080/test-war/V1/.well-known/openid-configuration

I get {"scopes_supported":["address","openid"],"claims_parameter_supported":false,"request_parameter_supported":false,"request_uri_parameter_supported":true,"require_request_uri_registration":false}

You don't seem to have a JAX-RS resource configured for path http://localhost:8080/test-war/V1/resource

Your JAX-RS resource is configured on path @Path(".well-known/openid-configuration")

**Comment by trajano** [comment] 2015-08-12 18:35
Did you use the `local-beans` branch?

**Comment by trajano** [comment] 2015-08-12 18:37
The `master` branch works and I used it as a base line.

**Comment by smillidge** [comment] 2015-08-12 19:37
I used the local-beans branch

**Comment by trajano** [comment] 2015-08-12 19:39
Interesting... local-beans branch should not have `@Path(".well-known/openid-configuration")`  It was removed in this commit https://github.com/trajano/test/commit/8180adab484deb9c67cddc87964d7246f47e41a1#commitcomment-12673394

**Comment by smillidge** [comment] 2015-08-12 19:48
Sorry I got that wrong I was building master.

It is the same problem as #377 

You can fix your example by;

1) Removing @Stateless from Resource (as it is not strictly necessary in this example)
2) Adding a beans.xml to WEB-INF with content;
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
       bean-discovery-mode="all">
</beans>
```

I need to investigate further but adding @Stateless to the resource is causing Jersey to look in the incorrect module names space;

No object bound to name java:app/test-ejb2-0.0.1-SNAPSHOT/Resource!net.trajano.test.Resource

when the EJB is deployed in;

java:global/test-ear-0.0.1-SNAPSHOT/test-war-0.0.1-SNAPSHOT/Resource!net.trajano.test.Resource

this needs further investigation.

**Comment by smillidge** [comment] 2015-08-12 20:15
Alternatively you can Remove @Stateless and add @RequestScoped and not bother with the beans.xml

**Comment by trajano** [comment] 2015-08-12 20:19
I have to see if that would work on a larger example with JPA

http://stackoverflow.com/questions/20558125/stateless-vs-requestscoped

I think it would provided I don't do the JPA inside the JAX-RS resource.  I never do that anyway because I always wanted CMT.

**Comment by smillidge** [comment] 2015-08-12 20:29
If you need the transactions that the Stateless session bean provides you can use the JavaEE 7 @Transactional annotation on the resource method.
http://docs.oracle.com/javaee/7/api/javax/transaction/Transactional.html

For example
```java
@RequestScoped
@Path("resource")
public class Resource {

	@EJB
	WebSideSlsb slsb;

	@GET
	@Produces(MediaType.APPLICATION_JSON)
    @Transactional(Transactional.TxType.REQUIRED)
	public Response get() {

		return Response.ok(Json.createArrayBuilder().add("hello world").build()).build();
	}

	@PostConstruct
	public void init() {
		System.out.println("POSTCONSTRUCT");
		System.out.println(slsb);
	}
}
```

**Comment by trajano** [comment] 2015-08-12 20:33
I'll try those out.  I use  @TransactionAttribute(TransactionAttributeType.REQUIRED) normally but yours should work too.

**Comment by schoendort** [comment] 2015-08-13 08:10
Is this a bug? Will it be fixed in the next build? 
I try to make our application compatible with wildfly, glassfish and payara. And this is the only point that I can't solve yet. Because Wildfly needs the @Stateless. I'll try it also with @RequestScoped.

**Comment by smillidge** [comment] 2015-08-13 08:58
Wildfly shouldn't require @Stateless. However for EJB injection to work you may require a beans.xml as mentioned above without @Stateless. 

Alternatively adding the @RequestScoped triggers CDI to scan the whole archive and do the injection.

wrt to whether it is a bug, we'll do some more investigation into Jersey's behaviour here.

**Comment by trajano** [comment] 2015-08-13 09:52
@schoendort  WildFly actually does not work with `@Stateless` for their web resources.  https://issues.jboss.org/browse/WFLY-5072

However, I chose to switch `@ManagedBean` to `@RequestScoped` as it seems that `@ManagedBean` may be deprecated in the future for more CDI specific scopes.

**Comment by trajano** [comment] 2015-08-13 10:12
@schoendort if you're not doing anything with JASPIC, I also recommend making your app work with WebSphere Liberty.

**Comment by schoendort** [comment] 2015-08-13 11:24
@trajano thanks for this advice, but I think thats only the combination with @Stateless and @WebListner because I have a few JAX-RS webservices with @ApplicationPath which extends "javax.ws.rs.core.Application" and these add classes as resources with @Stateless. And this is running on wildfly 9.0.1.final. But @RequestScoped is not running, or maybe I not able to make it runnable. 
Thats with Websphere liberty is interesting, but unfortunately we using JASPIC

**Comment by trajano** [comment] 2015-08-13 11:29
If you have a separate issue for WildFly I can post my findings there rather than this issue thread.

**Comment by smillidge** [comment] 2015-08-15 21:34
Closing this as is a duplicate of #377
We have a patch for this follow #377 to know when it has been pulled into Payara

**Closed by smillidge** 2015-08-15 21:34 UTC
Labels: reproducible
