### ISSUE TITLE
JdbcRuntimeExtension prints to System.out /CUSTCOM-80

### ISSUE THREAD

**Issue by loefberg** [payara/Payara#4382] opened 2019-12-13 09:23 UTC
JdbcRuntimeExtension#getAllSystemRAResourcesAndPools() prints to System.out. This is mildly annoying.

The offending code resides in [JdbcRuntimeExtension.java ](https://github.com/payara/Payara/blob/c2905122f21f49ed1455612bdc3aded5b1d1f2ce/appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/JdbcRuntimeExtension.java#L112)at line 112:
`System.out.println("JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = " + resources);`

**Comment by dmatej** [comment] 2019-12-14 20:42
Thanks for reporting, we created an internal issue CUSTCOM-80.

**Comment by AlanRoth** [comment] 2020-11-11 11:50
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:50 UTC
Labels: status:accepted
