### ISSUE TITLE
ERROR JDBC MSSQL ERROR

### ISSUE THREAD

**Issue by Siscon-Ng** [payara/Payara#2252] opened 2018-01-10 18:44 UTC
Hi 

Trying to insert a JDBC pool into the MSSQL server on payara 5

[2018-01-10T16:31:50.981-0200] [Payara 5..Beta1] [GRAVE] [NCLS-RSCL-00004] [javax.enterprise.admin.rest.client] [tid: _ThreadID=155 _ThreadName=admin-thread-pool::admin-listener(7)] [timeMillis: 1515609110981] [levelValue: 1000] [[
  An error occurred while processing a JSON object.
javax.json.stream.JsonParsingException: Unexpected char 58 at (line no=1, column no=345, offset=344)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:601)
	at org.glassfish.json.JsonTokenizer.unescape(JsonTokenizer.java:231)
	at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:184)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:379)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:459)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:363)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:338)
	at org.glassfish.json.JsonParserImpl.getValue(JsonParserImpl.java:182)
	at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:326)
	at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:164)
	at org.glassfish.admin.rest.client.utils.MarshallingUtils.getPropertiesFromJson(MarshallingUtils.java:85)
	at org.glassfish.admin.rest.readers.JsonPropertyListReader.readFrom(JsonPropertyListReader.java:88)
	at org.glassfish.admin.rest.readers.JsonPropertyListReader.readFrom(JsonPropertyListReader.java:66)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:73)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:271)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:97)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:80)
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:74)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:92)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:133)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:318)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:180)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:242)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Unknown Source)
]]
[2018-01-10T16:31:51.009-0200] [Payara 5..Beta1] [GRAVE] [] [org.glassfish.admingui] [tid: _ThreadID=102 _ThreadName=admin-thread-pool::admin-listener(4)] [timeMillis: 1515609111009] [levelValue: 1000] [[
  RestResponse.getResponse() dá FAILURE. endpoint = 'http://localhost:4848/management/domain/resources/jdbc-connection-pool/Siscon_JEE/property.json'; attrs = '[{"name":"Description","description":"","value":"siscon_jee"},{"name":"TrustServerCertificate","description":"","value":"false"},{"name":"User","description":"","value":"sa"},{"name":"LastUpdateCount","description":"","value":"true"},{"name":"ResponseBuffering","description":"","value":"adaptive"},{"name":"URL","description":"","value":"jdbc\:sqlserver\:\/\/"},{"name":"XopenStates","description":"","value":"false"},{"name":"PacketSize","description":"","value":"8000"},{"name":"Password","description":"","value":"sisprog"},{"name":"ApplicationName","description":"","value":"Microsoft JDBC Driver for SQL Server"},{"name":"DatabaseName","description":"","value":"SISCON_RJ_WEB"},{"name":"Encrypt","description":"","value":"false"},{"name":"LockTimeout","description":"","value":"-1"},{"name":"SendStringParametersAsUnicode","description":"","value":"true"},{"name":"MultiSubnetFailover","description":"","value":"false"},{"name":"ApplicationIntent","description":"","value":"readwrite"},{"name":"LoginTimeout","description":"","value":"15"},{"name":"WorkstationID","description":"","value":"PC-ALEX"},{"name":"ServerName","description":"","value":"servidorjava"},{"name":"PortNumber","description":"","value":"1433"},{"name":"SelectMethod","description":"","value":"direct"},{"name":"SendTimeAsDatetime","description":"","value":"true"}]']]

**Comment by mikecroft** [comment] 2018-01-10 18:55
Duplicate of  #2149

**Closed by mikecroft** 2018-01-10 18:55 UTC
