### ISSUE TITLE
Virtual server configuration is not propagated to WebModule - FISH-765 

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#4653] opened 2020-05-05 16:50 UTC
# Description #
----------
IE11 has problem with resources served over HTTPS connection.
This is caused by Pragma header, that is added by Catalina to response. (see https://docs.payara.fish/docs/5.201/documentation/payara-server/server-configuration/http/virtual-servers.html  securePagesWithPragma)

Debug showed that the VirtualServer parameter of Webmodule#configureMiscSettings is configured properly (securePagesWithPragma=false as defined in additional properties of virtual server "server") but code copies bean.getWebProperty() that does not contain any configuration.
Missing propagation of configuration then causes WebModule and AuthenticatorBase to be field initialized to default value, which is "true".

```
           WebProperty[] props = bean.getWebProperty(); // empty array
            for (WebProperty prop : props) {
            ...
                else if("securePagesWithPragma".equalsIgnoreCase(name)) {
                   // this path is not called
                    boolean securePagesWithPragma = ConfigBeansUtilities.toBoolean(value);
                    setSecurePagesWithPragma(securePagesWithPragma);
                } 
             ....
          }
```

## Expected Outcome
Header "Cache-Control: private" is sent.

```
            else {
                sresponse.setHeader("Cache-Control", "private");
            }
```

## Current Outcome
Headers "Cache-Control: no-cache" and "Pragma: No-cache" are sent.
```
           if (securePagesWithPragma) {
                // FIXME: These cause problems with downloading office docs
                // from IE under SSL and may not be needed for newer Mozilla
                // clients.
                sresponse.setHeader("Pragma", "No-cache");
                sresponse.setHeader("Cache-Control", "no-cache");
            } else {             
```

## Steps to reproduce (Only for bug reports) 

1) configure securePagesWithPragma=false in additional properties of virtual server
2) deploy some application
3) check headers returned in response

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **JDK Version**: OpenJDK 11
- **Operating System**:  Linux

**Comment by hberton** [comment] 2020-05-12 22:56
I I have the same problem

**Comment by AlanRoth** [comment] 2020-11-17 09:35
Hi @sgflt, can you try to reproduce this issue with Payara Community verision 5.2020.6? If the issue still occurs, could you please provide a reproducer ideally following the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by sgflt** [comment] 2020-11-18 10:49
Improved description of each step:

1. configure securePagesWithPragma=false in additional properties of virtual server
![Snímek obrazovky pořízený 2020-11-18 11-21-08](https://user-images.githubusercontent.com/6689451/99519929-c3179a00-2992-11eb-8acd-0ec0639a28cc.png)

2. deploy ~~some application~~ https://github.com/sgflt/payara-test-case to domain1
3. check headers returned in response `curl -i http://localhost:8080/bug/ajax.xhtml | grep Pragma` (Pragma should not be printed)

Startup debug, where VirtualServer should provide configured properties to WebModule:
![Snímek obrazovky pořízený 2020-11-18 11-34-24](https://user-images.githubusercontent.com/6689451/99520606-94e68a00-2993-11eb-81fd-8ed4fa6401af.png)

But nothing changed:
![Snímek obrazovky pořízený 2020-11-18 11-34-42](https://user-images.githubusercontent.com/6689451/99520664-ab8ce100-2993-11eb-98b7-0a0b80eeccc1.png)
![Snímek obrazovky pořízený 2020-11-18 11-35-50](https://user-images.githubusercontent.com/6689451/99520701-b8113980-2993-11eb-8b37-b93e0c7ed270.png)

And this code pushes Pragma to headers:
![Snímek obrazovky pořízený 2020-11-18 11-48-03](https://user-images.githubusercontent.com/6689451/99520909-00c8f280-2994-11eb-9844-e8fdb62a6a19.png)

**Comment by sgflt** [comment] 2020-11-18 11:37
I have created draft PR #4997, but I am not sure if sun-web.xml is supposed to be merged with VirtualServer, or ignored, or used with preference, or purged from code as deprecated feature, or something else.

**Comment by AlanRoth** [comment] 2020-11-18 15:23
Hi @sgflt,

Thank you for such a detailed response. If you're happy to submit a PR then I have created an internal ticket `FISH-765`.

**Comment by lprimak** [comment] 2021-05-12 19:38
Close this issue @sgflt ?

**Closed** 2021-05-14 13:29 UTC
Labels: Status: Accepted, Type: Bug
