### ISSUE TITLE
Restart deployment group not working properly / FISH-993

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#5084] opened 2021-01-04 08:25 UTC
# Description #
----------

When you have a deployment group and click restart deployment group the first server restarts, and the second stays stopped. Issue is constant, easy to reproduce:
![obraz](https://user-images.githubusercontent.com/41665450/103515240-a7971e80-4e6e-11eb-9451-241fd1ea8d64.png)

Second instance has to be started manually. This issue was not visible in earlier versions of Payara.

## Environment ##

- **Payara Version**: 5.2020.7
- **Edition**: Full
- **JDK Version**: zulu 11
- **Operating System**: Linux

**Comment by AlanRoth** [comment] 2021-01-11 16:49
Hi @peterpz1, 

I was able to reproduce the issue but not in the way you described, starting/stopping the server only starts/stops a single instance the same way you have pictured, restarting both the instances works fine after manually starting the stopped instance.

I created a internal issue `FISH-993`. Thank you.

**Comment by smillidge** [comment] 2021-03-27 17:02
This is not reproducible on latest master. I tried creating a deployment group with two instances and both restarted using restart deployment group in a rolling restart. I manually stopped an instance and selected restart deployment group and it detected one server was stopped and started it and then restarted the other server.

**Comment by AlanRoth** [comment] 2021-07-07 16:52
Greetings @peterpz1, 

As @smillidge has commented - the issue is no longer reproducible. I will close this issue because of this - feel free to re-open this issue if you feel like this issue has not been resolved.

Thank you for your understanding,
Alan

**Closed by AlanRoth** 2021-07-07 16:52 UTC
Labels: Status: Accepted, Type: Bug
