### ISSUE TITLE
Payara server not deleting the log files  when watchdog service is running

### ISSUE THREAD

**Issue by sameencse** [payara/Payara#4960] opened 2020-10-20 10:00 UTC
# Payara 5.194 server is not automatically cleaning up the Payara logs. #
----------

## Expected Outcome
Payara server should automatically delete the log files when it cross the limit 'maxHistoryFiles'

## Server is not deleting the logs files, it quickly fills up the desk space 4-6 GB, 
it throws the below error
`[2020-10-19T13:15:01.736+0530] [Payara 5.194] [SEVERE] [] [] [tid: _ThreadID=28 _ThreadName=GFFileHandler log pump] [timeMillis: 1603093501736] [levelValue: 1000] [[
  java.util.logging.ErrorManager: 0: FATAL ERROR: COULD NOT DELETE LOG FILE.]]

[2020-10-19T13:15:01.737+0530] [Payara 5.194] [SEVERE] [] [] [tid: _ThreadID=28 _ThreadName=GFFileHandler log pump] [timeMillis: 1603093501737] [levelValue: 1000] [[
  java.io.IOException: Could not delete log file: D:\Tools\server\FinAid\JFA\logs\server.log.lck
	at com.sun.enterprise.server.logging.GFFileHandler.cleanUpHistoryLogFiles(GFFileHandler.java:827)
	at com.sun.enterprise.server.logging.GFFileHandler.lambda$rotate$2(GFFileHandler.java:905)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.enterprise.server.logging.GFFileHandler.rotate(GFFileHandler.java:845)
	at com.sun.enterprise.server.logging.GFFileHandler.log(GFFileHandler.java:967)
	at com.sun.enterprise.server.logging.GFFileHandler$1.run(GFFileHandler.java:581)
]]`

## Steps to reproduce (Only for bug reports) 

1. Configure the payara server as windows services
2. Run the payara server with --watchdog set it to true.
3.Once its reaches the threshold, it throws the "java.util.logging.ErrorManager: 0: FATAL ERROR: COULD NOT DELETE LOG FILE" Error
4.Fill up the disk space quickly, need to delete the files manually. 

## Context (Optional)

Multiple web application deployed on payara server and running as a windows services configured, the windows configuration xml file include <startargument>--watchdog</startargument> and log rotation in domain.xml is set to `log-rotation-limit-in-bytes="2000000`, logging properties `com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles=10`, once it reaches the threshold it throws the 'COULD NOT DELETE LOG FILE.' 

Found the similar behavior observed in glassfish gitbub link  [https://github.com/eclipse-ee4j/glassfish/issues/21275](url)  but no proper solution.

Any suggestion on this?

PS:: Found the similar issue when just running the payara server with asadmin command "start-domain --verbose --debug --domainDir " 

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**:  OpenJDK
- **Operating System**: Windows
- **Database**:  SQL Server

**Comment by rdebusscher** [comment] 2020-11-02 15:30
Hi,

It this possibly that it is an issue of permissions, the user running the Payara server as service is not allowed to delete those files?

Regards
Rudy

**Comment by sameencse** [comment] 2020-11-04 07:04
Hi rdebusscher,
  I recheck, it doesn't have any permission issue, user which runs the payara server has full access, right now we are writing the batch script to delete those files. Please let me know if you need any other information

**Comment by MeroRai** [comment] 2020-11-16 10:18
Hi @sameencse, 

Could you test this and see if it is still an issue in on our current release of Payara Server Community, which is `5.2020.6`. 

Kind regards,
Susan Rai

**Comment by MeroRai** [comment] 2020-11-23 10:26
Hi @sameencse,

Could I get an update on this issue? Have you managed to test it on the current release of Payara Server Community?

Kind regards,
Susan Rai

**Comment by sameencse** [comment] 2020-12-01 08:49
@MeroRai 
Not yet, working on tight schedule. I will let you know once i tested on new version of payara server.

**Comment by AlanRoth** [comment] 2020-12-08 09:14
@sameencse, any updates on your progress?

**Comment by MeroRai** [comment] 2020-12-23 11:28
Hi @sameencse, since we haven’t received any updates from you, we’ll proceed to close this issue. Feel free to re-open it in the future if you are able to reproduce the problem successfully using the current release of Payara Community Edition at that point in time.

**Comment by sameencse** [comment] 2021-03-04 12:39
Hi @MeroRai / @AlanRoth @rdebusscher 

Tested this issue in payara 5.2021.1(see the below version of payara/jdk)

-    Payara Version: 5.2021.1
- 	Edition: Full
- 	JDK Version: openjdk version "11.0.10" 2021-01-19 LTS (Zulu11.45+27-CA)
- 	Operating System: Windows

This issue is still exist and server logs are not clearing.

**Comment by MeroRai** [comment] 2021-03-05 10:47
Hi @sameencse, thank you for testing it on the latest release of Payara Community Edition. When I have time I will test it myself and let you know the results.

**Comment by MeroRai** [comment] 2021-04-20 08:43
Hi @sameencse, I have managed to test this issue and the log files are successfully deleted. It is most likely the issue is with your environment.

**Closed by MeroRai** 2021-04-20 08:43 UTC
Labels: Status: Open, Type: Bug

**Comment by andresku** [comment] 2021-09-22 09:12
Hi @MeroRai , why this topis was closed? The problem was not solved. As far as I have recognized it correctly, the file server.log.lck is generated by the watchdog process, which is started automatically by the Windows service. Unfortunately, Watchdog uses the Glassfish / Payara log directory for its lock file. This is seen by Payara as one of the many log files and is also taken into account in "Maximum History Files". However, since it cannot be deleted as a lock file, the thread responsible receives an exception. As a result, the entire log cleaning does not work.
Some start options for the watchdog can be set in the file ...\domains\_domainname_\bin\_domainname_Service.xml. Unfortunately the directory for the lock file cannot be changed. But that would solve the whole problem.

**Comment by mirozitnansky** [comment] 2022-12-16 16:05
@andresku have you been able to resolve it? We same same issue version 5.2022.4, zulu-11, windows server 2016

**Comment by andresku** [comment] 2022-12-16 17:14
@mirozitnansky No, the solution to the problem can only be done by changing the service watchdog program for Payara/Glassfish.
I applied a workaround: I set "Maximum History Files" to 0, and run a log deletion script as a planned task once a day, which limits the number of log files to NBKEEP:
rem Keep only the newest %NBKEEP% Payara log files 
cd /d %GFLOGDIR%
FOR /f "skip=%NBKEEP% eol=: delims=" %%F IN ('dir /b /o-d *.log_*') do @del "%%F"
