### ISSUE TITLE
NPE in prettyDateTimeFormat

### ISSUE THREAD

**Issue by a-genius** [payara/Payara#2216] opened 2017-12-18 04:21 UTC
# Description #
----------

https://github.com/payara/Payara/blob/master/appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/PayaraUtilHandlers.java throws NPE in line 81:

	public static void prettyDateTimeFormat(HandlerContext context){
        String value = (String) context.getInputValue("milliseconds");
        String result = DateFormat.getDateTimeInstance().format(new Date(Long.valueOf(value)));	// throws NPE if value == null
        context.setOutputValue("prettyString", result);
    }

## Expected Outcome

Input should be validated before use. I got this NPE after a change to an application (adding an attribute). InvocationTargetException while attempting to process a 'beforeCreate' event for 'deploymentOccuranceTime'

## Current Outcome

NPE prevents display of tabs (Installed application > Descriptor,Resources,Target and Configuration Properties)

## Steps to reproduce (Only for bug reports) 

Add a configuration property to a web application
 

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**:  Full 
- **JDK Version**: Oracle JDK 8
- **Operating System**: Linux
- **Database**:

**Comment by Cousjava** [comment] 2017-12-19 14:39
I was unable to reproduce your issue, I could add an attribute to the application and then go back to the applications page without an errors being thrown.

**Comment by a-genius** [comment] 2017-12-19 23:53
I don't know exactly which value causes the problem. I tried to fix the domain.xml by removing my entry, but the bug is still there. Anyway, Long.valueOf tries to parse the input string and it obviously fails if the string can't be parsed. So adding some form of input validation is good defensive programming and it won't cost you an arm and a leg.

**Comment by michaelranaldo** [comment] 2018-01-25 11:41
Hi @a-genius ,

Similarly, I've been unable to reproduce this issue. 

However, I have created an internal JIRA `PAYARA-2440`.

Were you able to get your domain working in the end?

**Comment by smillidge** [comment] 2018-02-24 23:30
Fixed by #2424

**Closed by smillidge** 2018-02-24 23:30 UTC
Labels: 1:Investigating, c:PossibleBug, cannot reproduce
