### ISSUE TITLE
Slow startup/hang when application uses Eclipselink and genericra

### ISSUE THREAD

**Issue by bdrx312** [payara/Payara#197] opened 2015-02-05 20:47 UTC
I was using Glassfish 4.1 until we discovered we were affected by a critical bug ([GLASSFISH-21118][1]). I just tried updating to Payara 1.4.151 but am experiencing extremely slow shutdown and startup times compared to glassfish 4.1. In Glassfish my startup takes about 1 minute. The same domain and applications take 3-7 minutes in Payara.

Specifically on startup, in the logs I notice it hanging every time with these messages:

    [2015-02-05T...][Payara 4.1][INFO][][javax.enterpise.system.container.ejb.org.glassfish.ejb.persistent.timer][tid: _ThreadId=17 _ThreadName=RunLevelControllerThread-...][timeMillis: ...][levelValue: 800][[
     ==> Restoring Timers ...]]

    [2015-02-05T...][Payara 4.1][INFO][][org.eclipse.persistence.session.file:...applications/ejb-timer-service-app/WEB-INF/classes/__EJB__TIMER__App][tid: _ThreadId=17 _ThreadName=RunLevelControllerThread-...][timeMillis: ...][levelValue: 800][[
       Eclipselink, version: Eclipse Persistence Services - 2.5.2.p1]]

The log hangs there for 1-2 minutes then continues with

    [2015-02-05T...][Payara 4.1][INFO][][org.eclipse.persistence.session.file:...applications/ejb-timer-service-app/WEB-INF/classes/__EJB__TIMER__App.connection][tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-...][timeMillis: ...][levelValue: 800][[
       file:.../aplications/ejb-timer-sersvice-app/WEB-INF/classes/__EJB__Timer__App login successful]]

Is there any way to further diagnose this problem to find a solution or work around?

I have determined that the same issue occurs if I disable all the applications, stop the domain, start the domain, and the enable the applications. It hangs at the first EAR that has an ejb that uses JPA/Eclipselink.

I tried disabling automatic transaction recovery with `transaction-service.automatic-recovery=false` but it had no affect.

I tried to submit this as a question on StackOverflow with the tag Payara as suggested on the http://www.payara.co.uk/home page but a Payara tag does not exist and I do not have high enough reputation to create one.

  [1]: https://java.net/jira/browse/GLASSFISH-21118 "NullPointerException using https"

**Comment by smillidge** [comment] 2015-02-05 20:58
Any chance we can get a stripped down test case. Our patched eclipselink only fixes some schema generation bugs so shouldn't impact startup times. 

Does your application use EJB timers?

A full log trace of the startup would be useful/

**Comment by smillidge** [comment] 2015-02-05 21:09
Similar trace from Payara loading CargoTracker https://cargotracker.java.net/ which uses EJB timers and EclipseLink

[2015-02-05T21:00:05.482+0000] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.org.glassfish.ejb.persistent.timer] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170005482] [levelValue: 800] [[

  Loading EJBTimerService. Please wait.]]

[2015-02-05T21:00:06.481+0000] [Payara 4.1] [INFO] [] [org.eclipse.persistence.session.file:/opt/payara41/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170006481] [levelValue: 800] [[

  EclipseLink, version: Eclipse Persistence Services - 2.5.2.p1]]

[2015-02-05T21:00:06.591+0000] [Payara 4.1] [INFO] [] [org.eclipse.persistence.session.file:/opt/payara41/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App.connection] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170006591] [levelValue: 800] [[

  file:/opt/payara41/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App login successful]]

[2015-02-05T21:00:06.720+0000] [Payara 4.1] [INFO] [AS-EJB-00054] [javax.enterprise.ejb.container] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170006720] [levelValue: 800] [[

  Portable JNDI names for EJB TimerBean: [java:global/ejb-timer-service-app/TimerBean, java:global/ejb-timer-service-app/TimerBean!org.glassfish.ejb.persistent.timer.TimerLocal]]]

[2015-02-05T21:00:06.841+0000] [Payara 4.1] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170006841] [levelValue: 800] [[
  Loading application [ejb-timer-service-app] at [/ejb-timer-service-app]]]

[2015-02-05T21:00:06.863+0000] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.org.glassfish.ejb.persistent.timer] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170006863] [levelValue: 800] [[
  ejb.timer_service_started]]

[2015-02-05T21:00:06.864+0000] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.org.glassfish.ejb.persistent.timer] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170006864] [levelValue: 800] [[
  ==> Restoring Timers ... ]]

[2015-02-05T21:00:06.990+0000] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.org.glassfish.ejb.persistent.timer] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170006990] [levelValue: 800] [[
  There are no EJB Timers owned by this server]]

[2015-02-05T21:00:06.990+0000] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.org.glassfish.ejb.persistent.timer] [tid: _ThreadID=52 _ThreadName=admin-listener(5)] [timeMillis: 1423170006990] [levelValue: 800] [[

  <== ... Timers Restored.]]

**Comment by smillidge** [comment] 2015-02-05 21:14
You could also give us a thread dump when the server log is hanging to see what's going on.

**Comment by bdrx312** [comment] 2015-02-05 21:19
I forgot to post a stack trace of an exception earlier in the startup:

    JTS5043: Unexpected error occurred while creating transaction manager instance
    MultiException stack 1 of 1
    java.lang.IllegalStateException: Circular dependency involving
    org.glassfish.resourcebase.resources.listener.Resourcemanager was found. Full descriptor is SystemDescriptor(
    name=ResourceManager
    contracts={org.glassfish.resourcebase.resources.listener.ResourceManager, org.jvnet.hk2.config.ConfigListener}
    scope=org.glassfish.hk2.runlevel.RunLevel
    qualifiers={}
    descriptorType=CLASS
    descriptorVisiblity=NORMAL
    metadata=runLevelValue={2},runLevelMode={0},Bundle-SymbolicName={org.glassfish.main.resourcebase.resources.nucleus-resources},Bundle-Version={4.1.151}
    rank=0
    loader=OsgiPopulatorPostProcessor.HK2Loader(OSGIModuleImpl::Bundle=
        [org.glassfish.main.resourcebase.resources.nucleus-resources [97]], State = [READY], 1365657050)
    proxiable=null
    proxyForSameScope=null
    analysisName=null
    id=74
    locatorId=0
    identityHashCode=485231397
    reified=true)
    at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:178)
    at RunLevelContext.java:84
    at Utilities.java:2064
    at ServiceHandleImpl.java:105
    at ServiceHandleImpl.java:87
    at ServiceLocatorImpl.java:788
    at TransactionServiceProperties.java:318
    at TransactionManagerImpl.java:209
    at com.sun.jts.jta.TransactionManagerImpl.getTransactionManagerImpl(TransactionManagerImpl.java:177)
    at com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.postConstruct(JavaEETransactionManagerJTSDelegate.java:145)
    at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:329)
    at ClazzCreator.java:377
    at SystemDescriptor.java:471
    ...
    at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServices(ServicesLocatorImpl.java:735)

`com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.postConstruct(JavaEETransactionManagerJTSDelegate.java:145)` is where the fix was to bug 
https://java.net/jira/browse/GLASSFISH-21175 as seen here https://github.com/payara/Payara/commit/11d34855e9e17de708fc8ea5bf434b06f1a0f0d4

So this is most likely related. 
Our EJB does have a timer. We have 2 EARs with timers deployed to the same domain. I cannot provide a test case as the application is on an external network.

**Comment by smillidge** [comment] 2015-02-05 21:45
Looks like early creation of the JTS manager is failing and therefore you are hitting GLASSFISH-21175 as there is a 5 minute timeout to prevent the deadlock. However I am surprised you did not see the hang due to GLASSFISH-21175 with GlassFish 4.1.

Do you also have JCA connectors configured?

**Comment by bdrx312** [comment] 2015-02-05 22:45
I don't believe so. We have an oracle jdbc connector and we have JMS connection resources with a genericra to connect to IBM mq.

**Comment by smillidge** [comment] 2015-02-05 23:19
OK I suspect the IBM mq Resource Adapter is having an impact. We will try to reproduce.

**Comment by bdrx312** [comment] 2015-02-06 03:06
After further research I guess that the genericra is a JCA connector? which means yes we are using one. To clarify we are using the genericra adapter that came bundle with glassfish 2.1 with the necessary IBM mq jars places in the lib directory.

**Comment by davewinters** [comment] 2015-02-06 10:31
Can you take a number of thread dumps on start up along with providing the full server log file. The default deadlock timeout is 2 minutes as a result of the fix for https://java.net/jira/browse/GLASSFISH-21175 however one can override this timeout value in your ejb deployment descriptor. Since https://java.net/jira/browse/GLASSFISH-21175 occurs at startup and you disable transaction automatic recovery at application server start up with no effect, it would seem to point a different issue here as Steve pointed above. If we could view a number of thread dumps taken at 30 second intervals it would be useful.

**Comment by bdrx312** [comment] 2015-02-09 21:46
I disabled the deployed genericra and restarted the domain. The stop and startup time was back to normal which seems to confirm that the genericra is related to the issue.  Of course disabling the genericra cause lots of other errors to be printed in the log due to applications not being able to connect to the JMS queues.

Like I said the domain is on a separate network so I cannot provide a full server log nor thread dumps at this time.  I will try to get the thread dumps exported off the other network, but I am not sure how long that will take or whether I will even be able to get permission to export them.
If you could give me some details on what information is needed or would be helpful, I can hand type it up in the mean time.

Analyzing the thread dumps I notice the following after the first hang

    "RunLevelControllerThread-...." #20 daemon prio=5 os_prio=0 tid=0x.... nid=0x4933 in Object.wait() [0x00007fcc0084b000]
    java.lang.Thread.State: TIMED_WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    at com.sun.jts.CosTransactions.EventSemaphore.waitTimeoutEvent(EventSemaphore.java:156)
    -locked <0x00000000c0ef6320> (a com.sun.jts.CosTransactions.EventSemaphore)
    at com.sun.jts.CosTransactions.RecoveryManager.waitForResync(RecoveryManager.java:1480)
    at com.sun.jts.CosTransactions.TransactionFactoryImpl.localCreate(TransactionFactoryImpl.java:180)
    at com.sun.jts.CosTransactions.CurrentImpl.begin(CurrentImpl.java:428)
    at com.sun.jts.jta.TransactionManagerImpl.begin(TransactionManagerImpl.java:296)
    at com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.beginJTS(JavaEETransactionManagerJTSDelegate.java:499)
    at (JavaEETransactionManagerJTSDelegate.java:400)
    at (JavaEETransactionManagerSimplified.java:429)
    at (JavaEETransactionManagerJTSDelegate.java:319)
    at (JavaEETransactionManagerSimplified.java:356)
    at (SystemResourceManagerImpl.java:103)
    at (PoolManagerImpl.java:211)
    at (ConnectionManagerImpl.java:354)
    at (ConnectionManagerImpl.java:307)
    at (ConnectionManagerImpl.java:196)
    at (ConnectionManagerImpl.java:171)
    at (ConnectionManagerImpl.java:166)
    at (AbstractDataSource:114)
    at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:123)
    at connectToDatasource(DatasourceLogin.java:162)
    at connectInternal(DatasourceAccessor.java:346)
    at (DatasourceAccessor.java:307)
    at (DatasourceAccessor.java:434)
    at (ConnectionPool.java:217)
    at (ExternalconnectionPool.java:146)
    -locked <0x00000000fdba48c0> (a org.eclipse.persistence.sessions.server.ExternalConnectionPool)
    at org.eclipse.persistence.sessions.server.ServerSession.connect(ServerSession.java:493)
    at (DatabaseSessionImpl.java:742)
    at (EntityManagerFactoryProvider.java:239)
    at (EntityManagerSetupImpl.java:685)
    at (EntityManagerFactoryDelegate.java:204)
    -locked <0x00000000fd980cc8> (a org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:304)
    ...
    at com.sun.enterprise.container.common.impl.EntityManagerWrapper._getDelegate(EntityManagerWrapper.java:197)
    at (EntityManagerWrapper.java:521)
    at org.glassfish.ejb.persistence.timer.TimerBean.findTimersByOwnerAndState(TimerBean.java:209)
    at (TimerBean.java:523(
    ...
    at com.sun.proxy.$Proxy262.findActiveTimersOwnedByThisServer(Unknown Source)
    at org.glassfish.ejb.persistence.timer.PersistentEJBTimerService.restoreEJBTimers(PersistentEJBTimerService.java:369)
    at (PersistentEJBTimerService.java:1400)
    at com.sun.ejb.containers.EJBTimerService.initEJBTimerService(EJBTimerService.java:236)
    -locked <0x00000000fd9a69f0> (a java.lang.Class for com.sun.ejb.containers.EJBTimerService)
    at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:205)
   ...
    at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:105)
    -locked <0x00000000c0c2dc60> (a java.lang.Object)
    at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:87)
    at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1223)
    at run(CurrentTaskFuture:1154)
    at runWork(ThreadPoolExecutor.java:1142)
    at run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

    Locked ownable synchronizers:
    - <0x00000000c0eba748> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by bdrx312** [comment] 2015-02-09 21:51
Has Payara been tested with genericra and/or IBM mq? If so which versions; we can try updating our genericra to the latest version 2.1 from here (https://genericjmsra.java.net/) if you think this could resolve the problem.

**Comment by smillidge** [comment] 2015-02-09 22:31
Looks like you are hitting https://java.net/jira/browse/GLASSFISH-21175 again. I thought we'd got rid of it via https://github.com/payara/Payara/issues/10 and https://github.com/payara/Payara/pull/101 

However it looks like it has come back. We can now reproduce this internally so thanks for your help.

You could try messing with your deployment order for the resource adapter as this is a race condition. It looks like our fix to force early creation of the JTA transaction manager is failing with the OSGI problem and then because of that you are hitting GLASSFISH-21175.

**Comment by bdrx312** [comment] 2015-02-10 01:45
Changing the deployment order of the Resource Adapter had no effect. I changed the order to 1 and also 1000 and in both cases still got the OSGI error stack trace. Disabling all the applications, deleting the resource adapter config, stopping and then starting avoids the OSGI issue. Recreating the resource adapter config and then starting all the applications afterwards has startup time as normal.

davewinters mentioned there is an ejb deployment descriptor value to change the default deadlock timeout of 2 minutes. What is the name of the value and what are the implications of changing it?

**Comment by bdrx312** [comment] 2015-02-12 04:17
It turns out that messages to MDBs are also affected and result in each message taking 2 minutes to send.  Also the work around of disabling the applications and deleting the adapter won't work in our case because we also have lifecycle listeners that depend on the applications being enabled.

**Comment by davewinters** [comment] 2015-02-12 10:33
To override the default EJB Container timeout of 2 minutes, one can specify this timeout in the glassfish-ejb-jar.xml in your project(s) for example <cmt-timeout-in-seconds>5</cmt-timeout-in-seconds>

Alternatively, we can change our original fix so that a different timeout parameter is used and which could be configured in the domain.xml. I can go ahead and make this change??

**Comment by davewinters** [comment] 2015-02-12 14:50
I think we should change the waitTimeoutEvent method in EventSemaphore so that rather than waiting for a specific timeout (currently 2 minutes , the default value if not specified in glassfish-ejb-jar.xml) that we check at set intervals say every 2 seconds if the semaphore posted flag has been updated.

**Comment by smillidge** [comment] 2015-02-14 10:56
I agree.

**Comment by davewinters** [comment] 2015-02-20 12:37
Hi could you get a number of thread dumps taken 20 seconds apart  when MDB's are taking apparently 2 minutes to send messages? Also can you send me all the properties you have set on the resource adapter (genericjmsra) . I assume you have configured the resource adapter configuration to use an XA connection factory?

**Comment by bdrx312** [comment] 2015-02-23 21:51
asadmin ${connection_info} deploy genericra.rar
asadmin ${connection_info} create-resource-adapter-config \
   --property ProviderIntegrationMode=jndi:JndiProperties='java.naming.factory.url.pkgs\=com.ibm.mq.jms.naming,java.naming.factory.initial\=com.sun.jndi.fscontext.RefFSContextFactory,java.naming.provider.url\=file\:/ibm/mq/JNDI-Directory':SupportsXA=false \
   genericra

**Comment by davewinters** [comment] 2015-02-26 14:19
Ok I have reproduced this issue whereby I use the generic ra adapter 2.1  to integrate Glassfish with activemq 5.11.0 . Each MDB message takes 2 minutes to be received on Payara. This issue occurs as a result of the proposed fix for GLASSFISH-21175. See full stack trace below. We will investigate and make a fix for this issue.

Relevant Thread in trace::
"p: thread-pool-1; w: 5" daemon prio=6 tid=0x000000000afdb000 nid=0x1854 in Object.wait() [0x0000000011afe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e1e203e8> (a com.sun.jts.CosTransactions.EventSemaphore)
	at com.sun.jts.CosTransactions.EventSemaphore.waitTimeoutEvent(EventSemaphore.java:156)
	- locked <0x00000000e1e203e8> (a com.sun.jts.CosTransactions.EventSemaphore)


Stack Trace:
"p: thread-pool-1; w: 5" daemon prio=6 tid=0x000000000afdb000 nid=0x1854 in Object.wait() [0x0000000011afe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000e1e203e8> (a com.sun.jts.CosTransactions.EventSemaphore)
	at com.sun.jts.CosTransactions.EventSemaphore.waitTimeoutEvent(EventSemaphore.java:156)
	- locked <0x00000000e1e203e8> (a com.sun.jts.CosTransactions.EventSemaphore)
	at com.sun.jts.CosTransactions.RecoveryManager.waitForResync(RecoveryManager.java:1480)
	at com.sun.jts.CosTransactions.TransactionFactoryImpl.localCreate(TransactionFactoryImpl.java:180)
	at com.sun.jts.CosTransactions.CurrentImpl.begin(CurrentImpl.java:428)
	at com.sun.jts.jta.TransactionManagerImpl.begin(TransactionManagerImpl.java:296)
	at com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.beginJTS(JavaEETransactionManagerJTSDelegate.java:499)
	at com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.startJTSTx(JavaEETransactionManagerJTSDelegate.java:400)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.startJTSTx(JavaEETransactionManagerSimplified.java:429)
	at com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.enlistLAOResource(JavaEETransactionManagerJTSDelegate.java:319)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.enlistResource(JavaEETransactionManagerSimplified.java:356)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.enlistComponentResources(JavaEETransactionManagerSimplified.java:1339)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.enlistComponentResources(JavaEETransactionManagerSimplified.java:501)
	at com.sun.ejb.containers.EJBContainerTransactionManager.startNewTx(EJBContainerTransactionManager.java:314)
	at com.sun.ejb.containers.EJBContainerTransactionManager.preInvokeTx(EJBContainerTransactionManager.java:250)
	at com.sun.ejb.containers.BaseContainer.preInvokeTx(BaseContainer.java:4524)
	at org.glassfish.ejb.mdb.MessageBeanContainer.beforeMessageDelivery(MessageBeanContainer.java:1164)
	at org.glassfish.ejb.mdb.MessageBeanListenerImpl.beforeMessageDelivery(MessageBeanListenerImpl.java:77)
	at com.sun.enterprise.connectors.inbound.MessageEndpointInvocationHandler.invoke(MessageEndpointInvocationHandler.java:139)
	at com.sun.proxy.$Proxy314.beforeDelivery(Unknown Source)
	at com.sun.genericra.inbound.async.InboundJmsResource.refresh(InboundJmsResource.java:142)
	at com.sun.genericra.inbound.async.WorkImpl.run(WorkImpl.java:49)
	at com.sun.enterprise.connectors.work.OneWork.doWork(OneWork.java:107)
	at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:497)
	at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:540)

   Locked ownable synchronizers:
	- None

**Comment by davewinters** [comment] 2015-02-26 14:45
I tested overriding the cmt transaction timeout in the MDB project glassfish-ejb-jar.xml  and as expected it overrides the default timeout set in code of 2 minutes. See example below whereby I set the cmt timeout to 2 seconds for the MDB in my test project. Messages are now processed every 2 seconds by the MBD listener.

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE glassfish-ejb-jar PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 EJB 3.1//EN" "http://glassfish.org/dtds/glassfish-ejb-jar_3_1-1.dtd">
<glassfish-ejb-jar>
    <enterprise-beans>
        <ejb>
           
            <ejb-name>ExampleMessageBean</ejb-name>
            <cmt-timeout-in-seconds>2</cmt-timeout-in-seconds>
            <mdb-resource-adapter>
                <resource-adapter-mid>genericra</resource-adapter-mid>
            </mdb-resource-adapter>
        </ejb>
        
    </enterprise-beans>
    
</glassfish-ejb-jar>

**Comment by smillidge** [comment] 2015-02-26 18:30
Can you try the latest pre-release build to see if this goes away http://www.payara.co/upstream_builds

**Comment by bdrx312** [comment] 2015-02-27 16:27
Confirmed fixed.

**Comment by smillidge** [comment] 2015-02-27 19:39
Thanks

**Closed by smillidge** 2015-02-27 19:39 UTC
Labels: payara bug, reproducible
