### ISSUE TITLE
Class delegate over EAR issue

### ISSUE THREAD

**Issue by rds76** [payara/Payara#1249] opened 2016-12-20 10:15 UTC
# Description #
----------
Created application with apache-cxf WS libraries works just fine but only when packed into WAR with option  `<class-loader delegate="false" />` in glassfish-web.xml 
Moving app into EAR even with option` <classloading-delegate>false</classloading-delegate> `in glassfish-application.xml I'm getting class cast exception. When completly remove all jax-ws Metro libs from Payara/modules (webservices*.jar files) it works as expected.

I would expect same behaviour with option class delegate = false for both EAR or WAR as documented and followed here: https://payara.gitbooks.io/payara-server/content/documentation/extended-documentation/classloading.html

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**:  OpenJDK Runtime Environment (build 1.8.0_111-b15)
- **Operating System**: Linux

**Comment by rds76** [comment] 2016-12-20 14:38
Can confirm as mentioned here: http://stackoverflow.com/questions/38570837/how-to-activate-payara-class-loading-parameter-fish-payara-classloading-delegate
I'm not able to set class delegate as global option, tried everything and only setting on glassfish-web.xml turn off load classes from Payara libs instead of WAR

**Comment by lprimak** [comment] 2016-12-20 16:49
Can you post a link to a simple project so we can reproduce this issue?
Thanks

**Comment by rds76** [comment] 2016-12-20 19:46
Unfortunately do not have any simple project.
But make a simple war which uses any lib from paraya and include it to web-inf/lib folder. Deploy war and check classloader from where it picks jar. 
I'm not able to let classloader to priority pick custom jar from war lib folder with system option `fish.payara.classloading.delegate=false` as documented above. Or is there anything else what needs to be enabled to make it works?

**Comment by lprimak** [comment] 2016-12-21 05:01
@rds76 Can you please create that simple project that demonstrates the problem?
I would be happy to take a look.  I developed the classloading option and have tested it previously and I found it working as designed in my projects.

**Comment by lprimak** [comment] 2016-12-21 05:06
The only thing I can think of is that when other parts of Payara are using WS libraries even before your app is loaded, and therefore cannot be overridden when you app gets loaded afterwards

**Comment by rds76** [comment] 2016-12-21 07:28
What do you think other parts of Payara? IMHO it doesnt make sense
1) class loader is isolated withing application and those option delagate=false should avoid to pass class loading to its parent classloader before try to load class itself
2) how can you explain it works setting delagate=false in web.xml? But it doesnt work setting delegate to false in system property? Check this [link I already mention](http://stackoverflow.com/questions/38570837/how-to-activate-payara-class-loading-parameter-fish-payara-classloading-delegate), dude has the same issue as this system option does not work

**Comment by rds76** [comment] 2016-12-21 08:08
Ok, I made simple WAR which uses Guava lib and Joiner class:
#### 1)
 Payara system property `fish.payara.classloading.delegate = false `
`<!-- <class-loader delegate="false" /> -->` in glassfish-web.xml
Class loader: 
```
[Loaded com.google.common.base.Joiner from file:/opt/payara/164/payara41/glassfish/modules/guava.jar]
```
#### 2)
Payara  system property `fish.payara.classloading.delegate = false `
`<class-loader delegate="false" />` in glassfish-web.xml
Class loader: 
```
[Loaded com.google.common.base.Joiner from file:/opt/payara/164/payara41/glassfish/domains/payaradomain/applications/WebApplicationTest/WEB-INF/lib/guava-19.0.jar]
```

**Comment by lprimak** [comment] 2016-12-21 18:50
Ah, I see where the confusion lies.

For WAR files, ```<class-loader delegate="false" />``` is the only way to disable delegation.
```fish.payara.classloading.delegate``` option only controls whether ```<domain_dir>/lib``` overrides Payara modules/ directory or not.  It does not override application-specific settings.
We have to keep WAR class loading delegation true by default so Payara is a drop-in replacement for GlassFish

**Comment by rds76** [comment] 2016-12-21 19:04
Btw, documentation 4.1 is quite confusing then 

> This way, any library that is included by the application developer will override the one that's included in Payara.

And it still doesn't work packing that war into EAR as mentioned in my 1st post. Can you check this?

**Comment by lprimak** [comment] 2016-12-21 19:14
I agree, we will improve this documentation.

I will be happy to check the EAR problem, but I do need a reproducer application.
I have tested this using Guava as a test case, and it works as designed.

**Comment by lprimak** [comment] 2016-12-21 19:16
We are trying to walk a fine line here to keep things compatible as a drop-in replacement, and add useful functionality, and in this admittedly complicated case, it'll take some time to sort out all the details.

**Comment by rds76** [comment] 2016-12-21 19:39
I will prepare some test EAR a and make additional tests tomorrow.
I need to get same functionality as WAR app but needs to be part on one single EAR app, but have been unsuccessful with class loading so far.

**Comment by lprimak** [comment] 2016-12-21 20:14
Thanks, @rds76, I will take a look when you have a test application.

There are a few inconsistencies in GlassFish (and hence Payara) between WAR and EAR deployments, so maybe there was something else overlooked.

There is some caution because Java EE spec specifically disallows overriding implementations of Java EE APIs (javax.*) so you may be hitting that.
Perhaps WAR classloading delegation erroneously allows core overrides.

Looking forward to your test app.
Thanks!

**Comment by rds76** [comment] 2016-12-22 14:07
I made deeper testing and class delegation works as documented in Payara. The problem here caused (javax.*) package as you mentioned. Really weird that is working for WARs even this is mentioned as exception in [Oracle doc](https://docs.oracle.com/cd/E18930_01/html/821-2418/gfqpi.html).
Troubles here made `javax.xml.ws.spi.Provider` (this starting with _javax_) which is responsible for choosing implemetation for WS. Finaly I changed my code to use apache-cxf-ws factory `org.apache.cxf.jaxws.JaxWsProxyFactoryBean` to create WS stubs instead of standard [WS Provider](https://docs.oracle.com/javase/7/docs/api/javax/xml/ws/spi/Provider.html). Now I'm able to create WS client based on apache-cxf implemetation inside Payara JEE container with (default java Metro `com.sun.xml.ws` ) packed into EAR.
Btw, more info could be found [here](http://stackoverflow.com/questions/6364333/jax-ws-when-apache-cxf-is-installed-it-steals-default-jdk-jax-ws-implementat)

**Thanks for help a wish you all mery xmass!**

**Comment by lprimak** [comment] 2016-12-22 19:45
@rds76 Does this satisfy this issue?
Please close it if it does.

Thanks!

**Closed** 2016-12-23 16:53 UTC
Labels: 1:Investigating, c:PossibleBug, Test Case Required

**Comment by janArb** [comment] 2017-02-22 09:37
I don't get the idea why Payara needs to be a 100% drop in replacement for Glassfish, because if you want Glassfish then you can use it directly. But if people want something better, then they will take Payara. But even if that design choice will not be changed, I would like to reopen this issue. We still have old Glassfish3 installations and need to support them for some time. If we use the parameter for delegation in the glassfish-web.xml the release cannot be deployed to Glassfish3 anymore. We really would need at least a new configuration parameter like fish.payara.classloading.delegate=false to work globally also for WARs. If that property cannot be used (I still don't understand why this does not work for WARs), why not add a new property fish.payara.classloading.wars.delegate=false and behave like setting that in the glassfish-web.xml?

**Comment by lprimak** [comment] 2017-02-23 19:58
@janArb Are you sure it doesn't work for WARs?
I believe absent of the glassfish-web.xml statement, fish.payara.classloading variable should still work as described.  Of course glassfish-web.xml would override that.

Also, the reason for drop-in replacement is to have as easy migration path from GlassFish as possible.

**Comment by janArb** [comment] 2017-06-15 13:15
@lprimak I found no way to get that running via the system property in domain.xml for WARs, i.e. that the libraries from the WAR are used first. I saw that the payaradomain/config/domain.xml also contains the system property now and would love to have that applied to WARs, too. Currently we have to maintain two different build processes because of that (see details in my comment above).

**Comment by lprimak** [comment] 2017-06-15 18:04
@janArb This is a closed issue.
If you would like us to look at something:
- Open a new issue
- Attach a simple self-contained example of the problem (http://sscce.org)
then we can take a look.

Thank you!
