### ISSUE TITLE
OpenAPI endpoint tracing / FISH-777

### ISSUE THREAD

**Issue by avpinchuk** [payara/Payara#4921] opened 2020-09-29 08:19 UTC
# Description #
----------

Payara does not exclude /openapi endpoint from tracing.

## Expected Outcome

According to subsection "Disabling server tracing" section 3.1.3 of Microprofile Opentracing 1.3 specification they always excluded from tracing.

- **Payara Version**: 5.2020.4
- **Edition**: Micro
- **JDK Version**: OpenJDK 11
- **Operating System**: Windows 10

**Comment by AlanRoth** [comment] 2020-11-16 13:03
Hi @avpinchuk can you please provide a simple to follow scenario how to reproduce this on the latest release of Payara Community Edition? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by avpinchuk** [comment] 2020-11-23 11:53
Hi, this should be an app example?

**Comment by AlanRoth** [comment] 2020-11-23 12:16
Hi @avpinchuk, an app or just clear steps on how I can reproduce the same error you are experiencing are fine.

**Comment by avpinchuk** [comment] 2020-11-23 13:31
1. Application at https://github.com/avpinchuk/issue4921.git
2. Go to http://localhost:8080/openapi
3. In console we see the log entry for reported span. If Jaeger backend started the span reported to him

I also sent PR https://github.com/payara/Payara/pull/4923#issue-495336729

**Comment by AlanRoth** [comment] 2020-11-23 14:43
Hi @avpinchuk, since you have created a PR, we will automatically accept the issue. Apologies about the confusion. An internal issue should have been created when you raised the PR. I have now created an internal issue `FISH-777` to track this. Thank you.

**Comment by AlanRoth** [comment] 2020-11-25 11:52
Hi, PR #4923 has been merged, I'll be closing this issue.

**Closed by AlanRoth** 2020-11-25 11:52 UTC
Labels: Status: Accepted, Type: Bug
