### ISSUE TITLE
Not possible to specify the schema for EJB__TIMER__TBL

### ISSUE THREAD

**Issue by tivanacc** [payara/Payara#3078] opened 2018-08-22 14:36 UTC
# Not possible to specify the schema for EJB__TIMER__TBL (?) #
----------

## Expected Outcome

It should be possible to specify in which schema Payara creates its `EJB__TIMER__TBL` table to store persistent timer state.

## Current Outcome

Currently there seems to be no option to set the schema in which Payara creates the `EJB__TIMER_TBL` table.

## Steps to reproduce (Only for bug reports) 

Our project is a legacy Java EE application, currently being migrated from Glassfish 3 to Payara Server  4.1.2.182.1 #badassfish (build 308).
The application uses multiple data sources and several (persistent) timers, therefore Payara creates the EJB__TIMER__TBL in the specified timer-datasource: `config.server-config.ejb-container.ejb-timer-service.timer-datasource`, which is fine.
 ` <ejb-timer-service timer-datasource="jdbc/abc"></ejb-timer-service>`
The timer data source is a PostgreSQL 9.6 database and the EJB__TIMER__TBL gets created in the 'public' schema, which is not OK.
We tried to create the EJB__TIMER__TBL explicitly in the desired schema (e.g. `appschema`). Did not help, the table is still created (also) in schema 'public' (and we suppose the application uses that table).
The application uses Hibernate (4.3.11.Final) as persistence provider / entity manager, and the schema to be used is specified with the `<property name="hibernate.default_schema" value="appschema"/>` persistence-unit property in persistence.xml.

Note: GMS is enabled for the application.

Please let us know how the schema can be specified for Payara to create EJB__TIMER__TBL in.
If creation of the EJB__TIMER__TBL table can be avoided (and persistent timer states can be stored differently), then please also let us know.

## Environment ##

- **Payara Version**: 4.1.2.182.1 #badassfish (build 308)
- **Edition**: Full
- **JDK Version**: OpenJDK Runtime Environment (Zulu 8.31.0.2-linux64) (build 1.8.0_181-b02)
- **Operating System**: Linux
- **Database**: PostGres 9.6

**Comment by smillidge** [comment] 2018-09-02 20:13
This is a duplicate of #1418

**Closed by smillidge** 2018-09-02 20:13 UTC
Labels: c:Enhancement
