### ISSUE TITLE
The exception: "java.lang.IllegalArgumentException: PWC2788: setAttribute: Non-serializable attribute" will occur when a web-fragment.xml with <distributable/> is found

### ISSUE THREAD

**Issue by kjjaeger** [payara/Payara#688] opened 2016-03-03 00:45 UTC
If you are using Spring web classes starting with version 3.2.2 and higher on any version of Glassfish or Payara, you will run into issues on deployment saying that every class in the session must be serializable.  There is a lot of information on this here: https://jira.spring.io/browse/SPR-11389 and I would agree this does not really appear to be a Spring framework bug, as it can occur with other libraries such as ZK.  The workaround of placing an empty "absolute-ordering" tag in a web application's web.xml did work for me, but I feel this is a hack and something I should not rely on long term.  There is also an unresolved Glassfish bug for this here: https://java.net/jira/browse/GLASSFISH-20917 in which at least one member of the Glassfish team seems to be pushing back on this as a "specification" issue, but that is not helpful at all.  I hope the Payara team can come up with a reasonable alternative to handling "distributable" in web-fragment.xml files.

**Comment by smillidge** [comment] 2016-03-03 17:40
Do you have a simple app that demonstrates the problem?

**Comment by kjjaeger** [comment] 2016-03-03 20:43
Create a simple web application with this for the index.jsp

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello GlassFish Bug!</h1>
        <%
            session.setAttribute("test", new java.io.ByteArrayOutputStream(20));
        %>
    </body>
</html>

and include this dependency in the pom.xml

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>4.2.4.RELEASE</version>
        </dependency>

and you will see this:

Warning:   StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
java.lang.IllegalArgumentException: setAttribute: Non-serializable attribute with name test
	at org.apache.catalina.session.ManagerBase.checkSessionAttribute(ManagerBase.java:835)
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1841)
	at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:178)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:57)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kjjaeger** [comment] 2016-03-03 20:45
How do I turn off this Markdown thing?

**Comment by kjjaeger** [comment] 2016-03-03 20:53
The previous JSP will also cause the issue if you include a zk core dependency like this:

        <dependency>
            <groupId>org.zkoss.zk</groupId>
            <artifactId>zk</artifactId>
            <version>8.0.1.1</version>
        </dependency>

And pretty much any library that contains web-fragment.xml with distributable set to true

**Comment by kjjaeger** [comment] 2016-03-04 15:46
I am attaching a war file here.  I had to rename it .zip to allow it to be attached.
[BreakGlassFish1-1.0.zip](https://github.com/payara/Payara/files/158948/BreakGlassFish1-1.0.zip)

**Comment by smillidge** [comment] 2016-03-05 23:52
Thanks for the test case we will try to reproduce

**Comment by lprimak** [comment] 2016-04-28 15:33
Kenneth, it is indeed in the spec that all session properties have to be serializable,
but I agree with you that it is not helpful, and should be fixed.
I also think that the workaround mentioned above should work without sideffects.
For someone who came up against problem such as this again and again, I feel your pain.
This hit me especially hard when only discovering in production, because that environment is clustered, but the development environment is not.

**Comment by lprimak** [comment] 2016-04-28 15:42
I can already see some issues...
How can this be implemented in a generic way for non-serializable object?
- Should they be ignored?
- Should they be ignored with a warning?
- Should certain non-serializable types be explicitly supported, such as ByteBuffer?

**Comment by kjjaeger** [comment] 2016-04-29 00:08
I would think the more reasonable behavior would be that an error be thrown only when a web application is deployed on a Payara cluster, and only generate a warning if Payara is not clustered.  Another option would be to provide a configuration flag to turn off that check for serializable.  I am uncertain how feasible any of this is.

Also, it may be worth investigating what TomEE and Wildfly are doing for web-fragments marked distributable.  I know they are definitely not doing the same thing as Glassfish/Payara.  If they are ignoring the specification, maybe emulating that behavior is not the best idea, but perhaps they are interpreting the specification differently.

Thanks for looking into this.

**Comment by lprimak** [comment] 2016-04-29 01:14
I would say the easiest way would be to ignore `<distributable/>` in web fragments, and only listen to that directive in the main web.xml file, but what needs to be investigated is how compliant with the spec this is.  It's a good idea to find out how TomEE or Wildly do it as an example.
Also, in Payara, cluster isn't as clear cut as it is in GlassFish, as Payara supports Hazelcast clustering with standalone instances, for example. This is an amazing feature BTW

**Comment by ggam** [comment] 2016-04-30 06:51
The Servlet spec says (section 8.2.3): 
> The web.xml resulting from the merge is considered <distributable> only if all its web fragments are marked as <distributable> as well.

So if the web.xml is not marked distributable, it should be automatically ignored from the fragments

**Comment by lprimak** [comment] 2016-05-01 03:53
So it looks like something wasn't properly implemented in GlassFish, and can probably be fixed in Payara

**Comment by smillidge** [comment] 2016-05-21 07:15
Internal defect number PAYARA-799

**Comment by lprimak** [comment] 2016-05-23 19:48
Should be fixed now

**Comment by smillidge** [comment] 2016-06-12 10:12
Fixed by #834

**Closed by smillidge** 2016-06-12 10:12 UTC
Labels: 2:Defect, c:ConfirmedBug, reproducible, upstream bug
