### ISSUE TITLE
Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener

### ISSUE THREAD

**Issue by ahamana** [payara/Payara#2332] opened 2018-01-28 11:40 UTC
# Description #
----------

When server start up withe Payara 5, the error that "Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener" occurs.

## Expected Outcome

Server start up without fail.

## Current Outcome

\* I think the cause of this error relates with [this stackoverflow](https://stackoverflow.com/questions/48235803/error-creating-managed-object-for-class-class-org-jboss-weld-module-web-servle).
\* Both of the delegate options(true/false) of glassfish-web.xml, this error occurs.
\* If there are any ideas to resolve this error, please let me know.

[2018-01-28T19:54:06.756+0900] [Payara 5..Beta2] [警告] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=58 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1517136846756] [levelValue: 900] [[
  Exception while dispatching an event
org.glassfish.api.invocation.InvocationException
	at org.glassfish.api.invocation.InvocationManagerImpl.postInvoke(InvocationManagerImpl.java:178)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:293)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:333)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:494)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:512)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:564)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:251)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:190)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:242)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
]]

[2018-01-28T19:54:07.318+0900] [Payara 5..Beta2] [重大] [AS-WEB-CORE-00108] [javax.enterprise.web.core] [tid: _ThreadID=58 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1517136847318] [levelValue: 1000] [[
  ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: java.lang.IllegalArgumentException: javax.servlet.ServletException: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5688)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:609)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2099)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1745)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:537)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:514)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:564)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:251)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:190)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:242)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: javax.servlet.ServletException: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
	at org.apache.catalina.core.StandardContext.addListener(StandardContext.java:3005)
	at org.apache.catalina.core.StandardContext.addApplicationListener(StandardContext.java:2200)
	at com.sun.enterprise.web.TomcatDeploymentConfig.configureApplicationListener(TomcatDeploymentConfig.java:236)
	at com.sun.enterprise.web.TomcatDeploymentConfig.configureWebModule(TomcatDeploymentConfig.java:95)
	at com.sun.enterprise.web.WebModuleContextConfig.start(WebModuleContextConfig.java:239)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:336)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:163)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5685)
	... 48 more
Caused by: javax.servlet.ServletException: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
	at org.apache.catalina.core.StandardContext.createListener(StandardContext.java:3126)
	at org.apache.catalina.core.StandardContext.loadListener(StandardContext.java:5208)
	at com.sun.enterprise.web.WebModule.loadListener(WebModule.java:1709)
	at org.apache.catalina.core.StandardContext.addListener(StandardContext.java:3003)
	... 55 more
Caused by: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.createManagedObject(InjectionManagerImpl.java:298)
	at com.sun.enterprise.web.WebContainer.createListenerInstance(WebContainer.java:808)
	at com.sun.enterprise.web.WebModule.createListenerInstance(WebModule.java:2079)
	at org.apache.catalina.core.StandardContext.createListener(StandardContext.java:3124)
	... 58 more
Caused by: java.lang.NullPointerException
	at org.glassfish.weld.services.JCDIServiceImpl.createManagedObject(JCDIServiceImpl.java:458)
	at org.glassfish.weld.services.JCDIServiceImpl.createManagedObject(JCDIServiceImpl.java:314)
	at com.sun.enterprise.container.common.impl.managedbean.ManagedBeanManagerImpl.createManagedBean(ManagedBeanManagerImpl.java:476)
	at com.sun.enterprise.container.common.impl.managedbean.ManagedBeanManagerImpl.createManagedBean(ManagedBeanManagerImpl.java:429)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.createManagedObject(InjectionManagerImpl.java:283)
	... 61 more
]]

## Steps to reproduce (Only for bug reports) 
My application works fine with Payara 4.1.2.174.
I modified my application with Java EE 8 specifications.
\* My application doesn't use JPA, so only modified JSF from 2.2 to 2.3 and upgraded OmniFaces from 2.6.8 to 3.0.
\* I don't use the <code>@ManagedBean</code> annotation.
I replaced Payara from 4.1.2.174 to Beta 2/Beta1 and then ran my application from Eclipse.
\* I have not checked with Payara 5 Alpha.

## Environment ##

- **Payara Version**: 5 Beta 2
- **Edition**: Full
- **JDK Version**: 8 u162 - Oracle
- **Operating System**: Windows 10
- **Database**: MySQL

**Comment by fxrobin** [comment] 2018-03-01 14:10
I confirm that I have the same issue with payara 5 Beta 2

**Comment by ahamana** [comment] 2018-03-09 07:27
In case of my application, I think the cause of this issue relates with the follwing Weld issues.
\- I encounterd an issue like this issue when I upgraded the version of Paraya 4, 174 to 181.
\- the Weld 2.4.6/3.0.3 has these issues.
https://issues.jboss.org/browse/WELD-2442
https://issues.jboss.org/browse/WELD-2470

So, I will try confirming again when Payara 5 uses Weld 3.0.4 or later.

**Comment by OndrejM** [comment] 2018-04-06 23:12
The application can't be deployed due to incorrect setup in your application. It may be incorrect setup of  dependency injection, persistence.xml or any other component validated during deployment. 

The problem is that the InvocationException throw from a finally block masks the original DeploymentException, which is ignored instead of being logged due to a bug in Payara Server. The only way to find out what's the original exception is to debug Payara Server and read the information about the problem from the DeploymentException in a debugger.

Put a breakpoint on [this line in WeldDeployer.java](https://github.com/payara/Payara/blob/payara-server-5.181/appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java#L522). This line throws the InvocationException which hides the DeploymentException thrown one line above.

This problem was brought by this commit into Payara 5: https://github.com/payara/Payara/commit/1238c9eecb09415a285ba37ef567e5d73fbaeeab#diff-990a2b98ed05fe9def6b93056a756f50R522

A simple solution is to put the line causing the InvocationException into a try catch block and handle the exception. Finally blocks should throw no exceptions otherwise they hide the exception thrown by the try or catch blocks.

**Comment by mikecroft** [comment] 2018-04-23 10:45
Fixed by the referenced PR

**Closed by mikecroft** 2018-04-23 10:45 UTC
Labels: 1:Wait, upstream bug, v:Payara-5

**Comment by ahamana** [comment] 2018-05-12 12:37
I have tried running my application with Payara 5 uses Weld 3.0.4 and confirmed my application worked fine.
* It is the current pre-release Build.
Thanks for upgrading Weld.
