### ISSUE TITLE
Enhancement: Cpu usage of admin interface

### ISSUE THREAD

**Issue by bh-tt** [payara/Payara#5949] opened 2022-09-20 13:56 UTC
# Description #
----------
I was testing the performance of some applications using Java Flight Recordings and found that even when very busy, about 20-30% of cpu usage of a running instance consists of resolving the Json Provider. Theses calls all seem to come from the admin REST interface, which apparently uses the static Json methods to write responses instead of resolving the provider once and caching it.

## Expected Outcome
The admin interface should resolve the json provider only once, preferably once per boot but once per request might be okay too(to preserve the option for a provider switch without reboot)

## Current Outcome
The admin interface resolves the json provider once or more for each admin request. This is detrimental to performance.

## Context
I've been using Java Flight Recordings on many of my organisations applications (mostly java SE) and can often find several locations for easy improvement which can reduce cpu usage by 20-50%. I was surprised Payara has hotspots like these as well.

Using payara community 5.2022.2

**Comment by JamesHillyard** [comment] 2022-09-20 14:01
Hi @bh-tt,

Thank you for requesting this enhancement, I would be interested in seeing the flight recordings for myself and also to help us verify a future fix has infact improved performance. Could you please provide a simple to follow reproducer which would allow me to easily identify this performance issue? It will greatly help us understand the scope of this issue and measure our future implementation, should the community vote this as an issue they would like to see implemented.

Thanks,
James

**Comment by bh-tt** [comment] 2022-09-20 14:02
I'll see if I can strip the credentials from the flight recording and upload it, together with the server config.

**Comment by bh-tt** [comment] 2022-09-20 15:02
It appears my company has an extra war deployed with most applications which returns all metrics, exposing one endpoint that does dozens if not hundreds of requests to the admin interface (for every method of every bean of every deployed application) to gather all of those metrics. This is why I have so many requests going to the admin interface. 

Creating a provider-independent fix for this is likely hard as well, see https://github.com/payara/Payara/blob/master/nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/JsonUtil.java. Part of the calls can be prevented by creating a JsonBuilderFactory, and using that to create JsonObjectBuilder and JsonArrayBuilder instances, but all of the `Json.createValue` calls with primitives, Strings and such cannot be replaced in that way. That appears to be a gap in the javax.json-api library. You might be able to do something with custom adapters for enums, InternetAddress, RestModel and other special cases and leave the rest to the implementation, but that seems like a lot of work for little gain except in very specific circumstances.

I'll leave it to you to decide whether to actually accept this issue, the impact of changing that is likely negligible unless you do a lot of requests to the admin API. If you still want the recording I'll upload it, if not feel free to close this.

**Comment by JamesHillyard** [comment] 2022-09-20 15:34
Hi @bh-tt,

Thank you for your prompt reply, in that case if you feel confident to do so you can raise a PR to implement this enhancement and our development team will gladly review it. Otherwise, we will close this issue due to us not being able to easily benchmark the enhancement to verify a fix.

We hope you understand.
Best Regards,
James

**Closed** 2022-09-21 07:14 UTC
Labels: Type: Enhancement, Status: Pending
