### ISSUE TITLE
wrong redirect of webservice endpoint to https

### ISSUE THREAD

**Issue by rds76** [payara/Payara#1117] opened 2016-10-02 12:04 UTC
**Payara v163**
web service EJB configured with: `<transport-guarantee>CONFIDENTIAL</transport-guarantee>`
original endpoint url: http://my.domain.com/ws/b2b

Got error:
```
 Internal Server error: /ws/https:/my.domain.com:443/ws/b2b
 java.io.CharConversionException: Encoded slashes are not allowed
```

**Comment by rds76** [comment] 2016-10-04 07:55
Possible found source of the issue: https://github.com/payara/Payara/blob/master/appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/EjbWebServiceServlet.java#L138

and another with wrong  WARNING message:
> [2016-10-04T09:29:29.589+0200] [Payara 4.1] [WARNING] [AS-WSJSR109IMPL-00076] [javax.enterprise.webservices] [tid: _ThreadID=23 _ThreadName=http-thread-pool(1)] [timeMillis: 1475566169589] [[  Invalid request scheme for Endpoint MyWS. Expected {1}, received {2}.]]

https://github.com/payara/Payara/blob/master/appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/LogUtils.java#L289

Regarding https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html params must be escaped with double single quotes

**Comment by mikecroft** [comment] 2016-10-04 08:31
I think you need to change your use of URLEncoder to [HttpServletResponse.encodeRedirectURL()](https://tomcat.apache.org/tomcat-8.0-doc/servletapi/javax/servlet/http/HttpServletResponse.html#encodeRedirectURL(java.lang.String)). I'm not an expert, but it looks like `URLEncoder` is not for encoding URLs, but for encoding Strings in the `application/x-www-form-urlencoded` MIME type

**Comment by rds76** [comment] 2016-10-04 09:05
I went a bit further with some tcpdump, this is what server replies:
```
HTTP/1.1 302 Found
Server: Payara Server  4.1.1.163 #badassfish
X-Powered-By: Servlet/3.1 JSP/2.3 (Payara Server  4.1.1.163 #badassfish Java/Oracle Corporation/1.7)
Server: grizzly/2.3.25
Location: http://my.domain.com/ws/https%3A%2F%2Fmy.domain.com%3A443%2Fws%2Fb2b
Content-Language: en-US
Content-Type: text/html;charset=ISO-8859-1
Date: Tue, 04 Oct 2016 08:53:32 GMT
Transfer-Encoding: chunked
```
with urldecoded Location: `http://my.domain.com/ws/https://my.domain.com:443/ws/b2b`
IMHO server is returning wrong url. I would expect: `https://my.domain.com:443/ws/b2b`

**Comment by mikecroft** [comment] 2016-10-04 09:12
Have you changed your use of `URLEncoder`? From what I've found, that is only to be used to encode, e.g. the ***path*** of a URL, hence your location. [See this SO answer](http://stackoverflow.com/a/10786112/212224).

`java.net.URLEncoder` is a Java SE class and not provided by Payara, so this would not be an issue with Payara Server.

**Comment by rds76** [comment] 2016-10-04 09:22
There is no issue in urlencode, the issue is: **Payara returns wrong redirect Location**.
Tried also to open wsdl in Chrome browser and it redirect me to: `http://my.domain.com/ws/https%3A%2F%2Fmy.domain.com%3A443%2Fws%2Fb2b` instead of `https%3A%2F%2Fmy.domain.com%3A443%2Fws%2Fb2b`

**Comment by mikecroft** [comment] 2016-10-04 09:29
Sorry, my mistake, I misunderstood your update. Can you share the source of *your* code that's giving the incorrect location? We need to be able to reproduce it independently to work on a fix.

**Comment by rds76** [comment] 2016-10-04 09:44
Actually create any simple EJB webservice with config file `glassfish-ejb-jar` and secure it with **CONFIDENTIAL** token
call any ws method or simply open WSDL: urlendpoint?wsdl

_glassfish-ejb-jar:_
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-ejb-jar PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 EJB 3.1//EN" "http://glassfish.org/dtds/glassfish-ejb-jar_3_1-1.dtd">
<glassfish-ejb-jar>
  <enterprise-beans>
    <ejb>
      <ejb-name>MyWS</ejb-name>
      <webservice-endpoint>
        <transport-guarantee>CONFIDENTIAL</transport-guarantee>
      </webservice-endpoint>      
    </ejb>
  </enterprise-beans>
</glassfish-ejb-jar>
```

Btw, Glassfish v3.1.2 does not redirect at all, it just returns empty response with HTTP/1.1 200 OK  and  message in log
```
[#|2016-10-04T11:38:21.786+0200|WARNING|glassfish3.1.2|javax.enterprise.webservices.org.glassfish.webservices|_ThreadID=58;_ThreadName=Thread-2;|Invalid request scheme for Endpoint MyWS. Expected https . Received http|#]
```
But thats a differnet story...

**Comment by rds76** [comment] 2016-10-04 20:56
## Fix:
Src: [EjbWebServiceServlet.java](https://github.com/payara/Payara/blob/master/appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/EjbWebServiceServlet.java#L138)
worng: `hresp.sendRedirect(URLEncoder.encode(sb.toString(), "UTF-8"));` 
**correct:** `hresp.sendRedirect(hresp.encodeRedirectURL(sb.toString());`

using java.net.URLEncoder is not correctly handled by HttpServletResponse.sendRedirect method, regarding [doc](http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html#encodeRedirectURL(java.lang.String)), encodeRedirectURL should be used.

**Tested on 164-SNAPSHOT, works like a charm.**

**Comment by smillidge** [comment] 2016-10-06 21:14
I can confirm this from the description. Internal bug ID is PAYARA-1104

**Comment by smillidge** [comment] 2016-10-06 21:25
I can confirm the suggested fix also works. This will be in Payara 164

**Closed** 2016-10-08 16:49 UTC
Labels: 3:DevInProgress, c:ConfirmedBug
