### ISSUE TITLE
asadmin ignores --name on deploy of applications

### ISSUE THREAD

**Issue by md-mg** [payara/Payara#2900] opened 2018-06-26 12:24 UTC
# Description #
----------

when deploying applications on payarafish 5.182 with asadmin the --name-parameter is ignored.
`/usr/local/payara5/bin/asadmin deploy --force=true --name=poi-api-ear /tmp/poi-api-ear-release-4.0.15-SNAPSHOT.ear`
`Application deployed with name poi-api-ear-release-4.0.15-SNAPSHOT.`
`Command deploy executed successfully.`
`./asadmin deploy --type rar --name activemq-rar /root/software/activemq-rar-5.15.`
`Application deployed with name activemq-rar-5.15.4.`

`./asadmin list-applications`
`poi-api-ear-release-4.0.15-SNAPSHOT  <ear, web, ejb>`
`activemq-rar-5.15.4                  <connector>`
`Command list-applications executed successfully.`

## Expected Outcome
**On payarafish 4.1.2-181:**
`./asadmin list-applications`
`poi-api-ear <ear, web, ejb>`
`activemq-rar <connector>`
`Command list-applications executed successfully.`

## Current Outcome
`./asadmin list-applications`
`poi-api-ear-release-4.0.15-SNAPSHOT  <ear, web, ejb>`
`activemq-rar-5.15.4 <connector>`
`Command list-applications executed successfully.`

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**: `java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
`
- **Operating System**: Linux / CentOS 6
- **Database**: PostGreSQL 9.6

**Comment by scrmtrey91** [comment] 2018-06-26 18:08
Try like this:

--name poi-api-ear 

instead of:

--name=poi-api-ear

**Comment by scrmtrey91** [comment] 2018-06-26 18:19
I try it like this: 

 .\asadmin deploy --name testapp --force=true C:\Users\Tadej\IdeaProjects\payara5testapp\payara5testapp-backend\target\payara5testapp-backend-1.0-SNAPSHOT.war
Application deployed with name testapp.

So its working properly.

**Comment by md-mg** [comment] 2018-06-27 05:17
Strange. Not on my system:
````
./asadmin deploy --name activemq-rar --force=true /root/software/activemq-rar-5.15.4.rar
Application deployed with name activemq-rar-5.15.4.
Command deploy executed successfully.

[root@md-vm-059 bin]# cp /root/software/activemq-rar-5.15.4.rar /tmp/test.rar
[root@md-vm-059 bin]# ./asadmin deploy --name activemq-rar --force=true /tmp/test.rar
Application deployed with name test.
Command deploy executed successfully.

./asadmin deploy --name activemq --force=true /tmp/test.rar
Application deployed with name test.
Command deploy executed successfully.
````
--name is ignored and the basename of the file to deploy is taken.

I'll set up a naked payarafish on a test-system and try it again...

**Comment by md-mg** [comment] 2018-06-27 05:36
With a new, naked payarafish, unzipped, started, nothing else done:
````
[root@md-732a bin]# ./asadmin start-domain
Waiting for domain1 to start ......
Successfully started the domain : domain1
domain  Location: /usr/local/payara5/glassfish/domains/domain1
Log File: /usr/local/payara5/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
[root@md-732a bin]# ./asadmin deploy --name activemq --force=true /root/software/activemq-rar-5.15.4.rar 
Application deployed with name activemq-rar-5.15.4.
Command deploy executed successfully.
[root@md-732a bin]# 
````
--name is still ignored.

server.log of the (naked) test-system:
[server.log](https://github.com/payara/Payara/files/2139880/server.log)

**Comment by md-mg** [comment] 2018-06-27 06:04
... also tried on a windows-system, fresh new payara:
````
C:\Users\mg\Downloads\payara-5.182\payara5\bin>asadmin start-domain
Waiting for domain1 to start ...............
Successfully started the domain : domain1
domain Location: C:\Users\mg\Downloads\payara-5.182\payara5\glassfish\domains\domain1
Log File: C:\Users\mg\Downloads\payara-5.182\payara5\glassfish\domains\domain1\logs\server.log
Admin Port: 4848
Command start-domain executed successfully.

C:\Users\mg\Downloads\payara-5.182\payara5\bin>asadmin deploy --name test C:\Users\marc.gebauer\Downloads\activemq-rar-5.15.4.rar
Application deployed with name activemq-rar-5.15.4.
Command deploy executed successfully.

C:\Users\mg\Downloads\payara-5.182\payara5\bin>
````

I used the payara-5.182.zip direct from the website payara.fish -> downloads.

md5sum is
`80d859f1c80811b0095f0d68c2c04fec  payara-5.182.zip`

**Comment by scrmtrey91** [comment] 2018-06-27 06:10
Maybe it does not work, because you are trying to deploy rar file instead of war, jar, ear ?

**Comment by md-mg** [comment] 2018-06-27 06:20
... but it works on pf 4.1.2.
... and, as you can see above - i tried also a .ear-file:
````
./asadmin deploy --name test --force=true /tmp/poi-api-ear-release-4.0.15-SNAPSHOT.ear
Application deployed with name poi-api-ear-release-4.0.15-SNAPSHOT.
Command deploy executed successfully.
./asadmin list-applications
poi-api-ear-release-4.0.15-SNAPSHOT  <ear, web, ejb>
Command list-applications executed successfully.
````

**Comment by md-mg** [comment] 2018-06-29 05:28
I tried installing a PF 5.181 - it works.
````
[root@md-732a bin]# ./asadmin start-domain
Waiting for domain1 to start ........
Successfully started the domain : domain1
domain  Location: /usr/local/payara5.181/glassfish/domains/domain1
Log File: /usr/local/payara5.181/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
[root@md-732a bin]# ./asadmin version
Version = Payara Server  5.181 #badassfish (build 213)
Command version executed successfully.
[root@md-732a bin]# ./asadmin deploy --name activemq /root/software/activemq-rar-5.15.4.rar 
Application deployed with name activemq.
Command deploy executed successfully.
[root@md-732a bin]# ./asadmin list-application
Command list-application not found. 
Check the entry of command name. This command may be provided by a package that is not installed.
Closest matching local and remote command(s): 
    list-application-refs
    list-applications

Command list-application failed.
[root@md-732a bin]# ./asadmin list-applications
activemq  <connector>  
Command list-applications executed successfully.
````

so it must be a bug in the 5.182-release-version.

**Comment by md-mg** [comment] 2018-06-29 09:29
I'm not a developer but maybe the merge
````SHA-1: 83dd7fd5ab52b0eb416d7cc39b9476cda10b469f

* Merge pull request #2528 from MeroRai/PAYARA-2461

PAYARA-2461 Options to allow the application's name to be used for Portable JNDI name of EJBs contained within an EAR````

on nucleus\deployment\admin\src\main\java\org\glassfish\deployment\admin\DeployCommand.java

could be responsible for this behaviour...

**Comment by smillidge** [comment] 2018-06-29 16:45
Thanks we will try to reproduce.

**Comment by MeroRai** [comment] 2018-07-02 09:54
Hi @md-mg, 

Since 5.182 release, `--name` parameter is ignored if Module Descriptors are present in an application. You can override this behavior by using `--forcename` parameter. 

Regards,
Rai

**Comment by md-mg** [comment] 2018-07-02 10:10
Thank you for your replay - I'll test...

But since it changes a default-behaviour I think it should be mentioned in the asadmin deploy --help - output and in the change-logs / release-notes of the version.
Also the --forcename-option should be in the --help-output of asadmin.

(as long as I haven't overlooked it - payara-documentation sometimes is a litte bit confusing)

**Comment by smillidge** [comment] 2018-07-02 19:19
Documentation issue raised PAYARA-2893

**Comment by md-mg** [comment] 2018-07-03 07:20
ok, with --forcename the value of the --name-option is accepted.

**personal point of view:**
... but i'm not happy with this behavior - why use --name when it's sometimes acceptet, sometimes not? 
If I use --name on deploy i rely on it - that's because I use it. 
Without --name the deploy may do what's specified in the application-environment-configuration-file, but if - as a server-admin - i specifiy the name i'd like the server to use it.

So for me I now always have to use --name and --forcename because if not I can't rely on the servers behaviour on deploy.

**Comment by OndrejM** [comment] 2018-07-03 11:19
@md-mg the reason for this change is because of how IDEs like Eclipse or Netbeans use the deploy command. All of them use the --name argument even if that's not desirable, without any option to change this. Our customer needed an option to deploy using the names specified in deployment descriptors instead. We could not fix the IDE plugins at that time, so we changed the behavior as a workaround since 4.1.2.174. Now we would probably fix Payara plugins for IDEs as we already maintain them for Eclipse and Netbeans.

I admit that we made a mistake and should make this behavior optional with a system property. I'm sorry that we failed your expectations. That sometimes happens because we have to prioritize our customers. And, even if we try not to, but we also make mistakes.

**Comment by md-mg** [comment] 2018-07-03 11:45
thanks for the explanation - you're doing a great job with pf and for sure your customers are more important for you then those using the community-edition.

the main point from my point of view was (after recognizing it's not a bug, just a feature) - documentation and release-notes didn't explain this changed behavior to me. And i didn't expect such a change in a minor-release-version.

but now, with the additional parameter our deploys work as expected and i can continue testing before upgrading our live-clusters...

**Comment by smillidge** [comment] 2018-09-07 11:54
Fixed by https://github.com/payara/Payara-Server-Documentation/pull/420

**Closed by smillidge** 2018-09-07 11:54 UTC
Labels: documentation

**Comment by md-mg** [comment] 2018-09-07 14:02
Ich bin bis 10.09.2018 abwesend.

in dringenden Fällen wenden Sie sich bitte an M. Hörz
(m.hoerz@mairdumont.com).


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[payara/Payara] asadmin ignores --name on deploy of applications (#2900)"
gesendet am 07.09.2018 13:55:06.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

---------------------------------------------------------------------------------------------------------------------------------------------------------------
Hier finden Sie unser aktuelles Digitales Verlagsprogramm:
http://www.mairdumont.com/geschaftsbereiche/handel/downloads
---------------------------------------------------------------------------------------------------------------------------------------------------------------
MAIRDUMONT GmbH & Co. KG
Sitz: 73760 Ostfildern
Amtsgericht: Stuttgart HRA 211281
Geschäftsführer: Dr. Stephanie Mair-Huydts, Dr. Thomas Brinkmann, Dr. Frank
Mair, Steffen Rübke

**Comment by md-mg** [comment] 2018-09-07 14:02
Ich bin bis 10.09.2018 abwesend.

in dringenden Fällen wenden Sie sich bitte an M. Hörz
(m.hoerz@mairdumont.com).


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[payara/Payara] asadmin ignores --name on deploy of applications (#2900)"
gesendet am 07.09.2018 13:55:08.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

---------------------------------------------------------------------------------------------------------------------------------------------------------------
Hier finden Sie unser aktuelles Digitales Verlagsprogramm:
http://www.mairdumont.com/geschaftsbereiche/handel/downloads
---------------------------------------------------------------------------------------------------------------------------------------------------------------
MAIRDUMONT GmbH & Co. KG
Sitz: 73760 Ostfildern
Amtsgericht: Stuttgart HRA 211281
Geschäftsführer: Dr. Stephanie Mair-Huydts, Dr. Thomas Brinkmann, Dr. Frank
Mair, Steffen Rübke
