### ISSUE TITLE
Can not change-admin-password on AIX 7.1 unknown error

### ISSUE THREAD

**Issue by samyomar** [payara/Payara#571] opened 2015-12-17 22:14 UTC
as shown below, I got unknown error when I tried to invoke this command on AIX 7.1
change-admin-password

I assumed that the default user name is admin and the default password is ''  (nothing, I pressed enter)

![payarafish](https://cloud.githubusercontent.com/assets/1243220/11883494/0b556e6a-a51c-11e5-997c-ffacd33466e4.PNG)

**Comment by smillidge** [comment] 2015-12-18 08:06
Hi was this using Payara Blue?  Are you using IBM JDK, if so what version?

**Comment by smillidge** [comment] 2015-12-20 16:16
There should also be a stack trace on the Payara Server side can you post that?

**Comment by smillidge** [comment] 2015-12-20 16:50
Tested Payara Blue on IBM JDK 1.8 on linux but couldn't reproduce the issue.

**Comment by samyomar** [comment] 2015-12-20 17:27
I am using Payara blue for sure.
The default Java version for the server was JDK 7, as shown here

![captwwwure](https://cloud.githubusercontent.com/assets/1243220/11919022/67785150-a74f-11e5-9a29-9b8049a14463.PNG)


and to make Payara work with JDK 8, I updated asenv.conf file as shown here

![capwsssture](https://cloud.githubusercontent.com/assets/1243220/11919021/621368bc-a74f-11e5-91c5-d0c1be048403.PNG)

**Comment by smillidge** [comment] 2015-12-20 18:35
There should be an error in the server log if you are getting an error from the asadmin command.

**Comment by samyomar** [comment] 2015-12-20 20:35
[2015-12-17T23:19:01.707+0200] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=203 _ThreadName=Thread-13] [timeMillis: 1450387141707] [levelValue: 800] [[
  JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]]]

[2015-12-17T23:19:50.348+0200] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1450387190348] [levelValue: 800] [[
  JVM invocation command line:
/usr/java8_64/bin/java
-cp
/home/oracle/samy/payara41/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-XX:MaxPermSize=192m
-Xmx512m
-javaagent:/home/oracle/samy/payara41/glassfish/lib/monitor/flashlight-agent.jar
-client
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/home/oracle/samy/payara41/glassfish/domains/domain1/config/cacerts.jks
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/home/oracle/samy/payara41/glassfish/modules/autostart/
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=/home/oracle/samy/payara41/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.endorsed.dirs=/home/oracle/samy/payara41/glassfish/modules/endorsed:/home/oracle/samy/payara41/glassfish/lib/endorsed
-Djava.security.policy=/home/oracle/samy/payara41/glassfish/domains/domain1/config/server.policy
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.bundles.startTransient=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfelix.fileinstall.log.level=2
-Djavax.net.ssl.keyStore=/home/oracle/samy/payara41/glassfish/domains/domain1/config/keystore.jks
-Djava.security.auth.login.config=/home/oracle/samy/payara41/glassfish/domains/domain1/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/home/oracle/samy/payara41/glassfish/domains/domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dosgi.shell.telnet.ip=127.0.0.1
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=/usr/java8_64/lib/ext:/usr/java8_64/jre/lib/ext:/home/oracle/samy/payara41/glassfish/domains/domain1/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djava.library.path=/home/oracle/samy/payara41/glassfish/lib:/usr/java8_64/jre/lib/ppc64/compressedrefs:/usr/java8_64/jre/lib/ppc64:/usr/java8_64/jre/lib/ppc64/j9vm:/usr/java8_64/lib/ppc64:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/home/oracle/samy/payara41/glassfish/domains/domain1
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/home/oracle/samy/payara41/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/home/oracle/samy/payara41/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain]]

[2015-12-17T23:19:53.226+0200] [Payara 4.1] [INFO] [NCLS-LOGGING-00009] [javax.enterprise.logging] [tid: _ThreadID=54 _ThreadName=RunLevelControllerThread-1450387193144] [timeMillis: 1450387193226] [levelValue: 800] [[
  Running Payara Version: Payara Server  4.1.1.154 #badassfish (build 8)]]

[2015-12-17T23:19:53.227+0200] [Payara 4.1] [INFO] [NCLS-LOGGING-00010] [javax.enterprise.logging] [tid: _ThreadID=54 _ThreadName=RunLevelControllerThread-1450387193144] [timeMillis: 1450387193227] [levelValue: 800] [[
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter]]

[2015-12-17T23:19:53.510+0200] [Payara 4.1] [INFO] [SEC-SVCS-00100] [javax.enterprise.security.services] [tid: _ThreadID=53 _ThreadName=RunLevelControllerThread-1450387193141] [timeMillis: 1450387193510] [levelValue: 800] [[
  Authorization Service has successfully initialized.]]

[2015-12-17T23:19:53.571+0200] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=55 _ThreadName=RunLevelControllerThread-1450387193149] [timeMillis: 1450387193571] [levelValue: 800] [[
  Realm [admin-realm] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.]]

[2015-12-17T23:19:53.599+0200] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=55 _ThreadName=RunLevelControllerThread-1450387193149] [timeMillis: 1450387193599] [levelValue: 800] [[
  Realm [file] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.]]

[2015-12-17T23:19:53.610+0200] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=55 _ThreadName=RunLevelControllerThread-1450387193149] [timeMillis: 1450387193610] [levelValue: 800] [[
  Realm [certificate] of classtype [com.sun.enterprise.security.auth.realm.certificate.CertificateRealm] successfully created.]]

[2015-12-17T23:19:53.645+0200] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=56 _ThreadName=RunLevelControllerThread-1450387193149] [timeMillis: 1450387193645] [levelValue: 800] [[
  Grizzly Framework 2.3.23 started in: 44ms - bound to [/0.0.0.0:7887]]]

[2015-12-17T23:19:53.675+0200] [Payara 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=55 _ThreadName=RunLevelControllerThread-1450387193149] [timeMillis: 1450387193675] [levelValue: 800] [[
  Registered org.glassfish.ha.store.adapter.cache.ShoalBackingStoreProxy for persistence-type = replicated in BackingStoreFactoryRegistry]]

[2015-12-17T23:19:53.683+0200] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=56 _ThreadName=RunLevelControllerThread-1450387193149] [timeMillis: 1450387193683] [levelValue: 800] [[
  Grizzly Framework 2.3.23 started in: 3ms - bound to [/0.0.0.0:6886]]]

[2015-12-17T23:19:53.690+0200] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=56 _ThreadName=RunLevelControllerThread-1450387193149] [timeMillis: 1450387193690] [levelValue: 800] [[
  Grizzly Framework 2.3.23 started in: 3ms - bound to [/0.0.0.0:4441]]]

[2015-12-17T23:19:53.701+0200] [Payara 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=53 _ThreadName=RunLevelControllerThread-1450387193141] [timeMillis: 1450387193701] [levelValue: 800] [[
  Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry]]

[2015-12-17T23:19:53.701+0200] [Payara 4.1] [INFO] [] [fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactory] [tid: _ThreadID=53 _ThreadName=RunLevelControllerThread-1450387193141] [timeMillis: 1450387193701] [levelValue: 800] [[
  Registered Hazelcast BackingStoreFactory with persistence-type = hazelcast]]

[2015-12-17T23:19:54.011+0200] [Payara 4.1] [INFO] [] [org.hibernate.validator.internal.util.Version] [tid: _ThreadID=54 _ThreadName=RunLevelControllerThread-1450387193144] [timeMillis: 1450387194011] [levelValue: 800] [[
  HV000001: Hibernate Validator 5.1.2.Final]]

[2015-12-17T23:19:54.777+0200] [Payara 4.1] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1450387194777] [levelValue: 800] [[
  Payara Server  4.1.1.154 #badassfish (8) startup time : Felix (2,480ms), startup services(1,639ms), total(4,119ms)]]

[2015-12-17T23:19:54.778+0200] [Payara 4.1] [INFO] [] [fish.payara.nucleus.util.CleanupPostBoot] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1450387194778] [levelValue: 800] [[
  Cleaning JarFileFactory Cache to prevent jar FD leaks]]

[2015-12-17T23:19:54.820+0200] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=53 _ThreadName=RunLevelControllerThread-1450387193141] [timeMillis: 1450387194820] [levelValue: 800] [[
  Grizzly Framework 2.3.23 started in: 8ms - bound to [/0.0.0.0:7677]]]

[2015-12-17T23:19:54.912+0200] [Payara 4.1] [WARNING] [NCLS-JMX-00007] [javax.enterprise.system.jmx] [tid: _ThreadID=106 _ThreadName=Thread-28] [timeMillis: 1450387194912] [levelValue: 900] [[
  Cannot start JMX connector JmxConnector config: { name = system, Protocol = rmi_jrmp, Address = 0.0.0.0, Port = 8686, AcceptAll = false, AuthRealmName = admin-realm, SecurityEnabled = false} due to exception java.lang.RuntimeException: Port 8686 is not available for the internal rmi registry. This means that a call was made with the same port, without closing earlier registry instance. This has to do with the system jmx connector configuration in admin-service element of the configuration associated with this instance]]

[2015-12-17T23:19:54.913+0200] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=106 _ThreadName=Thread-14] [timeMillis: 1450387194913] [levelValue: 1000] [[
  java.lang.RuntimeException: Port 8686 is not available for the internal rmi registry. This means that a call was made with the same port, without closing earlier registry instance. This has to do with the system jmx connector configuration in admin-service element of the configuration associated with this instance]]

[2015-12-17T23:19:54.913+0200] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=106 _ThreadName=Thread-14] [timeMillis: 1450387194913] [levelValue: 1000] [[
  at org.glassfish.admin.mbeanserver.RMIConnectorStarter._startRegistry(RMIConnectorStarter.java:257)]]

[2015-12-17T23:19:54.913+0200] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=106 _ThreadName=Thread-14] [timeMillis: 1450387194913] [levelValue: 1000] [[
  at org.glassfish.admin.mbeanserver.RMIConnectorStarter.startRegistry(RMIConnectorStarter.java:235)]]

[2015-12-17T23:19:54.913+0200] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=106 _ThreadName=Thread-14] [timeMillis: 1450387194913] [levelValue: 1000] [[
  at org.glassfish.admin.mbeanserver.RMIConnectorStarter.<init>(RMIConnectorStarter.java:169)]]

[2015-12-17T23:19:54.913+0200] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=106 _ThreadName=Thread-14] [timeMillis: 1450387194913] [levelValue: 1000] [[
  at org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread.startConnector(JMXStartupService.java:310)]]

[2015-12-17T23:19:54.913+0200] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=106 _ThreadName=Thread-14] [timeMillis: 1450387194913] [levelValue: 1000] [[
  at 
Here is a copy from the server.log file.
Please note that I am running GF 4.1 already on the same server. and to make Payara work
beside GF I changed the HTTP , HTTPS and JMS ports in the domain.xml file.

===============
org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread.run(JMXStartupService.java:350)]]

[2015-12-17T23:19:54.933+0200] [Payara 4.1] [INFO] [NCLS-BOOTSTRAP-00027] [javax.enterprise.bootstrap] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1450387194933] [levelValue: 800] [[
  Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@16f85e10 as OSGi service registration: org.apache.felix.framework.ServiceRegistrationImpl@86120bf4.]]

[2015-12-17T23:19:54.961+0200] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=50 _ThreadName=Thread-13] [timeMillis: 1450387194961] [levelValue: 800] [[
  /home/oracle/samy/payara41/glassfish/domains/domain1/autodeploy/bundles does not exist, please create it.]]

[2015-12-17T23:20:04.497+0200] [Payara 4.1] [INFO] [NCLS-REST-00001] [javax.enterprise.admin.rest] [tid: _ThreadID=84 _ThreadName=admin-listener(2)] [timeMillis: 1450387204497] [levelValue: 800] [[
  Listening to REST requests at context: /command/domain.]]

**Comment by smillidge** [comment] 2015-12-20 20:51
that's just the boot messages do you have an exception in one of the server logs after running the change password command

**Comment by samyomar** [comment] 2015-12-20 21:11
No, and here is the full file for your reference.
[server.zip](https://github.com/payara/Payara/files/67959/server.zip)

**Comment by smillidge** [comment] 2016-01-24 22:26
We've tested on AIX with IBM JDK and can't reproduce this issue. Are you sure you are connected to the correct server and trying to change the correct asadmin password as I noticed from your logs you are not running Payara on the default ports.

**Comment by samyomar** [comment] 2016-01-31 19:32
I am connecting to our AIX server for sure.
and Yes , I am not using the default ports as it was allocated to Glassfish 4.1.1
I will try to stop glassfish completely then run paraya, maybe some conflicts occurred.

**Comment by mikecroft** [comment] 2016-06-10 13:00
Hi @samyomar are you still having problems with this?

**Comment by mikecroft** [comment] 2016-07-16 14:31
Is there still an issue for you here @samyomar?

**Comment by mikecroft** [comment] 2016-07-28 14:29
Hi @samyomar - I'm going to close this since we can't reproduce it. Please feel free to reopen if it's still a problem for you and we can work through it together.

**Closed by mikecroft** 2016-07-28 14:29 UTC
Labels: 1:Wait, cannot reproduce, requestor unresponsive (1), requestor unresponsive (2), Test Case Required
