### ISSUE TITLE
websockets not working on virtual server /CUSTCOM-97

### ISSUE THREAD

**Issue by mirozitnansky** [payara/Payara#3311] opened 2018-10-24 13:17 UTC
# Description #
----------

When using websocket on context root of deployed application, it's working ok.
If we are addressing application over domain defined in payara virtual server and using default-web-module to set specific application for context root '/', web socket is unable to connect, however application working just fine over virtual server.

## Expected Outcome

Websocket endpoint should listen same way as application itself.

## Current Outcome

Websocket connects to full path of deployed application (for example provided below)

> ws://localhost:8080/showcase/omnifaces.push/counter?b912634e-bf4c-4032-b8ab-773194274c6a

but not to virtual server default module path

> WebSocket connection to 'ws://test.local:8080/omnifaces.push/counter?b912634e-bf4c-4032-b8ab-773194274c6a' failed: Error during WebSocket handshake: Unexpected response code: 404

where context root _showcase_ is missing

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain

2 -**  Configure an virtual server for server instance :

![image](https://user-images.githubusercontent.com/22233613/47432887-91c24500-d79f-11e8-986c-901e91114aa4.png)

3 -**  Add to system hosts file :
`127.0.0.1 test.local`

3 -**  Deploy omnifaces showcase war to virtual server server and test.local:
https://github.com/omnifaces/showcase/blob/master/showcase.war
![image](https://user-images.githubusercontent.com/22233613/47432289-1d3ad680-d79e-11e8-9595-fbf4372f9f69.png)

4 -** Test if websocket demo is running on server
http://localhost:8080/showcase/push/socket

5 -** Add default web module _socket_ to virtual server _test.local_

6 -** Test websocket demo over virtual server without application context root _showcase_ 
http://test.local:8080/push/socket
In chrome inspector js console is error

> WebSocket connection to 'ws://test.local:8080/omnifaces.push/counter?b912634e-bf4c-4032-b8ab-773194274c6a' failed: Error during WebSocket handshake: Unexpected response code: 404

## Environment ##

- **Payara Version**: 4.1.1.185
- **Edition**: Full
- **JDK Version**: 8 u191 - Oracle
- **Operating System**: Windows, Linux

**Comment by rdebusscher** [comment] 2019-12-17 15:32
Tracked by `CUSTCOM-97`

**Comment by AlanRoth** [comment] 2020-11-11 11:24
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:24 UTC
Labels: bug, status:accepted
