### ISSUE TITLE
Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer

### ISSUE THREAD

**Issue by fisherab** [payara/Payara#1160] opened 2016-10-31 12:49 UTC
# Could not create stateless EJB #
----------

My code runs correctly on Glassfish 4.0 and on WildFly. It does not work on Glassfish 4.1 so I tried Payara Server and get the same problem. There has been some mention of the problem on the web and the general feeling is that it is a timing issue in Glassfish where an EJB is being used before it is fully initialised. I do have a number of interdependent @Singletons trying to start up.

## Expected Outcome

The EJB starts correctly
## Current Outcome
I see in the server.log:

```
Caused by: javax.ejb.CreateException: Could not create stateless EJB
	at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:514)
	at  com.sun.ejb.containers.StatelessSessionContainer.access$000(StatelessSessionContainer.java:97)
	at com.sun.ejb.containers.StatelessSessionContainer$SessionContextFactory.create(StatelessSessionContainer.java:698)
	... 64 more
     Caused by: A MultiException has 1 exceptions.  They are:
     1. java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
	at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:89)
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:926)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:980)
	at org.glassfish.jersey.gf.ejb.internal.EjbComponentInterceptor.inject(EjbComponentInterceptor.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:153)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:998)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:417)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:380)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:1959)
	at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:507)
	... 66 more
Caused by: java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAnalyzer(ServiceLocatorImpl.java:2387)
	at org.jvnet.hk2.internal.Utilities.getClassAnalyzer(Utilities.java:164)
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:925)
```

[server.log.txt](https://github.com/payara/Payara/files/561747/server.log.txt)

## Steps to reproduce (Only for bug reports) 

If necessary I will produce a simplified version of the application.

### Samples

None

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**:  Full 
- **JDK Version**: Oracle 1.8.0_101
- **Operating System**: Ubuntu

**Comment by OndrejM** [comment] 2016-10-31 13:17
Problem mentioned also here: http://stackoverflow.com/questions/29408162/glassfish-4-1-deploy-fails-could-not-find-an-implementation-of-classanalyser
and here: http://jersey.576304.n2.nabble.com/Erratic-missing-quot-CdiInjecteeSkippingClassAnalyzer-quot-Exceptions-td7583446.html
Not clear though what happens.

**Comment by OndrejM** [comment] 2016-10-31 13:19
Hi @fisherab, this is most probably a bug in GlassFish code. Can you reproduce the problem every time, or it happens only sometimes, randomly?
If you attach a sample application, it would significantly help in chasing this issue and fixing it.

**Comment by fisherab** [comment] 2016-10-31 14:32
Yes it is totally reproducible. I will try and produce a simpler application which exhibits the same problem.

**Comment by fisherab** [comment] 2016-11-03 15:42
While trying to build this simple example to show up the bug. I found that our setup script for glassfish servers includes:

`asadmin set configs.config.server-config.cdi-service.enable-implicit-cdi=false`

This line was inserted in the script some years ago to fix some other problem which nobody now remembers. Removing this line allows us to run with payara41, glassfish 4.1.1 and glassfish 4.0.

I have not closed the bug because there is still the question of why it works on glassfish 4.0 but not in 4.1 and derived works. However I would not be unhappy if you choose to close it.

**Comment by fturizo** [comment] 2016-12-27 17:33
Hello @fisherab, since you are disabling implicit CDI scanning in your application this issue seems to be related to the use of third-party libraries. Is this still a problem for your setup? If so please include the sample application to reproduce it so we can give some assessment. Let us know how it goes.

**Comment by fturizo** [comment] 2017-01-25 00:33
Hi @fisherab. Is this issue still persisting for you? Can you provide a reproducer application in this case to detect and identify the cause?

**Comment by mikecroft** [comment] 2017-03-30 20:20
Hi @fisherab - I'm going to close this as you mentioned in your last comment that you had found a solution. We'd still be interested to see a reproducer if you have time to create one, though.

**Closed by mikecroft** 2017-03-30 20:20 UTC
Labels: 1:Wait, c:PossibleBug, requestor unresponsive (1), Test Case Required
