### ISSUE TITLE
Payara source does not compile using JDK 11 or JDK 17. Please fix.

### ISSUE THREAD

**Issue by BreDenro** [payara/Payara#5511] opened 2021-11-30 21:05 UTC
# Description #
----------

See https://github.com/payara/Payara/issues/5509 for all explanations.

JDK 8 is really old, and we don't always even have this on our systems anymore. Please make Payara source compile with JDK 11 and JDK 17.

**Comment by fturizo** [comment] 2021-11-30 21:12
@BreDenro, I'm sorry but we were clear on issue #5509 that at the moment the Payara source code can only be built using JDK 8 as well. This is by design and we have plans to make the source code on Payara Platform 6 and onwards compilable with newer versions of Java. We'll close this issue but please, refrain from reopening or raising this issue again in the future.

**Closed by fturizo** 2021-11-30 21:12 UTC
Labels: Type: Enhancement, Status: Open
