### ISSUE TITLE
Unable to resolve jackson-dataformat-xml due to wrong OSGI version range /FISH-45

### ISSUE THREAD

**Issue by Snofillap** [payara/Payara#4060] opened 2019-06-25 16:01 UTC
# Description #
----------

Unable to resolve jackson-dataformat-xml in 5.191 and 5.192 due to wrong OSGI version range
related to com.fasterxml.jackson.dataformat.jackson-dataformat-xml and org.codehaus.stax2. 

Simple calls like "new com.fasterxml.jackson.dataformat.xml.XmlMapper()" will fail with class loading error.

Consider the following example bean of a simple ejb-project referencing payara-embedded-all.

@javax.ejb.Singleton
@javax.ejb.Startup
public class App {
	@javax.annotation.PostConstruct
	public void startup() {
		new com.fasterxml.jackson.dataformat.xml.XmlMapper();
	}
}

It will lead to an deployment error. 

## Expected Outcome

Jar with the above class should deploy. 

## Current Outcome

Deployment error. 

[Payara 5.191] [WARNUNG] [] [javax.enterprise.system.core] [tid: _ThreadID=41 _ThreadName=http-thread-pool::http-listener-2(2)] [timeMillis: 1559836422032] [levelValue: 900] [[
  APIClassLoader.loadClass() caused exception
org.osgi.framework.BundleException: Unable to resolve com.fasterxml.jackson.dataformat.jackson-dataformat-xml [150](R 150.0): missing requirement [com.fasterxml.jackson.dataformat.jackson-dataformat-xml [150](R 150.0)] osgi.wiring.package; (&(osgi.wiring.package=org.codehaus.stax2)(version>=3.1.0)(!(version>=4.0.0))) Unresolved requirements: [[com.fasterxml.jackson.dataformat.jackson-dataformat-xml [150](R 150.0)] osgi.wiring.package; (&(osgi.wiring.package=org.codehaus.stax2)(version>=3.1.0)(!(version>=4.0.0)))]
                at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4362)

## Steps to reproduce (Only for bug reports) 

Create a simple EJB project with the above class and try to deploy.

## Context (Optional)

Actually this may be related to org.codehaus.stax2 which changed version from 3.1.4 to 4.1.0 between 183 and 191. 
jackson-dataformat-xml.jar (in payara5\glassfish\modules) requires stax2 to be in the range “3.*”. Look to the end of its MANIFEST.MF. 
Replacing stax2 4.1 with the older version 3.1.4 and restarting payara failed. We get a 
Unable to resolve com.fasterxml.woodstox.woodstox-core [382](R 382.0): missing requirement [com.fasterxml.woodstox.woodstox-core [382](R 382.0)] osgi.wiring.package; (&(osgi.wiring.package=org.codehaus.stax2)(version>=4.1.0)(!(version>=5.0.0))) Unresolved requirements: [[com.fasterxml.woodstox.woodstox-core [382](R 382.0)] osgi.wiring.package; (&(osgi.wiring.package=org.codehaus.stax2)(version>=4.1.0)(!(version>=5.0.0)))]

Patching jackson-dataformat-xml.jar worked as a workaround for us: 
We changed MANIFEST.MF to allow for stax4 between 3 and 5. 
It was
org.codehaus.stax2;version="[3.1,4)", org.codehaus.stax2.io;version="[3.1,4)",org.codehaus.stax2.ri;version="[3.1,4)"
We patched it to be
org.codehaus.stax2;version="[3.1,5)", org.codehaus.stax2.io;version="[3.1,5)",org.codehaus.stax2.ri;version="[3.1,5)"

## Environment ##

- **Payara Version**: 5.191 and 5.192
- **Edition**: Full
- **JDK Version**: OpenJDK1.8.0_201 
- **Operating System**: Windows

**Comment by OndroMih** [comment] 2019-07-05 22:09
I can confirm there's a bug and it's easy to reproduce, raising an internal ticket.

**Comment by m3n4d3l** [comment] 2019-07-13 17:58
I have the same problem. Prevents an application from connecting to a mysql database. Does anyone have a momentary solution?

**Comment by borjapenman** [comment] 2019-07-19 12:22
@Snofillap left a workaround (patching jackson-dataformat-xml.jar) but I hope there is a fix for this soon

**Comment by borjapenman** [comment] 2019-08-29 14:02
Still reproducible on 5.193 :( It didn't seem very difficult to fix

**Comment by smillidge** [comment] 2019-10-26 20:17
Upstream component was upgraded in #4266

**Comment by borjapenman** [comment] 2019-12-02 14:39
Still reproducible on 5.194

**Comment by ilgrosso** [comment] 2019-12-05 07:47
I confirm this bug is still present with 5.194

**Comment by ilgrosso** [comment] 2019-12-05 08:37
FYI, I have `<class-loader delegate="false"/>` in my `glassfish-web.xml`.

Explicitly adding the Maven dependency:

```xml
        <dependency>
          <groupId>com.fasterxml.jackson.dataformat</groupId>
          <artifactId>jackson-dataformat-xml</artifactId>
          <version>...</version>
        </dependency>
```

made it working.

**Comment by vschimanski** [comment] 2019-12-17 21:36
Confirmed on my side as well,  have the error described,

and funny things is  is that  ... it  works for me on old glassfish 5.01 without this error.

**Comment by rdebusscher** [comment] 2019-12-20 14:20
Tracked now by `CUSTCOM-21`

**Comment by hulky188** [comment] 2020-02-07 14:53
on 5.194, stax version is 4.1, but  jackson-dataformat-xml.jar manifest is asking for at least 4.2.
So, I succeded to remove the error by replacing :
,org.codehaus.stax2;version="[4.2,5)",org.codehaus.stax2.io;version="[4.2,5)",org.codehaus.stax2.ri;version="[4.2,5)"
with
,org.codehaus.stax2;version="[4.1,5.1)",org.codehaus.stax2.io;version="[4.1,5)",org.codehaus.stax2.ri;version="[4.1,5)"
But isn't it a problem to downgrade the possible version from 4.2 to 4.1?

**Comment by borjapenman** [comment] 2020-03-10 10:36
Still an issue in Payara 5.201. Just checked

**Comment by Dougnlizt** [comment] 2020-04-22 20:25
At first I thought I was having issues with Payara 5.201, but then after clearing things out and starting fresh, it is actually working for me.  Here is my environment:

- NetBeans 11.3 (running Zulu open jdk 1.8u252)
- Payara 5.201 on Zulu open jdk 1.8u252

I was able to get Payara 5.191 by modifying the Manifest file as posted previously.

**Closed** 2020-07-14 08:22 UTC
Labels: status:accepted, upstream bug

**Comment by MeroRai** [comment] 2020-07-14 08:28
This issue has been fixed by https://github.com/payara/Payara/pull/4784

**Comment by Faruktulumcu** [comment] 2020-07-28 08:31
> FYI, I have `<class-loader delegate="false"/>` in my `glassfish-web.xml`.
> 
> Explicitly adding the Maven dependency:
> 
> ```
>         <dependency>
>           <groupId>com.fasterxml.jackson.dataformat</groupId>
>           <artifactId>jackson-dataformat-xml</artifactId>
>           <version>...</version>
>         </dependency>
> ```
> 
> made it working.

that worked also for me
many thanks! 👍
