### ISSUE TITLE
If a batch job fails, the start time of the job is not saved

### ISSUE THREAD

**Issue by pythonmeister** [payara/Payara#5021] opened 2020-12-02 09:23 UTC
If a batch job fails, the start time of the job is not saved.

![image](https://user-images.githubusercontent.com/48514286/100853727-6040fb00-3488-11eb-8e39-73a113a419d8.png)

Payara 5.2020.6
Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux / buster
AdoptOpenJDK 11.0.8
PostgreSQL Server 12.5 (Debian 12.5-1.pgdg100+1)

Please also see #5018

**Comment by AlanRoth** [comment] 2020-12-02 09:46
Hello again @pythonmeister, sorry about prematurely closing your issue, we can carry on here. Does every failed batch job have no start time?

**Comment by pythonmeister** [comment] 2020-12-02 09:48
No problem, Alan, let's go on here. 
As far as I can tell, yes.

**Comment by pythonmeister** [comment] 2020-12-02 09:54
And, it happend again:
![image](https://user-images.githubusercontent.com/48514286/100857197-b31cb180-348c-11eb-9ac6-d4c9b4d1bb8e.png)
A job is STARTING, but never reaches STARTED state and also does not record a start time.

**Comment by AlanRoth** [comment] 2020-12-02 10:01
The failed jobs not reporting a start time may be expected, as it may be showing that the batch job has failed at startup, so no start time can be logged. However, if a batch job began then failed, a start time should be logged. Does the 'Starting' job eventually fail?

**Comment by pythonmeister** [comment] 2020-12-02 10:05
The starting job never reaches a subsequent state, it never fails. Sooner or later we are forced to flush the jobs to re-enable the processing of incoming data. Annoyingly we never see exceptions inside the server.log if that happens.
Is there a way to increase visibility inside the log?

**Comment by AlanRoth** [comment] 2020-12-02 10:22
You can have a look at the logger settings in the administration console - but I don't believe there is a logger for batch jobs, however, you can add your own logger and set it to 'ALL'. 

The jobs stuck in the 'starting' state should possibly timeout after some time. I'm in contact with the engineering team to confirm.

**Comment by pythonmeister** [comment] 2020-12-02 10:36
The timeout is probably beyond several hours, as far as I can tell from watching our system closely.

**Comment by AlanRoth** [comment] 2020-12-02 10:44
Could this be mis-configuration? Do batch jobs you have seen run successfully fail or get stuck in the 'Starting' state? Is there any way to reproduce this?

**Comment by pythonmeister** [comment] 2020-12-02 10:55
We have both cases:

- stuck in STARTING
- FAILED "successfully"

Unfortunately we found no way to reproduce, it just happens in our production system.

**Comment by AlanRoth** [comment] 2020-12-02 12:29
Hi @pythonmeister, 

I've had a discussion with some of our engineers, and I'm afraid without a reproducer we cannot proceed and accept the issue, we do not have the resources to dedicate ourselves to deep investigation for community issues - if you find a way to reproduce the issue then we're more than happy to accept this. We also encourage that you investigate the issue yourself and submit a community contribution.

If it is critical that these issues are resolved by us, I can recommend that you purchase Payara Enterprise, as we will be able to perform a much deeper investigation to reproduce this issue. We will also be able to expedite the solution with our engineering team.

Thank you for your understanding, and I apologise I was not able to provide you with a resolution,
Alan

**Comment by pythonmeister** [comment] 2020-12-02 12:32
No problem; I added a custom logger, and we are now waiting for the problems to show.
I will open a new ticket if I have more meaningful information.

But this issue was two-fold: one was no start time information, the other was jobs not going beyond starting.

**Comment by AlanRoth** [comment] 2020-12-02 12:38
I will close this issue, for now, I hope you find a way to reproduce this! I'm sorry you're having problems with Payara in production.

I will comment on this issue if we do find any more information about this, (if some of the issues are intended or not).

Thank you for the fast replies also, it is much appreciated,
Alan

**Closed by AlanRoth** 2020-12-02 12:38 UTC
Labels: Status: Pending

**Comment by AlanRoth** [comment] 2020-12-02 13:01
Hi @pythonmeister, 

From the looks of it, the batch job is encountering an exception at the initialization step, meaning it gets marked as failed and the timestamp never gets set as you can see here, the startup method which sets the timestamp won't be called; [BaseStepControllerImpl.java](https://github.com/WASdev/standards.jsr352.jbatch/blob/f96f9aba0060bfe990714c783453145af0862ad3/com.ibm.jbatch.container/src/main/java/com/ibm/jbatch/container/impl/BaseStepControllerImpl.java#L139). This will also provide you with some hints on which logger to use to see the exceptions.

Thank you,
Alan
