### ISSUE TITLE
Gzip compression not working?

### ISSUE THREAD

**Issue by dorpsidioot** [payara/Payara#1143] opened 2016-10-21 09:39 UTC
I've set the compression to 'on' on both the HTTP listeners and modified the compressable mime types to: 'text/html,text/xml,text/plain,application/json,text/javascript'. This used to work like a charm in glassfish v3, but responses keep coming back uncompressed, but with encoding type 'chunked'.

I've tried disabling chunking but no avail either.

**Comment by smillidge** [comment] 2016-10-21 19:44
Do you think this is the same as https://java.net/jira/browse/GRIZZLY-1669?

**Comment by dorpsidioot** [comment] 2016-10-24 11:33
Don't think so, since that ticket is for requests where gzip compression has been applied to the request body. This is for the response body. In glassfish v3.1.2 this worked like a charm and it also works/worked(our prod server is still 4.1.154) on payara 4.1.154. I can confirm that it's not working with 4.1.162 and 4.1.163. It seems as if it's completely ignoring the configuration values. If I - for example - disable the response chunking, it still does response chunking.

(sorry for the late reply btw, busy weekend kept me from opening my laptop)

**Comment by rds76** [comment] 2016-10-24 12:03
U have to send request with correct header, `Accept-Encoding: gzip,deflate` does the trick. Response header contains `Content-Encoding: gzip` and body is gziped then. Working on latest Payara build.

**Comment by dorpsidioot** [comment] 2016-10-24 12:15
Request:

GET /alcatras-web/resources/chart/data?series%5B%5D=541529913041000008_EM&series%5B%5D=541529913024000001_IST&series%5B%5D=541529913140000046_IST&series%5B%5D=541529913024000087_IST&series%5B%5D=541529913133000022_IST&series%5B%5D=541529913025000727_IST&series%5B%5D=541529913045000004_C5S_CMP&series%5B%5D=541529913045000004_N2_CMP&chartType=MULTI&period=INTERVAL&source=AUTO&trackingPeriod=CUSTOM&version=ALCATRAS_CORRECTED&startDate=2016-08-01T12%3A56%3A00.000Z&endDate=2016-08-21T12%3A56%3A00.000Z HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
DNT: 1
Referer: http://localhost:8080/alcatras-web/dashboard
Accept-Encoding: gzip, deflate, sdch
Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: JSESSIONID=69a6eaa650f664c891a602fadd7e

Response:
HTTP/1.1 200 OK
Server: Payara Server  4.1.1.162 #badassfish
Content-Type: application/json
Date: Mon, 24 Oct 2016 12:11:58 GMT
Transfer-Encoding: chunked

HTTP listener configuration:

![image](https://cloud.githubusercontent.com/assets/13536281/19645272/3d4ebe4e-99f4-11e6-8488-f8ab3a372b15.png)

**Comment by rds76** [comment] 2016-10-24 12:45
what is the response content length?

**Comment by dorpsidioot** [comment] 2016-10-24 12:49
5MB+, so large enough to merit compression

**Comment by rds76** [comment] 2016-10-24 14:32
try change Mime Types to  `text/json`

**Comment by rds76** [comment] 2016-10-24 14:37
or try one o those:
`application/x-javascript` `text/javascript` `text/x-javascrip` `text/x-json`

**Comment by dorpsidioot** [comment] 2016-10-26 09:13
Tried all of them, no avail, still won't gzip, only chunks

**Comment by rds76** [comment] 2016-10-26 11:56
try remove **sdch** from request `Accept-Encoding: gzip, deflate, sdch`, and you can also try it with simple text/html requests
look, it works here:
```
Wed Oct 26 13:51:09 CEST 2016:DEBUG:>> "Accept-Encoding: gzip,deflate[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:>> "Content-Type: text/xml;charset=UTF-8[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:>> "SOAPAction: ""[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:>> "Content-Length: 228[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:>> "Connection: Keep-Alive[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:>> "User-Agent: Apache-HttpClient/4.1.1 (java 1.5)[\r][\n]"
```
```
Wed Oct 26 13:51:09 CEST 2016:DEBUG:<< "HTTP/1.1 200 OK[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:<< "Content-Encoding: gzip[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:<< "Server: Payara Server  4.1.1.163 #badassfish[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:<< "X-Powered-By: Servlet/3.1 JSP/2.3 (Payara Server  4.1.1.163 #badassfish Java/Oracle Corporation/1.7)[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:<< "Server: grizzly/2.3.25[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:<< "Content-Type: text/xml; charset=utf-8[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:<< "Date: Wed, 26 Oct 2016 11:51:09 GMT[\r][\n]"
Wed Oct 26 13:51:09 CEST 2016:DEBUG:<< "Transfer-Encoding: chunked[\r][\n]"

```

**Comment by dorpsidioot** [comment] 2016-11-15 12:38
Coming back to this after I've done some tests with 4.1.164 release and the results are still the same, if you curl with just gzip, deflate then compression works as it should. However most browsers add more stuff to this header and then it stops working completely, which is quite annoying to say the least, means that almost all modern browsers which add sdch and others make it so this will stop working all together.

**Comment by mikecroft** [comment] 2016-12-23 20:23
@dorpsidioot do you have a test case that we can see that shows this behaviour?

**Comment by lprimak** [comment] 2016-12-28 22:31
Internal ID https://payara.atlassian.net/browse/PAYARA-1288

**Comment by lprimak** [comment] 2016-12-28 23:03
@dorpsidioot I cannot reproduce this issue.

Here is what I do:

```$ curl -H "Accept-Encoding: gzip, deflate, sdch" -verbose http://localhost:8080/file.txt```
and I get gzipped output:

```
macbook-13340:Compress-1288 lprimak$ curl -H "Accept-Encoding: gzip, deflate, sdch" -verbose http://localhost:8080/file.txt
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /file.txt HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
> Referer: rbose
> Accept-Encoding: gzip, deflate, sdch
> 
< HTTP/1.1 200 OK
< Content-Encoding: gzip
< Accept-Ranges: bytes
< ETag: W/"4640-1482964903000"
< Last-Modified: Wed, 28 Dec 2016 22:41:43 GMT
< Content-Type: text/plain
< Date: Wed, 28 Dec 2016 23:00:46 GMT
< Transfer-Encoding: chunked
```

Now I see your point about chunking, as it's there and I can't turn it off,
but I definitely can't reproduce your gzip encoding problem.
Can you help me with that?
Thanks!

**Comment by lprimak** [comment] 2016-12-29 00:41
I've looked at the chunking option issue and it seems to be a regression with the new version of Grizzly.  I will investigate this further.  This may be something that needs to be raised with Grizzly team

**Comment by lprimak** [comment] 2016-12-30 01:18
I've created a Grizzly issue for the chunking:
https://java.net/jira/browse/GRIZZLY-1882

Please vote for it if you would like it fixed

**Comment by dorpsidioot** [comment] 2017-01-02 15:56
I will create a simple test case in the coming days, was on holiday before and have sprint planning to do in the coming days, will create on asap. Could be tied to either our use of wicket or jersey.

**Comment by lprimak** [comment] 2017-01-11 18:29
If you are using Wicket, it probably uses it's own code to generate output stream, so it needs to have it's own gzip compression, so that's probably it's not working for you, i.e. not a Payara issue

**Comment by lprimak** [comment] 2017-01-19 02:25
@dorpsidioot Any updates on this?  If it is indeed a Wicket issue, please close this ticket,
thanks!

**Comment by dorpsidioot** [comment] 2017-01-19 07:47
@lprimak I've run some tests locally with just a war and a large css file(bootstrap.css) and there it didn't compress either, so I doubt it's related to wicket. Could you copy your domain.xml settings for the basic http listener here, so I can see if there are any subtle differences which could break this?

**Comment by lprimak** [comment] 2017-01-19 17:10
How do you know it isn't compressing?  How are you testing it?  Can you post your curl statement here?

Also, let's do it the other way around...
Can you post:
- link to compressed domain folder
- link to the WAR you are testing
- curl command line that you are testing with.

This way I can hopefully reproduce this behavior.

Thank you!

**Comment by lprimak** [comment] 2017-01-19 17:32
I added the "text/css" mime type to the compressible types in admin console,
and it compresses boostrap.css in my tests.

Here is my network config chunk:
```
      <network-config>
        <protocols>
          <protocol name="http-listener-1">
            <http compressable-mime-type="text/html,text/xml,text/plain,text/css" max-connections="250" default-virtual-server="server" compression="on">
              <file-cache></file-cache>
            </http>
            <ssl></ssl>
          </protocol>
          <protocol name="http-listener-2" security-enabled="true">
            <http max-connections="250" default-virtual-server="server">
              <file-cache></file-cache>
            </http>
            <ssl classname="com.sun.enterprise.security.ssl.GlassfishSSLImpl" cert-nickname="s1as"></ssl>
          </protocol>
          <protocol name="admin-listener">
            <http encoded-slash-enabled="true" max-connections="250" default-virtual-server="__asadmin">
              <file-cache></file-cache>
            </http>
          </protocol>
        </protocols>
        <network-listeners>
          <network-listener protocol="http-listener-1" port="8080" name="http-listener-1" thread-pool="http-thread-pool" transport="tcp"></network-listener>
          <network-listener protocol="http-listener-2" port="8181" name="http-listener-2" thread-pool="http-thread-pool" transport="tcp"></network-listener>
          <network-listener protocol="admin-listener" port="4848" name="admin-listener" thread-pool="admin-thread-pool" transport="tcp"></network-listener>
        </network-listeners>
        <transports>
          <transport name="tcp"></transport>
        </transports>
      </network-config>
```

**Comment by dorpsidioot** [comment] 2017-01-20 14:12
Ok, I've gone further down the rabbit hole:
Testing with curl with html/js/css files => gzip encoding enabled
Testing with chrome (and checking using dev tools network/audit) : no compression
I'm checking futher because it's really annoying the hell out of me =)

**Comment by lprimak** [comment] 2017-01-20 20:53
So, are you saying it works with curl for you but doesn't work with chrome?

**Comment by noamichael** [comment] 2017-02-01 14:06
@dorpsidioot I see the same behavior: no compression in chrome.

**Comment by lprimak** [comment] 2017-02-01 23:53
@noamichael can you try to reproduce this with curl?

**Comment by lprimak** [comment] 2017-02-07 21:14
@dorpsidioot @noamichael Still cannot reproduce.
Tried it with Chrome, and here are the request / response headers.
The response is coming in compressed.

![chromeheaders](https://cloud.githubusercontent.com/assets/1002484/22711784/100bce8e-ed48-11e6-8545-ac0547c7f71a.png)

**Comment by mikecroft** [comment] 2017-02-07 21:49
@lprimak I notice that the sample output from @dorpsidioot above was from Payara 162 - I know we've upgraded Grizzly versions a couple of times since then, could the issue only be in earlier versions?

@dorpsidioot @noamichael have you tried with the latest versions of Payara? The prerelease version in the screenshot above can be downloaded here:
http://www.payara.fish/upstream_builds

The only thing I can think is that there may be differences in versions/platforms of Chrome, otherwise.

**Comment by lprimak** [comment] 2017-02-07 21:52
@mikecroft he says he tried .164, but you very well could be right here.

**Comment by lprimak** [comment] 2017-03-21 22:05
@dorpsidioot @noamichael have you tried it with the latest Payara?

**Comment by dorpsidioot** [comment] 2017-03-22 07:55
Must be magic but tested 171 yesterday evening and was about to shout out that the problem no longer exists in 4.1.171. Ticket may be closed!

**Comment by lprimak** [comment] 2017-03-22 16:09
Glad to hear it, will close the ticket

**Closed by lprimak** 2017-03-22 16:09 UTC
Labels: 1:Wait, cannot reproduce, requestor unresponsive (1), Test Case Required

**Comment by sameencse** [comment] 2017-07-04 16:47
I am getting the similar issue even in payara 172&173 snapshot ..looks like this is not fixed created ticket as well https://github.com/payara/Payara/issues/1739
