### ISSUE TITLE
Enabling TLS 1.3 makes payara stop responding after a few requests/seconds

### ISSUE THREAD

**Issue by SammyA** [payara/Payara#4369] opened 2019-12-05 12:16 UTC
Enabling TLS 1.3 breaks https listener
----------
After a short while, the https port stops responding

## Expected Outcome

`curl -fsSLk https://localhost:8181` should return the payara default index page

## Current Outcome

After a couple of requests, payara stops responding on the https port. http port (8080) still works.

## Steps to reproduce (Only for bug reports) 

- create a new clean default domain, and start it.
- `asadmin --port=4848 set 'configs.config.server-config.network-config.protocols.protocol.http-listener-2.ssl.tls13-enabled=true'
- stop and start the domain
- run `curl -fsSLk https://localhost:8181` repeatedly. after a couple tries, payara stops responding.

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: azul zulu 11 (Zulu11.35+15-CA build 11.0.5+10-LTS)
- **Operating System**: linux
- **Database**: n/a

**Comment by rdebusscher** [comment] 2019-12-06 09:07
Hi @SammyA 

I could reproduce this also on Oracle JDK 11 (Mac) and it seems there is an infinite loop 
 >at sun.security.ssl.SSLEngineImpl.writeRecord(java.base@11/SSLEngineImpl.java:255)

We will investigate this further if the problem lies with OpenJDK, Grizzly (how we use SSL code) or client (since there seems no issue when using Chrome, only curl)

Regards
Rudy

**Comment by SammyA** [comment] 2020-08-20 10:50
Tested again with latest Azul Zulu jdk version 11.0.8 (Zulu11.41+23-CA) and could no longer reproduce. Went back to the previous azul zulu 11.0.7, still hangs.

BTW, I noticed that in 5.2020.4 the TLS1.3 setting is no longer available from the admin webinterface (Configurations/server-config/HTTP Service/Http Listeners/http-listener-2/SSL)?

**Comment by AlanRoth** [comment] 2020-11-11 11:50
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:50 UTC
Labels: investigating, reproducible
