### ISSUE TITLE
Observer method of @Initialized(ApplicationScoped.class) that uses @PersistenceContext fails /CUSTCOM-99

### ISSUE THREAD

**Issue by serdroid** [payara/Payara#3453] opened 2018-11-29 06:43 UTC
# Description #
----------

I have developed a code that observing CDI event, initalization of javax.enterprise.context.ApplicationScoped class. That code deals with persistence context and load some data from database. I am getting this exception while calling this method.

```
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:Exception attempting to inject Env-Prop: info.serdroid.ionia.CountryDao/entityManager@Field-Injectable Resource. Class name = info.serdroid.ionia.CountryDao Field name=entityManager@java.lang.String@@@ into class info.serdroid.ionia.CountryDao: Lookup failed for 'java:comp/env/info.serdroid.ionia.CountryDao/entityManager' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} -- Exception attempting to inject Env-Prop: info.serdroid.ionia.CountryDao/entityManager@Field-Injectable Resource. Class name = info.serdroid.ionia.CountryDao Field name=entityManager@java.lang.String@@@ into class info.serdroid.ionia.CountryDao: Lookup failed for 'java:comp/env/info.serdroid.ionia.CountryDao/entityManager' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}
	at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:194)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)
```

## Expected Outcome
I think it should inject PersistenceContext properly.
## Current Outcome

Both payara and payara-micro behave same. I am evaluating Payara for a while and I think it is pretty good. I am currently using wildfly and trying to move some projects to payara. This sample code works fine on wildfly. I tried on wildfly versions 10.1.0.Final, 12.0.0.Final, 13.0.0.Final. Wildfly fires this event after ServletContext initialization completed. I guess payara fires event before persistence context initialization.
I have developed a version based on javax.ejb.Startup and that works fine. You could evaluate this version on ejb branch.

Is this a bug or do I misuse this feature?

## Steps to reproduce (Only for bug reports) 
I have developed a sample reproducer application. The link is in the samples section.
### Samples
https://github.com/serdroid/ionia.git

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full/Web/Micro
- **JDK Version**: Oracle JDK 1.8.0_172-b11
- **Operating System**: Linux
- **Database**: H2, Sybase

**Comment by OndroMih** [comment] 2019-03-14 12:09
Thank you for the reproducer. I was able to reproduce the issue with it. It seems that the CDI event is triggered prematurely, before the datasource is registered in the JNDI tree.

When I used a Singleton EJB with `@Startup` annotation, all works as expected:

```
@javax.ejb.Singleton
@Startup
public class StartUp {

    @Inject CountryCache cache;
    
    @PostConstruct
    public void start() {
        cache.load();
    }
}
```

And removed `@Observes` in `CountryCache`:

```
@ApplicationScoped
public class CountryCache {

...

	public void load() {
		System.out.println("---- MenuCache#reload ----");
...
	}
	
}
```

**Comment by smillidge** [comment] 2019-10-26 21:32
@OndroMih is there a JIRA associated with this or is the workaround sufficient. I note this is an enhancement.

**Comment by rdebusscher** [comment] 2019-12-18 07:32
I have created issue `CUSTCOM-99`. It has a low priority since there is a workaround.

**Comment by AlanRoth** [comment] 2020-11-11 11:26
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:26 UTC
Labels: enhancement, reproducible, status:accepted
