### ISSUE TITLE
EJB Container loging lack of information / CUSTCOM-216

### ISSUE THREAD

**Issue by vkalayda** [payara/Payara#2284] opened 2018-01-17 08:30 UTC
# Description #
----------
Lack of detailed information in logs.

## Expected Outcome

Detailed information in logs. Not just "ejb.stateless_ejbcreate_exception" message, with this message is very difficult to understand the cause of the error.

You can spend half a day to look through dozens of components to find the root cause :)

## Current Outcome

I have misconfigured component (bean) with timer, without required resources, such as JNDI variables and i got every 5 seconds in logs i got following:

2018-01-17T10:16:05.992+0200] [Payara 4.1] [SEVERE] [] [javax.enterprise.ejb.container] [tid: _ThreadID=182 _ThreadName=__ejb-thread-pool16] [timeMillis: 1516176965992] [levelValue: 1000] [[
  ejb.stateless_ejbcreate_exception]]

## Steps to reproduce (Only for bug reports) 

1. ./asadmin start-domain payaradomain

    EJB Container configuration

2. ./asadmin set server.ejb-container.steady-pool-size=10
3. ./asadmin set server.ejb-container.pool-idle-timeout-in-seconds=5

    Deploy application 

4. ./asadmin deploy ee-ejb-container-issue.war

After this every 5 seconds, you will get SEVERE record in the server logs.

### Samples

Source code to reproduce issue here https://github.com/vkalayda/ee-ejb-container-issue

## Environment ##

- **Payara Version**: 4.1.1.71
- **Edition**: Full
- **JDK Version**: 1.8.0u102 - Oracle.
- **Operating System**: Linux

**Comment by smillidge** [comment] 2018-01-17 16:14
Looks like a I18n properties file is missing. 
We'll try to reproduce.

**Comment by vkalayda** [comment] 2018-01-17 18:52
Hello, yes, this is the first reason. 
But I mean that detailed log with reason may help to understand - why the bean can't be instantiated.
In my case, this is missing JNDI variable.

**Comment by vkalayda** [comment] 2019-11-11 13:27
Hi guys, I am sorry for delay.

I try to reproduce this on the last Full version of Payara - 5.193.1.

There are two cases.

[ First case ]

 In this case, JNDI variable not exists and I try to deploy the application.
 Behaviour is correct, i mean that server write to logs detailed information:

 
 [2019-11-11T15:09:22.556+0200] [Payara 5.193] [SEVERE] [AS-DEPLOYMENT-00026] [javax.enterprise.system.tools.deployment.dol] [tid: _ThreadID=178 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1573477762556] [levelValue: 1000] [[
  JNDI lookup failed for the resource: Name: java:module/env/com.test.prototype.SchedulerBean/testVariable, Lookup: jndi/testVariable, Type: java.lang.String.]]

 [2019-11-11T15:09:22.557+0200] [Payara 5.193] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=178 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1573477762557] [levelValue: 1000] [[
  JNDI lookup failed for the resource: Name: [java:module/env/com.test.prototype.SchedulerBean/testVariable], Lookup: [jndi/testVariable], Type: [java.lang.String]]]
 
  From this information, I am able to understand what happened and how to manage this issue.
 
[ Second case ]

 1. In this case, the application was deployed and I did reconfiguration - delete "jndi/testVariable" JNDI.
 2. After this I restarted the payara domain, the application was successfully deployed, but every 5 seconds I have following error in logs.
 
 
 [2019-11-11T15:12:56.930+0200] [Payara 5.193] [SEVERE] [] [javax.enterprise.ejb.container] [tid: _ThreadID=177 _ThreadName=__ejb-thread-pool2] [timeMillis: 1573477976930] [levelValue: 1000] [[
  ejb.stateless_ejbcreate_exception]]
  
 As I wrote earlier, no one can't understand from this message what happens and how to manage this issue. There is no information at all such as in the first case.

**Comment by vkalayda** [comment] 2020-02-10 14:17
Hello @OndroMih as you can understand the main issue is that deployed application without required resources "in this case is JNDI", was successfully deployed after restarting of payara.

>> After this I restarted the payara domain, the application was successfully deployed, but every 5 seconds I have following error in logs.

This depends on  EJB container settings, EJB container try to initialize pool with EJB Stateless bean instances. But during instantiation got the error - because JNDI not found.

Thank you.

**Comment by OndroMih** [comment] 2020-03-03 16:18
Hi @vkalayda, I was able to reproduce with Payara Server 5.201. I agree that the best option would be that the app isn't deployed upon restart if required JNDI resources are missing and should be disabled. We'll see how complicated it would be to do that.

**Comment by OndroMih** [comment] 2020-03-24 17:44
Our engineers will have a look at this to see if we can come with an improvement

**Comment by AlanRoth** [comment] 2020-11-11 10:57
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 10:57 UTC
Labels: status:accepted
