### ISSUE TITLE
Bug Report: Payara Embedded Web always return 404 not found on any GET request

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#6264] opened 2023-04-16 14:43 UTC
### Brief Summary

After bootstrapping Payara Embedded Web, ports 8080, 8181, 4848 are bound but return 404 on any GET request.

### Expected Outcome

Port 4848 should serve Payara Admin, port 8080 should serve application using HTTP, port 8181 should serve application using HTTPS.

### Current Outcome

Any GET on port 4848, 8080 and 8181 report 404 not found.

Console looks like this:
```
Apr 16, 2023 2:35:33 PM com.sun.enterprise.v3.server.CommonClassLoaderServiceImpl findH2Client
INFO: Cannot find h2db client jar file, h2 jdbc driver will not be available by default.
Apr 16, 2023 2:35:33 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator null
Apr 16, 2023 2:35:34 PM com.hazelcast.instance.impl.HazelcastInstanceFactory
WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
Apr 16, 2023 2:35:34 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [development] [5.1.1] Using bind address: 0.0.0.0/0.0.0.0:4900
Apr 16, 2023 2:35:34 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [development] [5.1.1] Using public address: /10.0.5.2:4900
Apr 16, 2023 2:35:34 PM com.hazelcast.system.logo
INFO: [10.0.5.2]:4900 [development] [5.1.1] 
        +       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
        + +   + +  |    |    / \       /  |      |     /         / \    |         |   
        + + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
        + +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
        +       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
Apr 16, 2023 2:35:34 PM com.hazelcast.system
INFO: [10.0.5.2]:4900 [development] [5.1.1] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
Apr 16, 2023 2:35:34 PM com.hazelcast.system
INFO: [10.0.5.2]:4900 [development] [5.1.1] Hazelcast Platform 5.1.1 (20220317 - 5b5fa10) starting at [10.0.5.2]:4900
Apr 16, 2023 2:35:34 PM com.hazelcast.system
INFO: [10.0.5.2]:4900 [development] [5.1.1] Cluster name: development
Apr 16, 2023 2:35:34 PM com.hazelcast.system
INFO: [10.0.5.2]:4900 [development] [5.1.1] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
Apr 16, 2023 2:35:34 PM com.hazelcast.system
INFO: [10.0.5.2]:4900 [development] [5.1.1] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
Apr 16, 2023 2:35:35 PM com.hazelcast.system.security
INFO: [10.0.5.2]:4900 [development] [5.1.1] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
Apr 16, 2023 2:35:35 PM com.hazelcast.instance.impl.Node
INFO: [10.0.5.2]:4900 [development] [5.1.1] Using Discovery SPI
Apr 16, 2023 2:35:35 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [10.0.5.2]:4900 [development] [5.1.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Apr 16, 2023 2:35:35 PM com.hazelcast.core.LifecycleService
INFO: [10.0.5.2]:4900 [development] [5.1.1] [10.0.5.2]:4900 is STARTING
Apr 16, 2023 2:35:35 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [10.0.5.2]:4900 [development] [5.1.1] [10.0.5.2]:5900 is added to the blacklist.
Apr 16, 2023 2:35:36 PM com.hazelcast.internal.cluster.ClusterService
INFO: [10.0.5.2]:4900 [development] [5.1.1] 

Members {size:1, ver:1} [
        Member [10.0.5.2]:4900 - a5db29f1-dfe5-4cac-aa0b-44959ba81442 this
]

Apr 16, 2023 2:35:36 PM com.hazelcast.internal.jmx.ManagementService
INFO: [10.0.5.2]:4900 [development] [5.1.1] Hazelcast JMX agent enabled.
Apr 16, 2023 2:35:36 PM com.hazelcast.core.LifecycleService
INFO: [10.0.5.2]:4900 [development] [5.1.1] [10.0.5.2]:4900 is STARTED
Apr 16, 2023 2:35:36 PM com.hazelcast.internal.partition.impl.PartitionStateManager
INFO: [10.0.5.2]:4900 [development] [5.1.1] Initializing cluster partition table arrangement...
Apr 16, 2023 2:35:36 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: Hazelcast Instance Bound to JNDI at payara/Hazelcast
Apr 16, 2023 2:35:36 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: JSR107 Caching Provider Bound to JNDI at payara/CachingProvider
Apr 16, 2023 2:35:36 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager
Apr 16, 2023 2:35:36 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener http-listener started in: 4ms - bound to [/0.0.0.0:8080]
Apr 16, 2023 2:35:37 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener https-listener started in: 1ms - bound to [/0.0.0.0:8181]
Apr 16, 2023 2:35:37 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener admin-listener started in: 1ms - bound to [/0.0.0.0:4848]
Apr 16, 2023 2:35:37 PM com.sun.enterprise.v3.services.impl.GrizzlyService postConstruct
INFO: Grizzly 4.0.0 started in: 2,688ms - bound to [http-listener:8080, https-listener:8181, admin-listener:4848]
Apr 16, 2023 2:35:38 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener iiop-service started in: 1ms - bound to [/0.0.0.0:3700]
Apr 16, 2023 2:35:38 PM fish.payara.nucleus.cluster.PayaraCluster logClusterStatus
INFO: Data Grid Status 
Payara Data Grid State: DG Version: 5 DG Name: development DG Size: 1
Instances: {
 DataGrid: development Name: server Lite: false This: true UUID: a5db29f1-dfe5-4cac-aa0b-44959ba81442 Address: /10.0.5.2:4900
}
Apr 16, 2023 2:35:38 PM com.sun.enterprise.v3.server.AppServerStartup postStartupJob
INFO: Undefined Product Name - define product and version info in config/branding 0.0.0 (0) startup time : Embedded (871ms), startup services(4,696ms), total(5,567ms)
Apr 16, 2023 2:35:38 PM fish.payara.nucleus.notification.NotificationService bootstrapNotificationService
INFO: Payara Notification Service bootstrapped.
Apr 16, 2023 2:35:38 PM org.glassfish.kernel.event.EventsImpl send
WARNING: Exception while dispatching an event
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.HashMap sun.net.www.protocol.jar.JarFileFactory.fileCache accessible: module java.base does not "opens sun.net.www.protocol.jar" to unnamed module @7037a37e
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at com.sun.enterprise.admin.util.JarFileUtils.closeCachedJarFiles(JarFileUtils.java:77)
        at fish.payara.nucleus.util.CleanupPostBoot.event(CleanupPostBoot.java:78)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.AppServerStartup.postStartupJob(AppServerStartup.java:434)
        at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:357)
        at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:237)
        at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:219)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:84)
        at eu.headcrashing.jaxrsdoneright.sebootstrap.PayaraDemo.main(PayaraDemo.java:14)
```

### Reproducer

This minimum reproducer reports port 4848 started, so it should serve Payara Admin (but it doesn't):
```java
public class PayaraDemo {

    public static final void main(String[] args) throws Throwable {
        var bootstrap = new BootstrapProperties();
        var runtime = GlassFishRuntime.bootstrap(bootstrap);
        var glassfishProperties = new GlassFishProperties();
        var glassfish = runtime.newGlassFish(glassfishProperties);
        glassfish.start();
    }
}
```
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>eu.headcrashing.jaxrsdoneright</groupId>
    <artifactId>payarademo</artifactId>
    <version>1</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>fish.payara.extras</groupId>
            <artifactId>payara-embedded-web</artifactId>
            <version>6.2023.3</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.10.1</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```
The same ready-to-run Maven project with this reproducer can be found here: https://gitlab.com/mkarg/jaxrs-done-right/-/tree/payarademo

### Operating System

Linux (Ubuntu 20.04.5 LTS)

### JDK Version

Temurin 19

### Payara Distribution

Payara Embedded Web

**Comment by fturizo** [comment] 2023-07-12 22:15
Greetings @mkarg,

Apologies for the delayed reply, this issue fell through the cracks. We have reviewed this issue and have confirmed that the current outcome is the expected outcome of Payara Embedded. 

Regarding the usage of port `4848`, Payara Embedded doesn't ship with the admin console (but it makes available the DAS through this port), which is why the listener reports as started but there are no resources to serve.

For ports `8080` and `8181`, Payara Embedded doesn't ship with default web pages for the root context root (like in the standard server), so a `404` error is to be expected as well. If you deploy an application after starting the embedded server you will be able to access it:

```
var glassfish = runtime.newGlassFish(glassfishProperties);

glassfish.start();

var artifact = new File(args[0]);
var deployer = glassfish.getDeployer();
deployer.deploy(artifact, "--contextRoot=/");
```

Executing an HTTP request to http://localhost:8080/ will get you access to the application deployed. We'll proceed to close this issue as there's no work to be done.

**Closed by fturizo** 2023-07-12 22:15 UTC
Labels: Type: Bug, Status: Open

**Comment by mkarg** [comment] 2023-07-13 21:13
@fturizo BTW, with Payara Embedded, is it essential to use the Payara API or can I instead bootstrap using the Jakarta REST SE Bootstrap API? Jersey works with SE Bootstrap API, so this should work, right?

**Comment by fturizo** [comment] 2023-07-14 22:02
@mkarg, if you are intending to use Payara Embedded to make JAX-RS services available, I'd say that would be enough since the Embedded server is a fully compatible Jakarta EE runtime, but if you want to approach the use of the Jakarta REST SE Bootstrap API, then you certainly don't require Payara Embedded, as you can bootstrap a different HTTP engine instead.

**Comment by mkarg** [comment] 2023-07-14 22:20
@fturizo As a Co-Author of the Jakarta REST Spec and inventor of the Jakarta REST SE Bootstrap API my intention is to find out whether Payara Embedded supports it or not.
