### ISSUE TITLE
"IllegalArgumentException: Can not set [EJB interface] field [managed bean field] to com.sun.proxy.$Proxy[some number]" with <class-loader delegate="false"/>

### ISSUE THREAD

**Issue by krichter722** [payara/Payara#2237] opened 2018-01-02 18:55 UTC
# Description #
----------

Setting `<class-loader delegate="false"/>` in a `glassfish-web.xml` of a web module of a Java EE project causes `java.lang.IllegalArgumentException: Can not set [EJB interface] field [managed bean field] to com.sun.proxy.$Proxy[some number]`, e.g. `java.lang.IllegalArgumentException: Can not set richtercloud.payara.classloading.proxy.issue.jar.InitService field richtercloud.payara.classloading.proxy.issue.jar.Init.initService to com.sun.proxy.$Proxy341`, when injecting an EJB into an application scoped JSF managed bean with eager loading. See https://gitlab.com/krichter/payara-classloading-proxy-issue/-/jobs/46473894 for the GitLab CI output and the reference to a MCVE.

#1249 contains a hint about removing "jax-ws Metro libs" which I don't understand fully and don't know how to test.

## Expected Outcome

The injection should work or a clear, understandable error message explaining the reason for the failure should be given - ideally as user [I wouldn't have to think what to do next](https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think).

## Current Outcome

```
[2018-01-02T18:27:34.028+0000] [Payara 4.1] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.config] [tid: _ThreadID=54 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1514917654028] [levelValue: 1000] [[
  Critical error during deployment: 
com.sun.faces.mgbean.ManagedBeanCreationException: An error occurred performing resource injection on managed bean init
	at com.sun.faces.mgbean.BeanBuilder.injectResources(BeanBuilder.java:209)
	at com.sun.faces.mgbean.BeanBuilder.build(BeanBuilder.java:101)
	at com.sun.faces.mgbean.BeanManager.createAndPush(BeanManager.java:409)
	at com.sun.faces.mgbean.BeanManager.create(BeanManager.java:269)
	at com.sun.faces.mgbean.BeanManager.create(BeanManager.java:256)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:259)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:4991)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:574)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5560)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:522)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2099)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1745)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:501)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:508)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:407)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:173)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.faces.spi.InjectionProviderException: com.sun.enterprise.container.common.spi.util.InjectionException: Exception attempting to inject Local ejb-ref name=richtercloud.payara.classloading.proxy.issue.jar.Init/initService,Local 3.x interface =richtercloud.payara.classloading.proxy.issue.jar.InitService resolved to intra-app EJB DefaultInitService in module payara-classloading-proxy-issue-ejb-1.0-SNAPSHOT.jar,ejb-link=payara-classloading-proxy-issue-ejb-1.0-SNAPSHOT.jar#DefaultInitService,lookup=,mappedName=,jndi-name=,refType=Session into class richtercloud.payara.classloading.proxy.issue.jar.Init: Can not set richtercloud.payara.classloading.proxy.issue.jar.InitService field richtercloud.payara.classloading.proxy.issue.jar.Init.initService to com.sun.proxy.$Proxy227
	at org.glassfish.faces.integration.GlassFishInjectionProvider.inject(GlassFishInjectionProvider.java:194)
	at com.sun.faces.mgbean.BeanBuilder.injectResources(BeanBuilder.java:203)
	... 80 more
Caused by: com.sun.enterprise.container.common.spi.util.InjectionException: Exception attempting to inject Local ejb-ref name=richtercloud.payara.classloading.proxy.issue.jar.Init/initService,Local 3.x interface =richtercloud.payara.classloading.proxy.issue.jar.InitService resolved to intra-app EJB DefaultInitService in module payara-classloading-proxy-issue-ejb-1.0-SNAPSHOT.jar,ejb-link=payara-classloading-proxy-issue-ejb-1.0-SNAPSHOT.jar#DefaultInitService,lookup=,mappedName=,jndi-name=,refType=Session into class richtercloud.payara.classloading.proxy.issue.jar.Init: Can not set richtercloud.payara.classloading.proxy.issue.jar.InitService field richtercloud.payara.classloading.proxy.issue.jar.Init.initService to com.sun.proxy.$Proxy227
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:740)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.inject(InjectionManagerImpl.java:507)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectInstance(InjectionManagerImpl.java:170)
	at org.glassfish.faces.integration.GlassFishInjectionProvider.inject(GlassFishInjectionProvider.java:184)
	... 81 more
Caused by: java.lang.IllegalArgumentException: Can not set richtercloud.payara.classloading.proxy.issue.jar.InitService field richtercloud.payara.classloading.proxy.issue.jar.Init.initService to com.sun.proxy.$Proxy227
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:688)
	... 84 more
]]
```

## Steps to reproduce (Only for bug reports) 

see `.gitlab-ci.yml` in MCVE

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full
- **JDK Version**: 8 u151 - OpenJDK
- **Operating System**: Linux
- **Database**: Apache Derby embedded

**Comment by krichter722** [comment] 2018-01-02 20:32
I can work around this issue by replacing `@ManagedBean` with `@Named`, however the feedback isn't useful and I don't understand why the workaround works.

**Comment by lprimak** [comment] 2018-01-02 22:09
Can you post the code where this is happening?

**Comment by krichter722** [comment] 2018-01-02 22:14
> Can you post the code where this is happening?

The last statement in `.gitlab-ci.yml` in the self-contained example. The deployment with `asadmin` fails because of the failing injection. The example and the GitLab CI should allow to reproduce the problem. Does that work for you?

**Comment by lprimak** [comment] 2018-01-02 23:33
I believe this is an upstream issue.  This would not be of high priority because JSF ManagedBeans are deprecated in favor of CDI managed beans

**Comment by krichter722** [comment] 2018-01-03 12:34
> I believe this is an upstream issue. This would not be of high priority because JSF ManagedBeans are deprecated in favor of CDI managed beans

@lprimak Trying to create a MCVE for another issue, I could reproduce the issue with CDI managed beans. The project is https://gitlab.com/krichter/jee-slf4j-logging. I'd appreciate feedback if you can reproduce the issue as well. Otherwise I'll set up a reproduction scenario on GitLab CI like above.

I see `Exception attempting to inject Local ejb-ref name=richtercloud.jee.slf4j.logging.jar.MyManagedBean/myController,Local 3.x interface =richtercloud.jee.slf4j.logging.jar.MyController resolved to intra-app EJB DefaultMyController in module jee-slf4j-logging-ejb-1.0-SNAPSHOT.jar,ejb-link=jee-slf4j-logging-ejb-1.0-SNAPSHOT.jar#DefaultMyController,lookup=,mappedName=,jndi-name=,refType=Session into class richtercloud.jee.slf4j.logging.jar.MyManagedBean: Can not set richtercloud.jee.slf4j.logging.jar.MyController field richtercloud.jee.slf4j.logging.jar.MyManagedBean.myController to com.sun.proxy.$Proxy240` when I open http://localhost:8080/jee-slf4j-logging-web/ with Payara 4.1.2.174 Full version. The injection is performed using `@EJB` in a `@Named @javax.faces.view.ViewScoped` JSF backing bean (see project for details).

**Comment by krichter722** [comment] 2018-01-03 14:23
I created a reproduction with `.gitlab-ci.yml` and details of it can be found at https://gitlab.com/krichter/jee-slf4j-logging/-/jobs/46560402.

**Comment by krichter722** [comment] 2018-01-06 10:26
The issue here seems that the JAR containing the EJB interfaces added as dependency to the WAR should have a `provided` scope, otherwise the EJB interfaces are in more than one JAR instead of just the EAR `lib` directory.

The feedback still needs to be improved here imo.

**Comment by krichter722** [comment] 2018-01-07 20:41
The issue here occurs if either

  * the JAR containing the EJB interfaces added as dependency to the WAR should have a `provided` scope, otherwise the EJB interfaces are in more than one JAR instead of just the EAR `lib` directory
  * or `@Named @javax.faces.view.ViewScoped` is used instead of `@Named @javax.faces.bean.ViewScoped` or `@Named @javax.enterprise.context.ApplicationScoped` instead of
`@Named @javax.faces.bean.ApplicationScoped` on JSF managed bean.

The feedback still needs to be improved here imo, so this issue should be left open.

**Comment by krichter722** [comment] 2018-01-13 02:19
I created SSCCE for Payara 5.x SNAPSHOT and for GlassFish 5.0 on the `payara-5` and `glassfish-5` branches of the referenced project.

I filed a report against GlassFish 5.0 at https://github.com/javaee/glassfish/issues/22401.

**Comment by krichter722** [comment] 2018-01-16 20:41
This is caused by `compile` Maven scope of the JAR module in the WEB module which leads injection point declarations to be not a superclass of their implementation which is correct after they've been loaded by different class loaders. It can be fixed by changing the scope to `provided`.

I leave this open to get a statement from devs whether they see any possibility to improve the feedback here and put it on their schedule. That being said I'm fine with the issue being closed that statement.

**Comment by michaelranaldo** [comment] 2018-01-17 17:47
Hi @krichter722 ,

Thanks for keeping us updated with this. I've created internal issue PAYARA-2407 for someone to look in to this to see if it would be possibly on our end to improve the feedback from this kind of error.

**Comment by lprimak** [comment] 2018-01-18 03:10
Thanks for your hard work and reproducer to figure this out.  As @michaelranaldo said, we have an internal issue to track this.

**Comment by fturizo** [comment] 2020-02-06 18:27
Closing this request as it is considerably old and there's a clear solution to the issue even if the internal logging of the server is not. Feel free to raise a new issue if the problem is still present in the current release of Payara Server 5.x and give recommendations on how the improvement should work.

**Closed by fturizo** 2020-02-06 18:27 UTC
