### ISSUE TITLE
HTTP DELETE containing payload or form data results in response 400 'Bad request'

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara#1545] opened 2017-04-20 19:20 UTC
# Description #
----------
This is mainly a feature request:

When the payara server is called with HTTP DELETE request containing a payload or form which results in a Content-Length > 0 a HTTP response 400 'Bad request' is returned.

## Expected Outcome

Concerning the HTTP 1.1 spec it is undefined what should happen if this occurs but its generally not forbidden. Glassfish/Grizzly has a configuration option which may allow such requests. By default this is deactivated but it would be really nice to have this configuration option in Payara available. The following Glassfish ticket deals with this: https://java.net/jira/browse/GLASSFISH-21238

## Current Outcome

Response HTTP 400 will always be returned.

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 1.8.0_121
- **Operating System**: Mac, Linux

**Comment by smillidge** [comment] 2017-04-22 20:25
Fix for GLASSFISH-21238 is already in the Payara code.

It should be configurable via asadmin;

`asadmin set configs.config.default-config.network-config.protocols.protocol.http-listener-1.http.allow-payload-for-undefined-http-methods=true`

It does need the admin console editing to show it in the admin console.

**Comment by svendiedrichsen** [comment] 2017-04-23 14:19
If I'm not mistaken in the comments of GLASSFISH-21238 the dev talks about the fact that it has not been fixed in GF 4.1.1 instead it has been ported back to 4.1.2. Did you cherry pick it for Payara because the issue is in state REOPENDED?

**Comment by smillidge** [comment] 2017-04-23 15:48
We regularly keep Payara up to date and did the required cherry pick a while back.

**Comment by svendiedrichsen** [comment] 2017-04-23 18:53
Thanks for your time and patience.

**Comment by svendiedrichsen** [comment] 2017-05-30 09:53
When I do the proposed amendments using the asadmin command I receive a 403/Forbidden response. I have a little WAR prepared to provoke the problem.

You will find an index.html under /payara.

[test-delete-html-1.0-SNAPSHOT.war.zip](https://github.com/payara/Payara/files/1037880/test-delete-html-1.0-SNAPSHOT.war.zip)

**Comment by fturizo** [comment] 2017-06-24 21:26
@svendiedrichsen, you are correct. This bug is still present on the current version of Payara Server. I've created the internal issue `PAYARA-1791` so the developers can take a look to it.

**Comment by fturizo** [comment] 2017-07-06 00:22
Greetings @svendiedrichsen, the developers have tested this behaviour and found no problems with the way the Grizzly HTTP listener is configured. I've tested a sample REST application and got a **204-No Content** response after setting the property of the listener. With your test application, I'm indeed getting a **403 - Forbidden**. Could you attach the code for your application configuration class and the REST endpoint to give it a look?

**Comment by timbrody** [comment] 2017-07-20 08:05
I have recently encountered this issue (DELETE with body) and can confirm that on version 172 and allow-payload-for-undefined-http-methods set to true Payara passes the request through to the Web app.

For the benefit of others, ensure allow-payload-for-undefined-http-methods is set on the http listener actually in use - the example from @smillidge is for setting the default config.

e.g. for my server the setting is

```
set configs.config.server-config.network-config.protocols.protocol.http-protocol.http.allow-payload-for-undefined-http-methods=true
```

```xml
          <protocol name="http-protocol">
            <http xpowered-by="false" allow-payload-for-undefined-http-methods="true" default-virtual-server="server">
              <file-cache></file-cache>
            </http>
          </protocol>
```

**Comment by fturizo** [comment] 2017-07-20 16:47
Considering that we haven't received a reply for @svendiedrichsen and the behaviour of the Grizzly option is working as intended we'll close the issue for the moment.

**Closed** 2017-07-20 16:47 UTC
Labels: c:Misconfiguration
