### ISSUE TITLE
Bug Report:Payara 6.2023.7 version is not compatible and working with JDK-17 

### ISSUE THREAD

**Issue by ojuschugh1** [payara/Payara#6361] opened 2023-08-14 19:43 UTC
### Brief Summary

I am trying to run the Eclipse cargo tracker project on the Payara 6 server's latest release version 6.2023.7. I am using JDK-17, after cleaning and packaging when I try to run the cargo tracker.war file on the Payara server. It leads to deployment errors. Then I tested it with JDK-11, and it works fine with it. I think that there is still a compatibility issue between  Payara 6.2023.7 version with JDK-17

### Expected Outcome

Proper working of Payara 6.2023.7 with JDK-17

### Current Outcome

Compatibility issue in Payara 6.2023.7 version with JDK-17

`[INFO] [talledLocalContainer] Parsed GlassFish version = [6.2023.7]
[INFO] [talledLocalContainer] Payara 6.2023.7 starting...
[INFO] [talledLocalContainer] Attempting to start cargo-domain.... Please look at the server log for more details.....
[INFO] [talledLocalContainer] Payara 6.2023.7 is stopping...
[INFO] [talledLocalContainer] Payara 6.2023.7 is stopped
[WARNING] [talledLocalContainer] org.codehaus.cargo.util.CargoException: At least one GlassFish deployment has failed: org.codehaus.cargo.util.CargoException: GlassFish admin command with args (--interactive=false --host localhost --port 4848 --user admin --passwordfile C:\Users\ojus\Desktop\c10\cargotracker\target\cargo\configurations\payara\password.properties deploy --force --contextroot cargo-tracker C:\Users\ojus\Desktop\c10\cargotracker\target\cargo-tracker.war) failed: asadmin exited 1: remote failure: Error occurred during deployment: Exception while loading the app. Please see server.log for more details.
Command deploy failed.
[ERROR] Starting container [org.codehaus.cargo.container.payara.PayaraInstalledLocalContainer@53e6c75c] failed
org.codehaus.cargo.util.CargoException: At least one GlassFish deployment has failed: org.codehaus.cargo.util.CargoException: GlassFish admin command with args (--interactive=false --host localhost --port 4848 --user admin --passwordfile C:\Users\ojus\Desktop\c10\cargotracker\target\cargo\configurations\payara\password.properties deploy --force --contextroot cargo-tracker C:\Users\ojus\Desktop\c10\cargotracker\target\cargo-tracker.war) failed: asadmin exited 1: remote failure: Error occurred during deployment: Exception while loading the app. Please see server.log for more details.
Command deploy failed.`

### Reproducer

Use JDK-11 if you are using Payara 6.2023.7 version 

### Operating System

Windows 10

### JDK Version

17

### Payara Distribution

Payara Server Full Profile

**Comment by lprimak** [comment] 2023-08-14 20:51
Duplicate of #6344 (see workaround there)

**Comment by shub8968** [comment] 2023-08-15 17:33
Closing as duplicate of https://github.com/payara/Payara/issues/6344

**Closed by shub8968** 2023-08-15 17:33 UTC
Labels: Type: Bug, Status: Open
