### ISSUE TITLE
defaultManagedExecutorService thread-pool  does not scale in 5.184 - PAYARA-3507

### ISSUE THREAD

**Issue by mb-dbc-dk** [payara/Payara#3751] opened 2019-02-20 07:51 UTC
# When running multiple tasks in the defaultManagedExecutorService onmly `core-size` tasks are processed in parallel
 ----------

When starting a war that submits multiple tasks, to a MES, only 2 are run in parallel

## Expected Outcome

When adding more than 2 (and less than 200) tasks all should be processed in parallel

## Current Outcome

2 tasks complete, then the next 2 are started up

## Steps to reproduce (Only for bug reports) 

1 -** Get the example

     git clone https://github.com/DBCDK/payara-micro-5.184-thread-pool.git

2 -** Run the example

    mvn package payara-micro:start

3 -** See the tasks queued, and only 2 processed at the time

### Samples

[github](https://github.com/DBCDK/payara-micro-5.184-thread-pool.git)

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Micro
- **JDK Version**: Oracle 1.8.0_181-b13
- **Operating System**: Linux

**Comment by rdebusscher** [comment] 2019-02-20 13:54
Hi Morton,

We are already aware of this and are planning to change the default configuration for the Managed Executor service.

You can change Thread pool by putting the following commands in a file and specify it as prebootcommandfile (see [this documentation](https://docs.payara.fish/documentation/payara-micro/asadmin/pre-and-post-boot-scripts.html))

    set resources.managed-executor-service.concurrent/__defaultManagedExecutorService.core-pool-size=0
    set resources.managed-executor-service.concurrent/__defaultManagedExecutorService.hung-after-seconds=0
    set resources.managed-executor-service.concurrent/__defaultManagedExecutorService.keep-alive-seconds=60
    set resources.managed-executor-service.concurrent/__defaultManagedExecutorService.long-running-tasks=false
    set resources.managed-executor-service.concurrent/__defaultManagedExecutorService.task-queue-capacity=2147483647
    set resources.managed-executor-service.concurrent/__defaultManagedExecutorService.maximum-pool-size=2147483647

This makes the thread pool unlimited.

The cause of this is the implementation within the JDK (see [here](https://dzone.com/articles/scalable-java-thread-pool-executor) for an explanation)

**Comment by smillidge** [comment] 2019-02-21 20:11
defaults are pretty tricky for this. Too many threads and people that don't use it will complain too few and you get an issue like this. As Rudy points out it is tunable, not sure what the default should be. Perhaps a commandline flag to set it?

**Comment by OndroMih** [comment] 2019-03-14 09:21
This is already fixed in 5.191 by #3759 with setting core pool size to 0.

There's a more profound flaw in how executors work which causes this issue for core pool size greater than 0 - the executor will put tasks first into the queue before using more threads than core pool size. We plan to address this in the future so that the executor first uses available threads up to max pool size and then puts them on the queue. However, we have no roadmap for it. If you'd like to track it, please raise a separate github issue.

I'm closing this issue as it's now resolved in 5.191

**Closed by OndroMih** 2019-03-14 09:21 UTC
Labels: 2:WithDev, c:Misconfiguration, payara-micro
