### ISSUE TITLE
Granted policy not correctly generated on 164

### ISSUE THREAD

**Issue by itservices-trust** [payara/Payara#1219] opened 2016-12-05 10:20 UTC
After deploy an application with "default principal to role mapping" enabled, the granted.policy file under generated/policy did not show the grants for the secured part
As result, I can access the application (I can see the "login successful" log) but I'll be routed to an error page (in log I can see isGranted=false)
----------

No error are shown in logs (I don't know which logs I can set to a finer policy to have more information)

## Expected Outcome

The same application deployed in a payara 163 version generate, among others, those lines
`grant      principal org.glassfish.security.common.Group "DMLM_USER" {
  permission javax.security.jacc.WebResourcePermission "/*:/stylesheets/*:/images/*:/javax.faces.resource/*:/assets/*:/uploadfiles.jsp:/fileupload1.jsp";
  permission javax.security.jacc.WebRoleRefPermission "uploadfiles", "DMLM_USER";
  permission javax.security.jacc.WebRoleRefPermission "jsp", "DMLM_USER";
  permission javax.security.jacc.WebRoleRefPermission "", "DMLM_USER";
  permission javax.security.jacc.WebRoleRefPermission "default", "DMLM_USER";
  permission javax.security.jacc.WebRoleRefPermission "Faces Servlet", "DMLM_USER";
};`

where DMLM_USER is our security role name

## Current Outcome

no one of the lines above appear if I deploy into a payara 164 version

## Steps to reproduce (Only for bug reports) 

With the domain started and the "Default Principal To Role Mapping " enabled in tab security, deploy and application that have the following web.xml (security part snippet, pull out filter part, context,servlet,session-config,mime.mapping and error-page)
`    <security-constraint>
        <display-name>Free pages</display-name>
        <web-resource-collection>
            <web-resource-name>free to be used resources</web-resource-name>
            <description/>
            <url-pattern>/javax.faces.resource/*</url-pattern>
            <url-pattern>/assets/*</url-pattern>
            <url-pattern>/images/*</url-pattern>
            <url-pattern>/stylesheets/*</url-pattern>
        </web-resource-collection>
        <web-resource-collection>
            <web-resource-name>Upload file receivers</web-resource-name>
            <description/>
            <url-pattern>/uploadfiles.jsp</url-pattern>
            <url-pattern>/fileupload1.jsp</url-pattern>
        </web-resource-collection>
    </security-constraint>
    <security-constraint>
        <display-name>Protected Area</display-name>
        <web-resource-collection>
            <web-resource-name>all</web-resource-name>
            <description/>
            <url-pattern>/*</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <description/>
            <role-name>DMLM_USER</role-name>
        </auth-constraint>
    </security-constraint>
    <distributable/>
    <login-config>
        <auth-method>FORM</auth-method>
        <realm-name>dmlmSecurity</realm-name>
        <form-login-config>
            <form-login-page>/login.xhtml</form-login-page>
            <form-error-page>/permissionDenied.xhtml</form-error-page>
        </form-login-config>
    </login-config>
    <security-role>
        <description/>
        <role-name>DMLM_USER</role-name>
    </security-role>
`
nothing related to security in glassfish-web.xml

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**:  Full
- **JDK Version**: 8 101B13 - Oracle
- **Operating System**:  Linux

**Comment by itservices-trust** [comment] 2016-12-05 10:31
I've tried to add in glassfish-web.xml

  <security-role-mapping>
    <role-name>DMLM_USER</role-name>
    <group-name>DMLM_USER</group-name>
  </security-role-mapping>

and now the policy file is generated correctly
In version 163 it was unnecessarily

**Comment by smillidge** [comment] 2016-12-05 10:35
This is a known bug and will be fixed in 171 for opensource 164.1 for customers. See #1213

**Comment by smillidge** [comment] 2016-12-05 10:37
Duplicate of #1213

**Closed** 2016-12-05 10:36 UTC
Labels: duplicate

**Comment by itservices-trust** [comment] 2016-12-05 10:48
thanks
