### ISSUE TITLE
When alternatedocroot points to a location without WEB-INF/classes, vague error: "Failed to copy resources"

### ISSUE THREAD

**Issue by jskillin-idt** [payara/Payara#226] opened 2015-03-09 19:06 UTC
I had incorrectly set alternatedocroot to point at a directory which contained only web resources, but made it match all possible resources. When attempting to start this WAR on 4.1, I got a "Failed to copy resources" error. This error is almost useless, and had me scratching my head for quite a few days.

It'd be much more useful if the failure gave an explanation, especially since the reason for this failure has multiple sources.

(In my case, the WEB-INF/classes folder was not located in the alternatedocroot location, which is only an implied requirement in the documentation for this feature.)

**Comment by smillidge** [comment] 2015-03-11 21:57
Can you provide a little more detail on the directory structure in the war and your web.xml to figure out the configuration you had?

**Comment by jskillin-idt** [comment] 2015-03-19 13:50
The web resources lived in /webdir, and the project lived in /projdir. There was an ant /projdir/build.xml file that packaged the WAR with all the data in /webdir along with the usual compiled classes, XML, and libraries. If, however, you specified a flag, the build would exclude /webdir, and drop an alternatedocroot that matched "/*" to /webdir.

**Comment by fturizo** [comment] 2016-12-03 00:25
Greetings @jskillin-idt, we're sorry that we are coming back to you after this while. Is this issue still persisting with the newer releases of Payara Server? If so, could you attach the _glassfish-web.xml_ file to see if we can reproduce it?

**Comment by mikecroft** [comment] 2017-03-30 20:23
Closing since it looks like we don't have enough to go on to investigate properly.

**Closed by mikecroft** 2017-03-30 20:23 UTC
Labels: 1:Wait, c:Enhancement, requestor unresponsive (1), Test Case Required, try to reproduce
