### ISSUE TITLE
Node Host is required for type CONFIG

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#2256] opened 2018-01-11 14:09 UTC
# Description #
----------
If I create a new node with type CONFIG and leave empty field "Node Host", then instance start on that node fails.

## Expected Outcome
Instance starts without error.

## Current Outcome
Could not start instance xxxx on node xxx (null). This command requires connecting to node xxx (null) using SSH to complete its operation, but node xxx is not configured to use SSH. You may use update-node-ssh to configure node xxx to use SSH. To complete this operation run the following command locally on host null from the GlassFish install location null: lib/nadmin start-local-instance --node xxx --sync normal xxxx

## Steps to reproduce (Only for bug reports) 
1) create a new node with Type CONFIG (leave Node Host empty)
2) create cluster with instance on the node
3) try to start the instance

## Context (Optional)
Comment under the field "Node Host" says that "If the type is DCOM or SSH, the node host is required. ", so for CONFIG this field should be optional.

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full 
- **JDK Version**: 1.8.0_144 
- **Operating System**: RHEL 7 
- **Database**:

**Comment by smillidge** [comment] 2018-01-15 12:02
This is correct behaviour. You cannot start a config node instance from the administration console. You must log onto the machine and start it locally. Is this failing from admin console or failing when you run the command locally?

**Comment by sgflt** [comment] 2018-01-16 17:38
I probably should mention that all operations are executed on the single machine. So all commands don't leave "localhost".

Alternative steps with asadmin:
1) ./asadmin create-node-config test-node
2) ./asadmin create-instance --node test-node test-instance
3) ./asadmin start-instance test-instance

> remote failure: Could not start instance test-instance on node test-node (null).
> 
> This command requires connecting to node test-node (null) using SSH to complete its operation, but node test-node is not configured to use SSH. You may use update-node-ssh to configure node test-node to use SSH.
> 
> To complete this operation run the following command locally on host null from the GlassFish install location null:
> 
>  lib/nadmin  start-local-instance --node test-node --sync normal test-instance
> Command start-instance failed.

4) lib/nadmin  start-local-instance --node test-node --sync normal test-instance

> Server instance directory /opt/payara41/glassfish/nodes/test-node/test-instance does not exist or is not a directory
> Command start-local-instance failed.

To sum it up, the the CONFIG node is unusable if "Node host" field is empty even on single machine. If I fill "localhost" then I am able to start the instance from Admin GUI and by asadmin command.

**Comment by smillidge** [comment] 2018-01-17 16:20
If you are on the same machine as the DAS you do not need to create a new node the localhost-domain1 node will suffice

**Comment by sgflt** [comment] 2018-01-18 03:57
I agree, but I think the input description is still misleading.

**Comment by mikecroft** [comment] 2018-01-26 11:29
Closing as this is working as designed.

The description is correct, the node host is *not* required for `CONFIG` nodes due to the fact that instances on config nodes must be started from the remote node.

Payara cannot know in advance that a given node you create is local only and cannot assume that since an incorrect assumption could lead to unpredictability.

**Closed by mikecroft** 2018-01-26 11:29 UTC
Labels: c:Question
