### ISSUE TITLE
DerbyDB start fails in docker

### ISSUE THREAD

**Issue by AdamBien** [payara/Payara#1738] opened 2017-07-03 09:23 UTC
# Description #
----------

asadmin start-database fails on docker with the payara 172 (and earlier). Reason: Earlier DerbyDB versions have problems with "network drives". See: https://issues.apache.org/jira/browse/DERBY-6503 https://issues.apache.org/jira/browse/DERBY-6410 (got the same issue on Docker in CentOS)

## Solution

Upgrade derby (db-derby-10.12.1.1). Drop-in replacement seems to work. Tested with various apps. See working Dockerfile: https://github.com/AdamBien/docklands/blob/master/payara-with-derby/Dockerfile

## Expected Outcome

asadmin start-database works on docker

## Current Outcome

Start fails

## Steps to reproduce (Only for bug reports) 

    ./asadmin start-database within docker

## Environment ##

- **Payara Version**: *172
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: CentOS within docker running on Mac
- **Database**: DerbyDB

**Comment by mikecroft** [comment] 2017-07-03 09:34
Created `PAYARA-1817` to get Derby upgraded

**Comment by smillidge** [comment] 2017-07-03 10:25
Latest Derby versions are JDK 8 only. There is already a PR for this in Payara 5 branch.

**Comment by mikecroft** [comment] 2017-07-03 10:33
Also looks like a backport isn't an option:

> I agree it is wise for us to not do this backport considering how involved the FileUtil changes are.
>
> The issue is that FileUtil has gotten very out of sync between 10.10 and trunk. The reason for this is that we have had to backport changes out of order from trunk to 10.10 for FileUtil(this is because there are few changes in trunk which are not suitable for bacport to 10.10). This makes backport to FileUtil much harder if the FileUtil is touched a lot by a specific checkin in trunk(which is what happened with this jira).
>
> I will label this jira as reject for backport to 10.10

_[comment-14216614](https://issues.apache.org/jira/browse/DERBY-6503?focusedCommentId=14216614&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14216614)_

**Comment by mikecroft** [comment] 2017-07-03 11:33
Hi @AdamBien - taking a closer look at this, I just double-checked myself with `docker run -it payara/server-full:latest /bin/bash` and running `bin/asadmin start-database`; I found that Derby started with no problems.

The Payara docker image is built on top of the official OpenJDK 8 image (`LATEST`) tag, so runs OpenJDK 8u111 on Debian Jessie (rather than CentOS).

I tried to clone airhacks/payara and run that Dockerfile after building locally and found that it also worked without issue. The only difference I see at the moment is that I am using Ubuntu 14.04 LTS as my host OS, rather than MacOS.

Are you running `start-database` interactively or in a script? What's the error I need to look out for?

**Comment by mikecroft** [comment] 2017-07-10 13:41
Hi @AdamBien I still can't reproduce this. I have tried both starting the database interactively and as part of the Dockerfile. Using the following:

```Dockerfile
FROM airhacks/java
MAINTAINER Adam Bien, adam-bien.com
ENV PAYARA_ARCHIVE payara41
ENV DOMAIN_NAME domain1
ENV INSTALL_DIR /
RUN curl -o ${INSTALL_DIR}/${PAYARA_ARCHIVE}.zip -L https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/Payara+4.1.2.172/payara-4.1.2.172.zip \
    && unzip ${INSTALL_DIR}/${PAYARA_ARCHIVE}.zip -d ${INSTALL_DIR} \
    && rm ${INSTALL_DIR}/${PAYARA_ARCHIVE}.zip
ENV PAYARA_HOME ${INSTALL_DIR}/payara41/glassfish
ENV DEPLOYMENT_DIR ${INSTALL_DIR}deploy
RUN mkdir ${DEPLOYMENT_DIR}
WORKDIR ${PAYARA_HOME}/bin
ADD start.sh .
RUN chmod a+x start.sh
RUN ${PAYARA_HOME}/bin/asadmin start-database
EXPOSE 4848 8009 8080 8181
```

I ran `docker build -t test-airhacks/payara .` and it worked perfectly. Can you confirm whether or not you get the same issue using the same Dockerfile? It's only slightly modified from your own, so I expect this may be due to the platform for Docker Engine if you're using macOS and I'm on Ubuntu.

**Comment by mikecroft** [comment] 2017-07-26 07:42
Since we haven't been able to reproduce this, I'll have to close this issue. We are also restricted with the latest version of Docker not running on JDK 7, so an upgrade there isn't feasible. I think the best solution is [the existing workaround](https://github.com/AdamBien/docklands/blob/master/payara-with-derby/Dockerfile)

**Closed by mikecroft** 2017-07-26 07:42 UTC
Labels: 1:Wait, c:PossibleBug, cannot reproduce
