### ISSUE TITLE
Bug Report: slf4j-api does not load an implementation in Payara 6 / FISH-6479

### ISSUE THREAD

**Issue by ajkyffin** [payara/Payara#5898] opened 2022-08-15 12:20 UTC
# Description #
----------

When deploying an application that includes slf4j-api and an implementation, the implementation is not loaded.

## Expected Outcome ##

The slf4j-api included with the application should be loaded and this should then load the included implementation. This is the behaviour in Payara 5.

## Current Outcome ##

The slf4j-api that is loaded is one that is included in Payara, which falls back to the no-operation (NOP) implementation, so there is no logging.

## Steps to reproduce ## 

I have created a testcase here: https://github.com/ajkyffin/slf4j-testcase

It can be built with `mvn package` and deployed with `asadmin deploy target/testcase-1.0.0-SNAPSHOT.war`. The deployment fails because MarkerFactory is not implemented by the NOP implementation and an UnsupportedOperationException is thrown:

```
[2022-08-15T11:37:56.296+0100] [Payara 6.2022.1.Alpha3] [INFO] [AS-EJB-00054] [jakarta.enterprise.ejb.container] [tid: _ThreadID=107 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1660559876296] [levelValue: 800] [[
  Portable JNDI names for EJB Slf4jTestcase: [java:global/testcase-1.0.0-SNAPSHOT/Slf4jTestcase!com.example.testcase.Slf4jTestcase, java:global/testcase-1.0.0-SNAPSHOT/Slf4jTestcase]]]

[2022-08-15T11:37:56.343+0100] [Payara 6.2022.1.Alpha3] [SEVERE] [] [] [tid: _ThreadID=107 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1660559876343] [levelValue: 1000] [[
  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".]]

[2022-08-15T11:37:56.344+0100] [Payara 6.2022.1.Alpha3] [SEVERE] [] [] [tid: _ThreadID=107 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1660559876344] [levelValue: 1000] [[
  SLF4J: Defaulting to no-operation (NOP) logger implementation]]

[2022-08-15T11:37:56.345+0100] [Payara 6.2022.1.Alpha3] [SEVERE] [] [] [tid: _ThreadID=107 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1660559876345] [levelValue: 1000] [[
  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.]]

[2022-08-15T11:37:56.371+0100] [Payara 6.2022.1.Alpha3] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=107 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1660559876371] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbDeployer load method
java.lang.RuntimeException: EJB Container initialization error
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:237)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:286)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:104)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:218)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:334)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:571)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:592)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:409)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:260)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:239)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:179)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ExceptionInInitializerError
	at org.slf4j.MarkerFactory.bwCompatibleGetMarkerFactoryFromBinder(MarkerFactory.java:61)
	at org.slf4j.MarkerFactory.<clinit>(MarkerFactory.java:71)
	at com.example.testcase.Slf4jTestcase.<init>(Slf4jTestcase.java:20)
	at com.example.testcase.__EJB31_Generated__Slf4jTestcase__Intf____Bean__.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at com.sun.ejb.containers.BaseContainer.instantiateOptionalEJBLocalBusinessObjectImpl(BaseContainer.java:3809)
	at com.sun.ejb.containers.StatelessSessionContainer.initializeHome(StatelessSessionContainer.java:216)
	at com.sun.ejb.containers.StatelessContainerFactory.createContainer(StatelessContainerFactory.java:63)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:225)
	... 63 more
Caused by: java.lang.UnsupportedOperationException: This code should never make it into the jar
	at org.slf4j.impl.StaticMarkerBinder.<init>(StaticMarkerBinder.java:51)
	at org.slf4j.impl.StaticMarkerBinder.<clinit>(StaticMarkerBinder.java:48)
	... 76 more
]]
```

I have tried not including slf4j-api in the WAR, and I have tried including a much older version that doesn't throw UnsupportedOperationException, both with the same result. This implies that the slf4j-api that is being loaded is included in Payara, and not the one from the WAR.

## Environment ##

- **Distribution**: Server Full Profile - 6.2022.1.Alpha3
- **JDK Version**: openjdk version "11.0.16" 2022-07-19
- **Operating System**: Debain 11.4 (bullseye)

**Comment by AlanRoth** [comment] 2022-08-15 13:40
Hi @ajkyffin,

Thank you for raising the issue. I have been able to successfully reproduce it and have raised an internal ticket `FISH-6479`.

As always, if you feel confident to contribute to Payara, you may be able to expedite the resolution by submitting your own PR, otherwise the issue will be prioritized and work on accordingly by our dev team.

Best Regards,
Alan

**Comment by ajkyffin** [comment] 2022-09-05 09:32
The slf4j-api that is being loaded comes from the `webservices-extra-xmlsec` module, which exists solely to provide dependencies for the `xmlsec` module.

I have a workaround which is to unzip those 2 modules, move slf4j-api from webservices-extra-xmlsec into xmlsec and edit `MANIFEST.MF` in both modules to remove references to org.slf4j.

Perhaps the fix for this is to just include the dependencies in the xmlsec module?

**Comment by krzysztof-osiecki** [comment] 2022-09-19 09:56
@AlanRoth hi, can we expect this to be resolved in the release version? I just checked on alpha4 and its seems to still be a problem.  
I'm asking because i realize that it may not be the most urgent issue for you at the moment and would like to prepare some workarounds if it is to not be fixed in upcoming release.

**Comment by ajkyffin** [comment] 2022-09-20 14:05
I've written a pom file that rebundles xmlsec along with it's dependencies. It's a replacement for both the `xmlsec` and `webservices-extra-xmlsec` modules. It gets logging working again, although I haven't tested the functionality of the xmlsec module itself.
https://github.com/ajkyffin/xmlsec-rebundled

**Comment by krzysztof-osiecki** [comment] 2022-11-09 12:14
@ajkyffin it works like a charm, however i'm using payara micro for production, is there any way to apply your fix to that?

**Comment by ajkyffin** [comment] 2022-11-09 12:42
@krzysztof-osiecki my testcase works fine in payara micro. I can't find any reference to slf4j in payara micro so the same issue shouldn't occur.

**Comment by krzysztof-osiecki** [comment] 2022-11-09 12:44
Ok, thx ill have to look for mistake somewhere else because logs are not working in my application on micro.

**Comment by lprimak** [comment] 2022-11-21 08:36
same issue

**Comment by lprimak** [comment] 2022-11-22 20:13
**much easier workaround**
You can just turn off class loader delegation, this has been tested and works for this issue:
See https://docs.payara.fish/community/docs/documentation/payara-server/classloading.html

**Closed** 2023-03-10 12:59 UTC
Labels: Status: Accepted, Type: Bug
