### ISSUE TITLE
Is not possible to set virtual server additional properties using docker image / FISH-1012

### ISSUE THREAD

**Issue by silvafabio** [payara/Payara#5078] opened 2020-12-30 14:42 UTC
# Description #
----------

Is not possible to properly set virtual server additional properties using docker image and post-boot-commands.asadmin file.

## Expected Outcome

The value of property should be defined without the quotation marks used to define it.

![payara-admin-gui-expected](https://user-images.githubusercontent.com/3480949/103357216-65966300-4a91-11eb-87e6-1eca8fd78a1d.png)

## Current Outcome

The value of property are including the quotation marks used to define it.

![payara-admin-gui](https://user-images.githubusercontent.com/3480949/103357308-9eced300-4a91-11eb-8545-16a639d24337.png)

If not used quotation marks in the post-boot-commands.asadmin file the last (second image beloow) log error is presented

![payara-docker-log](https://user-images.githubusercontent.com/3480949/103357338-af7f4900-4a91-11eb-8955-454f482ef8c8.png)

The elements in the domain.xml as defined as:

![payara-domain-xml-property](https://user-images.githubusercontent.com/3480949/103358596-b5c2f480-4a94-11eb-8755-a03d4c97c9c0.png)

https://docs.oracle.com/cd/E19798-01/821-1753/auto337/index.html

## Steps to reproduce (Only for bug reports) 

1 -Uncompress the attached file in some directory like /tmp/payara/config/post-boot-commands.asadmin

[post-boot-commands.zip](https://github.com/payara/Payara/files/5754525/post-boot-commands.zip)

2 - Run the docker command
  docker run -v /tmp/payara/config:/opt/payara/config --name payara-test --rm -d -p 8080:8080 -p 4848:4848 payara/server-full:5.2020.7-jdk11

3 - Access the admin gui https://localhost:4848/

4 - Go to "configurations" -> "server-config" -> "Virtual server" -> "server" and roll down to Additional Properties.

## Context (Optional)

Happen in JDK8 and JDK11.

## Environment ##

- **Payara Version**: 5.194 to 5.2020.7 (both 8 and 11)
- **Edition**: Full
- **JDK Version**: container defined
- **Operating System**: Linux

**Comment by AlanRoth** [comment] 2021-01-14 16:00
Hi @silvafabio,

Thank you for the reproducer, I was able to easily reproduce the issue. I have created a internal ticket `FISH-1012`. If you are able, we always encourage community users to contribute a solution, however if you are not able, then our dev team will pick up the issue at some point in the future.

Thank you,
Alan

**Comment by silvafabio** [comment] 2021-01-14 17:05
Hi @AlanRoth .

Sure, could you show me some files to check as a start point?

Thanks

**Comment by AlanRoth** [comment] 2021-01-18 14:29
Hi @silvafabio I'm not sure where you could start, perhaps @Pandrex247 can provide a hint. Thank you.

**Comment by Pandrex247** [comment] 2021-01-18 15:05
Given the presence of spaces in the property it should require the enclosing quotes, particularly since it's being set via the `set` command.

So the `set` command is one place to look to see what input it's actually receiving, here: https://github.com/payara/Payara/blob/master/nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/SetCommand.java

If it isn't reaching there though, another place to look would be the `BootCommands` class, which is where the command file is parsed in and executed: https://github.com/payara/Payara/blob/master/nucleus/core/bootstrap/src/main/java/fish/payara/boot/runtime/BootCommands.java

**Comment by OndroMih** [comment] 2021-06-15 11:23
Hi, @silvafabio, I found out that you're enclosing the value of the virtual server property in quotes. This isn't supported. Instead, you should enclose the whole argument in quotes, like this:

```
set "configs.config.server-config.http-service.virtual-server.server.property.send-error_3=code=404 path=/opt/payara/appserver/glassfish/domains/production/docroot/404.html reason=NOT_FOUND"
```
I tested it and it works and gave the expected results.

In general, you should enclose the whole argument when the value contains spaces. For example, instead of `set property="value with spaces"`, you should write `set "property=value with space". 

Although the comment in [BootCommands.java](https://github.com/payara/Payara/blob/b263fb8b7eab9fee664cd8b0a9457ed3dc96cdd0/nucleus/core/bootstrap/src/main/java/fish/payara/boot/runtime/BootCommands.java#L65) suggests that quotes around values are supported, this is not completely finished. The quotes are not removed from the value, they are passed in the executed command which then leaves them in the value. This doesn't happen if the quotes are around the whole argument. In that case Payara Server removes the quotes before passing the argument to the `set` command. 

If you're interested, you can enhance BootCommands.java to remove the quotes around values and raise a pull request so that this way of using quotes is also supported. I'm closing this issue now. If you'd like to work on it, feel free to reopen it or just raise a pull request.

**Closed by OndroMih** 2021-06-15 11:23 UTC
Labels: Type: Enhancement

**Comment by silvafabio** [comment] 2021-09-23 19:38
Hi @OndroMih.

Long time ;-)

It worked as you proposed, thank you my friend.

I'll find some time to submit a pull request.

Thanks again.
