### ISSUE TITLE
Impossible to configure Hazelcast in Payara Micro

### ISSUE THREAD

**Issue by realulim** [payara/Payara#1542] opened 2017-04-19 09:27 UTC
# Description #
----------
I have found no way to supply a hazelcast config file to Payara Micro. The behavior is different between version 4.1.1.164 and 171. I believe the latter version runs into a bug that has subsequently been fixed in [here](https://github.com/payara/Payara/pull/1514). Therefore I will use 4.1.1.164 for this bug description, but am quite sure that the fixed 4.1.1.171 exhibits the same behavior (I cannot test that, because there has been no newer release).

## Expected Outcome
I expect Payara Micro to read the supplied Hazelcast config file and configure Hazelcast accordingly.

## Current Outcome
The config file is ignored, it can even contain invalid XML, so it's not even parsed. I can even pass a non-existing path to Payara and it won't complain.

## Steps to reproduce (Only for bug reports) 
There are two ways I have tried, both times using the example application under https://github.com/realulim/payara-hazelcast-example

The first way is via the conf/postboot.txt file. Uncomment the "set-hazelcast-configuration" directive and start Payara Micro via java -jar /my/payara-micro.jar --postbootcommandfile ./conf/postboot.txt --deploy target/PayaraHazelcastExample-1.0-SNAPSHOT.war

The application starts up normally, but is running on defaults. There are no complaints the hazelcast config file is missing and the startPort 8084 option is also ignored, the cluster member runs under 5900, which is the default.

The second way I have tried to configure Hazelcast is without the postboot.txt file, but programmatically in the code of my application. In the class ApplicationConfig, there is a method annotated with @PostConstruct. In that method uncomment the lines marked as "not working". Again, my application starts with default settings, despite the fact that I give a path to a Hazelcast config file that does not exist. If I put an existing config file there, its contents are also ignored. Note that the code does get executed in a way, because if I disable Hazelcast by setting "--enabled=false" I am getting the expected exception: "javax.naming.NameNotFoundException: Hazelcast not found".

## Context (Optional)
My guess is that there is a bug in parsing the "command line" to provide the config file to Payara. This appears to be no matter whether the command is read from a postboot.txt file or in the code directly. I believe that once there is an error in any option in the command line, the entire command is silently ignored and Payara starts with default Hazelcast options. I am surmising that because my application starts with default settings, if I use this command line:

set-hazelcast-configuration --enabled=false -f /opt/hazelcast.xml --dynamic=true

Apparently the non-existing /opt/hazelcast.xml causes Payara to silently ignore the entire command and keep the default configuration. Whereas:

set-hazelcast-configuration --enabled=false --dynamic=true

works as expected, i. e. Hazelcast is switched off and my application cannot start.

Please note that even if I supply a working hazelcast.xml, it is not evaluated. I have extracted the hazelcast-default.xml from the Payara Micro jar and disabled multicast in it, but Payara Micro started the cluster with multicasting nonetheless.

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Micro
- **JDK Version**: 1.8
- **Operating System**: Linux

**Comment by mikecroft** [comment] 2017-04-19 09:54
You can always try with the prerelease builds, which contain everything that has been merged to see if the PR you mentioned has resolved the problem.

Have you tested with the `--hzconfigfile` option?

It seems like you're listing a couple of problems here in one issue:

* The `set-hazelcast-configuration` command does not set the Hazelcast configuration
* The `set-hazelcast-configuration` command silently fails if an invalid property is found

The method you're using here is just using an `asadmin` command, so if there is a bug here then it should be in both Server and Micro, hence using `--hzconfigfile` should avoid those issues.

If you have a valid config file, does the rest of the command work? I.e. HZ can be disabled etc?

**Comment by realulim** [comment] 2017-04-19 10:00
Sorry for (potentially) mixing different issues, but I am not familiar enough with Payara to tell these things apart. I'm certainly open to splitting this issue up.

I have not tried the -hzconfigfile option, because I was under the assumption that I'd need an Uber jar, which I do not have. Is there any documentation for this option?

**Comment by mikecroft** [comment] 2017-04-19 10:04
No problem! We can handle any triage/moving around of issues ourselves :-)

We've documented all the command line options here:
https://payara.gitbooks.io/payara-server/content/documentation/payara-micro/appendices/cmd-line-opts.html

but perhaps the best documentation is to use the `--help` option:

```
java -jar payara-micro.jar --help
```

It's been improved in the prerelease builds to make it a bit clearer, so you should get output like this:

```
➜  ~ java -jar /opt/payara/micro/prerelease/payara-micro.jar --help
--accesslog                       <directory-path> Sets user defined directory path for the access log
--accesslogformat                 Sets user defined log format for the access log
--additionalrepository            <repo-url> specifies an additional repository to search for deployable artefacts in
--autobindhttp                    sets autobinding of the http port to a non-bound port
--autobindrange                   <number-of-ports> sets the maximum number of ports to look at for port autobinding
--autobindssl                     sets autobinding of the https port to a non-bound port
...etc...
```

**Comment by realulim** [comment] 2017-04-19 11:04
Ok, I tried that option and it doesn't work either.

**Comment by realulim** [comment] 2017-04-19 14:42
I just thought of a third way to configure Hazelcast, which also failed. I started Payara Micro with the --rootDir parameter, let it extract the domain.xml and then stopped Payara Micro again. Then I edited the domain.xml to change the Hazelcast configuration. However, my changes were reverted on the next start of Payara Micro with that rootDir.

**Comment by smillidge** [comment] 2017-04-20 17:42
I can't reproduce this. I just downloaded 171.1 from the website ran
`java -jar payara-micro-4.1.1.171.1.jar --hzconfigfile ~/temp/hazelcast-default.xml`

and it worked as I changed the start port in the hazelcast-default.xml file from the default.

Payara Micro also shows this log message to show it has configured from the supplied file.

`[2017-04-20T18:38:56.301+0100] [] [INFO] [] [com.hazelcast.config.UrlXmlConfig] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1492709936301] [levelValue: 800] Configuring Hazelcast from 'file:/tmp/payaramicro-rt1827132044106032114tmp/config/hazelcast-default.xml`

**Comment by smillidge** [comment] 2017-04-20 18:14
There is a little peculiarity about the file path for the hazelcast config file if you try to set the file directly using post-boot or pre-boot. The file path is then relative to the config directory of the server. This is behaviour inherited from full server where the file would reside in the domain/config directory to enable replication to instances. Therefore using rootdir and copying in the hazelcast config file into the rootdir/config directory and using a preboot command file with

`set configs.config.server-config.hazelcast-runtime-configuration.hazelcast-configuration-file=hazelcast-default.xml` works.


A Postboot command file using the command
```
set-hazelcast-configuration --enabled=true -f hazelcast.xml --dynamic=true
```

also works on 171.1 IF the file path is relative to the config directory.  However this is very inefficient as Hazelcast will boot then when the above command is ran it will reboot with the new config file. 

I would recommend using --hzconfigfile as it does the right thing and copies your configuration file into the config directory and reqrites the domain.xml to refer to your hazelcast configuration file.

**Comment by realulim** [comment] 2017-04-21 14:13
Without deploying my application, the --hzconfigfile parameter seems to work. Maybe something's wrong with my application, although it seems questionable that it could prevent Payara from configuring Hazelcast. However, since the bug report concerns itself with the postbootfile and programmatic technique, I haven't tested the --hzconfigfile parameter thoroughly, so perhaps the one time I ran it, I missed something and it was working all along.

**Comment by mikecroft** [comment] 2017-05-31 10:07
Closing since this seems like it was a peculiarity with the scenario

**Closed by mikecroft** 2017-05-31 10:07 UTC
Labels: 1:Wait, c:Misconfiguration, cannot reproduce

**Comment by fransflippo** [comment] 2017-08-29 05:44
Can confirm the `--hzconfigfile` command line switch is ignored on 164. Same seems to happen with the `--logToFile` parameter: it still logs to standard out.

The documentation shown when doing `--help` shows the switch as `--hzConfigFile`. Could it be that switches are case sensitive and unknown switches are silently ignored? Will try and find an answer to that.

**Comment by fransflippo** [comment] 2017-08-29 05:45
Can confirm unknown switches are ignored. Started my Uber JAR with the `--pancake` switch (which I'm quite sure is not recognized) but it happily started up.

**Comment by fransflippo** [comment] 2017-08-29 06:14
Started with `--hzConfigFile` and now it's complaining about the XML file, so it seems to be picking it up now.

**Comment by mikecroft** [comment] 2017-08-29 08:37
Switches used to be case sensitive, but are not any longer. Invalid command options are now not silently ignored either. For further queries, please use the Payara Forum.
