### ISSUE TITLE
Application deployment fails on container

### ISSUE THREAD

**Issue by TeroPihlaja** [payara/Payara#3899] opened 2019-04-16 07:51 UTC
# Description #
----------

We are encountering issue with application deployment on Docker.

I believe this is same issue as #1893

## Expected Outcome

Application deployment succeeds.

## Current Outcome

When running Payara **inside a Docker container** (official payara/server-full:latest image or self-built debian:stable + Oracle Java 8u172 + Payara 5.183) the application deployment fails

[server.log](https://github.com/payara/Payara/files/3083493/server.log)

When running with **same** Debian 9, Oracle Java 8u172 and Payara 5.183 versions **inside a VM**, the application deployment succeeds.

## Steps to reproduce (Only for bug reports) 

1 -**  Run payara on Docker from payara/server-full image

2 -** Deploy the example WAR hello-world-with-vaadin-cdi-dependency.war

### Samples

* https://github.com/TeroPihlaja/payara-deployment-test
* https://github.com/TeroPihlaja/payara-deployment-test/raw/master/dist/hello-world-with-vaadin-cdi-dependency.war

## Context (Optional)

At the moment this issue is blocking us from running our applications inside containers.

## Environment ##

- **Payara Version**: 5.183, 5.184, 5.192
- **Edition**: Full
- **JDK Version**: OpenJDK 8u171 and Oracle Java 8u172
- **Operating System**: Debian Linux

**Comment by TeroPihlaja** [comment] 2019-04-18 14:21
@smillidge did you have a look at the instructions for reproducing this issue?

**Comment by smillidge** [comment] 2019-04-18 14:43
apologies you have provided the test case

**Comment by TeroPihlaja** [comment] 2019-06-10 19:57
This seems to be working in Payara Server 5.192 docker image:
```
payara/server-full                                                               latest                                     64c4b8676b82        12 days ago         807MB
```

I have not idea why it works with this one. Do you want to investigate or should we close this issue?

**Comment by smillidge** [comment] 2019-06-16 20:51
I'll close the issue we don't maintain older version images. Thanks for letting us know.

**Comment by TeroPihlaja** [comment] 2019-08-07 19:19
@smillidge Can we re-open this issue. I seem to be able to reproduce this again with 5.192 docker image.

I think my successful test was done on a different docker host (which might or might not have caused the difference in result).

Attached log is from the same container hash 64c4b8676b82 and the same war-file from the first comment.

Docker inspect:
[inspect.txt](https://github.com/payara/Payara/files/3478565/inspect.txt)

[payara-docker-issue.log](https://github.com/payara/Payara/files/3478543/payara-docker-issue.log)

**Comment by smillidge** [comment] 2019-08-07 20:22
OK done

**Comment by Aketzu** [comment] 2019-08-19 13:56
Now same thing happens in Debian 10 virtual machine with AdoptOpenJDK 1.8.0_222 and Payara 5.192

**Comment by Aketzu** [comment] 2019-08-19 14:49
One fix/workaround is to update deltaspike. In the example .war above vaadin-cdi 2.0.0 dependency pulls in deltaspike 1.7.2.

If I manually add dependency for deltaspike 1.8.0 then the example file deploys normally.
```xml
    <dependency>
      <groupId>org.apache.deltaspike.core</groupId>
      <artifactId>deltaspike-core-api</artifactId>
      <version>1.8.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.deltaspike.core</groupId>
      <artifactId>deltaspike-core-impl</artifactId>
      <version>1.8.0</version>
    </dependency>
```

Deltaspike changelog: 
https://git-wip-us.apache.org/repos/asf?p=deltaspike.git;a=shortlog;h=9a371a22ca48d2acb287722e7de522e75eae0e92

**Comment by smillidge** [comment] 2019-10-26 21:08
So is this a DeltaSpike issue?

**Comment by ylupol** [comment] 2019-10-31 16:02
Can be reproduced on the environment:
* Mac OS 10.15.1
* OpenJDK 1.8.0_222
* Payara Server 4.1.1.171.1 #badassfish (build 139)

however deployment went fine on:
* Mac OS 10.11
* Oracle JDK 8u66
* Payara Server 4.1.1.171.1 #badassfish (build 139) `(the same version)`

OS & JDK combination is suspected to be the cause.

**Comment by rdebusscher** [comment] 2020-01-03 10:16
Confirmed with 5.194

- Deployment on DAS outside Docker  (Vaadin + DS 1.7.2) -> Success
- Deployment on Docker (Vaadin + DS 1.7.2)-> Fails
- Deployment on Docker (Vaadin + DS 1.8.0) -> Success
- Deployment on Docker (DS 1.7.2 only) -> Success

Closing as this somehow seems a DS issue in combination with Vaadin.

Regards
Rudy

**Closed by rdebusscher** 2020-01-03 10:16 UTC
Labels: try to reproduce
