### ISSUE TITLE
Admin console: Missing the ALL log level

### ISSUE THREAD

**Issue by z-mathe** [payara/Payara#1743] opened 2017-07-03 17:53 UTC
# Description #
----------

There are some properties in payaradomain template with the level **ALL** (if I know well, it is not deprecated yet, we also use some settings from our earlier versions):

logging.properties (e.g. from payaradomain folder):
```
com.sun.enterprise.server.logging.GFFileHandler.level=ALL
com.sun.enterprise.server.logging.SyslogHandler.level=ALL
```
## Expected Outcome

After starting the server, it should be selectable the **ALL** level as well on the GUI from the dropdown controls. What's more, the stored value should be read back.

## Current Outcome

Because the **ALL** level is missing from the list, the "Module Log Levels" form automatically change these levels to **OFF**. This is very deceptive if someone presses the "Save" button while setting another feature. We've also noticed that it just stopped logging the system completely, until we turned it back to **ALL**.

![image](https://user-images.githubusercontent.com/28045201/27803210-a4257db0-6028-11e7-8564-df405d3d1090.png)

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: Full
- **JDK Version**: 8 u131 - Oracle
- **Operating System**: Windows

**Comment by smillidge** [comment] 2017-07-03 18:16
Duplicate of #1680 this will be fixed in 173.

**Closed by smillidge** 2017-07-03 18:16 UTC
