### ISSUE TITLE
No logging after upgrade from 4.1.2.174 to 181

### ISSUE THREAD

**Issue by berniegsfc** [payara/Payara#2400] opened 2018-02-14 17:21 UTC
# Description #
----------
After upgrading (domain-backup, domain-restore) from 174 to 181, the server.log only has the java command option message and nothing else.  When I go to the admin server-config/logger settings and check "log to file", I get the error "For input string: "null" Invalid logging attribute name or value fish.payara.enterprise.server.logging.PayaraNotificationFileHandler.rotationTimelimitInMinutes=null."

## Expected Outcome

I expected logging to work as it did in the previous release.

## Current Outcome

server.log is empty except for the initial java command option message.

## Steps to reproduce (Only for bug reports) 

$ 174/payara41/glassfish/bin/asadmin backup-domain spdf
$ 181/payara41/glassfish/bin/asadmin restore-domain --filename 174/payara41/glassfish/domains/spdf/backups/spdf_date_v00001.zip spdf
$ 181/payara41/glassfish/bin/asadmin start-domain spdf
$ cat 181/payara41/glassfish/domains/spdf/logs/server.log
[2018-02-14T06:51:37.856-0500] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1518609097856] [levelValue: 800] [[  JVM invocation command line:/usr/jdk1.8.0_162/bin/java
-cp
/home/bharris/opt/payara/181/payara41/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-XX:MaxPermSize=192m
-Xmx768m
-server
-javaagent:/home/bharris/opt/payara/181/payara41/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/home/bharris/opt/payara/181/payara41/glassfish/domains/spdf/config/cacerts.jks
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/home/bharris/opt/payara/181/payara41/glassfish/modules/autostart/
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=/home/bharris/opt/payara/181/payara41/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.endorsed.dirs=/home/bharris/opt/payara/181/payara41/glassfish/modules/endorsed:/home/bharris/opt/payara/181/payara41/glassfish/lib/endorsed
-Djava.security.policy=/home/bharris/opt/payara/181/payara41/glassfish/domains/spdf/config/server.policy
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.bundles.startTransient=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfelix.fileinstall.log.level=2
-Djavax.net.ssl.keyStore=/home/bharris/opt/payara/181/payara41/glassfish/domains/spdf/config/keystore.jks
-Djava.security.auth.login.config=/home/bharris/opt/payara/181/payara41/glassfish/domains/spdf/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Dproduct.name
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/home/bharris/opt/payara/181/payara41/glassfish/domains/spdf
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dosgi.shell.telnet.ip=127.0.0.1
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=/usr/jdk1.8.0_162/lib/ext:/usr/jdk1.8.0_162/jre/lib/ext:/home/bharris/opt/payara/181/payara41/glassfish/domains/spdf/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djava.library.path=/home/bharris/opt/payara/181/payara41/glassfish/lib:/usr/local/cdf36_4/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/home/bharris/opt/payara/181/payara41/glassfish/domains/spdf
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/home/bharris/opt/payara/181/payara41/glassfish/domains,,,spdf
-domainname
spdf
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/home/bharris/opt/payara/181/payara41/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false]]

## Environment ##

- **Payara Version**: 4.1.1.181
- **Edition**:  Full
- **JDK Version**:  1.8.0_162 - Oracle
- **Operating System**: RHEL 6.9
- **Database**: None

**Comment by smillidge** [comment] 2018-02-15 12:13
Does this happen on a clean new 4.181 domain?

**Comment by berniegsfc** [comment] 2018-02-15 12:16
No, the problem only occurs with an "upgrade" (backup-domain, restore-domain).

**Comment by smillidge** [comment] 2018-02-15 14:14
OK we have reproduced this and it is due to missing properties in the logging.properties for the Notification logger.

**Comment by smillidge** [comment] 2018-03-05 15:15
Fixed by #2449

**Closed by smillidge** 2018-03-05 15:15 UTC
Labels: 2:WithDev, c:ConfirmedBug

**Comment by evanzel** [comment] 2018-03-07 07:48
Hi, should we expect a release in the Payara 4 Community Stream with this fix?

**Comment by makadizsolt** [comment] 2018-03-08 10:29
Replacing the /payara41/glassfish/domains/domain1/config/logging.properties file with the original one from the 181 installer zip (after restoring but before starting the domain) solved the problem for me. But I use server logging in the default mode, so it's just a workaround if the default settings suffice.

**Comment by smillidge** [comment] 2018-03-08 11:23
You can also add the missing properties manually to your logging.properties.
The next release on community stream will be 5.181 see http://blog.payara.fish/payara-5-and-payara-4-development-changes

**Comment by evanzel** [comment] 2018-03-08 12:12
Thanks, the above was indeed enough as a fix.
