### ISSUE TITLE
is it possible to setup a user to deploy with less than asadmin permissions?

### ISSUE THREAD

**Issue by dhubbard-ag** [payara/Payara#3744] opened 2019-02-19 09:51 UTC
I raised a question in [ServerFault](https://serverfault.com/questions/951290/in-glassfish-4-1-is-it-possible-to-setup-a-deploy-user-which-has-less-than-asadm) which I'm hoping someone here can assist with.

Is there any finer granularity of permissions out of the box in Glassfish other than asadmin group that would allow deploy? or is there any way to setup a new group with required permissions?

**Comment by rdebusscher** [comment] 2019-02-20 14:11
Hi,

To my knowledge, this is not available in GlassFish and we have an open development task for this within Payara.

See also https://github.com/payara/Payara/issues/1600

**Comment by dhubbard-ag** [comment] 2019-02-20 14:31
Thanks @rdebusscher - I've subscribed to that - I guess as that is over 18 months old I won't depend on it.

**Comment by rdebusscher** [comment] 2019-02-20 16:08
When this is an important feature for you, you can always consider Payara Support through [Payara Enterprise](https://www.payara.fish/support/). Enhancements request filed by Payara Customers have higher priority.

**Comment by OndroMih** [comment] 2019-03-14 09:35
I'm closing this as this is a duplicate of #1600. We have plans to add this feature but it's not currently in the roadmap. Honestly, there's a very small chance that we'll add this feature in a near future unless our support customers request it or the community contributes it.

**Closed by OndroMih** 2019-03-14 09:35 UTC
Labels: 2:WithDev, c:Enhancement
