### ISSUE TITLE
MicroConfig is not resolved in JSP /CUSTCOM-92

### ISSUE THREAD

**Issue by jeyvison** [payara/Payara#2817] opened 2018-06-04 19:11 UTC
# Description #
----------
Hello Folks, I'm trying to use MicroProfile(Especifically MicroConfig) in JSP using Payara Full.

This is how my **build.gradle** file looks like:

```
plugins {
    id 'java'
    id 'war'
}

group 'testPayara'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    providedCompile 'org.eclipse.microprofile:microprofile:1.2'
    providedCompile group: 'javax', name: 'javaee-api', version: '8.0'

}
```

My **JSP**:
```

<%@ page import="org.eclipse.microprofile.config.ConfigProvider" %><%--
  Created by IntelliJ IDEA.
  User: jeyvison
  Date: 1/6/18
  Time: 17:18
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
  <head>
    <title>$Title$</title>
  </head>
  Hello

  <%=ConfigProvider.getConfig().getValue("teste", Integer.class)%>
  </body>
</html>
```

My **microprofile-config.properties**

`teste=10`

## Expected Outcome

The JSP should show **Hello 10** in the browser

## Current Outcome

The JSP shows me the following error:

```
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP

PWC6199: Generated servlet error:
package org.eclipse.microprofile.config does not exist

PWC6197: An error occurred at line: 15 in the jsp file: /index.jsp
PWC6199: Generated servlet error:
cannot find symbol
  symbol:   variable ConfigProvider
  location: class org.apache.jsp.index_jsp 
```

## Steps to reproduce (Only for bug reports) 

Run the attached sample and acesse the following URL:

**http://localhost:8080/testPayara-1.0-SNAPSHOT/**

### Samples

See Sample [here](https://drive.google.com/file/d/1dfMmb3n8UeqxdvCTYGzrICngeDYxJ5Cc/view?usp=sharing)

## Context (Optional)

The code `ConfigProvider.getConfig().getValue("teste", Integer.class)` works in Java classes. The problem is the JSP.

## Environment ##

- **Payara Version**: 5.181
- **Edition**: Full
- **JDK Version**: 1.8.0_171 Oracle
- **Operating System**: MacOS
- **Database**: Oracle

**Comment by OndrejM** [comment] 2018-06-20 14:22
Thanks for raising this issue. Unfortunately JSP classloading is underspecified and the MP Config API isn't available in the classpath when the JSP is evaluated.

Can you work around this issue if you create a Java class that calls `ConfigProvider` and you use that class in your JSP? In other words, can you wrap calling `ConfigProvider` into another Java class that's called from the JSP?

**Comment by smillidge** [comment] 2018-06-20 16:24
I think the problem is the upstream JSP compiler builds a classpath on the fly to feed into Javac so this will need a fix in the RI JSP compiler

**Comment by rdebusscher** [comment] 2019-12-17 11:00
Created internal issue `CUSTCOM-92`.

**Comment by AlanRoth** [comment] 2020-11-11 11:18
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:18 UTC
Labels: enhancement, status:accepted, upstream bug
