### ISSUE TITLE
Asadmin Recorder: JavaMail Session entry is recorded with host and user /CUSTCOM-94

### ISSUE THREAD

**Issue by sponiro** [payara/Payara#2920] opened 2018-07-03 06:33 UTC
# Description #
----------

Recording a JavaMail Session entry with Asadmin Recorder creates a bad recording. The resulting create-javamail-resource command contains --host and --user parameters which when used with asadmin raise an error on the console. 

## Expected Outcome

The produced command should use --mailhost and --mailuser.

## Current Outcome

The produced command uses --host and --user.

## Steps to reproduce (Only for bug reports) 

Enable Asadmin Recorder and create a new JavaMail Session entry. Look up the recorded command for create-javamail-resource. It contains --host and --user

## Environment ##

- **Payara Version**: 4.1.2.181 
- **Edition**: Full
- **Operating System**: Linux

**Comment by rdebusscher** [comment] 2019-12-17 13:27
Created issue `CUSTCOM-94`

**Comment by AlanRoth** [comment] 2020-11-11 11:21
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.

**Closed by AlanRoth** 2020-11-11 11:21 UTC
Labels: status:accepted
