### ISSUE TITLE
Glassfish && Payara validates @PostConstruct even with CDI disabled

### ISSUE THREAD

**Issue by OndroMih** [payara/Payara#663] opened 2016-02-16 09:47 UTC
[A question on SO](http://stackoverflow.com/questions/35411854/glassfish-4-scans-for-postconstruct-with-cdi-disabled/35428512#35428512) describes this issue: Glassfish validates method with `@PostConstruct` annotation even when CDI is disabled (by turning off implicit scanning for CDI beans via Glassfish config). The application used to work on Glassfish 3 with Spring - it seems there is less strict validation on post-construct methods in Spring.

I wanted to know if Payara can alleviate the constraints and disable validations when bean is not used for DI. I went to the source code to find out what is forcing the validations.

According to source code (in both Glassfish and Payara), @PostContruct annotation handler [PostConstructHandler](https://github.com/payara/Payara/blob/8a403bf75d3734e564a9fb95d60498987cc4287e/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/handlers/PostConstructHandler.java#L72) validates the annotated method before any resourceContainerContext is processed, possible even when there is no context in the list.

I want to try to reproduce this and debug the code to find out, if it is possible to postpone validation until the first context is processed, skipping the validation if there is no context due to CDI implicit scanning disabled. If I find out that there is not easy fix to this problem, I will close this issue, as it is not so important and in line with Javadoc documentation of [@PostConstruct](http://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html)

**Comment by OndrejM** [comment] 2016-03-07 14:19
Test application created: https://github.com/OndrejM-Payara-support/Payara-663

**Comment by OndrejM** [comment] 2016-03-08 13:47
It seems that it is not easy to fix, as classes are always scanned for annotations, the information about them is stored in a metadata registry, and only if needed, the metadata registry is used by particular JavaEE mechanism. The problem is that the validation happens during the scanning process, which is always triggered. To change this behavior, it would require to move validation to later phases, which is not trivial and woud need to be done for other annotations too.

**Comment by OndrejM** [comment] 2016-03-08 13:52
Developers, please label as either Enhancement or Wontfix, depending on whether you think it makes sense to improve the current behavior. If there is no specific need, I think it is not worth the effort to improve current behavior.

**Comment by mikecroft** [comment] 2016-08-16 08:14
I couldn't find any internal issue for this yet, so I've created `PAYARA-1000` as a minor enhancement

**Closed** 2019-02-02 23:01 UTC
Labels: wontfix
